version "3.7.2"

#include "brootol_dumb_z/sfx/sfx_main.zc"
#include "brootol_dumb_z/sfx/sfx_base.zc"
#include "brootol_dumb_z/sfx/sfx_states.zc"

//sfx
#include "brootol_dumb_z/sfx/SMOKE.zc"
#include "brootol_dumb_z/sfx/CASING.zc"
#include "brootol_dumb_z/sfx/FIRE.zc"
#include "brootol_dumb_z/sfx/SPARKS.zc"
#include "brootol_dumb_z/sfx/FLARES.zc"
#include "brootol_dumb_z/sfx/PUFF.zc"

#include "brootol_dumb_z/sfx/PARTICLES.zc"


//Guns Guns Guns
#include "brootol_dumb_z/weapons/MELEE.zc"
#include "brootol_dumb_z/weapons/SAW.zc"
#include "brootol_dumb_z/weapons/RIFLE.zc"
#include "brootol_dumb_z/weapons/SHOTGUN.zc"
#include "brootol_dumb_z/weapons/SSG.zc"
#include "brootol_dumb_z/weapons/MINIGUN.zc"
#include "brootol_dumb_z/weapons/ROCKETLAUNCHER.zc"
#include "brootol_dumb_z/weapons/PLASMA.zc"
#include "brootol_dumb_z/weapons/BFG.zc"
#include "brootol_dumb_z/weapons/Grenades.zc"

#include "brootol_dumb_z/weapons/STGRENADELAUNCH.zc"
#include "brootol_dumb_z/weapons/STBFG10k.zc"
#include "brootol_dumb_z/weapons/STRAILGUN.zc"


//Gore N' Blood
#include "brootol_dumb_z/gore/GORE!!!.zc"
#include "brootol_dumb_z/gore/GORE2.zc"
#include "brootol_dumb_z/gore/GORE3.zc"
#include "brootol_dumb_z/gore/BLOOD.zc"
#include "brootol_dumb_z/gore/BLOODSPLASH.zc"
#include "brootol_dumb_z/gore/BURN.zc"


//DECORATIONS
#include "brootol_dumb_z/decor/FURNITURE.zc"
#include "brootol_dumb_z/decor/LAMPS.zc"
#include "brootol_dumb_z/decor/NATURAL.zc"
#include "brootol_dumb_z/decor/FIREWORKS.zc"
#include "brootol_dumb_z/decor/TORCHES.zc"
#include "brootol_dumb_z/decor/DEAD.zc"


#include "brootol_dumb_z/actors_dump/EXPLOSIVES.zc"
#include "brootol_dumb_z/actors_dump/DROPABLES.zc"

//,onsters base must go before gore
//because gore base inherits from monster base
#include "brootol_dumb_z/monsters/monster_base.zc"

#include "brootol_dumb_z/gore/gore_base.zc"


#include "brootol_dumb_z/weapons/weapon_base.zc"
#include "brootol_dumb_z/weapons/ammo/AMMO.zc"


#include "brootol_dumb_z/base_definitions.zc"


/*
check difficlty
G_SkillPropertyInt(SKILLP_ACSReturn)
set acsreturn value in sklil definition
*/



class debugger : eventhandler
{
array <string> destroyed;
array <int> ammount;

override void worldthingdestroyed(worldevent e)
{
    string s = e.thing.getclassname();
    int i = destroyed.find(s);
    if( i == destroyed.size() )
    {
        destroyed.push(s);
        ammount.push(1);
    }

    else
        ammount[i]++;
}

uint timer;
override void worldtick()
{
    timer++;

    if(timer == 35)
    {
        timer = 0;
        for(uint i = 0; i < destroyed.size(); i++)
        {
            console.printf("");
            console.printf("%i %s was destroyed in last second", ammount[i], destroyed[i] );
            ammount.delete(i);
            destroyed.delete(i);
        }
    }
}

}

