version "3.7.2"

// IF YOU WANT TO USE STUFF FROM THIS MOD, GIVE ME CREDITS

//Ok
//Change my mind after millions of "tnt1 aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa 0"
//Or not









CLASS FallingHeight : Inventory { 
	Default {
		
		inventory.maxamount 100;
	}
}




//monsters base must go before gore
//because gore base inherits from monster base
#include "brootol_dumb_z/monsters/monster_base.zc"
#include "brootol_dumb_z/gore/bodies/gore_base.zc"
#include "brootol_dumb_z/weapons/weapon_base.zc"
#include "brootol_dumb_z/weapons/weapon_dual_base.zc"

#include "brootol_dumb_z/sfx/sfx_main.zc"
#include "brootol_dumb_z/sfx/sfx_base.zc"
#include "brootol_dumb_z/sfx/sfx_states.zc"

//sfx
#include "brootol_dumb_z/sfx/model_dummies.zc"
#include "brootol_dumb_z/sfx/SPARKS.zc"

#include "brootol_dumb_z/sfx/FLARES.zc"
#include "brootol_dumb_z/sfx/PUFF.zc"
#include "brootol_dumb_z/sfx/PARTICLES.zc"

#include "brootol_dumb_z/sfx/CASING.zc"

//Guns Guns Guns
#include "brootol_dumb_z/weapons/MELEE.zc"
#include "brootol_dumb_z/weapons/SAW.zc"
#include "brootol_dumb_z/weapons/RIFLE.zc"
#include "brootol_dumb_z/weapons/SHOTGUN.zc"
#include "brootol_dumb_z/weapons/SSG.zc"
#include "brootol_dumb_z/weapons/MINIGUN.zc"
#include "brootol_dumb_z/weapons/ROCKETLAUNCHER.zc"
#include "brootol_dumb_z/weapons/PLASMA.zc"
#include "brootol_dumb_z/weapons/BFG.zc"
#include "brootol_dumb_z/weapons/Grenades.zc"

#include "brootol_dumb_z/weapons/STGRENADELAUNCH.zc"
#include "brootol_dumb_z/weapons/STBFG10k.zc"
#include "brootol_dumb_z/weapons/STRAILGUN.zc"

#include "brootol_dumb_z/weapons/DUALRIFLE.zc"
#include "brootol_dumb_z/weapons/DUALPLASMA.zc"
#include "brootol_dumb_z/weapons/IMPSHIELD.zc"
#include "brootol_dumb_z/weapons/ZMANSHIELD.zc"
#include "brootol_dumb_z/weapons/SGUYSHIELD.zc"
#include "brootol_dumb_z/weapons/MP40.zc"
#include "brootol_dumb_z/weapons/EXTRA.zc"


//items
#include "brootol_dumb_z/items/ARTIFACT.zc"
#include "brootol_dumb_z/items/HEALTH2.zc"


//Gore N' Blood
#include "brootol_dumb_z/gore/gore_event.zc"
#include "brootol_dumb_z/gore/blood_pools.zc"
#include "brootol_dumb_z/gore/gore_fixed.zc"

#include "brootol_dumb_z/gore/BLOOD/BLOOD_base.zc"
#include "brootol_dumb_z/gore/BLOOD/BLOOD.zc"

#include "brootol_dumb_z/gore/GORE!!!.zc"
#include "brootol_dumb_z/gore/GORE!!!.zc"

#include "brootol_dumb_z/gore/GORE!!!.zc"
#include "brootol_dumb_z/gore/GORE2.zc"
#include "brootol_dumb_z/gore/GORE3.zc"
#include "brootol_dumb_z/gore/BLOOD/BLOOD.zc"
#include "brootol_dumb_z/gore/BLOODSPLASH.zc"
#include "brootol_dumb_z/gore/blueblood.zc"
#include "brootol_dumb_z/gore/greenblood.zc"
#include "brootol_dumb_z/gore/underwaterblood.zc"


//DECORATIONS
#include "brootol_dumb_z/decor/decoration_base.zc"
#include "brootol_dumb_z/decor/FURNITURE.zc"
#include "brootol_dumb_z/decor/LAMPS.zc"
#include "brootol_dumb_z/decor/NATURAL.zc"
#include "brootol_dumb_z/decor/FIREWORKS.zc"
#include "brootol_dumb_z/decor/lighting/TORCHES.zc"
#include "brootol_dumb_z/decor/lighting/barrels.zc"

#include "brootol_dumb_z/decor/DEAD.zc"


#include "brootol_dumb_z/weapons/ammo/AMMO.zc"


#include "brootol_dumb_z/base_definitions.zc"

#include "brootol_dumb_z/monsters/ZOMBIEMEN/ZOMBIEMEN.zc"
#include "brootol_dumb_z/monsters/ZOMBIEMEN/ZOMB_gore.zc"

#include "brootol_dumb_z/monsters/shotgunner/SERGEANTS.zc"
#include "brootol_dumb_z/monsters/shotgunner/SERG_gore.zc"

#include "brootol_dumb_z/monsters/COMmANDO/COMANDO.zc"
#include "brootol_dumb_z/monsters/COMmANDO/COMmANDO_gore.zc"

#include "brootol_dumb_z/monsters/IMP/IMP.zc"
#include "brootol_dumb_z/monsters/IMP/IMP_gore.zc"

#include "brootol_dumb_z/monsters/DEMON/DEMON.zc"
#include "brootol_dumb_z/monsters/DEMON/DEMON_gore.zc"

#include "brootol_dumb_z/monsters/SPECTRE.zc"

#include "brootol_dumb_z/monsters/KNIGHT/KNIGHT.zc"
#include "brootol_dumb_z/monsters/KNIGHT/KNIGHT_gore.zc"

#include "brootol_dumb_z/monsters/BARON/BARON.zc"
#include "brootol_dumb_z/monsters/BARON/BARON_gore.zc"

#include "brootol_dumb_z/monsters/CACODEMOn/CACODEMOn.zc"
#include "brootol_dumb_z/monsters/CACODEMOn/CACODEMOn_gore.zc"

#include "brootol_dumb_z/monsters/SPIDER/SPIDER.zc"
#include "brootol_dumb_z/monsters/SPIDER/SPIDER_gore.zc"

#include "brootol_dumb_z/monsters/REVENANT/REVENANT.zc"
#include "brootol_dumb_z/monsters/REVENANT/REVENANT_gore.zc"

#include "brootol_dumb_z/monsters/mancubus/mancubus.zc"
#include "brootol_dumb_z/monsters/mancubus/mancubus_gore.zc"

#include "brootol_dumb_z/monsters/PAIN/PAIN.zc"
#include "brootol_dumb_z/monsters/PAIN/PAIN_gore.zc"

//ready
#include "brootol_dumb_z/monsters/archvile/ARCHVILE.zc"
#include "brootol_dumb_z/monsters/archvile/ARCH_gore.zc"

#include "brootol_dumb_z/monsters/LOSTSOUL/LOSTSOUL.zc"

#include "brootol_dumb_z/monsters/bosses/CYBERDEMON.zc"
#include "brootol_dumb_z/monsters/bosses/cyber_gore.zc"
#include "brootol_dumb_z/monsters/bosses/MASTERMIND.zc"
#include "brootol_dumb_z/monsters/bosses/SpecialDoom1Boses.zc"

#include "brootol_dumb_z/monsters/NAZIS.zc"
#include "brootol_dumb_z/monsters/BELPHEGOR.zc"
#include "brootol_dumb_z/monsters/JUGGERNAUT.zc"
#include "brootol_dumb_z/monsters/EEEVILLL.zc"




#include "brootol_dumb_z/player/proto_PLAYER.zc"
#include "brootol_dumb_z/player/PLAYER.zc"

#include "brootol_dumb_z/marines/marine_base.zc"
#include "brootol_dumb_z/marines/marines.zc"
#include "brootol_dumb_z/marines/capturedmarine.zc"
#include "brootol_dumb_z/marines/BFGmarine.zc"
#include "brootol_dumb_z/marines/chaingunmarine.zc"
#include "brootol_dumb_z/marines/plasmagunmarine.zc"
#include "brootol_dumb_z/marines/rocketlaunchermarine.zc"
#include "brootol_dumb_z/marines/shotgunmarine.zc"



/*
check difficlty
G_SkillPropertyInt(SKILLP_ACSReturn)
set acsreturn value in sklil definition
*/

#include "brootol_dumb_z/actors_dump/bossbrain.zc"
#include "brootol_dumb_z/actors_dump/bossbrain.zc"
#include "brootol_dumb_z/actors_dump/epic2stuff.zc"
#include "brootol_dumb_z/actors_dump/stealthmonsters.zc"
#include "brootol_dumb_z/actors_dump/teleport.zc"
#include "brootol_dumb_z/actors_dump/water.zc"
#include "brootol_dumb_z/actors_dump/TRACERS.zc"
#include "brootol_dumb_z/actors_dump/BrutalChexQuest.zc"

//third party dependencies
//gutawewr zforms
#include "third_party_library/doomb_ZForms/Include.zsc"





class debugger : eventhandler
{
array <string> destroyed;
array <int> ammount;

override void worldthingdestroyed(worldevent e)
{
    if(!doomb_debug) return;
    
    string s = e.thing.getclassname();
    int i = destroyed.find(s);
    if( i == destroyed.size() )
    {
        destroyed.push(s);
        ammount.push(1);
    }

    else
        ammount[i]++;
}

uint timer;
override void worldtick()
{
    timer++;

    if(timer == 35)
    {
        timer = 0;
        if(doomb_debug)
            for(uint i = 0; i < destroyed.size(); i++)
            {
                console.printf("");
                console.printf("%i %s was destroyed in last second", ammount[i], destroyed[i] );
                ammount.delete(i);
                destroyed.delete(i);
            }
    }
}

}