//All the liquid gore stuff goes here.

//cause slowdown
CLASS TinyBlood : doomb_blood { 
	Default {
		scale 0.2;
		speed 7;
		health 1;
		radius 8;
		height 1;
		+DontSplash;
		Gravity 0.7;
		Decal "BrutalBloodSplat";
		XScale 0.4;
		YScale 0.8;
		+MISSILE;
		+CLIENTSIDEONLY;
		+NOTELEPORT;
		+NOBLOCKMAP;
		+FORCEXYBILLBOARD;
		-EXPLODEONWATER;
		+DOOMBOUNCE;
	}
	States
	{
		Spawn:
			tnt1 a 0 nodelay {scale *= frandom(0.8, 1.2);}
		mini:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			BLUD Z 1
			{
				if(pos.z <= floorz)
					setstatelabel("death");
			}
		loop;
			
		Splash:
			TNT1 A 0 A_SpawnProjectile ("Underblood1", 7, 0, random (0, 360), 2, - random (30, 150));
		stop;

		Death:
			TNT1 A 0 A_PlaySound("blooddrop3");
			XDT1 EFGHIJKL 2;
			TNT1 A 0 A_SpawnItem("MediumBloodSpot");
		stop;
	}
}











CLASS Brutal_Blood : doomb_blood Replaces Blood { 
	Default {
		Decal "BrutalBloodSplat";
		+FORCEXYBILLBOARD;
		+NOGRAVITY;
		+THRUACTORS;
		+CLIENTSIDEONLY;
		Scale 0.5;
		Speed 0;
	}
	states
	{
		Spawn:
			TNT1 A 0 nodelay A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 0 doomb_spawn_blood();
		Splash:
			tnt1 A 0 { vel = ( random(-3, 3), random(-3, 3), random(-3, 3));}
			BSP4 ABCDEFGHIJKLMNOPQRSTUVWXYZ 2;
		stop;
	}
	
}

CLASS BloodHit : ACTOR { 
	Default {
		height 8;
		radius 4;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOCLIP;
		+CLIENTSIDEONLY;
		Scale 0.7;
	}
	states
	{
		Spawn:
			BLHT ABCDE 1;
			Stop;
	}
}







CLASS Brutal_FlyingBlood : Brutal_Blood { 
	Default {
		scale 0.5;
		speed 10;
		health 1;
		radius 8;
		height 1;
		Gravity 0.8;
		damage 0;
		Renderstyle "Translucent";
		Alpha 0.95;
		damagetype "Blood";
		Decal "BrutalBloodSuper";
		+MISSILE;
		-nogravity
		+CLIENTSIDEONLY;
		+NOTELEPORT;
		+NOBLOCKMAP;
		+THRUACTORS;
		+BLOODLESSIMPACT;
		+FORCEXYBILLBOARD;
		+NODAMAGETHRUST;
		+MOVEWITHSECTOR;
		+CORPSE;
		-DONTSPLASH;
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay A_ScaleVelocity(frandom(1, 1.8));
			BLOD AB 2 A_JumpIf(waterlevel > 1, "Splash");
			tnt1 a 0 {frame = randompick(2, 4);}
		Spawn2:
			BLOD "#" 1 A_JumpIf(waterlevel > 1, "Splash");
		loop;
			
		Death:
			TNT1 A 0 A_PlaySound("blooddrop2");
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_SpawnItemEx ("CeilBloodLauncher",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
	}
}


CLASS Brutal_BloodSpot : ACTOR { 
	Default {
		radius 2;
		height 2;
		mass 1;
		Health 300;
		+NOTELEPORT;
		+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
		+MOVEWITHSECTOR;
		+FLOORCLIP;
		+NOTARGET;
		-SHOOTABLE;
		+NOBLOOD;
		-DONTSPLASH;
		-SOLID;
		+THRUACTORS;
		Alpha 0.9;
		Mass 99999999;
		Scale 0.5;
		Decal "BrutalBloodSplat";
		DamageFactor "TeleportRemover", 100.0;
	}
	states
	{
			BPDL A 800;//duration
		Spawn:
			TNT1 A 0 nodelay{frame = random(0, 3);}
		SpawnAFrameOnly:
			BPDL "#" 800;//duration
			BPDL "#" 1 A_FadeOut(0.05);
		wait;
	}
}


CLASS GiantBloodSpot: Brutal_BloodSpot { 
	Default {
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx ("BootSmearerRed",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 2;
			Goto super::spawn;
	}
}




CLASS BigBloodSpot: GiantBloodSpot { 
	Default {
		
		Scale 0.7;
	}
}



CLASS MediumBloodSpot: GiantBloodSpot { 
	Default {
		
		Scale 0.4;
	}
}

CLASS SmallBloodPool2 : MediumBloodSpot Replaces SmallBloodPool {}


CLASS CeilBloodLauncher: Brutal_FLyingBlood  { 
	Default {
		
		+THRUACTORS;
		+BLOODLESSIMPACT;
		-DOOMBOUNCE;
		damagetype "Blood";
		Speed 15;
		Gravity 0.0;
		Decal "BrutalBloodSplat";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "null");
			TNT1 A 3 a_settics(random(3, 12) );
			Stop;
		Death:
			BPDL A 1 A_SpawnItem ("DripingBloodLeavesSmallPool");
			bpdl AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1
			{
				a_settics(random(5, 24) );
				A_SpawnItemEx ("TinyBlood", frandom (-5, 5), frandom (-5, 5));
			}
			BPDL AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 2;
			BPDL AAAAAAAAA 1 A_FadeOut(0.1);
		stop;
		
		death:
		Stop;
	}
}

CLASS DripingBloodLeavesSmallPool: TinyBlood { 
	Default {
		
		-DONTSPLASH;
	}
	States
	{
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("MinuscleBloodSpot");
			TNT1 A 0 A_PlaySound("blooddrop2");
			XDT1 EFGHIJKL 2;
			stop;
	}
}





















// Blood trails spawned by FlyingBlood
//cause slowdown
CLASS Brutal_FlyingBloodTrail : brutal_blood { 
	Default
	{
		scale 0.70;
		mass 1;
		renderstyle "Translucent";
		alpha 0.7;
		Decal "BrutalBloodSplat";
		+NOTELEPORT;
		+NOCLIP;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		+DontSplash;
		+MISSILE;
		-NOGRAVITY;
		Speed 2;
	}
	states
	{
		Spawn:
			TNT1 A 0 nodelay A_JumpIf(waterlevel > 1, "Splash");
			tnt1 a 0
			{

			 	gravity = frandom(0.5, 0.9);
				scale *=frandom(0.7, 1.1);
				vel *= frandom(1, 2);
				A_SetTranslucent(frandom(0.5, 0.7) );
			}
			BTRL ABCD 1;
			BLOD ABCDEFFFFFF 4 A_JumpIf(waterlevel > 1, "Splash");
		stop;
			
		Death:
		Stop;
	}
}











CLASS SmallBrainPiece : ACTOR { 
	Default {
		Radius 2;
		Height 2;
		Speed 10;
		Mass 1;
		Scale 0.5;
		Decal "BrutalBloodSuper";
		+MISSILE;
		+NOTELEPORT;
		+THRUGHOST;
		+THRUACTORS;
		+CLIENTSIDEONLY;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		-DONTSPLASH;
		+FORCEXYBILLBOARD;
		+FLOORCLIP;
	}
	States
	{
		Spawn:
			XDB5 ABCDEFGH 3;
		Loop;
	
	
			XDT5 B 800;
			XDT5 O 800;
		Death:
			"####" "#" 0 A_CheckFloor("on_floor");
		on_ceiling:
			XDB5 "#" 35 {vel = (0, 0, 0);}
			XDB5 "#" 35
			{
				if(random(0, 10) > 1)
					setstatelabel("on_ceiling");
			}
		fall_down:
			XDB5 "#" 1
			{
				vel.z -= 0.5;
				if(pos.z <= floorz)
					setstatelabel("on_floor");
			}
		loop;

		on_floor:
			XDT5 B 800
			{
				frame = randompick(1, 14);
			}
			XDT5 "#" 35 a_fadeout(0.05);
		wait;
	}
}






CLASS head_piece_base : doomb_body_base { 
	Default {
		Radius 2;
		Height 2;
		Speed 6;
		Mass 1;
		Decal "BrutalBloodSplat";
		+CLIENTSIDEONLY;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+FLOORCLIP;
		Scale 1.2;
	}
}


CLASS Brains1 : head_piece_base { //Random bloody piece
	Default {
		scale 0.6;
	}
	States
	{
		Spawn:
			XDT5 C 800;
			XDT5 C 35 a_fadeout(0.05);
			wait;
			
	}
}

CLASS jaw : brains1 {
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BRIB ABCDG 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		Loop;
			
		Death:
			BRIB "#" 35 a_fadeout(0.05);
		wait;
	}
}

CLASS eye : brains1 { //Eyeballs
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BRIB EFGH 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
			
			BRIB E 800;
			BRIB F 800;
			BRIB G 800;
			BRIB H 800;
		Death:
			BRIB E 1
			{
				frame = random(4, 7);
			}
			BRIB "#" 35 a_fadeout(0.05);
		wait;
	}
}

CLASS head_piece : brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BRIB IJKL 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			tnt1 a 0 {frame = random(3, 4);}
			BRIN "#" 800;
			BRIN "#" 35 a_fadeout(0.05);
			wait;
	}
}


CLASS head_piece_dark : brains1 { //Brown skinned piece
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BRIB MNOP 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			BRIN F 800;
			BRIN F 35 a_fadeout(0.05);
		wait;
	}
}



CLASS head_piece_darkBig: head_piece_dark { //White skinned piece 1
	Default {
		
		Scale 1.8;
	}
}


CLASS jawBig: jaw { //White skinned piece 1
	Default {
		Scale 1.3;
	}
}


CLASS head_pieceGreen: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR7B IJKL 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			BR7N D 1;
			BR7N D 800;
			BR7N D 35 a_fadeout(0.05);
			wait;
	}
}


CLASS head_pieceGreenBig: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR7B ABCD 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			BR7B A 800;
			BR7B A 35 a_fadeout(0.05);
			wait;
	}
}





CLASS head_pieceBlonde: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR8B IJKL 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			BR8B I 1;
			BR8B I 800;
			BR8B I 35 a_fadeout(0.05);
			wait;
	}
}


CLASS head_pieceBlondeBig: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR8B ABCD 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			BR8B A 800;
			BR8B A 35 a_fadeout(0.05);
			wait;
	}
}


CLASS BrainsSergeantHeadPiece: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR7B EFGH 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			BR7B E 800;
			BR7B E 35 a_fadeout(0.05);
			wait;
	}
}


CLASS BrainsImpHeadPiece: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR7N E 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			BR7N E 800;
			BR7N E 35 a_fadeout(0.05);
			wait;
	}
}










CLASS PinkyJaw: head_piece_base { 
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			PDG1 ABCDEFGHI 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			PDG1 "#" 2000;
		Stop;
	}
}



CLASS HellKnightHeadPiece: head_piece_base { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HKHE IJKL 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			HKHE I 2;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			Goto Rest;
			
		Rest:
			HKHE I 800;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DoNothing");
			Loop;
		DoNothing:
			TNT1 A 0;
			Stop;
	}
}

CLASS HellKnightHeadPiece2: head_piece_base { 
	Default {
		
		XScale -1.0;
	}
}


CLASS FatalityBlood: Brutal_FlyingBlood { 
	Default {
		
		Speed 14;
	}
}



CLASS MuchBlood : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		+NOTELEPORT;
		+ALLOWPARTICLES;
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "NULL");
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 15, 0, random (0, 360), 2, - random (0, 360));
			TNT1 AAA 0 A_SpawnProjectile("BloodMistSmall", 0, 0, 180);
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, - random (0, 160));
		stop;
	}
}


CLASS DeadBlood  : ACTOR { 
	Default {
		
		Decal "BrutalBloodSplat";
		
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOCLIP;
		-DONTSPLASH;
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		Spawn:
			TNT1 A 0;
			TNT1 AAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItem ("BloodHit");
			stop;
		Splash:
			tnt1 A 0;
			stop;
	}
}





























CLASS WallRedBlood : ACTOR { 
	Default {
		
		
		scale 0.6;
		speed 7;
		health 1;
		radius 8;
		height 8;
		Gravity 0.7;
		damage 0;
		damagetype "Blood";
		Decal "BrutalBloodSuper";
		+MISSILE;
		+CLIENTSIDEONLY;
		+NOTELEPORT;
		+THRUACTORS;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 ABCD 4;
			loop;
		Splash:
		Death:
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodFake", 0, 0, random (0, 360), 2, random (0, 90));
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_PlaySound("HEDBON");
			TNT1 A 20;
			Stop;
	}
}

 


























CLASS BloodDying : Brutal_Blood { 
	states
	{
		Spawn:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 0 A_SpawnItem ("BloodHit");
			TNT1 A 0 A_SpawnItem ("Brutal_FlyingBlood");
			stop;
		Splash:
			stop;
	}
}




CLASS MinuscleBloodSpot: Brutal_BloodSpot { 
	Default {
		
		Scale 0.25;
	}
}



















CLASS SawBlood : ACTOR Replaces AxeBlood { 
	Default {
		
		Decal "BrutalBloodSplat";
		
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOCLIP;
		-DONTSPLASH;
		-ALLOWPARTICLES;
		MONSTER;
		-FRIENDLY;
		+NOTARGET;
		-COUNTKILL;
		Speed 0;
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 1 A_Look;
		See:
			TNT1 A 0 Radius_Quake (4, 4, 0, 2, 0);
			TNT1 A 0 A_PlaySOund("misc/xdeath4", 1);
			TNT1 A 0 A_GiveToTarget("PowerBloodOnVisor", 1);
			TNT1 A 0 A_SpawnProjectile ("BloodMist", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 1 A_Chase("Melee","Melee");
			Stop;
		Melee:
			TNT1 A 0 A_GiveToTarget("BloodSplasherz", 1);
			TNT1 A 10;
			stop;
		Splash:
			TNT1 AAA 0 A_SpawnProjectile ("Underblood1", 7, 0, random (0, 360), 2, random (30, 150));
			stop;
	}
}






CLASS Brutal_FlyingBloodSaw: Brutal_FlyingBlood  { 
	Default {
		
		Alpha 0.3;
		Speed 0.5;
		Gravity 0.3;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			BLOD BC 2;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 0 A_Jump(255, "Spawn1", "Spawn2");
		Spawn1:
			BLOD EEEEEEEEEEEEEEEEEEEEEEEE 1 A_FadeOut(0.03);
			Stop;
	}
}


CLASS GrowingBloodPool: Brutal_BloodSpot { 
	Default {
		radius 30;
		height 1;
		mass 1;
		Alpha 0.99;
		+NOTELEPORT;
		+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
		+MOVEWITHSECTOR;
		+FLOORCLIP;
		-DONTSPLASH;
		Scale 1.0;
		Decal "BrutalBloodSplat";
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "null");
			TNT1 A 0 A_SpawnItemEx ("BootSmearerRed",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT5 AAAAAAAAAAAAAAAAAAAAAAAAA 5 {scale *= 1.03;}
		Live:
			TNT5 a 900;//duration
		loop;
	}
}




CLASS Brutal_LiquidBlood: Brutal_FlyingBlood  { 
	Default {
		
		speed 3;
		scale 0.2;
		gravity 0.6;
		
	}
	States
	{
		Spawn:
			BLOD A 1 A_SpawnItem("Brutal_LiquidBloodTrail");
			Loop;
		Death:
			TNT1 A 0 A_PlaySound("blooddrop");
			XDT1 FGHIJKL 2;
			TNT1 A 0;
			Stop;
	}
}


CLASS Brutal_LiquidBlood2: Brutal_FlyingBlood  { 
	Default {
		
		speed 4;
		scale 0.4;
		gravity 0.6;
		
	}
	States
	{
		Spawn:
			BLOD A 1 A_SpawnItem("Brutal_LiquidBloodTrail");
			Loop;
		Death:
			TNT1 A 0 A_PlaySound("blooddrop");
			XDT1 FGHIJKL 2;
			TNT1 A 0;
			Stop;
	}
}

CLASS Brutal_LiquidBlood3: Brutal_FlyingBlood  { 
	Default {
		
		Speed 3;
	}
	States
	{
		Spawn:
			BLOD A 1 A_SpawnItem("Brutal_LiquidBloodTrail");
			Loop;
		Death:
			TNT1 A 0 A_PlaySound("blooddrop");
			TNT1 A 0 A_CheckFloor("SpawnFloor");
			TNT1 A 4;
			Stop;
			
		SpawnFloor:
			tnt1 a 0 A_SPawnItem("Brutal_BloodSpot");
			XDT1 FGHIJKL 2;
			TNT1 A 0;
			Stop;
	}
}



CLASS Brutal_LiquidBloodTrail: Brutal_FlyingBlood  { 
	Default {
		
		scale 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			BL8D ABCDEEEEE 2;
			Stop;
		Death:
			TNT1 A 0;
			Stop;
	}
}






//cause slowdown
CLASS Brutal_FlyingBloodFake  : brutal_blood { 
	Default {
		
		
		scale 0.5;
		speed 3;
		health 1;
		radius 8;
		height 1;
		damage 0;
		Renderstyle "Translucent";
		Alpha 0.95;
		damagetype "Blood";
		Decal "BrutalBloodSplat";
		+MISSILE;
		+CLIENTSIDEONLY;
		+NOTELEPORT;
		+BLOODLESSIMPACT;
		+FORCEXYBILLBOARD;
		+NODAMAGETHRUST;
		+MOVEWITHSECTOR;
		+CORPSE;
		-DONTSPLASH;
		+THRUACTORS;
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			BLOD KKKKKKKKKKKK 1 A_FadeOut(0.05);
		Stop;
		Death:
			Stop;
	}
}








CLASS Cyberdemon_Blood : ACTOR { 
	Default {
		
		Decal "BrutalBloodSplat";
		
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOCLIP;
		-DONTSPLASH;
		-ALLOWPARTICLES;
		Speed 0;
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 AAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 AAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodFake", 7, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 7, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("SmallSuperGore", 10, 0, random (0, 360), 2, random (10, 170));
			TNT1 A 0 A_SpawnItem ("RicoChet");
			stop;
		Splash:
			TNT1 AAA 0 A_SpawnProjectile ("Underblood1", 7, 0, random (0, 360), 2, random (30, 150));
			stop;
	}
}







CLASS Bloodmist : Brutal_FlyingBlood { 
	Default {
		
		decal "BrutalBloodSuper";
		+MISSILE +NOTELEPORT +NOBLOCKMAP +NOBLOCKMONST +DONTSPLASH +CLIENTSIDEONLY +THRUACTORS;
		scale    0.8;
		radius    2;
		height    2;
		speed    8;
		Gravity 0.4;
		RenderStyle    "Translucent";
		alpha    0.9;
	}
	states
	{
		Spawn:
			TNT1 A 0;
			MSBL ABCDEFGH 1;
			MSBL HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 1 A_FadeOut(0.005);
			Stop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_CheckFloor("Disappear");
			MSBL HHHHHHHH 1 A_FadeOut(0.1);
			Stop;
			
		Vanish:
		Disappear:
			TNT1 A 2;
			Stop;
	}
}


CLASS BloodmistBig : Bloodmist { 
	Default {
		
		scale    0.9;
		speed    4;
		GRAVITY 0.4;
	}
}


CLASS BloodmistSmall : Bloodmist { 
	Default {
		
		scale    0.45;
		Gravity 0.8;
	}
}


CLASS BloodmistExtraBig : Bloodmist { 
	Default {
		
		scale    1.4;
	}
}


CLASS BloodmistLarge : Bloodmist { 
	Default {
		
		scale    0.95;
	}
}

CLASS BloodmistXXBig : Bloodmist { 
	Default {
		
		scale    2.2;
		GRAVITY 0.2;
	}
}


CLASS SplatteredSmall: Brutal_BloodSpot { 
	Default {
		
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			//TNT1 A 0 Acs_executealways(373, 0, 0, 0, 0)//Check if is under a liquid
			TNT1 A 0 A_FaceTarget;
			TNT1 A 2;
			TNT1 A 0 A_JumpIfInventory("IsOverWater", 1, "Splash");
			TNT1 A 0 A_JumpIfInventory("IsOverSlime", 1, "Splash");
			TNT1 A 0 A_JumpIfInventory("IsOverlava", 1, "Splash");
			TNT1 A 0 A_SpawnItemEx ("BootSmearerRed",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			BPDL A -1;
			Stop;
	}
}


CLASS SplatteredLarge: Brutal_BloodSpot { 
	Default {
		
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			//TNT1 A 0 Acs_executealways(373, 0, 0, 0, 0)//Check if is under a liquid
			TNT1 A 0 A_FaceTarget;
			TNT1 A 2;
			
			TNT1 A 0 A_JumpIfInventory("IsOverWater", 1, "Splash");
			TNT1 A 0 A_JumpIfInventory("IsOverSlime", 1, "Splash");
			TNT1 A 0 A_JumpIfInventory("IsOverlava", 1, "Splash");
			TNT1 A 0 A_SpawnItemEx ("BootSmearerRed",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			BPDL A -1;
			Stop;
	}
}




CLASS RedBloodFootPrintLeft: GrowingBloodPool { 
	Default {
		
		Scale 0.09;
		+CLIENTSIDEONLY;
	}
	states
	{
		Spawn:
		Death:
		Crash:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 0 Acs_executealways(373, 0, 0, 0, 0);//Check if is under a liquid
			TNT1 A 2;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			TNT1 A 0 A_JumpIfInventory("IsOverWater", 1, "Splash");
			TNT1 A 0 A_JumpIfInventory("IsOverSlime", 1, "Splash");
			TNT1 A 0 A_JumpIfInventory("IsOverlava", 1, "Splash");
			TNT1 A 0 A_CheckFloor("ShowUp");
			Goto Splash;
		ShowUp:
			BPDL A 600;
			TNT1 A 0 A_JumpIfInventory("LowGraphicsMode", 1, "Splash");
			Loop;
		Splash:
			TNT1 A 0;
			Stop;
	}
}


CLASS RedBloodFootPrintRight: GrowingBloodPool { 
	Default {
		
		Scale 0.09;
		+CLIENTSIDEONLY;
	}
	states
	{
		Spawn:
		Death:
		Crash:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 0 Acs_executealways(373, 0, 0, 0, 0);//Check if is under a liquid
			TNT1 A 2;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			TNT1 A 0 A_JumpIfInventory("IsOverWater", 1, "Splash");
			TNT1 A 0 A_JumpIfInventory("IsOverSlime", 1, "Splash");
			TNT1 A 0 A_JumpIfInventory("IsOverlava", 1, "Splash");
			TNT1 A 0 A_CheckFloor("ShowUp");
			Goto Splash;
		ShowUp:
			BPDL A 600;
			TNT1 A 0 A_JumpIfInventory("LowGraphicsMode", 1, "Splash");
			Loop;
		Splash:
			TNT1 A 0;
			Stop;
	}
}


CLASS BootSmearerRed: GrowingBloodPool { 
	Default {
		
		MONSTER;
		-SOLID;
		+NOCLIP;
		+THRUACTORS;
		-COUNTKILL;
		+LOOKALLAROUND;
		-FRIENDLY;
		Radius 0;
		Height 0;
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 1 A_Look;
			Goto See;
			
		See:
			TNT1 A 1 A_Chase(",");
			TNT1 A 0 A_Die("LookForPlayer");
		Death:
		Death.LookForPlayer:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 8 A_JumpIfCloser(60, "SmearBootsWithRedBlood");
			Stop;
		SmearBootsWithRedBlood:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 8);
			BPDL A 0;
			Stop;
	}
}




CLASS BootSmearerBlue: GrowingBloodPool { 
	Default {
		
		MONSTER;
		-SOLID;
		+NOCLIP;
		+THRUACTORS;
		-COUNTKILL;
		+LOOKALLAROUND;
		-FRIENDLY;
		Radius 0;
		Height 0;
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 1 A_Look;
			Goto See;
			
		See:
			TNT1 A 1 A_Chase(",");
			TNT1 A 0 A_Die("LookForPlayer");
		Death:
		Death.LookForPlayer:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 8 A_JumpIfCloser(60, "SmearBootsWithRedBlood");
			Stop;
		SmearBootsWithRedBlood:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithBlueBlood", 8);
			BPDL A 0;
			Stop;
	}
}


CLASS BootSmearerGreen: GrowingBloodPool { 
	Default {
		
		MONSTER;
		-SOLID;
		+NOCLIP;
		+THRUACTORS;
		-COUNTKILL;
		+LOOKALLAROUND;
		-FRIENDLY;
		Radius 0;
		Height 0;
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 1 A_Look;
			Goto See;
			
		See:
			TNT1 A 1 A_Chase(",");
			TNT1 A 0 A_Die("LookForPlayer");
		Death:
		Death.LookForPlayer:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 8 A_JumpIfCloser(60, "SmearBootsWithRedBlood");
			Stop;
		SmearBootsWithRedBlood:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithGreenBlood", 8);
			BPDL A 0;
			Stop;
	}
}


CLASS doomb_fatsoEyeballs : ACTOR { //Eyeballs
	Default {
		
		Radius 2;
		Height 2;
		Speed 6;
		Mass 1;
		Decal "BrutalBloodSplat";
		+CLIENTSIDEONLY;
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+FLOORCLIP;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			MANE Y 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			MANE Y 1;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			Goto Rest;
			
			
		Rest:
			MANE Y 800;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DoNothing");
			Loop;
			
		DoNothing:
			TNT1 A 0;
			Stop;
	}
}

CLASS BloodSplasherz : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}
