//All the liquid gore stuff goes here.

//SLOWDOWN
CLASS TinyBlood : doomb_blood { 
	Default {
		scale 0.2;
		speed 7;
		health 1;
		radius 8;
		height 1;
		+DontSplash;
		Gravity 0.7;
		Decal "BrutalBloodSplat";
		XScale 0.4;
		YScale 0.8;
		+MISSILE;
		+CLIENTSIDEONLY;
		+NOTELEPORT;
		+NOBLOCKMAP;
		+FORCEXYBILLBOARD;
		-EXPLODEONWATER;
		+DOOMBOUNCE;
	}
	States
	{
		Spawn:
			tnt1 a 0 nodelay {scale *= frandom(0.8, 1.2);}
		mini:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			BLUD Z 1
			{
				if(pos.z <= floorz)
					setstatelabel("death");
			}
		loop;

		Splash:
			TNT1 A 0 A_SpawnProjectile ("Underblood1", 7, 0, random (0, 360), 2, - random (30, 150));
		stop;

		Death:
			tnt1 a 0 {vel = (0, 0, 0);}
			XDT1 EFGHIJKL 2;
			TNT1 A 0 A_PlaySound("blooddrop3");
			TNT1 A 0 {spawn("MediumBloodSpot", (pos.xy, floorz) );}
		stop;
	}
}










//SLOWDOWN
CLASS Brutal_Blood : doomb_blood Replaces Blood { 
	Default {
		renderstyle "add";
		Decal "BrutalBloodSplat";
		+FORCEXYBILLBOARD;
		+THRUACTORS;
		+CLIENTSIDEONLY;
		Scale 0.5;
		Speed 0;
	}
	states
	{
		Spawn:
			TNT1 A 0 nodelay A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 0 doomb_spawn_blood();
		Splash:
			tnt1 A 0 { vel = ( random(-3, 3), random(-3, 3), random(-3, 3));}
			BSP4 ABCDEFGHIJKLMNOPQRSTUVWXYZ 2;
		stop;
	}
	
}

CLASS BloodHit : ACTOR { 
	Default {
		height 8;
		radius 4;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOCLIP;
		+CLIENTSIDEONLY;
		Scale 0.7;
	}
	states
	{
		Spawn:
			BLHT ABCDE 1;
			Stop;
	}
}







CLASS Brutal_FlyingBlood : Brutal_Blood { 
	Default {
		scale 0.5;
		speed 10;
		health 1;
		radius 8;
		height 1;
		Gravity 0.8;
		damage 0;
		Renderstyle "Translucent";
		Alpha 0.95;
		damagetype "Blood";
		Decal "BrutalBloodSuper";
		+MISSILE;
		-nogravity
		+CLIENTSIDEONLY;
		+NOTELEPORT;
		+NOBLOCKMAP;
		+THRUACTORS;
		+BLOODLESSIMPACT;
		+FORCEXYBILLBOARD;
		+NODAMAGETHRUST;
		+MOVEWITHSECTOR;
		+CORPSE;
		-DONTSPLASH;
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay A_ScaleVelocity(frandom(1, 1.8));
			BLOD AB 2 A_JumpIf(waterlevel > 1, "Splash");
			tnt1 a 0 {frame = randompick(2, 4);}
		Spawn2:
			BLOD "#" 1 A_JumpIf(waterlevel > 1, "Splash");
		loop;
			
		Death:
			TNT1 A 0 A_PlaySound("blooddrop2");
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_SpawnItemEx ("CeilBloodLauncher",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
	}
}


CLASS Brutal_BloodSpot : doomb_blood
{ 
	Default {
		radius 2;
		height 2;
		mass 1;
		Health 300;
		+NOTELEPORT;
		+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
		+MOVEWITHSECTOR;
		+FLOORCLIP;
		+NOTARGET;
		-SHOOTABLE;
		+NOBLOOD;
		-DONTSPLASH;
		-SOLID;
		+THRUACTORS;
		Alpha 0.9;
		Mass 99999999;
		Scale 0.5;
		Decal "BrutalBloodSplat";
	}
	states
	{
			BPDL A 800;//duration
		Spawn:
			TNT1 A 0 nodelay{frame = random(0, 3);}
		SpawnAFrameOnly:
			BPDL "#" 800;//duration
			BPDL "#" 1 A_FadeOut(0.05);
		wait;
	}
}









CLASS MediumBloodSpot: doomb_red_blood_pool { 
	Default {
		
		Scale 0.4;
	}
}



CLASS CeilBloodLauncher: Brutal_FLyingBlood  { 
	Default {
		+missile
		+THRUACTORS;
		+BLOODLESSIMPACT;
		-DOOMBOUNCE;
		damagetype "Blood";
		Speed 10;
		Gravity 0.0;
		Decal "BrutalBloodSplat";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "null");
			TNT1 A 3 a_settics(random(3, 12) );
			Stop;
		Death:
			BPDL A 1 A_SpawnItem ("DripingBloodLeavesSmallPool");
			bpdl AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1
			{
				a_settics(random(5, 24) );
				A_SpawnItemEx ("TinyBlood", frandom (-5, 5), frandom (-5, 5));
			}
			BPDL AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 2;
			BPDL AAAAAAAAA 1 A_FadeOut(0.1);
		stop;
	}
}

CLASS DripingBloodLeavesSmallPool: TinyBlood { 
	Default {
		-DONTSPLASH;
	}
	States
	{
		Death:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("blooddrop2");
			XDT1 EFGHIJKL 2;
			stop;
	}
}





















// Blood trails spawned by FlyingBlood
//SLOWDOWN
CLASS Brutal_FlyingBloodTrail : brutal_blood { 
	Default
	{
		scale 0.70;
		mass 1;
		renderstyle "Translucent";
		alpha 0.7;
		Decal "BrutalBloodSplat";
		+NOTELEPORT;
		+NOCLIP;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		+DontSplash;
		+MISSILE;
		-NOGRAVITY;
		Speed 2;
	}
	states
	{
		Spawn:
			TNT1 A 0 nodelay A_JumpIf(waterlevel > 1, "null");
			tnt1 a 0
			{
			 	gravity = frandom(0.5, 0.9);
				scale *=frandom(0.7, 1.1);
				vel *= frandom(1, 2);
				A_SetTranslucent(frandom(0.5, 0.7) );
			}
			BTRL ABCD 1;
			BLOD ABCDEFFFFFF 4 A_JumpIf(waterlevel > 1, "null");
		stop;
			
		Death:
		Stop;
	}
}

















CLASS head_piece_base : doomb_body_base { 
	Default {
		Radius 2;
		Height 2;
		Speed 6;
		Mass 1;
		Decal "BrutalBloodSplat";
		+CLIENTSIDEONLY;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+FLOORCLIP;
		Scale 0.6;
	}
}


CLASS Brains1 : head_piece_base { //Random bloody piece
	States
	{
		Spawn:
			XDT5 C 800;
			XDT5 C 35 a_fadeout(0.05);
			wait;
			
		Death:
			"####" "#" 800;
			"####" "#" 35 a_fadeout(0.05);
		wait;
	}
}

CLASS jaw : brains1 {
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BRIB ABCDG 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		Loop;
	}
}

CLASS eye : brains1 { //Eyeballs
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BRIB EFGH 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		Loop;
	}
}

CLASS head_piece : brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BRIB IJKL 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		Loop;

		Death:
			BRIN "#" 800;
			BRIN "#" 35 a_fadeout(0.05);
		wait;
	}
}


CLASS head_piece_dark : brains1 { //Brown skinned piece
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BRIB MNOP 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
	}
}





CLASS jawBig: jaw { //White skinned piece 1
	Default {
		Scale 1.3;
	}
}


CLASS head_pieceGreen: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR7B IJKL 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			BR7N D 1;
			BR7N D 800;
			BR7N D 35 a_fadeout(0.05);
			wait;
	}
}


CLASS head_pieceGreenBig: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR7B ABCD 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
	}
}





CLASS head_pieceBlonde: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR8B IJKL 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		Loop;
	}
}


CLASS head_pieceBlondeBig: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR8B ABCD 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		Loop;
	}
}


CLASS BrainsSergeantHeadPiece: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR7B EFGH 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		Loop;
	}
}


CLASS BrainsImpHeadPiece: Brains1 { //White skinned piece 1
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BR7N E 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		Loop;
	}
}










CLASS PinkyJaw: Brains1 { 
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			PDG1 ABCDEFGHI 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		Loop;
	}
}



CLASS HellKnightHeadPiece: Brains1 { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HKHE IJKL 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		Loop;
	}
}

CLASS HellKnightHeadPiece2: head_piece_base { 
	Default {
		
		XScale -1.0;
	}
}


CLASS FatalityBlood: Brutal_FlyingBlood { 
	Default {
		
		Speed 14;
	}
}



CLASS MuchBlood : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		+NOTELEPORT;
		+ALLOWPARTICLES;
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "NULL");
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 15, 0, random (0, 360), 2, - random (0, 360));
			TNT1 AAA 0 A_SpawnProjectile("BloodMistSmall", 0, 0, 180);
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, - random (0, 160));
		stop;
	}
}


CLASS DeadBlood  : ACTOR { 
	Default {
		Decal "BrutalBloodSplat";
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOCLIP;
		-DONTSPLASH;
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "null");
		Spawn:
			TNT1 A 0;
			TNT1 AAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItem ("BloodHit");
		stop;
	}
}





























CLASS WallRedBlood : ACTOR { 
	Default {
		
		
		scale 0.6;
		speed 7;
		health 1;
		radius 8;
		height 8;
		Gravity 0.7;
		damage 0;
		damagetype "Blood";
		Decal "BrutalBloodSuper";
		+MISSILE;
		+CLIENTSIDEONLY;
		+NOTELEPORT;
		+THRUACTORS;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 ABCD 4;
			loop;
		Splash:
		Death:
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodFake", 0, 0, random (0, 360), 2, random (0, 90));
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			TNT1 A 0 A_PlaySound("HEDBON");
			TNT1 A 20;
			Stop;
	}
}

 


























CLASS BloodDying : Brutal_Blood { 
	states
	{
		Spawn:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_JumpIf(waterlevel > 1, "null");
			TNT1 A 0 A_SpawnItem ("BloodHit");
			TNT1 A 0 A_SpawnItem ("Brutal_FlyingBlood");
		stop;
	}
}























CLASS SawBlood : ACTOR Replaces AxeBlood { 
	Default {
		Decal "BrutalBloodSplat";
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOCLIP;
		-DONTSPLASH;
		-ALLOWPARTICLES;
		MONSTER;
		-FRIENDLY;
		+NOTARGET;
		-COUNTKILL;
		Speed 0;
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 1 A_Look;
		See:
			TNT1 A 0 Radius_Quake (4, 4, 0, 2, 0);
			TNT1 A 0 A_PlaySOund("misc/xdeath4", 1);
			TNT1 A 0 A_GiveToTarget("PowerBloodOnVisor", 1);
			TNT1 A 0 A_SpawnProjectile ("BloodMist", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		Stop;
		
		Splash:
			TNT1 AAA 0 A_SpawnProjectile ("Underblood1", 7, 0, random (0, 360), 2, random (30, 150));
			stop;
	}
}






CLASS Brutal_FlyingBloodSaw: Brutal_FlyingBlood  { 
	Default {
		
		Alpha 0.3;
		Speed 0.5;
		Gravity 0.3;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			BLOD BC 2 A_JumpIf(waterlevel > 1, "Splash");
		Spawn1:
			BLOD EEEEEEEEEEEEEEEEEEEEEEEE 1 A_FadeOut(0.03);
			Stop;
	}
}






CLASS Brutal_LiquidBlood: Brutal_FlyingBlood  { 
	Default {
		
		speed 3;
		scale 0.2;
		gravity 0.6;
		
	}
	States
	{
		Spawn:
			tnt1 a 0 nodelay {scale *= frandom(0.4, 0.6);}
			BLOD A 1 A_SpawnItem("Brutal_LiquidBloodTrail");
			Loop;
		Death:
			TNT1 A 0 A_PlaySound("blooddrop");
			XDT1 FGHIJKL 2;
			Stop;
	}
}






CLASS Brutal_LiquidBloodTrail: Brutal_FlyingBlood  { 
	Default {
		scale 0.4;
	}
	States
	{
		Spawn:
			BL8D ABCDEEEEE 2;
			Stop;
		Death:
			TNT1 A 0;
			Stop;
	}
}






//SLOWDOWN
CLASS Brutal_FlyingBloodFake  : brutal_blood { 
	Default {
		scale 0.5;
		speed 3;
		health 1;
		radius 8;
		height 1;
		damage 0;
		Renderstyle "Translucent";
		Alpha 0.95;
		damagetype "Blood";
		Decal "";
		+MISSILE;
		+CLIENTSIDEONLY;
		+NOTELEPORT;
		+BLOODLESSIMPACT;
		+FORCEXYBILLBOARD;
		+NODAMAGETHRUST;
		+MOVEWITHSECTOR;
		+CORPSE;
		-DONTSPLASH;
		+THRUACTORS;
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "null");
			BLOD KKKKKKKKKKKK 1 A_FadeOut(0.05);
		Stop;
		Death:
			Stop;
	}
}








CLASS Cyberdemon_Blood : ACTOR { 
	Default {
		Decal "BrutalBloodSplat";
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOCLIP;
		-DONTSPLASH;
		-ALLOWPARTICLES;
		Speed 0;
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 AAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 AAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodFake", 7, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 7, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("SmallSuperGore", 10, 0, random (0, 360), 2, random (10, 170));
			TNT1 A 0 A_SpawnItem ("RicoChet");
			stop;
		Splash:
			TNT1 AAA 0 A_SpawnProjectile ("Underblood1", 7, 0, random (0, 360), 2, random (30, 150));
			stop;
	}
}







CLASS Bloodmist : Brutal_FlyingBlood { 
	Default {
		decal "BrutalBloodSuper";
		+MISSILE +NOTELEPORT +NOBLOCKMAP +NOBLOCKMONST +DONTSPLASH +CLIENTSIDEONLY +THRUACTORS;
		scale    0.8;
		radius    2;
		height    2;
		speed    8;
		Gravity 0.4;
		RenderStyle   "Translucent";
		alpha    0.9;
	}
	states
	{
		Spawn:
			TNT1 A 0 nodelay {scale *= frandom(0.8, 0.95);}
			MSBL ABCDEFGH 1;
			MSBL HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 1 A_FadeOut(0.005);
			Stop;
			
		Death:
			TNT1 A 0 A_CheckFloor("null");
			MSBL HHHHHHHH 1 A_FadeOut(0.1);
		Stop;
	}
}


//SLOWDOWN
CLASS BloodmistSmall : Bloodmist { 
	Default {
		
		scale    0.45;
		Gravity 0.8;
	}
}


CLASS BloodmistExtraBig : Bloodmist { 
	Default {
		
		scale    1.4;
	}
}


CLASS BloodmistXXBig : Bloodmist { 
	Default {
		
		scale    2.2;
		GRAVITY 0.2;
	}
}










CLASS doomb_fatsoEyeballs : ACTOR { //Eyeballs
	Default {
		Radius 2;
		Height 2;
		Speed 6;
		Mass 1;
		Decal "BrutalBloodSplat";
		+CLIENTSIDEONLY;
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+FLOORCLIP;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			MANE Y 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			MANE Y 800;
		stop;
	}
}