CLASS BigGibBase : doomb_body_base { 
	Default {
		Radius 10;
		Height 10;
		+CLIENTSIDEONLY;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+DONTSPLASH;
		+NOBLOCKMONST;
		-NOBLOCKMAP;
		+GHOST;
		+THRUACTORS;
		+FLOORCLIP;
		+SLIDESONWALLS;
		+FORCEXYBILLBOARD;
		DamageFactor "CauseObjectsToSplash", 0.0;
		-SOLID;
		+SHOOTABLE;
		damagefactor "Crush", 50.0;
		damagefactor "Plasma", 20.0;
		painchance "Flames", 0;
		painchance "Fire", 0;
		painchance "Burn", 0;
		damagefactor "Kick", 3.0;
		damagefactor "SuperKick", 3.0;
		damagefactor "punch", 2.0;
		Mass 1000;
		Health 100;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0 ;
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		damagefactor "Trample", 5000.0;
		painchance 255;
	}
	States 
	{
		Spawn:
			TNT1 A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
			
			
		Death:
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("XDeathSkinPiece2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeathSkinPiece1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("SmallSuperGore", 10, 0, random (0, 360), 2, random (10, 170));
			Stop;
			
		Death.plasma:
		Death.Fire:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(128, "DeathFire2");
			TNT1 A 0 doomb_spawn_burned_flesh();
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0;
			Stop;
			
		DeathFire2:
			TNT1 A 0 doomb_spawn_burned_flesh();
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0;
			Stop;
		Death.Trample:
		Death.Crush:
		Death.Stomp:
		Death.punch:
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 30));
			TNT1 AAAA 0 A_SpawnProjectile ("BloodMist", 5, 0, random (0, 360), 2, random (0, 30));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("XDeathSkinPiece2", 5, 0, random (0, 360), 2, random (10, 30));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeathSkinPiece1", 5, 0, random (0, 360), 2, random (10, 130));
			TNT1 AAAA 0 A_SpawnProjectile ("SmallSuperGore", 10, 0, random (0, 360), 2, random (10, 30));
			TNT1 A 0 doomb_spawn_bloodpool();
			XME2 L -1;
		Stop;
		
		Death.Desintegrate:
			TNT1 A 0;
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodFake", 0, 0, random (0, 360), 2, random (0, 90));
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 7, 0, random (0, 360), 2, random (30, 60));
			TNT1 A 0 A_SpawnProjectile ("BloodMistSmall", 7, 0, random (0, 360), 2, random (30, 60));
			Stop;
			
	}
	
}

CLASS LimbBase: BigGibBase { 
	Default {
		Radius 6;
		Height 10;
		Mass 1000;
		Painchance 256;
		Health 35;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+SHOOTABLE;
		-CLIENTSIDEONLY;
		+NOBLOCKMONST;
		//+SOLID
		+THRUACTORS;
		+FLOORCLIP;
		damagefactor "Crush", 50.0;
		DeathSound "misc/xdeath4";
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0 ;
		damagefactor "Taunt", 0.0 ;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		//damagefactor "Plasma", 99000.0
		damagefactor "Trample", 2.0;
		damagefactor "Kick", 9.0;
		damagefactor "Explosive_Impact", 0.1;
		damagefactor "Explosive_Impact", 9.1;
		damagefactor "Melee", 9.0;
		damagefactor "Plasma", 20.0;
		painchance 255;
	}
	States
	{
		Spawn:
			TNT1 A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XDT3 BCDEFGH 3;
		Death.Crush:
			TNT1 A 1 A_SpawnProjectile ("XDeath1", 5, 5, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 5, -5, random (0, 360), 2, random (0, 160));
			
			CRSB A 9009;
			Stop ;
			Stop;
	}
	
}		

CLASS TinyGib : doomb_body_base { 
	Default {
		
		Radius 2;
		Height 8;
		Speed 6;
		Mass 1;
		gravity 0.5;
		Scale 0.8;
		Decal "BrutalBloodSplat";
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+NOBLOCKMONST;
		seesound "bloood";
		deathsound "bloood";
	}
	States
	{
		Spawn:
			TNT1 A 1;
			Loop;
	}
}



CLASS BloodTrails : doomb_blood { 
	Default {
		
		Decal "BrutalBloodSplat";
		
		Alpha 0.4;
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		Gravity 0.05;
		+NOCLIP;
		+DontSplash;
		-EXPLODEONWATER;
		-ALLOWPARTICLES;
		+CLIENTSIDEONLY;
		-NOGRAVITY;
		Scale 1.2;
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 AAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 180));
			stop;
	}
}



CLASS GreenBloodTrail : doomb_blood { 
	Default {
		
		-NOGRAVITY;
		+NOCLIP;
		radius 16;
		height 16;
		gravity 0.5;
		Scale 1.5;
	translation "168:191=112:127","16:47=120:127";
	+FORCEXYBILLBOARD;
	+NOBLOCKMAP;
	}
states
	{
Spawn:
	TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
	TNT1 A 0;
	TNT1 A 0 Thing_ChangeTid(0,386);
	BLOD ABCD 2;
	stop;
Splash:
	TNT1 A 0;
	Stop;
}
}


CLASS BlueBloodTrail : doomb_blood { 
	Default {
 
-NOGRAVITY
+NOCLIP
radius 16;
height 16;
gravity 0.5;
Scale 1.5;
translation "168:191=192:207","16:47=240:247";
decal "CacoBloodSplat";
+FORCEXYBILLBOARD
	}
states
	{
	Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		TNT1 A 0;
		TNT1 A 0 Thing_ChangeTid(0,386);
		BLOD ABCD 2;
		stop;
    Splash:
        TNT1 A 0;
        Stop;
	}
}



CLASS XDeath1 : doomb_body_base { 
	Default {
 
    Radius 8;
    Height 8;
    Speed 10;
    Scale 1.2;
	Mass 1;
    +NOBLOCKMAP
	+MISSILE
    +NOTELEPORT
    +MOVEWITHSECTOR
    +CLIENTSIDEONLY
    +BLOODLESSIMPACT 
	+DONTSPLASH
	+THRUGHOST
	+thrUACTORS
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		Gravity 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			BLOD A 4 A_SpawnProjectile ("Brutal_LiquidBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			XDT1 EFGHIJKL 5;
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Stop;
			TNT1 A 1;
		Underwater:
		Splash:
			XDT1 ABCD 3
			{
				A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
				vel.z += 3;
			}
		stop;
	}
}

CLASS XDeath2: XDeath1 { 
	Default {
		DeathSound "misc/xdeath2";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME1 ABCD 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CheckFloor("SpawnFloor");
			TNT1 A 0 A_SpawnItemEx ("CeilBloodLauncher",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 doomb_meat_on_ceiling();
			Stop;
			
		SpawnFloor:
			XME1 E 1;
			XME1 E 3;
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		Living:
			XME1 E 600;
			Loop;
		Vanish:
			TNT1 A 5;
			Stop;
	}
}


CLASS XDeath3: XDeath1 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal "BrutalBloodSuper";
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME2 ABCD 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CheckFloor("SpawnFloor");
			TNT1 A 0 A_SpawnItemEx ("CeilBloodLauncher",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 doomb_meat_on_ceiling();
			Stop;
			
		SpawnFloor:
			XME2 E 1;
			XME2 E 3;
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		Living:
			XME2 E 600;
			Loop;
		Vanish:
			TNT1 A 5;
			Stop;
	}
}

CLASS XDeath4: XDeath1 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 1.1;
		+DOOMBOUNCE;
		BounceFactor 0.3;
		wallbouncefactor 0.2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME3 ABCDEFGH 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			XME3 "#" 800;
		loop;
	}
}


CLASS XDeath5: XDeath1 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME5 ABCD 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XME5 E 3;
		Living:
			XME5 E 800;//duration
			Loop;
		Vanish:
			TNT1 A 1;
			Stop;
			
	}
}


CLASS XDeathOrgan1 : ACTOR { 
	Default {
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 0.9;
		Speed 4;
	}
	States
	{
		Spawn:
			XME8 A 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			XME8 A 1;
			XME8 A -1;
			Stop;
	}
}



CLASS XDeathOrgan2: XDeathOrgan1 { 
	States
	{
		Spawn:
			XME8 B 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			XME8 B 1;
			XME8 B -1;
			Stop;
	}
}

CLASS XDeathGuts : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		Scale 1.1;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME4 AAAABBBBCCCCDDDD 2;
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			//TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1)
			XME4 E 9009;
			Stop;
	}
}











/////////////////
//ARMS
/////////////////


CLASS XDeathArm1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.1;
		Speed 8;
		Mass 1;
		gravity 0.5;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		wallbouncefactor 0.2;
		BounceCount 3;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		+EXPLODEONWATER;
		+SKYEXPLODE;
		-DONTSPLASH;
		seesound "bloood";
		deathsound "bloood";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XARM AEBCFDG 5 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			XDT5 I 1;
			XDT5 I 0 A_SpawnItem("Gib_Arm");
			Stop;
	}
}

CLASS Gib_Arm: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			XDT5 I 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma:
		Death.fire:
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
			Stop;
		Death:    
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("GibHand", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("GibArmPart", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
			
		Death.Kick:
		Death.punch:
			XDT5 I 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XARM ABCD 3;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			XARM A 6;
			XARM ABCDABCDABCD 6 A_CheckFloor("Landz");
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_Arm");
			Stop;
	}
}

CLASS GibArmPart: TinyGib { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			XDT5 Z -1;
			stop;
	}
	
}
CLASS GibHand: TinyGib { 
	Default {
		Scale 1.0;
	}
	States
	{
		Spawn:
			XDT5 Y 1;
			Loop;
		Death:
			XDT5 Y 1;
			Loop;
			
	}
	
}






//////////////
//GUTS
//////////////


CLASS XDeathStomach: XDeathArm1 { 
	Default {
		
		-DOOMBOUNCE;
		BounceFactor 0.0;
		Speed 2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XSTO A 24 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XSTO EEEEEEEEE 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			XSTO E 9009;
			Stop;
	}
}


CLASS XDeathHalfMarine : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 4;
		Mass 8;
		BounceFactor 0.2;
		BounceCount 3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HPLA A 12 A_SpawnProjectile("Brutal_FlyingBloodTrail",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			HPLA A 0 A_SpawnItem("HalfMarineGib",0,0,0,1);
			Stop;
	}
}

CLASS HalfMarineGib: BigGibBase { 
	States
	{
		Spawn:
			HPLA A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
	}
	
}


	   







CLASS XDeathBrain1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 13;
		Mass 1;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+MISSILE;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDB5 ABCD 6;
			Loop;
		Death:
			TNT1 A 0 A_Jump(128, "Death2");
			XDT5 B 9009;
			Stop;
		Death2:
			XDT5 O 9009;
			Stop;
	}
}

CLASS XDeathBrain2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 12;
		Mass 1;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+MISSILE;
	}
	States
	{
		Spawn:
			XDB5 EFGH 6 A_JumpIf(waterlevel > 1, "Death");
			Loop;
		Death:
			XDT5 C 1;
			XDT5 C 9009;
			Stop;
	}
}











//SLOWDOWN
CLASS Instestin : doomb_blood
{ 
	Default {
		
		Radius 8;
		Height 12;
		Speed 6;
		Mass 1;
		BounceFactor 0.4;
		Renderstyle "Translucent";
		Alpha 0.9;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
		-EXPLODEONWATER;
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
		Scale 1.1;
	}
	States
	{
		Spawn:
			GUTS ABCD 8;
		Loop;
		
		Death:
			tnt1 a 0 A_QueueCorpse;
			GUTS E 1 A_JumpIf(waterlevel > 1, "Water");
		Rest:
			TNT1 A 0 A_Jump(255, "Rest1", "Rest2");
		Rest1:
			GUTS E -1;
		stop;
			
		Rest2:
			GUTS F -1;
		stop;
		Water:
			TNT1 A 0 A_Jump(128, "Water2");
		Water1:
			GUTS GH 10;
			stop;
			
		Water2:
			GUTS IJ 10;
			stop;
	}
}

































CLASS BurningFlyingMeatPiece : doomb_body_base { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 16;
		Scale 0.8;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		BounceFactor 0.4;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "null");
			XME1 ABCD 2 doomb_show_effect("FlameTrails", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnProjectile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			XME1 E 1 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			XME1 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 7 doomb_show_effect("FlameTrails", velocity: (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			XME1 E 9009;
			TNT1 A 1;
		Stop;
	}
}





CLASS Teeth : ACTOR { 
	Default {
		
		Height 2;
		Radius 2;
		Speed 6;
		Scale 0.7;
		+DOOMBOUNCE;
		- NOGRAVITY;
		+WINDTHRUST;
		+CLIENTSIDEONLY;
		+MOVEWITHSECTOR;
		+MISSILE;
		+NOBLOCKMAP;
		-DROPOFF;
		+NOTELEPORT;
		+FORCEXYBILLBOARD;
		+NOTDMATCH;
		+GHOST;
	}
	States
	{
		Spawn:
			XTET ABCDABCDABCDABCDABCDABCDABCDABCDABCD 5;
			Stop;
			
		Death:
			XTET "#" 250;
			stop;
	}
}


CLASS TeethNoBounce: Teeth { 
	Default {
		
		-DOOMBOUNCE;
	}
}











































CLASS Ashes1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		Speed 5;
		Gravity 0.2;
		DeathSound "";
		SeeSound "";
		+DOOMBOUNCE;
		+DONTSPLASH;
		BounceFactor 0.01;
		Decal "";
		Scale 1.0;
	}
	States
	{
		Spawn:
			tnt1 a 0 nodelay a_jump(126, "spawn2");
		mini:
			ASHZ ABCB 3;
			Loop;

		Spawn2:
			ASHY ABCB 3;
			Loop;

		Death:
			"####" "#" 400;
			Stop;
	}
}










CLASS BasicMarineGib1: actor { 
	Default {
		
		Radius 6;
		Height 6;
		+NOBLOCKMAP;
		+CLIENTSIDEONLY;
		Mass 50;
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_SetAngle(random(0, 359));
			TNT1 A 0 A_Recoil(3);
			XDMG A -1 {frame = random(0, 3);}
			Stop;
	}
}




	   
CLASS XDeathSkinPiece1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		Radius 2;
		Height 2;
		Speed 10;
		Scale 1.0;
		Mass 1;
		SeeSound "";
		DeathSound "";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			XSKI A 4;
			Loop;
		Death:
			XSKI B 1;
			XSKI B -1;
			Stop;
			TNT1 A 1;
		Underwater:
		Splash:
			Goto Death;
	}
}	


CLASS XDeathSkinPiece2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		
		Radius 2;
		Height 2;
		Speed 10;
		Scale 1.0;
		Mass 1;
		SeeSound "";
		DeathSound "";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			XSKI C 4;
			Loop;
		Death:
			XSKI D 1;
			XSKI D -1;
			Stop;
			TNT1 A 1;
		Underwater:
		Splash:
			Goto Death;
	}
}	   
