CLASS BigGibBase : doomb_body_base { 
	Default {
		Radius 10;
		Height 10;
		+CLIENTSIDEONLY;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+DONTSPLASH;
		+NOBLOCKMONST;
		-NOBLOCKMAP;
		+GHOST;
		+THRUACTORS;
		+FLOORCLIP;
		+SLIDESONWALLS;
		+FORCEXYBILLBOARD;
		DamageFactor "CauseObjectsToSplash", 0.0;
		DamageFactor "GibRemoving", 0.5;
		//+SOLID
		-SOLID;
		+SHOOTABLE;
		damagefactor "Crush", 50.0;
		damagefactor "Plasma", 20.0;
		damagefactor "TeleportRemover", 1000.0;
		painchance "Flames", 0;
		painchance "Fire", 0;
		painchance "Burn", 0;
		painchance "KillMe", 0;
		damagefactor "Kick", 3.0;
		damagefactor "SuperKick", 3.0;
		damagefactor "punch", 2.0;
		Mass 1000;
		Health 100;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0 ;
		damagefactor "KillMe", 0.0 ;
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		damagefactor "Trample", 5000.0;
		painchance 255;
	}
	States 
	{
		Spawn:
			TNT1 A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
			
			
		Death:
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("XDeathSkinPiece2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeathSkinPiece1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("SmallSuperGore", 10, 0, random (0, 360), 2, random (10, 170));
			Stop;
			
		Death.plasma:
		Death.Fire:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(128, "DeathFire2");
			TNT1 A 0 doomb_spawn_burned_flesh();
			EXPL AAA 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
			
		DeathFire2:
			TNT1 A 0 doomb_spawn_burned_flesh();
			EXPL AAA 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.Trample:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		Death.Crush:
		Death.Stomp:
		Death.SuperPunch:
		Death.punch:
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 30));
			TNT1 AAAA 0 A_SpawnProjectile ("BloodMist", 5, 0, random (0, 360), 2, random (0, 30));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("XDeathSkinPiece2", 5, 0, random (0, 360), 2, random (10, 30));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeathSkinPiece1", 5, 0, random (0, 360), 2, random (10, 130));
			TNT1 AAAA 0 A_SpawnProjectile ("SmallSuperGore", 10, 0, random (0, 360), 2, random (10, 30));
			TNT1 A 0 A_SpawnItem("SplatteredSmall");
			XME2 L 1;
			XME2 L -1;
			Stop;
		Death.TeleportRemover:
			TNT1 A 0;
			TNT1 A 0 {bNOCLIP = true;}
			TNT1 A 0 {bSHOOTABLE = false;}
			TNT1 A 0 A_NoBlocking;
			Stop;
		Death.GibRemoving:
			TNT1 A 0;
			TNT1 A 0 {bNOCLIP = true;}
			TNT1 A 0 {bSHOOTABLE = false;}
			TNT1 A 0 A_NoBlocking;
			Stop;
			
		Death.Desintegrate:
			TNT1 A 0;
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodFake", 0, 0, random (0, 360), 2, random (0, 90));
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 7, 0, random (0, 360), 2, random (30, 60));
			TNT1 A 0 A_SpawnProjectile ("BloodMistSmall", 7, 0, random (0, 360), 2, random (30, 60));
			Stop;
			
	}
	
}

CLASS LimbBase: BigGibBase { 
	Default {
		Radius 6;
		Height 10;
		Mass 1000;
		Painchance 256;
		Health 35;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+SHOOTABLE;
		-CLIENTSIDEONLY;
		+NOBLOCKMONST;
		//+SOLID
		+THRUACTORS;
		+FLOORCLIP;
		damagefactor "Crush", 50.0;
		DeathSound "misc/xdeath4";
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0 ;
		damagefactor "Taunt", 0.0 ;
		damagefactor "KillMe", 0.0;
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		//damagefactor "Plasma", 99000.0
		damagefactor "Trample", 2.0;
		damagefactor "Kick", 9.0;
		damagefactor "Explosive_Impact", 0.1;
		damagefactor "Explosive_Impact", 9.1;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		damagefactor "Plasma", 20.0;
		painchance 255;
	}
	States
	{
		Spawn:
			TNT1 A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XDT3 BCDEFGH 3;
		Death.Crush:
			TNT1 A 1 A_SpawnProjectile ("XDeath1", 5, 5, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 5, -5, random (0, 360), 2, random (0, 160));
			
			CRSB A 9009;
			Stop ;
			Stop;
	}
	
}		

CLASS TinyGib : ACTOR { 
	Default {
		
		Radius 2;
		Height 8;
		Speed 6;
		Mass 1;
		gravity 0.5;
		Scale 0.8;
		Decal "BrutalBloodSplat";
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+NOBLOCKMONST;
		seesound "bloood";
		deathsound "bloood";
	}
	States
	{
		Spawn:
			TNT1 A 1;
			Loop;
	}
}



CLASS BloodTrails : ACTOR { 
	Default {
		
		Decal "BrutalBloodSplat";
		
		Alpha 0.4;
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		Gravity 0.05;
		+NOCLIP;
		+DontSplash;
		-EXPLODEONWATER;
		-ALLOWPARTICLES;
		+CLIENTSIDEONLY;
		-NOGRAVITY;
		Scale 1.2;
	}
	states
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 AAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 180));
			stop;
	}
}



CLASS GreenBloodTrail : ACTOR { 
	Default {
		
		-NOGRAVITY;
		+NOCLIP;
		radius 16;
		height 16;
		gravity 0.5;
		Scale 1.5;
	translation "168:191=112:127","16:47=120:127";
	+FORCEXYBILLBOARD;
	+NOBLOCKMAP;
	}
states
	{
Spawn:
	TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
	TNT1 A 0;
	TNT1 A 0 Thing_ChangeTid(0,386);
	BLOD ABCD 2;
	stop;
Splash:
	TNT1 A 0;
	Stop;
}
}


CLASS BlueBloodTrail : ACTOR { 
	Default {
 
-NOGRAVITY
+NOCLIP
radius 16;
height 16;
gravity 0.5;
Scale 1.5;
translation "168:191=192:207","16:47=240:247";
decal "CacoBloodSplat";
+FORCEXYBILLBOARD
	}
states
	{
	Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		TNT1 A 0;
		TNT1 A 0 Thing_ChangeTid(0,386);
		BLOD ABCD 2;
		stop;
    Splash:
        TNT1 A 0;
        Stop;
	}
}



CLASS XDeath1 : ACTOR { 
	Default {
 
    Radius 8;
    Height 8;
    Speed 10;
    Scale 1.2;
	Mass 1;
    +NOBLOCKMAP
	+MISSILE
    +NOTELEPORT
    +MOVEWITHSECTOR
    +CLIENTSIDEONLY
    +BLOODLESSIMPACT 
	-DONTSPLASH
	+THRUGHOST
	+thrUACTORS
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			BLOD A 4 A_SpawnProjectile ("Brutal_LiquidBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XDT1 EFGHIJKL 5;
			Stop;
			TNT1 A 1;
		Underwater:
		Splash:
			BLUD C 0 ThrustThingZ (0,35,1,0);
			XDT1 AB 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			BLUD C 0 ThrustThingZ (0,35,1,0);
			XDT1 CD 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
	}
}

CLASS XDeath2: XDeath1 { 
	Default {
		
		+CLIENTSIDEONLY;
		+DONTSPLASH;
		Speed 10;
		Gravity 0.4;
		DeathSound "misc/xdeath2";
		Decal "BrutalBloodSuper";
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME1 ABCD 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CheckFloor("SpawnFloor");
			TNT1 A 0 A_SpawnItemEx ("CeilBloodCheckerLarge",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("DetectCeilXDeath2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		SpawnFloor:
			XME1 E 1;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			XME1 E 3;
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		Living:
			XME1 E 600;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "Vanish");
			Loop;
		Vanish:
			TNT1 A 5;
			Stop;
	}
}


CLASS XDeath2b: XDeath2 { 
	Default {
		
		Speed 4;
	}
}

CLASS XDeath3: XDeath1 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal "BrutalBloodSuper";
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME2 ABCD 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_CheckFloor("SpawnFloor");
			TNT1 A 0 A_SpawnItemEx ("CeilBloodCheckerLarge",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("DetectCeilXDeath3",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		SpawnFloor:
			XME2 E 1;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			XME2 E 3;
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		Living:
			XME2 E 600;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "Vanish");
			Loop;
		Vanish:
			TNT1 A 5;
			Stop;
	}
}

CLASS XDeath3b: XDeath3 { 
	Default {
		
		Speed 4;
	}
}

CLASS XDeath4: XDeath1 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 1.1;
		+DOOMBOUNCE;
		BounceFactor 0.3;
		wallbouncefactor 0.2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME3 ABCDEFGH 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Jump(255, "Death1", "Death2");
			GOto Death1;
			
		Death1:
			TNT1 A 0;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			XME3 GH 3;
			XME3 A 1;
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		Living1:
			XME3 A 600;//duration
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "Vanish");
			Loop;
		Death2:
			XME3 I 1;
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XME3 I 1;
		Living2:
			XME3 I 600;//duration
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "Vanish");
			Loop;
		Vanish:
			TNT1 A 1;
			Stop;
	}
}


CLASS XDeath5: XDeath1 { 
	Default {
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME5 ABCD 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			XME5 E 3;
		Living:
			XME5 E 800;//duration
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "Vanish");
			Loop;
		Vanish:
			TNT1 A 1;
			Stop;
			
	}
}


CLASS XDeathOrgan1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Scale 0.9;
		Speed 4;
	}
	States
	{
		Spawn:
			XME8 A 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			XME8 A 1;
			XME8 A -1;
			Stop;
	}
}



CLASS XDeathOrgan2: XDeathOrgan1 { 
	Default {
		
	}
	States
	{
		Spawn:
			XME8 B 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			XME8 B 1;
			XME8 B -1;
			Stop;
	}
}

CLASS XDeathGuts : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		Scale 1.1;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME4 AAAABBBBCCCCDDDD 2;
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			//TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1)
			XME4 E 9009;
			Stop;
	}
}











/////////////////
//ARMS
/////////////////


CLASS XDeathArm1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.1;
		Speed 8;
		Mass 1;
		gravity 0.5;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		wallbouncefactor 0.2;
		BounceCount 3;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		+EXPLODEONWATER;
		+SKYEXPLODE;
		-DONTSPLASH;
		seesound "bloood";
		deathsound "bloood";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XARM AEBCFDG 5 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			XDT5 I 1;
			XDT5 I 0 A_SpawnItem("Gib_Arm");
			Stop;
	}
}

CLASS Gib_Arm: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			XDT5 I 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma:
		Death.fire:
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
			Stop;
		Death:    
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("GibHand", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("GibArmPart", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
			
		Death.Kick:
		Death.punch:
			XDT5 I 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XARM ABCD 3;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			XARM A 6;
			XARM ABCDABCDABCD 6 A_CheckFloor("Landz");
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_Arm");
			Stop;
	}
}

CLASS XDeathArm1Kicked: XDeathArm1 { 
	Default {
		
		+ACTIVATEMCROSS;
		+ACTIVATEIMPACT;
		+CANUSEWALLS;
	}
	States
	{
		Spawn:
			TNT1 A 0 {bNOCLIP = true;}
			XARM A 2;
			TNT1 A 0 {bNOCLIP = false;}
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XARM ABCD 6 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Goto Spawn+3;
	}
}

CLASS GibArmPart: TinyGib { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			XDT5 Z -1;
			stop;
	}
	
}
CLASS GibHand: TinyGib { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			XDT5 Y 1;
			Loop;
		Death:
			XDT5 Y 1;
			Loop;
			
	}
	
}


CLASS XDeathBullArm1: XDeathArm1 { 
	Default {
		
		Scale 1.0;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		wallbouncefactor 0.2;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HND8 ABCDEFGH 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
			
		Death.plasma:
		death.Fire:
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedDemonArm", 32, 0, random (0, 360), 2, random (0, 160));
			Stop;
		Death:
			HND8 I 1;
			HND8 A 0 A_SpawnItem("Gib_DemonArm",0,0,0,1);
			Stop;
	}
}


CLASS XDeathDemonArm: XDeathBullArm1 { 
	Default {
		
		Scale 1.0;
	}
}

CLASS Gib_DemonArm: LimbBase { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			HND8 GH 2;
			Goto Spawn1;
			
		Spawn1:
			HND8 I 40000;
			Loop;
		Death:    
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("GibDemonHand", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("GibDemonArmPart", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Punch:
			HND8 AA 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathBullArm1Kicked", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			HND8 ABCDEFGH 2;
			Goto Spawn1;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			HND8 A 5;
			HND8 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_DemonArm");
			Stop;
			
	}
	
}

CLASS XDeathBullArm1Kicked: XDeathBullArm1 { 
	Default {
		
		+ACTIVATEMCROSS;
		+ACTIVATEIMPACT;
		+CANUSEWALLS;
	}
}

CLASS GibDemonArmPart: TinyGib { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			HND8 Z 1;
			Loop;
		Death:
			HND8 Z 1;
			Loop;
			
	}
	
}
CLASS GibDemonHand: TinyGib { 
	Default {
		
		Scale 0.9;
	}
	States
	{
		Spawn:
			HND8 Y 1;
			Loop;
		Death:
			HND8 Y 1;
			Loop;
			
	}
	
}








/////////////////////
//LEGS
/////////////////////


















//////////////
//GUTS
//////////////


CLASS XDeathStomach: XDeathArm1 { 
	Default {
		
		-DOOMBOUNCE;
		BounceFactor 0.0;
		Speed 2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XSTO A 24 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XSTO EEEEEEEEE 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			XSTO E 9009;
			Stop;
	}
}


CLASS XDeathHalfMarine : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 4;
		Mass 8;
		BounceFactor 0.2;
		BounceCount 3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HPLA A 12 A_SpawnProjectile("Brutal_FlyingBloodTrail",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			HPLA A 0 A_SpawnItem("HalfMarineGib",0,0,0,1);
			Stop;
	}
}

CLASS HalfMarineGib: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			HPLA A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop   ;
	}
	
}


	   





CLASS RipUndeadMarine : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 4;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			UDM3 E 4 A_SpawnProjectile("Brutal_FlyingBloodTrail",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			UDM3 E 9009;
			Stop;
	}
}

CLASS XDeathMeat2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 11;
		Mass 1;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT5 D 2;
		Death:
			XDT5 D 9009;
			Stop;
	}
}

CLASS XDeathBrain1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 13;
		Mass 1;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+MISSILE;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDB5 ABCD 6;
			Loop;
		Death:
			TNT1 A 0 A_Jump(128, "Death2");
			XDT5 B 9009;
			Stop;
		Death2:
			XDT5 O 9009;
			Stop;
	}
}

CLASS XDeathBrain2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 12;
		Mass 1;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+MISSILE;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDB5 EFGH 6;
			Loop;
		Death:
			XDT5 C 1;
			XDT5 C 9009;
			Stop;
	}
}

CLASS XDeathSmashedBrain : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 10;
		Mass 1;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			BRS1 A 4;
		Death:
			BRS1 A 9009;
			Stop;
	}
}

CLASS XDeathStomachHeavy : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 2;
		Mass 4;
		Decal "BrutalBloodSplat";
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			XDT5 F 1;
			Loop;
		Death:
			XDT5 F 1;
			XDT5 F 9009;
			Stop;
	}
}

CLASS XDeathTripe : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 13;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			XDT5 H 1;
			Loop;
		Death:
			XDT5 H 1;
			XDT5 H 9009;
			Stop;
	}
}

CLASS XDeathTripeHeavy : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.8;
		Speed 2;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			XDT5 H 1;
			Loop;
		Death:
			XDT5 H 1;
			XDT5 H 9009;
			Stop;
	}
}




CLASS XDeathGreen : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 18;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal "GreenBloodSuper";
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 4 A_SpawnProjectile("GreenBloodTrail",0,0,180,2);
			Loop;
		Death:
			TNT1 A 9009;
			Stop;
	}
}

CLASS XDeathBlue1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal "BlueBloodSplat";
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT6 A 6 A_SpawnProjectile("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			Loop;
		Death:
			XDT6 A 9009;
			Stop;
	}
}

CLASS XDeathBlue2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal "BlueBloodSplat";
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT6 B 6 A_SpawnProjectile("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			Loop;
		Death:
			XDT6 B 9009;
			Stop;
	}
}

CLASS XDeathBlue3 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal "BlueBloodSuper";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT6 C 6 A_SpawnProjectile("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			Loop;
		Death:
			XDT6 C 9009;
			Stop;
	}
}

CLASS XDeathBlue4 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal "BlueBloodSuper";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT6 D 6 A_SpawnProjectile("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			Loop;
		Death:
			XDT6 D 9009;
			Stop;
	}
}

CLASS XDeathBlue5 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		Decal "BlueBloodSuper";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDT6 E 6 A_SpawnProjectile("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			Loop;
		Death:
			XDT6 E 9009;
			Stop;
	}
}

CLASS SpiderLeg : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		BounceFactor 0.3;
		BounceCount 3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDSL ABCDEFGH 2;
			Loop;
		Death:
			XDSL I 9009;
			Stop;
	}
}

CLASS Instestin : ACTOR { 
	Default {
		
		Radius 8;
		Height 12;
		Speed 6;
		Mass 1;
		BounceFactor 0.4;
		Renderstyle "Translucent";
		Alpha 0.9;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
		-EXPLODEONWATER;
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
		Scale 1.1;
	}
	States
	{
		Spawn:
			GUTS ABCD 8;
			Loop;
		Death:
			
			GUTS E 1;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Water");
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			Goto Rest;
			
			
		Rest:
			TNT1 A 0;
			TNT1 A 0 A_Jump(255, "Rest1", "Rest2");
		Rest1:
			GUTS E 800;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DoNothing");
			Loop;
			
		Rest2:
			GUTS F 800;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DoNothing");
			Loop;
		DoNothing:
			TNT1 A 0;
			Stop;
			
		Water:
			TNT1 A 0;
			TNT1 A 0 A_Jump(128, "Water2");
			Goto Water1;
			
		Water1:
			GUTS GH 10;
			//TNT1 A 0 A_JumpIf(waterlevel == 0, "Death")
			Loop;
			
		Water2:
			GUTS IJ 10;
			//TNT1 A 0 A_JumpIf(waterlevel == 0, "Death")
			Loop;
	}
}




























CLASS XDeathChaingunguyHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		BounceCount 3;
		Scale 1.0;
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			CHHE AB 3;
			CHHE CDEFGH 3;
			Loop;
		Death:
			XHE2 E 0;
			XHE2 E 0 A_SpawnItem("ChaingunguyHead",0,0,0,1);
			Stop;
	}
}



CLASS XDeathChaingunguyHeadBeheaded: XDeathChaingunguyHead { 
	Default {
		
		Speed 5;
		Gravity 0.5;
	}
}


CLASS XDeathChaingunguyHeadOnXDeath: XDeathChaingunguyHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ChaingunguyHeadExplode");
			Stop;
			
	}
	
}
CLASS ChaingunguyHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		+SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Radius 10;
		
		Mass 60;
		Health 40;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(256, "Spawn1", "SPawn2");
		Spawn1:
			CHHE A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Spawn2:  
			CHHE E 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ChaingunguyHeadExplode");
			Stop;
		Death.Trample:
		Crush:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.SuperPunch:
		Death.Kick:
			CHHE EE 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathChaingunguyHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			CHHE ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			CHHE ABCDEFGH 3;
			XDT5 I 0 A_SpawnItem("ChaingunguyHead");
			Stop;
			
			
	}
	
}

CLASS XDeathChaingunguyHeadKicked: XDeathChaingunguyHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
	}
}




CLASS XDeathImpHead: XDeathChaingunguyHead { 
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			XHE4 AB 3;
			XHE4 CDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XHE4 E 1;
			XHE4 E 1 A_SpawnItem("ImpHead",0,0,0,1);
			Stop;
	}
}


CLASS XDeathImpHeadBeheaded: XDeathImpHead { 
	Default {
		
		Speed 5;
		Gravity 0.5;
	}
}

CLASS XDeathImpHeadOnXDeath: XDeathImpHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ImpHeadExplode");
			Stop;
			
	}
	
}
CLASS ImpHead : LimbBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			XHE4 C 1;
			XHE4 C -1;
			Stop;
		Spawn2:
			XHE4 G 1;
			XHE4 G -1;
			Stop;
		Spawn3:
			XHE4 H 1;
			XHE4 H -1;
			Stop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ImpHeadExplode");
			Stop;
		Death.SuperPunch:
		Death.Kick:
			XHE4 EE 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE4 ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE4 ABCDEFGH 3;
			XDT5 I 0 A_SpawnItem("ImpHead");
			Stop;
			
			
	}
	
}


CLASS BurningFlyingMeatPiece : doomb_body_base { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 16;
		Scale 0.8;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		BounceFactor 0.4;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			XME1 ABCD 2 doomb_show_effect("FlameTrails", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnProjectile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			XME1 E 1 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			XME1 EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 7 doomb_show_effect("FlameTrails", velocity: (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			XME1 E 9009;
			TNT1 A 1;
			Stop;
		Splash:
			TNT1 A 0;
			Stop;
	}
}





CLASS Teeth : ACTOR { 
	Default {
		
		Height 2;
		Radius 2;
		Speed 6;
		Scale 0.7;
		+DOOMBOUNCE;
		- NOGRAVITY;
		+WINDTHRUST;
		+CLIENTSIDEONLY;
		+MOVEWITHSECTOR;
		+MISSILE;
		+NOBLOCKMAP;
		-DROPOFF;
		+NOTELEPORT;
		+FORCEXYBILLBOARD;
		+NOTDMATCH;
		+GHOST;
	}
	States
	{
		Spawn:
			XTET ABCDABCDABCDABCDABCDABCDABCDABCDABCD 5;
			Stop;
			
		Death:
			LCPJ A 0 A_Jump(256,"Rest1","Rest2");
		Rest1:
			XTET B 250;
			stop;
			
		Rest2:
			XTET D 250;
			stop;
	}
}


CLASS TeethNoBounce: Teeth { 
	Default {
		
		-DOOMBOUNCE;
	}
}


CLASS XDeathHellKnightHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			HKHE ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			HKHE E 1;
			HKHE E 1 A_SpawnItem("HellKnightHead",0,0,0,1);
			Stop;
	}
}







CLASS XDeathPinkyDemonHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Speed 10;
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			DEMH AB 3;
			DEMH CDEFGH 3;
			Loop;
		Death:
			DEMH I 1;
			DEMH I 1 A_SpawnItem("PinkyDemonHead",0,0,0,1);
			Stop;
	}
}



CLASS PinkyDemonHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 60;
		Health 60;
		Scale 1.5;
	}
	States
	{
		Spawn:
			DEMH I 4000 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
			
		Death:
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_SpawnProjectile ("Brains2", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_SpawnProjectile ("Brains3", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_SpawnProjectile ("Brains4", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_SpawnProjectile ("Brains5", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 AAAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 5, 0, random (0, 360), 2, random (60, 140));
			Stop;
		Death.Trample:
		Crush:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			DEMH I 5;
			DEMH I 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 doomb_spawn_burned_flesh();
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.SuperPunch:
		Death.Kick:
			DEMH A 1 A_Pain;
			DEMH A 1 A_FaceTarget;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathPinkyDemonHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			DEMH ACEGI 3;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			DEMH ABCDEFGH 3;
			DEMH I 0 A_SpawnItem("PinkyDemonHead");
			Stop;
			
			
	}
	
}


CLASS XDeathPinkyDemonHeadKicked: XDeathPinkyDemonHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		Scale 1.3;
		BounceFactor 0.4;
	}
}




CLASS HellKnightHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		-NOBLOCKMAP;
		+SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Radius 10;
		Mass 60;
		Health 60;
		Scale 1.0;
	}
	States
	{
		Spawn:
			HKHE G 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("HellKnightHeadExplode", 0, 10);
			Stop;
		Death.Trample:
		Crush:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.SuperPunch:
		Death.Kick:
			HKHE DD 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			HKHE ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			HKHE ABCDEFGH 3;
			HKHE H 0 A_SpawnItem("HellKnightHead");
			Stop;
			
			
	}
	
}

CLASS XDeathHellKnightHeadKicked: XDeathHellKnightHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}





CLASS XDeathBaronHead5: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			XHE5 ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XHE5 A 1;
			XHE5 A 1 A_SpawnItem("BaronHead",0,0,0,1);
			Stop;
	}
}



CLASS BaronHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 60;
		Health 60;
		Scale 1.2;
	}
	States
	{
		Spawn:
			XHE5 A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("BaronOfHellHeadExplode", 0, 5);
			Stop;
		Death.Trample:
		Crush:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.SuperPunch:
		Death.Kick:
			XHE5 A 1 A_Pain;
			XHE5 A 1 A_FaceTarget;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathBaronHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE5 ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE5 ABCDEFGH 3;
			Stop;
			
			
	}
	
}

CLASS XDeathBaronHeadKicked: XDeathBaronHead5 { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}








CLASS XDeathRevenantHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			XHE6 ABCD 6;
			Loop;
		Death:
			XHE6 A 1;
			XHE6 A 1 A_SpawnItem("RevenantHead",0,0,0,1);
			Stop;
	}
}




CLASS RevenantHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		BloodType "RevenantBlood";
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 60;
		Health 60;
		Scale 1.0;
	}
	States
	{
		Spawn:
			XHE6 B 1900;
			Loop;
			
		Death.Trample:
		Crush:
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death:
		Death.SuperPunch:
		Death.Kick:
			XHE6 A 1 A_Pain;
			XHE6 A 1 A_FaceTarget;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathRevenantHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE6 ABCD 3;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			Goto Fly293;
		Fly293:
			XHE6 ABCD 6;
			TNT1 A 0 A_JumpIf(vel.z == 0, "Land293");
			
		Land293:
			XHE6 I 0 A_SpawnItem("XDeathRevenantHead");
			Stop;
			
			
	}
	
}

CLASS XDeathRevenantHeadKicked: XDeathRevenantHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}

CLASS XDeathRevenantHeadKicked2: XDeathRevenantHead { 
	Default {
		
		+BOUNCEONACTORS;
		+NOEXTREMEDEATH;
		Damage 15;
		Speed 24;
		BounceFactor 0.2;
	}
}








CLASS XDeathdoomb_fatsoHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			XHE7 ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XHE5 A 1;
			XHE5 A 1 A_SpawnItem("doomb_fatsoHead",0,0,0,1);
			Stop;
	}
}



CLASS doomb_fatsoHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 120;
		Health 60;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
			TNT1 A 0 A_JUmp(128, "Spawn2");
			
		Spawn1:
			XHE7 B 1900;
			Loop;
			
		Spawn2:
			XHE7 G 1900;
			Loop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("doomb_fatsoHeadExplode", 0, 10);
			Stop;
		Death.Trample:
		Crush:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0;
			Stop;
		Death.SuperPunch:
		Death.Kick:
			XHE7 A 1 A_Pain;
			XHE7 A 1 A_FaceTarget;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathdoomb_fatsoHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE7 ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE7 ABCDEFGH 3;
			XHE7 I 0 A_SpawnItem("doomb_fatsoHead");
			Stop;
			
			
	}
	
}


CLASS XDeathdoomb_fatsoHeadKicked: XDeathdoomb_fatsoHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}







CLASS XDeathCyberdemonHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		-DOOMBOUNCE;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			XHE8 ABCDEFGH 3 A_SpawnProjectile ("Brutal_FlyingBlood", 1, 0, random (0, 360), 2, random (20, 40));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XHE8 B 1;
			XHE8 B 1 A_SpawnItem("CyberdemonHead",0,0,0,1);
			Stop;
	}
}


CLASS CyberdemonHead: LimbBase { 
	Default {
		
		-CLIENTSIDEONLY;
		Radius 20;
		Mass 220;
		Health 100;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XHE8 C 1;
			XHE8 C -1;
			Loop;
			
		Death:
		Death.Trample:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("BloodMistBig", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAA 0 A_SpawnProjectile ("Brains6Big", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("Brains7Big", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath3b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath2b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 A 0 A_Stop;
			XHE8 I 10;
			XHE8 I -1;
			Stop;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			XHE8 ABCDEFGH 3;
			XHE8 B 0 A_SpawnItem("CyberdemonHead");
			Stop;
			
	}
	
}


CLASS XDeathCyberdemonTorso: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		-DOOMBOUNCE;
		Scale 1.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			CYGT ABCDEFGH 3 A_SpawnProjectile ("Brutal_FlyingBlood", 1, 0, random (0, 360), 2, random (20, 40));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			CYGT B 1;
			CYGT B 1 A_SpawnItem("CyberdemonTorso",0,0,0,1);
			Stop;
	}
}


CLASS CyberdemonTorso: LimbBase { 
	Default {
		
		-CLIENTSIDEONLY;
		Radius 20;
		Mass 220;
		Health 100;
		Scale 1.4;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			CYGT B 1;
			CYGT B -1;
			Loop;
			
		Death:
		Death.Trample:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("BloodMistBig", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath3b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath2b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 A 0 A_Stop;
			TNT1 I 10;
			TNT1 I -1;
			Stop;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			CYGT ABCDEFGH 3;
			XHE8 B 0 A_SpawnItem("CyberdemonTorso");
			Stop;
			
	}
	
}

CLASS XDeathCyberdemonPiece: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		-DOOMBOUNCE;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			CYGP ABCDEFGH 3 A_SpawnProjectile ("Brutal_FlyingBlood", 1, 0, random (0, 360), 2, random (20, 40));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			CYGP B 1;
			CYGP B 1 A_SpawnItem("CyberdemonPiece",0,0,0,1);
			Stop;
	}
}


CLASS CyberdemonPiece: LimbBase { 
	Default {
		
		-CLIENTSIDEONLY;
		Radius 20;
		Mass 220;
		Health 100;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			CYGP E 1;
			CYGP E -1;
			Loop;
			
		Death:
		Death.Trample:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("BloodMistBig", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath3b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath2b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 A 0 A_Stop;
			TNT1 I 10;
			TNT1 I -1;
			Stop;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			CYGP ABCDEFGH 3;
			CYGP B 0 A_SpawnItem("CyberdemonPiece");
			Stop;
			
	}
	
}



CLASS XDeathCyberdemonARm: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		-DOOMBOUNCE;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			CYGA ABCDEFGH 3 A_SpawnProjectile ("Brutal_FlyingBlood", 1, 0, random (0, 360), 2, random (20, 40));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			CYGA B 1;
			CYGA B 1 A_SpawnItem("CyberdemonArm",0,0,0,1);
			Stop;
	}
}


CLASS CyberdemonArm: LimbBase { 
	Default {
		
		-CLIENTSIDEONLY;
		Radius 20;
		Mass 220;
		Health 100;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			CYGA C 1;
			CYGA C -1;
			Loop;
			
		Death:
		Death.Trample:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("BloodMistBig", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath3b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath2b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 A 0 A_Stop;
			TNT1 I 10;
			TNT1 I -1;
			Stop;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			CYGA ABCDEFGH 3;
			CYGA B 0 A_SpawnItem("CyberdemonArm");
			Stop;
			
	}
	
}


CLASS XDeathCyberdemonGun: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		+SKYEXPLODE;
		-DOOMBOUNCE;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			CYGG ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			CYGG B 1;
			CYGG B 1 A_SpawnItem("CyberdemonGun",0,0,0,1);
			Stop;
	}
}


CLASS CyberdemonGun: LimbBase { 
	Default {
		
		-CLIENTSIDEONLY;
		Radius 20;
		Mass 220;
		Health 100;
		Scale 1.2;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			CYGG E 1;
			CYGG E -1;
			Loop;
			
		Death:
		Death.Trample:
			TNT1 A 0 A_GiveToTarget("BootsSmearedWithRedBlood", 6);
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("BloodMistBig", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath3b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath2b", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 A 0 A_Stop;
			TNT1 I 10;
			TNT1 I -1;
			Stop;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			CYGG ABCDEFGH 3;
			CYGG B 0 A_SpawnItem("CyberdemonGun");
			Stop;
			
	}
	
}





CLASS Ashes1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		Speed 5;
		Gravity 0.2;
		DeathSound "";
		SeeSound "";
		+DOOMBOUNCE;
		+DONTSPLASH;
		BounceFactor 0.01;
		Decal "";
		Scale 1.0;
	}
	States
	{
		Spawn:
			ASHZ ABCB 3;
			Loop;
		Death:
			ASHZ B 400;
			Stop;
		Splash:
			TNT1 A 0;
			TNT1 A 0;
			Stop;
	}
}


CLASS Ashes2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		Speed 5;
		Gravity 0.2;
		+DONTSPLASH;
		DeathSound "";
		SeeSound "";
		Decal "";
		Scale 1.0;
	}
	States
	{
		Spawn:
			ASHY ABCB 3;
			Loop;
		Death:
			ASHY B 400;
			Stop;
		Splash:
			TNT1 A 0;
			TNT1 A 0;
			Stop;
	}
}

CLASS XDeathArachnotronHead : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		Speed 12;
		Gravity 0.9;
		+DONTSPLASH;
		DeathSound "";
		SeeSound "";
		+SKYEXPLODE;
		Decal "";
		Scale 1.0;
	}
	States
	{
		Spawn:
			NAHA ABCDEFGH 4;
			Loop;
		Death:
			TNT1 A 0;
			//TNT1 A 0 A_Jump(128, "CleanDeath")
			TNT1 A 0 A_SpawnItem("CrawlingDyingSpider");
			Stop;
		CleanDeath:
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			NAHC IJKLMN 5;
			NAHC N -5;
			Stop;
			Stop;
	}
}









CLASS BasicGib : ACTOR { 
	Default {
		
		Radius 6;
		Height 6;
		+NOBLOCKMAP;
		+CLIENTSIDEONLY;
		Mass 50;
	}
	States
	{
		Spawn:
			TNT1 A 1;
			Stop;
	}
}




CLASS BasicMarineGib1: BasicGib { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_SetAngle(random(0, 359));
			TNT1 A 0 A_Recoil(3);
			XDMG A -1;
			Stop;
	}
}


CLASS BasicMarineGib2: BasicGib { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_SetAngle(random(0, 359));
			TNT1 A 0 A_Recoil(3);
			XDMG B -1;
			Stop;
	}
}


CLASS BasicMarineGib3: BasicGib { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_SetAngle(random(0, 359));
			TNT1 A 0 A_Recoil(3);
			XDMG C -1;
			Stop;
	}
}


CLASS BasicMarineGib4: BasicGib { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_SetAngle(random(0, 359));
			TNT1 A 0 A_Recoil(3);
			XDMG D -1;
			Stop;
	}
}


CLASS XDeathHalfDemon : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			SARC E 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			SARC F 1 A_SpawnItem("Gib_HalfDemon",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS Gib_HalfDemon: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			SARC F 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop   ;
	}
	
}	   
	   
CLASS XDeathSkinPiece1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		Radius 2;
		Height 2;
		Speed 10;
		Scale 1.0;
		Mass 1;
		SeeSound "";
		DeathSound "";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			XSKI A 4;
			Loop;
		Death:
			XSKI B 1;
			XSKI B -1;
			Stop;
			TNT1 A 1;
		Underwater:
		Splash:
			Goto Death;
	}
}	


CLASS XDeathSkinPiece2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		
		Radius 2;
		Height 2;
		Speed 10;
		Scale 1.0;
		Mass 1;
		SeeSound "";
		DeathSound "";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			XSKI C 4;
			Loop;
		Death:
			XSKI D 1;
			XSKI D -1;
			Stop;
			TNT1 A 1;
		Underwater:
		Splash:
			Goto Death;
	}
}	   











CLASS XDeathPainElementalNew1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		Mass 1;
		
		
		Speed 12;
		Gravity 0.4;
		Decal "BrutalBloodSplat";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath4";
	Translation "64:72=133:142", "73:75=13:15", "76:79=236:239";
	Scale 1.1;
	}
    States
    {
Spawn:
	TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
	CAGI ABCDEFGH 2 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 5, 0, random (0, 360), 2, random (0, 360));
	Loop;
Death:
	
	TNT1 A 0;
	TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
	TNT1 A 0 A_CheckFloor("SpawnFloor");
	TNT1 A 0 A_SpawnItemEx ("CeilBloodLauncher",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItemEx ("DetectCeilXDeath2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	
	//TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1)
	CAGI Q 9009;
	TNT1 A 2;
	Stop;
SpawnFloor:
	CAGI Q 9009;
	TNT1 A 2;
	Stop;
}
}



CLASS XDeathPainElementalNew2: XDeathPainElementalNew1 { 
	Default {
 
    Speed 12;
	Gravity 0.6;
    Decal "BrutalBloodSplat";
    Scale 1.1;
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
        CAGI IJKLMNOP 2 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 5, 0, random (0, 360), 2, random (0, 360));
        Loop;
    Death:
	    
		TNT1 A 0;
        TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
	    TNT1 A 0 A_CheckFloor("SpawnFloor");
		TNT1 A 0 A_SpawnItemEx ("CeilBloodLauncher",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("DetectCeilXDeath2",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		
		//TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1)
        CAGI R 9009;
		TNT1 A 2;
        Stop;
	SpawnFloor:
	    CAGI R 9009;
		TNT1 A 2;
		Stop;
    }
}



CLASS XDeathSpiderNew1: XDeathPainElementalNew1 { 
	Default {
 
    Scale 0.8;
	Speed 7;
	}
}

CLASS XDeathSpiderNew2: XDeathPainElementalNew2 { 
	Default {
 
    Scale 0.7;
	Speed 7;
	}
}
