CLASS doomb_fatso : doomb_monster_base Replaces Fatso { 
	Default {
		
		doomb_monster_base.headshot_multiplier 2;
		doomb_monster_base.head_starting_position 58;//so that if someone forgot to define this number monster dont get headshot from every attack
		doomb_monster_base.legs_height_max -1;//same for legs
		
		speed 8;
		Scale 1.2;
		MaxStepHeight 16;
		MaxDropOffHeight 24;
		damagefactor "Crush", 10.0;
		damagefactor "Avoid", 0.0;
		PainChance "Kick", 255;
		PainChance "Taunt", 255;
		PainChance "Explosive_Impact", 255;
		damagefactor "TeleportRemover", 0.0;
		damagefactor "GibRemoving", 0.0;
		DamageFactor "CauseObjectsToSplash", 0.0;
		DamageFactor "Shotgun", 0.8;
		PainChance "SSG", 255;
		DamageFactor "SSG", 0.1;
		Radius 48;
		height 64;
		GibHealth 30;
		Health 500;
		Mass 500;
		BloodType "Brutal_Blood",  "SawBlood";
		DropItem "DemonStrengthRune", 5;
		Obituary "%o was incinerated by a doomb_fatso.";
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		+DONTHARMCLASS;
		+THRUGHOST;
	}
	States
	{
		Idle:
		LookingForPlayer:
			TNT1 A 0 A_GiveInventory("SKImp", 1);
			
			FATT B 10 A_Look;
			
			FATT B 10 A_Look;
			
			FATT B 10 A_Look;
			TNT1 A 0 A_SetAngle(angle - 40);
			
			FATT B 10 A_Look;
			
			FATT B 10 A_Look;
			
			FATT B 10 A_Look;
			TNT1 A 0 A_SetAngle(angle + 40);
			
			FATT B 10 A_Look;
			
			FATT B 10 A_Look;
			
			FATT B 10 A_Look;
			
			FATT A 0 A_Wander;
			FATT AA 2 A_Look;
			TNT1 A 0 A_Recoil(-1);
			
			
			FATT B 0 A_Wander;
			FATT BB 2 A_Look;
			TNT1 A 0 A_Recoil(-1);
			
			
			FATT C 0 A_Wander;
			FATT CC 2 A_Look;
			TNT1 A 0 A_Recoil(-1);
			
			
			FATT D 0 A_Wander;
			FATT DD 2 A_Look;
			TNT1 A 0 A_Recoil(-1);
			
			
			
			TNT1 A 0 A_jump(128, "LookingForPlayer");
			
			
			FATT A 0 A_Wander;
			FATT AA 2 A_Look;
			TNT1 A 0 A_Recoil(-1);
			
			
			FATT B 0 A_Wander;
			FATT BB 2 A_Look;
			TNT1 A 0 A_Recoil(-1);
			
			
			FATT C 0 A_Wander;
			FATT CC 2 A_Look;
			TNT1 A 0 A_Recoil(-1);
			
			
			FATT D 0 A_Wander;
			FATT DD 2 A_Look;
			TNT1 A 0 A_Recoil(-1);
			
			Goto LookingForPlayer;
			
			
			
		ForgetTarget:
			TNT1 A 0 A_ClearTarget;
			TNT1 A 0 A_TakeInventory("EnemyMemory", 25);
			TNT1 A 0 A_GiveInventory("LookingForPlayer", 1);
			Goto LookingForPlayer;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_GiveInventory("TargetIsAdoomb_fatso");
			TNT1 A 0 ACS_ExecuteAlways(796, 0, 0, 0, 0);//Check if Vanilla Mode is activated
			
		Spawn2:
			FATT BBBBBBBBBB 10 A_Look;
			Loop;
			
			
		Death.minorhead:
		Death.Headshot:
			TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AAAAAA 0 A_SpawnProjectile ("Xdeath1", 62, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 62, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("Brains2", 62, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("Brains6", 62, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("Brains7", 62, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("doomb_fatsoEyeballs", 62, 0, random (0, 360), 2, random (0, 160));
			FATT KKK 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 50, 0, random (0, 360), 2, random (30, 50));
			FATT LLL 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (30, 50));
			TNT1 A 0 A_Scream;
			FATT MMM 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (20, 50));
			TNT1 A 0 A_NoBlocking;
			FATT NNOOPPQQRRSS 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 20, 0, random (0, 360), 2, random (20, 50));
			FATT TTTTTTTTTTTTTTTTTTTTTTT 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 20, 0, random (0, 360), 2, random (20, 50));
			TNT1 A 0 A_SpawnItem ("DeadFatNoHead", 1);
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			Stop;
			
		Death.decaptate:
			TNT1 AAAAAA 0 A_SpawnProjectile ("Xdeath1", 62, 0, random (50, 130), 2, random (50, 130));
			TNT1 A 0 A_SpawnProjectile ("Xdeathdoomb_fatsoHead", 62, 0, random (50, 130), 2, random (50, 130));
			FATT O 6 A_Scream;
			FATT P 6 A_NoBlocking;
			FATT QRS 6;
			FATT T 1 A_BossDeath;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem ("DeadFatNoHead", 1);
			Stop;
			
			
			
		Death:
			FAT3 A 1 A_Jump(64, "Death2");
			FAT3 B 6 A_Scream;
			FAT3 C 6 A_NoBlocking;
			FAT3 DEF 6;
			FAT3  F 1 A_BossDeath;
			FAT3 F -1;
			Stop;
			
		Death2:
			FATK A 6;
			FATK B 6 A_Scream;
			FATK C 6 A_NoBlocking;
			FATK DEF 6;
			FATK F 1 A_BossDeath   ;
			TNT1 A 0 A_SpawnItem ("DeadFat", 1);
			Stop;
			
		See:
			TNT1 A 0;
			TNT1 A 0 A_TakeInventory("EnemyMemory", 5);
			
		LookingForPlayer:
			TNT1 A 0 A_JumpIfInventory("EnemyMemory", 10, "ForgetTarget");
			TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
			FATT AAA 4 A_Chase;
			
			FATT BB 4 A_Chase;
			
			FATT CC 4 A_Chase;
			
			////TNT1 A 0 A_SpawnItemEx("HeavyFootSteps", 0, 10)
			FATT DD 4 A_Chase;
			
			FATT EE 4 A_Chase;
			
			FATT FF 4 A_Chase;
			TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
			TNT1 A 0 A_CheckSight("LookingForPlayer");
			Goto See;
			
		Missile:
			TNT1 A 0 A_JumpIfCloser(300, "Melee");
			
			
			//TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 0, 5)
			//TNT1 A 0 A_TakeInventory("CantFire", 1)
			//TNT1 A 0 A_SpawnProjectile("MonsterTargetCheck", 34, 0, 0, 0) 
			//TNT1 A 0 A_SpawnProjectile("MonsterTargetCheckFaster", 34, 0, 0, 0)
			FATT G 4 A_FaceTarget;
			//TNT1 A 0 A_JumpIfInventory("CantFire",1, "See")
			TNT1 A 0 A_JumpIfInventory("Enraged", 1, 1);
			FATT G 6 A_FatRaise;
			
			FATT G 10 A_FaceTarget;
			
			TNT1 A 0 A_SpawnProjectile("BigFireBall",30,-25,10,0);
			TNT1 A 0 A_SpawnProjectile("BigFireBall",30,25,0,0);
			FATT H 10 BRIGHT;
			
			FATT IG 5 A_FaceTarget;
			
			TNT1 A 0 A_SpawnProjectile("BigFireBall",30,-25,0,0);
			TNT1 A 0 A_SpawnProjectile("BigFireBall",30,25,-10,0);
			FATT H 10 BRIGHT;
			
			FATT IG 5 A_FaceTarget;
			
			TNT1 A 0 A_SpawnProjectile("BigFireBall",30,-25,4,0);
			TNT1 A 0 A_SpawnProjectile("BigFireBall",30,25,-4,0);
			FATT H 10 BRIGHT;
			
			FATT IG 5;
			Goto See;
			
		Melee:
			
			TNT1 A 0 A_JumpIfInventory("Enraged", 1, 1);
			FATT G 10 A_FatRaise;
			
			FATT G 10 A_FaceTarget;
			
			TNT1 A 0 A_PlaySound("BREATHOF");
			TNT1 A 0 A_SpawnProjectile("FlamethrowerMissile",30,-25,15,0);
			TNT1 A 0 A_SpawnProjectile("FlamethrowerMissile",30,25,-15,0);
			FATT H 10 BRIGHT;
			
			FATT IG 5 A_FaceTarget;
			
			TNT1 A 0 A_PlaySound("BREATHOF");
			TNT1 A 0 A_SpawnProjectile("FlamethrowerMissile",30,-25,15,0);
			TNT1 A 0 A_SpawnProjectile("FlamethrowerMissile",30,25,-15,0);
			FATT H 10 BRIGHT;
			
			FATT IG 5 A_FaceTarget;
			
			TNT1 A 0 A_PlaySound("BREATHOF");
			TNT1 A 0 A_SpawnProjectile("FlamethrowerMissile",30,-25,15,0);
			TNT1 A 0 A_SpawnProjectile("FlamethrowerMissile",30,25,-15,0);
			FATT H 10 BRIGHT;
			
			FATT IG 5 A_FaceTarget;
			Goto See;
		Pain:
			
			FATT J 3;
			FATT J 3 A_Pain;
			Goto See;
			
		Pain.Explosive_Impact:
		Pain.SSG:
			
			
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 {bNOPAIN = true;}
			FAT4 A 4 ThrustThingZ(0,30,0,1);
			FAT4 B 4 A_Pain;
			FAT4 CDDDD 4;
			FAT4 C 4 A_Stop;
			FAT4 BA 4;
			TNT1 A 0 {bNOPAIN = false;}
			Goto See;
			
		Pain.Kick:
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil(2);
			FATT J 9 A_Pain ;
			
			FATT J 8;
		Goto See;
			
			
			
		Death.Fatality:
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_GiveToTarget("GoFatality", 1);
			TNT1 A 0 A_GiveToTarget("FatsoFatality", 1);
			TNT1 A 1 A_BossDeath;
			TNT1 A 0;
			Stop;
			
		Death.cut:
		Death.Saw:
			TNT1 O 0 A_Jump(195, 2);
		Goto Death;
			TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Scream;
			TNT1 O 0 A_NoBlocking;
			FAT2 KL 5 A_SpawnProjectile ("MuchBlood", 75, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("RipGuts", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_BossDeath;
			FAT2 MNOP 5 A_SpawnProjectile ("MuchBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem ("NoGutsFatso", 1);
			Stop;
			
		Death.cutless:
			TNT1 O 0 A_Jump(110, 2);
			Goto Death;
			TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Scream;
			TNT1 O 0 A_NoBlocking;
			FAT2 KL 5 A_SpawnProjectile ("MuchBlood", 75, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("RipGuts", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_BossDeath;
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
			FAT2 MNOP 5 A_SpawnProjectile ("MuchBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem ("NoGutsFatso", 1);
			Stop;
			
		Death.Plasma:
		Death.Plasma2:
			TNT1 A 0 A_BossDeath;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			CRB7 G 5 BRIGHT;
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_burned_flesh;
			CRB7 H 5 BRIGHT;
			EXPL AAAAAA 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			CRB7 IJ 5 BRIGHT;
			CARB LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 10 A_SpawnProjectile ("SmallSmoke", 1, 0, random (0, 360), 2, random (0, 160));
			CARB L -1;
			Stop;
			
		Death.Fire:
			FATK A 4;
			FATK B 4 A_Scream;
			FATK C 4 A_NoBlocking;
			FATK DEF 4;
			FATK F 1 A_BossDeath;
			TNT1 A 0 A_Playsound("props/redfire");
			CARB LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 doomb_show_effect("FlameTrails", (0, 0, 32), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			CARB LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 10 A_SpawnProjectile ("PLasmaSmoke", 32, 0, random (0, 360), 2, random (70, 130));
			CARB L -1;
			Stop;
			
		Death.Explosives:
		XDeath:
		Death.Explosive_Impact:
		Death.Landmine:
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (60, 90));
			TNT1 A 0 A_SpawnProjectile ("XDeathdoomb_fatsoArm", 20, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0 A_SpawnProjectile ("XDeathdoomb_fatsoHead", 20, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath2b", 20, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath3b", 20, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("MuchBlood2", 50, 0, random (0, 360), 2, random (0, 160));
			XFBT A 6 A_Scream;
			XFBT B 6 A_NoBlocking;
			XFBT CDEF 6 A_BossDeath;
			XFBT F 1;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem ("XDeadFat", 1);
			Stop;
			
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS3 A 5;
			CRS3 A -1;
			Stop;
			
		Pain.Taunt:
			TNT1 A 0;
			SPOS B 0 A_Pain;
			TNT1 A 0 {bNOPAIN = true;}
			TNT1 A 0 {bMISSILEMORE = true;}
			TNT1 A 0 {bMISSILEEVENMORE = true;}
			TNT1 A 0 A_PlaySound("demon/pain");
			FATR A 1 A_FaceTarget;
			FATR A 10;
			TNT1 A 0 A_Pain;
			FATR BAC 8;
			TNT1 A 0 A_Pain;
			FATR ABAC 8;
			TNT1 A 0 A_Pain;
			FATR ABAC 8;
			TNT1 A 0 A_GiveInventory("Enraged", 1);
			Goto Missile;
			
		Pain.KillMe:
			TNT1 A 0;
			Goto Missile;
			
	} 
} 

CLASS BigFireBall : doomb_boolet_base Replaces Fatshot { 
	Default {
		
		Radius 6;
		Height 8;
		Speed 20;
		Fastspeed 25;
		Damagefunction (random(25,40));
		Projectile;
		Scale 1.0;
		+FORCEXYBILLBOARD;
		+THRUGHOST;
		RenderStyle "Translucent";
		DamageType "Fire";
		ExplosionRadius 150;
		ExplosionDamage 8;
		Alpha 1;
		Decal "Scorch";
		SeeSound "BREATHOF";
		DeathSound "fatso/shotx";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 ACS_ExecuteAlways(798, 0, 0, 0, 0);//Check Effects
			
		Spawn1:
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "SpawnCheap");
			TNT1 A 0 A_SpawnItem ("FireballExplosionFlamesSmall");
			MANF A 1 BRIGHT A_SpawnItem("RedFlare22");
			
			TNT1 A 0 A_SpawnItem ("FireballExplosionFlamesSmall");
			MANF B 1 BRIGHT A_SpawnItem("RedFlare22");
			TNT1 A 0 A_SpawnProjectile ("RocketSmokeTrail52", 2, 0, random (70, 110), 2, random (0, 360));
			
			TNT1 A 0 A_SpawnItem ("FireballExplosionFlamesSmall");
			MANF A 1 BRIGHT A_SpawnItem("RedFlare22");
			
			TNT1 A 0 A_SpawnProjectile ("FireballExplosionFlamesSmall", 0, 0, random (0, 360), 2, random (00, 360));
			MANF B 1 BRIGHT A_SpawnItem("RedFlare22");
			TNT1 A 0 A_SpawnProjectile ("RocketSmokeTrail52", 2, 0, random (70, 110), 2, random (0, 360));
			Loop;
			
		SpawnCheap:
			TNT1 A 0 A_SpawnItem ("FireballExplosionFlamesSmall");
			MANF AB 1 BRIGHT A_SpawnItem("RedFlare22");
			Loop;
			
		Death:
			TNT1 A 0 A_Explode(10, 50, 0);
		ExplosionEffect:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "DeathCheap");
			TNT1 AAAA 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			EXPL AAA 0 A_SpawnProjectile ("FlamethrowerFireParticles", 6, 0, random (0, 360), 2, random (0, 90));
			FRFX ZZZ 0 BRIGHT A_SpawnProjectile ("BigBlackSmoke", 2, 0, random (0, 360), 2, random (0, 30));
			TNT1 A 2 A_SpawnItem("BurningGroundLowDamage");
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece", random (-15, 15), random (-15, 15));
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-35, 35), random (-35, 35));
			TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-45, 45), random (-45, 35));
			TNT1 AAAAAA 20 A_SpawnProjectile ("BigBlackSmoke", 0, 0, random (0, 360), 2, random (40, 160));
			Stop;
			
		DeathCheap:
		XDeath:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(200, "StopInAir");
			TNT1 AAAA 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			EXPL AAA 0 A_SpawnProjectile ("FlamethrowerFireParticles", 6, 0, random (0, 360), 2, random (0, 90));
			Stop;
			
		XDeath:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(200, "StopInAir");
			TNT1 AAAA 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			EXPL AA 0 A_SpawnProjectile ("FlamethrowerFireParticles", 6, 0, random (0, 360), 2, random (0, 90));
			Stop;
			
		StopInAIr:
			EXPL AAA 0 A_SpawnProjectile ("FlamethrowerFireParticles", 6, 0, random (0, 360), 2, random (0, 90));
			Stop;
	}
}
