CLASS NoGutsFatso: CurbstompedMarine { 
	Default {
		
		Radius 24;
		Height 46;
		+SHOOTABLE;
		-SOLID;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		Mass 1000;
		Health 300;
		Scale 1.2;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			FAT2 P -1;
		Stop;

		Death:
			TNT1 A 0 doomb_severed_limb("MeatDeath");
		Stop;

		Death.Fire:
		Death.Plasma:
		Death.Plasma2:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AA 0 doomb_spawn_burned_flesh;
			EXPL AAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			CARB LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 10 doomb_show_effect("AltSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
			CARB L -1;
		stop;

		Death.Cut:
		Death.Saw:
			TNT1 A 0 doomb_severed_limb("XDeathdoomb_fatsoArm", (0, 0, 15), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_severed_limb("NoGutsFatso_RemovedWeapon", limb_ignore_cvar: true);
		Stop;
			
		Raise:
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 0 A_SpawnItem("TeleportFog");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("doomb_fatso");
		Stop;
	}
}


CLASS NoGutsFatso_RemovedWeapon: NoGutsFatso
{
States
{
	Spawn:
		FAT2 Q -1;
	Stop;
}

}

CLASS DeadFat: CurbstompedMarine { 
	Default {
	
	Radius 16;
	Height 18;
	Scale 1.2;
	+SHOOTABLE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	-SOLID;
	+THRUACTORS;
	damagefactor "Crusher", 50.0;
	Mass 1000;
	Health 200;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	}
States
    {
	Spawn:
		FATK F -1;
	Stop;

	Death:
	Death.Explosive_Impact:
	Death.Shotgun:
		TNT1 A 0 doomb_severed_limb("GutsPile");
		TNT1 A 0 doomb_severed_limb("GibsZ", (15, 15, 0) );
		TNT1 A 0 doomb_severed_limb("GibsZ", (-15, 15, 0) );
		TNT1 A 0 doomb_severed_limb("GibsZ", (-15, -15, 0) );
		TNT1 A 0 doomb_severed_limb("GibsZ", (15, -15, 0) );
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_blood_mist(null, (0, 0, 5), 6);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0
		{
			actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 35 ) );
			if(a)
				a.scale = (0.45, 0.45);
		}
	Stop;
		
	Death.Fire:
	Death.Plasma:
	Death.Plasma2:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AA 0 doomb_spawn_burned_flesh;
		EXPL AAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		CARB LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 10 doomb_show_effect("AltSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		CARB L -1;
	Stop;

	Death.Cut:
	Death.Saw:
		TNT1 A 0 doomb_severed_limb("XDeathdoomb_fatsoArm", vel_dir:doomb_random_velocity(5) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("DeadFatNoArm");
	stop;

	Raise:
		TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("doomb_fatso");
	Stop;
}

}		




CLASS XDeathdoomb_fatsoHead: XDeathArm1 { 
	Default {
		-CLIENTSIDEONLY;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			XHE7 ABCDEFGH 3;
			Loop;
		Death:
			XHE5 A 1 doomb_spawn_bloodpool(BPS_SMALL);
			XHE5 A 1 doomb_severed_limb("doomb_fatsoHead");
		Stop;
	}
}



CLASS doomb_fatsoHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 120;
		Health 60;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			TNT1 A 0 A_JUmp(128, "Spawn2");
		Spawn1:
			XHE7 B 1900;
		Loop;
			
		Spawn2:
			XHE7 G 1900;
		Loop;
			
		Death:
			TNT1 A 0 doomb_severed_limb("doomb_fatsoHeadExplode", (0, 0, 10) );
		Stop;

		Death.Trample:
		Crush:
			TNT1 AAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 9009;
		Stop;

		Death.plasma:
			TNT1 A 0 doomb_severed_limb("XDeathBurnedSkull", (0, 0, 32), doomb_random_velocity(5) );
			EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		Stop;

		Death.punch:
		Death.Kick:
			XHE7 A 1 A_Pain;
			XHE7 A 1 A_FaceTarget;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_severed_limb("XDeathdoomb_fatsoHead", (0, 0, 5), doomb_random_velocity(5) );
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		Stop;
			
		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE7 ABCDEFGH 2;
		Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE7 ABCDEFGH 3;
			XHE7 I 0 doomb_severed_limb("doomb_fatsoHead");
		Stop;
	}
	
}


CLASS DeadFatNoArm: DeadFat { 
States
    {
		Spawn:
			FATK G -1;
        Stop;
}

}

CLASS DeadFatNoHead: DeadFat { 
States
{
	Spawn:
		FATT T -1;
	Stop;

	Death:
		TNT1 A 0 doomb_severed_limb("XDeathdoomb_fatsoArm", (0, 0, 0), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("DeadFatNoHead_RemovedWeapon");
	Stop;
}

}

CLASS DeadFatNoHead_RemovedWeapon: DeadFat { 
States
{
	Spawn:
		FAT2 R -1;
	Stop;
}

}
CLASS XDeadFat: DeadFat { 
States
{
	Spawn:
		XFBT F -1;
	Stop;
}

}

CLASS FatalizedFatso: DeadFat { 
States
{
	Spawn:
		FATF F 1 A_PlaySound("fatso/pain");
        FATF FFEE 10 doomb_for_khorne("brutal_Blood", (0, 0, 35), doomb_random_velocity(5) );
		tnt1 a 0 a_jump(200, "spawn");		
		FATF E -1;
	Stop ;
	}
}


CLASS XDeathdoomb_fatsoArm: XDeathArm1 { 
	Default {
 
    +SKYEXPLODE
	-CLIENTSIDEONLY
    Scale 1.1;
    Speed 9;
	Gravity 0.4;
	bounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			MANA ABCDEFG 3;
		Loop;
		
		Death:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			HND8 A 0 A_SpawnItem("FlameCannon",0,0,0,1);
		Stop;
	}
}