
CLASS Frozendoomb_fatso : doomb_body_base { 
	Default {
		
		+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
		
		Radius 48;
		Height 64;
		Health 60;
		Scale 1.2;
	}
	States
	{
		Spawn:
			FZD9 A 200;
			FZD9 A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZD9 A 50;
			FZD9 B 2;
			FZD9 A 50;
			FZD9 B 2;
			FZD9 A 50;
			FZD9 B 2;
			FZD9 A 25;
			FZD9 B 2;
			FZD9 A 25;
			FZD9 B 2;
			FZD9 A 10;
			FZD9 B 2;
			FZD9 A 10;
			FZD9 B 2;
			FZD9 A 10;
			FZD9 BABABA 2;
		Death.Fire:
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_spawnItem("doomb_fatso");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AAA 0 doomb_for_khorne("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
			TNT1 A 0 doomb_much_blood(48);
			FZD9 C 300;
			FZD9 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
		Stop;
	}
}



CLASS NoGutsFatso: CurbstompedMarine { 
	Default {
		
		Radius 24;
		Height 46;
		+SHOOTABLE;
		-SOLID;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		Mass 1000;
		Health 300;
		Scale 1.2;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			FAT2 P -1;
			Stop;
		Death:
			TNT1 A 0 A_SpawnProjectile ("MuchMeatDeath", 2, 0, random (0, 360), 2, random (0, 160));
			Stop;
		Death.Fire:
		Death.Plasma:
		Death.Plasma2:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_burned_flesh;
			EXPL AAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			CARB LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 10 doomb_show_effect("AltSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
			CARB L -1;
		Death.Cut:
		Death.Saw:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("XDeathdoomb_fatsoArm", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 A_SpawnItem ("NoGutsFatso_RemovedWeapon", 1);
		Stop;
			
		Raise:
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 0 A_SpawnItem("TeleportFog");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("doomb_fatso");
			Stop;
	}
}


CLASS NoGutsFatso_RemovedWeapon: NoGutsFatso { 
	Default {
		
		Health 200;
	}
	States
	{
		Spawn:
			FAT2 Q -1;
			Stop;
	Death.Cutless: Death.Cut:
	Death.Saw:
		Goto Death;
}

}

CLASS DeadFat: CurbstompedMarine { 
	Default {
	
	Radius 16;
	Height 18;
	Scale 1.2;
	+SHOOTABLE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	-SOLID;
	+THRUACTORS;
	damagefactor "Crusher", 50.0;
	Mass 1000;
	Health 200;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	}
States
    {
	Spawn:
		FATK F -1;
		Stop;
	Death:
	Death.Explosive_Impact:
	Death.Shotgun:
		TNT1 A 0 A_SpawnItem("GutsPile");
		TNT1 A 0 A_SpawnItemEx("GibsZ", 15, 15);
		TNT1 A 0 A_SpawnItemEx("GibsZ", 15, -15);
		TNT1 A 0 A_SpawnItemEx("GibsZ", -15, 15);
		TNT1 A 0 A_SpawnItemEx("GibsZ", -15, -15);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 5), 6);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 30, 0, random (0, 360), 2, random (40, 90));
		TNT1 AAAAAAA 0 A_SpawnProjectile ("XDeathSkinPiece1", 25, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("XDeathSkinPiece1", 25, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0
		{
			actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 35 ) );
			if(a)
				a.scale = (0.45, 0.45);
		}
	Stop;
		
	Death.Fire:
	Death.Plasma:
	Death.Plasma2:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_spawn_burned_flesh;
		EXPL AAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		CARB LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 10 doomb_show_effect("AltSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		CARB L -1;
	Stop;

	Death.Cut:
	Death.Saw:
		TNT1 A 0;
		TNT1 A 0 A_SpawnProjectile ("XDeathdoomb_fatsoArm", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_SpawnItem ("DeadFatNoArm", 1);
	stop;

	Raise:
		TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("doomb_fatso");
	Stop;
	
	
}

}		




CLASS XDeathdoomb_fatsoHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			XHE7 ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			XHE5 A 1;
			XHE5 A 1 A_SpawnItem("doomb_fatsoHead",0,0,0,1);
			Stop;
	}
}



CLASS doomb_fatsoHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 120;
		Health 60;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
			TNT1 A 0 A_JUmp(128, "Spawn2");
			
		Spawn1:
			XHE7 B 1900;
			Loop;
			
		Spawn2:
			XHE7 G 1900;
			Loop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("doomb_fatsoHeadExplode", 0, 10);
			Stop;
		Death.Trample:
		Crush:
			TNT1 AAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0;
			Stop;
		Death.punch:
		Death.Kick:
			XHE7 A 1 A_Pain;
			XHE7 A 1 A_FaceTarget;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathdoomb_fatsoHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE7 ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE7 ABCDEFGH 3;
			XHE7 I 0 A_SpawnItem("doomb_fatsoHead");
			Stop;
			
			
	}
	
}


CLASS XDeathdoomb_fatsoHeadKicked: XDeathdoomb_fatsoHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}

CLASS DeadFatNoArm: DeadFat { 
	Default {
 
	}
States
    {
    Spawn:
		FATK G -1;
        Stop;
	
	Death.Saw:
	death.Cut:
	TNT1 A 1;
	Goto Death;
    
}

}

CLASS DeadFatNoHead: DeadFat { 
	Default {
Health 200;
	}
States
{
	Spawn:
		FATT T -1;
	Stop;
	Death:
		TNT1 A 0 A_SpawnProjectile ("XDeathdoomb_fatsoArm", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_SpawnItem ("DeadFatNoHead_RemovedWeapon", 1);
	Stop;
}

}

CLASS DeadFatNoHead_RemovedWeapon: DeadFat { 
Default
{
	Health 200;
}

States
{
Spawn:
		FAT2 R -1;
        Stop;
       Death.Cutless: Death.Cut:	        Death.Saw:
  	    TNT1 A 0;
		 Goto Death;
}

}
CLASS XDeadFat: DeadFat { 
	Default {
 
Health 200;
	}
States
{
Spawn:
		XFBT F -1;
        Stop    ;
       Death.Cutless: Death.Cut:	       Death.Saw:
  	    TNT1 A 0;
		 Goto Death;
}

}

CLASS FatalizedFatso: DeadFat { 
	Default {
 Scale 1.0;
  Health 200;
	}
States
{
	Spawn:
		FATF F 1 A_PlaySound("fatso/pain");
        FATF FFEE 10 A_SpawnProjectile ("Blood", 35, 0, random (0, 360), 2, random (0, 160));
		tnt1 a 0 a_jump(200, "spawn");		
		FATF E -1;
        Stop ;
	}
}


CLASS XDeathdoomb_fatsoArm: XDeathArm1 { 
	Default {
 
    +SKYEXPLODE
	-CLIENTSIDEONLY
    Scale 1.1;
    Speed 9;
	Gravity 0.4;
	bounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			MANA ABCDEFG 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			HND8 A 0;
			HND8 A 0 A_SpawnItem("FlameCannon",0,0,0,1);
			Stop;
	}
}
