//===========================================================================
//
// Chaingunner
//
//===========================================================================
CLASS ChaingunGuy1 : doomb_monster_base Replaces ChaingunGuy { 
	Default {
		
		doomb_monster_base.headshot_multiplier 2;
		doomb_monster_base.head_starting_position 50;//so that if someone forgot to define this number monster dont get headshot from every attack
		doomb_monster_base.legs_height_max 10;//same for legs
		
		Health 90;
		Radius 16;
		Height 56;
		Mass 100;
		Speed 5;
		PainChance 200;
		PainChance "HelperMarineFatality", 255;
		PainChance "Kick", 255;
		PainChance "Melee", 255;
		damagefactor "Cut", 0.3;
		damagefactor "Avoid", 0.0;
		damagefactor "GibRemoving", 0.0;
		damagefactor "Crush", 5.0;
		damagefactor "TeleportRemover", 0.0;
		damagefactor "cut", 0.7;
		damagefactor "saw", 0.7;
		damagefactor "Explosive_Impact", 2.0;
		damagetype "Melee";
		Monster;
		Translation "192:207=176:191";
		damagefactor "SSG", 50.0;
		MaxStepHeight 24;
		MaxDropOffHeight 32;
		+FLOORCLIP;
		+MISSILEMORE;
		+MISSILEEVENMORE;
		+RANDOMIZE;
		
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		BloodType "Brutal_Blood",  "SawBlood";
		SeeSound "grunt/sight";
		PainSound "grunt/pain";
		DeathSound "grunt/death";
		ActiveSound "grunt/active";
		AttackSound "weapons/minigunfire";
		damagefactor "Explosive_Impact", 2.0;
		Obituary "%o has been mowed down by a Zombie Commando.";
		DamageFactor "CauseObjectsToSplash", 0.0;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 ACS_ExecuteAlways(796, 0, 0, 0, 0);//Check if Vanilla Mode is activated
		TNT1 A 0 A_GiveInventory("SKChaingunGuy", 1);
		TNT1 A 0 A_JumpIfInTargetInventory("ChainguyguyContinue", 1, "MissileContinue");
		Goto Stand;
		
	STAND:
		TNT1 A 0;
		TNT1 A 0 A_CheckSight("Stand2");
		MPOS BBBBBBBBBB 10 A_Look;
		Loop;
		
	Stand2:
		MPOS B 14 A_Look;
		Goto Stand;
		
	Idle:
	SearchForPlayer:
		TNT1 A 0 A_ClearTarget;
		TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
		TNT1 A 0 A_GiveInventory("SKChaingunguy", 1);
		
		
		MPOS AAA 10 A_Look;
		TNT1 A 0 A_SetAngle(angle - 40);
		MPOS A 10 A_Look;
		TNT1 A 0 A_SetAngle(angle + 40);
		MPOS A 10 A_Look;
		
		MPOS ABCD 10 A_Look;
		loop;
		
	See:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 A_TakeInventory("SKChaingunGuy", 1);
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		TNT1 A 0 A_CheckSight("SeeNeverSeen");
		Goto SeeContinue;
		
	SeeContinue:
		TNT1 A 0 A_CheckSight("SeeNeverSeen");
		
	SeeContinuePart2:
		TNT1 A 0 A_GiveInventory("EverSeenTheplayer", 1);
		//TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 30, 0, 0)
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 12, "SearchForPlayer");
		
	SeeContinuePart36:
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		
		TNT1 A 0 A_TakeInventory("IsFiring", 1);
		MPOS AA 2 A_Chase;
		
		MPOS AA 2 A_Chase;
		
		MPOS BB 2 A_Chase;
		
		MPOS BB 2 A_Chase;
		
		MPOS CC 2 A_Chase;
		
		MPOS CC 2 A_Chase;
		
		MPOS DD 2 A_Chase;
		
		MPOS DD 2 A_Chase;
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "Idle");
		Loop;
		
	SeeNeverSeen:
		
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("EverSeenThePlayer", 1, "SeeContinuePart2");
		//TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 30, 0, 0)
		
		
		MPOS AA 2 A_Chase;
		TNT1 A 0 A_TakeInventory("IsFiring", 1);
		
		MPOS AA 2 A_Chase;
		
		
		MPOS BB 2 A_Chase;
		
		MPOS BB 2 A_Chase;
		
		
		MPOS CC 2 A_Chase;
		
		MPOS CC 2 A_Chase;
		
		
		MPOS DD 2 A_Chase;
		
		MPOS DD 2 A_Chase;
		TNT1 A 0 A_CheckSight("SeeNeverSeen");
		Goto SeeContinue;
		
	Missile:
		
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		
		//TNT1 A 0 A_TakeInventory("CantFire", 1)
		//TNT1 A 0 A_SpawnProjectile("MonsterTargetCheck", 34, 0, 0, 0) 
		//TNT1 A 0 A_SpawnProjectile("MonsterTargetCheckFaster", 34, 0, 0, 0) 
		MPOS E 6 A_FaceTarget;
		//TNT1 A 0 A_JumpIfInventory("CantFire",1, "SeeContinuePart36")
		
		TNT1 A 0 A_TakeInventory("SKChaingunGuy", 1);
		TNT1 A 0 A_PlaySound("CHAINSTA");
		MPOS E 4 A_FaceTarget;
		
		MPOS E 12 A_FaceTarget;
		TNT1 A 0 A_GiveInventory("IsFiring", 1);
		TNT1 A 0;
		
	MissileContinue:
		MPOS E 1 A_FaceTarget;
		
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAltFast", 34, 10, 15, 0);
		MPOS F 1 BRIGHT A_SpawnProjectile("MonsterMinigunTracer", 38, 0, random(-9, 9), 1, random(-2, 2));
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		
		MPOS E 2 A_FaceTarget;
		
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAltFast", 34, 10, 15, 0);
		MPOS F 1 BRIGHT A_SpawnProjectile("MonsterMinigunTracer", 38, 0, random(-7, 7), 1, random(-2, 2));
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MPOS E 2 A_FaceTarget;
		
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAltFast", 34, 10, 15, 0);
		MPOS F 1 BRIGHT A_SpawnProjectile("MonsterMinigunTracer", 38, 0, random(-9, 9), 1, random(-2, 2));
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MPOS E 2 A_FaceTarget;
		
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAltFast", 34, 10, 15, 0);
		MPOS F 1 BRIGHT A_SpawnProjectile("MonsterMinigunTracer", 38, 0, random(-7, 7), 1, random(-2, 2));
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MPOS E 2 A_FaceTarget;
		
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAltFast", 34, 10, 15, 0);
		MPOS F 1 BRIGHT A_SpawnProjectile("MonsterMinigunTracer", 38, 0, random(-9, 9), 1, random(-2, 2));
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_JumpIfInTargetInventory("ChainguyguyContinue", 1, "MissileContinue");
		MPOS E 2 A_FaceTarget;
		
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAltFast", 34, 10, 15, 0);
		MPOS F 1 BRIGHT A_SpawnProjectile("MonsterMinigunTracer", 38, 0, random(-9, 9), 1, random(-2, 2));
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_CheckSight("SeeContinue");
		TNT1 A 0 A_JumpIfInTargetInventory("ChainguyguyContinue", 1, "MissileContinue");
		TNT1 A 0 A_CposRefire;
	Goto MissileContinue;
		
	SpecialAttack:
		MPOS E 10 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("FireFightFlare", 34, 10, 15, 25);
		MPOS F 10;//A_SpawnProjectile("CommandoGrenade",10,0,0,0)
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MPOS E 10;
	Goto SeeContinue;
		
	GotoStealthKill:
		TNT1 A 1;
		TNT1 A 0 A_Explode(100, 1, 1);
		TNT1 A 1;
		Goto See;
		
	Pain.Punch:
		MPOS G 4;
		TNT1 A 0 A_JumpIfInventory ("SKChaingunGuy", 1, "GotoStealthKill");
		MPOS G 4 A_Pain;
		TNT1 A 0 A_TakeInventory("IsFiring", 1);
		Goto See;
	Pain:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("IsFiring", 1, "Pain.IsFiring");
		TNT1 A 0 A_TakeInventory("SKChaingunGuy", 1);
		MPOS G 3;
		MPOS G 3 A_Pain;
		TNT1 A 0 A_TakeInventory("IsFiring", 1);
		Goto SeeContinue;
		
	Pain.IsFiring:
		CPDR A 3;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 32, 15, 0, 2, -20);
		CPDR B 3 BRIGHT A_NoBlocking;
		Goto MissileContinue;
		
	Pain.HeavyImpact:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_Recoil(6);
		Goto Pain;
		
	Pain.Kick:
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_TakeInventory("IsFiring", 1);
		TNT1 A 0 A_TakeInventory("SKChaingunGuy", 1);
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil (3);
		MPOS G 2;
		CPBK ABC 2;
		
		CPBK C 8 A_Pain;
		CPBK D 8;
		
		CPBK C 8 A_Pain;
		CPBK D 8;
		
		CPBK C 8 A_Pain;
		CPBK D 8;
		
		CPBK C 8 A_Pain;
		CPBK D 8;
		
		CPBK BA 4;
		MPOS G 4;
	Goto See;
		
		
	Death.Cutless:
		TNT1 A 0;
		TNT1 A 0 A_Jump(32,"Death.Arm");
		TNT1 A 0 A_Jump(24,"Death.Rare");
		TNT1 A 0 A_Jump(96, "Death");
		Goto Death.ARm;
		
	Death.MonsterShotgunBullet:
	Death.Shotgun:
	Death.HKFT:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_JumpIfCloser(70, "Death.SSG");
		TNT1 A 0 A_Jump(24,"Death.Arm");
		TNT1 A 0 A_Jump(24,"Death.SSG");
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Recoil(6);
		TNT1 A 0 A_JumpIfInventory("IsFiring", 1, "Death.Rare");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		CPHM AB 4;
		CPHM CD 4 A_JumpIf((vel.Y == 0), "TakeASit");
		CPHM EF 4;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("DeadChaingunGuy_KilledByMinorHead", 3);
		Stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("IsFiring", 1, "Death.Rare");
		TNT1 AAA 0 A_SpawnItem("Blood", 0, 40);
		TNT1 A 0 A_Jump(96,"Death.Rare");
		TNT1 A 0 A_Jump(64,"Death.Arm");
		CPOD A 8 A_Scream;
		CPOD B 6 A_NoBlocking;
		CPOD CDEFG 6;
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 1 A_SpawnItem ("DeadChaingunGuy1", 3);
		Stop;
		
	Death.Rare:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(2);
		CPDR A 3 A_Scream;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 32, 15, 0, 2, -20);
		CPDR B 3 BRIGHT A_NoBlocking;
		
		CPDR A 3;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 32, 15, 0, 2, -20);
		CPDR B 3 BRIGHT A_NoBlocking;
		
		
		CPDR C 2;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 24, 15, -20, 2, -20);
		CPDR D 2 BRIGHT;
		
		CPDR C 2;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 24, 15, -20, 2, -20);
		CPDR D 2 BRIGHT;
		
		CPDR E 2;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 24, 15, -20, 2, 20);
		CPDR F 2 BRIGHT;
		
		CPDR G 2;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 24, 15, -10, 2, 40);
		CPDR H 2 BRIGHT;
		
		TNT1 A 0 A_Recoil(1);
		CPDR I 2;
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 24, 15, -10, 2, 40);
		CPDR J 2 BRIGHT;
		TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
		
		CPDR K 2;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 12, 15, -20, 2, 40);
		CPDR L 2 BRIGHT;
		TNT1 A 0 doomb_spawn_bloodpool();
		CPDR M 2;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 12, 15, -20, 2, 20);
		CPDR N 2 BRIGHT;
		
		CPDR M 2;
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 12, 15, -20, 2, 20);
		CPDR N 2 BRIGHT;
		
		
		TNT1 A 0 A_SpawnItemEx ("MiniGun", 0, 30);
		TNT1 A 0 A_SpawnItem("DeadChaingunguyCPDRO");
		Stop;
		
	TakeASit:
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("doomb_red_blood_pool");
		TNT1 A 0 A_SpawnItemEx ("MiniGun", 0, 30);
		TNT1 A 0 A_SpawnItemEx("DeadChaingunguy_Slumped", 10);
		Stop;
		
		
	Death.OriginalGibz:
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathChainArm", 35, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 35, 0, random (0, 360), 2, random (60, 120));
		TNT1 AA 0 A_SpawnProjectile ("XDeath2", 35, 0, random (0, 360), 2, random (60, 120));
		TNT1 AA 0 A_SpawnProjectile ("XDeath3", 35, 0, random (0, 360), 2, random (60, 120));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", 35, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_XScream;
		TNT1 O 0 A_NoBlocking;
		CPSC ABCDEFGH 4;
		CPSC H 1;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 1 A_SpawnItem ("DeadChaingunGuy_Half", 3);
		Stop;
		
	Death.Cutless:
		TNT1 A 0;
		TNT1 A 0 A_Jump(180,"Death.Arm");
		Goto Death;
	Death.Arm:
		TNT1 A 0;
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathChainArm", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 45, 0, random (0, 360), 2, random (0, 160));
		
		CPOD H 10 A_Scream;
		CPOD I 5;
		CPOD I 1 A_NoBlocking;
		TNT1 A 1 A_SpawnItem ("BrutalizedCommando1");
		Stop;
		
	XDeath:
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 42, 0, random (0, 190), 2, random (10, 60));
		// TNT1 A 0 A_SpawnItemEx ("XDeathChainHead", 50, 0, random (0, 360), 2, random (0, 160))
		TNT1 A 0 A_SpawnProjectile ("ChainXDeath", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		Stop;
		
		
	HeadExploder:
		TNT1 A 0 A_Jump(72, "Death.HeadExplode");
		Goto Death.HeadMinor;
		
	Death.Headshot:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
		TNT1 A 0 A_JumpIfHealthLower(-50, "Death.HeadExplode");
		TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExploder");
	Death.HeadMinor:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AA 0 A_SpawnProjectile ("Bloodmist", 60, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		CPHM I 6;
		CPHM J 6 A_Scream;
		CPHM C 6 A_NoBlocking;
		CPHM DEF 6;
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("DeadChaingunGuy_KilledByMinorHead", 3);
		Stop;
		
	Death.Kick:
	Death.HeavyImpact:
		CPHM A 9 A_FaceTarget;
		TNT1 A 0 A_Recoil(5);
		CPHM B 9 A_Scream;
		CPHM C 8 A_NoBlocking;
		CPHM DEF 8;
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		TNT1 A 0 A_SpawnItem ("DeadChaingunGuy_KilledByMinorHead", 3);
		Stop;
		
	Death.headExplode:
		
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ChaingunguyHeadExplode", 0, 50);
		CPHS AAA 2 A_SpawnProjectile ("Brutal_LiquidBlood", 50, 0, random (0, 360), 2, random (60, 120));
		CPHS BBB 2 A_SpawnProjectile ("Brutal_LiquidBlood", 50, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_XScream;
		CPHS CCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 40, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_NoBlocking;
		CPHS DDDDDDDDDDDDEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (60, 120));
		
		TNT1 A 0 doomb_spawn_bloodpool();
		CPHS FFFFFFFFFFFFFFF 2 A_SpawnProjectile ("Brutal_LiquidBlood", 5, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		TNT1 A 1 A_SpawnItem ("DeadChaingunGuy_NoHead", 3);
		Stop;
	Death.decaptate:
		TNT1 AAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItemEx ("XDeathChaingunguyHeadBeheaded", 50, 0, random (0, 360), 2, random (40, 90));
		CPHS AAA 2 A_SpawnProjectile ("Brutal_LiquidBlood", 50, 0, random (0, 360), 2, random (60, 120));
		CPHS BBB 2 A_SpawnProjectile ("Brutal_LiquidBlood", 50, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_XScream;
		CPHS CCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 40, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_NoBlocking;
		CPHS DDDDDDDDDDDDEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 doomb_spawn_bloodpool();
		CPHS FFFFFFFFFFFFFFF 2 A_SpawnProjectile ("Brutal_LiquidBlood", 5, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		TNT1 A 1 A_SpawnItem ("DeadChaingunGuy_NoHead", 3);
		Stop;
	Death.cut:
	Death.Saw:
		TNT1 O 0 A_Jump(220, 2);
		Goto Death;
		TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathChainArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathChainLeg", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_XScream;
		TNT1 O 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("XDeathGuts", 0, 0, random (0, 360), 2, random (0, 160));
		CPSC ABCDEFGH 8;
		CPSC H 1;
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 1 A_SpawnItem ("DeadChaingunGuy_Half", 3);
		Stop;
		
		
		
		
	Death.Explosive_Impact:
	Death.Landmine:
	Death.LandMine2:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 A 0 A_SpawnProjectile ("XDeathChainArm", 62, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathChainLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		
		CPDE A 1 A_Scream;
		CPDE A 1;
		CPDE A 2 A_CheckFloor ("Dead.Landmine");
		CPDE BCDEFGH 2 A_CheckFloor ("Dead.Landmine");
		CPDE A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_Spawnitem("DeadChaingunguyCPDEI");
		Stop;
		
	Dead.Landmine:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 A_SpawnItem ("Blood");
		CPDE I 1;
		TNT1 A 0 A_SpawnItem("DeadChaingunguyCPDEI");
		Stop;
		
	Death.Plasma: Death.Plasma2:
		PBR1 A 6 A_Scream;
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes2", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 doomb_show_effect("BluePlasmaFire", (0, 0, 32), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		PBR1 B 6 A_NoBlocking;
		PBR1 CDEFGH 6 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		PBR1 HHHHHHHHHHHHHHHHHHHHHH 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		PBR1 H -1;
	Stop;
	
	
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_burned_flesh;
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("GreenFlameTrails", (0, 0, 50), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
	Stop;
	
	Death.fire:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
			tnt1 B 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				A_SpawnItem("RedFlare", 0, 5);
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				A_SpawnProjectile ("SmallFireTrail324", 0, 0, random (0, 360), 2, -random (0, 130));
			}
		TNT1 A 0 A_PlaySound("BURNZOM");
	mini_fire:
		CPBR AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
			tnt1 B 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				A_SpawnItem("RedFlare", 0, 5);
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				A_SpawnProjectile ("SmallFireTrail324", 0, 0, random (0, 360), 2, -random (0, 130));
			}
		BDT1 B 0 doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
		CPBR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
			tnt1 B 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				A_SpawnItem("RedFlare", 0, 5);
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				A_SpawnProjectile ("SmallFireTrail324", 0, 0, random (0, 360), 2, -random (0, 130));
			}
		BDT1 B 0 doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
		CPBR CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
			tnt1 B 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				A_SpawnItem("RedFlare", 0, 5);
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				A_SpawnProjectile ("SmallFireTrail324", 0, 0, random (0, 360), 2, -random (0, 130));
			}
		BDT1 B 0 doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );

		CPBR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
			tnt1 B 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				A_SpawnItem("RedFlare", 0, 5);
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				A_SpawnProjectile ("SmallFireTrail324", 0, 0, random (0, 360), 2, -random (0, 130));
			}
		BDT1 B 0 doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );

		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-15, 15), random (-15, 15));
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 12, "Death_fire");
	Loop;
	
	Death_fire:	
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 light("BIGREDTORCH")
		{
			A_Explode(3,30, damagetype:"fire");
			A_SpawnItem("RedFlare", 0, 5);
			doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			A_SpawnProjectile ("SmallFireTrail324", 0, 0, random (0, 360), 2, -random (0, 130));
		}
		TNT1 A 0 A_SpawnItem("o_100SmallFireFocusSpawnerz");
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		BRZ3 H -1;
	Stop;
	
	
	Death.Throwable:
	Goto Death;
	
	Death.Fatality:
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		TNT1 A 0 A_Jump(130,5);
		TNT1 A 0 A_GiveToTarget("ComandoFatality", 1);
		Stop;
		TNT1 AAAAAAA 0;
		TNT1 A 0 A_GiveToTarget("ComandoFatality2", 1);
		TNT1 A 1;
		TNT1 A 0;
	Stop;
	
Death.HelperMarineFatallity:
	TNT1 A 0;
	TNT1 A 1 A_Pain;
	TNT1 A 0 A_Chase(null,null);
	TNT1 A 0 A_Scream;
	TNT1 A 0 A_NoBlocking       ;
	TNT1 A 0 A_GiveToTarget("ComandoFatality", 1);
	Stop;
	
	
Death.Eat:
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking;
	TNT1 A 0 A_Scream;
	TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
	TNT1 A 0 A_GiveToTarget("ComandoFatality",1);
	Stop;
	
Raise:
	CPOS N 5;
	CPOS MLKJIH 5;
	Goto See;

Crush:
Death.Stomp:
	TNT1 A 0 A_Scream;
	TNT1 A 0 A_NoBlocking;
	CPHM CDE 2;
	TNT1 AA 0 A_SpawnItem("MeatDeathSmall");
	TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
	TNT1 AAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
	TNT1 AA 0 bright A_SpawnProjectile ("XDeath2b", 55, 0, random (0, 360), 2, random (30, 180));
	TNT1 AA 0 bright A_SpawnProjectile ("XDeath3b", 55, 0, random (0, 360), 2, random (30, 180));
	TNT1 A 0 doomb_spawn_bloodpool();
	TNT1 A 0 A_SpawnItem ("CrushedRemains");
	TNT1 A 1;
	TNT1 A 1 A_XScream;
	Stop;
	
Pain.KillMe:
Pain.Taunt:
	TNT1 A 0;
	Goto Missile;
	
	Death.Punch:
		TNT1 A 0 A_JumpIfInventory ("SKChaingunGuy", 1, "StealthKill");
	Death.Blast:
	Death.SSG:
		MPSD A 1 A_Pain;
		MPSD A 1 A_FaceTarget;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 35, 0, random (170, 190), 2, random (0, 40));
		//TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160))
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("XDeathChainArm", 62, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathChaingunguyHeadOnXDeath", 62, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		MPSD AAAA 6 A_SpawnProjectile ("Brutal_LiquidBlood", 64, 0, random (0, 360), 2, random (30, 60));
		MPSD BBBBCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 34, 0, random (0, 60), 2, random (30, 60));
		TNT1 A 0 doomb_spawn_bloodpool();
		MPSD DDDDDDDDDDDDDDDDDDDDD 6 A_SpawnProjectile ("Brutal_LiquidBlood", 16, 0, random (0, 60), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem("DeadChaingunguyMPSDD");
	Stop;
	
	StealthKill:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, 1);
		Goto Death;
		TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_GiveToTarget("SKChaingunGuy", 1);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_SpawnItem("Chaingun");
		TNT1 A 0 A_Die("Stealthy");
		TNT1 A 1;
	Stop;

	Death.Stealthy:
		TNT1 A 0;
	Stop;
	
}
}

