//===========================================================================
//
// Chaingunner
//
//===========================================================================
CLASS doomb_commando : doomb_monster_base
{ 
Default
{
	doomb_monster_base.headshot_multiplier 2;
	doomb_monster_base.head_starting_position 50;//so that if someone forgot to define this number monster dont get headshot from every attack
	doomb_monster_base.legs_height_max 10;//same for legs
	doomb_monster_base.weapon_type "MiniGun";
	
	Health 90;
	Radius 16;
	Height 56;
	Mass 100;
	Speed 5;

	Monster;
	+FLOORCLIP;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+RANDOMIZE;

	PainChance 200;
	PainChance "HelperMarineFatality", 255;
	PainChance "Kick", 255;
	PainChance "Melee", 255;
	damagefactor "Cut", 0.3;
	damagefactor "Crush", 5.0;
	damagefactor "cut", 0.7;
	damagefactor "saw", 0.7;
	damagefactor "Explosive_Impact", 2.0;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagetype "Melee";

	Translation "192:207=176:191";
	damagefactor "SSG", 50.0;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	
	BloodType "Brutal_Blood",  "SawBlood";
	SeeSound "grunt/sight";
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	ActiveSound "grunt/active";
	AttackSound "weapons/minigunfire";
	damagefactor "Explosive_Impact", 2.0;
	Obituary "%o has been mowed down by a Zombie Commando.";
}

States
{
	Spawn:
		TNT1 A 0 A_JumpIfInTargetInventory("ChainguyguyContinue", 1, "MissileContinue");
	STAND:
		MPOS B 10 A_Look;
	Loop;

	Idle:
	SearchForPlayer:
		TNT1 A 0 A_ClearTarget;
		MPOS AAA 10 A_Look;
		TNT1 A 0 A_SetAngle(angle - 40);
		MPOS A 10 A_Look;
		TNT1 A 0 A_SetAngle(angle + 40);
		MPOS A 10 A_Look;
		MPOS ABCD 10 A_Look;
	loop;
		
	See:
		TNT1 A 0 {bNODROPOFF = false;}
	SeeContinue:
		tnt1 a 0 doomb_monster_memory();
		MPOS AAAABBBBCCCCDDDD 2 A_Chase;
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "Idle");
	Loop;
		
	Missile:
		TNT1 A 0 doomb_update_memory();
		MPOS E 6 A_FaceTarget;
		TNT1 A 0 A_PlaySound("CHAINSTA");
		MPOS E 4 A_FaceTarget;
		MPOS E 12 A_FaceTarget;
	MissileContinue:
		MPOS E 1
		{
			A_FaceTarget();
		}
		MPOS F 1 BRIGHT
		{
			A_SpawnProjectile("MonsterMinigunTracer", 38, 0, random(-9, 9), 1, random(-2, 2));
			A_PlaySOund("DISTFRRIFLE");

			{doomb_flare_base.doomb_attach_flare(self, "lens_flare_orange", (0, 0, 34) );}
			A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		}
		TNT1 A 0 A_JumpIfInTargetInventory("ChainguyguyContinue", 1, "MissileContinue");		
		TNT1 A 0 A_CposRefire;
	Goto MissileContinue;
		
	Pain.Punch:
		MPOS G 4;
		MPOS G 4 A_Pain;
	Goto See;
	
	Pain:
		TNT1 A 0 A_Jump(25,"Pain.IsFiring");
		MPOS G 3;
		MPOS G 3 A_Pain;
	Goto SeeContinue;
		
	Pain.IsFiring:
		CPDR A 3;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 32, 15, 0, 2, -20);
		CPDR B 3 BRIGHT light ("ZOMBIEATK") A_NoBlocking ;
		Goto MissileContinue;
		
	Pain.HeavyImpact:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_Recoil(6);
		Goto Pain;
		
	Pain.Kick:
		TNT1 A 0 A_Pain;
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil (3);
		MPOS G 2;
		CPBK ABC 2;
	pain_kick_loop:		
		CPBK C 8 A_Pain;
		CPBK D 8;
		tnt1 a 0 a_jump(60, "pain_kick_loop");

		CPBK BA 4;
		MPOS G 4;
	Goto See;
		
		
	Death.Cutless:
		TNT1 A 0 A_Jump(32,"Death.Arm");
		TNT1 A 0 A_Jump(24,"Death.Rare");
		TNT1 A 0 A_Jump(96, "Death");
	Goto Death.ARm;
		
	Death.Shotgun:
	Death.HKFT:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_JumpIfCloser(70, "Death.SSG");
		TNT1 A 0 A_Jump(24,"Death.Arm");
		TNT1 A 0 A_Jump(24,"Death.SSG");
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Recoil(6);
		TNT1 A 0 A_Jump(25,"Death.Rare");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		CPHM AB 4;
		CPHM CD 4 A_JumpIf((vel == (0, 0, 0) ), "TakeASit");
		CPHM EF 4;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadChaingunGuy_KilledByMinorHead", limb_ignore_cvar: true);
	Stop;
		
	Death.Throwable:
	Death:
		TNT1 A 0 A_Jump(96,"Death.Rare");
		TNT1 A 0 A_Jump(64,"Death.Arm");
		CPOD A 8 A_Scream;
		CPOD B 6 A_NoBlocking;
		CPOD CDEFG 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("Deaddoomb_commando", limb_ignore_cvar: true);
	Stop;
		
	Death.Rare:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(2);
		CPDR A 3 A_Scream;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 32, 15, 0, 2, -20);
		CPDR B 3 BRIGHT light ("ZOMBIEATK") A_NoBlocking;
		
		CPDR A 2;
		CPDR B 3 BRIGHT light ("ZOMBIEATK")
		{
			A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
			A_SpawnProjectile ("MonsterMinigunTracer", 32, 15, 0, 2, -20);

		}
		CPDR C 2;
		CPDR D 2 BRIGHT light ("ZOMBIEATK")
		{
			A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
			A_SpawnProjectile ("MonsterMinigunTracer", 24, 15, -20, 2, -20);
		}
		CPDR E 2;
		CPDR F 2 BRIGHT light ("ZOMBIEATK")
		{
			A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
			A_SpawnProjectile ("MonsterMinigunTracer", 24, 15, -20, 2, 20);
		}
		CPDR G 2;
		CPDR H 2 BRIGHT light ("ZOMBIEATK")
		{
			A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
			A_SpawnProjectile ("MonsterMinigunTracer", 24, 15, -10, 2, 40);
			A_Recoil(1);
		}
		CPDR I 2;
		TNT1 A 0 A_JumpIf((vel == (0, 0, 0) ), "TakeASit");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 24, 15, -10, 2, 40);
		CPDR J 2 BRIGHT light ("ZOMBIEATK")	A_JumpIf( (vel == (0, 0, 0) ), "TakeASit");
		
		CPDR K 2;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 12, 15, -20, 2, 40);
		CPDR L 2 BRIGHT light ("ZOMBIEATK");
		TNT1 A 0 doomb_spawn_bloodpool();
		CPDR M 2;
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 12, 15, -20, 2, 20);
		CPDR N 2 BRIGHT light ("ZOMBIEATK");
		
		CPDR M 2;
		TNT1 A 0 A_SpawnProjectile ("MonsterMinigunTracer", 12, 15, -20, 2, 20);
		CPDR N 2 BRIGHT light ("ZOMBIEATK");
		TNT1 A 0 doomb_severed_limb("DeadChaingunguyCPDRO", limb_ignore_cvar: true);
	Stop;
		
	TakeASit:
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadChaingunguy_Slumped", limb_ignore_cvar: true);
	Stop;


	Death.OriginalGibz:
		TNT1 A 0 doomb_much_blood(0);
		TNT1 A 0 doomb_severed_limb("XDeathChainArm", (0, 0, 35), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", 35, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 A_XScream;
		TNT1 O 0 A_NoBlocking;
		CPSC ABCDEFGH 4;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadChaingunGuy_Half", limb_ignore_cvar: true);
	Stop;
		
	Death.Cutless:
		TNT1 A 0 A_Jump(180,"Death.Arm");
	Goto Death;
	
	Death.Arm:
		TNT1 A 0 doomb_much_blood(0);
		TNT1 A 0 doomb_severed_limb("XDeathChainArm", (0, 0, 35), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		CPOD H 10 A_Scream;
		CPOD I 5;
		CPOD I 1 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("BrutalizedCommando1", limb_ignore_cvar: true);
	Stop;
		
	XDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("ChainXDeath", (0, 0, 35), limb_ignore_cvar: true);
		TNT1 AAAA 0 doomb_much_blood();
	Stop;
		
		
	Death.Headshot:
		TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "headshot_1");
		TNT1 A 0 A_JumpIfHealthLower(-50, "Death.HeadExplode");
	Death.HeadMinor:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, 60) );
		TNT1 AAAA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 60), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		TNT1 AA 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 55), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper");
		CPHM I 6;
		CPHM J 6 A_Scream;
		CPHM C 6 A_NoBlocking;
		CPHM DEF 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadChaingunGuy_KilledByMinorHead", limb_ignore_cvar: true);
	Stop;
		
	Death.Kick:
	Death.HeavyImpact:
		CPHM A 9 A_FaceTarget;
		TNT1 A 0 A_Recoil(5);
		CPHM B 9 A_Scream;
		CPHM C 8 A_NoBlocking;
		CPHM DEF 8;
		TNT1 A 0 doomb_severed_limb("DeadChaingunGuy_KilledByMinorHead", limb_ignore_cvar: true);
	Stop;


	Death.headExplode:
		TNT1 A 0 doomb_severed_limb("ChaingunguyHeadExplode", (0, 0, 55) );
		CPHS AAA 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		CPHS BBB 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_XScream;
		CPHS CCC 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_NoBlocking;
		CPHS DDDDDDDDDDDDEEE 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_spawn_bloodpool();
		CPHS FFFFFFFFFFFFFFF 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_severed_limb("DeadChaingunGuy_NoHead", limb_ignore_cvar: true);
	Stop;

	headshot_1:
		TNT1 AAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 doomb_severed_limb("XDeathChaingunguyHead", (0, 0, 50), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		CPHS AAABBB 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_XScream;
		CPHS CCC 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_NoBlocking;
		CPHS DDDDDDDDDDDDEEE 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_spawn_bloodpool();
		CPHS FFFFFFFFFFFFFFF 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_severed_limb("DeadChaingunGuy_NoHead", limb_ignore_cvar: true);
	Stop;

	Death.cut:
	Death.Saw:
		TNT1 O 0 A_Jump(220, 1);
	Goto Death;
		TNT1 A 0 doomb_much_blood(0);
		TNT1 A 0 doomb_severed_limb("XDeathChainArm", (0, 0, 35), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		TNT1 A 0 doomb_severed_limb("XDeathChainLeg", (0, 0, 5), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		TNT1 A 0 A_XScream;
		TNT1 O 0 A_NoBlocking;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		CPSC ABCDEFGH 8;
		CPSC H 1;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadChaingunGuy_Half", (0, 0, 35), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ), limb_ignore_cvar: true);
	Stop;
		
		
		
		
	Death.Explosive_Impact:
		TNT1 A 0 {vel.z += 40;}
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, height/2) );
		TNT1 A 0 doomb_severed_limb("XDeathChainArm", (0, 0, 35), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		TNT1 A 0 doomb_severed_limb("XDeathChainLeg", (0, 0, 5), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		TNT1 AAAAAAAAAAA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 50), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );

		CPDE A 1 A_Scream;
		CPDE ABCDEFGH 2 ;
		CPDE A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadChaingunguyCPDEI", limb_ignore_cvar: true);
	Stop;
		
		
	Death.Plasma:
	Death.Plasma2:
		PBR1 A 6 A_Scream;
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_severed_limb("Ashes1", (0, 0, 35), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		TNT1 AAAA 0 doomb_show_effect("BluePlasmaFire", (0, 0, 32), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		PBR1 B 6 A_NoBlocking;
		PBR1 CDEFGH 6 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 50), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		PBR1 HHHHHHHHHHHHHHHHHHHHHH 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		PBR1 H -1;
	Stop;
	
	
	Death.fire:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		tnt1 B 0
		{
			A_Explode(3,30, damagetype:"fire");
			{{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}}
			doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
		}
		TNT1 A 0 A_PlaySound("BURNZOM");
	mini_fire:
		CPBR AAABBBCCCBBB 1 light("BIGREDTORCH") BRIGHT A_Wander;
		tnt1 B 0 
		{
			A_Recoil(-1);
			A_Explode(3,30, damagetype:"fire");
			{{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}}
			doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
		}
		TNT1 A 0 A_Jump(26, "Death_fire");
	Loop;
	
	Death_fire:	
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 light("BIGREDTORCH")
		{
			A_Explode(3,30, damagetype:"fire");
			{{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}}
			doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
		}
		TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		BRZ3 H -1;
	Stop;
	
	


	Raise:
		CPOS NMLKJIH 5;
	Goto See;

	Crush:
	Death.Stomp:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		CPHM CDE 2;
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_blood_mist('doomb_non_interactive_blood', 'blood_mist', times:6);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("CrushedRemains", limb_ignore_cvar: true);
		TNT1 A 1 A_XScream;
	Stop;
	
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;
	
	Death.Punch:
	Death.Blast:
	Death.SSG:
		MPSD A 1 A_Pain;
		MPSD A 1 A_FaceTarget;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 A 0 doomb_blood_mist('doomb_non_interactive_blood', 'blood_mist', (0, 0, 35), 6);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, height/2) );
		TNT1 A 0 doomb_severed_limb("XDeathChainArm", (0, 0, 62), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );
		TNT1 A 0 doomb_severed_limb("XDeathChaingunguyHead", (0, 0, 62), (frandom(-3, 3), frandom(-3, 3), frandom(0, 3) ) );

		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		MPSD AAAA 6 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		MPSD BBBBCCCC 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_spawn_bloodpool();
		MPSD DDDDDDDDDDDDDDDDDDDDD 6 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_severed_limb("DeadChaingunguyMPSDD", limb_ignore_cvar: true);
	Stop;
	









	////////////////////////////////////////////////////////////
	//			fatality from player
	////////////////////////////////////////////////////////////
	Death.HelperMarineFatallity:
	Death.Fatality:
		tnt1 a 0
		{
			doomb_monster_fatality_camera(target);
			vel = (0, 0, 0);
			A_Pain();
			A_NoBlocking();
		}
		TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(256,"comando_fatality_1", "comando_fatality_2");

	comando_fatality_1:
		CFTA AAABCDE 2;
		tnt1 A 0
		{
			A_PlaySound("grunt/pain", CHAN_AUTO, 1);
			Radius_Quake (4, 24, 0, 15, 0);
			A_PlaySound("CLAP", CHAN_AUTO, 1);
		}
		CFTA EFF 7;
		CFTA GHIJK 2;
		CFTA L 7
		{
			A_PlaySound("grunt/pain", CHAN_AUTO, 1);
			Radius_Quake (4, 24, 0, 15, 0);
			A_PlaySound("misc/xdeath4", CHAN_AUTO, 1);
		}
		
		CFTA M 15;
		CFTA OPQR 4;
		CFTA R 15
		{
			A_PlaySound("grunt/pain", CHAN_AUTO, 1);
			A_PlaySound("grunt/death", CHAN_AUTO, 1);
			A_PlaySound("BURNZOM", CHAN_AUTO, 1);
			ACS_Execute(580, 0, 0, 0, 0);
			ACS_Execute(581, 0, 0, 0, 0);
			ACS_Execute(582, 0, 0, 0, 0);
			ACS_Execute(583, 0, 0, 0, 0);
			Radius_Quake (4, 24, 0, 15, 0);
		}
		tnt1 AAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 AAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 50) );
		CFTA S 25;
		//////////////////////////////////////////////////////
		tnt1 A 1
		{
			A_Givetotarget("HealthBonus",10);
			doomb_severed_limb("XDeathChainArm", (0, 0, 40), doomb_random_velocity(3) );
			doomb_severed_limb("XDeathChainArm", (0, 0, 40), doomb_random_velocity(3) );
			doomb_severed_limb("DyingComando", limb_ignore_cvar: true);
			doomb_destroy_monster_fatality_camera();
		}
	Stop;


	comando_fatality_2:
		CFTC A 1;
		CFTC A 1 A_PlaySound("BURNZOM");
		CFTC AAAA 5;
		CFTC B 1 A_PlaySound("grunt/death", CHAN_AUTO, 1);
		CFTC B 6
		{
			Radius_Quake (4, 24, 0, 15, 0);
			ACS_Execute(580, 0, 0, 0, 0);
			ACS_Execute(581, 0, 0, 0, 0);
			ACS_Execute(582, 0, 0, 0, 0);
			ACS_Execute(583, 0, 0, 0, 0);
		}
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 AAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 60), doomb_random_velocity(3) );
		TNT1 A 0
		{
			doomb_much_blood();
			doomb_severed_limb("XDeathChainArm", (0, 0, 40), doomb_random_velocity(3) );
			doomb_severed_limb("XDeathChainArm", (0, 0, 40), doomb_random_velocity(3) );
		}
		CFTC CDEF 4;
		CFTC F 15;
		tnt1 A 1
		{
			A_Givetotarget("HealthBonus",10);
			doomb_severed_limb("DeadChaingunGuy_Half", limb_ignore_cvar: true);
			doomb_severed_limb("XDeathChainArm", (0, 0, 40), doomb_random_velocity(3) );
			doomb_severed_limb("XDeathChainArm", (0, 0, 40), doomb_random_velocity(3) );
			doomb_destroy_monster_fatality_camera();
		}
	stop;
	////////////////////////////////////////////////////////////
	//			backstab from player
	////////////////////////////////////////////////////////////
	death.back_stab: 
		TNT1 A 0
		{
			if(is_melee_player_kill() )
				setstate(curstate+1);
		}
	Goto Death;
		tnt1 a 0
		{
			doomb_monster_fatality_camera(target);
			vel = (0, 0, 0);
		}
		SFCG AB 8;
		tnt1 A 0 A_PlaySound("misc/xdeath4");
		SFCG C 16;
		tnt1 A 1
		{
			doomb_severed_limb("DeadChaingunGuy_KilledByMinorHead", limb_ignore_cvar: true);
			doomb_destroy_monster_fatality_camera();
		}
	Stop;
}

}