CLASS Deaddoomb_commando: CurbstompedMarine { 
	Default {
		
		Radius 12;
		Height 12;
		+SHOOTABLE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		+FLOORCLIP;
		-SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Mass 1000;
		Health 200;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			CPOD G -1;
			Stop;
		Raise:
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 0 A_SpawnItem("TeleportFog");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("doomb_zombie_Man");
			Stop;
			
	}
	
}
CLASS DeadChaingunGuy_NoHead: Deaddoomb_commando { 
	States
	{
		Spawn:
			CPHS F -1;
			Stop;
	}
	
}
CLASS DeadChaingunGuy_Half: Deaddoomb_commando { 
	States
	{
		Spawn:
			CPSC H -1;
			Stop;
	}
	
}		
CLASS DeadChaingunGuyCPDRO: Deaddoomb_commando { 
	States
	{
		Spawn:
			CPDR O -1;
			Stop;
	}
}		


CLASS BrutalizedDeadChaingunGuy: Deaddoomb_commando { 
	States
	{
		Spawn:
			CFTB C -1;
			Stop;
	}
	
}


CLASS DeadChaingunGuy_KilledByMinorHead: Deaddoomb_commando { 
	States
	{
		Spawn:
			CPHM F -1;
			Stop;
	}
	
}
CLASS BrutalizedDeadCommando1: Deaddoomb_commando { 
	States
	{
		Spawn:
			CPOD L -1;
			Stop   ;
	}
	
}	   
	   
	   
	   
	   
	   
	    
CLASS DeadChaingunguy_Slumped: CurbstompedMarine { 
	Default {
		
		damagefactor "Crush", 50.0;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		//+NORADIUSDMG
		+NOPAIN;
		+CORPSE;
		
		Mass 6000;
		damagefactor "Crush", 50.0;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		//+NORADIUSDMG
		+NOPAIN;
		+CORPSE;
		
		
		+NOPAIN;
		Health 200;
	Height 22+15;
	doomb_monster_base.head_starting_position 22;
		Radius 6;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(6);
			BR95 A 6;
			TNT1 A 0 A_JumpIf(vel.x == 0 && vel.y == 0, "LayDown");
			BR95 A 16;
			Loop ;
		LayDown:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("Deaddoomb_commando");
			Stop;
		XDeath:
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("ChainXDeath");
			Stop;
			
		Death.Headshot:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItemEx("ChaingunguyHeadExplode", 0, 0, 22);
			TNT1 A 0 A_SpawnItem("DeadChaingunguy_Slumped_NoHead");
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_SpawnProjectile ("XDeathChainArm", 40, 0, random (0, 360), 2, random (30, 90));
		Stop;
			
	}
	
}		
		
		
CLASS DeadChaingunguyMPSDD: Deaddoomb_commando { 
	Default {
		
	}
	States
	{
		Spawn:
			MPSD D -1;
			Stop   ;
	}
	
}
CLASS DeadChaingunguyCPDEI: Deaddoomb_commando { 
	Default {
		
	}
	States
	{
		Spawn:
			CPDE I -1;
			Stop   ;
	}
	
}


		
CLASS DeadChaingunguy_Slumped_NoHead: CurbstompedMarine { 
	Default {
		
		Radius 12;
		Height 12;
		Scale 0.98;
		Mass 6000;
		damagefactor "Crush", 50.0;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		//+NORADIUSDMG
		+NOPAIN;
		+CORPSE;
		
		+NOPAIN;
		Height 22;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			BR95 B 100;
			Loop ;
		XDeath:
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("ChainXDeath");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_SpawnProjectile ("XDeathChainArm", 40, 0, random (0, 360), 2, random (30, 90));
		Stop;
			
	}
}








//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//miniguner minigun fatality
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
CLASS BrutalizedCommando1 : doomb_body_base
{
Default
{
	Radius 16;
	Height 50;
	Health 300;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	PainSound "grunt/pain";
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+FLOORCLIP;
	+DONTSPLASH;
	+nopain
	Scale 1.0;
}
States
{
	Spawn:
		CPOD JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 1
		{
			if(health <= 200)
				setstatelabel("no_hand");
			if(random(0, 10) == 10)
				doomb_for_khorne("TinyBlood", (0, 0, 23), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		}
		CPOD K 6
		{
			A_SpawnItem ("MiniGun", 0, 5,0);
			A_SpawnItem ("BrutalizedDeadCommando1");
		}
	Stop;

	//BrutalizedCommando2	
	no_hand:
		TNT1 A 0 doomb_much_blood(0);
		TNT1 A 0 A_SpawnProjectile ("XDeathChainArm", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_PlaySound("chainguy/death");
		CPOD MNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMN 1
		{
			if(health <= 100)
				setstatelabel("just_torso");
			if(random(0, 10) == 10)
				doomb_for_khorne("TinyBlood", (0, 0, 23), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		}
		CPOD O 5
		{
			A_SpawnItem ("BrutalizedDeadChaingunGuy");
			A_SpawnItem ("MiniGun", 0, 5,0);
		}
	Stop;

	//BrutalizedCommando3	
	just_torso:
		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece_dark", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 45, 0, random (0, 360), 2, random (0, 160));
		CPOD P 5;
		CPOD QQQQQQQQQQ 10 A_SpawnItem ("Blood", 0, 43);
		CPOD R 5;
		TNT1 A 0 A_SpawnItem ("BrutalizedDeadChaingunGuy");
	Stop;

	Death:
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		CPOD S -1 doomb_final_absolution(12, 12);
	Stop;
}

}


CLASS XDeathChainLeg: XDeathArm1 { 
	Default {
		
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG3 ABCDEFGH 5;
			Loop;
		Death:
			LEG3 A 1;
			LEG3 A 0 A_SpawnItem("Gib_ChainLeg");
			Stop;
	}
}

CLASS Gib_ChainLeg: LimbBase { 
	States
	{
		Spawn:
			LEG3 I 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma:
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160))   ;
			Stop;
		Death:    
			TNT1 AAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			Stop;
		Death.Kick:
		Death.punch:
			LEG3 A 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathChainLeg", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
	}
	
}


CLASS XDeathChainArm: XDeathArm1 { 
	Default {
		
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HND3 ABCDEFGH 5;
			Loop;
		Death:
			HND3 A 1;
			HND3 A 0 A_SpawnItem("Gib_ChainArm");
			Stop;
	}
}

CLASS Gib_ChainARm: LimbBase { 
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump (128, "Spawn2");
			HND3 E 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			HND3 E 9009;
			Loop;
		Spawn2:
			HND3 A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma:  
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160))   ;
			Stop;
		Death:    
			TNT1 AAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			Stop;
		Death.Kick:
		Death.punch:
			HND3 A 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathChainArm", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
	}
	
}



CLASS XDeathChaingunguyHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		BounceCount 3;
		Scale 1.0;
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			CHHE AB 3;
			CHHE CDEFGH 3;
			Loop;
		Death:
			XHE2 E 0;
			XHE2 E 0 A_SpawnItem("ChaingunguyHead",0,0,0,1);
			Stop;
	}
}



CLASS XDeathChaingunguyHeadBeheaded: XDeathChaingunguyHead { 
	Default {
		
		Speed 5;
		Gravity 0.5;
	}
}


CLASS XDeathChaingunguyHeadOnXDeath: XDeathChaingunguyHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ChaingunguyHeadExplode");
			Stop;
			
	}
	
}
CLASS ChaingunguyHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		+SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Radius 10;
		
		Mass 60;
		Health 40;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(256, "Spawn1", "SPawn2");
		Spawn1:
			CHHE A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Spawn2:  
			CHHE E 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ChaingunguyHeadExplode");
		Stop;
		
		Death.Trample:
		Crush:
			TNT1 AAAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0;
			Stop;
		Death.punch:
		Death.Kick:
			CHHE EE 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathChaingunguyHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			CHHE ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			CHHE ABCDEFGH 3;
			XDT5 I 0 A_SpawnItem("ChaingunguyHead");
			Stop;
			
			
	}
	
}


CLASS ChaingunguyHeadExplode: doomb_head_exlposion
{ 
	Default {
		
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_piece_dark", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("BrainsImpHeadPiece", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
			tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 A 10;
		Stop;
	}
}

CLASS XDeathChaingunguyHeadKicked: XDeathChaingunguyHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
	}
}

CLASS PlayerChaingunguyVictim : doomb_body_base { 
Default {
		Radius 16;
		Height 50;
		Health 70;
		
		PainSound "grunt/pain";
		PainChance 255;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+NORADIUSDMG;
		+FLOORCLIP;
		+DONTSPLASH;
		Scale 1.0;
}
	States
	{
		Spawn:
			XPL8 A 50;
		DieNow:
			PLAY JKL 5;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Fall;
			TNT1 A 0 {bSHOOTABLE = false;}
			PLAY L -1;
		Stop;
			
		Pain:
			TNT1 A 0 A_Jump(129, "Pain2");
			XPL8 B 2;
		Goto Spawn;
			
		Pain2:
			XPL8 C 3;
		Goto Spawn;
			
		Death:
			TNT1 A 0 doomb_Rip_Guts();
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_much_blood();
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 50, 0, random (0, 360), 2, random (0, 160));
			XPL2 A 10 A_XScream;
			TNT1 AA 0 doomb_spawn_big_blood (50);
			XPL2 B 20 A_NoBlocking;
			TNT1 AA 0 doomb_spawn_big_blood (50);
			XPL2 C 10 doomb_spawn_big_blood (40);
			TNT1 AA 0 doomb_spawn_big_blood (30);
			XPL2 DE 10 doomb_spawn_big_blood (20);
			TNT1 A 0 doomb_spawn_bloodpool();
			XPL2 E -1;
		Stop;
			
	}
	
}


CLASS FrozenChaingunguy : doomb_body_base { 
	Default {
		
		Health 60;
		Radius 16;
		Height 52;
		+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
		
	}
	States
	{
		Spawn:
			FZD3 A 200;
			FZD3 A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZD3 A 50;
			FZD3 B 2;
			FZD3 A 50;
			FZD3 B 2;
			FZD3 A 50;
			FZD3 B 2;
			FZD3 A 25;
			FZD3 B 2;
			FZD3 A 25;
			FZD3 B 2;
			FZD3 A 10;
			FZD3 B 2;
			FZD3 A 10;
			FZD3 B 2;
			FZD3 A 10;
			FZD3 BABABA 2;
		Death.Fire:
			TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_spawnItem("Chaingunguy");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_much_blood(48);
			TNT1 A 0 A_SpawnItem("Chaingun");
			FZD3 C 300;
			FZD3 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
			Stop;
	}
}


CLASS DyingComando : doomb_body_base
{
Default {
	Radius 21;
	Height 15;
	Health 40;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	+FORCEXYBILLBOARD;
	-SOLID;
	+SHOOTABLE;
	Scale 1.0;
	damagefactor "Blood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "Taunt", 0.0;
	
	damagefactor "Taunt", 0.0;
}

States
{
	Spawn:
		CFTB AB 10 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Pain;
		tnt1 a 0 a_jump(200, "spawn");

	Dead:
		CFTB C 1 A_SpawnItem ("BrutalizedDeadChaingunGuy", 3);
	Stop;

	Death:
		CFTB D 1 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 AAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Xdeath1", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 1 A_SpawnItem ("BrutalizedDeadChaingunGuy", 3);
	Stop;

	XDeath:
		TNT1 A 0 A_SpawnProjectile ("ChainXDeath", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 doomb_much_blood();
	Stop;
}

}