


CLASS DeadChaingunGuy1: CurbstompedMarine { 
	Default {
		
		Radius 12;
		Height 12;
		+SHOOTABLE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		+FLOORCLIP;
		-SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Mass 1000;
		Health 100;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			CPOD G -1;
			Stop;
		Raise:
			TNT1 A 2 A_SpawnProjectile ("RealFlameTrailsSmall", 6, 0, random (0, 360), 2, random (70, 110));
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 A_SpawnProjectile ("RealFlameTrailsSmall", 6, 0, random (0, 360), 2, random (70, 110));
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 0 A_SpawnItem("TeleportFog");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("doomb_zombie_Man");
			Stop;
			
	}
	
}
CLASS DeadChaingunGuy_NoHead: DeadChaingunGuy1 { 
	Default {
		
		Health 200;
	}
	States
	{
		Spawn:
			CPHS F -1;
			Stop;
	}
	
}
CLASS DeadChaingunGuy_Half: DeadChaingunGuy1 { 
	Default {
		
		Health 200;
	}
	States
	{
		Spawn:
			CPSC H -1;
			Stop;
	}
	
}		
CLASS DeadChaingunGuyCPDRO: DeadChaingunGuy1 { 
	Default {
		
		Health 200;
	}
	States
	{
		Spawn:
			CPDR O -1;
			Stop;
	}
}		


CLASS BrutalizedDeadChaingunGuy: DeadChaingunGuy1 { 
	Default {
		
		Health 200;
	}
	States
	{
		Spawn:
			CFTB C -1;
			Stop;
	}
	
}


CLASS DeadChaingunGuy_KilledByMinorHead: DeadChaingunGuy1 { 
	Default {
		
		Health 200;
	}
	States
	{
		Spawn:
			CPHM F -1;
			Stop;
	}
	
}
CLASS BrutalizedDeadCommando1: DeadChaingunguy1 { 
	Default {
		
	}
	States
	{
		Spawn:
			CPOD L -1;
			Stop   ;
	}
	
}	   
	   
CLASS BrutalizedCommandoLegs: DeadChaingunguy1 { 
	Default {
		
	}
	States
	{
		Spawn:
			CPOD S -1;
			Stop;
		Death:
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathChainLeg", 5, 0, random (0, 360), 2, random (0, 160));
			Stop   ;
	}
	
}	   
	   
	   
	   
	   
	    
CLASS DeadChaingunguy_Slumped: CurbstompedMarine { 
	Default {
		
		damagefactor "Crush", 50.0;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		//+NORADIUSDMG
		+NOPAIN;
		+CORPSE;
		
		Mass 6000;
		damagefactor "Crush", 50.0;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		//+NORADIUSDMG
		+NOPAIN;
		+CORPSE;
		
		
		+NOPAIN;
		Health 200;
		DamageFactor "Head", 15.0;
		Height 22;
		Radius 6;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(6);
			BR95 A 6;
			TNT1 A 0 A_JumpIf(vel.x < 0, "LayDown");
			TNT1 A 0 A_JumpIf(vel.y < 0, "LayDown");
			TNT1 A 0 A_JumpIf(vel.x > 0, "LayDown");
			TNT1 A 0 A_JumpIf(vel.y > 0, "LayDown");
			//headbox height 22
			BR95 A 16;
			Loop ;
		LayDown:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("DeadChaingunguy1");
			Stop;
		XDeath:
		Death.Explosives:
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("ChainXDeath");
			Stop;
			
		Death.Headshot:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItemEx("ChaingunguyHeadExplode", 0, 0, 22);
			TNT1 A 0 A_SpawnItem("DeadChaingunguy_Slumped_NoHead");
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_SpawnProjectile ("XDeathChainArm", 40, 0, random (0, 360), 2, random (30, 90));
			//TNT1 A 0 A_SpawnItem("DeadChaingunguyJustLegsAreLeft")
			Stop;
			
	}
	
}		
		
		
CLASS DeadChaingunguyMPSDD: DeadChaingunguy1 { 
	Default {
		
	}
	States
	{
		Spawn:
			MPSD D -1;
			Stop   ;
	}
	
}
CLASS DeadChaingunguyCPDEI: DeadChaingunguy1 { 
	Default {
		
	}
	States
	{
		Spawn:
			CPDE I -1;
			Stop   ;
	}
	
}


		
CLASS DeadChaingunguy_Slumped_NoHead: CurbstompedMarine { 
	Default {
		
		Radius 12;
		Height 12;
		Scale 0.98;
		Mass 6000;
		damagefactor "Crush", 50.0;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		//+NORADIUSDMG
		+NOPAIN;
		+CORPSE;
		
		+NOPAIN;
		Height 22;
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			BR95 B 100;
			Loop ;
		XDeath:
		Death.Explosives:
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("ChainXDeath");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_SpawnProjectile ("XDeathChainArm", 40, 0, random (0, 360), 2, random (30, 90));
			//TNT1 A 0 A_SpawnItem("DeadChaingunguyJustLegsAreLeft")
			Stop;
			
	}
}


CLASS BrutalizedCommando1 : ACTOR { 
	Default {
		
		
		Radius 16;
		Height 50;
		Health 30;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Avoid", 0.0;
		damagefactor "KillMe", 0.0;
		PainSound "grunt/pain";
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+FLOORCLIP;
		+DONTSPLASH;
		Scale 1.0;
	}
	States
	{
		Spawn:
			CPOD JJJJJJJJJJ 10 A_SpawnItem ("DripingBlo_odLeavesPool", 0, 23);
			CPOD K 6;
			TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
			TNT1 A 0 A_SpawnItem ("BrutalizedDeadCommando1");
			Stop;
			
		Pain:
			CPOD J 1 A_Pain;
			Goto Spawn;
			
		Death:
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathChainArm", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_PlaySound("chainguy/death");
			TNT1 A 0 A_SpawnItem ("BrutalizedCommando2");
			Stop;
			
	}
	
}
CLASS BrutalizedCommando2: BrutalizedCommando1 { 
	Default {
		
	}
	States
	{
		Spawn:
			CPOD MMM 10 A_SpawnItem ("DripingBlo_odLeavesPool", 0, 23);
			CPOD NNNNN 10 A_SpawnItem ("DripingBlo_odLeavesPool", 0, 23);
			CPOD O 5;
			TNT1 A 0 A_SpawnItem ("BrutalizedDeadChaingunGuy");
			TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
			Stop;
			
		Pain:
			CPOD M 5 A_Pain;
			Goto Spawn;
			
		Death:
			TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("Brains3", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("Brains6", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("Brains7", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("BrutalizedCommando3");
			TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
			Stop;
			
	}
	
}

CLASS BrutalizedCommando3: BrutalizedCommando1 { 
	Default {
		
	}
	States
	{
		Spawn:
			CPOD P 5;
			CPOD QQQQQQQQQQ 10 A_SpawnItem ("Blood", 0, 43);
			CPOD R 5;
			TNT1 A 0 A_SpawnItem ("BrutalizedDeadChaingunGuy");
			Stop;
			
		Pain:
			CPOD P 5 A_Pain;
			Goto Spawn;
			
		Death:
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 45, 0, random (0, 360), 2, random (0, 160));
			CPOD S 1;
			TNT1 A 0 A_SpawnItem ("BrutalizedCommandoLegs");
			Stop;
			
	}
	
}


CLASS XDeathChainLeg: XDeathArm1 { 
	Default {
		
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG3 ABCDEFGH 5;
			Loop;
		Death:
			LEG3 A 1;
			LEG3 A 0 A_SpawnItem("Gib_ChainLeg");
			Stop;
	}
}

CLASS Gib_ChainLeg: LimbBase { 
	Default {
		
	}
	States
	{
		Spawn:
			LEG3 I 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma:
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160))   ;
			Stop;
		Death:    
			TNT1 AAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Stop;
		Death.Kick:
		Death.SuperPunch:
			LEG3 A 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathChainLeg", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
	}
	
}


CLASS XDeathChainArm: XDeathArm1 { 
	Default {
		
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HND3 ABCDEFGH 5;
			Loop;
		Death:
			HND3 A 1;
			HND3 A 0 A_SpawnItem("Gib_ChainArm");
			Stop;
	}
}

CLASS Gib_ChainARm: LimbBase { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump (128, "Spawn2");
			HND3 E 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			HND3 E 9009;
			Loop;
		Spawn2:
			HND3 A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma:  
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160))   ;
			Stop;
		Death:    
			TNT1 AAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Stop;
		Death.Kick:
		Death.SuperPunch:
			HND3 A 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathChainArm", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
	}
	
}

CLASS PlayerChaingunguyVictim : doomb_blood { 
	Default {
		
		
		Radius 16;
		Height 50;
		Health 70;
		bloodtype "DeadBlood";
		PainSound "grunt/pain";
		PainChance 255;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+NORADIUSDMG;
		+FLOORCLIP;
		+DONTSPLASH;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			XPL8 A 50;
			Goto DieNow;
			
		DieNow:
			PLAY JKL 5;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Fall;
			TNT1 A 0 {bSHOOTABLE = false;}
			PLAY L -1;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 A_Jump(129, "Pain2");
			XPL8 B 2;
			Goto Spawn;
			
		Pain2:
			XPL8 C 3;
			Goto Spawn;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("RipGuts", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 50, 0, random (0, 360), 2, random (0, 160));
			XPL2 A 10 A_XScream;
			TNT1 AA 0 doomb_spawn_big_blood (50);
			XPL2 B 20 A_NoBlocking;
			TNT1 AA 0 doomb_spawn_big_blood (50);
			XPL2 C 10 doomb_spawn_big_blood (40);
			TNT1 AA 0 doomb_spawn_big_blood (30);
			XPL2 DE 10 doomb_spawn_big_blood (20);
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			XPL2 E -1;
			Stop;
			
	}
	
}


CLASS FrozenChaingunguy : ACTOR { 
	Default {
		
		Health 60;
		Radius 16;
		Height 52;
		+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
		
	}
	States
	{
		Spawn:
			FZD3 A 200;
			FZD3 A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZD3 A 50;
			FZD3 B 2;
			FZD3 A 50;
			FZD3 B 2;
			FZD3 A 50;
			FZD3 B 2;
			FZD3 A 25;
			FZD3 B 2;
			FZD3 A 25;
			FZD3 B 2;
			FZD3 A 10;
			FZD3 B 2;
			FZD3 A 10;
			FZD3 B 2;
			FZD3 A 10;
			FZD3 BABABA 2;
		Death.Fire:
			TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_spawnItem("Chaingunguy");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAA 0 A_SpawnProjectile ("MuchBlood", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem("Chaingun");
			FZD3 C 300;
			FZD3 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
			Stop;
	}
}


CLASS DyingComando : ACTOR { 
	Default {
		
		
		Radius 21;
		Height 15;
		Health 40;
		PainSound "grunt/pain";
		PainChance 255;
		Mass 999999;
		+FORCEXYBILLBOARD;
		-SOLID;
		+SHOOTABLE;
		Scale 1.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		damagefactor "KillMe", 0.0;
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
	}
	States
	{
		Spawn:
			CFTB AB 10;
			Goto Suffer;
		Suffer:
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Pain;
			CFTB AB 12;
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Pain;
			CFTB AB 12;
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Pain;
			CFTB AB 12;
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Pain;
			CFTB AB 12;
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Pain;
			CFTB AB 12;
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Pain;
			CFTB AB 11;
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Pain;
			CFTB AB 11;
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Pain;
			CFTB AB 11;
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Pain;
			CFTB AB 11;
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Pain;
			CFTB AB 11;
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Pain;
			CFTB AB 11;
			Goto Dead;
		Dead:
			CFTB C 1;
			TNT1 A 1 A_SpawnItem ("BrutalizedDeadChaingunGuy", 3);
			Stop;
		Death:
			CFTB D 1;
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 AAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("Xdeath1", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 1 A_SpawnItem ("BrutalizedDeadChaingunGuy", 3);
			Stop;
		XDeath:
			//TNT1 A 0 A_SpawnItemEx ("XDeathChainHead", 50, 0, random (0, 360), 2, random (0, 160))
			TNT1 A 0 A_SpawnProjectile ("ChainXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("MuchBlood2", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			Stop;
	}
}
