CLASS Deaddoomb_commando: CurbstompedMarine { 
	Default {
		
		Radius 12;
		Height 12;
		+SHOOTABLE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		+FLOORCLIP;
		-SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Mass 1000;
		Health 200;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			CPOD G -1;
			Stop;
		Raise:
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 0 A_SpawnItem("TeleportFog");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("doomb_zombie_Man");
			Stop;
			
	}
	
}
CLASS DeadChaingunGuy_NoHead: Deaddoomb_commando
{
States
{
	Spawn:
		CPHS F -1;
	Stop;
}
	
}

CLASS DeadChaingunGuy_Half: Deaddoomb_commando
{
States
{
	Spawn:
		CPSC H -1;
		Stop;
}
	
}		
CLASS DeadChaingunGuyCPDRO: Deaddoomb_commando
{
States
{
	Spawn:
		CPDR O -1;
		Stop;
}

}		


CLASS BrutalizedDeadChaingunGuy: Deaddoomb_commando
{
States
{
	Spawn:
		CFTB C -1;
		Stop;
}
	
}


CLASS DeadChaingunGuy_KilledByMinorHead: Deaddoomb_commando { 
	States
	{
		Spawn:
			CPHM F -1;
			Stop;
	}
	
}
CLASS BrutalizedDeadCommando1: Deaddoomb_commando { 
	States
	{
		Spawn:
			CPOD L -1;
			Stop   ;
	}
	
}	   
	   
	   
	   
	   
	   
	    
CLASS DeadChaingunguy_Slumped: CurbstompedMarine { 
Default {
	
	damagefactor "Crush", 50.0;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	//+NORADIUSDMG
	+NOPAIN;
	+CORPSE;
	
	Mass 6000;
	damagefactor "Crush", 50.0;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	//+NORADIUSDMG
	+NOPAIN;
	+CORPSE;
	
	
	+NOPAIN;
	Health 200;
	Height 45;
	doomb_monster_base.head_starting_position 22;
	Radius 6;
	Scale 0.9;
}

States
{
	Spawn:
		TNT1 A 0 nodelay A_Recoil(6);
		BR95 A 6;
		TNT1 A 0 A_JumpIf(vel.x == 0 && vel.y == 0, "LayDown");
		BR95 A 16;
	Loop;

	LayDown:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("Deaddoomb_commando", limb_ignore_cvar: true);
	Stop;

	XDeath:
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("ChainXDeath");
	Stop;
		
	Death.Headshot:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("ChaingunguyHeadExplode");
		TNT1 A 0 doomb_severed_limb("DeadChaingunguy_Slumped_NoHead", limb_ignore_cvar: true);
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, height/2) );
		TNT1 A 0 doomb_severed_limb("XDeathChainArm", "spawn", (0, 0, 40), doomb_random_velocity(7) );
	Stop;
}

}		
		
		
CLASS DeadChaingunguyMPSDD: Deaddoomb_commando
{
States
{
	Spawn:
		MPSD D -1;
	Stop   ;
}
	
}
CLASS DeadChaingunguyCPDEI: Deaddoomb_commando
{
States
{
	Spawn:
		CPDE I -1;
		Stop   ;
}
	
}


		
CLASS DeadChaingunguy_Slumped_NoHead: CurbstompedMarine
{
	Default {
		
		Radius 12;
		Height 12;
		Scale 0.98;
		Mass 6000;
		damagefactor "Crush", 50.0;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		//+NORADIUSDMG
		+NOPAIN;
		+CORPSE;
		
		+NOPAIN;
		Height 22;
		Scale 0.9;
	}

States
{
	Spawn:
		BR95 B 100;
	Loop ;

	XDeath:
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("ChainXDeath");
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, height/2) );
		TNT1 AA 0 doomb_severed_limb ("XDeathChainArm", 'spawn', (0, 0, 40), doomb_random_velocity(7) );
	Stop;
}

}








//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
//miniguner minigun fatality
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////
CLASS BrutalizedCommando1 : doomb_body_base
{
Default
{
	Radius 16;
	Height 50;
	Health 300;
	PainSound "grunt/pain";
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+FLOORCLIP;
	+DONTSPLASH;
	+nopain
	Scale 1.0;
}
States
{
	Spawn:
		CPOD JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 1
		{
			if(health <= 200)
				setstatelabel("no_hand");
			if(random(0, 10) == 10)
				doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 23), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		}
		CPOD K 6
		{
			A_SpawnItem ("MiniGun", 0, 5,0);
			doomb_severed_limb("BrutalizedDeadCommando1", limb_ignore_cvar: true);
		}
	Stop;

	//BrutalizedCommando2	
	no_hand:
		TNT1 A 0 doomb_much_blood(0);
		TNT1 A 0 doomb_severed_limb("XDeathChainArm", "spawn", (0, 0, 45), doomb_random_velocity(3) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_PlaySound("chainguy/death");
		CPOD MNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMNMN 1
		{
			if(health <= 100)
				setstatelabel("just_torso");
			if(random(0, 10) == 10)
				doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 23), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		}
		CPOD O 5
		{
			doomb_severed_limb("BrutalizedDeadChaingunGuy", limb_ignore_cvar: true);
			A_SpawnItem ("MiniGun", 0, 5,0);
		}
	Stop;

	//BrutalizedCommando3	
	just_torso:
		TNT1 A 0 doomb_severed_limb("eye", "spawn", (0, 0, 50), doomb_random_velocity(7) );
		TNT1 A 0 doomb_severed_limb("head_piece_dark", "spawn", (0, 0, 50), doomb_random_velocity(7) );
		TNT1 A 0 doomb_severed_limb("jaw", "spawn", (0, 0, 50), doomb_random_velocity(7) );
		TNT1 AAAAAA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 50), doomb_random_velocity(7) );
		TNT1 AAAAAAAAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 50), doomb_random_velocity(7) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		CPOD P 5;
		CPOD QQQQQQQQQQ 10 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 50), doomb_random_velocity(7) );
		CPOD R 5;
		TNT1 A 0 doomb_severed_limb("BrutalizedDeadChaingunGuy", limb_ignore_cvar: true);
	Stop;

	Death:
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_SpawnItem ("MiniGun", 0, 5,0);
		CPOD S -1 doomb_final_absolution(12, 12);
	Stop;
}

}



CLASS Gib_ChainLeg: LimbBase
{
	States
	{
		Spawn:
			LEG3 I 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;
		
		Death.plasma:
			TNT1 A 0 doomb_severed_limb("XDeathBurnedLeg");
		Stop;
		
		Death:
			TNT1 AAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		Stop;
		
		Death.Kick:
		Death.punch:
			LEG3 A 1 A_FaceTarget;
			TNT1 A 0 doomb_severed_limb("XDeathChainLeg", "spawn", (0, 0, 5), doomb_random_velocity(7) );
		Stop;
	}
	
}



CLASS Gib_ChainARm: LimbBase
{
	States
	{
		Spawn:
			TNT1 A 0 nodelay A_Jump (128, "Spawn2");
			HND3 E 1900 doomb_spawn_bloodpool(BPS_SMALL);
			HND3 E 9009;
			Loop;
		Spawn2:
			HND3 A 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;
		
		Death.plasma:  
			TNT1 A 0 doomb_severed_limb("XDeathBurnedArm", "spawn", limb_ignore_cvar: true);
		Stop;
		
		Death:    
			TNT1 AAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		Stop;
		
		Death.Kick:
		Death.punch:
			HND3 A 1 A_FaceTarget;
			TNT1 A 0 doomb_severed_limb("XDeathChainArm", "spawn", (0, 0, 3), doomb_random_velocity(7), limb_ignore_cvar: true);
		Stop;
	}
	
}





CLASS ChaingunguyHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		+SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Radius 10;
		
		Mass 60;
		Health 40;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay A_Jump(256, "Spawn1", "SPawn2");
		Spawn1:
			CHHE A 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;
		
		Spawn2:  
			CHHE E 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;
		
		Death:
			TNT1 A 0 doomb_severed_limb("ChaingunguyHeadExplode");
		Stop;
		
		Death.Trample:
		Crush:
			TNT1 AAAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 9009;
		Stop;

		Death.plasma:
			TNT1 A 0 doomb_severed_limb("XDeathBurnedSkull");
			EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		Stop;

		Death.punch:
		Death.Kick:
			CHHE EE 1 A_FaceTarget;
			TNT1 A 0 doomb_severed_limb("XDeathChaingunguyHead");
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		Stop;
			
		Pain:
			TNT1 A 0 {vel.z += 20;}
			CHHE ABCDEFGH 2;
		Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0 {vel.z += 40;}
			CHHE ABCDEFGH 3;
			tnt1 a 0 A_SpawnItem("ChaingunguyHead");
		Stop;
	}
	
}


CLASS PlayerChaingunguyVictim : doomb_body_base { 
Default {
		Radius 16;
		Height 50;
		Health 70;
		
		PainSound "grunt/pain";
		PainChance 255;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+NORADIUSDMG;
		+FLOORCLIP;
		+DONTSPLASH;
		Scale 1.0;
}
	States
	{
		Spawn:
			XPL8 A 50;
		DieNow:
			PLAY JKL 5;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Fall;
			TNT1 A 0 {bSHOOTABLE = false;}
			PLAY L -1;
		Stop;
			
		Pain:
			TNT1 A 0 A_Jump(129, "Pain2");
			XPL8 B 2;
		Goto Spawn;
			
		Pain2:
			XPL8 C 3;
		Goto Spawn;
			
		Death:
			TNT1 A 0 doomb_Rip_Guts();
			TNT1 A 0 doomb_severed_limb("XDeathHalfMarine", 'spawn', (0, 0, 50), doomb_random_velocity(3), true);
			TNT1 A 0 doomb_much_blood();
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			XPL2 A 10 A_XScream;
			TNT1 AA 0 doomb_spawn_big_blood (50);
			XPL2 B 20 A_NoBlocking;
			TNT1 AA 0 doomb_spawn_big_blood(50);
			XPL2 C 10 doomb_spawn_big_blood(40);
			TNT1 AA 0 doomb_spawn_big_blood(30);
			XPL2 DE 10 doomb_spawn_big_blood(20);
			TNT1 A 0 doomb_spawn_bloodpool();
			XPL2 E -1;
		Stop;
			
	}
	
}



CLASS DyingComando : doomb_body_base
{
Default
{
	Radius 21;
	Height 15;
	Health 40;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	+FORCEXYBILLBOARD;
	-SOLID;
	+SHOOTABLE;
	Scale 1.0;
}

States
{
	Spawn:
		CFTB AB 10 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_Pain;
		tnt1 a 0 a_jump(200, "spawn");
	Death:
		CFTB D 1 a_givetotarget("CrueltyBonus5Health");
		TNT1 AAAAAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 1 doomb_severed_limb("BrutalizedDeadChaingunGuy", limb_ignore_cvar: true);
	Stop;

	XDeath:
		TNT1 A 0 doomb_severed_limb("ChainXDeath");
		TNT1 AAA 0 doomb_much_blood();
	Stop;
}

}