
CLASS doomb_baron : doomb_monster_base
{ 
Default {
	
	doomb_monster_base.headshot_multiplier 2;
	doomb_monster_base.head_starting_position 50;//so that if someone forgot to define this number monster dont get headshot from every attack
	doomb_monster_base.legs_height_max -1;//same for legs
	
	Scale 1.0;
	damagefactor "Crush", 10.0;
	GibHealth 25;
	Health 1000;
	PainChance "Saw", 100;
	PainChance "Cut", 100;
	PainChance 25;
	PainChance "Kick", 255;
	damagefactor "SSG", 0.2;
	damagefactor "Fatality", 3.0;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	+QUICKTORETALIATE;
	PainChance "Explosive_Impact", 90;
	PainSound "PSXDPN";
	BloodType "Brutal_Blood",  "SawBlood";
	Obituary "%o was brutalized by a Baron of Hell.";
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	+DONTHaRmclass;
	Speed 6;
	
	Health 1000;
	Radius 24;
	Height 64;
	Mass 1000;
	Speed 8;
	PainChance 50;
	Monster;
	+FLOORCLIP;
	+BOSSDEATH;
	SeeSound "baron/sight";
	PainSound "baron/pain";
	DeathSound "baron/death";
	ActiveSound "baron/active";
	HitObituary "$OB_BARONHIT";
	Tag "$FN_BARON";
	species 'bruiser';
	
}
States
{
	
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
		TNT1 A 0 A_JumpIfInventory("DemonFatality", 1, "FatalityDemon");
	Stand:
		BOSS b 10 A_Look;
	Loop;
		
	See:
		BTS3 ABC 1;
		TNT1 A 0 A_FaceTarget;
		BTS3 D 6 ;
		BTS3 CBA 1;
		TNT1 A 0 HealThing(200);
	See2:
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		TNT1 A 0 A_JumpIfInventory("DemonFatality", 1, "FatalityDemon");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
	SeeNeverSeen:
		BOSS AAAABBCCCCDD 2 A_Chase;
		tnt1 a 0 doomb_monster_memory();
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
	Loop;
		
	Idle:
	LookingForPlayer:
		BOSS BBB 10 A_Look;
		TNT1 A 0 {angle += random(-40, 40);}
		BOSS BBBBBB 10 A_Look;
		BOSS AABBCCDD 2
		{
			A_Look();
			A_Wander();
			A_Recoil(-1);
		}
	loop;
		
		
		
	RAGE:
		TNT1 A 0 A_CheckSight("See");
		BTS3 ABC 2 ;
		BTS3 DEDFDEDFCBA 2;
		TNT1 A 0 HealThing(200);
		TNT1 A 0 A_Jump(96, "SpecialAttack");
	Goto See2;
		
	Melee:
		BOSS E 1
		{
			A_FaceTarget();
			doomb_update_memory();
		}
		BOSS E 1;
		BOSS E 6 A_PlaySound("weapons/gswing");
		BOSS F 6 A_FaceTarget;
		BOSS G 6
		{
			actor a = doomb_cheap_melee_attack(120, random(36, 80), "BHFT");
		
			if(a && a.health <= 0)
			{
				name type = a.getclassname();

				switch(type)
				{
					case 'doomb_zombie_Man':
						a.destroy();
						setstatelabel("FatalityZombieman");
					break;

					default:
					//FIXME add handlers for other fatalitys
					break;
				}
			}
		}
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		TNT1 A 0 A_JumpIfInventory("DemonFatality", 1, "FatalityDemon");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
	Goto See2;
		
	Missile:
		BOSS A 1
		{
			doomb_update_memory();
		}
		TNT1 A 0 A_TakeInventory("StopKickingMyBallsMotherFucker", 1);
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		BOSS e 3 A_FaceTarget;

		TNT1 A 0 A_Jump (64, "SpecialAttack");
		BOSS EEEE 2
		{
			A_FaceTarget();
			doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 40 , 78), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		}
		BOSS F 3 A_FaceTarget;
		
		BOSS G 8 A_SpawnProjectile("GreenPlasmaBall", 36, 0, 0, 1);
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
	Goto See2;
		
	SpecialAttack:
		BOSS RQ 3 A_FaceTarget;
		BOSS pppppPppp 2
		{
			A_FaceTarget();
			doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 40 , 78), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 40 , 78), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		}
		BOSS QQ 4
		{
			A_FaceTarget();
			doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 40 , 78), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 40 , 78), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		}
		BOSS R 8
		{
			A_SpawnProjectile("GreenPlasmaBall", 36, 15, 9, 11);
			A_SpawnProjectile("GreenPlasmaBall", 36, 15, -9, 11);
			A_SpawnProjectile("GreenPlasmaBall", 36, 15, 0, 11);
		}
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
	Goto See2;
		
		
	MissileBarrel:
		BOBA A 1 A_Chase(null,null);
		BOBA A 0 {bNOPAIN = true;}
		BOBA ABC 4;
		BOBA D 1;
		TNT1 A 0 A_PlaySound("baron/sight");
	WaitingToThrow:
		BOBA D 8;
		TNT1 A 0 A_CheckSight("WaitingToThrow");
		BOBA E 16;
		BOBA D 8;
	ThrowBarrel:
		BOSS P 2 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("ThrowedBarrel", 46, 15, 0, 11);
		BOSS Q 4 A_FaceTarget;
		BOBA A 0 {bNOPAIN = false;}
	Goto See2;
		
	WithBarrelLookFOrTheplayer:
		TNT1 A 0 A_ClearTarget;
		BOSS P 2 A_Chase;
	Goto See2;
		
		
	Pain.Explosive_Impact:
		TNT1 A 0 {vel.z += 5;}
	Pain:
		BOSS H 3 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		BOSS H 3 A_Pain;
	Goto See2;
		
	Death:
		BOSS I 8
		{
			A_Screamandunblock();
			A_BossDeath();
		}
		BOSS JKLMN 8;
		BOSS O -1;
	Stop;
		
	XDeath:
		TNT1 A 0 doomb_severed_limb("BaronXDeath");
		TNT1 A 0 doomb_severed_limb("XDeathBaronHead5", "spawn", (0, 0, 62), limb_ignore_cvar: true);
		BXDE B 0 A_Scream;
		BXDE C 0 A_BossDeath;
		BXDE D 0 A_NoBlocking;
		BXDE EFGH 1;
	Stop;

	Death.Blast:
	Death.SSG:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		TNT1 AAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 60) );
		BDSS PQRSTU 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		BDSS VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 1 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		BDSS V -1;
	Stop;
		
	Pain.Kick:
		TNT1 A 0 {bMISSILEMORE = true;}
		TNT1 A 0 {bMISSILEEVENMORE = true;}
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		TNT1 A 0 A_JumpIfInventory("StopKickingMyBallsMotherFucker", 1, "Missile");
		TNT1 A 0 A_GiveInventory("StopKickingMyBallsMotherFucker", 1);
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 {bNOPAIN = true;}
	mini_pain:
		BNRJ ABCD 5;
		TNT1 A 0 A_Pain;
		tnt1 a 0 a_jump(180,"mini_pain");
	Goto Missile;
		
	Death.Explosive_Impact:
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 A 0 doomb_severed_limb("XDeathHellKnightLeg", "spawn", (0, 0, 32), limb_ignore_cvar: true);
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		TNT1 A 0 doomb_much_blood(62);
		TNT1 A 0 A_Jump(255, "Death.Explosive_Impact1", "Death.Explosive_Impact2");
	Death.Explosive_Impact1:
		BOH3 A 8 A_Scream;
		BOH3 B 8 A_NoBlocking;
	mini_explosive_death:
		BOH3 C 8
		{
			if(vel.z == 0)
				setstate(findstate("land1"));
		}
	loop;

	Land1:
		BOH3 D -1;
	Stop;
		
	Death.Explosive_Impact2:
		BOH3 E 8 A_Scream;
		BOH3 F 8 A_NoBlocking;
	mini_explosion_loop:
		BOH3 G 8
		{
			if(vel.z == 0)
				setstate(curstate+1);
		}
	loop;

	Land2:
		BOH3 H -1;
	Stop;
		
	Death.Cut:
	Death.Saw:
	Death.Crush:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		TNT1 AAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfBOH", "spawn", (0, 0, 24), limb_ignore_cvar: true);
		BBO2 AABCD 10;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadBaronHalfDown", limb_ignore_cvar: true);
	Stop;
		
	Death.CutLess:
		TNT1 A 0 A_Jump(128, "Death.Blast");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_BossDeath;
		KSA8 A 8;
		TNT1 A 0 doomb_severed_limb("DyingBaron1", limb_ignore_cvar: true);
	Stop;
		
		
		
	Death.Shotgun:
	Death.SSG:
		TNT1 A 0 A_JumpIfCloser(300, "Death.Cutless");
	Goto Death;
		
		
	Death.Headshot:
		tnt1 a 0
		{
			switch(random(0, 3))
			{
				case 0:
					doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
					doomb_severed_limb("XDeathBaronHead5", "spawn", (0, 0, 62), limb_ignore_cvar: true);
				break;

				default:
				case 1:
					doomb_severed_limb("BaronOfHellHeadExplode", "spawn", (0, 0, 62), limb_ignore_cvar: true);
				break;
			}
		}
		BADH AB 9;
		BADH C 9 A_BossDeath;
		BADH D 9 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("DeadBaronNoHead", limb_ignore_cvar: true);
		TNT1 A 0 doomb_spawn_bloodpool();
	Stop;
		

	Death.Plasma:
	Death.Plasma2:
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), doomb_random_velocity(1, true) );
		TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), doomb_random_velocity(1, true), (frandom(1.8, 2.2), 0) );
		BOSC ABC 7 doomb_show_effect("ExplosionSmoke", (0, 0, 28), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), doomb_random_velocity(1, true) );
		TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), doomb_random_velocity(1, true), (frandom(1.8, 2.2), 0) );
		BOSC DEF 7 doomb_show_effect("ExplosionSmoke", (0, 0, 14), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		TNT1 A 0 doomb_spawn_bloodpool();
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 8 doomb_show_effect("ExplosionSmoke", (0, 0, 24), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		BOSB E -1;
	Stop;
	
	Death.Fire:
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		BOSB AAAABBBBCCCCDDDD 2 doomb_show_effect("FlameTrails", velocity: (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 doomb_show_effect("FlameTrails", velocity: (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 10 doomb_show_effect("AltSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		BOSB E -1;
	Stop;

	
	CurbstompMarine:
		KNTF A 15 A_SetInvulnerable;
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		KNTF BCD 8 doomb_much_blood();
		EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
		TNT1 A 0 doomb_much_blood();
		TNT1 AAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 50), (random(-3,3), random(-3, 3), frandom(0, 3) ) );
		KNTF DDDDDDDDDDDDDDDDDDD 8 doomb_much_blood(25);

		TNT1 A 0 doomb_Rip_Guts();
		KNTF EEEFFFGGG 8 doomb_much_blood(38);
		KNTF GGGGGGGGGGG 8 doomb_much_blood(25);
		TNT1 A 0 A_TakeInventory("Curbstomp_Marine",1);
		TNT1 A 0 A_UnSetInvulnerable;
		TNT1 A 0 doomb_severed_limb("RappedMarine", limb_ignore_cvar: true);
	Goto See2;
	
	
	FatalityZombieman:
		TNT1 A 0 A_SetInvulnerable;
		3HF1 A 20;
		TNT1 A 0 A_PlaySound("grunt/death");
		3HF1 BC 5;
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		3HF1 BCBC 5;
		TNT1 A 0 doomb_much_blood(55);
		3HF1 D 10;
		3HF1 E 5;
		TNT1 A 0 doomb_severed_limb("XDeathZombieManHead", "spawn", (0, 0, 65) , (random(-3, 3), random (-3, 3), frandom(0, 3) ) );
		3HF1 F 30;
		3HF1 G 10;
		TNT1 A 0 A_UnSetInvulnerable;
		3HF1 H 8 A_Chase;
		BOSS E 8 A_FaceTarget;
		BOSS F 8 A_SpawnProjectile("ThrowedZombieMan2", 64, 0, 0, 0);
		BOSS G 8;
	Goto See2;
	
	throw_sergeant:
		TNT1 A 0 A_SetInvulnerable;
		3HF1 I 15;
		TNT1 A 0 A_PlaySound("grunt/death");
		3HF1 I 5;
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		TNT1 A 0 doomb_severed_limb("SergeantFatalizedByBaron", "spawn", (0, 0, 65) , (random(-3, 3), random (-3, 3), frandom(0, 3) ) );
		3HF1 J 10;
		3HF1 KLM 15;
		TNT1 A 0 A_UnSetInvulnerable;
		3HF1 M 1 A_Chase;
		BOSS E 8 A_FaceTarget;
		BOSS F 8 A_SpawnProjectile("ThrowedSergeantPiece", 64, 0, 0, 0);
		BOSS G 8;
	Goto See2;
	
	
	FatalityDemon:
		TNT1 A 0 A_SetInvulnerable;
		TNT1 A 0 A_PlaySound("demon/pain");
		3HF1 N 20;
		TNT1 A 0
		{
			doomb_internal_organ a = doomb_internal_organ( doomb_severed_limb("doomb_internal_organ", "spawn", (0, 0, 30), doomb_random_velocity(5) ) );

			if(a)
				a.set_gib_appearance(0, DIT_GUT_PILE_FLYING);
		}
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		3HF1 OPQQQ 10 doomb_much_blood(25);
		TNT1 A 0 doomb_severed_limb("DeadDemonHalf", limb_ignore_cvar: true);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_TakeInventory("DemonFatality",1);
		TNT1 A 0 A_UnSetInvulnerable;
	Goto See2;
	
	
	FatalityImp:
		TNT1 A 0 {bSHOOTABLE = false;}
		TNT1 A 0 A_PlaySound("demon/pain");
		3HF2 ABABAB 4;
		TNT1 AAA 0 doomb_much_blood(40);
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 42), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		3HF2 CDE 6;
		3HF2 F 1 A_Chase(null,null);
		3HF2 FFF 15;
		3HF2 GGHHIJ 3;
		TNT1 A 0 doomb_severed_limb("DeadImp_BaronFatality", limb_ignore_cvar: true);
		TNT1 A 0 A_TakeInventory("ImpFatality3",1);
		TNT1 A 0 {bSHOOTABLE = true;}
	Goto See2;
	
	
	
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;
	
	Crush:
	Death.Stomp:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		tnt1 a 0 A_BossDeath;
		BOSS JKL 2;
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_blood_mist(times:6);
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("CrushedRemains", "spawn", limb_ignore_cvar: true);
	Stop;







	Death.Fatality:
		tnt1 A 0 doomb_monster_fatality_camera(target);
		BHF1 AAABCDEF 2;
		BHF1 G 3 A_PlaySound("weapons/gswing");
		BHF1 HIJKLLLMN 2;
		BHF1 O 3 A_PlaySound("demon/pain");
		tnt1 AAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 35), (random(-3, 3), random(-3, 3), frandom(0, 3) ) );
		tnt1 A 0 A_PlaySound("misc/xdeath4", CHAN_AUTO, 1);
		BHF1 PQR 3 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 35), (random(-3, 3), random(-3, 3), frandom(0, 3) ) );
		tnt1 A 0 A_PlaySound("misc/xdeath4", CHAN_AUTO, 1);
		tnt1 A 0 A_PlaySound("misc/xdeath3", CHAN_AUTO, 1);
		tnt1 A 0 A_PlaySound("misc/xdeath2", CHAN_AUTO, 1);
		tnt1 A 0 A_PlaySound("misc/xdeath1", CHAN_AUTO, 1);
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 AAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 35), (random(-3, 3), random(-3, 3), frandom(0, 3) ) );
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		BHF1 STUV 3 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 35), (random(-3, 3), random(-3, 3), frandom(0, 3) ) );
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 AAAAAA 0 doomb_sticky_guro(SGT_MEAT);
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		tnt1 AAAAAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 50), (random(-3, 3), random(-3, 3), frandom(0, 3) ) );
		tnt1 A 0 doomb_severed_limb("MeatDeath", "spawn", (0, 0, random(30, 40) ) );
		BHF1 WXYZZZZZZZZZZZZZZ 3;
		tnt1 A 0
		{
			A_Givetotarget("health",100);
			doomb_severed_limb("DeadBaronNoHead", limb_ignore_cvar: true);
			doomb_destroy_monster_fatality_camera();
			A_BossDeath();
		}
	Stop;
}

}