
CLASS DeadBaron: CurbstompedMarine { 
Default {
	
	Radius 12;
	Height 12;
	Scale 1.2;
	+SHOOTABLE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	-SOLID;
	+THRUACTORS;
	damagefactor "Crusher", 50.0;
	Mass 1000;
	Health 200;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
}
States
{
	Spawn:
		BADD F -1;
	Stop;
	
	Raise:
		TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("doomb_baron");
	Stop;
		
	Death:
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN );
		Stop;
		
	Death.Plasma:
	Death.Plasma2:
	Death.Fire:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		EXPL AAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		BOSB ABCDE 9 doomb_show_effect("ExplosionSmoke", (0, 0, 24), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 8 doomb_show_effect("ExplosionSmoke", (0, 0, 11), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		BOSB E -1;
	Stop;
}

}


CLASS DeadBaronHalfDown: DeadBaron { 
States
{
	Spawn:        
		BBO2 D -1;
	Stop;
}

}

CLASS XDeathHalfBOH : doomb_body_base
{ 
Default {
	
	Radius 1;
	Height 8;
	Speed 10;
	Mass 8;
	BounceFactor 0.3;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	
	DeathSound "misc/xdeath1";
}
States
{
	Spawn:
		BTO2 AABBCC 4 A_SpawnProjectile("Blood",0,0,180,2);
	Stop;

	death:
		BTO2 D -1 doomb_final_absolution(12, 12);
	stop;
}

}

CLASS DeadBaronNoHead: DeadBaron { 
States
{
	Spawn:
		BADH D -1;
	Stop;
}

}





CLASS DyingBaron1 : doomb_body_base
{ 
Default
{
	Radius 16;
	Height 64;
	doomb_monster_base.head_starting_position 50;
	doomb_monster_base.headshot_multiplier 3;

	Health 100;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	
	damagefactor "mini_gun", 0.6;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+FLOORCLIP;
	+DONTSPLASH;
	+NOPAIN;
	Scale 1.2;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound ("PSXDPN");
		KSA8 BC 6;
		TNT1 A 0 doomb_blood_dying();
		tnt1 a 0 a_jump(200, "spawn");
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_PlaySound("baron/death");
		KSA8 DEFG 6;
		KSA8 G -1 doomb_final_absolution(12, 12);
	Stop;
		
	Death.Headshot:
		TNT1 A 0 doomb_severed_limb("BaronOfHellHeadExplode", "spawn", (0, 0, 62), limb_ignore_cvar: true );
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		TNT1 AA 0 doomb_severed_limb("BaronHeadPiece", "spawn", (0, 0, 62) );
		BADH A 9;
		BADH B 9;
		BADH C 9 A_BossDeath;
		BADH D  9 A_NoBlocking;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadBaronNoHead", limb_ignore_cvar: true );
	Stop;
		
		
	Death.SSG:
	XDeath:
	Death.Explosive_Impact:
		TNT1 A 0 A_XScream;
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("BaronXDeath", limb_ignore_cvar: true );
	Stop;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(120, "Death");
	Death.mini_gun:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN );
		TNT1 AAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfBOH", "spawn", (0, 0, 24), limb_ignore_cvar: true);
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		BBO2 AABCD 10;
		TNT1 A 0 doomb_spawn_bloodpool();
		BBO2 D -1 doomb_final_absolution(12, 12);
	Stop;
}

}	





CLASS XDeathBaronofHellTorso: doomb_body_base
{ 
Default
{
	Radius 8;
	Height 8;
	Scale 1.1;
	Speed 8;
	Mass 1;
	gravity 0.5;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	wallbouncefactor 0.2;
	BounceCount 3;
	+DOOMBOUNCE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MISSILE;
	+EXPLODEONWATER;
	+SKYEXPLODE;
	-DONTSPLASH;
	seesound "bloood";
	deathsound "bloood";

	Scale 1.3;
	Speed 12;
	BounceFactor 0.4;
}

States
{
	Spawn:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		GORD ABCD 4 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), doomb_random_velocity(5) );
	Loop;

	Death:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		GORD E 1 doomb_severed_limb("Gib_BaronofHellTorso", limb_ignore_cvar: true);
	Stop;
}
}

CLASS Gib_BaronofHellTorso: LimbBase
{
Default
{
	Scale 1.3;
}

States
{
	Spawn:
		GORD E 1900 doomb_spawn_bloodpool(BPS_SMALL);
	Loop;
		
	Death.plasma:
	Death.Fire:
		TNT1 A 0 doomb_spawn_burned_flesh;
	Stop;
		
	Death:    
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN );
	Stop;
}

}





CLASS BaronHeadPiece : doomb_body_base
{
States
{
	Spawn:
		XHE5 IJKL 4
		{
			if(waterlevel > 1 || vel == (0, 0, 0) )
				setstatelabel("death");
			doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), doomb_random_velocity(5) );
		}
	Loop;
	
	Death:
		XHE5 I 800;
		XHE5 I 35 a_fadeout(0.05);
	wait;
}

}





CLASS BaronHead: LimbBase
{
Default
{
	
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	-CLIENTSIDEONLY;
	Radius 10;
	
	Mass 60;
	Health 60;
	Scale 1.2;
}

States
{
	Spawn:
		XHE5 A 1900 doomb_spawn_bloodpool(BPS_SMALL);
	Loop;
		
	Pain:
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE5 ABCDEFGH 2;
	Goto Spawn;

	Death:
		TNT1 A 0 doomb_severed_limb("BaronOfHellHeadExplode");
	Stop;

	Death.Trample:
	Crush:
		TNT1 AAAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), doomb_random_velocity(5) );
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 B 9009;
	Stop;

	Death.plasma:
		TNT1 A 0 doomb_severed_limb("XDeathBurnedSkull");
		EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 32), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
	Stop;

	Death.punch:
	Death.Kick:
		XHE5 A 1 A_Pain;
		XHE5 A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("XDeathBaronHeadKicked");
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
	Stop;
		
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XHE5 ABCDEFGH 3;
	Stop;
}
	
}

CLASS XDeathBaronHeadKicked: XDeathBaronHead5 { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}