
CLASS doomb_baron : doomb_monster_base Replaces BaronofHell
{ 
Default {
	
	doomb_monster_base.headshot_multiplier 2;
	doomb_monster_base.head_starting_position 58;//so that if someone forgot to define this number monster dont get headshot from every attack
	doomb_monster_base.legs_height_max -1;//same for legs
	
	Scale 1.1;
	damagefactor "Crush", 10.0;
	damagefactor "GibRemoving", 0.0;
	GibHealth 25;
	Health 1000;
	PainChance "Saw", 100;
	PainChance "Cut", 100;
	PainChance "Head", 120;
	PainChance 25;
	PainChance "Kick", 255;
	PainChance "CallingTheBaronAFaggot", 255;
	damagefactor "TeleportRemover", 0.0;
	damagefactor "Avoid", 0.0;
	damagefactor "SSG", 0.2;
	damagefactor "DontCallTheBaron", 0.0;
	DamageFactor "CauseObjectsToSplash", 0.0;
	damagefactor "Fatality", 3.0;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	+QUICKTORETALIATE;
	PainChance "Explosive_Impact", 255;
	PainSound "PSXDPN";
	BloodType "Brutal_Blood",  "SawBlood";
	Obituary "%o was brutalized by a Baron of Hell.";
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	+DONTHaRmclass;
	Speed 6;
	
	Health 1000;
	Radius 24;
	Height 64;
	Mass 1000;
	Speed 8;
	PainChance 50;
	Monster;
	+FLOORCLIP;
	+BOSSDEATH;
	SeeSound "baron/sight";
	PainSound "baron/pain";
	DeathSound "baron/death";
	ActiveSound "baron/active";
	HitObituary "$OB_BARONHIT";
	Tag "$FN_BARON";
	
}
States
{
	
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		TNT1 A 0 A_JumpIfInventory("ZombiemanFatality", 1, "FatalityZombieman");
		TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
		TNT1 A 0 A_JumpIfInventory("DemonFatality", 1, "FatalityDemon");
	Stand:
		BOSS b 10 A_Look;
	Loop;
		
	See:
		TNT1 A 0 A_JumpIfInventory("HasExplosiveBarrel", 1, "MissileBarrel");
		BTS3 ABC 1;
		TNT1 A 0 A_FaceTarget;
		BTS3 D 6 ;
		BTS3 CBA 1;
		TNT1 A 0 HealThing(200);
	See2:
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		TNT1 A 0 A_JumpIfInventory("ZombiemanFatality", 1, "FatalityZombieman");
		TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		TNT1 A 0 A_JumpIfInventory("DemonFatality", 1, "FatalityDemon");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
		TNT1 A 0 A_JumpIfInventory("HasExplosiveBarrel", 1, "MissileBarrel");
	SeeNeverSeen:
		BOSS AAAABBCCCCDD 2 A_Chase;
			TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
	Loop;
		
	Idle:
	LookingForPlayer:
		BOSS BBB 10 A_Look;
		TNT1 A 0 A_SetAngle(angle - 40);
		
		BOSS BBB 10 A_Look;
		TNT1 A 0 A_SetAngle(angle + 40);
		BOSS BBB 10 A_Look;
		BOSS AABBCCDD 2
		{
			A_Look();
			A_Wander();
			A_Recoil(-1);
		}
	loop;
		
		
		
	ForgetTarget:
		TNT1 A 0 A_ClearTarget;
		TNT1 A 0 A_TakeInventory("EnemyMemory", 25);
	Goto LookingForPlayer;
		
		
	RAGE:
		TNT1 A 0 A_CheckSight("See");
		BTS3 ABC 2 ;
		BTS3 DEDFDEDFCBA 2;
		TNT1 A 0 HealThing(200);
		TNT1 A 0 A_Jump(96, "SpecialAttack");
	Goto See2;
		
	Melee:
			TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("BaronAttackOnBarrel",10,0,0,0);
		BOSS E 1;
		TNT1 A 0 A_JumpIfInventory("HasExplosiveBarrel", 1, "MissileBarrel");
		BOSS E 6 A_PlaySound("weapons/gswing");
		BOSS F 6 A_FaceTarget;
		BOSS G 6 A_SpawnProjectile("BaronAttack",10,0,0,0);
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		TNT1 A 0 A_JumpIfInventory("ZombiemanFatality", 1, "FatalityZombieman");
	Goto See2;
		
	Melee2:
		BOSS EF 6 A_FaceTarget;
		BOSS G 6 A_SpawnProjectile("BaronAttack",10,0,0,0);
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		TNT1 A 0 A_JumpIfInventory("ZombiemanFatality", 1, "FatalityZombieman");
		TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		TNT1 A 0 A_JumpIfInventory("DemonFatality", 1, "FatalityDemon");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
	Goto See2;
		
	Missile:
		BOSS A 1;
		TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
			TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
		TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAnExplosiveBarrel", 1, "See2");
		TNT1 A 0 A_TakeInventory("StopKickingMyBallsMotherFucker", 1);
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		TNT1 A 0 A_JumpIfInventory("ZombiemanFatality", 1, "FatalityZombieman");
		TNT1 A 0 A_JumpIfInTargetInventory ("TypeZombieman", 1, "See2");
		TNT1 A 0 A_JumpIfInTargetInventory ("TypeSergeant", 1, "See2");
		BOSS e 3 A_FaceTarget;

		TNT1 A 0 A_Jump (64, "SpecialAttack");
		BOSS EEEE 2
		{
			A_FaceTarget();
			doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 40 , 78), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			A_SpawnProjectile ("BallGettingReadyGreen", 79, 40, random (0, 140), 2, random (0, 160));
		}
		BOSS F 3 A_FaceTarget;
		
		BOSS G 8 A_SpawnProjectile("GreenPlasmaBall", 36, 0, 0, 1);
		TNT1 A 0 A_TakeInventory("ComingToGetTheBarrel", 1);
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
	Goto See2;
		
	SpecialAttack:
		BOSS RQ 3 A_FaceTarget;
		BOSS pppppPppp 2
		{
			A_FaceTarget();
			doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 40 , 78), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 40 , 78), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			A_SpawnProjectile ("BallGettingReadyGreen", 79, 40, random (0, 140), 2, random (0, 160));
			A_SpawnProjectile ("BallGettingReadyGreen", 79, -40, random (0, 140), 2, random (0, 160));
		}
		BOSS QQ 4
		{
			A_FaceTarget();
			doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 40 , 78), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 40 , 78), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		}
		BOSS R 8
		{
			A_SpawnProjectile("GreenPlasmaBall", 36, 15, 9, 11);
			A_SpawnProjectile("GreenPlasmaBall", 36, 15, -9, 11);
			A_SpawnProjectile("GreenPlasmaBall", 36, 15, 0, 11);
		}
		TNT1 A 0 A_TakeInventory("ComingToGetTheBarrel", 1);
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
	Goto See2;
		
		
	CheckRetreat:
		TNT1 A 0 A_JumpIfCloser(600, "Retreat");
	Goto Missile;
		
	Retreat:
		BOSS DDDDCCCCBBBBAAAA 2
		{
			A_Recoil(2);
			A_FaceTarget();
		}
	Goto Missile;
		
	Pain.CallingTheBaronAFaggot:
		TNT1 A 0 A_GiveInventory("ComingToGetTheBarrel", 1);
	Goto See2;
		
	MissileBarrel:
		BOBA A 0;
		BOBA A 1 A_Chase(null,null);
		BOBA A 0 {bNOPAIN = true;}
		BOBA ABC 4;
		BOBA D 1;
		TNT1 A 0 A_PlaySound("baron/sight");
	WaitingToThrow:
		BOBA D 8;
		TNT1 A 0 A_CheckSight("WaitingToThrow");
		BOBA E 16;
		BOBA D 8;
		
	ThrowBarrel:
		BOSS P 2 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("ThrowedBarrel", 46, 15, 0, 11);
		BOSS Q 4 A_FaceTarget;
		BOSS R 8 A_TakeInventory("ComingToGetTheBarrel", 1);
		TNT1 A 0 A_TakeInventory("HasExplosiveBarrel", 1);
		BOBA A 0 {bNOPAIN = false;}
	Goto See2;
		
	WithBarrelLookFOrTheplayer:
		TNT1 A 0 A_ClearTarget;
		BOSS P 2 A_Chase;
	Goto See2;
		
		
	Pain.Explosive_Impact:
		TNT1 A 0 {vel.z += 5;}
	Pain:
		BOSS H 3 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		BOSS H 3 A_Pain;
	Goto See2;
		
	Death:
		BOSS I 8;
		BOSS J 8 A_Scream;
		BOSS K 8;
		BOSS L 8 A_NoBlocking;
		BOSS MN 8;
		BOSS O -1 A_BossDeath;
	Stop;
		
	XDeath:
		TNT1 A 0 A_SpawnProjectile ("BaronXDeath", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBaronHead5", 62, 0, random (0, 360), 2, random (0, 160));
		BXDE A  0;
		BXDE B  0 A_Scream;
		BXDE C  0 A_BossDeath;
		BXDE D  0 A_NoBlocking;
		BXDE EFGH 1;
	Stop;

	Death.Blast:
	Death.SSG:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath2b", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath3b", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeathBrain1", 60, 0, random (0, 360), 2, random (0, 160));
		BDSS PQRSTU 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		BDSS VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 1 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, random (0, 360), 2, random (30, 110));
		BDSS V -1;
	Stop;
		
	Pain.Kick:
		TNT1 A 0 {bMISSILEMORE = true;}
		TNT1 A 0 {bMISSILEEVENMORE = true;}
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		TNT1 A 0 A_JumpIfInventory("StopKickingMyBallsMotherFucker", 1, "Missile");
		TNT1 A 0 A_GiveInventory("StopKickingMyBallsMotherFucker", 1);
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 {bNOPAIN = true;}
		BNRJ ABCD 5;
		TNT1 A 0 A_Pain;
		BNRJ ABCD 5;
		TNT1 A 0 A_Pain;
		BNRJ ABCD 5;
	Goto Missile;
		
	Death.Explosive_Impact:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("XDeath1", 62, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("MuchBlood", 62, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Jump(255, "Death.Explosive_Impact1", "Death.Explosive_Impact2");
	Death.Explosive_Impact1:
		BOH3 A  8 A_Scream;
		BOH3 B  8 A_NoBlocking;
		BOH3 C 8
		{
			if(vel.z != 0)
				setstate(curstate);
		}
	Land1:
		BOH3 D -1;
	Stop;
		
	Death.Explosive_Impact2:
		BOH3 E  8 A_Scream;
		BOH3 F  8 A_NoBlocking;
		BOH3 G 8
		{
			if(vel.z != 0)
				setstate(curstate);
		}
	Land2:
		BOH3 H -1;
	Stop;
		
	Death.Cut:
	Death.Saw:
	Death.Crush:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAAA 0 A_SpawnProjectile ("Xdeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfBOH", 24, 0, random (0, 360), 2, random (0, 160));
		BBO2 AABCD 10;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("DeadBaronHalfDown", 1);
	Stop;
		
	Death.CutLess:
		TNT1 A 0 A_Jump(128, "Death.Blast");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_BossDeath;
		KSA8 A 8;
		TNT1 A 0 A_SpawnItem("DyingBaron1");
	Stop;
		
		
		
	Death.Shotgun:
	Death.SSG:
		TNT1 A 0 A_JumpIfCloser(300, "Death.Cutless");
	Goto Death;
		
		
	Death.Headshot:
		TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
		TNT1 A 0 A_SpawnItem("BaronOfHellHeadExplode", 0, 62);
		BADH A 9;
		BADH B 9;
		BADH C 9 A_BossDeath;
		BADH D 9 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("DeadBaronNoHead", 1);
		TNT1 A 0 doomb_spawn_bloodpool();
	Stop;
		
	Death.decaptate:
		TNT1 AAAAA 0 A_SpawnProjectile ("Xdeath1", 62, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 A_SpawnProjectile ("XDeathBaronHead5", 62, 0, random (0, 360), 2, random (50, 130));
		BADH AB 9;
		BADH C 9 A_BossDeath;
		BADH D 9 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("DeadBaronNoHead", 1);
		TNT1 A 0 doomb_spawn_bloodpool();
	Stop;
		
	Death.Fatality:
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_GiveToTarget("BaronFatality", 1);
		TNT1 A 1 A_NoBlocking;
		TNT1 A 0 A_BossDeath;
	Stop;
		
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
		TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(1.8, 2.2), 0) );
		BOSC ABC 7 doomb_show_effect("ExplosionSmoke", (0, 0, 28), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
		TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(1.8, 2.2), 0) );
		BOSC DEF 7 doomb_show_effect("ExplosionSmoke", (0, 0, 14), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		TNT1 A 0 doomb_spawn_bloodpool();
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 8 doomb_show_effect("ExplosionSmoke", (0, 0, 24), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		BOSB E -1;
	Stop;
	
	Death.GreenFire:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_spawn_burned_flesh;
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("GreenFlameTrails", (0, 0, 50), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
	Stop;

	Death.Fire:
		TNT1 A 0;
		TNT1 A 0 A_BossDeath;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		BOSB AAAABBBBCCCCDDDD 2 doomb_show_effect("FlameTrails", velocity: (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 doomb_show_effect("FlameTrails", velocity: (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 10 doomb_show_effect("AltSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		BOSB E -1;
	Stop;

	
	CurbstompMarine:
		TNT1 A 0 A_SetInvulnerable;
		KNTF A 15;
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath2b", 25, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath3b", 25, 0, random (0, 360), 2, random (0, 160));
		KNTF BCD 8 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
		KNTF DDDDDDDDDDDDDDDDDDD 8 A_SpawnProjectile ("MuchBlood", 25, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("RipGuts", 20, 0, random (0, 360), 2, random (0, 160));
		KNTF EEEFFFGGG 8 A_SpawnProjectile ("MuchBlood", 38, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("RipGuts", 20, 0, random (0, 360), 2, random (0, 160));
		KNTF GGGGGGGGGGG 8 A_SpawnProjectile ("MuchBlood", 25, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_TakeInventory("Curbstomp_Marine",1);
		TNT1 A 0 A_UnSetInvulnerable;
		TNT1 A 0 A_SpawnItem ("RappedMarine", 1);
	Goto See2;
	
	
	FatalityZombieman:
		TNT1 A 0 A_SetInvulnerable;
		3HF1 A 20;
		TNT1 A 0 A_PlaySound("grunt/death");
		3HF1 BC 5;
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 55, 0, random (0, 360), 2, random (0, 160));
		3HF1 BCBC 5 A_SpawnProjectile ("XDeath1", 55, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 55, 0, random (0, 360), 2, random (0, 160));
		3HF1 D 10;
		3HF1 E 5;
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieManHead", 65, 0, random (0, 360), 2, random (70, 120));
		3HF1 F 30;
		3HF1 G 10;
		TNT1 A 0 A_TakeInventory("ZombieManFatality",1);
		TNT1 A 0 A_UnSetInvulnerable;
		3HF1 H 8 A_Chase;
		BOSS E 8 A_FaceTarget;
		BOSS F 8 A_SpawnProjectile("ThrowedZombieMan2", 64, 0, 0, 0);
		BOSS G 8;
	Goto See2;
	
	FatalitySergeant:
		TNT1 A 0 A_SetInvulnerable;
		3HF1 I 15;
		TNT1 A 0 A_PlaySound("grunt/death");
		3HF1 I 5;
		TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath2", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem("SergeantFatalizedByBaron");
		3HF1 J 10;
		3HF1 KLM 15;
		TNT1 A 0 A_TakeInventory("SergeantFatality",1);
		TNT1 A 0 A_UnSetInvulnerable;
		3HF1 M 1 A_Chase;
		BOSS E 8 A_FaceTarget;
		BOSS F 8 A_SpawnProjectile("ThrowedSergeantPiece", 64, 0, 0, 0);
		BOSS G 8;
	Goto See2;
	
	
	FatalityDemon:
		TNT1 A 0 A_SetInvulnerable;
		TNT1 A 0 A_PlaySound("demon/pain");
		3HF1 N 20;
		TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 60, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath2", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (0, 160));
		3HF1 OPQQQ 10 A_SpawnProjectile ("MuchBlood", 25, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("DeadDemonHalf", 1);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_TakeInventory("DemonFatality",1);
		TNT1 A 0 A_UnSetInvulnerable;
	Goto See2;
	
	
	FatalityImp:
		TNT1 A 0 {bSHOOTABLE = false;}
		TNT1 A 0 A_PlaySound("demon/pain");
		3HF2 ABABAB 4;
		TNT1 AAAAAA 0 A_SpawnItem("MuchBlood", 40);
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath2", 45, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 42, 0, random (0, 360), 2, random (0, 160));
		3HF2 CDE 6;
		3HF2 F 1 A_Chase(null,null);
		3HF2 FFF 15;
		3HF2 GGHHIJ 3;
		TNT1 A 0 A_SpawnItem("DeadImp_BaronFatality");
		TNT1 A 0 A_TakeInventory("ImpFatality3",1);
		TNT1 A 0 {bSHOOTABLE = true;}
	Goto See2;
	
	
	
	Pain.KillMe:
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;
	
	Crush:
	Death.Stomp:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		BOSS JKL 2;
		TNT1 AA 0 A_SpawnItem("MeatDeathSmall");
		TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath2b", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath3b", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
	Stop;
}
}