
CLASS FrozenBaronOfHell : ACTOR { 
	Default {
		
		+SOLID;
		+SHOOTABLE;
		+NOBLOOD;
		+PUSHABLE;
		
		Radius 24;
		Height 64;
		Health 60;
		Scale 1.3;
	}
	States
	{
		Spawn:
			FZD7 A 200;
			FZD7 A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZD7 A 50;
			FZD7 B 2;
			FZD7 A 50;
			FZD7 B 2;
			FZD7 A 50;
			FZD7 B 2;
			FZD7 A 25;
			FZD7 B 2;
			FZD7 A 25;
			FZD7 B 2;
			FZD7 A 10;
			FZD7 B 2;
			FZD7 A 10;
			FZD7 B 2;
			FZD7 A 10;
			FZD7 BABABA 2;
		Death.Fire:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_spawnItem("BaronOfHell");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("MuchBlood", 48, 0, random (0, 360), 2, random (0, 160));
			FZD7 C 300;
			FZD7 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
			Stop;
	}
}


CLASS BaronAttack : ACTOR { 
	Default {
		
		Radius 24;
		Height 16;
		DamageType "BHFT";
		Projectile;
		+RANDOMIZE;
		+FORCEXYBILLBOARD;
		+THRUGHOST;
		RenderStyle "Add";
		Alpha 0.6;
		Damage 16;
		Speed 28;
	}
	States
	{
		Spawn:
			TNT1 A 2 BRIGHT;
			TNT1 A 2;//A_PlaySound("weapons/gswing")
			Goto Death;
		Death:
			TNT1 A 0 BRIGHT;
			Stop;
	}
}

CLASS DeadBaron: CurbstompedMarine { 
	Default {
		
		Radius 12;
		Height 12;
		Scale 1.2;
		+SHOOTABLE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		-SOLID;
		+THRUACTORS;
		damagefactor "Crusher", 50.0;
		Mass 1000;
		Health 200;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			BADD F -1;
			Stop;
		Raise:
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 0 A_SpawnItem("TeleportFog");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("BaronOfHell2");
			Stop;
			
		Death:
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
		Death.Plasma:
		Death.Plasma2:
		Death.Fire:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			EXPL AAAAA 0 A_SpawnProjectile ("ExplosionSmoke", 32, 0, random (0, 360), 2, random (0, 360));
			BOSB ABCDE 9 A_SpawnProjectile ("PlasmaSmoke", 24, 0, random (0, 180), 2, random (0, 180));
			BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 8 A_SpawnProjectile ("PlasmaSmoke", 16, 0, random (0, 180), 2, random (0, 180));
			BOSB E -1;
			Stop;
	}
	
}
CLASS DeadBaronHalfDown: DeadBaron { 
	States
	{
		Spawn:        
			BBO2 D -1;
		Stop;
	}
	
}
CLASS DeadBaronHalfUp: DeadBaron { 
	States
	{
		Spawn:
			BTO2 D -1;
		Stop;
	}
	
}
CLASS DeadBaronNoHead: DeadBaron { 
	States
	{
		Spawn:
			BADH D -1;
		Stop;
	}
	
}

CLASS XDeathHalfBOH : ACTOR { 
	Default {
		
		Radius 1;
		Height 8;
		Speed 10;
		Mass 8;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		
		DeathSound "misc/xdeath1";
	}
	States
	{
		Spawn:
			BTO2 AABBCC 4 A_SpawnProjectile("Blood",0,0,180,2);
			HPLA A 0 A_SpawnItem("DeadBaronHalfUp",0,0,0,1);
			Stop;
	}
}





CLASS BaronAttackOnbarrel: BaronAttack { 
	Default {
		
		DamageType "BHFTOnBarrel";
		Damage 1;
	}
}



CLASS CallingTheBaronAFaggot : ACTOR { 
	Default {
		
		Radius 4;
		Height 4;
		DamageType "CallingTheBaronAFaggot";
		Projectile;
		+RANDOMIZE;
		+FORCEXYBILLBOARD;
		+THRUGHOST;
		RenderStyle "Add";
		Alpha 0.6;
		Damagefunction (random (2, 3));
		Speed 32;
		SeeSound "none";
		DeathSound "none";
		Decal "none";
	}
	States
	{
		Spawn:
			TNT1 A 6;
			Goto Death;
		Death:
			TNT1 A 0 BRIGHT;
			Stop;
	}
}


CLASS DyingBaron1 : ACTOR { 
	Default {
		
		
		Radius 16;
		Height 60;
		Health 100;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Avoid", 0.0;
		damagefactor "KillMe", 0.0;
		damagefactor "Cutless", 0.6;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+FLOORCLIP;
		+DONTSPLASH;
		+NOPAIN;
		Scale 1.2;
	}
	States
	{
		Spawn:
			//headbox height 60
			TNT1 A 0;
			TNT1 A 0 A_PlaySound ("PSXDPN");
			KSA8 BC 6;
			TNT1 A 0 A_SpawnItem ("BloodDying", 0, 30);
			KSA8 BC 6;
			TNT1 A 0 A_SpawnItem ("BloodDying", 0, 30);
			TNT1 A 0 A_PlaySound ("PSXDPN");
			tnt1 a 0 a_jump(180, "spawn");
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_PlaySound("baron/death");
			KSA8 DEFG 6;
			KSA8 G -1;//doomb_final_absolution(12, 12)
			Stop;
			
		Death.Headshot:
			TNT1 A 0 A_SpawnItem("BaronOfHellHeadExplode", 0, 62);
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 AA 0 A_SpawnProjectile ("BaronHeadPiece", 62, 0, random (0, 360), 2, random (0, 160));
			BADH A 9;
			BADH B 9;
			BADH C 9 A_BossDeath;
			BADH D  9 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			TNT1 A 0 A_SpawnItem ("DeadBaronNoHead", 1);
			Stop;
			
			
		Death.SSG:
		XDeath:
		Death.Explosive_Impact:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("BaronXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
		Death.Shotgun:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(120, "Death.Cutless");
			Goto Death;
			
		Death.Cutless:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAAAAA 0 A_SpawnProjectile ("Xdeath1", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfBOH", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			BBO2 AABCD 10;
			TNT1 A 0 A_SpawnItem ("GrowingBloodPool");
			BBO2 D -1;//doomb_final_absolution(12, 12)
			Stop;
	}
}	





CLASS XDeathBaronofHellTorso: XDeathArm1 { 
	Default {
		
		Scale 1.3;
		Speed 12;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GORD ABCD 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			GORD E 1 A_SpawnItem("Gib_BaronofHellTorso");
			Stop;
	}
}

CLASS Gib_BaronofHellTorso: LimbBase { 
	Default {
		
		Scale 1.3;
	}
	States
	{
		Spawn:
			GORD E 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
			
		Death.plasma:
		Death.Fire:
			TNT1 A 0 doomb_spawn_burned_flesh;
			Stop;
			
		Death:    
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("Xdeath1", 0, 0, random (0, 360), 2, random (0, 360));
			Stop;
	}
	
}


CLASS XDeathBaronArm : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 8;
		Mass 6;
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal "GreenBloodSuper";
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GORB A 8 A_SpawnProjectile("GreenBloodTrail",0,0,180,2);
			Loop;
		Death:
			GORB A -1;
			Stop;
	}
}


CLASS BaronXDeath : ACTOR { 
	Default {
		
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
	States
	{
		Spawn:
			tnt1 a 0 A_Explode(3,600, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 A 0 A_SpawnProjectile ("XDeathBaronOfHellTorso", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathHellKnightLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath4", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath2b", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath3b", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece2", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece1", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("BigBloodSpot");
			
			TNT1 A 1;
			TNT1 A 0 ACS_ExecuteAlways(799, 0, 0, 0, 0);//Check Blood density
			TNT1 A 2;
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
			Stop;
			
		LowBlood:
			TNT1 A 2;
			Stop;
		LotsOfBlood:
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
			TNT1 AAAAAA 0 A_SpawnProjectile ("SuperGoreSpawner", 64, 0, random (0, 360), 2, random (20, 40));
			Stop;
		AbsurdBlood:
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("SuperGoreMist", 24, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("SuperGoreSpawner", 64, 0, random (0, 360), 2, random (20, 40));
			Stop;
	}
}


CLASS BaronHeadPiece : head_piece_base { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XHE5 IJKL 4 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			XHE5 I 800;
			XHE5 I 35 a_fadeout(0.05);
			wait;
	}
}
