
//===========================================================================
//
// Player
//
//===========================================================================


CLASS Doomer : doomber Replaces DoomPlayer
{

Default {
	
	Speed 1.0;
	Health 100;
	Radius 16;
	Height 56;
	Mass 500;
	player.viewheight 44;
	player.attackzoffset 16;
	GibHealth 20;
	PainChance 255;
	+SOLID;
	+THRUSPECIES;
	+MTHRUSPECIES;
	+DONTHARMCLASS;
	+THRUGHOST;
	Species "Marines";
	BloodType "Player_Blood";
	damagefactor "Taunt", 0.0;
	
	//FIXME most defenitelly sometyhing nasty
	damagefactor "Blood", 0.5;
	damagefactor "BlueBlood", 0.5;
	damagefactor "GreenBlood", 0.5;


	damagefactor "Shotgun", 0.5;
	damagefactor "SSG", 5.0;
	damagefactor "Bullet", 0.5;
	damagefactor "Cutless", 0.33;
	damagefactor "Trample", 8.0;
	damagefactor "Kick", 3.0;
	damagefactor "Fatality", 5.0;
	damagefactor "CancelTeleportFog", 0.0;
	damagefactor "BHFTOnBarrel", 0.0;
	damagefactor "HelperMarineFatallity", 0.0;
	damagefactor "Leg", 0.0;
	damagefactor "SpawnMarine", 0.0;

	Player.ColorRange 112, 127;
	Player.StartItem "Rifle";
	Player.StartItem "Melee_Attacks";
	Player.StartItem "doomb_clip", 60;
	Player.StartItem "RifleAmmo", 31;
	Player.StartItem "DoubleRifleAmmo", 31;
	Player.StartItem "ShotgunAmmo", 8;
	Player.StartItem "PlasmaAmmo", 50;
	Player.StartItem "SSGAmmo", 2;
	Player.StartItem "RocketRounds", 6;
	Player.StartItem "RailgunAmmo", 50;
	Player.StartItem "IsPlayer", 1;
	Player.StartItem "HandGrenades", 1;
	Player.StartItem "GrenadeAmmo", 1;
	Player.StartItem "LeftRifleAmmo", 31;
	Player.StartItem "JustStartedGame", 1;
	Player.StartItem "NeverSelectedShotgun", 1;

	Player.JumpZ 7.4;
	Player.DisplayName "Modern";
	Player.CrouchSprite "PLYC";
}


States
{
	Spawn:
		MARN A 0 A_TakeInventory("IsInvisible", 1);
		MARN A 0 A_TakeInventory("ChainguyguyContinue", 1);
		MARN D 1;
		MARN A 0 doomb_destroy_fatality_camera();//Disable Camera.
		MARN D 1;
		MARN A 0 A_JumpIfInventory("CheckMarines", 1, "SpawnFriends");
	
		TNT1 A 0 {bNOPAIN = false;}
	StandStill:
		MARN A 0 A_JumpIfInventory("ADSMode", 1, "ADSStand");
		MARN A 0 A_JumpIfInventory("GoFatality", 1, "FatalityChecker");
		MARN A 0 A_JumpIfInventory("GoSpecial", 1, "SpecialChecker");
		MARN A 0 {if(self && self.player && self.player.readyweapon && self.player.readyweapon.getclassname() == "Melee_Attacks") setstatelabel("FistsStand");}
		MARN DE 5;
		MARN B 0 A_JumpIfInventory("GoSpecial", 1, "SpecialCheckerMoving");
		MARN A 0 A_JumpIfInventory("CheckMarines", 1, "SpawnFriends");
	Loop;


	See:
		MARN C 0 A_TakeInventory("ChainguyguyContinue", 1);
		MARN C 0 A_JumpIfInventory("ADSMode", 1, "ADSStand");
		MARN A 0 {if(self && self.player && self.player.readyweapon && self.player.readyweapon.getclassname() == "Melee_Attacks") setstatelabel("FistsStand");}
		MARN B 0 A_JumpIfInventory("GoSpecial", 1, "SpecialCheckerMoving");
		MARN A 4 A_SpawnItemEx("FootstepStrong", 0, 0, 40, 0, 0);
		MARN A 0 spawn_blood_footprint();
		MARN A 0 A_JumpIfInventory("GoFatality", 1, "FatalityChecker");
		MARN B 0 A_JumpIfInventory("GoSpecial", 1, "SpecialCheckerMoving");
		MARN B 4;
		MARN A 0 A_JumpIfInventory("GoFatality", 1, "FatalityChecker");
		MARN A 0 A_JumpIfInventory("GoSpecial", 1, "SpecialCheckerMoving");
		MARN C 4 A_SpawnItemEx("FootstepStrong", 0, 0, 40, 0, 0);
		MARN C 0 spawn_blood_footprint();
	Goto StandStill;


	IsJumpin:
		MARN A 1;
		tnt1 A 0 A_JumpIf (vel.z > 0, "InAir");
		tnt1 A 0 A_JumpIf (vel.z < 0, "InAir");
	Goto StandStill;
		
	InAir:
		MARJ A 1 A_JumpIf (vel.z == 0, "Land");
	Loop;
		
	Land:
		TNT1 A 0 A_SetPitch(+3.0 + pitch);
		MARN A 0 A_SpawnItem("FootStepStrong");
		TNT1 A 0 A_GiveInventory("ImpactMovesSling", 1);
		MARN AAA 1 A_SetPitch(-1.0 + pitch);
	Goto StandStill;
		
		
	Kick:
		tnt1 A 0 A_JumpIf (vel.z != 0, "AirKick");
		tnt1 A 0 A_TakeInventory("KickHasHit",1);
		PKIK AB 3 A_JumpIfInventory("GoFatality", 1, "FatalityChecker");
		PKIK CB 3 ;
	Goto StandStill;
	
	RifleKick:
		tnt1 A 0 A_TakeInventory("KickHasHit",1);
		tnt1 A 0 A_JumpIf (vel.z != 0, "AirKick");
		tnt1 A 0 A_TakeInventory("KickHasHit",1);
		PKI1 AB 3 A_JumpIfInventory("GoFatality", 1, "FatalityChecker");
		PKI1 CB 3 A_JumpIfInventory("KickHasHit", 1, "KickHit");
		tnt1 A 0 A_TakeInventory("Kicking",1);
		Goto StandStill;
		
	AirKick:
		AKIK AAAAA 2 A_JumpIfInventory("KickHasHit", 1, "KickHit");
		tnt1 A 0 A_TakeInventory("Kicking",1);
		Goto StandStill;
		
	Punch://melee punch
		PLA1 H 1;
		tnt1 A 0 A_JumpIfInventory("GoFatality", 1, "FatalityChecker");
		tnt1 A 0 A_JumpIfInventory("GotMeatShield", 1, "MeatShieldChecker");
		tnt1 A 0 A_JumpIfInventory("GoSpecial", 1, "SpecialChecker");
		PLA1 H 1;
		PLA1 E 4;
		tnt1 A 0 A_JumpIfInventory("GoFatality", 1, "FatalityChecker");
		tnt1 A 0 A_JumpIfInventory("GotMeatShield", 1, "MeatShieldChecker");
		tnt1 A 0 A_JumpIfInventory("GoSpecial", 1, "SpecialChecker");
	Goto StandStill;
		
	SayOneLiner:
		MARN A 1;
		tnt1 A 0 A_PlaySound("ONELIN", 2);
		Goto StandStill;
		
	AdvancedTaunt:
		MARN A 1;
		tnt1 A 0 A_PlaySound("TAUNT0", 2);
		Goto StandStill;
		
	FistTaunt:
		tnt1 A 0;
		tnt1 A 0 A_PlaySound("MTAUN", 2);
		Goto StandStill;
		
		
	Roll_Right:
		PROL E 4
		{
			bNOPAIN = true;
			doomb_init_fatality_camera();//Start Camera//Start Camera
			
			Vel.X += 20 * Cos(angle - 90);
			Vel.Y += 20 * Sin(angle - 90);
		}
		PROL DCBA 4;
		MARN A 0 doomb_destroy_fatality_camera();//Disable Camera.
		MARN A 4;
		tnt1 A 0 {bNOPAIN = false;}
		TNT1 A 0 A_GiveInventory("ImpactMovesSling", 1);
	Goto StandStill;
		
	roll_left:
		PROL A 4
		{
			bNOPAIN = true;
			doomb_init_fatality_camera();//Start Camera//Start Camera
			Vel.X += 20 * Cos(angle + 90);
			Vel.Y += 20 * Sin(angle + 90);
		}
		PROL BCDE 4;
		MARN A 0 doomb_destroy_fatality_camera();//Disable Camera.
		MARN A 4;
		tnt1 A 0 {bNOPAIN = false;}
		TNT1 A 0 A_GiveInventory("ImpactMovesSling", 1);
	Goto StandStill;
		
		
	Pump:
		PLAY ABCD 4;
	Goto See;
	
	NoMovePump:
		PLAY B 12;
	Goto See;
		
	FistsStand:
		tnt1 A 0 A_JumpIfInventory("HasImpShield", 1, "SeeImpShield");
		tnt1 A 0 A_JumpIfInventory("HasZmanShield", 1, "SeeZmanShield");
		tnt1 A 0 A_JumpIfInventory("HasSguyShield", 1, "SeeSguyShield");
		tnt1 A 0 A_JumpIfInventory("HasBarrel", 1, "BarrelStand");
		MARN A 0 A_JumpIfInventory("GoFatality", 1, "FatalityChecker");
		MARN A 0 A_JumpIfInventory("GoSpecial", 1, "SpecialChecker");
		tnt1 A 0 doomb_destroy_fatality_camera();
		tnt1 A 0 A_JumpIf (vel.xy != (0, 0), "FistsMove");
		PLA1 B 5;
	Goto StandStill;
		
		
	FistsMove:
		tnt1 A 0 doomb_destroy_fatality_camera();
		tnt1 A 0 A_JumpIfInventory("GoFatality", 1, "FatalityChecker");
		tnt1 A 0 A_JumpIfInventory("GoSpecial", 1, "SpecialCheckerMoving");
		tnt1 A 0 A_JumpIfInventory("GotMeatShield", 1, "MeatShieldChecker");
		PLA1 ABCD 5;
		tnt1 A 0 A_JumpIf (vel.xy == (0, 0), "FistsMove");
	Goto See;
		
		
		
	ADSStand:
		MAR2 A 5;
		tnt1 A 0 A_JumpIf (vel.xy != (0, 0), "ADSMove");
		MAR2 A 0 doomb_destroy_fatality_camera();
		MAR2 A 5;
		MARN A 0 A_JumpIfInventory("GoFatality", 1, "FatalityChecker");
		MARN A 0 A_JumpIfInventory("GoSpecial", 1, "SpecialChecker");
		tnt1 A 0 A_JumpIf (vel.xy != (0, 0), "ADSMove");
		MAR2 D 5;
		tnt1 A 0 A_JumpIf (vel.xy != (0, 0), "ADSMove");
		MAR2 D 5;
		tnt1 A 0 A_JumpIf (vel.xy != (0, 0), "ADSMove");
	Goto StandStill;
		
	ADSMove:
		MAR2 A 5 A_JumpIfInventory("Kicking", 1, "Kick");
		MAR2 B 5 A_JumpIfInventory("Kicking", 1, "Kick");
		MARN A 0 A_JumpIfInventory("GoFatality", 1, "FatalityChecker");
		MARN A 0 A_JumpIfInventory("GoSpecial", 1, "SpecialChecker");
		MAR2 A 0 A_SpawnItemEx("FootstepStrong", 0, 0, 40, 0, 0);
		MAR2 C 5 A_JumpIfInventory("Kicking", 1, "Kick");
		MAR2 B 5 A_JumpIfInventory("Kicking", 1, "Kick");
		MAR2 A 0 A_SpawnItemEx("FootstepStrong", 0, 0, 40, 0, 0);
		tnt1 A 0 A_JumpIf (vel.xy != (0, 0), "spawn");
	Goto See;
		
		
	BarrelMove:
		tnt1 A 0 A_JumpIf (vel.xy == (0, 0), "BarrelStand");
		PBAR AB 8;
		tnt1 A 0 A_SpawnItemEx("FootstepStrong", 0, 0, 40, 0, 0);
		PBAR CB 8;
	Goto See;
		
	BarrelStand:
		PBAR A 1;
		tnt1 A 0 A_JumpIf (vel.xy != (0, 0), "BarrelMove");
	Goto StandStill;
		
		
		
	Death:

		tnt1 A 0 A_Jump (160, 3);
		Goto Death.Arm;
		tnt1 AAA 0;
		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		tnt1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		PLAY H 10;
		PLAY I 10 A_PlayerScream;
		PLAY J 10 A_NoBlocking;
		PLAY KLM 10;
		tnt1 A 0 doomb_spawn_bloodpool();
		PLAY N -1;
		Stop;




	// This section is responsable for calling scripts to make blood
	// drip on the screen when the player is affected by one of the actors
	// in the BLOODSPLASH lump.
	
Pain.Blood:
	tnt1 A 0 A_Giveinventory("BloodOnVisor",1);
	tnt1 A 0 A_GiveInventory("MeatAmmo", 1);
	tnt1 A 0 ACS_Execute(random(580, 585), 0, 0, 0, 0);
Goto StandStill;

Pain.BlueBlood:
	//tnt1 A 0 A_Giveinventory("BlueBloodOnVisor",1);
	tnt1 A 0 A_Giveinventory("health",1);
	tnt1 A 0 ACS_Execute(random(570, 575), 0, 0, 0, 0);
Goto StandStill;
	
Pain.GreenBlood:
	//tnt1 A 0 A_Giveinventory("GreenBloodOnVisor",1);
	tnt1 A 0 A_Giveinventory("health",1);
	tnt1 A 0 ACS_Execute(random(560, 565), 0, 0, 0, 0);
Goto StandStill;
	
	Pain:
		tnt1 A 0 A_setblend("70, 00, 00", 0.2, 34);
		tnt1 A 0 A_Pain;
		MARN A 0 {if(self && self.player && self.player.readyweapon && self.player.readyweapon.getclassname() == "Melee_Attacks") setstatelabel("FistsStand");}
		TNT1 A 0 A_GiveInventory("ImpactMovesSling", 1);
		tnt1 A 0 A_PlaySound("PAIN1", 2);
		PLAY G 5;
		Goto See;
		
	PainWfist:
		tnt1 A 0 A_JumpIfInventory("HasImpShield", 1, "SeeImpShield");
		tnt1 A 0 A_JumpIfInventory("HasZmanShield", 1, "SeeZmanShield");
		tnt1 A 0 A_JumpIfInventory("HasSguyShield", 1, "SeeSguyShield");
		PLA1 G 5;
		tnt1 A 0 A_PlaySound("PAIN1", 2);
	Goto StandStill;
		
		
	Pain.Blast:
	Pain.Explosive_Impact:
		tnt1 A 0 A_PlaySound("PAIN1", 2);
		tnt1 A 0 ACS_Execute(531, 0, 0, 0, 0);
		TNT1 A 0 ThrustThingZ(0, 20, 1, 0);
		Goto Pain;
		
		
	Pain.Bullet:
	Pain.MonsterMinigunBullet:
	Pain.Shotgun:
	Pain.SSG:
	Pain.CutLess:
		//Scripts 611 to 616 are responsible for making the bullet damage effect on screen
		tnt1 A 0 A_PlaySound("PAIN1", 2);
		tnt1 A 0 ACS_Execute(random(611, 616), 0, 0, 0, 0);
	Goto Pain;
		
		
		
	Pain.ImpFatalityMarine:
	Pain.Rip:
		tnt1 A 0 A_PlaySound("PAIN1", 2);
		tnt1 A 0 ACS_Execute(530, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(617, 0, 0, 0, 0);
	Goto Pain;




	Death.Eat:
		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		tnt1 A 0 A_GiveToTarget("EatMe",1);
		tnt1 A 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL1 A 10 A_XScream;
		XPL1 B 20 A_NoBlocking;
		XPL1 CDE 10;
		tnt1 A 0 doomb_spawn_bloodpool();
		PPOD A 0 A_SpawnItemEx("MarineEattenByDemon", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		tnt1 A -1;
	Stop;
		
	Death.Cut:
	Death.Saw:
		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		tnt1 A 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("RipGuts", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 A 10 A_XScream;
		tnt1 AA 0 doomb_spawn_big_blood(50);
		XPL2 B 20 A_NoBlocking;
		tnt1 AA 0 doomb_spawn_big_blood(50);
		XPL2 C 10 doomb_spawn_big_blood (40);
		tnt1 AA 0 doomb_spawn_big_blood(30);
		XPL2 DE 10 doomb_spawn_big_blood(20);
		tnt1 A 0 doomb_spawn_bloodpool();
		XPL2 E -1;
		Stop;
		
	Death.Slime:
		tnt1 A 0 A_PlaySound("BIGSCREA");
		tnt1 A 0 A_Takeinventory("Kicking",1);
		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		PMET AABBCCDDEEFFGGHHIIIII 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		PMET IIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLLLLLLLLL 3 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		tnt1 A 0 A_NoBlocking;
		tnt1 A -1;
		Stop;
		
	Death.CutLess:
		tnt1 A 0 A_Takeinventory("Kicking",1);
		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		tnt1 A 0 A_Scream;
		tnt1 A 0 A_Stop;
		tnt1 A 0 A_GiveInventory("ChainguyguyContinue", 1);
		tnt1 A 0 A_PlaySound("DSFDTHE");
		PLAY H 5;
		tnt1 A 0 A_GiveInventory("ChainguyguyContinue", 1);
		PPOD A 0 A_SpawnItemEx("PlayerChaingunguyVictim", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		tnt1 A 200;
		tnt1 A 0 A_NoBlocking;
		tnt1 A 0 A_TakeInventory("ChainguyguyContinue", 1);
		tnt1 A -1;
	Stop;
		
	Death.Rip:
		tnt1 A 0 A_Takeinventory("Kicking",1);

		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		tnt1 AAAAAAAAAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 A 10 A_XScream;
		tnt1 AAAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 B 20 A_NoBlocking;
		XPL3 C 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 D 10 A_SpawnProjectile ("MuchBlood", 40, 0, random (0, 360), 2, random (0, 160));
		XPL3 E 10 A_SpawnProjectile ("MuchBlood", 30, 0, random (0, 360), 2, random (0, 160));
		XPL3 F 10 A_SpawnProjectile ("MuchBlood", 20, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("MuchBlood", 10, 0, random (0, 360), 2, random (0, 160));
		XPL3 F 10 A_SpawnProjectile ("MuchBlood", 0, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 doomb_spawn_bloodpool();
		XPL3 F -1;
		Stop;
		
	XDeath:
		tnt1 A 0 A_Takeinventory("Kicking",1);

		tnt1 A 0 ThrustThingZ(0,60,0,1);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		tnt1 A 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);//ACS 580 to 585 is the blood driping on screen
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(584, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(585, 0, 0, 0, 0);
		MHEA A 0 A_XScream;
		MHEA B 0 A_NoBlocking;
		MHEA CD 0;
		//MHEA E -1
		tnt1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 90));
		tnt1 a 0 doomb_spawn_bloodpool();
		tnt1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		XDMG E 1;
		tnt1 AAAAAAAAAAAAAAA 0 A_SpawnProjectile ("WallRedBlood", 40, 0, random (0, 360), 2, random (-5, 5));
		tnt1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		XDMG E -1;
		Stop;
		
	Death.punch:
	Death.Blast:
	Death.SSG:
		tnt1 A 0 A_Takeinventory("Kicking",1);
		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		POSS Q 2 A_FaceTarget;
		tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		tnt1 AAAA 0 A_SpawnProjectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		tnt1 AAAA 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		tnt1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		tnt1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		tnt1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		tnt1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		tnt1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		tnt1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
		tnt1 AAAA 0 A_SpawnProjectile ("SuperGoreSpawner", 22, 0, random (170, 190), 2, random (0, 15));
		XPL2 A 10 A_XScream;
		tnt1 AA 0 doomb_spawn_big_blood (50);
		XPL2 B 20 A_NoBlocking;
		tnt1 AA 0 doomb_spawn_big_blood(50);
		XPL2 C 10 doomb_spawn_big_blood(40);
		tnt1 AA 0 doomb_spawn_big_blood( 30);
		XPL2 DE 10 doomb_spawn_big_blood( 20);
		tnt1 A 0 doomb_spawn_bloodpool();
		XPL2 E -1;
		Stop;
		
	Death.Rape:
		tnt1 A 0 A_Takeinventory("Kicking",1);

		tnt1 A 0 A_Jump (160, 3);
		Goto Death.Arm;
		tnt1 AAA 0;
		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		tnt1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 A 20 A_XScream;
		tnt1 A 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
		tnt1 AAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 B 20 A_NoBlocking;
		tnt1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 C 20;
		tnt1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 D 20;
		tnt1 AAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 E 20;
		tnt1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 F 20;
		tnt1 AAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 doomb_spawn_bloodpool();
		XPL4 F -1;
		Stop;
		
		
	Death.Arm:
		tnt1 A 0 A_Takeinventory("Kicking",1);

		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		tnt1 AA 0 A_SpawnProjectile ("XDeath1", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeathArm1", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_Scream;
		XPL5 A 10;
		tnt1 A 0 A_NoBlocking;
		tnt1 A 0 A_PlaySound("DSFDTHE");
		XPL5 BCBCBCBC 10 A_SpawnProjectile ("MuchBlood", 25, 0, random (0, 360), 2, random (0, 160));
		XPL5 DE 7 A_SpawnProjectile ("MuchBlood", 15, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 doomb_spawn_bloodpool();
		XPL5 E -1;
		Stop;
		
		
	Death.punch:
	Death.Explosive_Impact:
		tnt1 A 0 A_Takeinventory("Kicking",1);

		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		tnt1 A 0 ThrustThingZ(0,30,0,1);
		tnt1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (0, 40));
		tnt1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		tnt1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_XScream;
		XPL6 A 5;
		tnt1 A 0 A_NoBlocking;
		XPL6 BCDE 5;
		XPL6 F -1;
		Stop;
		
	
Death.Plasma: Death.Plasma2:
	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	PBR1 A 6 A_Scream;
	tnt1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
	tnt1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
	tnt1 AAAA 0 doomb_show_effect("BluePlasmaFire", (0, 0, 32), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
	PBR1 B 6 A_NoBlocking;
	PBR1 CDEFGH 6 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
	PBR1 HHHHHHHHHHHHHHHHHHHHHH 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
	PBR1 H -1;
	Stop;
	
Death.Fire:
	tnt1 a 0 a_jump(128,"fire_death_1");
	tnt1 A 0 A_Takeinventory("Kicking",1);
	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	PBUR A 1;
	PBUR A 1 A_PlayerScream;
	PBUR A 1 A_NoBlocking;
	PBUR AAAABBBBCCCCDDDDEEEEEEEEE 2 doomb_show_effect("FlameTrails", ( 0, 0, 32 - 3 * frame), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );

	PBUR EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 6 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
	PBUR E -1;
	Stop;
	
fire_death_1:

	tnt1 A 0 A_Takeinventory("Kicking",1);
	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	tnt1 A 0 A_Scream;
	tnt1 A 0 A_NoBlocking;
	TNT1 A 0 A_PlaySound("DSFDTHE");
	BUR2 A 1 BRIGHT;
	BUR2 AABBCCDDEEFFGGHHIIJJKKLLMMNNOOPPQQ 3 BRIGHT light("BIGREDTORCH")
	{
		A_Explode(3,30, damagetype:"fire");
		{Spawn("RedFlare", pos);}
		doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
	}
	TNT1 A 0 A_PlaySound("DSFDTHE");
	BURN RRSSTTSSRRSSTTSSRRSSTTRRSSTTSSRRSSTTSSRRSSTTSSTTUU 3 BRIGHT light("BIGREDTORCH")
	{
			A_Explode(3,30, damagetype:"fire");
			{Spawn("RedFlare", pos);}
			doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
	}
	TNT1 A 0 A_SpawnItemEx("BarrelExplosionSmokeColumn",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
	BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 9 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
	BURN V -1;
Stop;

Death.Desintegrate:

	tnt1 A 0 A_Takeinventory("Kicking",1);
	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	TNT1 A 0 A_XScream;
	TNT1 A 0 A_NoBlocking;
	TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodFake", 30, 0, random (0, 360), 2, random (0, 90));
	TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 37, 0, random (0, 360), 2, random (10, 50));
	TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 37, 0, random (0, 360), 2, random (40, 60));
	TNT1 AAA 0 A_SpawnProjectile ("BloodmistSmall", 37, 0, random (0, 360), 2, random (30, 90));
	TNT1 AA 0 A_SpawnProjectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 90));
	TNT1 AAA 0 A_SpawnProjectile ("XDeath2", 30, 0, random (0, 360), 2, random (0, 90));
	TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 30, 0, random (0, 360), 2, random (0, 90));
	TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 doomb_spawn_bloodpool();
	TNT1 A 0 A_SpawnProjectile ("SuperGoreSpawner", 30, 0, random (0, 360), 2, random (10, 90));
	ID50 ABCDEF 7;
	ID50 GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG 13 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
	ID50 G -1;
	Stop;
	
	Death.Stomp:
		tnt1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		tnt1 AAAAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
		tnt1 AA 0 bright A_SpawnProjectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
		tnt1 AA 0 bright A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
		tnt1 A 0 A_SpawnItem ("CrushedRemains");
		tnt1 A 1;
		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		tnt1 A 1 A_XScream;
		tnt1 A 1 A_NoBlocking;
		tnt1 A -1;
	Stop;
	
	Crush:
		tnt1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 A 5;
		CRS1 A -1;
	Stop;
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	// FATALITIES
	
	
	
	
FatalityZMan:

	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	FTYZ AB 4;
	
	tnt1 A 0  A_PlaySound("grunt/pain");
	FTYZ BC 3;
	FTYZ DEF 3;
	tnt1 A 0 A_PlaySound("BURNZOM", 3);
	
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	FTYZ FG 2;
	tnt1 A 0 A_PlaySound ("misc/xdeath", 1);
	FTYZ FG 2;
	tnt1 A 0 A_PlaySound ("misc/xdeath", 1);
	FTYZ F 2;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	FTYZ H 4;
	tnt1 AA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	FTYZ I 4;
	tnt1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_PlaySound ("misc/xdeath", 3);
	
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 AAAAAAAAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 50, 0, random (0, 360), 2, random (50, 130));
	tnt1 A 0 A_SpawnProjectile ("XDeathHalfZombieMan", 60, 0, 270, 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("XDeathHalfZombieManDown", 60, 0, 90, 2, random (0, 160));
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath2", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath3", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAA 0 A_SpawnProjectile ("Instestin", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 60, 0, random (0, 360), 2, random (0, 160));
	FTYZ K 2;
	FTYZ L 15
	{
		A_TakeInventory("ZombieManFatality",1);
		A_TakeInventory("GoFatality", 1);
		A_GiveInventory("HealthBonus",10);
		doomb_destroy_fatality_camera();//Stop Camera
		SetPlayerProperty(0,0,0);
	}
	Goto StandStill;
	
	
FatalityZMan2:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	FPZ2 AB 4;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 50, 0, random (0, 360), 2, random (50, 130));
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("XDeath2", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("XDeath3", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 60, 0, random (0, 360), 2, random (0, 160));
	FPZ2 C 10;
	tnt1 A 0 A_PlaySound("imp/melee");
	FPZ2 D 10;
	tnt1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	FPZ2 EF 3;
	tnt1 A 0 A_PlaySound("grunt/death");
	FPZ2 G 6
	{
		A_TakeInventory("ZombieManFatality2",1);
		A_TakeInventory("GoFatality", 1);
		A_GiveInventory("HealthBonus",10);
		A_SpawnItem ("ZombieManDyingAfterFatality");
		A_SpawnProjectile ("Instestin", 30, 0, 0, 2, 0);
		doomb_destroy_fatality_camera();//Stop Camera
		SetPlayerProperty(0,0,0);
	}
	Goto StandStill;
	
	
FatalityZMan3:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	FPZ3 A 6;
	FPZ3 BCDE 3;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	FPZ3 FGGGG 2;
	
	FPZ3 HHHIIIIIIIIHJJJ 1;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 AA 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("BloodMistSmall", 5, 0, random (0, 360), 2, random (40, 90));
	TNT1 A 0 doomb_spawn_bloodpool();
	
	FPZ3 KKKLLLLLLKJJJ 1;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 AA 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("BloodMistSmall", 5, 0, random (0, 360), 2, random (40, 90));
	
	
	FPZ3 MMMNNNNNNNMOOO 1;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 AA 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("BloodMistSmall", 5, 0, random (0, 360), 2, random (40, 90));
	FPZ3 MMMNNNNNNNMOOO 1;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 AA 0 A_SpawnProjectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("BloodMist", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAA 0 A_SpawnProjectile ("Brains1", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("jaw", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("eye", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("head_piece", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("head_piece", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("head_piece", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 5, 0, random (0, 360), 2, random (0, 160));
	
	
	FPZ3 PPPQQQQQQQPRRR 1;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("BloodMistSmall", 5, 0, random (0, 360), 2, random (40, 90));
	
	FPZ3 PPPQQQQQQPRRR 1;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("BloodMistSmall", 5, 0, random (0, 360), 2, random (40, 90));
	FPZ3 RP 3
	{
		A_TakeInventory("GoFatality", 1);
		A_TakeInventory("ZombieManFatality3",1);
		A_GiveInventory("HealthBonus",10);
		A_SpawnItem ("zombie_fatalized_body");
		doomb_destroy_fatality_camera();//Stop Camera
		SetPlayerProperty(0,0,0);
	}
	Goto StandStill;
	
	
FatalityZMan4:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	FPZ4 AB 2;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	FPZ4 CDEEE 3;
	FPZ4 FGH 2;
	
	FPZ4 HHI 2;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("BloodmistSmall", 5, 0, random (0, 360), 2, random (0, 90));
	tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 doomb_spawn_bloodpool();
	FPZ4 JJJIH 2;
	
	FPZ4 HHI 2;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("BloodmistSmall", 5, 0, random (0, 360), 2, random (0, 90));
	tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
	FPZ4 JJJIH 2;
	
	FPZ4 HHI 2;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("BloodmistSmall", 5, 0, random (0, 360), 2, random (0, 90));
	tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
	FPZ4 OOOMN 2;
	
	
	FPZ4 NNM 2;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("BloodmistSmall", 5, 0, random (0, 360), 2, random (0, 90));
	tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
	FPZ4 OOOMN 2;
	
	FPZ4 NNM 2;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("BloodmistSmall", 5, 0, random (0, 360), 2, random (0, 90));
	tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
	FPZ4 OOOMN 2;
	
	
	
	FPZ4 NNM 2;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("Bloodmist", 5, 0, random (0, 360), 2, random (0, 90));
	
	tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAA 0 A_SpawnProjectile ("Brains1", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("jaw", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("eye", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("head_piece", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("head_piece", 5, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("head_piece", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 doomb_spawn_bloodpool();
	tnt1 AAAAAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 5, 0, random (0, 360), 2, random (0, 160));
	FPZ4 P 7;
	FPZ4 L 6
	{
		A_TakeInventory("GoFatality", 1);
		A_TakeInventory("ZombieManFatality4",1);
		A_GiveInventory("HealthBonus",10);
		A_SpawnItem ("zombie_fatalized_body");
		doomb_destroy_fatality_camera();//Stop Camera
		SetPlayerProperty(0,0,0);
	}
	Goto StandStill;
	
FatalityImp:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	FTYI ABB 4;
	FTYI CDEFG 2;
	tnt1 A 0  A_PlaySound("imp/pain");
	tnt1 A 0 A_SpawnItemEx("FootStep", 0, 0, 40, 0, 0);
	tnt1 A 0 A_PlaySound("CLAP");
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	FTYI GGGGHHHHHHHHIIJJJJJJJJJJJ 1;
	FTYI K 3;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 A 0 A_SpawnItemEx("FootStep", 0, 25, 30, 0, 0);
	TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
	TNT1 A 0 doomb_spawn_bloodpool();
	FTYI LLLL 1;
	FTYI LMNNN 3;
	FTYI N 9
	{
		A_TakeInventory("GoFatality", 1);
		A_TakeInventory("ImpFatality",1);
		A_GiveInventory("HealthBonus",10);
		A_SpawnProjectile ("StompedImp", 1, 0, random (0, 360), 2, random (0, 160));
		doomb_destroy_fatality_camera();//Stop Camera
		SetPlayerProperty(0,0,0);
	}
	Goto StandStill;
	
	
FatalityImp2:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 50, 0, random (0, 360), 2, random (50, 130));
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath2", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath3", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 60, 0, random (0, 360), 2, random (0, 160));
	FTBI BC 2;
	tnt1 A 0  A_PlaySound("imp/die");
	FTBI D 25;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 50, 0, random (0, 360), 2, random (50, 130));
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath2", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath3", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 60, 0, random (0, 360), 2, random (0, 160));
	FTBI EF 3;
	FTBI G 25;
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_TakeInventory("ImpFatality2",1);
	tnt1 A 0 A_GiveInventory("HealthBonus",10);
	tnt1 A 0 A_SpawnItem ("ImpMessyCorpse");
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

	Goto StandStill;
	
	
FatalityImp3:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	FTCI AB 2;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	FTCI CDE 2;
	FTCI E 6;
	
	FTCI FGG 4;
	FTCI H 2;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 A_SpawnProjectile ("BloodMistSmall", 2, 0, random (0, 360), 2, random (20, 90));
	tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
	FTCI I 5;
	FTCI H 2;
	FTCI G 3;

	FTCI H 2;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 A_SpawnProjectile ("BloodMistSmall", 2, 0, random (0, 360), 2, random (20, 90));
	tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
	FTCI I 5;
	FTCI H 2;
	FTCI G 3;
	
	FTCI H 2;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	TNT1 A 0 doomb_spawn_bloodpool();
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 A_SpawnProjectile ("BloodMistSmall", 2, 0, random (0, 360), 2, random (20, 90));
	tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
	FTCI I 5;
	FTCI H 2;
	FTCI G 3;
	
	FTCI H 2;
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 A_SpawnProjectile ("BloodMistSmall", 2, 0, random (0, 360), 2, random (20, 90));
	tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
	FTCI I 5;
	FTCI H 2;
	FTCI G 3;
	
	FTCI H 2;
	
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 A_PlaySound("grunt/pain", 1);
	tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
	TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
	FTCI L 10;
	FTCI J 10;
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_TakeInventory("ImpFatality3",1);
	tnt1 A 0 A_GiveInventory("HealthBonus",10);
	tnt1 A 0 A_SpawnItem ("impfacesorapedomgthisiscruel");
	//tnt1 A 0 A_SpawnItem ("ZombieManDyingAfterFatality")
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

	Goto StandStill;
	
	
FatalitySergeant:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	FTYS A 6 A_PlaySound("grunt/pain");
	FTYS BC 6;
	tnt1 A 0 A_PlaySound("BURNZOM", 3);
	
	tnt1 A 0 A_PlaySound("misc/xdeath");
	FTYS DE 4;
	tnt1 A 0 A_PlaySound("misc/xdeath");
	FTYS DE 3;
	tnt1 A 0 A_PlaySound("misc/xdeath");
	FTYS DEE 2;
	
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 A_PlaySound("misc/xdeath", 3);
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 20, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAA 0 A_SpawnProjectile ("BloodMist", 30, 0, random (0, 360), 2, random (20, 90));
	FTYS FGHIIPPP 2 A_SpawnProjectile ("Blood", 1, 0, random (0, 360), 2, random (0, 160));
	
	FTYS QR 5;
	tnt1 A 0 A_SpawnItemEx("FootStep", 0, 0, 40, 0, 0);
	FTYS R 15
	{
		A_GiveInventory("ShotgunguyHead", 1);
		A_TakeInventory("GoFatality", 1);
		A_TakeInventory("SergeantFatality",1);
		A_GiveInventory("HealthBonus",10);
		A_SpawnProjectile ("DeadShotgunGuy_NoHead", 1, 0, random (0, 360), 2, random (0, 160));
		doomb_destroy_fatality_camera();//Stop Camera
		SetPlayerProperty(0,0,0);
	}
	Goto StandStill;
	
FatalitySergeant2:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();

	FTYS J 3;
	FTYS J 1 A_PlaySound("BURNZOM");
	FTYS JJJJ 3;
	FTYS J 1 A_PlaySound("grunt/death");
	FTYS K 4;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 20, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("XDeath2", 20, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("XDeath3", 20, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("BloodMist", 50, 0, random (0, 360), 2, random (20, 90));
	
	tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
	TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathHalfSergeant", 32, 0, random (0, 360), 2, random (0, 160));
	
	FTYS LMNO 3;
	FTYS O 10;
	///////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_TakeInventory("SergeantFatality2",1);
	tnt1 A 0 A_GiveInventory("HealthBonus",10);
	tnt1 A 0 doomb_spawn_bloodpool();
	tnt1 A 0 A_SpawnItem ("DeadShotgunguy_Half", 1);
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

	Goto StandStill;
	
	
FatalitySergeant3:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	FSP3 A 4;
	
	FSP3 B 4 A_PlaySound("grunt/pain");
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	FSP3 CDE 2;
	FSP3 E 6;
	
	FSP3 FG 3;
	tnt1 A 0 A_PlaySound("grunt/death");
	TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 20, 0, random (0, 360), 2, random (0, 160));
	//tnt1 AA 0 A_SpawnProjectile ("XDeath2", 20, 0, random (0, 360), 2, random (0, 160))
	//tnt1 AA 0 A_SpawnProjectile ("XDeath3", 20, 0, random (0, 360), 2, random (0, 160))
	TNT1 AAA 0 A_SpawnProjectile ("BloodMistSmall", 30, 0, random (0, 360), 2, random (20, 90));
	
	FSP3 HIIIIII 3;
	
	tnt1 A 0 A_PlaySound("weapons/sg");
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 AAAAA 0 A_SpawnProjectile ("XDeath1", 70, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("XDeath2", 70, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("XDeath3", 70, 0, random (0, 360), 2, random (0, 160));
	
	TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("BloodMist", 80, 0, random (0, 360), 2, random (20, 90));
	tnt1 A 0 A_SpawnProjectile ("FlyingImpaledSergeant", 50, 0, random (0, 360), 2, random (70, 110));
	
	
	FSP3 L 3 BRIGHT;
	FSP3 K 3;
	FSP3 J 10;
	///////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_TakeInventory("SergeantFatality3",1);
	tnt1 A 0 A_GiveInventory("HealthBonus",10);
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

	Goto StandStill;
	
	

	


	

	
	

	
	
FatalityRevenant:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	FREV ABABAB 3;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	FREV C 4 A_PlaySound("skeleton/pain");
	FREV D 4;
	FREV EFGHIJJJKL 4;
	FREV M 5 A_PlaySound("skeleton/sight");
	FREV M 10;
	FREV N 2;
	FREV O 2;
	
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 AA 0 A_SpawnProjectile ("XDeath1", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath2", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath3", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("XDeathRevenantHeadKicked2", 40, 0, 0, 2, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	
	FREV PQR 2;
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_TakeInventory("RevenantFatality",1);
	tnt1 A 0 A_GiveInventory("HealthBonus",15);
	tnt1 A 0 A_SpawnItemEx("DyingRevenant", 0, 35, 35, 1, 1);
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

Goto StandStill;
	
	
FatalityRevenant2:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	FRE2 A 5;
	FRE2 A 5 A_PlaySound("skeleton/pain");
	FRE2 A 5;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("XDeath2", 40, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	FRE2 BCDEFGGGGG 6;
	
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_TakeInventory("RevenantFatality2",1);
	tnt1 A 0 A_GiveInventory("HealthBonus",15);
	tnt1 A 0 A_SpawnItem("VeryFuckedUpRevenant");
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

Goto StandStill;
	
	
FatalityFatso:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	FATF A 6;
	tnt1 A 0 ACS_Execute(585, 0, 0, 0, 0);
	tnt1 A 0 A_SpawnProjectile ("Blood", 45, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 45 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	FATF A 6 A_PlaySound("misc/xdeath4");
	tnt1 A 0 A_SpawnProjectile ("Blood", 45, 0, random (0, 360), 2, random (0, 160));
	FATF A 6 A_PlaySound("fatso/pain");
	FATF AA 6 A_SpawnProjectile ("Blood", 45, 0, random (0, 360), 2, random (0, 160));
	
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 A_SpawnProjectile ("XDeath1", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("XDeath2", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("XDeath3", 50, 0, random (0, 360), 2, random (0, 160));
	FATF BCD 8;
	tnt1 A 0 A_PlaySound("fatso/pain");
	FATF D 50;
	
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_TakeInventory("FatsoFatality",1);
	tnt1 A 0 A_GiveInventory("HealthBonus",15);
	tnt1 A 0 A_SpawnItemEx("FatalizedFatso", 0, 1, 1, 1, 1);
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

Goto StandStill;
	
	

	
	
	
	
	
FatalityHK:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	HKF1 A 1;
	HKF1 AB 6;
	tnt1 A 0 A_PlaySound("misc/xdeath4");
	HKF1 C 6 A_PlaySound("PSXDPN");
	tnt1 AAA 0 A_SpawnProjectile ("Blood", 45, 0, random (0, 360), 2, random (0, 160));
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	HKF1 C 5;
	tnt1 A 0 A_PlaySound("imp/melee");
	HKF1 C 5;
	tnt1 AAAAAAA 0 A_SpawnProjectile ("Blood", 55, 0, random (0, 180), 2, random (0, 180));
	
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
	tnt1 AAAAAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAA 0 A_SpawnProjectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAA 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	
	
	HKF1 CDE 6 A_SpawnItem ("Brutal_Blood", 30);
	HKF1 FG 6 A_SpawnItem ("Brutal_Blood", 15);
	HKF1 HHH 6;
	
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_TakeInventory("HKFatality",1);
	tnt1 A 0 A_GiveInventory("HealthBonus",10);
	tnt1 A 0 A_SpawnItemEx("RapedHK", 0, 1, 1, 1, 1);
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

Goto StandStill;
	
	
	
FatalityHK3:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	tnt1 A 0 A_PlaySound("weapons/gswing", 1);
	tnt1 A 0 A_PlaySound("PSXDPN");
	HKF3 A 1;
	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	HKF3 ABC 6;
	tnt1 A 0 doomb_init_fatality_camera();//Start Camera

	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 A_PlaySound("PSXDPN", 2);
	HKF3 D 15;
	tnt1 A 0 A_PlaySound("knight/death");
	
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 AAAAAAA 0 A_SpawnProjectile ("XDeath1", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("Blood", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("XDeathHellKnightArm", 40, 0, 90, 2, random (0, 20));
	HKF3 EFGG 7 A_SpawnProjectile ("Blood", 40, 0, random (0, 360), 2, random (0, 160));
	
	tnt1 A 0 A_PlaySound("PSXDPN");
	HKF3 H 15;
	
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	
	tnt1 AAAAAAA 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("Blood", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 60, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_SpawnProjectile ("XDeathHellKnightHead", 40, 0, 270, 2, random (0, 20));
	HKF3 I 20;
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("HKFatality3",1);
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_GiveInventory("HealthBonus",10);
	tnt1 A 0 A_SpawnItemEx("NoArmNoHeadFatalizedHK", 0, 1, 1, 1, 1);
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

Goto StandStill;
	
	
FatalityHK2:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	HKF2 AAB 6;
	tnt1 A 0 doomb_init_fatality_camera();//Start Camera

	tnt1 A 0 A_PlaySound("PSXDPN");
	
	HKF2 DEFFGH 8;
	
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 A_PlaySound("PSXDPN");
	HKF2 IJIJIJ 4;
	
	
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	
	tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
	tnt1 AAAAAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AA 0 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	
	
	HKF2 KL 6;
	tnt1 A 0 A_SpawnProjectile ("XDeathHellKnightHead", 64, 0, random (0, 360), 2, random (60, 120));
	HKF2 MNNNNN 6;
	
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("HKFatality2",1);
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_GiveInventory("HealthBonus",10);
	tnt1 A 0 A_SpawnItemEx("OmgSoDeadHK", 0, 1, 1, 1, 1);
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

Goto StandStill;
	
	
	
FatalityArachnotron:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	ARF1 ABABABABABABAB 2;
	tnt1 A 0 A_SpawnItem("Spark_UpOnce",0,60);
	ARF1 CD 3;
	tnt1 A 0 A_PlaySound("baby/death");
	ARF1 EFFFF 3;
	ARF1 GGHHI 3;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 AAAAA 0 A_SpawnProjectile ("Instestin", 14, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
	tnt1 AAAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAA 0 A_SpawnProjectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAA 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	ARF1 JKLMNNNNNNNNNNNNNNNN 3;
	
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("ArachnotronFatality",1);
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_GiveInventory("HealthBonus",20);
	tnt1 A 0 A_SpawnItemEx("RapedArachnotron", 0, 1, 1, 1, 1);
	//tnt1 A 0 A_SpawnProjectile ("SpiderLeg", 30, 0, 0, 2, 0)
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

Goto StandStill;
	
	
FatalityArachnotron2:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	ARF2 A 6;
	tnt1 A 0 A_PlaySound("grunt/pain");
	ARF2 B 3;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	ARF2 BIBIBI 2;
	tnt1 A 0 A_PlaySound("baby/death");
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	tnt1 AAAAA 0 A_SpawnProjectile ("Instestin", 14, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
	tnt1 AAAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAA 0 A_SpawnProjectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAAAAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	
	ARF2 CDE 3;
	tnt1 A 0 A_SpawnProjectile ("XDeathArachnotronHead", 50, 0, random (0, 360), 2, random (40, 130));
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("ArachnotronFatality2",1);
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_GiveInventory("HealthBonus",20);
	tnt1 A 0 A_SpawnItemEx("NoLegsSpider", 0, 1, 1, 1, 1);
	//tnt1 A 0 A_SpawnProjectile ("SpiderLeg", 30, 0, 0, 2, 0)
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

Goto StandStill;
	
	
	

	
	
FatalityPE:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	PA1F A 3;
	FATF E 0 A_PlaySound("demon/pain");
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	PA1F A 9;
	
	tnt1 A 0 ACS_Execute(585, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	
	tnt1 AAAAAA 0 A_SpawnProjectile ("Blood", 55, 0, random (0, 180), 2, random (0, 180));
	tnt1 AA 0 A_SpawnProjectile ("XDeath1", 55, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_PlaySound("demon/pain");
	
	PA1F BCDEEEEEFGHI 3;
	
	tnt1 A 0 A_PlaySound("demon/pain");
	
	PA1F JKKKKL 3;
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("MuchBlood", 90, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 ACS_Execute(585, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	
	PA1F MNNNNNNNOPQR 3;
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("MuchBlood", 90, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 ACS_Execute(585, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	
	PA1F RQPQR 3;
	
	
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("MuchBlood", 90, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 ACS_Execute(585, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	
	PA1F RQPQR 3;
	
	
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("MuchBlood", 90, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 ACS_Execute(585, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	
	PA1F RQPQR 3;
	
	
	tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("XDeath2", 10, 0, random (0, 360), 2, random (0, 160));
	tnt1 AAA 0 A_SpawnProjectile ("MuchBlood", 90, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 ACS_Execute(585, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	
	
	PA1F S 30;
	PA1F STSTST 6 A_SpawnProjectile ("MuchBlood", 30, 0, random (0, 360), 2, random (0, 160));
	PA1F S 9;
	
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("PEFatality",1);
	tnt1 A 0 A_GiveInventory("HealthBonus",15);
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	tnt1 A 0 A_SpawnItemEx("FatalizedPE", 0, 1, 1, 1, 1);
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

Goto StandStill;


CurbstompZombieman:

	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 doomb_init_fatality_camera();
	//////////////////////////////////////////////////////
	01CB A 3;

	tnt1 A 0 A_PlaySound("grunt/death");
	01CB BCCCC 3 SetPlayerProperty(0,1,0);
	tnt1 A 0 A_PlaySound("misc/xdeath1");
	01CB D 3;
	XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
	tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
	tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
	//spawn height +20
	TNT1 A 0;
	TNT1 A 0 A_PlaySound("misc/xdeath4");
	TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
	TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
	TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
	TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
	
		TNT1 A 0 doomb_spawn_bloodpool();
	01CB E 20;
	//////////////////////////////////////////////////////
	tnt1 A 0 A_TakeInventory("IsCurbstompingZombieman",1);
	tnt1 A 0 A_GiveInventory("HealthBonus",10);
	tnt1 A 0 A_SpawnProjectile ("StompedZombieman", 1, 0, random (0, 360), 2, random (0, 160));
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	MARN A 0 doomb_destroy_fatality_camera();//Stop Camera

Goto StandStill;
	
	
	
	CurbstompSergeant:
		tnt1 A 0 doomb_init_fatality_camera();
		//////////////////////////////////////////////////////
		02CB A 3;

		tnt1 A 0 A_PlaySound("grunt/death");
		02CB BCCCC 3;
		tnt1 A 0 A_PlaySound("misc/xdeath1");
		02CB D 3;
		XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		TNT1 A 0 A_SpawnItemEx("ShotgunguyHeadExplode", 0, 20);
		TNT1 A 0 doomb_spawn_bloodpool();
		02CB E 20;
		//////////////////////////////////////////////////////
		tnt1 A 0 A_TakeInventory("IsCurbstompingSergeant",1);
		tnt1 A 0 A_TakeInventory("GoFatality", 1);
		tnt1 A 0 A_GiveInventory("HealthBonus",5);
		tnt1 A 0 A_SpawnProjectile ("StompedSergeant", 1, 0, random (0, 360), 2, random (0, 160));
		MARN A 0 doomb_destroy_fatality_camera();//Stop Camera
	Goto StandStill;
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	Death.Fatality:
		tnt1 A 0 A_NoBlocking;
		tnt1 A 0 A_Scream;
		tnt1 A 0 A_GiveToTarget("GoFatality", 1);
		tnt1 A 0 A_GiveToTarget("PVPFatality", 1);
		tnt1 A -1;
	Stop;

	FatalityPVP:
	
		tnt1 A 0 doomb_init_fatality_camera();//Start Camera
		//////////////////////////////////////////////////////
		PVPF ABB 10;
		PVPF C 4;
		PVPF D 4;
		XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
		PVPF E 4;
		tnt1 A 0 A_SpawnProjectile ("MeatDeath", 50, 0, random (0, 360), 2, random (0, 160))       ;
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 50);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 50);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 50);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 50);
		tnt1 AA 0 A_SpawnProjectile ("XDeathArm1", 42, 0, random (0, 360), 2, random (0, 90));
		PVPF EFGGGG 4;
		//////////////////////////////////////////////////////
		tnt1 A 0 A_TakeInventory("PVPFatality",1);
		tnt1 A 0 A_TakeInventory("GoFatality", 1);
		tnt1 A 0 A_GiveInventory("Megasphere",1);
		MARN A 0 doomb_destroy_fatality_camera();//Stop Camera
	
	Goto StandStill;
	
	
	
	
	
	
	// STEALTH KILLS
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	// Monsters that can perform fatality on player:
	
	
	// Baron and Hell Knight:
Death.HKFT:
Death.BHFT:
Death.RVFT:
	tnt1 A 1 A_PlayerScream;
	tnt1 A 1 A_NoBlocking;
	tnt1 A 0 A_GiveToTarget("Curbstomp_Marine",1);
	tnt1 A -1;
	Stop;
	
	//Imp:
Death.ImpFatalityMarine:
	tnt1 A 1 A_PlayerScream;
	tnt1 A 1 A_NoBlocking;
	tnt1 A 0 A_GiveToTarget("Fatality_Marine",1);
	tnt1 A 500;
	tnt1 A -1;
	Stop;
	
	
	
	
	
	
	
	
	
	
	//When you get MeatShields
	
	
GotImpShield:
	tnt1 A 0 A_TakeInventory("MeatAmmo", 100);
	tnt1 A 0 A_GiveInventory("ImpShield");
	tnt1 A 0 A_SelectWeapon("ImpShield");
	Goto SeeImpShield;
	
	
SeeImpShield:
	MAIS AB 8;
	Loop;
	
	
	
GotZmanShield:
	tnt1 A 0 A_TakeInventory("MeatAmmo", 100);
	tnt1 A 0 A_GiveInventory("ZmanShield");
	tnt1 A 0 A_SelectWeapon("ZmanShield");
	Goto SeeZmanShield;
	
	
SeeZmanShield:
	MAZS A 8;
	MAZS B 8;
	Loop;
	
	
GotSguyShield:
	tnt1 A 0 A_TakeInventory("MeatAmmo", 100);
	tnt1 A 0 A_GiveInventory("SguyShield");
	tnt1 A 0 A_SelectWeapon("SguyShield");
	Goto SeeSGuyShield;
	
SeeSGuyShield:
	MASS A 8;
	MASS B 8;
	Loop;
	
	
	
	
	
	
	
	
Salutes1:
	tnt1 A 0 A_PlaySound ("DSSALUTE");
	MWAV BCDEFEFDCB 7;
	Goto StandStill;
	
Salutes2:
	tnt1 A 0 A_PlaySound ("DSSALUTE");
	MWAV IJK 4;
	MWAV LMNNML 3;
	MWAV LMNNML 3;
	MWAV LMNNML 3;
	MWAV KJI 4;
Goto StandStill;
	
	
	
	//Special Checkers
	
	
SpecialChecker:
	tnt1 A 1;
	tnt1 A 0 A_TakeInventory("GoSpecial", 1);
	tnt1 A 0 A_JumpIfInventory("HasBarrel", 1, "BarrelStand");
	tnt1 A 0 A_JumpIfInventory("Kicking", 1, "RifleKick");
	tnt1 A 0 A_JumpIfInventory("ADSMode", 1, "ADSStand");
	tnt1 A 0 A_TakeInventory("GoSpecial", 1);
	Goto StandStill ;
	
	
SpecialCheckerMoving:
	tnt1 A 1;
	tnt1 A 0 A_TakeInventory("GoSpecial", 1);
	tnt1 A 0 A_JumpIfInventory("GotMeatShield", 1, "MeatShieldChecker");
	tnt1 A 0 A_JumpIfInventory("HasBarrel", 1, "BarrelMove");
	tnt1 A 0 A_JumpIfInventory("Kicking", 1, "RifleKick");
	tnt1 A 0 A_JumpIfInventory("ADSMode", 1, "ADSMove");
	tnt1 A 0 A_JumpIfInventory("HasImpShield", 1, "SeeImpShield");
	tnt1 A 0 A_JumpIfInventory("HasZmanShield", 1, "SeeZmanShield");
	tnt1 A 0 A_JumpIfInventory("HasSguyShield", 1, "SeeSguyShield");
	tnt1 A 0 A_TakeInventory("GoSpecial", 1);
	Goto See   ;
	
FatalityChecker:
	tnt1 A 0;
	tnt1 A 0 doomb_init_fatality_camera();//Start Camera
	
	tnt1 A 0 A_JumpIfInventory("PVPFatality", 1, "FatalityPVP");
	tnt1 A 0 A_JumpIfInventory("IsCurbstompingZombieman", 1, "CurbstompZombieman");
	tnt1 A 0 A_JumpIfInventory("IsCurbstompingSergeant", 1, "CurbstompSergeant")       ;
	tnt1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
	tnt1 A 0 A_JumpIfInventory("ImpFatality2", 1, "FatalityImp2");
	tnt1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp3");
	tnt1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZMan");
	tnt1 A 0 A_JumpIfInventory("ZombieManFatality2", 1, "FatalityZMan2");
	tnt1 A 0 A_JumpIfInventory("ZombieManFatality3", 1, "FatalityZMan3");
	tnt1 A 0 A_JumpIfInventory("ZombieManFatality4", 1, "FatalityZMan4");
	tnt1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
	tnt1 A 0 A_JumpIfInventory("SergeantFatality2", 1, "FatalitySergeant2");
	tnt1 A 0 A_JumpIfInventory("SergeantFatality3", 1, "FatalitySergeant3");
	tnt1 A 0 A_JumpIfInventory("RevenantFatality", 1, "FatalityRevenant");
	tnt1 A 0 A_JumpIfInventory("RevenantFatality2", 1, "FatalityRevenant2");
	tnt1 A 0 A_JumpIfInventory("FatsoFatality", 1, "FatalityFatso");
	tnt1 A 0 A_JumpIfInventory("HKFatality", 1, "FatalityHK");
	tnt1 A 0 A_JumpIfInventory("HKFatality2", 1, "FatalityHK2");
	tnt1 A 0 A_JumpIfInventory("HKFatality3", 1, "FatalityHK3");
	tnt1 A 0 A_JumpIfInventory("ArachnotronFatality", 1, "FatalityArachnotron");
	tnt1 A 0 A_JumpIfInventory("ArachnotronFatality2", 1, "FatalityArachnotron2");
	tnt1 A 0 A_JumpIfInventory("PEFatality", 1, "FatalityPE");
	tnt1 A 0 A_TakeInventory("GoFatality", 1);
	MARN A 0 doomb_destroy_fatality_camera();//Disable Camera.
Goto See;
	
	
	
MeatShieldChecker:
	tnt1 A 1;
	//tnt1 A 0 A_TakeInventory("GotMeatShield", 1)
	tnt1 A 0 A_TakeInventory("GoSpecial", 1);
	tnt1 A 0 A_JumpIfInventory("HasImpShield", 1, "GotImpShield");
	tnt1 A 0 A_JumpIfInventory("HasZmanShield", 1, "GotZmanShield");
	tnt1 A 0 A_JumpIfInventory("HasSguyShield", 1, "GotSguyShield");
	tnt1 A 0 A_TakeInventory("GoSpecial", 1);
	Goto See;
	
MeatShieldCheckerMoving:
	tnt1 A 1;
	//tnt1 A 0 A_TakeInventory("GotMeatShield", 1)
	tnt1 A 0 A_TakeInventory("GoSpecial", 1);
	tnt1 A 0 A_JumpIfInventory("HasImpShield", 1, "GotImpShield");
	tnt1 A 0 A_JumpIfInventory("HasZmanShield", 1, "GotZmanShield");
	tnt1 A 0 A_JumpIfInventory("HasSguyShield", 1, "GotSguyShield");
	tnt1 A 0 A_TakeInventory("GoSpecial", 1);
	Goto StandStill;
	
SpawnFriends: //This spawn any friendly marines that survived on the previous level
	tnt1 A 0 A_TakeInventory("CheckMarines", 1);
	PLAY A 2;

	TNT1 A 0 {bNOPAIN = false;}
	//tnt1 A 0 Thing_ChangeTID (0, 567)
	tnt1 A 0 A_JumpIfInventory("NumberOfAllies", 1, "SummonMarines");
SpawnFriends2:
	tnt1 A 0 A_JumpIfInventory("NumberOfAlliesMinigun", 1, "SummonMinigunners");
	Goto StandStill;
SpawnFriends3:
	tnt1 A 0 A_JumpIfInventory("NumberOfAlliesShotgun", 1, "SummonShotgunners");
	Goto StandStill;
SpawnFriends4:
	tnt1 A 0 A_JumpIfInventory("NumberOfAlliesPlasmagun", 1, "SummonPlasmagunners");
	Goto StandStill;
SpawnFriends5:
	tnt1 A 0 A_JumpIfInventory("NumberOfAlliesRocket", 1, "SummonRocketgunners");
	Goto StandStill;
SpawnFriends6:
	tnt1 A 0 A_JumpIfInventory("NumberOfAlliesBFG", 1, "SummonBFGgunners");
	Goto StandStill;
	
SummonMarines:
	PLAY A 2;
	TNT1 A 0 A_SpawnItemEx("Marine_Rifle",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItem("TeleportFog");

	tnt1 A 0 A_TakeInventory("NumberOfAllies", 1);
	tnt1 A 0 A_GiveInventory("MarinesDispenser", 1);
	tnt1 A 0 A_JumpIfInventory("NumberOfAllies", 1, "SummonMarines");
	Goto RecalculateMarines;
	
RecalculateMarines:
	PLAY A 2 A_TakeInventory("MarinesDispenser", 1);
	tnt1 A 0 A_GiveInventory("NumberOfAllies", 1);
	tnt1 A 0 A_JumpIfInventory("MarinesDispenser", 1, "RecalculateMarines");
	Goto SpawnFriends2;
	
	
SummonMinigunners:
	PLAY A 2;
	TNT1 A 0 A_SpawnItemEx("Marine_Minigun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItem("TeleportFog");

	tnt1 A 0 A_TakeInventory("NumberOfAlliesMinigun", 1);
	tnt1 A 0 A_GiveInventory("MarinesMinigunDispenser", 1);
	tnt1 A 0 A_JumpIfInventory("NumberOfAlliesMinigun", 1, "SummonMinigunners");
	Goto RecalculateMinigunners;
	
RecalculateMinigunners:
	PLAY A 2 A_TakeInventory("MarinesMinigunDispenser", 1);
	tnt1 A 0 A_GiveInventory("NumberOfAlliesMinigun", 1);
	tnt1 A 0 A_JumpIfInventory("MarinesMinigunDispenser", 1, "RecalculateMinigunners");
	Goto SpawnFriends3;
	
SummonShotgunners:
	PLAY A 2;
	TNT1 A 0 A_SpawnItemEx("Marine_Shotgun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItem("TeleportFog");

	tnt1 A 0 A_TakeInventory("NumberOfAlliesShotgun", 1);
	tnt1 A 0 A_GiveInventory("MarinesShotgunDispenser", 1);
	tnt1 A 0 A_JumpIfInventory("NumberOfAlliesShotgun", 1, "SummonShotgunners");
	Goto RecalculateShotgunners;
	
RecalculateShotgunners:
	PLAY A 2 A_TakeInventory("MarinesShotgunDispenser", 1);
	tnt1 A 0 A_GiveInventory("NumberOfAlliesShotgun", 1);
	tnt1 A 0 A_JumpIfInventory("MarinesShotgunDispenser", 1, "RecalculateShotgunners");
	Goto SpawnFriends4;
	
SummonPlasmaGunners:
	PLAY A 2;
			TNT1 A 0 A_SpawnItemEx("Marine_PlasmaGun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItem("TeleportFog");

	tnt1 A 0 A_TakeInventory("NumberOfAlliesPlasmaGun", 1);
	tnt1 A 0 A_GiveInventory("MarinesPlasmaGunDispenser", 1);
	tnt1 A 0 A_JumpIfInventory("NumberOfAlliesPlasmaGun", 1, "SummonPlasmaGunners");
	Goto RecalculatePlasmaGunners;
	
RecalculatePlasmaGunners:
	PLAY A 2 A_TakeInventory("MarinesPlasmaGunDispenser", 1);
	tnt1 A 0 A_GiveInventory("NumberOfAlliesPlasmaGun", 1);
	tnt1 A 0 A_JumpIfInventory("MarinesPlasmaGunDispenser", 1, "RecalculatePlasmaGunners");
	Goto SpawnFriends5;
	
SummonRocketGunners:
	PLAY A 2;
	TNT1 A 0 A_SpawnItemEx("Marine_Rocket",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItem("TeleportFog");

	tnt1 A 0 A_TakeInventory("NumberOfAlliesRocket", 1);
	tnt1 A 0 A_GiveInventory("MarinesRocketDispenser", 1);
	tnt1 A 0 A_JumpIfInventory("NumberOfAlliesRocket", 1, "SummonRocketGunners");
	Goto RecalculateRocketGunners;
	
RecalculateRocketGunners:
	PLAY A 2 A_TakeInventory("MarinesRocketDispenser", 1);
	tnt1 A 0 A_GiveInventory("NumberOfAlliesRocket", 1);
	tnt1 A 0 A_JumpIfInventory("MarinesRocketDispenser", 1, "RecalculateBFGGunners");
	Goto SpawnFriends6;
	
SummonBFGGunners:
	PLAY A 2;
	TNT1 A 0 A_SpawnItemEx("Marine_BFG",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	TNT1 A 0 A_SpawnItem("TeleportFog");

	tnt1 A 0 A_TakeInventory("NumberOfAlliesBFG", 1);
	tnt1 A 0 A_GiveInventory("MarinesBFGDispenser", 1);
	tnt1 A 0 A_JumpIfInventory("NumberOfAlliesBFG", 1, "SummonBFGGunners");
	Goto RecalculateBFGGunners;
	
RecalculateBFGGunners:
	PLAY A 2 A_TakeInventory("MarinesBFGDispenser", 1);
	tnt1 A 0 A_GiveInventory("NumberOfAlliesBFG", 1);
	tnt1 A 0 A_JumpIfInventory("MarinesBFGDispenser", 1, "RecalculateBFGGunners");
	Goto StandStill;
}






}

CLASS Player_Blood : Brutal_Blood { 
states
{
Spawn:
	tnt1 AAAAAAAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	tnt1 A 0 A_JumpIf(waterlevel > 1, "Splash");
	tnt1 A 0 A_SpawnProjectile ("CeilBloodLauncher", -1, 0, random (0, 360), 2, random (50, 130));
	tnt1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 7, 0, random (0, 360), 2, random (0, 160));
	stop;
Splash:
	tnt1 AAA 0 A_SpawnProjectile ("Underblood1", 7, 0, random (0, 360), 2, random (30, 150));
	stop;
	
}
}


CLASS PlayerFlyingBlood : doomb_blood
{ 
Default {


scale 0.75;
speed 7;
health 1;
radius 8;
height 1;

+MISSILE;
+CLIENTSIDEONLY;
+NOTELEPORT;
+NOBLOCKMAP;
+FORCEXYBILLBOARD;
+EXPLODEONWATER;
}
States
{
Spawn:
	tnt1 A 0 A_JumpIf(waterlevel > 1, "null");
	XDT1 ABCD 4 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
loop;

Death:
	tnt1 A 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
	XDT1 EFGHIJKL 3;
stop;
}
}


CLASS BloodOnVisor : PowerupGiver{ 
Default {
Inventory.Amount 1;
Scale 0.5;
Inventory.MaxAmount 10;
Powerup.Type "PowerBloodOnVisor";
Powerup.Duration 9;
Inventory.Icon "TNT1A0";
+INVENTORY.AUTOACTIVATE;
+INVENTORY.ALWAYSPICKUP;
Inventory.MaxAmount 0;
}
States
{
Spawn:
	tnt1 A 1;
	Stop;
} 
} 

CLASS PowerBloodOnVisor : PowerUp { 
Default {

Powerup.Duration 9;
Speed 0.4;
Inventory.Icon "TNT1A0";
}
}



CLASS BlueBloodOnVisor : PowerupGiver { 
Default {

Inventory.Amount 1;
Scale 0.5;
Inventory.MaxAmount 10;
Powerup.Type "powerBlueBloodOnVisor";
Powerup.Duration 9;
Inventory.Icon "TNT1A0";
+INVENTORY.AUTOACTIVATE;
+INVENTORY.ALWAYSPICKUP;
Inventory.MaxAmount 0;
}
States
{
Spawn:
	tnt1 A 1;
	Stop;
} 
} 

CLASS PowerBlueBloodOnVisor : PowerUp { 
Default {

Powerup.Duration 9;
Speed 0.4;
Inventory.Icon "TNT1A0";
}
}


CLASS GreenBloodOnVisor : PowerupGiver { 
Default {

Inventory.Amount 1;
Scale 0.5;
Inventory.MaxAmount 10;
Powerup.Type "powerGreenBloodOnVisor";
Powerup.Duration 9;
Inventory.Icon "TNT1A0";
+INVENTORY.AUTOACTIVATE;
+INVENTORY.ALWAYSPICKUP;
Inventory.MaxAmount 0;
}
States
{
Spawn:
	tnt1 A 1;
	Stop;
} 
} 

CLASS PowerGreenBloodOnVisor : PowerUp { 
Default {

Powerup.Duration 9;
Speed 0.4;
Inventory.Icon "TNT1A0";
}
}


CLASS ChainguyguyContinue : Inventory { 
Default {

inventory.maxamount 1;
}
}


CLASS ComeEatMeDemon : Inventory { 
Default {

inventory.maxamount 1;
}
}





CLASS MarineEattenByDemon: CurbstompedMarine { 
Default {

Health 100;
Height 16;
Radius 8;
MONSTER;
-GHOST;
+THRUACTORS;
+FRIENDLY;
}
States

{
Spawn:
	tnt1 A 0;
	tnt1 A 0 A_GiveInventory("ComeEatMeDemon");
	tnt1 A 0 doomb_spawn_bloodpool();
	XPL1 EEE 6 ;
	XPL1 E -1;
stop;
}

}	   
	

CLASS JustStartedGame : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS NeverSelectedShotgun : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS FootStep : ACTOR { 
Default {
	
	Radius 10;
	Height 10;
	Speed 7;
	Projectile;
	-NOGRAVITY;
	+MISSILE;
	+NOTELEPORT;
	+CLIENTSIDEONLY;
	+MOVEWITHSECTOR;
	+NOEXTREMEDEATH;
	DamageType "Trample";
	Damage 0;
	+NODAMAGETHRUST;
	+BLOODLESSIMPACT;
	+THRUACTORS;
	gravity 40;
	mass 1000;
	Obituary "%o was trampled by %k.";
}
States
{
	Spawn:
		tnt1 A 2;
	stop;
}
}



CLASS FootstepStrong: FootStep { 
Default {
	
	Speed 0;
	Radius 16;
	Damage 15;
	Damagefunction (random (2, 3));
	-CLIENTSIDEONLY;
}
States
{
	Spawn:
	Death:
	Crash:
		tnt1 A 1;
		TNT1 A 0 {if(waterlevel > 1) A_SpawnItem("LargeMassWaterImpact");}
		tnt1 A 0 A_Explode(60,5,0);
		stop;
}
}



CLASS HeavyFootSteps32: FootStep { 
Default {
	
	Damage 1;
	-CLIENTSIDEONLY;
	DamageType "Stomp";
	Obituary "%o was trampled by a Cyberdemon.";
}
States
{
	Spawn:
		tnt1 A 2 nodelay A_Explode(900,10,0);
	stop;
}
}

CLASS IsPlayer : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}


CLASS GoFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS GoSpecial : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS GotMeatShield : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS PVPFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}


CLASS ZombieManFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS ZombieManFatality3 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS ZombieManFatality4 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS SKImp : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}


CLASS HasImpShield : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS HasZManShield : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS HasSGuyShield : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS ZombieManFatality2 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS ImpFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS ImpFatality2 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS ImpFatality3 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS SergeantFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS SergeantFatality2 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS SergeantFatality3 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}


CLASS LostSoulFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}


CLASS RevenantFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS RevenantFatality2 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS PEFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS FatsoFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS HKFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS HKFatality2 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS HKFatality3 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS ArachnotronFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS ArachnotronFatality2 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS Taunting : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS Enraged : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS Curbstomp_Marine : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS Fatality_Marine : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS SSGAlt : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS IsJumping : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS IsDown : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}


CLASS HasBarrel : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}





CLASS IsCurbstompingZombieman : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS IsCurbstompingSergeant : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}