//FIXME placeholders to shut modeldef parser
class ShrapnelParticle : actor{}

CLASS WoodParticle : actor { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.6;
		Speed 7;
		Mass 1;
		gravity 0.5;
		BounceFactor 0.6;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;

		Scale 1.5;
		+THRUACTORS;
		bouncefactor 0.5;
		speed 8;
		seesound "";
	}
	states
	{
		Spawn:
			TNT1 A 0;
			WOOD ABCD 2;
			loop;
		Death:
			TNT1 A 0;
			WOOD B 300;
			WOOD BBBBB 1 A_FadeOut(0.2);
			Stop;
	}
}

CLASS WoodParticleSmall: WoodParticle { 
	Default {
		
		Scale 0.9;
		speed 6;
	}
}

CLASS WoodParticleBig: WoodParticle { 
	Default {
		
		Scale 2.3;
		speed 11;
	}
}

CLASS WoodParticleTIny: WoodParticle { 
	Default {
		
		Scale 0.6;
		speed 5;
	}
	states
	{
		Death:
			TNT1 A 0;
			WOOD B 100;
			WOOD BBBBB 1 A_FadeOut(0.2);
			Stop;
	}
}






CLASS XIceChunk1 : ACTOR { 
	Default {
 
    Radius 4;
    Height 4;
    Speed 8;
    Scale 1.0;
	Mass 1;
    +NOBLOCKMAP
	+MISSILE
    +NOTELEPORT
    +MOVEWITHSECTOR
    +CLIENTSIDEONLY
	-DONTSPLASH
	+THRUGHOST
	+THRUACTORS
		+DOOMBOUNCE;
		Alpha 1;
		BounceFactor 0.4;
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			ICC1 ABCD 3;
			Loop;
		Death:
			ICC1 A 100;
			ICC1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 A_FadeOut(0.01);
			Stop;
	}
}


CLASS XIceChunk2: XIceChunk1 { 
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			ICC2 ABCD 3;
			Loop;
		Death:
			ICC2 A 100;
			ICC2 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 A_FadeOut(0.01);
			Stop;
	}
}



CLASS XIceChunk3: XIceChunk1 { 
	Default {
		
		-DOOMBOUNCE;
		Gravity 0.4;
		Speed 6;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			ICC3 ABCD 3;
			Loop;
		Death:
			ICC3 A 100;
			ICC3 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 A_FadeOut(0.01);
			Stop;
	}
}