

CLASS ExplosionSmoke : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		+NOTELEPORT;
		+DONTSPLASH;
		+MISSILE;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		+NOINTERACTION;
		+NOGRAVITY;
		+DOOMBOUNCE;
		+THRUACTORS;
		Health 99999;
		BounceFactor 0.5;
		Radius 0;
		Height 0;
		Alpha 0.1;
		RenderStyle "Translucent";
		Scale 1.1;
		Speed 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay a_scalevelocity(random(1, 3) );
			tnt1 a 0 a_setscale(frandom(0.8, 1.1));
			TNT1 A 0 A_JumpIf(waterlevel > 1, "null");
			SMK3 BBB 2 A_FadeIn(0.1);
			SMK3 B 20;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMK3 CDEFGHIJKLM 3;
			Goto Death;
		Death:
			TNT1 A 0;
			Stop;
	}
}


CLASS ExplosionSmokeSmall22: ExplosionSmoke { 
	Default {
		
		Scale 0.2;
	}
}



CLASS HeavyExplosionSmoke: ExplosionSmoke { 
	Default {
		
		Speed 1;
	}
	States
	{
		Spawn:
			SMO2 A 5;
			SMO2 A 80;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMO2 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 2 A_FadeOut(0.01);
			Goto Death;
		Death:
			TNT1 A 0;
			Stop;
		Stap:
			TNT1 A 0;
			Stop;
	}
	
}




CLASS BigSmokes: ExplosionSmoke { 
	Default {
		
		Speed 1;
		Alpha 0.1;
		Scale 1.5;
	}
	States
	{
		Spawn:
			SMOK A 0;
			Goto Death;
		Death:
			//SMOC ABCDEFGHIJKLMNOPQRSTUVWXYZ 4 A_FadeOut(0.01)
			//SM7C AB 4 A_FadeOut(0.01)
			//SMOC ABCDEFGHIJKLMNOPQRSTUVWXYZ 4 A_FadeOut(0.01)
			//SM7C AB 4 A_FadeOut(0.01)
			//SMOK EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 A_FadeOut(0.002)
			//PUF2 ABCDEFGHIJKLMNOPQRSTUVWXYZ 2 A_FadeOut(0.010)
			SMK3 B 100;
			SMK3 CDEFGHIJKLM 1;
			
			Stop;
	}
}



CLASS GunFireSmoke: ExplosionSmoke { 
	Default {
		
		Alpha 0.3;
		Scale 0.2;
		Renderstyle "Add";
		Speed 8;
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay
			{
				a_setscale(frandom(-0.22, 0.22));
		}
		SMOK ABCDEFGHIJKLMNOPQ 1;
		Stop;
	}
}


CLASS SmallSmokers: BigSmokes { 
	Default {
		
		Scale 3.3;
		Speed 0;
		Alpha 0.11;
		-NOGRAVITY;
		-NOINTERACTION;
		Gravity 0.005;
	}
	States
	{
		Spawn:
			PUF2 E 2 A_FadeOut(0.003);
			wait;
	}
}


CLASS BigSmallSmokers: BigSmokes { 
	Default {
		
		Scale 0.6;
		Speed 0;
		Alpha 0.11;
		-NOGRAVITY;
		-NOINTERACTION;
		Gravity 0.005;
	}
	States
	{
		Spawn:
			PUF2 EEFGHIJK 4 A_FadeOut(0.005);
			PUF2 LMNOPQRSTUVWXYZ 4 A_FadeOut(0.005);
			Goto Death;
		Death:
			TNT1 A 0;
			
			Stop;
	}
}


CLASS AltSmoke: ExplosionSmoke { 
	Default {
		
		+NOINTERACTION;
		+NOCLIP;
		Scale 0.8;
	}
	States
	{
		Spawn:
			PUF2 A 1;
			Goto Death;
		Death:                                                          
			PUF2 ABCDEFGHIJKLMNOPQRSTUVWXYZ 2 A_FadeOut(0.010);
			
			Stop;
	}
}

CLASS ShinnySmoke: AltSmoke { 
	Default {
		
		Scale 2.0;
		Renderstyle "Add";
	}
}



CLASS PlasmaSmoke: ExplosionSmoke { 
	Default {
		
		Speed 1;
		Scale 0.5;
		Alpha 0.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMK3 BB 2 A_FadeIn(0.1);
			SMK3 B 20;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMK3 CDEFGHIJKLM 3;
			Goto Death;
	}
}

CLASS Vapor1: PlasmaSmoke { 
	Default {
		
		Renderstyle "Add";
	}
}


CLASS RocketSmokeTrail52: ExplosionSmoke { 
	Default {
		
		Speed 1;
		Alpha 0.3;
		Scale 0.3;
	}
	States
	{
		Spawn:
			TNT1 A 2;
			SMK3 B 20;
			SMK3 CDEFGHIJKLM 1;
			Stop;
	}
}



CLASS OldschoolRocketSmokeTrail2: AltSmoke { 
	Default {
		
		Alpha 0.7;
		Speed 1;
		+CLIENTSIDEONLY;
		Scale 0.2;
	}
	States
	{
		Spawn:  
			TNT1 A 2;
			SMK3 BCDEFGHIJKKLLMMN 2;
			Stop;
			
			Stop;
	}
}


CLASS NeoSmoke: AltSmoke { 
	Default {
		
		Alpha 0.1;
		Speed 1;
		+CLIENTSIDEONLY;
		Scale 1.5;
	}
	States
	{
		Spawn:
			TNT1 A 2;
			Goto Death;
		Death:                                                          
			PUF2 EEFGHIJK 2 A_FadeOut(0.010);
			TNT1 A 0 A_SpawnItem ("BigSmallSmokers");
			PUF2 LMNOPQRSTUVWXYZ 2 A_FadeOut(0.010);
			
			Stop;
	}
}


CLASS BigNeoSmoke: HeavyExplosionSmoke { 
	Default {
		
		//Alpha 0.6
		Scale 1.4;
		Alpha 0.12;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMO2 A 45;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMO2 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 2 A_FadeOut(0.002);
			Goto Death;
		Death:
			TNT1 A 0;
			Stop;
		Stap:
			TNT1 A 0;
			Stop;
	}
}


CLASS HugeNeoSmoke: BigNeoSmoke { 
	Default {
		
		Alpha 0.5;
		Scale 2.5;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMO2 A 5;
			SMO2 A 40;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMO2 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 2 A_FadeOut(0.003);
			Goto Death;
	}
}

CLASS RidiculousNeoSmoke: BigNeoSmoke { 
	Default {
		
		Alpha 0.5;
		Scale 5.0;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMO2 A 5;
			SMO2 A 40;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMO2 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 2 A_FadeOut(0.003);
			Goto Death;
	}
}

CLASS SmallSmoke: AltSmoke { 
	Default {
		
		+CLIENTSIDEONLY;
		Speed 1;
		Scale 1.5;
	}
}



CLASS MeleeSmoke: ExplosionSmoke { 
	Default {
		
		Speed 1;
		Alpha 0.15;
		Scale 0.2;
	}
	States
	{
		Spawn:
			//SMK1 IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 1 A_FadeOut(0.005)
			SMK3 B 4;
			SMK3 CDEFGHIJKLM 2;
			Stop;
	}
}


CLASS SmokeTrail : ACTOR { 
	Default {
		
		Scale 0.4;
		Alpha 0.3;
		Speed 1;
		RenderStyle "Translucent";
		+NOCLIP;
		+NOGRAVITY;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		+RANDOMIZE;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			SMOK ABCDEFGHIJKLMNOPQ 2 BRIGHT a_settics(random(2, 6));
			stop;
	}
}

CLASS SmokeTrail2 : ACTOR { 
	Default {
		
		Radius 1;
		Height 1;
		Alpha 0.3;
		RenderStyle "Translucent";
		Scale 0.8;
		Speed 1;
		Gravity 0;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		+FORCEXYBILLBOARD;
		+RANDOMIZE;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			SMOK ABCDEFGHIJKLMNOPQ 2 BRIGHT;
			stop;
	}
}








CLASS SmokeSpawner : ACTOR { 
	Default {
		
		Speed 20;
		+NOCLIP;
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 Thing_ChangeTID(0,390);
			tnt1 AA 0 A_SpawnProjectile ("ShotSmoke", 0, 0, random (0, 360), 2, random (0, 180));
			Stop;
	}
}

CLASS ShotSmoke : ACTOR { 
	Default {
		
		+NOGRAVITY;
		+NOBLOCKMAP;
		+FLOORCLIP;
		+FORCEXYBILLBOARD;
		+NOINTERACTION;
		+FORCEXYBILLBOARD;
		+MISSILE;
		Speed 1;
		RenderStyle "Add";
		Alpha 0.06;
		+CLIENTSIDEONLY;
		Radius 0;
		Height 0;
		Scale 0.6;
		
	}
	States
	{
		Spawn:
			tnt1 A 1;
			SMOK AABBCCDDEEFFGGHHIIJJKK 1 A_FadeOut(0.001);
			Stop;
	}
}

CLASS TorchSmoke : ACTOR { 
	Default {
		
		+NOGRAVITY;
		+NOBLOCKMAP;
		+FLOORCLIP;
		+FORCEXYBILLBOARD;
		+NOINTERACTION;
		+FORCEXYBILLBOARD;
		+MISSILE;
		+GHOST;
		Speed 1;
		RenderStyle "Translucent";
		Alpha 0.2;
		+CLIENTSIDEONLY;
		+NOCLIP;
		Radius 0;
		Height 0;
		Scale 1.2;
		
	}
	States
	{
		Spawn:
			tnt1 A 1;
			SMOK AAAAABBBBBCCCCCDDDDDEEEEEFFFFFGGGGGHHHHHIIIIIJJJJJKKKKK 1 A_FadeOut(0.005);
			Stop;
	}
}















CLASS CyberStep : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOTELEPORT;
		renderstyle "Translucent";
		alpha 0.75;
		Scale 0.5;
	}
	states
	{
		Spawn:
			MNSM ABCDEFGHIJKLMNOPQ 1 bright;
			stop;
	}
}

CLASS LostSoulOnHandFireSpawner : ACTOR { 
	Default {
		
		Speed 20;
		+NOCLIP;
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 Thing_ChangeTID(0,390);
			tnt1 AAA 0 A_SpawnProjectile ("SoulTrails", 0, 0, random (0, 360), 2, random (0, 180));
			Stop;
	}
}


CLASS LSOHK : ACTOR { 
	Default {
		
		Speed 20;
		+NOCLIP;
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_PlaySound ("Skull/Death");
			EXPL AAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("FlameTrails", 6, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("ExplosionParticle2", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAA 0 A_SpawnProjectile ("LSpart1", 42, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("LSpart3", 42, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("LSpart2", 42, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0;
			Stop;
	}
}










CLASS BarrelExplosionSmokeColumn : ACTOR { 
	Default {
		
		XScale 1.4;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+DONTSPLASH;
		+CLIENTSIDEONLY;
		Damage 0;
	}
	States
	{
		Spawn:
			SB17 E 4;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SB17 ABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCDABCD 5;
			SB17 E 4;
			Stop;
		Stap:
			TNT1 A 0;
			Stop;
	}
}



CLASS ExplosionSimpleSmokeColumn: BarrelExplosionSmokeColumn { 
	Default {
		
		Radius 0;
		Height 0;
		Alpha 0.4;
		RenderStyle "Translucent";
		XScale 1.5;
		YScale 0.6;
	}
}

CLASS ExplosionSimpleSmokeColumn2: ExplosionSimpleSmokeColumn { 
	Default {
		
		+NOGRAVITY;
	}
}
	
	
	
CLASS BigBlackSmoke : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		+NOTELEPORT;
		+DONTSPLASH;
		+MISSILE;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		+NOINTERACTION;
		+NOGRAVITY;
		+DOOMBOUNCE;
		+THRUACTORS;
		Health 99999;
		BounceFactor 0.5;
		Radius 1;
		Height 1;
		Alpha 1.0;
		RenderStyle "Translucent";
		Scale 0.7;
		Speed 2;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_FadeOut(0.9);
			SMK1 KKKKKKKK 2 A_FadeIn(0.02);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMK1 K 25 a_settics(random(25,50) );
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Stap");
			SMK1 KKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKK 2 A_FadeOut(0.01);
			Goto Death;
		Death:
			TNT1 A 0;
			Stop;
		Stap:
			TNT1 A 0;
			Stop;
	}
}

CLASS MediumBlackSmoke: BigBlackSmoke { 
	Default {
		
		Scale 0.3;
	}
}
