
CLASS CyberdemonBoss: doomb_monster_base
{ 
	Default {
		damagefactor "Explosive_Impact", 1.1;
		damagefactor "HKFT", 0.05;
		damagefactor "HKFT", 0.05;
		damagefactor "Avoid", 0.0;

		Obituary "%o was destroyed by the Cyberdemon.";
		+NOICEDEATH;
		Health 10000;
		damagefactor "Crush", 20.0;
		MaxStepHeight 24;
		MaxDropOffHeight 32;
		Scale 2.4;
		Radius 90;
		Height 220 + 32;
		doomb_monster_base.head_starting_position 200;
		doomb_monster_base.headshot_multiplier 1.5;

		+MISSILEMORE;
		+MISSILEEVENMORE;
		+DONTRIP;
		+NORADIUSDMG;
		+QUICKTORETALIATE;
		+boss;
		Speed 28;
		FastSpeed 32;
		painchance "kick", 255;
		mass 5000;
		PainChance "Taunt", 255;
		DropItem "DemonStrengthRune", 25;
		BloodType "CyberDemon_Blood", "SawBlood", "SawBlood";
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
	}
	States
	{
		
		Death.Taunt:
			TNT1 A 0 {bsolid = false;}
			TNT1 A 0 A_SpawnItem("TheCyberdemon");
			Stop;
			
		Spawn:
			CYBR DZ 10 A_Look;
		Loop;
			
		See:
			CYBR A 3 A_Hoof;
			
			TNT1 A 0 A_SpawnItem("HeavyFootSteps32");
			CYBR A 3;
			TNT1 A 0 A_JumpIfCloser(250, "Stomp");
			
			CYBR AA 2 A_Chase;
			TNT1 A 0 A_JumpIfCloser(250, "Stomp");
			CYBR BB 2 A_Chase;
			
			CYBR BBC 2 A_Chase;
			TNT1 A 0 A_SpawnItem("HeavyFootSteps32");
			TNT1 A 0 A_JumpIfCloser(250, "Stomp");
			
			CYBR C 2 A_Chase;
			CYBR C 2;
			CYBR C 2 A_Metal;
			CYBR DD 2 A_Chase;
			TNT1 A 0 A_JumpIfCloser(250, "Stomp");
			CYBR DD 2 A_Chase;
		Loop;
			
			
		Missile:
			TNT1 A 0 A_JumpIfCloser(250, "Stomp");
			TNT1 A 0 A_JumpIfInventory("Enraged", 1, "SpecialAttack");
			
			CYBR E 8 A_FaceTarget;
			
			CYBR F 6 BRIGHT A_SpawnProjectile("FastCyberBalls",120,-50,random(-7, 7) );
			CYBR E 6 A_FaceTarget;
			tnt1 a 0 a_jump(128, "missile");
		Goto See;
			
			
		Stomp:
			
			CYBR Z 5 A_FaceTarget;
			TNT1 A 0 A_Recoil(-15);
			
			CYMA A 7 A_FaceTarget;
			CYBR Z 0 A_FaceTarget;
			TNT1 A 0 A_Recoil(-15);
			
			TNT1 A 0 A_Spawnitem("CyberStomp",10);
			CYMA B 7;
			
			CYMA B 7;
			
			Goto See;
		Death:
			CYBR H 10;
			EXPL A 0 Radius_Quake (6, 100, 0, 22, 0);
		TNT1 AAAA 0
		{
			A_PlaySound("FAREXPL");
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		}
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 190, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_SpawnProjectile ("UltraGoreSpawner", 190, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("CyberXDeath", 100, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
			CYBR I 5 A_Scream;
		EXPL AAAA 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 AAAAA 0 A_SpawnItem("SpawnedExplosionRepeat");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(2.3, 2.7), 0), 0.5 );
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
		TNT1 A 0;
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
		TNT1 A 0 A_SpawnItem("NewfagExplosionFlare");
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(9, 9.4), 0) );
		TNT1 AAA 0 A_SpawnItem("NewfagExplosionFlare");
			CYBR JKL 5;
			CYBR M 5 A_NoBlocking;
			CYBR NOP 5;
			CYBR P 200;
			TNT1 A 0 A_BrainDie;
			CYBR P -1 A_BossDeath;
			Stop;
		Pain.Taunt:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("Enraged", 1, "SpecialAttack");
			SPOS B 0 A_Pain;
			TNT1 A 0 {bMISSILEMORE = true;}
			TNT1 A 0 {bMISSILEEVENMORE = true;}
			TNT1 A 0 A_PlaySound("demon/pain");
			CYBT A 1 A_FaceTarget;
			CYBT ABCCBADE 4;
			TNT1 A 0 A_PlaySound("CYBTAT", 1);
			CYBT FGHGFGHGFGHGFGHG 3;
			CYBT EDA 4;
			TNT1 A 0 A_GiveInventory("Enraged", 1);
			Goto Missile;
			
		SpecialAttack:
			
			CYBR E 6 A_FaceTarget;
			
			CYBR F 4 BRIGHT A_SpawnProjectile("FastCyberBalls",120,-50,0,0);
			TNT1 A 0 A_JumpIfCloser(180, "Stomp");
			
			CYBR E 4 A_FaceTarget;
			
			CYBR F 4 BRIGHT A_SpawnProjectile("FastCyberBalls",120,-50,-7,0);
			TNT1 A 0 A_JumpIfCloser(180, "Stomp");
			
			CYBR E 4 A_FaceTarget;
			
			CYBR F 4 BRIGHT A_SpawnProjectile("FastCyberBalls",120,-50,7,0);
			TNT1 A 0 A_JumpIfCloser(180, "Stomp");
			
			CYBR E 4 A_FaceTarget;
			
			CYBR F 4 BRIGHT A_SpawnProjectile("FastCyberBalls",120,-50,0,0);
			TNT1 A 0 A_JumpIfCloser(180, "Stomp");
			
			CYBR E 4 A_FaceTarget;
			
			CYBR F 4 BRIGHT A_SpawnProjectile("FastCyberBalls",120,-50,0,0);
			CYBR E 4 A_FaceTarget;
			
			CYBR F 4 BRIGHT A_SpawnProjectile("FastCyberBalls",120,-50,0,0);
			Goto See;
			
	}
}









CLASS SuperMastermind : doomb_monster_base { 
	Default {
		damagefactor "HKFT", 0.05;
		damagefactor "Explosive_Impact", 1.5;
		damagefactor "Avoid", 0.0;
		damagefactor "Stomp", 0.0;

		Obituary "%o was destroyed by a Mastermind.";
		+NOICEDEATH;
		
		Height 144 + 100;
		doomb_monster_base.head_starting_position 150;
		doomb_monster_base.headshot_multiplier 1.5;

		Health 20000;
		Radius 210;
		damagefactor "Crush", 30.0;
		Scale 2.5;
		Mass 500000;
		Speed 40;
		+NOTARGET;
		PainChance 30;
		PainChance "Explosive_Impact", 80;
		Monster;
		+BOSS;
		+FLOORCLIP;
		+DONTRIP;
		+DONTMORPH;
		+BOSSDEATH;
		+NORADIUSDMG;
		+NOBLOOD;
		+MISSILEMORE;
		-SOLID;
		+MISSILEEVENMORE;
		+SHOOTABLE;
		DropItem "DemonStrengthRune", 25;
		SeeSound "spider/sight";
		AttackSound "spider/attack";
		PainSound "spider/pain";
		DeathSound "spider/death";
		ActiveSound "spider/active";
		obituary "$OB_SPIDER";
		damagefactor "Blood", 0.0;
		MaxStepHeight 24;
		MaxDropOffHeight 32;
	}
	States
	{
		Death.Taunt:
			TNT1 A 0 {bsolid = false;}
			TNT1 A 0 A_SpawnItem("TheSpiderMastermind");
			Stop;
		Spawn:
			TNT1 A 0;
			SPID A 10 A_Look;
			Loop;
		See:
			SPID A 2 A_Metal;
			
			SPID ABBCCD 2
			{
				A_Recoil(-3);
				A_Chase();
			}
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", 180, 180);
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", -180, 180);
			SPID D 2 A_Metal;
			
			
			SPID EEF 2
			{
				A_Recoil(-3);
				A_Chase();
			}
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", 180, -180);
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", -180, -180);
			Loop;
			
		Missile:
			SPID AAAH 4 A_FaceTarget;
			TNT1 AAAAAAAAAAAAAAAAA 0;
			TNT1 A 0 A_JumpIfCloser(200, "StopFiring");
			SPID G 2 A_FaceTarget;
			SPID H 2 BRIGHT A_SpawnProjectile("SuperMastermindTracer", 124, 0, random(-7, 7), 1, random(-4, 2));
			TNT1 A 0 A_SpawnItem ("MasterMindCaseSpawn", 0, 60,0);
			SPID G 0 A_SpidRefire;
		Goto see;
			
		StopFiring:
			SPID A 6 A_FaceTarget;
		Goto See;
			
		Avoid:
			SPID ABCD 6
			{
				A_FastChase();
				A_FaceTarget();
			}
		Goto Missile;
			
		Pain:
			SPID I 4 A_Pain;
		Goto See;
			
		Death:
			SPID J 20 A_Scream;
			tnt1 a 0 A_FaceTarget;
			EXPL A 0 Radius_Quake (8, 100, 0, 22, 0);
		TNT1 AAAA 0
		{
			A_PlaySound("FAREXPL");
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		}
			TNT1 AAAA 0 A_SpawnProjectile ("SuperGoreSpawner", 110, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID K 10 A_NoBlocking;
		TNT1 AAAA 0
		{
			A_PlaySound("FAREXPL");
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		}
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 80, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID L 5;
			TNT1 AAAA 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
		EXPL AAAA 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 AAAAA 0 A_SpawnItem("SpawnedExplosionRepeat");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(2.3, 2.7), 0), 0.5 );
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
		TNT1 A 0;
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
		TNT1 A 0 A_SpawnItem("NewfagExplosionFlare");
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(9, 9.4), 0) );
		TNT1 AAA 0 A_SpawnItem("NewfagExplosionFlare");
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 30, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_SpawnProjectile ("UltraGoreSpawner", 30, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 30, 0, random (0, 360), 2, random (70, 90));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 100, 0, random (0, 360), 2, random (20, 90));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 300;
			TNT1 A 0 A_BrainDie;
			Stop;
			
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS3 A 5;
			CRS3 A -1;
			Stop;
			
			
		Death.Cut:
		Death.Saw:
			TNT1 AAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XDeath1", 120, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0 A_SpawnProjectile ("XSpiderMastermindCuttedBrain", 120, 0, random (0, 360), 2, random (50, 130));
			SPIY AAAAAAAAAAA 8 A_SpawnItem("MuchBlood", 0, 120);
			
			EXPL A 0 Radius_Quake (8, 100, 0, 22, 0);
		TNT1 AAAA 0
		{
			A_PlaySound("FAREXPL");
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		}
			TNT1 AAAA 0 A_SpawnProjectile ("SuperGoreSpawner", 110, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID K 10 A_NoBlocking;
		TNT1 AAAA 0
		{
			A_PlaySound("FAREXPL");
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		}
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 80, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID L 5;
			TNT1 AAAA 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
		EXPL AAAA 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 AAAAA 0 A_SpawnItem("SpawnedExplosionRepeat");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(2.3, 2.7), 0), 0.5 );
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
		TNT1 A 0;
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
		TNT1 A 0 A_SpawnItem("NewfagExplosionFlare");
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(9, 9.4), 0) );
		TNT1 AAA 0 A_SpawnItem("NewfagExplosionFlare");
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 30, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_SpawnProjectile ("UltraGoreSpawner", 30, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 30, 0, random (0, 360), 2, random (70, 90));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 100, 0, random (0, 360), 2, random (20, 90));
			TNT1 AAA 0 A_SpawnProjectile ("MastermindLeg", 30, 0, random (0, 360), 2, random (40, 90));
			TNT1 A 0 A_SpawnProjectile ("MastermindLeg", 30, 0, 0, 2, 65);
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 300;
			TNT1 A 0 A_BossDeath;
			Stop;
	}
}
