//Tracing projectiles goes here

CLASS Tracer: doomb_boolet_base { 
	Default {
		
		Projectile;
		+RANDOMIZE;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+NOEXTREMEDEATH;
		+MISSILE;
		damage 0;
		radius 2;
		height 2;
		speed 140;
		renderstyle "Add";
		alpha 0.9;
		scale 0.15;
		
	}
	states
	{
		Spawn:
			TRAC A 1 BRIGHT;
			Loop;
		Death:
			tnt1 a 1;
		Stop;
	}
}

CLASS MinigunTracer: Tracer { 
	Default {
		
		-DONTSPLASH;
		seesound "weapons/minigunfire";
		damagetype "Cutless";
	}
}



CLASS MonsterTracer: Tracer { 
	Default {
		
		+BLOODSPLATTER;
		+THRUGHOST;
		-DONTSPLASH;
		speed 60;
		damagefunction (random(9,12));
		Decal "BulletDecalNew1";
		DamageType "MonsterBullet";
	}
	States
	{
		Spawn:
			TRAC A 1 BRIGHT;
			TNT1 A 0 ThrustThingZ(0,random(-8, 8),0,1);
			TRAC A 1 BRIGHT;
		Spawn2:
			TRAC A 1 BRIGHT;
			Loop;
			
		Death:
			TNT1 A 0 A_SpawnItemEx ("RicoChet",0,0,-5,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
	}
}



CLASS ShotgunguyTracer: Tracer { 
	Default {
		
		+BLOODSPLATTER;
		+THRUGHOST;
		-DONTSPLASH;
		+MISSILE;
		speed 60;
		damagefunction (random(9,14));
		Decal "BulletDecalNew1";
		DamageType "MonsterShotgunBullet";
	}
	States
	{
		Spawn:
			TRAC A 1 BRIGHT;
			TNT1 A 0 ThrustThingZ(0,random(-8, 8),0,1);
			TRAC A 1 BRIGHT;
			Goto Spawn2;
			
		Spawn2:
			TRAC A 1 BRIGHT;
			Loop;
			
		Death:
			TNT1 A 0 A_SpawnItemEx ("RicoChet",0,0,-5,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
	}
}

CLASS ZombieManTracer: MonsterTracer { 
	Default {
		
		damagefunction (random(6,9));
	}
}


CLASS MonsterMinigunTracer: MonsterTracer { 
	Default {
		
		+BLOODSPLATTER;
		+THRUGHOST;
		-DONTSPLASH;
		speed 60;
		damagefunction (random(6,6));
		seesound "CHGNSHOT";
		damagetype "MonsterCutless";
		Decal "BulletDecalNew1";
	}
	States
	{
		
		Death:
			TNT1 A 0 A_SpawnItemEx ("RicoChet",0,0,-5,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
	}
}


CLASS MeatShieldTracer: Tracer { 
	Default {
		
		+BLOODSPLATTER;
		+THRUACTORS;
		-DONTSPLASH;
		speed 100;
		damagefunction (random(20,25));
		Decal "BulletDecalNew1";
	}
	States
	{
		Death:
			TNT1 A 0 A_SpawnItemEx ("RicoChet",0,0,-5,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		Spawn:
			TRAC A 1 BRIGHT;
			TNT1 A 0 {bTHRUACTORS = false;}
		Fly:
			TRAC A 1 BRIGHT;
			Loop;
	}
}


CLASS MarineTracer: Tracer { 
	Default {
		
		+BLOODSPLATTER;
		+THRUGHOST;
		-DONTSPLASH;
		-GHOST;
		-THRUGHOST;
		+THRUSPECIES;
		+MTHRUSPECIES;
		speed 100;
		damagefunction (random(8,10));
		Decal "BulletDecalNew1";
	}
	States
	{
		Death:
			TNT1 A 0 A_SpawnItemEx ("RicoChet",0,0,-5,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
		XDEath:
			TNT1 A 0;
			//TNT1 A 0 A_Explode(2, 5)
			TNT1 A 1;
			Stop;
	}
}

CLASS MarineStrongTracer: MarineTracer { 
	Default {
		
		damagefunction (random(12,13));
	}
	States
	{
		Spawn:
			TRAC A 1 BRIGHT;
			TNT1 A 0 ThrustThingZ(0,random(-9, 9),0,1);
			TRAC A 1 BRIGHT;
			Goto Spawn2;
			
		Spawn2:
			TRAC A 1 BRIGHT;
			Loop;
	}
}


CLASS MarineShotgunTracer: MarineTracer { 
	Default {
		
		damagefunction (random(10,12));
		damagetype "Shotgun";
	}
	States
	{
		Spawn:
			TRAC A 1 BRIGHT;
			TNT1 A 0 ThrustThingZ(0,random(-9, 9),0,1);
			TRAC A 1 BRIGHT;
			Goto Spawn2;
			
		Spawn2:
			TRAC A 1 BRIGHT;
			Loop;
	}
}



CLASS Alerter: MonsterTracer { 
	Default {
		
		-BLOODSPLATTER;
		+THRUGHOST;
		+DONTSPLASH;
		-ACTIVATEIMPACT;
		-ACTIVATEMCROSS;
		-ACTIVATEPCROSS;
		speed 200;
		radius 12;
		height 12;
		damagefunction (random(1,1));
		DamageType "Avoid";
		Decal "None";
	}
	States
	{
		Spawn:
			TNT1 A 1 BRIGHT;
			Loop;
		Death:
			TNT1 A 0;
			Stop;
	}
}


//check it
CLASS Taunter: MonsterTracer { 
	Default {
		
		-BLOODSPLATTER;
		+THRUGHOST;
		+DONTSPLASH;
		radius 16;
		height 16;
		speed 100;
		damagefunction (random(1,2));
		DamageType "Taunt";
		Decal "None";
		-ACTIVATEIMPACT;
		-ACTIVATEPCROSS;
	}
	States
	{
		Spawn:
			PUZZ Z 1 BRIGHT;
			Loop;
		XDeath:
		Melee:
		Death:
			TNT1 A 1;
			
			Stop;
	}
}





CLASS MastermindTracer: Tracer { 
	Default {
		
		+BLOODSPLATTER;
		+THRUGHOST;
		-DONTSPLASH;
		speed 90;
		damagefunction (random(5,7));
		scale .2;
		RenderStyle "Add";
		Alpha 0.9;
		seesound "SSHFIRE";
		damagetype "Explosive_Impact";
		Decal "Scorch";
		Obituary "$OB_SPIDER";
	}
	States
	{
		
		Spawn:
			tnt1 a 0 nodelay {vel *= frandom(0.8, 1.2);}
		mini:
			TRAC A 1;
		Loop;

		Death:
			EXPL A 0 A_Explode (2, 120, 0);
			TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
			TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (0.9, 0.9) );
			TNT1 A 0 A_SpawnItem("WhiteShockwaveSmall");
			TNT1 A 0 A_PlaySound("FAREXPL");
			TNT1 AAAAAAAA 4 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		Stop;
	}
}

CLASS SuperMastermindTracer: MastermindTracer { 
	Default {
		
		Speed 120;
		damagefunction (random(25,30));
		Height 24;
	}
}

	
	
	
	
	
	
	
	
	
	
	


CLASS SpawnBulletDecalBackwards: FastProjectile { 
	Default {
	
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+DONTSPLASH;
	+THRUACTORS;
	damage 0;
	radius 2;
	height 2;
	speed 50;
	renderstyle "Add";
	Decal "BulletDecalNew1";
	alpha 0.9;
	scale .3;
	}
states
	{
	Spawn:
		TNT1 A 1 BRIGHT;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItemEx ("RicoChet",0,0,-5,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 10;
		Stop;
	XDeath:
		TNT1 A 0;
		Stop;
}
}




CLASS Penetrator: MarineTracer { 
	Default {
	
	damagefunction (random(8,10));
	//Decal "BulletDecalNew1"
	Decal "none";
	-SKYEXPLODE;
	}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnProjectile("SpawnBulletDecalBackwards", 0, 0, 0);
		TRAC A 10 BRIGHT;
		sTOP;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_CheckFloor("XDeath");
		TNT1 A 0 A_CheckCeiling("XDeath");
		TNT1 A 0 A_SpawnItemEx ("RicoChet",0,0,-5,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
		
	DeathSpecial:
		
		Stop;
	XDEath:
		TNT1 A 0;
		//TNT1 A 0 A_Explode(2, 5)
		TNT1 A 1;
		Stop;
}
}





