//Tracing projectiles goes here

CLASS Tracer: doomb_boolet_base
{

override void Tick()
{
	if(target && target is "playerpawn")
	{
		if(random[monster_avoid](0,10) <= 1)
		{
			FLineTraceData avoider;

			LineTrace(angle, speed, pitch, data: avoider);

			if(avoider.hitactor && avoider.hitactor.health > 0 && avoider.hitactor.bcorpse == false && avoider.hitactor is "doomb_monster_base" && !(avoider.hitactor is "doomb_body_base") )
			{
				state neo = avoider.hitactor.findstate("avoid");
				if(neo)
					avoider.hitactor.setstate(neo);
			}
		}
	}

	super.tick();
}

	Default
	{
		Projectile;
		+RANDOMIZE;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+NOEXTREMEDEATH;
		+MISSILE;
		-DONTSPLASH;

		damage 0;
		radius 2;
		height 2;
		speed 100;
		renderstyle "Add";
		alpha 0.9;
		scale 0.15;
		Decal "BulletDecalNew1";
		
	}
	states
	{
		Spawn:
			TRAC A 1 BRIGHT nodelay {vel *= frandom(0.8, 1.4);}
		spawn_mini_loop:
			TRAC A 1 BRIGHT;
		Loop;

		Death:
			tnt1 a 1
			{
				if(!blockingmobj)
					A_SpawnItemEx ("RicoChet",0,0,-5,0,0,0,0,SXF_NOCHECKPOSITION,0);
			}
		Stop;
	}
}

CLASS MinigunTracer: Tracer { 
	Default {
		seesound "weapons/minigunfire";
		damagetype "Cutless";
	}
}



CLASS MonsterTracer: Tracer
{
	Default {
		+BLOODSPLATTER;
		+THRUGHOST;
		speed 60;
		damagefunction (random(9,12));
		DamageType "Bullet";
	}
}



CLASS ShotgunguyTracer: Tracer { 
	Default {
		+BLOODSPLATTER;
		+THRUGHOST;
		+MISSILE;
		speed 60;
		damagefunction (random(9,14));
		DamageType "Shotgun";
	}
}

CLASS ZombieManTracer: MonsterTracer { 
	Default {
		damagefunction (random(6,9));
	}
}


CLASS MonsterMinigunTracer: MonsterTracer { 
	Default {
		+BLOODSPLATTER;
		+THRUGHOST;
		speed 60;
		damagefunction (6);
		seesound "CHGNSHOT";
		damagetype "Cutless";
	}
}


CLASS MeatShieldTracer: Tracer { 
	Default {
		+BLOODSPLATTER;
		+THRUACTORS;
		damagefunction (random(20,25));
	}
}


CLASS MarineTracer: Tracer { 
	Default {
		+BLOODSPLATTER;
		+THRUGHOST;
		-GHOST;
		-THRUGHOST;
		+THRUSPECIES;
		+MTHRUSPECIES;
		damagefunction (random(8,10));
	}
}

CLASS MarineStrongTracer: MarineTracer { 
	Default {
		damagefunction (random(12,13));
	}
}


CLASS MarineShotgunTracer: MarineTracer { 
	Default {
		damagefunction (random(10,12));
		damagetype "Shotgun";
	}
}



//check it
CLASS Taunter: MonsterTracer { 
	Default {
		-BLOODSPLATTER;
		+THRUGHOST;
		+DONTSPLASH;
		radius 16;
		height 16;
		damagefunction (random(1,2));
		DamageType "Taunt";
		Decal "None";
		-ACTIVATEIMPACT;
		-ACTIVATEPCROSS;
	}
}





CLASS MastermindTracer: Tracer { 
	Default {
		+BLOODSPLATTER;
		+THRUGHOST;
		damagefunction (random(5,7));
		scale .2;
		RenderStyle "Add";
		Alpha 0.9;
		seesound "SSHFIRE";
		damagetype "Explosive_Impact";
		Decal "Scorch";
		Obituary "$OB_SPIDER";
	}
	States
	{
		
		Spawn:
			tnt1 a 0 nodelay {vel *= frandom(0.8, 1.2);}
		mini:
			TRAC A 1;
		Loop;

		Death:
			EXPL A 0 A_Explode (2, 120, 0);
			TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			XXXX A 0 Radius_Quake (4, 24, 0, 15, 0);
			TNT1 a 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (0.9, 0.9) );
			TNT1 A 0 A_SpawnItem("WhiteShockwaveSmall");
			TNT1 A 0 A_PlaySound("FAREXPL");
			//TNT1 AAAAAAAA 4 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		Stop;
	}
}

CLASS SuperMastermindTracer: MastermindTracer { 
	Default {
		damagefunction (random(25,30));
		Height 24;
	}
}