
CLASS HalfArchVile1 : ACTOR { 
	Default {
		
		Radius 1;
		Height 8;
		Speed 8;
		Scale 1.5;
		Mass 1;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			VIGP A 4 A_SpawnProjectile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			VIGP B 1;
			VIGP B -1;
		Splash:
			TNT1 A 1;
			Stop;
	}
}

CLASS HalfArchVile2 : ACTOR { 
	Default {
		
		Radius 1;
		Height 8;
		Speed 8;
		Scale 1.5;
		Mass 1;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			VIGP C 4 A_SpawnProjectile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			VIGP D 1;
			VIGP D -1;
		Splash:
			TNT1 A 1;
			Stop;
	}
}


CLASS FatalizedArchVile1: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			AVF1 Z 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			AVF1 Z -1;
			Stop;
	}
}


CLASS XDeathArchVile : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			VILP A 4 A_SpawnProjectile("BloodTrails",0,0,180,2);
			Goto Death;
		Death:
			VILP B 0;
			VILP B 0 A_SpawnItem("GibArchVile",0,0,0,1);
			Stop;
	}
}

CLASS GibArchVile: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			VILP B 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
	}
	
}
CLASS XDeathArchVileLeg : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			VILP C 4 A_SpawnProjectile("BloodTrails",0,0,180,2);
			Goto Death;
		Death:
			VILP C 1;
			VILP C 9009;
			Stop;
	}
}


CLASS Frozenarchvile : ACTOR { 
	Default {
		
		+SOLID
		+SHOOTABLE
		+NOBLOOD
		+PUSHABLE;

		Radius 20;
		Height 56;
		Health 60;
	}
	States
	{
		Spawn:
			FZDB A 200;
			FZDB A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZDB A 50;
			FZDB B 2;
			FZDB A 50;
			FZDB B 2;
			FZDB A 50;
			FZDB B 2;
			FZDB A 25;
			FZDB B 2;
			FZDB A 25;
			FZDB B 2;
			FZDB A 10;
			FZDB B 2;
			FZDB A 10;
			FZDB B 2;
			FZDB A 10;
			FZDB BABABA 2;
			
		Death.Fire:
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_spawnItem("archvile");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("MuchBlood", 48, 0, random (0, 360), 2, random (0, 160));
			FZDB C 300;
			FZDB CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
		Stop;
	}
}
