CLASS HalfArchVile1 : doomb_body_base
{ 
	Default
	{
		Radius 1;
		Height 8;
		Speed 8;
		Scale 1.5;
		Mass 1;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 AAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			VIGP A 4;
		Loop;
		
		Death:
			TNT1 AAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			VIGP B -1;
		Splash:
			TNT1 A 1;
		Stop;

		Raise:
		stop;
	}
}

CLASS HalfArchVile2 : doomb_body_base
{ 
	Default {
		Radius 1;
		Height 8;
		Speed 8;
		Scale 1.5;
		Mass 1;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 AAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			VIGP C 4;
			Loop;
		Death:
			TNT1 AAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			VIGP D 1;
			VIGP D -1;
		Splash:
			TNT1 A 1;
			Stop;
		Raise:
		stop;
	}
}


CLASS FatalizedArchVile1: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			AVF1 Z 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			AVF1 Z -1;
			Stop;
		Raise:
		stop;
	}
}

CLASS GibArchVile: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			VILP B 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Raise:
		stop;
	}
	
}
CLASS Frozenarchvile : doomb_body_base { 
	Default {
		
		+SOLID
		+SHOOTABLE
		+NOBLOOD
		+PUSHABLE;

		Radius 20;
		Height 56;
		Health 60;
	}
	States
	{
		Spawn:
			FZDB A 200;
			FZDB A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZDB A 50;
			FZDB B 2;
			FZDB A 50;
			FZDB B 2;
			FZDB A 50;
			FZDB B 2;
			FZDB A 25;
			FZDB B 2;
			FZDB A 25;
			FZDB B 2;
			FZDB A 10;
			FZDB B 2;
			FZDB A 10;
			FZDB B 2;
			FZDB A 10;
			FZDB BABABA 2;
			
		Death.Fire:
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_spawnItem("archvile");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 	doomb_for_khorne("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
			TNT1 AAAAA 0 doomb_much_blood();
			FZDB C 300;
			FZDB CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
		Stop;
		Raise:
		stop;
	}
}
