CLASS SergeantAmmo : Inventory { 
	Default {
		
		inventory.maxamount 6;
	}
}


CLASS doomb_shotgun_guy : doomb_monster_base Replaces ShotgunGuy { 
	Default {
		
		doomb_monster_base.headshot_multiplier 2;
		doomb_monster_base.head_starting_position 50;
		doomb_monster_base.legs_height_max 10;
		doomb_monster_base.weapon_type "Shot_Gun";

		Height 56;
		Radius 16;
		health 50;
		Mass 300;
		Speed 6;
		FastSpeed 12;
		Scale 0.98;

		PainChance 200;
		PainChance "Kick", 255;
		PainChance "Melee", 255;
		PainChance "HelperMarineFatality", 255;
		PainChance "Explosive_Impact", 255;
		damagefactor "Crush", 5.0;
		PainChance "Taunt", 255;
		damagefactor "SSG", 50.0;

		DropItem "GrenadeAmmo", 15;
		damagetype "Melee";

		Monster;
		+DONTHARMCLASS
		+DONTHARMSPECIES
		+FLOORCLIP;
		+SLIDESONWALLS;
		+RANDOMIZE;

		BloodType "Brutal_Blood",  "SawBlood";
		SeeSound "grunt/sight";
		PainSound "grunt/pain";
		DeathSound "grunt/death";
		ActiveSound "grunt/active";
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "taunt", 0.0;
		damagefactor "cut", 0.7;
		damagefactor "saw", 0.7;
		damagefactor "Explosive_Impact", 2.5;
		Obituary "%o got his face splattered on the wall by a Zombie Shotgunner.";
		MaxStepHeight 24;
		MaxDropOffHeight 32;
	}
	States
	{
		
		Avoid: 
			SPOS A 1 A_FaceTarget;
			TNT1 A 0 
			{
				int i = randompick(90. -90);
				vel.xy += (10 * sin(angle + i), 10 * cos(angle + i) );
			}
			ZRO3 ABCDEFGH 2 A_FaceTarget;
		Goto Missile;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_TakeInventory("SergeantAmmo", 6);
			TNT1 A 0 A_GiveInventory("SergeantAmmo", random(0,5));
			SPOS B 1;
			Goto Stand;
		Stand:
			SHID ABABABABAB 10 A_Look;
			Loop;
			
		FallBack:
			TNT1 A 0 A_CheckSight("Advance");
			TNT1 A 0 {bNODROPOFF = true;}
			SPOS DDCCBBAA 2
			{
				A_FaceTarget();
				A_Recoil(2);
			}
			TNT1 A 0 {bNODROPOFF = false;}
		GOto Missile;
			

		SearchForPlayer:
		Idle:
			TNT1 A 0 A_ClearTarget;
			SHID ACADAA 10 A_Look;
			SPOS AABBCCDD 4
			{
				A_Look();
				A_Wander();
			}
		Loop;
			
			
		See:
			TNT1 A 0 {bNODROPOFF = false;}
			TNT1 A 0 A_CheckSight("SeeNeverSeen");
			Goto SeeContinue;
			
		SeeContinue:
			TNT1 A 0 {bNODROPOFF = false;}
			TNT1 A 0 A_JumpIfCloser(200, "FallBack");
			TNT1 A 0 A_JumpIfHealthLower(1, "Death");
			SPOS AAAABBBBCCCCDDDD 2 A_Chase;
			TNT1 A 0 doomb_update_memory();
			TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "Idle");
		Loop;
			
		SeeNeverSeen:
			TNT1 A 0 A_JumpIfCloser(200, "FallBack");
		Advance:
			TNT1 A 0 {bNODROPOFF = false;}
			SPOS AA 2 A_Chase;
			SPOS BBCCDD 2 A_Chase;
		Loop;
			
		Missile:
			TNT1 A 0 doomb_update_memory();
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_JumpIfHealthLower(1, "Death");
			
			TNT1 A 0 {bNODROPOFF = false;}
			SPOS D 3 A_FaceTarget;
			TNT1 A 0 A_GiveInventory("SergeantAmmo", 1);
			
			SPOS D 3 A_FaceTarget;
			SPOS E 10 A_FaceTarget;
			SPOS E 4 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 34, 10, 15, 0);
			TNT1 AAAAA 0 A_SpawnProjectile("ShotgunguyTracer", 36, 0, random(-7, 7), CMF_OFFSETPITCH, frandom(-5, 5) );
			TNT1 AAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 36), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			TNT1 A 0 A_PlaySound("weapons/sg");
			SPOS F 5 BRIGHT;
			TNT1 A 0 A_Recoil(1);
			SPSR C 6;
			SPOS E 7 A_FaceTarget;
			SPSR A 7 A_PlaySound("weapons/sgpump");
			SPSR B 7 A_SpawnItem ("ShotCaseSpawn", 0, 30,0);
			SPSR A 7 A_JumpIfInventory("SergeantAmmo", 6, "Reload");
			TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "SearchForPlayer");
		Goto SeeContinue;
			
		Reload:
			SPSR A 15;
			ID12 EFG 5;
			TNT1 A 0 A_PlaySound("insertshell");
			TNT1 A 0 A_TakeInventory("SergeantAmmo", 1);
			tnt1 a 0 a_jump(200, "reload");
			SPSR A 10 A_PlaySound("weapons/sgpump");
			SPSR BA 10;
		Goto SeeContinue;
			
			
			
		Pain:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, 9);
			SPOS G 5;
			SPOS G 5 A_Pain;
			TNT1 A 0 A_Jump(196, "Missile");
		Goto SeeContinue;
			TNT1 AAAAA 0;
			TNT1 A 0 A_Pain;
			ID11 H 6;
		Goto GetUp;
			
		Pain.punch:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, 6);
			SPOS G 4;
			SPOS G 4 A_Pain;
			Goto SeeContinue;
			TNT1 AAAAA 0;
			TNT1 A 0 A_Pain;
			ID11 H 8;
			ID11 S 35;
			TNT1 A 0 A_TakeInventory("IsDown", 1);
			ID11 T 10;
			Goto SeeContinue;
			
		Pain.Explosive_Impact:
			TNT1 A 0 {bNODROPOFF = false;}
			TNT1 A 0;
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			TNT1 A 0 A_GiveInventory("IsDown", 1);
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			SPO4 UUVWXY 4;
			Goto FallingAfterImpact;
			
			
			
			
			
		Pain.Kick:
		Pain.HeavyImpact:
			TNT1 A 0;
			TNT1 A 0 {bNODROPOFF = false;}
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			ID11 G 1 A_Pain;
			TNT1 A 0 A_GiveInventory("IsDown", 1);
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 {bNOPAIN = true;}
			SPO4 U 1 A_facetarget;
			SPO4 U 3;
			SPO4 UVWXY 3;
			TNT1 A 0 {bNOPAIN = false;}
			
		FallingAfterImpact:
			ID11 H 1 A_GiveInventory ("FallingHeight", 1);
			ID11 H 1 A_CheckFloor ("GetUp");
			tnt1 A 0 A_JumpIf (vel.z == 0, "GetUp");
			Loop;
			
		GetUp:
			TNT1 A 0;
			TNT1 A 0 A_GiveInventory("IsDown", 1);
			TNT1 A 0 {if(waterlevel > 1) A_SpawnItem("LargeMassWaterImpact");}
			TNT1 A 0 {bFORCEXYBILLBOARD = true;}
			TNT1 A 0 {bSOLID = false;}
			TNT1 A 0 {bNOPAIN = false;}
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 4, "FallingDie");
			ID11 SSSSSSSSS 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
			TNT1 A 0 A_TakeInventory("FallingHeight", 100);
			
			ID11 T 10;
			TNT1 A 0 A_TakeInventory("IsDown", 1);
		Goto SeeContinue;
			
		FallingDie:
			TNT1 A 0;
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 15, "Death.Stomp");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 10, "FallingSuperDeath");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 4, "FallingDeath");
			
		FallingDeath:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBLocking;
			TNT1 A 0 A_Stop;
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
			ID11 EF 2;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadShotgunguy");
			Stop;
			
		FallingSuperDeath:
			TNT1 A 0;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBLocking;
			TNT1 A 0 doomb_spawn_bloodpool();
			Goto Death.Explosive_Impact+1;
			
		Death.Shotgun:
			TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
			TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
			
			TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
			Goto Death;
			
		Death.Shotgunontheface:
		Death.HeavyImpact:
			TNT1 A 0;
			TNT1 A 0 {bSLIDESONWALLS = false;}
			TNT1 A 0 A_Jump(24, "Death.ARm");
			TNT1 A 0 A_Jump(128, "DeathShotgunFly");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_Pain;
			SPOS H 1 A_FaceTarget;
			TNT1 A 0 A_Recoil(13);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
			SPO4 ABCD 4;
			SPO4 EFGHIJ 4 A_JumpIf((vel.Y == 0), "DSFStop");
			Goto DSFStop+1;
			
		DSFStop:
			TNT1 A 0 A_SpawnItem("Ploft3");
			TNT1 A 0 A_Stop;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnProjectile ("WallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
			TNT1 A 0 A_SpawnItem("DeadShotgunguySPO4J");
			Stop;
			
		DeathShotgunontheface2:
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_Pain;
			SPOS H 1 A_FaceTarget;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_Recoil(13);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
			SPO4 KLMN 4;
			SPO4 OPQRST 4 A_JumpIf((vel.Y == 0), "DSFStop2");
			Goto DSFStop2+1;
			
		DSFStop2:
			TNT1 A 0 A_SpawnItem("Ploft3");
			TNT1 A 0 A_Stop;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnProjectile ("WallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
			TNT1 A 0 A_SpawnItem("DeadShotgunguySPO4J");
			Stop;
			
		DeathShotgunFly:
			TNT1 A 0 {bNODROPOFF = false;}
			TNT1 A 0 {bSLIDESONWALLS = false;}
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (6);
			SPO4 U 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			SPO4 U 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			SPO4 V 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			SPO4 W 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
			SPO4 X 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
			SPO4 Y 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("Deaddoomb_shotgun_guy");
			Stop;
		TakeASit:
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
			SPO4 U 5;
		TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItemEx("DeadShotgunguy_Slumped", 10);
			Stop;
			
		Death.Eat:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_GiveToTarget("SergeantFatality",1);
			Stop;
			
		Death.ShotgunonthefaceArm:
			TNT1 A 0;
			TNT1 A 0 A_Jump(128, "Death.Arm");
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			ID11 OP 15;
			SPO5 E -1 doomb_final_absolution(12, 12);
			Stop;
			
		Death.punch:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		Death.Kick:
			TNT1 A 0 {bNODROPOFF = false;}
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (8);
			SPO4 UUVWXY 4;
			TNT1 A 0 A_SpawnItem("DeadShotgunguy");
			Stop;
			
			
			
		Death:
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
			
			TNT1 A 0 A_Jump(96, "Death.Arm");
		Death.MinorLeg:
			TNT1 A 0 A_Jump(48, "Death.Leg");
			SPOS H 5 A_Scream;
			SPOS I 5;
			SPOS J 5 A_NoBlocking;
			SPOS K 5;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadShotgunguy");
			Stop;
			
		Death.Down:
		Death.Trample:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 2, 0, random (0, 360), 2, random (0, 40));
			ID11 H 12;
			TNT1 A 0 A_SpawnItem("DeadShotgunguy");
			Stop;
			
		Death.Leg:
			TNT1 A 0 A_SpawnProjectile ("XDeathSargeLeg1", 35, 0, random (0, 360), 2, random (0, 160));
			SPO3 A 9 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Playsound ("grunt/death");
			SPO3 B 3;
			SPO3 C 3 A_NoBlocking;
			TNT1 A 0 A_SpawnItemEx ("SergeantGotHisLegBlowed",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		LeaveCrawling:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx ("DyingSergeantNoLeg",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0;
			Stop;
			
		Death.Arm:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
			SPO5 A 9 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItemEx ("DyingSergeant",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		Death.Headshot:
			TNT1 A 0 A_Jump(126, "headshot_1");
			TNT1 A 0 A_JumpIfHealthLower(-200, "HeavyHead");
			TNT1 A 0 A_JumpIfHealthLower(-50, "Death.HeadExplode");
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_Jump(100, "death_headshot_1");
			TNT1 A 0 A_Jump(42, "death_headshot_2");
			TNT1 AAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 50 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 40, 0, random (100, 130), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (90, 110), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (100, 130), 2, random (0, 160));
			TNT1 A 0 A_Scream;
			SPOS TTTTUU 2 A_SpawnProjectile ("Brutal_LiquidBlood", 40, 0, 120, 2, random (0, 60));
			SPOS VVV 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, 120, 2, random (60, 120));
			TNT1 A 0 A_NoBlocking;
			SPOS XXXYYY 2 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, random (0, 360), 2, random (60, 120));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadShotgunGuy_NoBrain");
			Stop;
			
		death_headshot_2:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("DyingShotgunguyHitInEye");
			Stop;
			
		death_headshot_1:
			13DG J 6
			{
				A_SpawnProjectile ("MuchBlood", 40, 0, random (0, 360), 2, random (0, 160));
				A_Pain();
				A_FaceTarget();
				A_SpawnProjectile ("head_piece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
				A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
			}
			13DG KL 8;
			
			TNT1 A 0 A_Scream;
			13DG M 6 A_NoBlocking;
			
			TNT1 A 0 doomb_spawn_bloodpool();
			13DG N -1 doomb_final_absolution(12, 12);
		Stop;
			
			
		Death.headExplode:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_JumpIfInTargetInventory("HeavyStrikeUpward", 1, "HeavyHead");
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode", 0, 50);
			SPDH AAAAABBBBBBBBBBCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (60, 120));
			SPDH DDDDEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (60, 120));
			SPDH EEEEEEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 5, 0, random (0, 360), 2, random (10, 40));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadShotgunGuy_NoHead");
			Stop;
			
		HeavyHead:
			TNT1 A 0 A_ClearTarget;
			SOSL G 1 A_Chase(null, null);
			SOSL G 1 A_Pain;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil(10);
			TNT1 A 0 ThrustThingZ(0,35,0,1);
			TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (10, 170));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("jaw", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("eye", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_piece", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("BrainsSergeantHeadPiece", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			SOSL GHIJK 6;
			SOSL LLLLLLLLLLLLLLLLLLL 4 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (10, 40));
			SOSL L -1;
			Stop;
			
		headshot_1:
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Blood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_SpawnProjectile ("XDeathSergeantHead", 50, 0, random (0, 360), 2, random (40, 90));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			SPDH AAAAABBBBBBBBBBCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (60, 120));
			SPDH DDDDDDEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (60, 120));
			SPDH EEEEEEEEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 5, 0, random (0, 360), 2, random (10, 40));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadShotgunGuy_NoHead");
			Stop;
			
		Death.Saw:
		Death.cut:
		Death.HKFT:
			TNT1 A 0;
			TNT1 A 0 A_Jump(96, "Death.Arm");
			Goto Death.Tear;
			
		Death.cutless:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
			TNT1 A 0 A_Jump(16, "Death");
			TNT1 A 0 A_Jump(32, "Death.Cut");
			TNT1 A 0 A_Jump(9, "Death.LegMassacre");
			TNT1 A 0 A_Jump(64, "Death");
			Goto Death.Minigun;
			
		Death.Tear:
			TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_XScream;
			TNT1 O 0 A_NoBlocking;
			SP2X AA 8;
			TNT1 A 0 A_SpawnProjectile ("XDeath4", 40, 0, random (0, 360), 2, random (0, 160));
			
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfSergeant", 32, 0, random (0, 360), 2, random (0, 160));
			
			SP2X BBCD 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadShotgunGuy_Half");
			Stop;
			
		Death.Minigun:
			TNT1 A 0;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Scream;
			TNT1 O 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("BrutalizedSergeant1", 1);
			Stop;
			
		Death.LegMassacre:
			TNT1 A 0;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Scream;
			TNT1 O 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("BrutalizedSergeantLeg", 1);
			Stop;
			
		Death.Blast:
		Death.Railgun:
			TNT1 A 0;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Jump(12, "Death.Arm");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(128, "Death.Blast2");
			TNT1 A 0 A_Scream;
			TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
			ZXZ7 A 6 A_Stop;
			TNT1 A 0 doomb_spawn_bloodpool();
			ZXZ7 BBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (30, 60));
			ZXZ7 CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (10, 40));
			ZXZ7 DD 3 A_SpawnProjectile ("Brutal_LiquidBlood", 6, 0, random (0, 360), 2, random (30, 60));
			TNT1 A 0 A_SpawnItem("DeadShotgunguyZXZ7E");
			Stop;
			
		Death.Blast2:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 42, 0, random (0, 360), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			TNT1 AA 0 A_SpawnProjectile ("Xdeath2", 16, 0, random (130, 210), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
			ZXZ6 A 6 A_Stop;
			TNT1 A 0 doomb_spawn_bloodpool();
			ZXZ6 BBBBBBBBBBBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (30, 60));
			ZXZ6 CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (10, 40));
			ZXZ6 DD 3 A_SpawnProjectile ("Brutal_LiquidBlood", 6, 0, random (0, 360), 2, random (30, 60));
			TNT1 A 0 A_SpawnItem("DeadShotgunguyZXZ6E");
			Stop;
			
		Death.SSG:
			SZD1 E 1 A_Pain;
			SZD1 E 1 A_FaceTarget;
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 35, 0, random (170, 190), 2, random (0, 40));
			//TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160))
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
			TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 A 0 A_SpawnProjectile ("XDeathSergeantHead", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			SZD1 EEFFGH 6;
			TNT1 A 0 doomb_spawn_bloodpool();
			SZD1 H -1;//doomb_final_absolution(12, 12);
			Stop;
			
	Death.Plasma: Death.Plasma2:
		PBR1 A 6 A_Scream;
		TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 doomb_show_effect("BluePlasmaFire", (0, 0, 32), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		PBR1 B 6 A_NoBlocking;
		PBR1 CDEFGH 6 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		PBR1 HHHHHHHHHHHHHHHHHHHHHH 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		PBR1 H -1;
		Stop;
		
		
	Death.HelperMarineFatallity:
	Death.BHFT:
	Death.RVFT:
		TNT1 A 0;
		TNT1 A 1 A_Pain;
		TNT1 A 0 A_Chase(null,null);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking       ;
		TNT1 A 0 A_GiveToTarget("SergeantFatality", 1);
		Stop;
		
	Death.fire:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("BurningZombieMan", 0, 7);
		TNT1 A 0 A_SpawnItem("BurningShotgunguy", 0, 10);
		Stop;
		
	XDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("SargeXDeath", 0, 0, random (0, 360), 2, random (0, 160));
		Stop;
		
	Crush:
	Death.Stomp:
	Death.Stomp:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		SPOS IJK 2;
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
		Stop;
		
	Death.Explosive_Impact:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget;
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(angle < 180, "IsFacingNorth");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayLeft");
	Goto XDeath;
	
	IsFacingNorth:
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayLeft");
		Goto XDeath;
		
	BlownAwayLeft:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Xscream;
		SXSX GHIJKLM 3 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
		TNT1 A 0 A_CheckFloor("Land8473");
		SXSX GHIJKLMGHIJKLM 5 A_CheckFloor("Land8473");
	Land8473:
		SXSX N 0;
		TNT1 A 0 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem("DeadSergeantSXSXO");
		Stop;
		
	BlownAwayRight:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Jump(96, "Death.Hammered");
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItemEx("BloodMist", 0, 0, 50, vel.x, vel.y, vel.z, 0, SXF_ABSOLUTEvelOCITY);
		SXS2 GHIJKLM 3 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
		TNT1 A 0 A_CheckFloor("Land8472");
		SXS2 GHIJKLMGHIJKLM 5 A_CheckFloor("Land8472");
	Land8472:
		SXS2 N 0;
		TNT1 A 0 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem("DeadSergeantSXS2O");
		Stop;
		
	Death.Hammered:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathSargeLeg2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID14 AB 5;
		ID14 CDEF 5 A_CheckFloor ("Dead.Explosive_Impact");
		ID14 FFFFFF 5 A_CheckFloor ("Dead.Explosive_Impact");
		TNT1 A 0 A_SpawnItem ("VeryFuckedUpBrutalizedSergeantLeg");
		Stop;
		
	Dead.Explosive_Impact:
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("VeryFuckedUpBrutalizedSergeantLeg");
		TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 A 0 A_SpawnItem ("MuchBlood");
	Stop;
	
	Raise:
		SPOS LKJIH 5;
	Goto SeeContinue;
		
		
	////////////////////////////////////////////////////////////
	//			backstab from player
	////////////////////////////////////////////////////////////
	death.back_stab: 
		TNT1 A 0
		{
			if(is_melee_player_kill() )
				setstate(curstate+1);
		}
	Goto Death;
		tnt1 a 0
		{
			doomb_monster_fatality_camera(target);
			vel = (0, 0, 0);
		}
		SFSZ AB 8;
		SFSZ C 16;
		tnt1 A 0 A_PlaySound("misc/xdeath4");
		SFSZ D 16;
		tnt1 A 1
		{
			A_SpawnItemEx("DeadShotgunGuy");
			doomb_destroy_monster_fatality_camera();
		}
	Stop;


	Death.Fatality:
		tnt1 A 0
		{
			doomb_monster_fatality_camera(target);
			A_Pain();
			A_NoBlocking();
		}
		TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(256, "sergeant_fatality_1", "sergeant_fatality_2", "sergeant_fatality_3");
		
	sergeant_fatality_1:
		FTYS A 6 A_PlaySound("grunt/pain", CHAN_AUTO, 1);
		FTYS BC 6;
		tnt1 A 0 A_PlaySound("BURNZOM", 3);
		
		tnt1 A 0 A_PlaySound("misc/xdeath", CHAN_AUTO, 1);
		FTYS DE 4;
		tnt1 A 0 A_PlaySound("misc/xdeath", CHAN_AUTO, 1);
		FTYS DE 3;
		tnt1 A 0 A_PlaySound("misc/xdeath", CHAN_AUTO, 1);
		FTYS DEE 2;
		
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 A_PlaySound("misc/xdeath", 3);
		tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("BloodMist", 30, 0, random (0, 360), 2, random (20, 90));
		FTYS FGHIIPPP 2 A_SpawnProjectile ("Blood", 1, 0, random (0, 360), 2, random (0, 160));
		
		FTYS QR 5;
		tnt1 A 0 A_SpawnItemEx("FootStep", 0, 0, 40, 0, 0);
		FTYS R 15;
		tnt1 A 0 
		{
			A_Givetotarget("HealthBonus",10);
			A_SpawnProjectile ("DeadShotgunGuy_NoHead", 1, 0, random (0, 360), 2, random (0, 160));
			doomb_destroy_monster_fatality_camera();
		}
	stop;
	
	sergeant_fatality_2:
		tnt1 A 0
		{
			doomb_monster_fatality_camera(target);
			A_Pain();
			A_NoBlocking();
		}

		FTYS J 3;
		FTYS J 1 A_PlaySound("BURNZOM", CHAN_AUTO, 1);
		FTYS JJJJ 3;
		FTYS J 1 A_PlaySound("grunt/death", CHAN_AUTO, 1);
		FTYS K 4;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 20, 0, random (0, 360), 2, random (0, 160));
		tnt1 AA 0 A_SpawnProjectile ("XDeath2", 20, 0, random (0, 360), 2, random (0, 160));
		tnt1 AA 0 A_SpawnProjectile ("XDeath3", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("BloodMist", 50, 0, random (0, 360), 2, random (20, 90));
		
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfSergeant", 32, 0, random (0, 360), 2, random (0, 160));
		
		FTYS LMNO 3;
		FTYS O 10;
		tnt1 A 0 
		{
			doomb_spawn_bloodpool();
			A_Givetotarget("HealthBonus",10);
			A_SpawnProjectile ("DeadShotgunguy_Half", 1, 0, random (0, 360), 2, random (0, 160));
			doomb_destroy_monster_fatality_camera();
		}
	stop;
	
	
	sergeant_fatality_3:
		FSP3 A 4;
		FSP3 B 4 A_PlaySound("grunt/pain");
		TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
		FSP3 CDE 2;
		FSP3 E 6;
		FSP3 FG 3;
		tnt1 A 0 A_PlaySound("grunt/death");
		TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 20, 0, random (0, 360), 2, random (0, 160));
		//tnt1 AA 0 A_SpawnProjectile ("XDeath2", 20, 0, random (0, 360), 2, random (0, 160))
		//tnt1 AA 0 A_SpawnProjectile ("XDeath3", 20, 0, random (0, 360), 2, random (0, 160))
		TNT1 AAA 0 A_SpawnProjectile ("BloodMistSmall", 30, 0, random (0, 360), 2, random (20, 90));
		FSP3 HIIIIII 3;
		tnt1 A 0 A_PlaySound("weapons/sg");
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 AAAAA 0 A_SpawnProjectile ("XDeath1", 70, 0, random (0, 360), 2, random (0, 160));
		tnt1 AA 0 A_SpawnProjectile ("XDeath2", 70, 0, random (0, 360), 2, random (0, 160));
		tnt1 AA 0 A_SpawnProjectile ("XDeath3", 70, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("BloodMist", 80, 0, random (0, 360), 2, random (20, 90));
		tnt1 A 0 A_SpawnProjectile ("FlyingImpaledSergeant", 50, 0, random (0, 360), 2, random (70, 110));
		FSP3 L 3 BRIGHT;
		FSP3 K 3;
		FSP3 J 10;
		tnt1 A 0 
		{
			A_Givetotarget("HealthBonus",10);
			doomb_destroy_monster_fatality_camera();
		}
	stop;
}
}


CLASS SergeantFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS SergeantFatality2 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS SergeantFatality3 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}
