
CLASS XDeathHalfShotgunguyNoArmNoHead : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.3;
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			SPSX GHIJKLMN 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			SPSX O -1;//doomb_final_absolution(12, 12);
			Stop;
	}
}




CLASS XDeathHalfSergeant : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 7;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			SP2X F 12 A_SpawnProjectile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			SP2X G 0 A_SpawnItem("GibHalfSergeant",0,0,0,1);
			Stop;
	}
}




CLASS GibHalfSergeant: BigGibBase { 
	Default {
		
		
	}
	States
	{
		Spawn:
			SP2X G 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop   ;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathSergeantHead", 32, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
	}
	
}



CLASS Deaddoomb_shotgun_guy: CurbstompedMarine Replaces DeadShotgunguy { 
	Default {
		
		Radius 12;
		Height 12;
		+SHOOTABLE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		+FLOORCLIP;
		-SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Mass 6000;
		Health 300;
		damagefactor "Blood", 0.0;
		PainChance "Melee", 255;
		damagefactor "Trample", 0.0;
		damagefactor "Explosive_Impact", 10.0;
	}
	States
	{
		Spawn:
			SPOS L -1;
			Stop;
		Raise:
			SPOS K 1;
			SPOS JIH 1;
			TNT1 A 0 A_SpawnItem ("doomb_shotgun_guy", 3);
			Stop;
		Death:
			TNT1 A 0 A_SpawnProjectile ("XDeathSargeLeg1", 5, 0, random (0, 360), 2, random (0, 160));
			SPOS A 0 doomb_Meat_Death_Small();
			TNT1 A 1 A_SpawnItem ("DeadShotgunGuy_NoLeg", 5);
			Stop;
			
		Death.Plasma:
		Death.Plasma2:
			TNT1 A 0;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_spawn_burned_flesh;
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0;
			Stop;
			
	}
}


CLASS DeadShotgunGuy_NoLeg: Deaddoomb_shotgun_guy  { 
	Default {
		
		health 300;
	}
	States
	{
		Spawn:
			SPO3 F -1;
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathSargeLeg1", 5, 0, random (0, 360), 2, random (0, 160));
			SPOS A 0 doomb_Meat_Death_Small();
			TNT1 A 1 A_SpawnItem ("DeadShotgunGuy_NoLegBoth", 5);
			Stop;
	}
	
}


CLASS DeadShotgunGuy_NoLegBoth: Deaddoomb_shotgun_guy  { 
	Default {
		
		health 300;
	}
	States
	{
		Spawn:
			SPO3 K -1;
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			SPOS A 0 doomb_Meat_Death_Small();
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 5, 0, random (0, 360), 2, random (0, 160));
			
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfSergeant", 32, 0, random (0, 360), 2, random (0, 160));
			
			Stop;
	}
}		


CLASS DeadShotgunGuy_NoHead: CurbstompedMarine  { 
	Default {
		
		health 300;
	}
	States
	{
		Spawn:
			SPDH E -1;
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			SPOS A 0 doomb_Meat_Death_Small();
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem("DeadShotgunGuy_NoHeadNoArm");
			Stop;
	}
	
}

CLASS DeadShotgunGuy_NoHeadNoArm: Deaddoomb_shotgun_guy { 
	Default {
		
		health 300;
	}
	States
	{
		Spawn:
			SPXS B -1;
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking;
			SPOS A 0 doomb_Meat_Death_Small();
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 5, 0, random (0, 360), 2, random (0, 160));
			SZD3 C -1;//doomb_final_absolution(12, 12);
			Stop;
			
	}
	
}
CLASS DeadShotgunGuy_Half: Deaddoomb_shotgun_guy { 
	Default {
		
		health 300;
	}
	States
	{
		Spawn:
			SP2X E -1;
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			SPOS A 0 doomb_Meat_Death_Small();
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 5, 0, random (0, 360), 2, random (0, 160));
			SZD1 H -1;//doomb_final_absolution(12, 12);
			Stop;
	}
	
}






CLASS DeadShotgunguy_Slumped: CurbstompedMarine { 
	Default {
		
		Scale 0.98;
		Mass 6000;
		damagefactor "Crush", 50.0;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		//+NORADIUSDMG
		+NOPAIN;
		+CORPSE;
		+NOPAIN;
		Health 200;
	Height 22+15;
	doomb_monster_base.head_starting_position 22;
		Radius 6;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(6);
			BR93 A 6;
			TNT1 A 0 A_JumpIf(vel.z == 0, "LayDown");
			BR93 A 16;
			Loop ;
		LayDown:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("Deaddoomb_shotgun_guy");
			Stop;
		XDeath:
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("SargeXDeath");
			Stop;
			
		Death.Headshot:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItemEx("ShotgunguyHeadExplode", 0, 0, 22);
			TNT1 A 0 A_SpawnItem("DeadShotgunguy_Slumped_NoHead");
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 40, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_SpawnItemEx("ShotgunguyHeadExplode", 0, 0, 22);
		Stop;
			
	}
	
}		
		
CLASS DeadShotgunguy_Slumped_NoHead: CurbstompedMarine { 
	Default {
		
		
		Radius 12;
		Scale 0.98;
		Mass 6000;
		damagefactor "Crush", 50.0;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		//+NORADIUSDMG
		+NOPAIN;
		+CORPSE;
		+NOPAIN;
		Height 22;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			BR93 B 100;
			Loop ;
		XDeath:
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("SargeXDeath");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 40, 0, random (0, 360), 2, random (30, 90));
		Stop;
	}
}		
		
		
CLASS DeadSergeantSXSXO: Deaddoomb_shotgun_guy { 
	States
	{
		Spawn:
			SXSX O -1;
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 A 0 doomb_Rip_Guts();
			TNT1 A 0 A_SpawnProjectile ("XDeathSargeLeg2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathaRM1", 32, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
	}
}		


	
CLASS DeadSergeantSXS2O: Deaddoomb_shotgun_guy { 
	Default {
		
	}
	States
	{
		Spawn:
			SXS2 O -1;
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 A 0 doomb_Rip_Guts();
			TNT1 A 0 A_SpawnProjectile ("XDeathSargeLeg2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathaRM1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("ShotgunguyHeadExplode", 32, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
	}
}	




CLASS DeadShotgunguySPO4J: Deaddoomb_shotgun_guy { 
	Default {
		
	}
	States
	{
		Spawn:
			SPO4 J -1;
			Stop;
			
		Death:
			TNT1 A 0 doomb_Meat_Death_Small();
			
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfSergeant", 32, 0, random (0, 360), 2, random (0, 160));
			
			TNT1 A 0 A_SpawnItem("DeadShotgunguy_Half");
			Stop;
			
	}
}	



CLASS DyingShotgunguyHitInEye: doomb_body_base { 
	Default {
		
		Radius 12;
		Height 32 + 15;
		doomb_monster_base.head_starting_position 35;

		Speed 0;
		Health 40;
		-COUNTKILL;
		+GHOST;
		+THRUGHOST;
		+NOPAIN;
	}
	States
	{
		Spawn:
			TNT1 AAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 50 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
			SPOS U 6 A_Playsound("grunt/pain", 3);
			SPOS V 6;
			SPOS VWVW 18 A_Playsound("grunt/pain", 3);
			SPOS VW 18 A_Playsound("grunt/pain", 3);
			tnt1 a 0 a_die();
		Death:
			TNT1 A 0 A_NoBlocking;
			SPOS XY 6;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadShotgunGuy_NoBrain");
		Stop;
			
		Death.Headshot:
			TNT1 A 0 A_SpawnItem("CrueltyBonus1Health");
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_JumpIfInTargetInventory("HeavyStrikeUpward", 1, "HeavyHead");
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode", 0, 50);
			SPDH AAAAABBBBBBBBBBCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (60, 120));
			SPDH DDDDEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (60, 120));
			SPDH EEEEEEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 5, 0, random (0, 360), 2, random (10, 40));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadShotgunGuy_NoHead");
		Stop;

		Death.Shotgun:
			TNT1 A 0 {bNODROPOFF = false;}
			TNT1 A 0 {bSLIDESONWALLS = false;}
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (6);
			SPO4 U 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			SPO4 U 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			SPO4 V 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			SPO4 W 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
			SPO4 X 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
			SPO4 Y 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("Deaddoomb_shotgun_guy");
		Stop;
		
		Death.Cutless:
			TNT1 A 0 doomb_much_blood();
			TNT1 A 0 A_XScream;
			TNT1 O 0 A_NoBlocking;
			SP2X AA 8;
			TNT1 A 0 A_SpawnProjectile ("XDeath4", 40, 0, random (0, 360), 2, random (0, 160));
			
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfSergeant", 32, 0, random (0, 360), 2, random (0, 160));
			
			SP2X BBCD 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadShotgunGuy_Half");
		Stop;
	}
}

CLASS DeadShotgunGuy_NoBrain: Deaddoomb_shotgun_guy { 
	Default {
		
		health 300;
	}
	States
	{
		Spawn:
			SPOS Z -1;
			Stop;
			
		Death:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
			TNT1 A 0 A_SpawnItem ("DeadShotgunguy_NoHead", 1);
			Stop;
			
	}
	
}








CLASS DeadShotgunguyZXZ7E: Deaddoomb_shotgun_guy { 
	Default {
		
	}
	States
	{
		Spawn:
			ZXZ7 E -1;
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
			SZD3 C -1;//doomb_final_absolution(12, 12);
			Stop;
			
	}
}	


CLASS DeadShotgunguyZXZ6E: Deaddoomb_shotgun_guy { 
	Default {
		
	}
	States
	{
		Spawn:
			ZXZ6 E -1;
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
			SZD3 F -1;//doomb_final_absolution(12, 12);
			Stop;
			
	}
	
}



CLASS XDeathSergeantHead: LimbBase { 
	Default {
		
		
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			XHE1 AB 3;
			TNT1 A 0 {bTHRUSPECIES = false;}
			XHE1 CDEFGH 3;
			Loop;
		Death:
			XHE1 E 1;
			XHE1 E 1 A_SpawnItem("SergeantHead",0,0,0,1);
			Stop;
			
	}
}


CLASS XDeathSergeantHeadOnXDeath: XDeathSergeantHead { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
			Stop;
			
	}
	
}


CLASS SargeXDeath : doomb_body_base { 
	Default {
		
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
	States
	{
		Spawn:
			tnt1 a 0 A_Explode(3,600, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AAAAAAAAAAAAAAA 0 A_SpawnProjectile ("WallRedBlood", 40, 0, random (0, 360), 2, random (-15, 15));
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 0, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath2", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath3", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece1", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece1", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfShotgunguyNoArmNoHead", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathSargeLeg2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("GibSargeBoot", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathSergeantHeadOnXDeath", 32, 0, random (0, 360), 2, random (0, 160));
			tnt1 a 0 doomb_spawn_bloodpool();
			
			TNT1 A 1;
			TNT1 A 2;
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
			Stop;
	}
}


CLASS SergeantHead: LimbBase { 
	Default {
		
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			XHE1 C -1;
			Stop;
			
		Spawn2:
			XHE1 G -1;
			Stop;
			
		Spawn3:
			XHE1 H -1;
			Stop;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode");
			Stop;
		Death.Punch:
		Death.Kick:
			XHE2 EE 1 A_FaceTarget;
			TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
			TNT1 A 0 A_SpawnProjectile ("XDeathSergeantHead", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE1 ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE1 ABCDEFGH 3;
			XDT5 I 0 A_SpawnItem("SergeantHead");
			Stop;
			
			
	}
	
}

CLASS SergeantHeadThrown: XDeathSergeantHead { 
	Default {
		
		+BOUNCEONACTORS;
		Damagefunction (random (30, 40));
		DamageType "Kick";
		-CLIENTSIDEONLY;
		Speed 20;
		Gravity 0.4;
		wallbouncefactor 0.2;
	}
}


CLASS DyingSergeant : doomb_body_base { 
	Default {
		Radius 16;
		Height 28+18;
		doomb_monster_base.head_starting_position 28;

		Health 50;
		PainSound "grunt/pain";
		PainChance 255;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Leg", 0.0;
		damagefactor "Kick", 6.0;
		Mass 500;
		+SHOOTABLE;
		+FLOORCLIP;
		+DONTSPLASH;
		MONSTER;
		+FRIENDLY;//
		-COUNTKILL;
		+GHOST;
		+THRUGHOST;
		-SOLID;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			SPO5 A 1 A_Chase;
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_PlaySound ("BURNZOM");
			SPO5 AAAAA 2 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, 90, 2, random (0, 45));
			TNT1 A 0 A_Jump(16, "Death");
		Suffer:
			SPO5 BBBBBCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, 90, 2, random (0, 45));
			TNT1 A 0 A_Jump(12, "LastStand") ;
			TNT1 A 0
			{
				if(random(0, 10) > 7)
					a_die();
			}
		Loop;

		Death.Fatality:
		Death.punch:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("HasSguyShield", 1);
			TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
			Stop;
			
		Death.fire:
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("BurningZombie");
			Stop;
			
		Death.Cut:
		Death.Cutless:
		Death:
			SPO5 D 8;
			TNT1 A 0 A_PlaySound ("grunt/death");
			SPO5 E -1 doomb_final_absolution(12, 12);
			Stop;
			
		Death.Headshot:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_Jump(126, "headshot_1");
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode", 0, 30);
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 37, 0, random (0, 360), 2, random (0, 160));
			SZD4 AAAAA 2 A_SpawnProjectile ("Brutal_LiquidBlood", 25, 0, random (0, 360), 2, random (30, 110));
			SZD4 BBBBBBBBBBBBBBBBBBBBBBBBB 1 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (30, 110));
			SZD4 B -1 doomb_final_absolution(12, 12);
			Stop;
			
		headshot_1:
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("SmallSuperGore", 32, 0, random (0, 360), 2, random (10, 170));
			TNT1 A 0 A_SpawnProjectile ("XDeathSergeantHead", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 37, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_NoBlocking;
			SZD4 AAAAA 2 A_SpawnProjectile ("Brutal_LiquidBlood", 25, 0, random (0, 360), 2, random (30, 110));
			SZD4 BBBBBBBBBBBBBBBBBBBBBBBBB 1 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (30, 110));
			SZD4 B -1 doomb_final_absolution(12, 12);
			Stop;
			
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		XBRN AA 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_burned_flesh;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		XBRN BB 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 A 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
		TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(1.8, 2.2), 0) );
		TNT1 A 0;
	Stop;
		
	Xdeath:
	Death.punch:
	Death.Blast:
	Death.SSG:
	Death.Shotgun:
		TNT1 A 0 A_SpawnItem ("CrueltyBonus10Armor");
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Bloodmist", 30, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnItem ("Brutal_Blood", 0 , 40);
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathSergeantHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		SZD1 EFGH 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		SZD1 H -1 doomb_final_absolution(12, 12);
		Stop;
		
	LastStand:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_SpawnItem ("SergeantLastStand2");
		Stop;
		
}
}



CLASS DyingSergeantNoLeg : doomb_body_base { 
	Default {
	
	Radius 12;
	Height 22;

	Speed 9;
	Health 50;
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	+SHOOTABLE;
	+DONTSPLASH;
	+FLOORCLIP;
	//+NOBLOCKMAP
	+LOOKALLAROUND;
	+FRIGHTENED;
	+FRIENDLY;//
	+GHOST;
	+THRUGHOST;
	-SOLID;
	damagefactor "Kick", 6.0;
	damagefactor "trample", 2.0;
	PainChance "Kick", 255;
	damagefactor "Leg", 0.0;
	damagefactor "KickDowned", 100.0;
	}
    States
    {
	
	Pain.Kick:
		TNT1 A 0 A_SpawnProjectile ("Teeth", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("Blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem("CrueltyBonus1health");
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_FaceTarget;
		SMAK ABA 6;
		SMAM A 15;
		Goto See;
		
	Death.Kick:
	Death.punch:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_GiveToTarget("IsCurbstompingSergeant", 1);
		Stop;
		
	Death.Fatality:
	Death.punch:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("HasSguyShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		Stop;
		
	Spawn:
		SMAM A 1 A_Look;
		Loop;
	See:
		SMAM ABAB 10 A_Wander;
		SMAM A 9 A_Pain;
		TNT1 A 0 A_SpawnItemEx("Brutal_FlyingBlood", 0, 0, 10, 0, 0);
		TNT1 A 0 A_Jump(12, "LastStand");
		tnt1 a 0 doomb_random_death();
		Loop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("DeadShotgunGuy_NoLeg");
		Stop;
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS2 A -1;
		Stop;
		
		
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		XBRN AA 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_burned_flesh;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		XBRN BB 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 A 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
		TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(1.8, 2.2), 0) );
		TNT1 A 0;
	Stop;
	
	Death.Fire:
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 A 0 A_SpawnItem ("DyingSergeantNoLegInFlames");
	Stop;
	
	Death.Trample:	
		TNT1 A 0 doomb_much_blood(10);
		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("StompedSergeant");
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
	Stop;

	LastStand:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_SpawnItem ("SergeantLastStand1");
	Stop;
	
}
}



CLASS XDeathSargeLeg1: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG2 ABCDEFGH 5 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			Loop;
		Death:
			LEG2 A 1;
			LEG2 A 0 A_SpawnItem("Gib_SargeLeg");
			Stop;
	}
}

CLASS Gib_SargeLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			LEG2 A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma:
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
			Stop;
		Death:    
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnProjectile ("GibSargeLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("GibSargeBoot", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Punch:
			LEG2 A 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathSargeLeg1", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LEG2 ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			LEG2 ABCDEFGH 5;
			XDT5 I 0 A_SpawnItem("Gib_SargeLeg");
			Stop;
			
			
	}
	
}
CLASS GibSargeLegPart: TinyGib
{
	States
	{
		Spawn:
			LEG2 Z -11;
		Loop;
	}
}
CLASS GibSargeBoot: TinyGib { 
	States
	{
		Spawn:
			LEG2 Y -1;
		stop;
			
	}
}


CLASS XDeathSargeLeg2: XDeathArm1 { 
Default {
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG2 ABCDEFGH 5 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			Loop;
		Death:
			LEG2 E 1;
			LEG2 E 1 A_SpawnItem("Gib_SargeLeg2");
			Stop;
	}
}


CLASS BurningShotgunguy : doomb_body_base { 
	Default {
		
		Radius 12;
		Height 56;
		Speed 5;
		Scale 0.85;
		Health 100;
		GibHealth 25;
		damagefactor "Fire", 0.0;
		damagefactor "Explosive_Impact", 10.0;
		MONSTER;
		-COUNTKILL;
		+NOICEDEATH;
		+FRIENDLY;
		+FLOORCLIP;
		+SHOOTABLE;
		+NOBLOCKMONST;
		+DONTSPLASH;
		
		Gravity 0.7;
		bloodtype "DeadBlood";
		Obituary "%o was near someone in flames.";
		MaxDropOffHeight 6000;
		
		Mass 999999;
		
	}
	States
	{
		Spawn:
			BRZ1 B 0 doomb_show_effect("BurnParticles", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_PlaySound("BURNZOM");
		Suffer:
			BRZ3 AAABBB 1 BRIGHT
			{
				A_Wander();
				A_Recoil(-1);
				doomb_show_effect("BurnParticles", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
				doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
			}
			TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
			TNT1 A 0 doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 12, "Death");
			Loop;
			
			
		Death:
			TNT1 A 0 A_Fall;
			TNT1 A 0 {bSHOOTABLE = false;}
			TNT1 A 0 {bSOLID = false;}
			TNT1 A 0 {bNOTARGET = true;}
			
			TNT1 A 0 A_Jump(256, "Death1", "Death2", "Death3");
			Goto Death1;
			
		Death1:
			TNT1 A 0 A_PlaySound("BURNZOM");
			BRZ3 DDEEFFGG 3
			{
				doomb_show_effect("BurnParticles", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
				A_Wander();
			}
			tnt1 a 0 a_jump(200, "death1");
			BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 doomb_show_effect("BurnParticles", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BRZ3 H -1;
			Stop;
		Death2:
			BRZ3 DDEEFFGG 3
			{
				doomb_show_effect("BurnParticles", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
				A_Wander();
			}
			tnt1 a 0 a_jump(200, "death2");


			BRZ3 IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 3 doomb_show_effect("BurnParticles", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			BRZ3 IIIIIIIIIIIIIIIII 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BRZ3 I -1;
			Stop;
			
		Death3:
			TNT1 A 0 A_PlaySound("BURNZOM");
			BRZ3 DDEEFFGG 3
			{
				doomb_show_effect("BurnParticles", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
				A_Wander();
			}
			TNT1 A 0 A_SpawnItem("DyingSergeantNoLegInFlames");
		Stop;
	}
}


CLASS ShotgunguyHeadExplode: actor { 
	Default {
		
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("BrainsSergeantHeadPiece", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
			TNT1 A 10;
			Stop;
	}
}

CLASS DyingSergeantNoLegInFlames : doomb_body_base { 
	Default {
		
		Radius 12;
		Height 30;
		Speed 5;
		Health 20;
		PainSound "grunt/pain";
		DeathSound "grunt/death";
		+SHOOTABLE;
		+FLOORCLIP;
		//+NOBLOCKMAP
		+LOOKALLAROUND;
		+NOICEDEATH;
		+FRIGHTENED;
		-SOLID;
		
		damagefactor "Fire", 0.0;
	}
	States
	{
		
		Spawn:
			TNT1 A 0 A_Playsound("BurnZom");
			SMBM AABB 5
			{
				A_Chase();
				doomb_show_effect("BurnParticles", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			}
			tnt1 a 0 a_jumpif(random(0, 10) < 1, "death");
		Loop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 doomb_show_effect("BurnParticles", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			TNT1 A 0 {bSHOOTABLE = false;}
			BRZ3 H -1;
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS2 A 5;
			CRS2 A -1;
			Stop;
			
		Death.Stomp:
		Death.SSG:
		XDeath:
			TNT1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AAAAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AA 0 bright A_SpawnProjectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 AA 0 bright A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 A 0 A_SpawnItem ("CrushedRemains");
			TNT1 A 1;
			TNT1 A 0;
			TNT1 A 1 A_XScream;
			TNT1 A 1 A_NoBlocking;
			TNT1 A -1;
			Stop;
	}
}


CLASS Gib_SargeLeg2: Gib_SargeLeg { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			LEG2 E 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma:
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
			Stop;
		Death:    
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnProjectile ("GibSargeLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("GibSargeBoot", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Punch:
			LEG2 A 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathSargeLeg1", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
	}
	
}


CLASS DyingSergeantLegBlewedOff : DyingSergeantNoLeg { 
	Default {
 
	
	Radius 16;
	Height 28;
	Health 50;
	PainSound "grunt/pain";
	PainChance 255;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "Kick", 6.0;
	Mass 500;
	-SOLID;
	+SHOOTABLE;
	+GHOST;
	+THRUGHOST;
	}
	States
	{
		Death.Fatality:
		Death.punch:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("HasSguyShield", 1);
			TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
			Stop;
			
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_PlaySound ("BURNZOM");
			SPO3 CCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random(0, 180), 2, random (0, 35));
			TNT1 A 0 A_Jump(16, "Death");
			Goto Suffer;
			
		Suffer:
			SPO3 DDDDDEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random(0, 180), 2, random (0, 35));
			TNT1 A 0 doomb_blood_dying();
			TNT1 A 0 A_Jump(12, "LastStand");
			TNT1 A 0 doomb_random_death();
		Loop;
			
		Death.Cut:
		Death.Cutless:
		Death:
			SPO3 GH 6;
			TNT1 A 0 A_PlaySound ("grunt/death");
			TNT1 A 0 A_SpawnItem ("DeadShotgunGuy_NoLeg");
			Stop;
			
		Death.Headshot:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode", 0, 30);
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 37, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_NoBlocking;
			SPO3 IJ 6;
			TNT1 A 0 A_SpawnItem ("DeadShotgunguy_NoLeg", 1);
			Stop;
			
		Death.Shotgun:
			TNT1 A 0 doomb_much_blood(35);
			TNT1 A 0 A_Scream;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 A_NoBlocking;
			ID11 MN 15;
			TNT1 A 0 A_SpawnItem ("DeadShotgunguy_NoLeg");
		Stop;
			
			
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		XBRN AA 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_burned_flesh;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		XBRN BB 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 A 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
		TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(1.8, 2.2), 0) );
		TNT1 A 0;
		Stop;
		
	Xdeath:
	Death.punch:
	Death.Blast:
	Death.SSG:
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieManHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		SZD1 EFGH 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		SZD1 H -1;//doomb_final_absolution(12, 12);
		Stop;
		
}
}





CLASS BrutalizedSergeant1 : doomb_body_base
{ 
Default
{
	Radius 16;
	Height 50;
	Health 300;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+FLOORCLIP;
	+DONTSPLASH;
	+GHOST;
	+THRUGHOST;
	+nopain
	Scale 1.0;
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(2);
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		SZD1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1
		{
			if(health <= 200)
				setstatelabel("no_head");
		}
		
		SZD2 ABCD 5 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
		SPO5 E -1 doomb_final_absolution(12, 12);
	Stop;
		
	//BrutalizedSergeant2
	no_head:
		TNT1 A 0;
		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Recoil(2);
		SZD1 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1
		{
			if(health <= 100)
				setstatelabel("just_torso");
		}
		SZD4 AB 6 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
		SZD4 B -1 doomb_final_absolution(12, 12);
	Stop;
	
	just_torso:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(2);
		SZD1 C 12;
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
	    TNT1 A 0;
	//BrutalizedSergeant3
		SZD1 C 35;
		SZD3 ABC 6 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
		TNT1 A 0 doomb_spawn_bloodpool();
		SZD3 C -1 doomb_final_absolution(12, 12);
	Stop;
	
	Death:
		TNT1 A 0 A_Recoil(2);
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
	    TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
        TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("Brutal_LiquidBlood", 44, 0, random (0, 360), 2, random (0, 50));
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		SZD1 EFGH 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		SZD1 H -1 doomb_final_absolution(12, 12);
	Stop;




























	Death.SSG:
	XDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("SargeXDeath", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;

	Death.Fatality:
	Death.punch:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("HasSguyShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	Stop;

	Death.Plasma: Death.Plasma2:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		XBRN AA 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_burned_flesh;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		XBRN BB 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 A 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
		TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(1.8, 2.2), 0) );
	Stop;
}

}



	   
CLASS StompedSergeant: CurbstompedMarine { 
	Default {
 
Health 200;
	}
States
{
	Spawn:
        02CB F -1;
        Stop;
	Death:
		 TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AAAA 0 A_SpawnProjectile ("XDeath2", 15, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AAAA 0 A_SpawnProjectile ("XDeath3", 15, 0, random (0, 360), 2, random (0, 160));
		 TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AA 0 doomb_Meat_Death_Small();
		 TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		 TNT1 A 0 A_SpawnProjectile ("XDeathHalfShotgunguyNoArmNoHead", 32, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AAAAAAA 0 A_SpawnProjectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
		 TNT1 A 0 A_SpawnProjectile ("XDeathSargeLeg2", 32, 0, random (0, 360), 2, random (0, 160));
		 TNT1 A 0 A_SpawnProjectile ("GibSargeBoot", 32, 0, random (0, 360), 2, random (0, 160));
	Stop;
}

}		  
		  
CLASS VeryFuckedUpBrutalizedSergeantLeg: CurbstompedMarine { 
	Default {
 
    Health 200;
	}
     States
     {
         Spawn:
			ID14 G -1;
        Stop;
		Death:
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath2", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath3", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_Meat_Death_Small();
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfShotgunguyNoArmNoHead", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathSargeLeg2", 32, 0, random (0, 360), 2, random (0, 160));
		Stop;
}

}

CLASS BrutalizedSergeantLeg: BrutalizedSergeant1 { 
	States
	{
	Spawn:
	Pain:
		SPO3 A 15;
		SPO3 BCD 5;
		TNT1 A 0 A_SpawnItem ("DeadShotgunguy_NoLeg");
	Stop;
	
	Death:
		TNT1 A 0 A_Recoil(4);

		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		//TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
	    ID14 ABCDEF 5;
		TNT1 A 0 A_SpawnItem ("VeryFuckedUpBrutalizedSergeantLeg");
	Stop;

}
}










	







CLASS SergeantFatalizedByBaron: doomb_body_base { 
	Default {
 
Renderstyle "Translucent";
Alpha 1.0;
	}
	States
	{
	Spawn:
	SP2X BCD 8;
	TNT1 A 0 doomb_spawn_bloodpool();
    TNT1 A 0 A_SpawnItem ("DeadShotgunguy_Half", 1);
	Stop;
}
}








CLASS SergeantGotHisLegBlowed : doomb_body_base { 
	Default {
 
	Radius 16;
	Height 28;
	Health 50;
	PainSound "grunt/pain";
	PainChance 255;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
		damagefactor "Leg", 0.0;
		damagefactor "Kick", 6.0;
		Mass 500;
		+SHOOTABLE;
		+FLOORCLIP;
		+DONTSPLASH;
		MONSTER;
		+FRIENDLY;//
		-COUNTKILL;
		+GHOST;
		+THRUGHOST;
		-SOLID;
		
		+FLOORCLIP;
		+DONTSPLASH;
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			SPO3 D 1 A_PlaySound ("BURNZOM");
			TNT1 A 0 doomb_spawn_bloodpool();
		Suffer:
			TNT1 A 0;
			SPO3 DDDDD 2 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
			SPO3 EEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
			TNT1 A 0 A_Jump(32, "LeaveCrawling");
			TNT1 A 0 A_Jump(16, "LastStand");
			tnt1 a 0 a_jump(180, "suffer");
			Loop;
			
		Death.Cut:
		Death.Cutless:
		Death:
			TNT1 A 0;
			SPO3 GH 5;
			TNT1 A 0 A_PlaySound ("grunt/death");
			TNT1 A 0 A_SpawnItem ("DeadShotgunguy_NoLeg");
			Stop;
			
		LEaveCrawling:
			TNT1 A 0 A_PlaySound ("grunt/death");
			TNT1 A 0 A_SpawnItem ("DyingSergeantNoLeg");
			Stop;
			
		Death.Headshot:
			TNT1 A 0 A_Jump(126, "headshot_1");
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode", 0, 30);
			TNT1 A 0 A_Scream;
			TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 37, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			SPO3 IJ 5;
			TNT1 A 0 A_SpawnItem ("DeadShotgunguy_NoLeg", 1);
			Stop;
			
		headshot_1:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_SpawnProjectile ("XDeathSergeantHead", 32, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_Scream;
			TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 37, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			SPO3 IJ 5;
			
			TNT1 A 0 A_SpawnItem ("DeadShotgunguy_NoLeg", 1);
			Stop;
			
		Death.Shotgun:
		Death.Kick:
		Death.punch:
			TNT1 A 0 doomb_much_blood(35);
			TNT1 A 0 A_Scream;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 A_NoBlocking;
			ID11 GH 10;
			TNT1 A 0 A_SpawnItem ("DeadShotgunguy_NoLeg");
		Stop;
			
		Death.Fatality:
		Death.punch:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("HasSguyShield", 1);
			TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
			Stop;
			
		LastStand:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_SpawnItem ("SergeantLastStand1");
			Stop;
			
		XDeath:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_FaceTarget;
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 42, 0, random (170, 190), 2, random (10, 60));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 42, 0, random (170, 190), 2, random (10, 60));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 42, 0, random (170, 190), 2, random (10, 60));
			TNT1 A 0 A_SpawnProjectile ("XDeath4", 42, 0, random (170, 190), 2, random (10, 60));
			TNT1 A 0 A_SpawnProjectile ("SargeXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			Stop;
	}
}





CLASS FlyingImpaledSergeant : doomb_body_base
{ 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			ID18 AA 3 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			ID11 GG 3 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		Fall:
			ID11 H 3 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		Loop;
		
		Death:
		TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadShotgunguy");
		Stop;
			
		Splash:
		Stop;
	}
}


CLASS FrozenShotgunguy : doomb_body_base
{ 
	Default {
		
		Health 60;
		Radius 16;
		Height 52;
		+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
		
	}
	States
	{
		Spawn:
			FZD2 A 200;
			FZD2 A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZD2 A 50;
			FZD2 B 2;
			FZD2 A 50;
			FZD2 B 2;
			FZD2 A 50;
			FZD2 B 2;
			FZD2 A 25;
			FZD2 B 2;
			FZD2 A 25;
			FZD2 B 2;
			FZD2 A 10;
			FZD2 B 2;
			FZD2 A 10;
			FZD2 B 2;
			FZD2 A 10;
			FZD2 BABABA 2;
		Death.Fire:
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_spawnItem("Shotgunguy");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_much_blood(48);
			TNT1 A 0 A_SpawnItem("Shotgun");
			FZD2 C 300;
			FZD2 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
			Stop;
			
	}
}


CLASS SergeantLastStand1: DyingSergeantNoLeg { 
	Default {
	Height 28+18;
	doomb_monster_base.head_starting_position 30;

		Speed 0;
		MONSTER;
		+MISSILEMORE;
		+MISSILEEVENMORE;
		+LOOKALLAROUND;
		+GHOST;
		+THRUGHOST;
		-SOLID;
	}
	States
	{
		Spawn:
			ZSLS A 1 A_Look;
		See:
			ZSLS AAAAA 1 A_Chase;
			Loop;
			
		Missile:
			ZSLS AAAA 10
			{
				A_FaceTarget();
				A_SpawnProjectile ("Brutal_LiquidBlood", 6, 0, random(0, 180), 2, random (0, 35));
			}
			ZSLS B 6 BRIGHT
			{
				A_SpawnProjectile("MonsterTracer", 28, 0, random(-12, 12), CMF_OFFSETPITCH, frandom(-5, 5) );
				A_SpawnProjectile("OrangeLensFlareAlt", 24, 10, 15, 0);
				A_PlaySound("weapons/rifle");
				A_SpawnItem ("RifleCaseSpawn", 0, 20,0);
				doomb_random_death();
			}
		loop;			
			
		Death.headshot:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Scream;
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 37, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_NoBlocking;
			POS7 GHI 6;
			TNT1 A 0 A_SpawnItem ("DeadShotgunguy_NoLeg", 1);
		Stop;
	}
}	



CLASS SergeantLastStand2: DyingSergeant { 
	Default {
	Height 28+18;
	doomb_monster_base.head_starting_position 30;

		Speed 0;
		MONSTER;
		+MISSILEMORE;
		+MISSILEEVENMORE;
		+LOOKALLAROUND;
		+GHOST;
		+THRUGHOST;
	}
	States
	{
		Spawn:
			ZSLS C 1 A_Look;
		See:
			ZSLS C 10 A_Chase;
			TNT1 A 0 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, 90, 2, random (0, 45));
			tnt1 a 0 a_jump(10, "death");
		Loop;
			
		Missile:
			ZSLS CCCC 10
			{
				A_FaceTarget();
				A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, 90, 2, random (0, 45));
			}			
			TNT1 AA 0 A_SpawnProjectile("OrangeLensFlareAlt", 24, 10, 15, 0);
			TNT1 A 0 A_PlaySound("weapons/rifle");
			ZSLS D 6 BRIGHT A_SpawnProjectile("MonsterTracer", 28, 0, random(-12, 12), CMF_OFFSETPITCH, frandom(-5, 5) );
			TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 20,0);
			tnt1 a 0 doomb_random_death();	
		loop;			
			
		Death.Headshot:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_Jump(126, "headshot_1");
			TNT1 A 0 A_SpawnItem("ShotgunguyHeadExplode", 0, 30);
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 37, 0, random (0, 360), 2, random (0, 160));
			SZD4 AAAAA 2 A_SpawnProjectile ("Brutal_LiquidBlood", 25, 0, random (0, 360), 2, random (30, 110));
			SZD4 BBBBBBBBBBBBBBBBBBBBBBBBB 1 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (30, 110));
			SZD4 B -1 doomb_final_absolution(12, 12);
		Stop;
	}
}