CLASS CapturedMarine: doomb_monster_base Replaces Blursphere { 
	Default {
		
		Radius 24;
		Height 48;
		Speed 0;
		Health 300;
		Scale 1.0;
		
		+SHOOTABLE;
		+FLOORCLIP;
		+SOLID;
		+FRIENDLY;
		-COUNTKILL;
		+FLOORCLIP;
		Painchance 255;
		DamageType "Taunt";
		damagefactor "Trample", 0.0;
		damagefactor "Cut", 10.0;
		damagefactor "Taunt", 0.0;
		damagefactor "headcut", 0.0;
		damagefactor "KillMe", 0.0;
		damagefactor "Fatality", 99.0;
		damagefactor "Melee", 99.0;
		damagefactor "Kick", 99.0;
		damagefactor "GibRemoving", 0.0;
		damagefactor "TeleportRemover", 0.0;
		DamageFactor "CauseObjectsToSplash", 0.0;
		DeathSound "*death";
		PainSound "*pain50";
		BloodType "Brutal_Blood";
		+USESPECIAL;
		Activation THINGSPEC_Activate;
		DropItem "PoleWithNothing", 255;
		Mass 999999;
		Speed 0;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Stop;
			MARN A 0 ACS_ExecuteAlways(719, 0, 0, 0, 0);//Check if Coop
			TNT1 A 1;
			Goto Spawn1;
		DM:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("SuperBlursphere");
			TNT1 A 5000;
			Loop;
			
		Spawn1:
			TNT1 A 0 A_CheckSight("Spawn2");
			CAPT A 1 A_Stop;
			CAPT ABCB 15 A_Stop;
			TNT1 A 0 A_SpawnProjectile ("OrderTitle3", 50, 0, 0, 2, 90);
			TNT1 A 0 A_SpawnItem ("KillMe");
			Loop;
			
		Spawn2:
			CAPT A 5;
			Goto Spawn1;
			
		SetFree:
		Death.Cut:
		Death.Punch:
		Death.Fatality:
		Death.Kick:
		Active:
			TNT1 A 0 A_Playsound ("TAUNT");
			TNT1 A 0 {bNOPAIN = true;}
			CAPT F 12;
			TNT1 A 0 A_NoBlocking;
			//TNT1 A 0 A_SpawnItem("Ally")
			TNT1 A 0 A_GiveToTarget("NumberOfAllies", 1);
			TNT1 A 0 A_SpawnItemEx ("RandomMarine",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			CAPT N 1 A_NoBlocking;
			Stop;
			
		Pain:
		Pain.Blast:
		Pain.Explosive_Impact:
		Pain.Bullet:
		Pain.SSG:
		Pain.CutLess:
		Pain.ImpFatalityMarine:
		Pain.Rip:
			CAPT P 1;
			TNT1 A 0 A_Stop;
			CAPT P 5 A_Pain;
			TNT1 A 0 A_Stop;
			Goto Spawn;
			
		Death:
		Death.Bullet:
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			PLAY H 10 A_PlayerScream;
			
			PLAY I 10 A_NoBlocking;
			PLAY J 10;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			PLAY KLM 10;
			TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
			PLAY N -1;
			Stop;
			
		Death.Eat:
			TNT1 A 0 A_GiveToTarget("EatMe",1);
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL1 A 10 A_XScream;
			XPL1 B 20 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			XPL1 CDE 10;
			TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
			XPL1 E -1;
			Stop;
			
		Death.Cut:
		Death.Saw:
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("RipGuts", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL2 A 10 A_XScream;
			TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL2 B 20 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL2 C 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL2 DE 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
			XPL2 E -1;
			Stop;
			
		Death.Slime:
			TNT1 A 0 A_PlaySound("BIGSCREA");
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			PMET AABBCCDDEEFFGGHHIIIII 10 doomb_show_effect("ExplosionSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			PMET IIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLLLLLLLLL 3 doomb_show_effect("ExplosionSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			TNT1 A 0 A_NoBlocking;
			TNT1 A -1;
			Stop;
			
		Death.CutLess:
			TNT1 A 0 A_Jump (128, 3);
			Goto Death;
			TNT1 AAA 0;
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("RipGuts", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL2 A 10 A_XScream;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL2 B 20 A_NoBlocking;
			TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL2 C 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL2 DE 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
			XPL2 E -1;
			Stop;
			
		Death.Rip:
			TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL3 A 10 A_XScream;
			TNT1 AAAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL3 B 20 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL3 C 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL3 D 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL3 E 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL3 F 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL3 F 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
			XPL3 F -1;
			Stop;
		Death.Explosives:
		XDeath:
			TNT1 A 0 ThrustThingZ(0,60,0,1);
			TNT1 A 0 A_SpawnProjectile ("MarineXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib2", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib3", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib4", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			MHEA A 7 A_XScream;
			MHEA B 7 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			MHEA CD 7;
			MHEA E -1;
			Stop;
			
		Crush:
		Death.Stomp:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AAAAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AA 0 bright A_SpawnProjectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 AA 0 bright A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 A 0 A_SpawnItem ("doomb_red_blood_pool");
			TNT1 A 0 A_SpawnItem ("CrushedRemains");
			TNT1 A 1;
			TNT1 A 1 A_XScream;
			TNT1 A 1 A_NoBlocking;
			Stop;
			
		Death.Blast:
		Death.SuperPunch:
		Death.SSG:
			PLAY O 2 A_FaceTarget;
			//TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160))
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			PLAY OPQRSTU 8;
			TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
			PLAY U -1;
			Stop;
			
		Death.Rape:
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL4 A 20 A_XScream;
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL4 B 20 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL4 C 20;
			TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL4 D 20;
			TNT1 AAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL4 E 20;
			TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			XPL4 F 20;
			TNT1 AAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
			XPL4 F -1;
			Stop;
			
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_spawn_burned_flesh;
			EXPL AAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 1;
			TNT1 A -1;
			Stop;
			
			
		Death.GreenFire:
			TNT1 A 0;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
			
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_spawn_burned_flesh;
			
			EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0;//doomb_show_effect("GreenFlameTrails", (0, 0, 50), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
			Stop;
			
		fire_death_1:
			PBUR A 1;
			PBUR A 1 A_Scream;
			PBUR A 1 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			PBUR AAAABBBBCCCCDDDDEEEEEEEEE 2;//doomb_show_effect("FlameTrails", ( 0, 0, 32 - frame * 3), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );	
			
			
			PBUR EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 6 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			PBUR E -1;
			Stop;
			
		Death.Fire:
			tnt1 a 0 a_jump(128, "fire_death_1");
			TNT1 A 0 A_PlaySound("BIGSCREA");
			BURN W 6 A_Scream;
			BURN X 6 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			BUR2 ABCD 6 BRIGHT doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BURN FGHIJKLMNOPQRSTUV 6 BRIGHT doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 6 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BURN V -1;
			Stop;
			
			
		Death.Explosive_Impact:
			tnt1 A 0 ThrustThingZ(0,30,0,1);
			tnt1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
			tnt1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
			tnt1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
			tnt1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
			tnt1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
			tnt1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (0, 40));
			tnt1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
			tnt1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
			tnt1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
			tnt1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
			tnt1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			tnt1 A 0 A_XScream;
			XPL6 A 5;
			tnt1 A 0 A_NoBlocking;
			XPL6 BCDE 5;
			XPL6 F -1;
			Stop;
			
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 A 5;
			CRS1 A -1;
			Stop;
			
		Death.HKFT:
		Death.BHFT:
		Death.RVFT:
			TNT1 A 1 A_PlayerScream;
			TNT1 A 1 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			TNT1 A 0 A_GiveToTarget("Curbstomp_Marine",1);
			TNT1 A -1;
			Stop;
			
		Death.FatalityMarine:
			TNT1 A 1 A_PlayerScream;
			TNT1 A 0 A_GiveToTarget("GoFatality", 1);
			TNT1 A 1 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("RemoveMarine");
			TNT1 A 0 A_GiveToTarget("Fatality_Marine",1);
			TNT1 A -1;
			Stop;
	}
}

CLASS KillMe : ACTOR { 
	Default {
		
		+NOTARGET;
		Radius 10;
		Height 10;
		DamageType "KillMe";
		+NOGRAVITY;
		+NOTELEPORT;
		+NODAMAGETHRUST;
		+THRUGHOST;
		+NORADIUSDMG;
		+NOEXTREMEDEATH;
		+FORCERADIUSDMG;
		-BLOODSPLATTER;
		+BLOODLESSIMPACT;
		PROJECTILE;
		+DEHEXPLOSION;
		+ACTIVATEMCROSS;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Explode(3,500);
			Stop;
	}
}






CLASS KillMeSmall: KillMe { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Explode(3,400);
			Stop;
	}
}

CLASS MarineSurvivor2: Marine
{ 
	Default {
		Speed 5;
		Health 6;
	}
	States
	{
		Spawn:
			PLAY A 0;
			TNT1 A 0 A_CheckSight("Spawn2");
			PLAY A 0;
			//TNT1 A 0 A_SpawnItem ("GiantKillMe")
			PLAY A 1 A_Chase;
			Goto See;
			
		Spawn2:
			PLAY A 1;
			Goto Spawn;
	}
}


CLASS MarinePunch : ACTOR { 
	Default {
		
		Radius 10;
		Height 18;
		DamageType "HelperMarineFatallity";
		Projectile;
		+RANDOMIZE;
		Damage 10;
		+FORCEXYBILLBOARD;
		+THRUGHOST;
		+BLOODSPLATTER;
		RenderStyle "Add";
		Alpha 0.6;
		HitObituary "$OB_IMPHIT";
		Obituary "$OB_IMPHIT";
		+DONTHARMCLASS;
		
		SeeSound "None";
		DeathSound "none";
		Decal "none";
		Speed 20;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("skeleton/swing");
			TNT1 A 4 BRIGHT;
			Stop;
		Death:
			TNT1 A 0 A_PlaySound("player/cyborg/fist");
			TNT1 A 0 BRIGHT;
			Stop;
	}
}




CLASS MarineGivingHealth : ACTOR { 
	Default {
		
		MONSTER;
		-COUNTKILL;
		+SOLID;
		-SHOOTABLE;
		+MISSILEMORE;
		+MISSILEEVENMORE;
		Health 99999;
		Radius 16;
		Height 52;
		Speed 0;
		MeleeRange 28;
	}
	States
	{
		Spawn:
			MR8S A 1 A_Look;
			TNT1 A 0 A_CheckSight("GiveHealth");
			TNT1 A 0 A_PlaySound("MRNGI2");
			Goto See;
			
		See:
			MR8S AAAAABBBBB 5 A_Chase;
			TNT1 A 0 A_CheckSight("GiveHealth");
			Loop;
			
			
			
		Missile:
		GiveHealth:
			MR8S A 1 A_FaceTarget;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItemEx("Stimpack", 30, 0);
			TNT1 A 0 A_SpawnItem("Marine_Rifle");
			Stop;
	}
}



CLASS BlurSphere2: BlurSphere { //Replaces BlurSphere
	Default {
		
		-COUNTITEM;
	}
	States
	{
		Spawn:
			PINS A 2 Bright;
			TNT1 A 0 A_SpawnItem("CapturedMarine");
			Stop;
	}
}	


CLASS PoleWithNothing : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		Mass 99999999;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_SpawnItem("PoleWithNothing2", 0, -40);
			Stop;
			
	}
	
}

CLASS PoleWithNothing2 : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		Mass 99999999;
	}
	States
	{
		Spawn:
			CAPT N 1 A_Stop;
			CAPT N -1;
			Stop;
			
	}
	
}





CLASS MonsterSightAlert : ACTOR { 
	Default {
		
		MONSTER;
		+THRUACTORS;
		Health 1;
		DamageType "Alert";
		+SHOOTABLE;
		+NOPAIN;
		+MISSILE;
		Radius 1;
		Height 1;
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0;
			TNT1 A 0 A_Explode(2,500, 0);
			TNT1 A 1;
			Stop;
		Death:
			TNT1 A 0;
			Stop;
	}
}








CLASS OrderTitle1 : ACTOR { 
	Default {
		
		Height 1;
		Radius 1;
		Mass 0;
		+Missile;
		+NoBlockMap;
		+NoGravity;
		+DontSplash;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		+THRUACTORS;
		+GHOST;
		+THRUGHOST;
		RenderStyle "Add";
		Scale 0.2;
		Speed 1;
	}
	States
	{
		Spawn:
			CMMN A 2 BRIGHT;
			CMMN AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 Bright A_FadeOut(0.04);
			Stop;
	}
}


CLASS OrderTitle2: OrderTitle1 { 
	Default {
		
	}
	States
	{
		Spawn:
			CMMN B 2 BRIGHT;
			CMMN BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1 Bright A_FadeOut(0.04);
			Stop;
	}
}


CLASS OrderTitle3: OrderTitle1 { 
	Default {
		
	}
	States
	{
		Spawn:
			CMMN C 2 BRIGHT;
			CMMN CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 Bright A_FadeOut(0.04);
			Stop;
	}
}
