CLASS CapturedMarine: doomb_marine_base Replaces Blursphere
{ 
	Default
	{
		Radius 24;
		Height 48;
		Speed 0;
		Health 300;
		Scale 1.0;
		Mass 999999;
		Speed 0;
		
		Activation THINGSPEC_Activate;
		+USESPECIAL;
		+SHOOTABLE;
		+FLOORCLIP;
		+SOLID;
		+FRIENDLY;
		-COUNTKILL;
		+FLOORCLIP;

		Painchance 255;
		DamageType "Taunt";
		damagefactor "Trample", 0.0;
		damagefactor "Cut", 10.0;
		damagefactor "Taunt", 0.0;
		damagefactor "headcut", 0.0;
		damagefactor "Fatality", 99.0;
		damagefactor "Melee", 99.0;
		damagefactor "Kick", 99.0;

		DeathSound "*death";
		PainSound "*pain50";
		BloodType "Brutal_Blood";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Stop;
			MARN A 0 {if(deathmatch) setstatelabel("dm");}
			TNT1 A 1;
		Goto Spawn1;
		
		DM:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("SuperBlursphere");
			TNT1 A 5000;
		Loop;
			
		Spawn1:
			CAPT ABCB 15 A_Stop;
			TNT1 A 0 A_SpawnProjectile ("OrderTitle3", 50, 0, 0, 2, -90);
		Loop;
			
		SetFree:
		Death.Cut:
		Death.Punch:
		Death.Fatality:
		Death.Kick:
		Active:
			TNT1 A 0 A_Playsound ("TAUNT");
			TNT1 A 0 {bNOPAIN = true;}
			CAPT F 12;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItemEx ("RandomMarine",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("PoleWithNothing",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
			
		Pain:
		Pain.Blast:
		Pain.Explosive_Impact:
		Pain.Bullet:
		Pain.SSG:
		Pain.mini_gun:
		Pain.ImpFatalityMarine:
		Pain.Rip:
			CAPT P 1 A_Stop;
			CAPT P 5 A_Pain;
		Goto Spawn;
			
		Death:
		Death.Bullet:
			TNT1 A 0 doomb_much_blood();
			PLAY H 10 A_PlayerScream;
			PLAY I 10 A_NoBlocking;
			PLAY J 10 ;
			PLAY KLM 10;
			PLAY N -1 doomb_spawn_bloodpool();
		Stop;
			
		Death.Eat:
			TNT1 A 0 A_GiveToTarget("EatMe",1);
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_much_blood();
			XPL1 A 10 A_XScream;
			XPL1 B 20 A_NoBlocking;
			TNT1 A 0 ;
			XPL1 CDE 10;
			TNT1 A 0 doomb_spawn_bloodpool();
			XPL1 E -1;
			Stop;
			
		Death.Cut:
		Death.Saw:
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_Rip_Guts();
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_much_blood();
			XPL2 A 10 A_XScream;
			TNT1 A 0 doomb_much_blood();
			XPL2 B 20 A_NoBlocking;
			TNT1 A 0 ;
			TNT1 A 0 doomb_much_blood();
			XPL2 CDE 10 doomb_much_blood();
			TNT1 A 0 doomb_spawn_bloodpool();
			XPL2 E -1;
		Stop;
			
		Death.Slime:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_PlaySound("BIGSCREA");
			TNT1 A 0 ;
			PMET AABBCCDDEEFFGGHHIIIII 10 doomb_show_effect("ExplosionSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			PMET IIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLLLLLLLLL 3 doomb_show_effect("ExplosionSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			Stop;
			
		Death.mini_gun:
			TNT1 A 0 A_Jump (128, 3);
			Goto Death;
			TNT1 AAA 0;
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_Rip_Guts();
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_much_blood();
			XPL2 A 10 A_XScream;
			TNT1 A 0 ;
			TNT1 A 0 doomb_much_blood();
			XPL2 B 20 A_NoBlocking;
			TNT1 A 0 doomb_much_blood();
			XPL2 CDE 10 doomb_much_blood();
			TNT1 A 0 doomb_spawn_bloodpool();
			XPL2 E -1;
			Stop;
			
		Death.Rip:
			TNT1 A 0 doomb_much_blood();
			XPL3 A 10 A_XScream;
			TNT1 A 0 doomb_much_blood();
			XPL3 B 20 A_NoBlocking;
			TNT1 A 0 doomb_much_blood();
			XPL3 CDEFF 10 doomb_much_blood();
			TNT1 A 0 doomb_spawn_bloodpool();
			XPL3 F -1;
		Stop;

		XDeath:
			TNT1 A 0 ThrustThingZ(0,60,0,1);
			TNT1 A 0 A_SpawnProjectile ("MarineXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			MHEA A 7 A_XScream;
			MHEA B 7 A_NoBlocking;
			TNT1 A 0 ;
			MHEA CD 7;
			MHEA E -1;
			Stop;
			
		Crush:
		Death.Stomp:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), doomb_random_velocity(5) );
			TNT1 A 0 doomb_blood_mist(times:6);
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("CrushedRemains");
			TNT1 A 1;
			TNT1 A 1 A_XScream;
			TNT1 A 1 A_NoBlocking;
			Stop;
			
		Death.Blast:
		Death.SSG:
			PLAY O 2 A_FaceTarget;
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_spray_decal("BrutalBloodSuper");
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;
			PLAY OPQRSTU 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			PLAY U -1;
			Stop;
			
		Death.Rape:
			TNT1 A 0 doomb_much_blood();
			XPL4 A 20 A_XScream;
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_much_blood();
			XPL4 B 20 A_NoBlocking;
			TNT1 A 0 doomb_much_blood();
			XPL4 CDEF 20 doomb_much_blood();
			TNT1 A 0 doomb_spawn_bloodpool();
			XPL4 F -1;
			Stop;
			
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ;
			TNT1 AAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_spawn_burned_flesh;
			EXPL AAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 1;
			TNT1 A -1;
			Stop;
			
			
			
		fire_death_1:
			PBUR A 1;
			PBUR A 1 A_Scream;
			PBUR A 1 A_NoBlocking;
			TNT1 A 0 ;
			PBUR AAAABBBBCCCCDDDDEEEEEEEEE 2 doomb_show_effect("FlameTrails", ( 0, 0, 32 - frame * 3), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			PBUR EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 6 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			PBUR E -1;
			Stop;
			
		Death.Fire:
			tnt1 a 0 a_jump(128, "fire_death_1");
			TNT1 A 0 A_PlaySound("BIGSCREA");
			BURN W 6 A_Scream;
			BURN X 6 A_NoBlocking;
			TNT1 A 0 ;
			BUR2 ABCD 6 BRIGHT doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BURN FGHIJKLMNOPQRSTUV 6 BRIGHT doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 6 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BURN V -1;
			Stop;
			
			
		Death.Explosive_Impact:
			tnt1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 doomb_severed_limb("eye", "spawn", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("head_piece", "spawn", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("jaw", "spawn", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_spray_decal("BrutalBloodSuper");
			tnt1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
			tnt1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			tnt1 A 0 A_XScream;
			XPL6 A 5;
			tnt1 A 0 A_NoBlocking;
			XPL6 BCDE 5;
			XPL6 F -1;
			Stop;
			
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 A -1;
			Stop;
			
		Death.HKFT:
		Death.BHFT:
		Death.RVFT:
			TNT1 A 1 A_PlayerScream;
			TNT1 A 1 A_NoBlocking;
			TNT1 A 0 ;
			TNT1 A 0 A_GiveToTarget("Curbstomp_Marine",1);
			TNT1 A -1;
			Stop;
			
		Death.FatalityMarine:
			TNT1 A 1 A_PlayerScream;
			TNT1 A 1 A_NoBlocking;
			TNT1 A 0 ;
			TNT1 A 0 A_GiveToTarget("Fatality_Marine",1);
			TNT1 A -1;
			Stop;
	}
}

CLASS RandomMarine: actor { 
	Default {
		
		Radius 10;
		Height 48;
		-SHOOTABLE;
	}
	States
	{
		Spawn:
			PLAY A 1;
			PLAY A 1 A_CheckSight("DontSpawn");
			TNT1 A 0 A_Chase;
			TNT1 A 0 A_Look;
		See:
			TNT1 A 0;
			TNT1 A 0 A_Jump(96, "See2");
			TNT1 A 0 A_Jump(96, "See3");
			TNT1 A 0 A_Jump(64, "See4");
			TNT1 A 0 A_Jump(32, "See5", "See6");
			
		See2:
			TNT1 A 0 A_SpawnItemEx ("MarineShotgun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		See3:
			TNT1 A 0 A_SpawnItemEx ("MarineChaingun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		See4:
			TNT1 A 0 A_SpawnItemEx ("MarinePlasma",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		See5:
			TNT1 A 0 A_SpawnItemEx ("MarineRocket",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		See6:
			TNT1 A 0 A_SpawnItemEx ("MarineBFG",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		DontSpawn:
			PLAY A 1;
			Goto Spawn;
	}
}










CLASS BlurSphere2: BlurSphere { //Replaces BlurSphere
	Default {
		
		-COUNTITEM;
	}
	States
	{
		Spawn:
			PINS A 2 Bright;
			TNT1 A 0 A_SpawnItem("CapturedMarine");
			Stop;
	}
}	


CLASS PoleWithNothing : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		+noclip
		Mass 99999999;
	}
	States
	{
		Spawn:
			CAPT N 1 A_Stop;
			CAPT N -1;
			Stop;
			
	}
	
}













CLASS OrderTitle1 : ACTOR { 
	Default {
		
		Height 1;
		Radius 1;
		Mass 0;
		+Missile;
		+NoBlockMap;
		+NoGravity;
		+DontSplash;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		+THRUACTORS;
		+GHOST;
		+THRUGHOST;
		RenderStyle "Add";
		Scale 0.2;
		Speed 1;
	}
	States
	{
		Spawn:
			CMMN A 2 BRIGHT;
			CMMN AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1 Bright A_FadeOut(0.04);
			Stop;
	}
}


CLASS OrderTitle2: OrderTitle1 { 
	States
	{
		Spawn:
			CMMN B 2 BRIGHT;
			CMMN BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1 Bright A_FadeOut(0.04);
			Stop;
	}
}


CLASS OrderTitle3: OrderTitle1 { 
	States
	{
		Spawn:
			CMMN C 2 BRIGHT;
			CMMN CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 Bright A_FadeOut(0.04);
			Stop;
	}
}
