
CLASS PrePlacedMarineMinigun : ACTOR Replaces MarineChaingun { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx ("Marine_MinigunSpawn",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
	}
}


CLASS NumberOfAlliesMinigun : Inventory { 
	Default {
		
		inventory.maxamount 5;
	}
}

CLASS MarinesMinigunDispenser : Inventory { 
	Default {
		
		inventory.maxamount 5;
	}
}




CLASS Marine_MinigunSpawn: RedTorch { 
	Default {
		
		Radius 10;
		Height 48;
		MONSTER;
		-SHOOTABLE;
		-COUNTKILL;
		-FRIENDLY;
	}
	States
	{
		Spawn:
			PL42 A 10;
			PL42 A 1 A_CheckSight("DontSpawn");
			TNT1 A 0 A_Chase;
			TNT1 A 0 A_Look;
		See:
			TNT1 A 0 A_GiveToTarget("NumberOfAlliesMinigun", 1);
			TNT1 A 0 A_SpawnItemEx ("Marine_Minigun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
		DontSpawn:
			PL42 A 1;
			Goto Spawn;
	}
}

CLASS Marine_Minigun: Marine_base
{ 
	Default {
		
		Scale 1.05;
		DropItem "MiniGun";
	}
override int doomb_get_aditional_death_sprite()
{
	return GetSpriteIndex("PL42");
}

	States
	{
		Active:
			TNT1 A 0 {bnoclip = true; a_noblocking();}
			TNT1 A 0 A_PlaySound("MarineGuard", 2);
			TNT1 A 0 A_SpawnProjectile ("OrderTitle2", 50, 0, 0, 2, 90);
			PL42 A 30;
			TNT1 A 0 A_SpawnItemEx ("MinigunMarineGuarding",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_GiveInventory("TargetIsAMarine");
			PL42 A 1 A_Look;
			Goto See;
			
		ForgetTarget:
			TNT1 A 0 A_ClearTarget;
			Goto See;
			
		See:
			TNT1 A 0 {bnodropoff = false;}
			TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
			TNT1 A 0 {bmissilemore = true;}
			TNT1 A 0 {bmissileevenmore = true;}
			TNT1 A 0 A_Recoil(-1);

			PL42 AABBCCDD 1
			{
				A_Chase();
				A_Recoil(-1);
			}
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 1, "FollowPlayer");
			TNT1 A 0 A_JumpIfCloser(200, "Waits");
			TNT1 A 0 A_CheckSight("CheckIfPlayerSee");

			TNT1 A 0 A_JumpIfCloser(200, "Waits");
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 1, "FollowPlayer");
		Goto See;
		
		BecomeEnemy23:
			PL42 A 1;
			TNT1 A 0 A_ClearTarget;
			TNT1 A 0 {bshootable = false;}
			TNT1 A 0 {bfriendly = false;}
			Goto FollowPlayer;
			
		FollowPlayer:
			TNT1 A 0 {bfriendly = false;}
			TNT1 A 0 {bshootable = false;}
			TNT1 A 0 A_JumpIfCloser(150, "Waits");
			TNT1 A 0 {bmissilemore = false;}
			TNT1 A 0 {bmissileevenmore = false;}
			PL42 AABBCCDD 1
			{
				A_Chase();
				A_Recoil(-1);
			}
			TNT1 A 0 A_CheckSight("CheckIfPlayerSee");
			TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 A_JumpIfTargetInLOS("See");
			TNT1 A 0 {bfriendly = false;}
			TNT1 A 0 A_CheckSight("CheckIfPlayerSee");
		Loop;
			
		CheckRangeToWait:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(150, "Waits");
			Goto FollowPLayer;
			
		CheckIfPlayerSee:
			TNT1 A 0;
			PL42 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_FastChase;
			TNT1 A 0 {bshootable = false;}
			TNT1 A 0 {bfriendly = false;}
			////TNT1 A 0 Thing_Hate(94, 0, 0)
			TNT1 A 0 A_JumpIfCloser(800, 2);
			Goto Pathfind;
			TNT1 AAA 0;
			Goto FollowPlayer;
			
			
			
	Pathfind:
		TNT1 A 0;
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 A_JumpIFInTargetInventory("IsPLayer", 1, 1);
	Goto FollowPLayer;
		TNT1 A 0 A_Noblocking;
		TNT1 A 0 A_SpawnItemEx ("Marine1Pathfinder",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETTARGET,0);
	Stop;
			
			
			
		Waits:
			PL42 H 1;
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 1, 2);
			TNT1 A 0 A_ClearTarget;
			Goto See;
			TNT1 A 0 {bfriendly = false;}
			TNT1 A 0 {bmissilemore = true;}
			TNT1 A 0 {bmissileevenmore = true;}
			TNT1 A 0 {bshootable = false;}
			TNT1 A 0 {bsolid = false;}
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "BecomeEnemy23");
			TNT1 A 0 A_JumpIfInTargetInventory("Clip2", 50, "GiveAmmo");
			
			PL42 H 8 A_Stop;
			PL42 E 8 A_Stop;
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_CheckSight("FollowPlayer");
			TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 A_ClearTarget;
			
			TNT1 A 0 {bshootable = true;}
			MARN D 0 A_Look;
			TNT1 A 0 {bfriendly = false;}
			TNT1 A 0 {bshootable = false;}
			PL42 E 1 A_LookEx(0, 0, 0, 0, 0, "FollowPlayer");
			TNT1 A 0 A_CheckSIght("FollowPlayer");
			TNT1 A 0 {bshootable = true;}
			TNT1 A 0 A_JumpIfCloser(200, "Waits");
		Goto FollowPlayer;

		GiveAmmo:
			TNT1 A 0;
			PL42 A 10 A_FaceTarget;
			TNT1 A 0 A_PlaySound("MRNGI1");
			PL42 I 30;
			TNT1 A 0 A_GiveToTarget("Clip2", 100);
			//TNT1 A 0 A_SpawnItemEx("Stimpack", 40, 0)
			Goto Waits;
			
		Missile:
			TNT1 A 0 {bnodropoff = true;}
			TNT1 A 0 A_SpawnItem("KillMeSmall");
			TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 1, "CheckRangeToWait");
			TNT1 A 0 {bshootable = true;}
			TNT1 A 0 {bsolid = true;}
			TNT1 A 0 A_JumpIfCloser(300, "Retreat");
			TNT1 A 0 A_PlaySound("MRNAT", 2);
			
		Missile2:
			PL42 E 2 A_FaceTarget;
			TNT1 A 0 A_PlaySound("CHGNSHOT", 1);
			PL42 F 1 BRIGHT;
			TNT1 A 0 A_SpawnProjectile("MarineStrongTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
			TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
			tnt1 a 0 a_jump(30, "see");
		loop;
			
		StrafeLeft:
			PL42 A 3 A_FaceTarget;
			PL42 B 3 ThrustThing(angle*256/360+192, 3, 0, 0);
			PL42 C 3 A_FaceTarget;
			PL42 D 3 ThrustThing(angle*256/360+192, 3, 0, 0);
			Goto Missile2;
			
		StrafeRight:
			PL42 A 3 A_FaceTarget;
			PL42 B 3 ThrustThing(angle*256/360+64, 3, 0, 0);
			PL42 C 3 A_FaceTarget;
			PL42 D 3 ThrustThing(angle*256/360+64, 3, 0, 0);
			Goto Missile2;
			
		CheckRetreat:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(500, "Retreat");
		Pain.Avoid:
			TNT1 A 0 A_Jump(256, "StrafeLeft", "StrafeRight");
			Goto StrafeLeft;
			
		Retreat:
			TNT1 A 0;
			PL42 A 3 A_FaceTarget;
			TNT1 A 0 A_Recoil(5);
			PL42 B 3;
			TNT1 A 0 A_Recoil(5);
			PL42 CD 3 A_FaceTarget;
			Goto MIssile2;
			
			
			
		AttackMelee:
			TNT1 A 0;
			PLAM A 4 A_FaceTarget;
			TNT1 A 0 A_Recoil(-4);
			PLAM A 1 A_FaceTarget;
			PLAM B 4 A_SpawnProjectile("MarinePunch",40,0,0,0);
			PLAM B 2;
			TNT1 A 0 A_JumpIfInventory("ZombiemanFatality3", 1, "FatalityZombieman");
			TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
			TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			TNT1 A 0 A_JumpIfInventory("RevenantFatality", 1, "FatalityRevenant");
			Goto See;
			
		Pain:
			PL42 G 3;
			TNT1 A 0 {bnodropoff = false;}
			PL42 G 3 A_Pain;
			Goto FollowPlayer;
			
			
			
	}
}




CLASS MinigunMarineGuarding: Marine_Minigun { 
	Default {
		
		FastSpeed 0;
		MaxStepHeight 0;
		+FRIENDLY;
		+MISSILEMORE;
		+NODROPOFF;
		+MISSILEEVENMORE;
		+SHOOTABLE;
		Speed 0;
	}
	States
	{
		Active:
			TNT1 A 0 {bnoclip = true;}
			TNT1 A 0 A_PlaySound("MarineFollow", 2);
			TNT1 A 0 A_SpawnProjectile ("OrderTitle1", 50, 0, 0, 2, 90);
			PL42 A 30;
			TNT1 A 0 {bnoclip = true;}
			TNT1 A 0 A_SpawnItemEx ("Marine_Minigun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 A_GiveInventory("TargetIsAMarine");
			PL42 E 1 A_Look;
			Goto See;
			
		See:
			//TNT1 A 0 A_SetAngle(random(90, -90) + angle)
			TNT1 A 0 {bshootable = false;}
			TNT1 A 0 {bsolid = false;}
			PL42 EEEEEEEEEEHHHHHHHHH 1 A_Chase;
			TNT1 A 0 A_ClearTarget;
			Loop;
			
			
		Missile:
			//PL42 E 1
			TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 A_SpawnItem("KillMeSmall");
			TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
			TNT1 A 0 {bshootable = true;}
			TNT1 A 0 {bsolid = true;}
			
		Missile2:
			TNT1 A 0 {bshootable = true;}
			TNT1 A 0 {bsolid = true;}
			
			PL42 E 2 A_FaceTarget;
			TNT1 A 0 A_PlaySound("CHGNSHOT", 1);
			PL42 F 1 BRIGHT;
			TNT1 A 0 A_SpawnProjectile("MarineStrongTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
			TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
			TNT1 A 0 a_monsterrefire(200, "see");
		Goto See;
			
			
		Pain:
			PL42 G 3;
			PL42 G 3 A_Pain;
			TNT1 A 0 A_Jump(128, "StrafeLeft", "StrafeRight");
			Goto See;
			
		StrafeLeft:
			PL42 A 3 A_FaceTarget;
			PL42 B 3 ThrustThing(angle*256/360+192, 3, 0, 0);
			PL42 C 3 A_FaceTarget;
			PL42 D 3 ThrustThing(angle*256/360+192, 3, 0, 0);
			Goto Missile2;
			
		StrafeRight:
			PL42 A 3 A_FaceTarget;
			PL42 B 3 ThrustThing(angle*256/360+64, 3, 0, 0);
			PL42 C 3 A_FaceTarget;
			PL42 D 3 ThrustThing(angle*256/360+64, 3, 0, 0);
			Goto Missile2;
	}
}

CLASS Marine_MinigunAdd: Marine1Pathfinder { 
	Default {
		Speed 4;
	}
	States
	{
		Death:
		Missile:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("NumberOfAlliesMinigun", 1);
		Stop;
	}
}

CLASS RemoveMarineMinigun : ACTOR { 
	States
	{
		Spawn:
		Pain:
		See:
			TNT1 A 1;
			TNT1 A 0 A_SpawnItemEx("RemoveMarineMinigunActivate",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 1;
			Stop;
	}
}

CLASS RemoveMarineMinigunActivate: Marine1Pathfinder { 
	Default {
		-FRIENDLY;
		-SHOOTABLE;
		Scale 1.0;
		Speed 1;
		MaxTargetRange 90000;
	}
	States
	{
		Missile:
			TNT1 A 1;
			TNT1 A 0 A_TakeFromTarget("NumberOfAlliesMinigun", 1);
		Stop;
	}
}




CLASS Marine_MinigunSpawnChecker : ACTOR { 
	Default {
		
		MONSTER;
		-COUNTKILL;
		+FRIENDLY;
		-SOLID;
		-SHOOTABLE;
		Health 1;
		Radius 16;
		Height 52;
		Damagetype "SpawnMarine";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_GiveInventory("TargetIsAMarine", 1);
			TNT1 A 0 A_AlertMonsters;
			TNT1 A 0 A_Explode(25, 40);
			Stop;
		Death:
			TNT1 A 1;
			Stop;
	}
}

