CLASS PrePlacedMarine : ACTOR Replaces MarinePistol { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx ("Marine",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
	}
}


CLASS Marine : doomb_marine_base
{ 
	States
	{
		Spawn:
			PLAY A 10;
			PLAY A 1 A_CheckSight("DontSpawn");
			TNT1 A 0 A_Chase;
			TNT1 A 0 A_Look;
		See:
			TNT1 A 0 A_GiveToTarget("NumberOfAllies", 1);
			TNT1 A 0 A_SpawnItemEx ("Marine_Rifle",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		DontSpawn:
			PLAY A 1;
			Goto Spawn;
	}
}


CLASS RandomMarine: actor { 
	Default {
		
		Radius 10;
		Height 48;
		-SHOOTABLE;
	}
	States
	{
		Spawn:
			PLAY A 1;
			PLAY A 1 A_CheckSight("DontSpawn");
			TNT1 A 0 A_Chase;
			TNT1 A 0 A_Look;
		See:
			TNT1 A 0;
			TNT1 A 0 A_Jump(96, "See1", "See2");
			TNT1 A 0 A_Jump(96, "See3");
			TNT1 A 0 A_Jump(64, "See4");
			TNT1 A 0 A_Jump(32, "See5", "See6");
			
		See1:
			TNT1 A 0 A_SpawnItemEx ("PrePLacedMarine",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		See2:
			TNT1 A 0 A_SpawnItemEx ("MarineShotgun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		See3:
			TNT1 A 0 A_SpawnItemEx ("MarineChaingun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		See4:
			TNT1 A 0 A_SpawnItemEx ("MarinePlasma",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		See5:
			TNT1 A 0 A_SpawnItemEx ("MarineRocket",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		See6:
			TNT1 A 0 A_SpawnItemEx ("MarineBFG",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		DontSpawn:
			PLAY A 1;
			Goto Spawn;
	}
}

CLASS Marine_Fist: PrePlacedMarine Replaces MarineFist { 
	Default {
		
		Health 90;
	}
}

CLASS Marine_SSG: PrePlacedMarine Replaces MarineSSG { 
	Default {
		
		Health 90;
	}
}


CLASS Marine_Rifle : doomb_marine_base {
	Default 
	{
		    DropItem "Rifle";
	}

	States
	{
	Active:
		TNT1 A 0 {bnoclip = true;}
		TNT1 A 0 A_PlaySound("MarineGuard", 2);
		TNT1 A 0 A_SpawnProjectile ("OrderTitle2", 50, 0, 0, 2, 90);
		MR7S A 30;
		TNT1 A 0 {bnoclip = true;}
		TNT1 A 0 A_SpawnItemEx ("RifleMarineGuarding",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
		
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_GiveInventory("TargetIsAMarine");
		PLAY A 1 A_Look;
		Goto See;
		
	ForgetTarget:
		TNT1 A 0 A_ClearTarget;
		Goto See;
		
	See:
		TNT1 A 0 A_JumpIfInventory("ZombiemanFatality3", 1, "FatalityZombieman");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
		TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		TNT1 A 0 A_JumpIfInventory("RevenantFatality", 1, "FatalityRevenant");
		tnt1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
		TNT1 A 0 {bnodropoff = false;}
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
		
		
		TNT1 A 0 {bmissilemore = true;}
		TNT1 A 0 {bmissileevenmore = true;}
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
		PLAY AABBCCDD 1
		{
			A_Chase();
			A_Recoil(-1);
		}
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_JumpIfCloser(200, "Waits");
		TNT1 A 0 A_CheckSight("ForgetTarget");
		TNT1 A 0 A_CheckSight("FollowPLayer");
		TNT1 A 0 A_CheckSight("CheckIfPlayerSee");
	Goto See;

	BecomeEnemy23:
		PLAY A 1;
		TNT1 A 0 A_ClearTarget;
		TNT1 A 0 {bshootable = false;}
		TNT1 A 0 {bfriendly = false;}
	FollowPlayer:
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 {bshootable = false;}
		TNT1 A 0 A_JumpIfCloser(150, "Waits");
		TNT1 A 0 {bmissilemore = false;}
		TNT1 A 0 {bmissileevenmore = false;}
		PLAY A 1 A_Chase;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_Recoil(-1);
		PLAY AABBCCDD 1
		{
			A_Chase();
			A_Recoil(-1);
		}
		TNT1 A 0 A_CheckSight("CheckIfPlayerSee");
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_JumpIfTargetInLOS("See");
		TNT1 A 0 {bfriendly = false;}
	Loop;
		
	CheckRangeToWait:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(150, "Waits");
		Goto FollowPLayer;
		
	CheckIfPlayerSee:
		TNT1 A 0;
		PLAY AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_FastChase;
		TNT1 A 0 {bshootable = false;}
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 A_JumpIfCloser(800, 2);
		Goto Pathfind;
		TNT1 AAA 0;
		Goto FollowPlayer;
		
		
		
	Pathfind:
		TNT1 A 0;
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 A_JumpIFInTargetInventory("IsPLayer", 1, 1);
	Goto FollowPLayer;
		TNT1 A 0 A_Noblocking;
		TNT1 A 0 A_SpawnItemEx ("Marine1Pathfinder",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETTARGET,0);
	Stop;
		
		
		
	Waits:
		MARN D 1;
		TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 1, 2);
		TNT1 A 0 A_ClearTarget;
		Goto See;
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 {bmissilemore = true;}
		TNT1 A 0 {bmissileevenmore = true;}
		TNT1 A 0 {bshootable = false;}
		TNT1 A 0 {bsolid = false;}
		TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "BecomeEnemy23");
		TNT1 A 0 A_Jump(32, "Waits2");
		
		MARN D 8 A_Stop;
		MARN E 8 A_Stop;
		TNT1 A 0 A_Stop;
		TNT1 A 0 A_CheckSight("FollowPlayer");
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_ClearTarget;
		
		TNT1 A 0 {bshootable = true;}
		MARN D 0 A_Look;
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 {bshootable = false;}
		MARN D 1 A_LookEx(0, 0, 0, 0, 0, "FollowPlayer");
		TNT1 A 0 A_CheckSIght("FollowPlayer");
		TNT1 A 0 {bshootable = true;}
		TNT1 A 0 A_JumpIfCloser(200, "Waits");
		Goto FollowPlayer;
		
	Waits2:
		TNT1 A 0 A_SetAngle(random(90, -90) + angle);
		MARN D 8 A_Stop;
		TNT1 A 0 A_PlaySound("MRNWT", 2);
		MARN E 8 A_Stop;
		TNT1 A 0 A_CheckSight("FollowPlayer");
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_ClearTarget;
		
		TNT1 A 0 {bshootable = true;}
		MARN D 0 A_Look;
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 {bshootable = false;}
		MARN D 1 A_LookEx(0, 0, 0, 0, 0, "FollowPlayer");
		TNT1 A 0 A_CheckSIght("FollowPlayer");
		TNT1 A 0 {bshootable = true;}
		TNT1 A 0 A_JumpIfCloser(300, "Waits");
		Goto FollowPLayer;
		
	Waits3:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInTargetInventory("Clip2", 40, 3);
		Goto GiveAmmo;
		TNT1 AAA 0;
		TNT1 A 0 A_SetAngle(random(90, -90) + angle);
		MARN D 8 A_Stop;
		TNT1 A 0 A_PlaySound("MRNWC", 2);
		MARN E 8 A_Stop;
		TNT1 A 0 A_CheckSight("FollowPlayer");
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_ClearTarget;
		
		TNT1 A 0 {bshootable = true;}
		MARN D 0 A_Look;
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 {bshootable = false;}
		MARN D 1 A_LookEx(0, 0, 0, 0, 0, "FollowPlayer");
		TNT1 A 0 A_CheckSIght("FollowPlayer");
		TNT1 A 0 {bshootable = true;}
		TNT1 A 0 A_JumpIfCloser(300, "Waits");
		Goto FollowPLayer;
		
	GiveAmmo:
		TNT1 A 0;
		MR7S A 10 A_FaceTarget;
		TNT1 A 0 A_PlaySound("MRNGI1");
		MR8S CD 15;
		TNT1 A 0 A_GiveToTarget("Clip2", 50);
		//TNT1 A 0 A_SpawnItemEx("Stimpack", 40, 0)
		Goto Waits;
		
	Missile:
		TNT1 A 0 {bnodropoff = true;}
		TNT1 A 0 doomb_trigger_monsters(cursector);
		TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
		TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
		TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 1, "CheckRangeToWait");
		TNT1 A 0 {bshootable = true;}
		TNT1 A 0 {bsolid = true;}
		
		TNT1 A 0 A_JumpIfCloser(60, "AttackMelee");
		TNT1 A 0 A_JumpIfCloser(300, "Retreat");
		TNT1 A 0 A_PlaySound("MRNAT", 2);
		
		TNT1 A 0 A_Jump(128, "MissileLeft", "MissileRight");
		
		PLAY E 6 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		PLAY F 3 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 40, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		tnt1 a 0 A_CPosREfire;
	Goto See;
		
	MissileLeft:
		MARN A 2
		{
			A_FaceTarget();
			vel.xy += (3 * sin(angle - 90), 3 * cos(angle - 90) );
		}
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		tnt1 a 0 a_jump(140, "MissileLeft");
	Goto See;
		
		
		
	MissileRight:
		MARN A 2
			{
				A_FaceTarget();
				vel.xy += (3 * sin(angle + 90), 3 * cos(angle + 90) );
			}
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		tnt1 a 0 a_jump(140, "MissileLeft");
	Goto See;

		
	CheckRetreat:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(500, "Retreat");
		TNT1 A 0 A_Jump(256, "MissileRight", "MissileLeft");
		Goto MissileRight;
		
	Retreat:
		TNT1 A 0;
		MARN A 3 A_FaceTarget;
		TNT1 A 0 A_Recoil(5);
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 3 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);

		TNT1 A 0 A_Jump(128, "MissileRight", "MissileLeft");
		tnt1 a 0 a_jump(140, "Retreat");
	Goto See;
		
		
		
	AttackMelee:
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "AttackKick");
		PLAM A 4 A_FaceTarget;
		TNT1 A 0 A_Recoil(-4);
		PLAM A 1 A_FaceTarget;
		PLAM B 4 A_SpawnProjectile("MarinePunch",40,0,0,0);
		PLAM B 2;
		TNT1 A 0 A_JumpIfInventory("ZombiemanFatality3", 1, "FatalityZombieman");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
		TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		TNT1 A 0 A_JumpIfInventory("RevenantFatality", 1, "FatalityRevenant");
		Goto See;
		
		
	AttackKick:
		PLAY A 1 
			{
				A_FaceTarget();
				vel.xy += (40 * sin(angle), 40 * cos(angle) );
			}
		TNT1 A 0 A_Recoil(-8);
		MARJ A 6 A_FaceTarget;
		AKIK A 1 A_SpawnProjectile("AirKickAttack",40,0,0,0);
		TNT1 A 0 A_Stop;
		AKIK A 6;
		TNT1 A 0 A_JumpIfInventory("ZombiemanFatality3", 1, "FatalityZombieman");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
		TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		TNT1 A 0 A_JumpIfInventory("RevenantFatality", 1, "FatalityRevenant");
		Goto See;
		
	Pain.Kick:
		PLAY A 2 A_FaceTarget;
		TNT1 A 0 A_Recoil(5);
		Goto FollowPlayer;
		
		
	Pain:
		PLAY G 3;
		TNT1 A 0 {bnodropoff = false;}
		PLAY G 3 A_Pain;
		Goto FollowPlayer;
		
		

}
}




CLASS RifleMarineGuarding: Marine_Rifle { 
	Default {
	
	FastSpeed 0;
	MaxStepHeight 0;
	+FRIENDLY;
	+MISSILEMORE;
	+NODROPOFF;
	+MISSILEEVENMORE;
	+DONTSPLASH;
	Speed 0;
	}
	States
	{
	Active:
		TNT1 A 0 {bnoclip = true;}
		TNT1 A 0 A_PlaySound("MarineFollow", 2);
		TNT1 A 0 A_SpawnProjectile ("OrderTitle1", 50, 0, 0, 2, 90);
		MR7S A 30;
		TNT1 A 0 {bnoclip = true;}
		TNT1 A 0 A_SpawnItemEx ("Marine_Rifle",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
		
	Spawn:
		TNT1 A 0;
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_GiveInventory("TargetIsAMarine");
		MARN D 1 A_Look;
		Goto See;
		
	See:
		//TNT1 A 0 A_SetAngle(random(90, -90) + angle)
		TNT1 A 0 {bshootable = false;}
		TNT1 A 0 {bsolid = false;}
		MARN DDDDDDDDDDEEEEEEEEE 1 A_Chase;
		TNT1 A 0 A_ClearTarget;
		Loop;
		
		
	Missile:
		TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 doomb_trigger_monsters(cursector);
			TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
		TNT1 A 0 {bshootable = true;}
		TNT1 A 0 {bsolid = true;}
		
		TNT1 A 0 A_PlaySound("MRNAT", 2);

		PLAY E 6 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		PLAY F 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 40, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);

		TNT1 A 0 A_CPosREfire;
	Goto See;
		
	MissileLeft:
		MARN A 2
			{
				A_FaceTarget();
				vel.xy += (3 * sin(angle - 90), 3 * cos(angle - 90) );
			}
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		tnt1 a 0 a_jump(140, "MissileLeft");
	Goto See;
		
		
		
	MissileRight:
		MARN A 2 
			{
				A_FaceTarget();
				vel.xy += (3 * sin(angle + 90), 3 * cos(angle + 90) );
			}
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		tnt1 a 0 a_jump(140, "MissileLeft");
	Goto See;
		
	CheckRetreat:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(500, "Retreat");
		TNT1 A 0 A_Jump(256, "MissileRight", "MissileLeft");
	Goto MissileRight;
		
	Retreat:
		TNT1 A 0;
		MARN A 2 A_FaceTarget;
		TNT1 A 0 A_Recoil(4);
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		
		TNT1 A 0 A_Recoil(4);
		MARN C 2 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		
		MARN A 2 A_FaceTarget;
		TNT1 A 0 A_Recoil(4);
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		
		MARN C 2 A_FaceTarget;
		TNT1 A 0 A_Recoil(4);
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_Jump(128, "MissileRight", "MissileLeft");
		Goto See;
		
	Pain.Kick:
		PLAY A 2 A_FaceTarget;
		TNT1 A 0 A_Recoil(5);
		Goto See;
		
		
	Pain:
		PLAY G 3;
		PLAY G 3 A_Pain;
		TNT1 A 0 A_Jump(128, "MissileLeft", "MissileRight");
		Goto See;
}
}

CLASS Ally: DeadMarine { 
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump(192,"Spawn2","Spawn2","Spawn3","Spawn4","Spawn4","Spawn5","Spawn6","Spawn7","Spawn8","Spawn8");
		TNT1 A 1 A_SpawnItem("Marine",0,0,0,0);
		Stop;
		
	Spawn2:
		TNT1 A 1 A_SpawnItem("MarineShotgun",0,0,0,0);
		Stop;
		
	Spawn3:
		TNT1 A 1 A_SpawnItem("MarineSSG",0,0,0,0);
		Stop;
		
	Spawn4:
		TNT1 A 1 A_SpawnItem("MarineChaingun",0,0,0,0);
		Stop;
		
	Spawn5:
		TNT1 A 1 A_SpawnItem("MarinePlasma",0,0,0,0);
		Stop;
		
	Spawn6:
		Goto Spawn;
		Stop;
		
	Spawn7:
		TNT1 A 1 A_SpawnItem("MarineRocket",0,0,0,0);
		Stop;
		
	Spawn8:
		TNT1 A 1 A_SpawnItem("Marine",0,0,0,0);
		Stop;
		
	Death:
		Stop;
}
}



CLASS TargetIsAMarine : Inventory { 
	Default {
	
	inventory.maxamount 1;
	}
}


CLASS BotIsChasingYou : Inventory { 
	Default {
	
	inventory.maxamount 1;
	}
}


CLASS NumberOfAllies : Inventory { 
	Default {
	
	inventory.maxamount 5;
	}
}

CLASS MarinesDispenser : Inventory { 
	Default {
	
	inventory.maxamount 5;
	}
}

CLASS MarinesChaingunDispenser : Inventory { 
	Default {
	
	inventory.maxamount 5;
	}
}

CLASS CheckMarines : Inventory { 
	Default {
	
	inventory.maxamount 1;
	}
}



CLASS Marine1Pathfinder : ACTOR { 
	Default {
	
	Radius 32;
	Height 56;
	Speed 20;
	Health 4000;
	PainChance 255;
	MaxTargetRange 150;
	Monster;
	damagefactor "SpawnMarine", 8000.0;
	MaxDropOffHeight 1200;
	MaxStepHeight 1200;
	-COUNTKILL;
	+NOTARGET;
	+THRUACTORS;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+DONTSPLASH;
	-SHOOTABLE;
	-FRIENDLY;
	+NOCLIP;
	+LOOKALLAROUND;
	+NOINFIGHTING;
	}
	States
	{
	Spawn:
	Pain:
	See:
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0;
		TNT1 A 0 A_GiveInventory("TargetIsAMarine", 1);
		TNT1 AAAAA 1 A_Chase;
		TNT1 A 0;
		TNT1 A 0 A_GiveInventory("TargetIsAMarine", 1);
		TNT1 A 1 A_FaceTarget;
	Loop;

	Death:
	Missile:
		TNT1 A 1 A_Recoil(-2);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItemEx(target.getclassname(),0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItem("TeleportFog");
		Stop;
}
}


CLASS MarineAdd: Marine1Pathfinder { 
	Default {
	Speed 4;
	}
	States
	{
	Death:
	Missile:
		TNT1 A 1;
		TNT1 A 0 A_GiveToTarget("NumberOfAllies", 1);
	Stop;
}
}

CLASS RemoveMarine : ACTOR { 
	States
	{
	Spawn:
	Pain:
	See:
		TNT1 A 1;
		TNT1 A 0 A_SpawnItemEx("RemoveMarineActivate",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 1;
		Stop;
}
}

CLASS RemoveMarineActivate: Marine1Pathfinder { 
	Default {
	
	-FRIENDLY;
	-SHOOTABLE;
	Scale 1.0;
	Speed 1;
	MaxTargetRange 90000;
	}
	States
	{
	Missile:
		TNT1 A 1;
		TNT1 A 0 A_TakeFromTarget("NumberOfAllies", 1);
		TNT1 A 1;
	Stop;
}
}




CLASS MarineSpawnChecker : ACTOR { 
	Default {
	
	MONSTER;
	-COUNTKILL;
	+FRIENDLY;
	-SOLID;
	-SHOOTABLE;
	Health 1;
	Radius 16;
	Height 52;
	Damagetype "SpawnMarine";
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_GiveInventory("TargetIsAMarine", 1);
		TNT1 A 0 A_AlertMonsters;
		TNT1 A 0 A_Explode(25, 40);
		Stop;
	Death:
		TNT1 A 1;
		Stop;
}
}