CLASS Marine_Rifle : doomb_marine_base Replaces MarinePistol
{
	Default 
	{
		doomb_marine_base.spare_ammo "doomb_clip";
		DropItem "Rifle";
	}

	States
	{
	Active:
		TNT1 A 0 {bnoclip = true;}
		TNT1 A 0 A_PlaySound("MarineGuard", 2);
		TNT1 A 0 A_SpawnProjectile ("OrderTitle2", 50, 0, 0, 2, 90);
		MR7S A 30;
		TNT1 A 0 A_SpawnItemEx ("RifleMarineGuarding",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;
		
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_GiveInventory("TargetIsAMarine");
		PLAY A 1 A_Look;
		Goto See;
		
	ForgetTarget:
		TNT1 A 0 A_ClearTarget;
		Goto See;
		
	See:
		TNT1 A 0 A_JumpIfInventory("ZombiemanFatality3", 1, "FatalityZombieman");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
		TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		TNT1 A 0 A_JumpIfInventory("RevenantFatality", 1, "FatalityRevenant");
		tnt1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
		PLAY AABBCCDD 1
		{
			A_Chase();
			A_Recoil(-1);
		}
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_JumpIfCloser(200, "Waits");
		TNT1 A 0 A_CheckSight("ForgetTarget");
		TNT1 A 0 A_CheckSight("FollowPLayer");
		TNT1 A 0 A_CheckSight("CheckIfPlayerSee");
	Goto See;

	BecomeEnemy23:
		PLAY A 1;
		TNT1 A 0 A_ClearTarget;
		TNT1 A 0 {bshootable = false;}
		TNT1 A 0 {bfriendly = false;}
	FollowPlayer:
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 {bshootable = false;}
		TNT1 A 0 A_JumpIfCloser(150, "Waits");
		TNT1 A 0 {bmissilemore = false;}
		TNT1 A 0 {bmissileevenmore = false;}
		PLAY A 1 A_Chase;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_Recoil(-1);
		PLAY AABBCCDD 1
		{
			A_Chase();
			A_Recoil(-1);
		}
		TNT1 A 0 A_CheckSight("CheckIfPlayerSee");
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_JumpIfTargetInLOS("See");
		TNT1 A 0 {bfriendly = false;}
	Loop;
		
	CheckRangeToWait:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(150, "Waits");
		Goto FollowPLayer;
		
	CheckIfPlayerSee:
		TNT1 A 0;
		PLAY AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_FastChase;
		TNT1 A 0 {bshootable = false;}
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 A_JumpIfCloser(800, 2);
		Goto Pathfind;
		TNT1 AAA 0;
		Goto FollowPlayer;
		
		
		
	Pathfind:
		TNT1 A 0;
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 A_JumpIFInTargetInventory("IsPLayer", 1, 1);
	Goto FollowPLayer;
		TNT1 A 0 A_Noblocking;
		TNT1 A 0 A_SpawnItemEx ("Marine1Pathfinder",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETTARGET,0);
	Stop;
		
		
		
	Waits:
		MARN D 1;
		TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 1, 2);
		TNT1 A 0 A_ClearTarget;
		Goto See;
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 {bmissilemore = true;}
		TNT1 A 0 {bmissileevenmore = true;}
		TNT1 A 0 {bshootable = false;}
		TNT1 A 0 {bsolid = false;}
		TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "BecomeEnemy23");
		
		MARN DE 8 A_Stop;
		TNT1 A 0 A_Stop;
		TNT1 A 0 A_CheckSight("FollowPlayer");
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_ClearTarget;
		
		TNT1 A 0 {bshootable = true;}
		MARN D 0 A_Look;
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 {bshootable = false;}
		MARN D 1 A_LookEx(0, 0, 0, 0, 0, "FollowPlayer");
		TNT1 A 0 A_CheckSIght("FollowPlayer");
		TNT1 A 0 {bshootable = true;}
		TNT1 A 0 A_JumpIfCloser(200, "Waits");
		Goto FollowPlayer;
		
	Waits3:
		TNT1 A 0;
		Goto GiveAmmo;
		TNT1 AAA 0;
		TNT1 A 0 A_SetAngle(random(90, -90) + angle);
		MARN D 8 A_Stop;
		TNT1 A 0 A_PlaySound("MRNWC", 2);
		MARN E 8 A_Stop;
		TNT1 A 0 A_CheckSight("FollowPlayer");
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_ClearTarget;
		
		TNT1 A 0 {bshootable = true;}
		MARN D 0 A_Look;
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 {bshootable = false;}
		MARN D 1 A_LookEx(0, 0, 0, 0, 0, "FollowPlayer");
		TNT1 A 0 A_CheckSIght("FollowPlayer");
		TNT1 A 0 {bshootable = true;}
		TNT1 A 0 A_JumpIfCloser(300, "Waits");
		Goto FollowPLayer;
		
	GiveAmmo:
		TNT1 A 0;
		MR7S A 10 A_FaceTarget;
		TNT1 A 0 A_PlaySound("MRNGI1");
		MR8S CD 15;
		//TNT1 A 0 A_SpawnItemEx("Stimpack", 40, 0)
		Goto Waits;
		
	Missile:
		TNT1 A 0 {bnodropoff = true;}
		TNT1 A 0 doomb_trigger_monsters(cursector);
		TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
		TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
		TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 1, "CheckRangeToWait");
		TNT1 A 0 {bshootable = true;}
		TNT1 A 0 {bsolid = true;}
		
		TNT1 A 0 A_JumpIfCloser(60, "AttackMelee");
		TNT1 A 0 A_JumpIfCloser(300, "Retreat");
		TNT1 A 0 A_PlaySound("MRNAT", 2);
		
		TNT1 A 0 A_Jump(128, "MissileLeft", "MissileRight");
		
		PLAY E 6 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		PLAY F 3 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 40, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		tnt1 a 0 A_CPosREfire;
	Goto See;
		
	MissileLeft:
		MARN A 2
		{
			A_FaceTarget();
			vel.xy += (3 * sin(angle - 90), 3 * cos(angle - 90) );
		}
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		tnt1 a 0 a_jump(140, "MissileLeft");
	Goto See;


	MissileRight:
		MARN A 2
			{
				A_FaceTarget();
				vel.xy += (3 * sin(angle + 90), 3 * cos(angle + 90) );
			}
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		tnt1 a 0 a_jump(140, "MissileLeft");
	Goto See;

		
	CheckRetreat:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(500, "Retreat");
		TNT1 A 0 A_Jump(256, "MissileRight", "MissileLeft");
		Goto MissileRight;
		
	Retreat:
		TNT1 A 0;
		MARN A 3 A_FaceTarget;
		TNT1 A 0 A_Recoil(5);
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 3 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);

		TNT1 A 0 A_Jump(128, "MissileRight", "MissileLeft");
		tnt1 a 0 a_jump(140, "Retreat");
	Goto See;
		
		
		
	AttackMelee:
		TNT1 A 0;
		TNT1 A 0 A_Jump(32, "AttackKick");
		PLAM A 4 A_FaceTarget;
		TNT1 A 0 A_Recoil(-4);
		PLAM A 1 A_FaceTarget;
		PLAM B 4 A_SpawnProjectile("MarinePunch",40,0,0,0);
		PLAM B 2;
		TNT1 A 0 A_JumpIfInventory("ZombiemanFatality3", 1, "FatalityZombieman");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
		TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		TNT1 A 0 A_JumpIfInventory("RevenantFatality", 1, "FatalityRevenant");
		Goto See;
		
		
	AttackKick:
		PLAY A 1 
			{
				A_FaceTarget();
				vel.xy += (40 * sin(angle), 40 * cos(angle) );
			}
		TNT1 A 0 A_Recoil(-8);
		MARJ A 6 A_FaceTarget;
		AKIK A 1 A_SpawnProjectile("AirKickAttack",40,0,0,0);
		TNT1 A 0 A_Stop;
		AKIK A 6;
		TNT1 A 0 A_JumpIfInventory("ZombiemanFatality3", 1, "FatalityZombieman");
		TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
		TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		TNT1 A 0 A_JumpIfInventory("RevenantFatality", 1, "FatalityRevenant");
		Goto See;
		
	Pain.Kick:
		PLAY A 2 A_FaceTarget;
		TNT1 A 0 A_Recoil(5);
		Goto FollowPlayer;
		
		
	Pain:
		PLAY G 3;
		TNT1 A 0 {bnodropoff = false;}
		PLAY G 3 A_Pain;
		Goto FollowPlayer;
		
		

}
}




CLASS RifleMarineGuarding: Marine_Rifle { 
	Default {
	
	FastSpeed 0;
	MaxStepHeight 0;
	+FRIENDLY;
	+MISSILEMORE;
	+NODROPOFF;
	+MISSILEEVENMORE;
	+DONTSPLASH;
	Speed 0;
	}
	States
	{
	Active:
		TNT1 A 0 {bnoclip = true;}
		TNT1 A 0 A_PlaySound("MarineFollow", 2);
		TNT1 A 0 A_SpawnProjectile ("OrderTitle1", 50, 0, 0, 2, 90);
		MR7S A 30;
		TNT1 A 0 {bnoclip = true;}
		TNT1 A 0 A_SpawnItemEx ("Marine_Rifle",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
		
	Spawn:
		TNT1 A 0;
		TNT1 A 0 {bfriendly = true;}
		TNT1 A 0 A_GiveInventory("TargetIsAMarine");
		MARN D 1 A_Look;
		Goto See;
		
	See:
		//TNT1 A 0 A_SetAngle(random(90, -90) + angle)
		TNT1 A 0 {bshootable = false;}
		TNT1 A 0 {bsolid = false;}
		MARN DDDDDDDDDDEEEEEEEEE 1 A_Chase;
		TNT1 A 0 A_ClearTarget;
		Loop;
		
		
	Missile:
		TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 doomb_trigger_monsters(cursector);
			TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
		TNT1 A 0 {bshootable = true;}
		TNT1 A 0 {bsolid = true;}
		
		TNT1 A 0 A_PlaySound("MRNAT", 2);

		PLAY E 6 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		PLAY F 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 40, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);

		TNT1 A 0 A_CPosREfire;
	Goto See;
		
	MissileLeft:
		MARN A 2
			{
				A_FaceTarget();
				vel.xy += (3 * sin(angle - 90), 3 * cos(angle - 90) );
			}
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		tnt1 a 0 a_jump(140, "MissileLeft");
	Goto See;
		
		
		
	MissileRight:
		MARN A 2 
			{
				A_FaceTarget();
				vel.xy += (3 * sin(angle + 90), 3 * cos(angle + 90) );
			}
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		tnt1 a 0 a_jump(140, "MissileLeft");
	Goto See;
		
	CheckRetreat:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfCloser(500, "Retreat");
		TNT1 A 0 A_Jump(256, "MissileRight", "MissileLeft");
	Goto MissileRight;
		
	Retreat:
		TNT1 A 0;
		MARN A 2 A_FaceTarget;
		TNT1 A 0 A_Recoil(4);
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		
		TNT1 A 0 A_Recoil(4);
		MARN C 2 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		
		MARN A 2 A_FaceTarget;
		TNT1 A 0 A_Recoil(4);
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		
		MARN C 2 A_FaceTarget;
		TNT1 A 0 A_Recoil(4);
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 34);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		MARN B 2 BRIGHT;
		TNT1 A 0 A_SpawnProjectile("MarineTracer", 42, 0, 0, 0);
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_Jump(128, "MissileRight", "MissileLeft");
		Goto See;
		
	Pain.Kick:
		PLAY A 2 A_FaceTarget;
		TNT1 A 0 A_Recoil(5);
		Goto See;
		
		
	Pain:
		PLAY G 3;
		PLAY G 3 A_Pain;
		TNT1 A 0 A_Jump(128, "MissileLeft", "MissileRight");
		Goto See;
}
}