CLASS Marine_PlasmaGunSpawn: RedTorch { 
	Default {
		
		Radius 10;
		Height 48;
		MONSTER;
		-SHOOTABLE;
		-COUNTKILL;
		-FRIENDLY;
	}
	States
	{
		Spawn:
			PLA6 A 10;
			PLA6 A 1 A_CheckSight("DontSpawn");
			TNT1 A 0 A_Chase;
			TNT1 A 0 A_Look;
		See:
			TNT1 A 0 A_GiveToTarget("NumberOfAlliesPlasmaGun", 1);
			TNT1 A 0 A_SpawnItemEx ("Marine_PlasmaGun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
		DontSpawn:
			PLA6 A 1;
			Goto Spawn;
	}
}

CLASS Marine_PlasmaGun: Marine_base { 
	Default {
		
		DropItem "PlasmaRifle";
	}

override int doomb_get_aditional_death_sprite()
{
	return GetSpriteIndex("PLA6");
}


	States
	{
		Active:
			TNT1 A 0 {bnoclip = true;}
			TNT1 A 0 A_PlaySound("MarineGuard", 2);
			TNT1 A 0 A_SpawnProjectile ("OrderTitle2", 50, 0, 0, 2, 90);
			PLA6 A 30;
			TNT1 A 0 {bnoclip = true;}
			TNT1 A 0 A_SpawnItemEx ("PlasmaGunMarineGuarding",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_GiveInventory("TargetIsAMarine");
			PLA6 A 1 A_Look;
			Goto See;
			
		ForgetTarget:
			TNT1 A 0 A_ClearTarget;
			Goto See;
			
		See:
			TNT1 A 0 {bnodropoff = false;}
			TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
			
			
			TNT1 A 0 {bmissilemore = true;}
			TNT1 A 0 {bmissileevenmore = true;}
			PLA6 AABBCCDD 1
			{
				A_Chase();
				A_Recoil(-1);
			}
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 1, "FollowPlayer");
			TNT1 A 0 A_JumpIfCloser(200, "Waits");
			TNT1 A 0 A_CheckSight("CheckIfPlayerSee");
			TNT1 A 0 A_JumpIfCloser(200, "Waits");
		Goto See;

		BecomeEnemy23:
			PLA6 A 1;
			TNT1 A 0 A_ClearTarget;
			TNT1 A 0 {bshootable = false;}
			TNT1 A 0 {bfriendly = false;}
			Goto FollowPlayer;
			
		FollowPlayer:
			TNT1 A 0 {bfriendly = false;}
			TNT1 A 0 {bshootable = false;}
			TNT1 A 0 A_JumpIfCloser(150, "Waits");
			TNT1 A 0 {bmissilemore = false;}
			TNT1 A 0 {bmissileevenmore = false;}
			PLA6 A 1 A_Chase;
			TNT1 A 0 A_Recoil(-1);
			TNT1 A 0 A_Recoil(-1);
			PLA6 AABBCCDD 1
			{
				A_Chase();
				A_Recoil(-1);
			}

			TNT1 A 0 A_CheckSight("CheckIfPlayerSee");
			TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 A_JumpIfTargetInLOS("See");
			TNT1 A 0 {bfriendly = false;}
		Loop;
			
		CheckRangeToWait:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(150, "Waits");
			Goto FollowPLayer;
			
		CheckIfPlayerSee:
			TNT1 A 0;
			PLA6 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_FastChase;
			TNT1 A 0 {bshootable = false;}
			TNT1 A 0 {bfriendly = false;}
			////TNT1 A 0 Thing_Hate(94, 0, 0)
			TNT1 A 0 A_JumpIfCloser(800, 2);
			Goto Pathfind;
			TNT1 AAA 0;
			Goto FollowPlayer;
			
			
			
	Pathfind:
		TNT1 A 0;
		TNT1 A 0 {bfriendly = false;}
		TNT1 A 0 A_JumpIFInTargetInventory("IsPLayer", 1, 1);
	Goto FollowPLayer;
		TNT1 A 0 A_Noblocking;
		TNT1 A 0 A_SpawnItemEx ("Marine1Pathfinder",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION|SXF_SETTARGET,0);
	Stop;
			
			
			
		Waits:
			PLA6 H 1;
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 1, 2);
			TNT1 A 0 A_ClearTarget;
			Goto See;
			TNT1 A 0 {bfriendly = false;}
			TNT1 A 0 {bmissilemore = true;}
			TNT1 A 0 {bmissileevenmore = true;}
			TNT1 A 0 {bshootable = false;}
			TNT1 A 0 {bsolid = false;}
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "BecomeEnemy23");
			TNT1 A 0 A_JumpIfInTargetInventory("Clip2", 50, 3);

			PLA6 H 8 A_Stop;
			PLA6 E 8 A_Stop;
			TNT1 A 0 A_CheckSight("FollowPlayer");
			TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 A_ClearTarget;
			
			TNT1 A 0 {bshootable = true;}
			MARN D 0 A_Look;
			TNT1 A 0 {bfriendly = false;}
			TNT1 A 0 {bshootable = false;}
			PLA6 E 1 A_LookEx(0, 0, 0, 0, 0, "FollowPlayer");
			TNT1 A 0 A_CheckSIght("FollowPlayer");
			TNT1 A 0 {bshootable = true;}
			TNT1 A 0 A_JumpIfCloser(200, "Waits");
		Goto FollowPlayer;

		GiveAmmo:
			TNT1 A 0;
			PLA6 A 10 A_FaceTarget;
			TNT1 A 0 A_PlaySound("MRNGI1");
			PLA6 I 30;
			TNT1 A 0 A_GiveToTarget("Clip2", 100);
			//TNT1 A 0 A_SpawnItemEx("Stimpack", 40, 0)
			Goto Waits;
			
		Missile:
			//PLA6 E 1
			TNT1 A 0 {bnodropoff = true;}
			TNT1 A 0 A_SpawnItem("KillMeSmall");
			TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMarine", 1, "FollowPLayer");//
			TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 1, "CheckRangeToWait");
			TNT1 A 0 {bshootable = true;}
			TNT1 A 0 {bsolid = true;}
			TNT1 A 0 A_JumpIfCloser(300, "Retreat");
			TNT1 A 0 A_PlaySound("MRNAT", 2);
			
		Missile2:
			TNT1 A 0 {bshootable = true;}
			TNT1 A 0 {bsolid = true;}
			PLA6 E 3 A_FaceTarget;
			
			TNT1 A 0 A_PlaySound("PLSM9", CHAN_WEAPON);
			PLA6 F 2 BRIGHT A_SpawnProjectile("Plasma_Ball",40,0,0,0);
			tnt1 a 0 a_jump(200, "missile2");
		Goto See;
			
		StrafeLeft:
			PLA6 A 3 A_FaceTarget;
			PLA6 B 3 ThrustThing(angle*256/360+192, 3, 0, 0);
			PLA6 C 3 A_FaceTarget;
			PLA6 D 3 ThrustThing(angle*256/360+192, 3, 0, 0);
			Goto Missile2;
			
		StrafeRight:
			PLA6 A 3 A_FaceTarget;
			PLA6 B 3 ThrustThing(angle*256/360+64, 3, 0, 0);
			PLA6 C 3 A_FaceTarget;
			PLA6 D 3 ThrustThing(angle*256/360+64, 3, 0, 0);
			Goto Missile2;
			
		CheckRetreat:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(500, "Retreat");
		Pain.Avoid:
			TNT1 A 0 A_Jump(256, "StrafeLeft", "StrafeRight");
			Goto StrafeLeft;
			
		Retreat:
			TNT1 A 0;
			PLA6 A 3 A_FaceTarget;
			TNT1 A 0 A_Recoil(5);
			PLA6 B 3;
			TNT1 A 0 A_Recoil(5);
			PLA6 CD 3 A_FaceTarget;
			Goto MIssile2;
			
			
			
		AttackMelee:
			TNT1 A 0;
			PLAM A 4 A_FaceTarget;
			TNT1 A 0 A_Recoil(-4);
			PLAM A 1 A_FaceTarget;
			PLAM B 4 A_SpawnProjectile("MarinePunch",40,0,0,0);
			PLAM B 2;
			TNT1 A 0 A_JumpIfInventory("ZombiemanFatality3", 1, "FatalityZombieman");
			TNT1 A 0 A_JumpIfInventory("ImpFatality3", 1, "FatalityImp");
			TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			TNT1 A 0 A_JumpIfInventory("RevenantFatality", 1, "FatalityRevenant");
			Goto See;
			
		Pain:
			PLA6 G 3;
			TNT1 A 0 {bnodropoff = false;}
			PLA6 G 3 A_Pain;
			Goto FollowPlayer;
			
			
			
			

			
			
			
	}
}




CLASS PlasmaGunMarineGuarding: Marine_PlasmaGun { 
	Default {
		
		FastSpeed 0;
		MaxStepHeight 0;
		+FRIENDLY;
		+MISSILEMORE;
		+NODROPOFF;
		+MISSILEEVENMORE;
		+SHOOTABLE;
		Speed 0;
	}
	States
	{
		Active:
			TNT1 A 0 {bnoclip = true;}
			TNT1 A 0 A_PlaySound("MarineFollow", 2);
			TNT1 A 0 A_SpawnProjectile ("OrderTitle1", 50, 0, 0, 2, 90);
			PLA6 A 30;
			TNT1 A 0 {bnoclip = true;}
			TNT1 A 0 A_SpawnItemEx ("Marine_PlasmaGun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 A_GiveInventory("TargetIsAMarine");
			PLA6 E 1 A_Look;
			Goto See;
			
		See:
			//TNT1 A 0 A_SetAngle(random(90, -90) + angle)
			TNT1 A 0 {bshootable = false;}
			TNT1 A 0 {bsolid = false;}
			PLA6 EEEEEEEEEEHHHHHHHHH 1 A_Chase;
			TNT1 A 0 A_ClearTarget;
			Loop;
			
			
			
		Missile:
			TNT1 A 0 {bfriendly = true;}
			TNT1 A 0 A_SpawnItem("KillMeSmall");
			TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
			TNT1 A 0 {bshootable = true;}
			TNT1 A 0 {bsolid = true;}
			
		Missile2:
			TNT1 A 0 {bshootable = true;}
			TNT1 A 0 {bsolid = true;}
			TNT1 A 0 A_PlaySound("PLSM9", CHAN_WEAPON);
			PLA6 F 2 BRIGHT A_SpawnProjectile("Plasma_Ball",40,0,0,0);
			PLA6 E 3 A_FaceTarget;
			
			TNT1 A 0 A_PlaySound("PLSM9", CHAN_WEAPON);
			PLA6 F 2 BRIGHT A_SpawnProjectile("Plasma_Ball",40,0,0,0);
			PLA6 E 3 A_FaceTarget;
			
			TNT1 A 0 A_PlaySound("PLSM9", CHAN_WEAPON);
			PLA6 F 2 BRIGHT A_SpawnProjectile("Plasma_Ball",40,0,0,0);
			PLA6 E 3 A_FaceTarget;
			
			TNT1 A 0 A_PlaySound("PLSM9", CHAN_WEAPON);
			PLA6 F 2 BRIGHT A_SpawnProjectile("Plasma_Ball",40,0,0,0);
			PLA6 E 3 A_FaceTarget;
			
			TNT1 A 0 A_PlaySound("PLSM9", CHAN_WEAPON);
			PLA6 F 2 BRIGHT A_SpawnProjectile("Plasma_Ball",40,0,0,0);
			PLA6 E 3 A_FaceTarget;
			Goto See;
			
			
		Pain:
			PLA6 G 3;
			PLA6 G 3 A_Pain;
			TNT1 A 0 A_Jump(128, "StrafeLeft", "StrafeRight");
			Goto See;
			
		StrafeLeft:
			PLA6 A 3 A_FaceTarget;
			PLA6 B 3 ThrustThing(angle*256/360+192, 3, 0, 0);
			PLA6 C 3 A_FaceTarget;
			PLA6 D 3 ThrustThing(angle*256/360+192, 3, 0, 0);
			Goto Missile2;
			
		StrafeRight:
			PLA6 A 3 A_FaceTarget;
			PLA6 B 3 ThrustThing(angle*256/360+64, 3, 0, 0);
			PLA6 C 3 A_FaceTarget;
			PLA6 D 3 ThrustThing(angle*256/360+64, 3, 0, 0);
			Goto Missile2;
	}
}

CLASS Marine_PlasmaGunPathfinder : ACTOR { 
	Default {
		
		Radius 32;
		Height 56;
		Speed 20;
		Health 4000;
		PainChance 255;
		MaxTargetRange 150;
		Monster;
		damagefactor "SpawnMarine", 8000.0;
		MaxDropOffHeight 1200;
		MaxStepHeight 1200;
		-COUNTKILL;
		+NOTARGET;
		+THRUACTORS;
		+MISSILEMORE;
		+MISSILEEVENMORE;
		+DONTSPLASH;
		-SHOOTABLE;
		-FRIENDLY;
		+NOCLIP;
		+LOOKALLAROUND;
		+NOINFIGHTING;
	}
	States
	{
		Spawn:
		Pain:
		See:
			TNT1 A 0 {bfriendly = false;}
			//TNT1 A 0 Thing_ChangeTID(0,98)
			//TNT1 A 0 Thing_Hate(98, 0, 0)
			TNT1 A 0;
			TNT1 A 0 A_GiveInventory("TargetIsAMarine", 1);
			TNT1 AAAAA 1 A_Chase;
			//TNT1 A 0 Thing_Hate(98, 0, 0)
			TNT1 A 0;
			TNT1 A 0 A_GiveInventory("TargetIsAMarine", 1);
			TNT1 A 1 A_FaceTarget;
			Loop;
			//Missile:
			TNT1 A 2;
			TNT1 A 0 A_SpawnItem("MarineSpawnChecker");
			TNT1 A 5;
			Goto See;
		Death:
		Missile:
			TNT1 A 0;
			TNT1 A 0 A_Recoil(-2);
			TNT1 A 2;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItemEx("Marine_PlasmaGun",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItem("TeleportFog");
			Stop;
	}
}

CLASS Marine_PlasmaGunAdd: Marine1Pathfinder { 
	Default {
		
		Speed 4;
	}
	States
	{
		Death:
		Missile:
			TNT1 A 1;
			TNT1 A 0 A_GiveToTarget("NumberOfAlliesPlasmaGun", 1);
			Stop;
	}
}