CLASS doomb_Marine_PlasmaGun: doomb_marine_base
{ 
	Default {
		doomb_marine_base.spare_ammo "doomb_cells";
		
		DropItem "PlasmaRifle";
	}

override int doomb_get_aditional_death_sprite()
{
	return GetSpriteIndex("PLA6");
}


States
{
		
	Spawn:
		PLA6 A 1 
		{
			if(is_guarding() )
				setstatelabel("guard_see");

			A_Look();
			doomb_set_leader();
		}

	See:
		tnt1 a 0
		{
			if(is_guarding() )
				setstatelabel("guard_see");
		}
		PLA6 AABBCCDD 1
		{
			doomb_marine_chase("plasma_Melee", "missile", "plasma_on_guard");
		}
	loop;


		
	plasma_on_guard:
		PLA6 H 1 a_stop();
		PLA6 HEHEHE 8
		{
			a_look();
			if(doomb_sqrd_distance_to_leader() > 300 * 300)
				setstatelabel("see");
		
			//dont have sprites
			//doomb_try_share_ammo();
		}
		tnt1 a 0
		{
			angle += randompick(-40, -80, 40, 80);
		
			if(random(0, 10) <= 1)
				setstatelabel("wander_around");
		}
	loop;

	wander_around:
		PLA6 H 1 a_stop;
		tnt1 a 0
		{
			if(leader)
				a_face(leader);
			
			angle += random(-40, 40);
		}
		PLA6 AABBCCDDAABBCCDD 1
		{
			vel.xy = (10 * cos(angle), 10 * sin(angle) );
		}
		tnt1 a 0 {vel = (0, 0, 0);}
	goto plasma_on_guard;



	share_some_ammo:
		PLA6 A 10 A_FaceTarget;
		TNT1 A 0 A_PlaySound("MRNGI1");
		PLA6 I 30;
	Goto plasma_on_guard;
		
	Missile:
		TNT1 A 0
		{
			if(is_guarding() )
				setstatelabel("guard_fire");

			bnodropoff = true;

			doomb_trigger_monsters(cursector);
			doomb_if_boss_retreat(target, "CheckRetreat");
			A_PlaySound("MRNAT", 2);
		}
	Missile2:
		PLA6 E 3 A_FaceTarget;
		TNT1 A 0 A_PlaySound("PLSM9", CHAN_WEAPON);
		PLA6 F 2 BRIGHT A_SpawnProjectile("Plasma_Ball",40,0,0,0);
		tnt1 a 0 a_monsterrefire(200, "see");
	loop;
		
		
		
		
		
	plasma_Melee:
		PLAM A 4 A_FaceTarget;
		TNT1 A 0 A_Recoil(-4);
		PLAM A 1 A_FaceTarget;
		PLAM B 4 doomb_marine_punch(80, random(20, 60), 'marine_punch');
		PLAM B 2;
	Goto See;
		




		
	Retreat:
		PLA6 ABCD 3
		{
			A_FaceTarget();
			A_Recoil(5);
		}
	Goto MIssile2;
	
	Pain:
		PLA6 G 3 A_Pain;
		PLA6 G 3 A_Jump(128, "avoid");
	Goto see;
		
	CheckRetreat:
		tnt1 a 0
		{
			if(is_guarding() )
				setstatelabel("guard_fire");
		}
		TNT1 A 0 A_JumpIfCloser(500, "Retreat");
	Avoid:
		PLA6 ABCD 3
		{
			A_FaceTarget();
			int i = randompick(90, -90);
			vel.xy += (3 * cos(angle + i), 3 * sin(angle + i) );
		}
		tnt1 a 0
		{
			if(is_guarding() )
				setstatelabel("guard_fire");
		}
	Goto Missile2;			
		
		




		
	follow_player:
		TNT1 A 0 A_PlaySound("MarineFollow", 2);
		TNT1 A 0 A_SpawnProjectile ("OrderTitle1", 50, 0, 0, 2, -90);
		PLA6 A 3 {bnoclip = false;}
	goto see;

	guard_area:
		TNT1 A 0 A_PlaySound("MarineGuard", 2);
		TNT1 A 0 A_SpawnProjectile ("OrderTitle2", 50, 0, 0, 2, -90);
		PLA6 A 3 {bnoclip = true;}
		PLA6 E 1 A_Look;
	guard_see:
		PLA6 EEEEEEEEEEHHHHHHHHH 1 A_LookEx(label:"guard_fire");
		tnt1 a 0 {angle += random(-80, 80);}
	loop;
		
		
		
	guard_fire:
		TNT1 A 0 doomb_trigger_monsters(cursector);
		PLA6 F 3 BRIGHT
		{
			A_SpawnProjectile("Plasma_Ball",40,0,0,0);
			A_PlaySound("PLSM9", CHAN_WEAPON);
		}
		PLA6 E 3 A_FaceTarget;
		tnt1 a 0 a_monsterrefire(200, "guard_see");
	loop;
}

}