#include "brootol_dumb_z/gore/limbs/GORE!!!.zc"
#include "brootol_dumb_z/gore/limbs/GORE2.zc"
#include "brootol_dumb_z/gore/limbs/GORE3.zc"
#include "brootol_dumb_z/gore/limbs/gore_fixed.zc"
#include "brootol_dumb_z/gore/limbs/shared_parts.zc"
#include "brootol_dumb_z/gore/limbs/xdeath_collection.zc"
#include "brootol_dumb_z/gore/limbs/meat_death.zc"
#include "brootol_dumb_z/gore/limbs/head_explosion.zc"


//all base classes for body related actors
class doomb_body_base : doomb_monster_base abstract
{
protected bool bleeding;

default
{
    -ismonster
	-countkill
}

protected void doomb_random_death(name st = "")
{
	if(random(0, 10) > 7)
		a_die(st);
}


protected void doomb_meat_on_ceiling()
{
	FLineTraceData RemoteRay;

	LineTrace(
		random( 0, 360),
		60,
		-frandom(85 , 90),//- because thank you randi
		TRF_THRUACTORS | TRF_NOSKY,
		height + 1,
		data: RemoteRay
	);

	if (RemoteRay.HitType == TRACE_HitCeiling)
	{
		spawn("doomb_sticky_meat", pos:RemoteRay.HitLocation);
	}
}


protected void doomb_blood_dying()
{
	if(waterlevel < 1)
	{
		doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		A_SpawnItem ("BloodHit", 0, 30);
		doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	}
}

}


CLASS BigGibBase : doomb_body_base { 
	Default {
		Radius 10;
		Height 10;
		Mass 1000;
		Health 100;

		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+DONTSPLASH;
		+NOBLOCKMONST;
		-NOBLOCKMAP;
		+GHOST;
		+THRUACTORS;
		+FLOORCLIP;
		+SLIDESONWALLS;
		+FORCEXYBILLBOARD;
		-SOLID;
		+SHOOTABLE;
		DeathSound "misc/xdeath4";
	
		painchance 255;
		painchance "Fire", 0;

		damagefactor "Crush", 50.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0 ;
		damagefactor "Taunt", 0.0 ;
		damagefactor "Taunt", 0.0;
		damagefactor "Trample", 2.0;
		damagefactor "Kick", 9.0;
		damagefactor "punch", 2.0;
		damagefactor "Explosive_Impact", 9.1;
		damagefactor "Melee", 9.0;
		damagefactor "Plasma", 20.0;
	}
	States 
	{
		Spawn:
			TNT1 A 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;
			
			
		Death:
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		Stop;
			
		Death.plasma:
		Death.Fire:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(128, "DeathFire2");
			TNT1 A 0 doomb_spawn_burned_flesh();
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		Stop;
			
		DeathFire2:
			TNT1 A 0 doomb_spawn_burned_flesh();
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		Stop;
		
		Death.Trample:
		Death.Crush:
		Death.Stomp:
		Death.punch:
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash");
			TNT1 A 0 doomb_spawn_bloodpool();
			XME2 L -1;
		Stop;
		
		Death.Desintegrate:
			TNT1 A 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0
			{
				actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 35 ) );
				if(a)
					a.scale = (0.45, 0.45);
			}
		Stop;
	}
}

CLASS LimbBase: BigGibBase
{ 
States
{
	Spawn:
		TNT1 A 1900 doomb_spawn_bloodpool(BPS_SMALL);
	Loop;
	
	Death:
		TNT1 AAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		XDT3 BCDEFGH 3;
	Death.Crush:
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		CRSB A 9009;
	Stop;
}

}