CLASS TheCyberdemon : doomb_monster_base Replaces Cyberdemon { 
	Default {
		
		doomb_monster_base.headshot_multiplier 2;
		doomb_monster_base.head_starting_position 100;//so that if someone forgot to define this number monster dont get headshot from every attack
		doomb_monster_base.legs_height_max -1;//same for legs
		
		painchance "kick", 255;
		PainChance "Taunt", 255;
		damagefactor "Explosive_Impact", 1.1;
		damagefactor "HKFT", 0.05;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Crush", 20.0;

		BloodType "CyberDemon_Blood", "SawBlood", "SawBlood";
		DropItem "DemonStrengthRune", 25;
		Obituary "%o was exploded to pieces by a Cyberdemon.";
		SeeSound "cyber/sight";
		PainSound "cyber/pain";
		DeathSound "cyber/death";
		ActiveSound "cyber/active";

		Speed 16;
		Scale 1.2;
		Radius 45;
		Height 110;
		FastSpeed 22;
		mass 5000;
		Health 5000;
		MaxStepHeight 24;
		MaxDropOffHeight 32;
		doomb_monster_base.head_starting_position 90;
		doomb_monster_base.headshot_multiplier 1.5;

		+NOICEDEATH;
		+MISSILEMORE;
		+MISSILEEVENMORE;
		+DONTRIP;
		+NORADIUSDMG;
		+QUICKTORETALIATE;
		+boss
	}

	private void doomb_cyber_stomp()
	{
		if(target && target.health > 0)
		{
			//if( (abs(target.pos.x) - abs(pos.x))< 50 && (abs(target.pos.y) - abs(pos.y)) < 50 && (abs(target.pos.z) - abs(pos.z)) < 10)
			if( (abs(target.pos.x - pos.x))< 50 && (abs(target.pos.y - pos.y)) < 50 && (abs(target.pos.z - pos.z)) < 10)
				setstatelabel("stomp");
		}
	}

	States
	{
		Spawn:
			CYBR DZ 10 A_Look;
		Loop;
			
		See:
			TNT1 A 0 A_SpawnItem("HeavyFootSteps32");
			CYBR A 3 A_Hoof;

			CYBR AAA 2
			{
				A_Chase();
				doomb_cyber_stomp();
			}
			tnt1 a 0 A_SpawnItemEx("CyberStomp",12,-30);
			CYBR BBBBC 2
			{
				A_Chase();
				doomb_cyber_stomp();
			}
			CYBR C 2
			{
				A_Chase();
				A_SpawnItem("HeavyFootSteps32");
			}
			CYBR C 2;
			CYBR C 2 A_Metal;
			
			TNT1 A 0 A_SpawnItemEx("CyberStomp",12,30);
			CYBR DDDD 2
			{
				A_Chase();
				doomb_cyber_stomp();
			}
		Loop;
			
			
		Missile:
			TNT1 A 0 doomb_cyber_stomp();
			TNT1 A 0 A_JumpIfInventory("Enraged", 1, "SpecialAttack");
			
			CYBR EFEFEFEF 6
			{
				doomb_cyber_stomp();

				if(frame == 4)
					A_FaceTarget();
				if(frame == 5)
				{
					bBright = true;
					A_SpawnProjectile("CyberBalls",60,-25,0,0);
				}
			}
		Goto See;
			
		SpecialAttack:
			CYBR E 6 A_FaceTarget;
			CYBR F 4 BRIGHT A_SpawnProjectile("CyberBalls",60,-25,0,0);
			TNT1 A 0 A_JumpIfCloser(180, "Stomp");
			CYBR E 4 A_FaceTarget;
			CYBR F 4 BRIGHT A_SpawnProjectile("CyberBalls",60,-25,-7,0);
			TNT1 A 0 A_JumpIfCloser(180, "Stomp");
			CYBR E 4 A_FaceTarget;
			CYBR F 4 BRIGHT A_SpawnProjectile("CyberBalls",60,-25,7,0);
			TNT1 A 0 A_JumpIfCloser(180, "Stomp");
			CYBR E 4 A_FaceTarget;
			CYBR F 4 BRIGHT A_SpawnProjectile("CyberBalls",60,-25,0,0);
			TNT1 A 0 A_JumpIfCloser(180, "Stomp");
			CYBR E 4 A_FaceTarget;
			CYBR F 4 BRIGHT A_SpawnProjectile("CyberBalls",60,-25,0,0);
			CYBR E 4 A_FaceTarget;
			CYBR F 4 BRIGHT A_SpawnProjectile("CyberBalls",60,-25,0,0);
		Goto See;

		Stomp:
			tnt1 aaaaaaaaaaaaaaaaaaaaaaaaa 0;
			CYBR Z 5
			{
				A_FaceTarget();
				A_Recoil(-5);
			}
			CYMA A 7
			{
				A_FaceTarget();
				A_Spawnitem("CyberStomp", 30);
			}
			CYMA B 7;
		Goto See;

		Death:
			CYBR H 10;
			EXPL A 0 Radius_Quake (6, 100, 0, 22, 0);
			TNT1 AAAA 0
			{
				A_PlaySound("FAREXPL");
				doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
				doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
				A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			}
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 90, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("XDeathCyberdemonHead", 120, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("XDeathCyberdemonArm", 120, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("XDeathCyberdemonGun", 120, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("XDeathCyberdemonPiece", 120, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("XDeathCyberdemonTorso", 120, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_SpawnProjectile ("UltraGoreSpawner", 90, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("CyberXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			CYBR I 5 A_Scream;
			CYBR JKL 5;
			CYBR M 5 A_NoBlocking;
			CYBR NOP 5;
			CYBR P -1 A_BossDeath;
			Stop;
			
		Death.headshot:
			TNT1 A 0 A_SpawnProjectile ("XDeathCyberdemonHead", 120, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("XDeath1", 120, 0, random (0, 360), 2, random (0, 180));
			CYBB AAAAA 8 A_SpawnItem("MuchBlood", 0, 120);
			CYBB ABCABCB 8 A_SpawnItem("MuchBlood", 0, 120);
			EXPL A 0 Radius_Quake (6, 100, 0, 22, 0);
			TNT1 AAAA 0
			{
				A_PlaySound("FAREXPL");
				doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
				doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
				A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			}
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 90, 0, random (0, 360), 2, random (0, 180));
			
			TNT1 AAAAAA 0 A_SpawnProjectile ("UltraGoreSpawner", 90, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("CyberXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			CYBR I 0 A_Fall;
			CYBR JKL 0;
			CYBR M 0 A_NoBlocking;
			CYBR NOP 0;
			CYBR P 120;
			CYBR P -1 A_BossDeath;
			Stop;
			
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS3 A 5;
			CRS3 A -1;
			Stop;
			
		Pain.Taunt:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("Enraged", 1, "SpecialAttack");
			SPOS B 0 A_Pain;
			TNT1 A 0 {bMISSILEMORE = true;}
			TNT1 A 0 {bMISSILEEVENMORE = true;}
			TNT1 A 0 A_PlaySound("demon/pain");
			CYBT A 1 A_FaceTarget;
			CYBT ABCCBADE 4;
			TNT1 A 0 A_PlaySound("CYBTAT", 1);
			CYBT FGHGFGHGFGHGFGHG 3;
			CYBT EDA 4;
			TNT1 A 0 A_GiveInventory("Enraged", 1);
		Goto Missile;
	}
}



