//===========================================================================
//
// Spider boss
//
//===========================================================================
CLASS doomb_mind : doomb_monster_base
{ 
	Default {
		damagefactor "BFG", 0.2;
		damagefactor "HKFT", 0.05;
		damagefactor "Explosive_Impact", 1.5;
		damagefactor "Blood", 0.0;
		damagefactor "Stomp", 0.0;
		damagefactor "Crush", 30.0;
		damagefactor "Trample", 0.0;

		PainChance 30;
		PainChance "Explosive_Impact", 80;

		Health 4000;
		Radius 90;
		Scale 1.5;
		Mass 500000;
		Speed 20;
		MaxStepHeight 24;
		MaxDropOffHeight 32;
		Height 100;
		doomb_monster_base.head_starting_position 72;
		doomb_monster_base.headshot_multiplier 1.5;

		Monster;
		+BOSS;
		+FLOORCLIP;
		+DONTRIP;
		+DONTMORPH;
		+NOICEDEATH;
		+BOSSDEATH;
		+NORADIUSDMG;
		+NOBLOOD;
		+MISSILEMORE;
		+SOLID;
		+MISSILEEVENMORE;
		+SHOOTABLE;

		DropItem "DemonStrengthRune", 25;
		SeeSound "spider/sight";
		AttackSound "spider/attack";
		PainSound "spider/pain";
		DeathSound "spider/death";
		Obituary "%o was destroyed by a Mastermind.";
		ActiveSound "spider/active";
		obituary "$OB_SPIDER";
	}
	States
	{
		Spawn:
		Stand:
			SPID A 10 A_Look();
			Loop;
			
		See:
			SPID AFBBCC 2 A_Metal();
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", 90, 90);
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", -90, 90);

			SPID DDEEFF 2 A_Chase();
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", 90, -90);
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", -90, -90);
		Loop;
			
		Missile:
			SPID AAAH 4 A_FaceTarget();
		fire_mini:
			SPID G 2 A_FaceTarget();
			SPID H 2 BRIGHT
			{
				//for(uint i = 0; i < 2; i++)
				{
					A_SpawnProjectile("MastermindTracer", 72, 0, random(-7, 7), 1, random(-4, 2));
					A_SpawnItem ("MasterMindCaseSpawn", 0, 60,0);
				}
			}
			SPID G 0 a_spidrefire();
		loop;
			
		Pain:
			SPID I 4 A_Pain();
		Goto See;



		Death:
			SPID J 20 A_Scream();
			tnt1 a 0 A_FaceTarget();
			EXPL A 0 Radius_Quake (8, 100, 0, 22, 0);
			TNT1 AAAA 0
			{
				A_PlaySound("FAREXPL");
				doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
				doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
				A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			}
			TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 110), 6);
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID K 10 A_NoBlocking();
			TNT1 AAAA 0
			{
				A_PlaySound("FAREXPL");
				doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
				doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
				A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
				doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			}
			TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 110), 6);
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID L 5;
			TNT1 AAAA 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
			EXPL AAAA 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
			TNT1 AAAAA 0 A_SpawnItem("SpawnedExplosionRepeat");
			EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
			TNT1 A 0 A_PlaySound("FAREXPL");
			EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(2.3, 2.7), 0), 0.5 );
			EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
			TNT1 A 0;
			TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
			TNT1 A 0 A_SpawnItem("NewfagExplosionFlare");
			TNT1 A 0 A_PlaySound("FAREXPL");
			EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
			EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
			TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(9, 9.4), 0) );
			TNT1 AAA 0 A_SpawnItem("NewfagExplosionFlare");
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 30), 6);
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 30, 0, random (0, 360), 2, random (70, 90));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 100, 0, random (0, 360), 2, random (20, 90));
			//SPID MNOPQR 5
			TNT1 AAA 0 A_SpawnProjectile ("MastermindLeg", 30, 0, random (0, 360), 2, random (40, 90));
			TNT1 A 0 A_SpawnProjectile ("MastermindLeg", 30, 0, 0, 2, 65);
			//TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160))
			TNT1 A 0 doomb_spawn_bloodpool();
			SPID S 300;
			SPID S 1 A_BossDeath();
			SPID S -1;
		Stop;
			
		Death.Telefrag:
			SPID J 20 A_Scream();
			tnt1 a 0 A_FaceTarget();
			EXPL A 0 Radius_Quake (8, 100, 0, 22, 0);
		TNT1 AAAA 0
		{
			A_PlaySound("FAREXPL");
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		}
			TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 110), 6);
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID K 10 A_NoBlocking();
		TNT1 AAAA 0
		{
			A_PlaySound("FAREXPL");
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		}
			TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 80), 6);
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID L 5;
			TNT1 AAAA 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
		EXPL AAAA 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 AAAAA 0 A_SpawnItem("SpawnedExplosionRepeat");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(2.3, 2.7), 0), 0.5 );
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
		TNT1 A 0;
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
		TNT1 A 0 A_SpawnItem("NewfagExplosionFlare");
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(9, 9.4), 0) );
		TNT1 AAA 0 A_SpawnItem("NewfagExplosionFlare");
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 30), 6);
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 30, 0, random (0, 360), 2, random (70, 90));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 100, 0, random (0, 360), 2, random (20, 90));
			TNT1 AAA 0 A_SpawnProjectile ("MastermindLeg", 30, 0, random (0, 360), 2, random (40, 90));
			TNT1 A 0 A_SpawnProjectile ("MastermindLeg", 30, 0, 0, 2, 65);
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 300;
			TNT1 A 1 A_BossDeath();
			TNT1 A -1;
			Stop;
			
		Crush:
			CRS3 A 5 A_PlaySound("misc/xdeath4");
			CRS3 A -1;
			Stop;
			
			
		Death.Cut:
		Death.Saw:
		Death.headshot:
			TNT1 AAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XDeath1", 120, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0 A_SpawnProjectile ("XSpiderMastermindCuttedBrain", 120, 0, random (0, 360), 2, random (50, 130));
			SPIY AAAAAAAAAAA 8 doomb_much_blood(120);

			
			EXPL A 0 Radius_Quake (8, 100, 0, 22, 0);
		TNT1 AAAA 0
		{
			A_PlaySound("FAREXPL");
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		}
			TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 110), 6);
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID K 10 A_NoBlocking();
		TNT1 AAAA 0
		{
			A_PlaySound("FAREXPL");
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		}
			TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 80), 6);
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID L 5;
			TNT1 AAAA 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
		EXPL AAAA 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 AAAAA 0 A_SpawnItem("SpawnedExplosionRepeat");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(2.3, 2.7), 0), 0.5 );
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
		TNT1 A 0;
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(6, 6.4), 0) );
		TNT1 A 0 A_SpawnItem("NewfagExplosionFlare");
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (5, 0), 0.5 );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(9, 9.4), 0) );
		TNT1 AAA 0 A_SpawnItem("NewfagExplosionFlare");
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 30), 6);
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 30, 0, random (0, 360), 2, random (70, 90));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 100, 0, random (0, 360), 2, random (20, 90));
			TNT1 AAA 0 A_SpawnProjectile ("MastermindLeg", 30, 0, random (0, 360), 2, random (40, 90));
			TNT1 A 0 A_SpawnProjectile ("MastermindLeg", 30, 0, 0, 2, 65);
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 300;
			TNT1 A 0 A_BossDeath();
			Stop;
	}
}


CLASS XSpiderMastermindCuttedBrain : doomb_body_base
{ 
	Default {
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			SPIP ABCDEFGH 3 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SPIP I 1;
			SPIP I -1;
			Stop;
		Splash:
			TNT1 A 0;
			Stop;
	}
}


CLASS CyberStomp : visual_sfx { 
	Default {
		
		Radius 12;
		Height 8;
		+MISSILE;
		Speed 15;
		Damage 50;
		renderstyle "Translucent";
		alpha 0.75;
		DamageType "Stomp";
		Gravity 2.0;
		Decal "Cracks";
		-NOGRAVITY;
		+EXTREMEDEATH;
		Health 5;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 40, 0, 0);
			TNT1 A 0 A_PlaySound("CLAP");
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			EXPL A 0 A_Explode(90, 80, damagetype:"stomp");
			MNSM ABCDEFGHIJKLMNOPQ 1 bright;
			Stop;
	}
}










CLASS MastermindStep : visual_sfx { 
	Default {
		
		Radius 32;
		Height 32;
		Speed 0;
		Damage 50;
		renderstyle "Translucent";
		alpha 0.75;
		DamageType "Stomp";
		MeleeDamage 0;
		Gravity 2.0;
		Scale 0.4;
		Decal "Cracks";
		-NOGRAVITY;
		+EXTREMEDEATH;
		Obituary "%o has stepped by a Mastermind.";
		Health 5;
	}
	States
	{
		Spawn:
			
			tnt1 A 0 A_SpawnProjectile("FootstepStrong", 0, 0, 150);
			tnt1 A 0 A_SpawnProjectile("FootstepStrong", 0, 0, -150);
			tnt1 A 0 A_SpawnProjectile("FootstepStrong", 0, 0, -30);
			tnt1 A 0 A_SpawnProjectile("FootstepStrong", 0, 0, 30);
			tnt1 A 0 A_SpawnProjectile("FootstepStrong", 0, 0, -60);
			tnt1 A 0 A_SpawnProjectile("FootstepStrong", 0, 0, 60);
			tnt1 A 0 A_SpawnProjectile("FootstepStrong", 0, 0, -90);
			tnt1 A 0 A_SpawnProjectile("FootstepStrong", 0, 0, 90);
			tnt1 A 0 A_SpawnProjectile("FootstepStrong", 0, 0, -120);
			tnt1 A 0 A_SpawnProjectile("FootstepStrong", 0, 0, 120);
			TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 40, 0, 0);
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			
			EXPL A 0 A_Explode(30, 50, damagetype:"stomp");
			TNT1 A 4;
			MNSM ABCDEFGHIJKLMNOPQ 1;
			Stop;
	}
}
















CLASS MastermindLeg : doomb_body_base { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 24;
		Scale 1.3;
		Gravity 0.8;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+THRUACTORS;
		+FLOORCLIP;
		-NOGRAVITY;
		+FORCERADIUSDMG;
		+SKYEXPLODE;
		DamageType "Stomp";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			SPP4 ABCDEFGH 5;
			Loop;
		Death:
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			TNT1 A 0 A_Explode(300, 100);
			EXPL AAAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		KeepRotating:
			SPP4 AB 2;
			SPP4 CDEFGH 2 A_CheckFloor("Rest");
			Loop;
		Rest:
			SPP4 A 1;
			TNT1 A 0 A_Explode(50, 100);
			EXPL AAAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			SPP4 A -1;
			Stop;
			
		Underwater:
		Splash:
			SPP4 A 4;
			Loop;
	}
}
