//===========================================================================
//
// Spider boss
//
//===========================================================================
CLASS TheSpiderMastermind : doomb_monster_base Replaces SpiderMastermind{ 
	Default {
		
		damagefactor "BFG", 0.2;
		damagefactor "HKFT", 0.05;
		//damagefactor "Head", 1.5
		damagefactor "Explosive_Impact", 1.5;
		damagefactor "Avoid", 0.0;
		damagefactor "Decaptate", 5.0;
		damagefactor "Stomp", 0.0;
		damagefactor "GibRemoving", 0.0;
		damagefactor "Trample", 0.0;
		damagefactor "TeleportRemover", 0.0;
		DamageFactor "CauseObjectsToSplash", 0.0;
		Obituary "%o was destroyed by a Mastermind.";
		+NOICEDEATH;
		Health 4000;
		Radius 90;
		damagefactor "Crush", 30.0;
		Scale 1.5;
		Height 72;
		Mass 500000;
		Speed 20;
		PainChance 30;
		PainChance "Explosive_Impact", 80;
		Monster;
		//MinMissileChance 200
		+BOSS;
		+FLOORCLIP;
		+DONTRIP;
		+DONTMORPH;
		+BOSSDEATH;
		+NORADIUSDMG;
		+NOBLOOD;
		+MISSILEMORE;
		+SOLID;
		+MISSILEEVENMORE;
		+SHOOTABLE;
		DropItem "DemonStrengthRune", 25;
		SeeSound "spider/sight";
		AttackSound "spider/attack";
		PainSound "spider/pain";
		DeathSound "spider/death";
		ActiveSound "spider/active";
		obituary "$OB_SPIDER";
		damagefactor "Blood", 0.0;
		MaxStepHeight 24;
		MaxDropOffHeight 32;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_GiveInventory("TargetIsAMastermind");
			TNT1 A 0 ACS_ExecuteAlways(796, 0, 0, 0, 0);//Check if Vanilla Mode is activated
			
		Stand:
			SPID A 10 A_Look();
			Loop;
			
		See:
			//headbox height 72
			SPID AFBBCC 2 A_Metal();
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", 90, 90);
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", -90, 90);

			SPID DDEEFF 2 A_Chase();
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", 90, -90);
			TNT1 A 0 A_SpawnItemEx("MasterMindStep", -90, -90);
		Loop;
			
		Missile:
			TNT1 A 0 A_TakeInventory ("BrutalCounter2", 500);
			//headbox height 82
			SPID AAAH 4 A_FaceTarget();

			SPID G 2 A_FaceTarget();
			
			SPID H 2 BRIGHT A_SpawnProjectile("MastermindTracer", 72, 0, random(-7, 7), 1, random(-4, 2));
			TNT1 A 0 A_SpawnItem ("MasterMindCaseSpawn", 0, 60,0);
			
			TNT1 A 0 A_GiveInventory ("BrutalCounter2", 1);
			TNT1 A 0 A_JumpIfInventory ("BrutalCounter2", 30, "StopFiring");
			SPID G 0 A_SpidRefire();
			Goto Missile+7;
			
		StopFiring:
			SPID A 6 A_FaceTarget();
			Goto See;
			
		Avoid:
			tnt1 A 0 A_FaceTarget();
			SPID A 6 A_FastChase();
			
			tnt1 A 0 A_FaceTarget();
			SPID B 6 A_FastChase();
			
			tnt1 A 0 A_FaceTarget();
			SPID C 6 A_FastChase();
			
			tnt1 A 0 A_FaceTarget();
			SPID D 6 A_FastChase();
			
			Goto Missile;
			
		Pain:
			SPID I 4 A_Pain();
		Goto See;



		Death:
			SPID J 20 A_Scream();
			tnt1 a 0 A_FaceTarget();
			EXPL A 0 Radius_Quake (8, 100, 0, 22, 0);
			TNT1 AAAAAA 0 A_SpawnProjectile ("ExplosionSpawner", 50, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_SpawnProjectile ("SuperGoreSpawner", 110, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID K 10 A_NoBlocking();
			TNT1 AAAAAA 0 A_SpawnProjectile ("ExplosionSpawner", 10, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 80, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID L 5;
			TNT1 AAAA 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("RidiculousExplosionSpawner", 30, 0, random (0, 360), 2, 90);
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 30, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_SpawnProjectile ("UltraGoreSpawner", 30, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 30, 0, random (0, 360), 2, random (70, 90));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 100, 0, random (0, 360), 2, random (20, 90));
			//SPID MNOPQR 5
			TNT1 AAA 0 A_SpawnProjectile ("MastermindLeg", 30, 0, random (0, 360), 2, random (40, 90));
			TNT1 A 0 A_SpawnProjectile ("MastermindLeg", 30, 0, 0, 2, 65);
			//TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160))
			TNT1 A 0 doomb_spawn_bloodpool();
			SPID S 300;
			SPID S 1 A_BossDeath();
			SPID S -1;
			Stop;
			
		Death.Telefrag:
			SPID J 20 A_Scream();
			tnt1 a 0 A_FaceTarget();
			EXPL A 0 Radius_Quake (8, 100, 0, 22, 0);
			TNT1 AAAAAA 0 A_SpawnProjectile ("ExplosionSpawner", 50, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_SpawnProjectile ("SuperGoreSpawner", 110, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID K 10 A_NoBlocking();
			TNT1 AAAAAA 0 A_SpawnProjectile ("ExplosionSpawner", 10, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 80, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID L 5;
			TNT1 AAAA 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("RidiculousExplosionSpawner", 30, 0, random (0, 360), 2, 90);
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 30, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_SpawnProjectile ("UltraGoreSpawner", 30, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 30, 0, random (0, 360), 2, random (70, 90));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 100, 0, random (0, 360), 2, random (20, 90));
			//SPID MNOPQR 5
			TNT1 AAA 0 A_SpawnProjectile ("MastermindLeg", 30, 0, random (0, 360), 2, random (40, 90));
			TNT1 A 0 A_SpawnProjectile ("MastermindLeg", 30, 0, 0, 2, 65);
			//TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160))
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 300;
			TNT1 A 1 A_BossDeath();
			TNT1 A -1;
			Stop;
			
		Crush:
			CRS3 A 5 A_PlaySound("misc/xdeath4");
			CRS3 A -1;
			Stop;
			
			
		Death.Cut:
		Death.Saw:
		Death.decaptate:
			TNT1 AAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XDeath1", 120, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0 A_SpawnProjectile ("XSpiderMastermindCuttedBrain", 120, 0, random (0, 360), 2, random (50, 130));
			SPIY AAAAAAAAAAA 8 A_SpawnItem("MuchBlood", 0, 120);
			
			EXPL A 0 Radius_Quake (8, 100, 0, 22, 0);
			TNT1 AAAAAA 0 A_SpawnProjectile ("ExplosionSpawner", 50, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_SpawnProjectile ("SuperGoreSpawner", 110, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID K 10 A_NoBlocking();
			TNT1 AAAAAA 0 A_SpawnProjectile ("ExplosionSpawner", 10, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 80, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 90, 0, random (0, 360), 2, random (70, 90));
			SPID L 5;
			TNT1 AAAA 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("RidiculousExplosionSpawner", 30, 0, random (0, 360), 2, 90);
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 30, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_SpawnProjectile ("UltraGoreSpawner", 30, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 30, 0, random (0, 360), 2, random (70, 90));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistXXBig", 100, 0, random (0, 360), 2, random (20, 90));
			//SPID MNOPQR 5
			TNT1 AAA 0 A_SpawnProjectile ("MastermindLeg", 30, 0, random (0, 360), 2, random (40, 90));
			TNT1 A 0 A_SpawnProjectile ("MastermindLeg", 30, 0, 0, 2, 65);
			//TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("PEPart2SuperFast", 32, 0, random (0, 360), 2, random (0, 160))
			TNT1 A 0 a_spawnitemex ("doomb_red_blood_pool");
			TNT1 A 300;
			TNT1 A 0 A_BossDeath();
			Stop;
	}
}


CLASS XSpiderMastermindCuttedBrain : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			SPIP ABCDEFGH 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			SPIP I 1;
			SPIP I -1;
			Stop;
		Splash:
			TNT1 A 0;
			Stop;
	}
}


CLASS CyberStomp : visual_sfx { 
	Default {
		
		Radius 12;
		Height 8;
		+MISSILE;
		Speed 15;
		Damage 50;
		renderstyle "Translucent";
		alpha 0.75;
		DamageType "Stomp";
		MeleeDamage 0;
		Gravity 2.0;
		Decal "Cracks";
		-NOGRAVITY;
		+EXTREMEDEATH;
		Health 5;
	}
	States
	{
		Spawn:
			TNT1 A 10;
			Stop;
		Death:
			
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 150);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -150);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -30);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 30);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -60);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 60);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -90);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 90);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -120);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 120);
			TNT1 A 0 A_SpawnItemEx("FootStep5", 0, 0, 40, 0, 0);
			TNT1 A 0 A_PlaySound("CLAP");
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile("HugeWallChunk",0,0,random(0,360),2,random(-40,40));
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile("BigWallChunk",0,0,random(0,360),2,random(-40,40));
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			
			EXPL A 0 A_Explode();
			MNSM ABCDEFGHIJKLMNOPQ 1 bright;
			Stop;
	}
}



CLASS CyberStompBig : visual_sfx { 
	Default {
		
		Radius 12;
		Height 8;
		+MISSILE;
		Speed 15;
		Damage 50;
		renderstyle "Translucent";
		alpha 0.75;
		DamageType "Stomp";
		MeleeDamage 0;
		Gravity 2.0;
		Decal "Cracks";
		-NOGRAVITY;
		+EXTREMEDEATH;
		Health 5;
	}
	States
	{
		Spawn:
			TNT1 A 10;
			Stop;
		Death:
			
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 150);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -150);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -30);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 30);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -60);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 60);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -90);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 90);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -120);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 120);
			TNT1 A 0 A_SpawnItemEx("FootStep5", 0, 0, 40, 0, 0);
			TNT1 A 0 A_PlaySound("CLAP");
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile("HugeWallChunk",0,0,random(0,360),2,random(-40,40));
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile("BigWallChunk",0,0,random(0,360),2,random(-40,40));
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			
			EXPL A 0 A_Explode(300, 300, 0);
			MNSM ABCDEFGHIJKLMNOPQ 1 bright;
			Stop;
	}
}






CLASS MastermindStep : visual_sfx { 
	Default {
		
		Radius 32;
		Height 32;
		Speed 0;
		Damage 50;
		renderstyle "Translucent";
		alpha 0.75;
		DamageType "Stomp";
		MeleeDamage 0;
		Gravity 2.0;
		Scale 0.4;
		Decal "Cracks";
		-NOGRAVITY;
		+EXTREMEDEATH;
		Obituary "%o has stepped by a Mastermind.";
		Health 5;
	}
	States
	{
		Spawn:
			
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 150);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -150);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -30);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 30);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -60);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 60);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -90);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 90);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, -120);
			tnt1 A 0 A_SpawnProjectile("FootStep6", 0, 0, 120);
			TNT1 A 0 A_SpawnItemEx("FootStep5", 0, 0, 40, 0, 0);
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			
			EXPL A 0 A_Explode(300, 50, 0);
			TNT1 A 4;
			MNSM ABCDEFGHIJKLMNOPQ 0;
			Stop;
	}
}
















CLASS MastermindLeg : doomb_body_base { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 24;
		Scale 1.3;
		Gravity 0.8;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+THRUACTORS;
		+FLOORCLIP;
		-NOGRAVITY;
		+FORCERADIUSDMG;
		+SKYEXPLODE;
		DamageType "Stomp";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
		Mass 1;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Underwater");
			SPP4 ABCDEFGH 5;
			Loop;
		Death:
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			TNT1 A 0 A_Explode(300, 100);
			EXPL AAAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		KeepRotating:
			SPP4 AB 2;
			SPP4 CDEFGH 2 A_CheckFloor("Rest");
			Loop;
		Rest:
			SPP4 A 1;
			TNT1 A 0 A_Explode(50, 100);
			EXPL AAAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			SPP4 A -1;
			Stop;
			
		Underwater:
		Splash:
			SPP4 A 4;
			Loop;
	}
}
