CLASS HandGrenades : doomb_weapon_base { 
	Default {
		
		Weapon.AmmoUse1 1;
		Weapon.AmmoGive1 1;
		Weapon.AmmoUse2 1;
		Weapon.AmmoGive2 0;
		Weapon.SelectionOrder 99999;
		Weapon.AmmoType1 "GrenadeAmmo";
		Weapon.AmmoType2 "GrenadeAmmo";
		Obituary "%o was shreded by %k's grenade.";
		AttackSound "None";
		Inventory.PickupSound "AmmoAPIN";
		Inventory.Pickupmessage "You got a Frag Grenade!  (Slot 0)";
		
		+WEAPON.NOAUTOAIM;
		+WEAPON.NOALERT;
		+WEAPON.NOAUTOFIRE;
		Scale 0.3;
	}
	States
	{
		Ready:
			TNT1 A 0 A_JumpIfInventory("GrenadeAmmo", 1, 1);
			Goto NoGrenades;
			GRHO AB 1;
		Steady:
			GRHO C 1 A_WeaponReady;
			Loop;
			
		NoGrenades:
			TNT1 A 1 A_WeaponReady;
			Goto Ready;
			
		Deselect:
			TNT1 A 1 A_Lower;
		Wait;
			
		Select:
			GRWG A 1 A_Raise;
			Loop;
		Fire:
			GRTH ABCD 1;
			TNT1 A 0 A_PLaySound ("GRNPIN");
			GRTH EEFG 1;
			TNT1 A 1;
			TNT1 A 1 A_Refire;
			TNT1 A 0 A_PLaySound ("GRNTOSS");
			GRTH HI 1;
			TNT1 A 0 A_FireProjectile("HandGrenade", random(-2,2), 1, 0, 0, 0, 0);
			GRTH JKLM 1;
			TNT1 A 3;
			Goto Ready;
			
		AltFire:
			GRTH ABCD 1;
			TNT1 A 0 A_PLaySound ("GRNPIN");
			GRTH EEFG 1;
			
		AltHold:
			TNT1 A 1;
			TNT1 A 1 A_Refire;
			TNT1 A 0 A_PLaySound ("GRNTOSS");
			GRTH HI 1;
			TNT1 A 0 A_FireProjectile("HandGrenadeAlt", 0, 1, 0, 0, 0, 0);
			GRTH JKLM 1;
			TNT1 A 3;
			Goto Ready;
			
		Spawn:
			GRND H -1;
			Stop;
			
			
			
			
	}
}



CLASS HandGrenade : doomb_boolet_base { 
	Default {
		
		Radius 4;
		Height 4;
		Projectile;
		Speed 30;
		Damage 0;
		Gravity 0.7;
		Scale 0.2;
		Projectile;
		-NOGRAVITY;
		-BLOODSPLATTER;
		-EXTREMEDEATH;
		+EXPLODEONWATER;
		+SKYEXPLODE;
		+DOOMBOUNCE;
		BounceFactor 0.5;
		WallBounceFactor 0.25;
		//+BOUNCEONACTORS
		Health 5;
		SeeSound "GRNBNCE";
		DeathSound "none";
		Obituary "%o ate %k grenade.";
	}
	private uint timer; 

	States
	{
		Spawn:
			tnt1 a 0
			{
				timer++;
				if(timer > 15)
					setstatelabel("explode");
			}
			GRND ABCDEFGH 2 {vel.z -= 1;}
		Loop;

		Death:
			tnt1 a 0
			{
				timer++;
				if(timer > 15)
					setstatelabel("explode");

				vel.z -= 5;
			}
			GRND H 16;
		Loop;
			
			
			
		Explode:
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			TNT1 A 0 A_PlaySound("explosion", 2);
			TNT1 A 0 A_Explode(200,200, damagetype:"Explosive_Impact");
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -15);
			TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 AAAAAA 0
			{
				doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
				//doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
				//doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
				//doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
				doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
			}

			TNT1 AAAAAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			BEXP B 0 A_Scream;
			TNT1 A 0 A_ALertMonsters;
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ShrapnelParticle", (0, 0, 0), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
			tnt1 a 0
			{
				a_setscale(3.0);
				a_setrenderstyle(0.12, STYLE_add);
			}
			TNT1 a 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		Stop;
	}
}

CLASS HandGrenadeDroped: HandGrenade { 
	Default {
		
		Speed 4;
	}
}

CLASS HandGrenadeAlt: HandGrenade { 
	Default {
		
		Speed 8;
	}
}

		
		

CLASS GrenadeAmmo : Ammo { 
	Default {
		Inventory.PickupMessage "Picked up a Grenade.";
		Inventory.Amount 1;
		Inventory.MaxAmount 10;
		Ammo.BackpackAmount 5;
		Ammo.BackpackMaxAmount 20;
		Inventory.Icon "GRNDA";
		Scale 0.3;
	}
	States
	{
		Spawn:
			GRND H -1;
			Stop;
	}
}


CLASS GrenadeBox : GrenadeAmmo { 
	Default {
		
		Inventory.PickupMessage "Picked up a box of grenades.";
		Inventory.Amount 10;
	}
	States
	{
		Spawn:
			GRND H -1;
			Stop;
	}
}
		
