CLASS HandGrenades : doomb_weapon_base { 
	Default {
		
		Weapon.AmmoUse1 1;
		Weapon.AmmoGive1 1;
		Weapon.AmmoUse2 1;
		Weapon.AmmoGive2 0;
		Weapon.SelectionOrder 99999;
		Weapon.AmmoType1 "GrenadeAmmo";
		Weapon.AmmoType2 "GrenadeAmmo";
		Obituary "%o was shreded by %k's grenade.";
		AttackSound "None";
		Inventory.PickupSound "AmmoAPIN";
		Inventory.Pickupmessage "You got a Frag Grenade!  (Slot 0)";
		
		+WEAPON.NOAUTOAIM;
		+WEAPON.NOALERT;
		+WEAPON.NOAUTOFIRE;
		//+INVENTORY.UNDROPPABLE
		Scale 0.3;
	}
	States
	{
		Ready:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("GrenadeAmmo", 1, 1);
			Goto NoGrenades;
			GRHO AB 1;
			Goto Steady;
			
		Steady:
			GRHO C 1 A_WeaponReady;
			Loop;
			
		NoGrenades:
			TNT1 A 1 A_WeaponReady;
			Goto Ready;
			
		Deselect:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("FiredGrenade", 1, "DropGrenade");
			TNT1 A 1 A_Lower;
			Wait;
			
		DropGrenade:
			TNT1 A 0;
			TNT1 A 0 A_TakeInventory("FiredGrenade", 1);
			TNT1 A 0 A_FireProjectile("HandGrenadeDroped", random(-2,2), 1, 0, 0, 0, 0);
			Goto Deselect;
			
		Select:
			GRWG A 1 A_Raise;
			Loop;
		Fire:
			GRTH ABCD 1;
			TNT1 A 0 A_PLaySound ("GRNPIN");
			GRTH EEFG 1;
			TNT1 A 1;
			TNT1 A 1 A_Refire;
			TNT1 A 0 A_PLaySound ("GRNTOSS");
			GRTH HI 1;
			TNT1 A 0 A_FireProjectile("HandGrenade", random(-2,2), 1, 0, 0, 0, 0);
			TNT1 A 0 A_TakeInventory("FiredGrenade", 1);
			GRTH JKLM 1;
			TNT1 A 3;
			Goto Ready;
			
		AltFire:
			GRTH ABCD 1;
			TNT1 A 0 A_GiveInventory("FiredGrenade", 1);
			TNT1 A 0 A_PLaySound ("GRNPIN");
			GRTH EEFG 1;
			
		AltHold:
			TNT1 A 1;
			TNT1 A 1 A_Refire;
			TNT1 A 0 A_PLaySound ("GRNTOSS");
			GRTH HI 1;
			TNT1 A 0 A_FireProjectile("HandGrenadeAlt", 0, 1, 0, 0, 0, 0);
			TNT1 A 0 A_TakeInventory("FiredGrenade", 1);
			GRTH JKLM 1;
			TNT1 A 3;
			Goto Ready;
			
		Spawn:
			GRND H -1;
			Stop;
			
			
			
			
	}
}



CLASS GrenadeTime : Inventory { 
	Default {
		
		inventory.maxamount 6;
	}
}

CLASS TossGrenade : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}


CLASS FiredGrenade : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}

CLASS HandGrenade : ACTOR { 
	Default {
		
		Radius 4;
		Height 4;
		Projectile;
		Speed 30;
		Damage 0;
		Gravity 0.7;
		Scale 0.2;
		Projectile;
		+MISSILE;
		-NOGRAVITY;
		-BLOODSPLATTER;
		-EXTREMEDEATH;
		//+DOOMBOUNCE
		+EXPLODEONWATER;
		+SKYEXPLODE;
		+DOOMBOUNCE;
		BounceFactor 0.5;
		WallBounceFactor 0.25;
		//+BOUNCEONACTORS
		Health 5;
		SeeSound "GRNBNCE";
		DeathSound "none";
		Obituary "%o ate %k grenade.";
	}
	States
	{
		Spawn:
			GRND ABCDEFGH 2;
			TNT1 A 0 A_GiveInventory("GrenadeTime", 1);
			TNT1 A 0 A_JumpIfInventory("GrenadeTime", 3, "Explode");
			Loop;
		Death:
			TNT1 A 0;
			GRND H 16;
			TNT1 A 0 A_GiveInventory("GrenadeTime", 1);
			TNT1 A 0 A_JumpIfInventory("GrenadeTime", 3, "Explode");
			Loop;
			
			
			
		Explode:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("FragGrenadeExplosion");
			Stop;
	}
}

CLASS HandGrenadeDroped: HandGrenade { 
	Default {
		
		Speed 4;
	}
}

CLASS HandGrenadeAlt: HandGrenade { 
	Default {
		
		Speed 8;
	}
}

CLASS FragGrenadeExplosion : ACTOR { 
	Default {
		
		+NOBLOCKMAP;
		+MISSILE;
		Damagetype "Explosive_Impact";
		DeathSound "Explosion";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			
			TNT1 A 0 A_Explode(200,800, 0);
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -15);
			TNT1 A 0 A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_Explode(160,200);
			TNT1 AAAAAA 0 A_SpawnProjectile ("SmallExplosionSpawner", 20, 0, random (0, 360), 2, - random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("ExplosionParticle2", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_SpawnProjectile ("ExplosionParticle2", 0, 0, random (0, 360), 2, random (0, 180));
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			BEXP B 0 BRIGHT A_Scream;
			TNT1 A 0 A_ALertMonsters;
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("ShrapnelParticle2", 0, 0, random (0, 360), 2, random (5, 90));
			TNT1 A 0 A_PlaySound("FAREXPL", 3);
			TNT1 A 0 A_SpawnItem("BarrelExplosionSmokeColumn");
			tnt1 a 0
			{
				a_setscale(3.0);
				a_setrenderstyle(0.12, STYLE_add);
				
		}
		SHWK ACEGIKMOQ 1 A_FadeOut(0.01);
		TNT1 AAAAAAAAAAAAAAA 8 A_SpawnProjectile ("ExplosionSmoke", 1, 0, random (0, 360), 2, random (50, 130));
		Stop;
	}
	
}		
		
		

CLASS GrenadeAmmo : Ammo { 
	Default {
		
		
		Inventory.PickupMessage "Picked up a Grenade.";
		Inventory.Amount 1;
		Inventory.MaxAmount 10;
		Ammo.BackpackAmount 5;
		Ammo.BackpackMaxAmount 20;
		Inventory.Icon "GRNDA";
		Scale 0.3;
	}
	States
	{
		Spawn:
			GRND H -1;
			Stop;
	}
}


CLASS GrenadeBox : GrenadeAmmo { 
	Default {
		
		Inventory.PickupMessage "Picked up a box of grenades.";
		Inventory.Amount 10;
	}
	States
	{
		Spawn:
			GRND H -1;
			Stop;
	}
}
		
