CLASS PlasmaAmmo : Ammo { 
	Default {
		
		Inventory.Amount 0;
		Inventory.MaxAmount 50;
		Ammo.BackpackAmount 0;
		Ammo.BackpackMaxAmount 50;
		Inventory.Icon "PLASA0";
	}
}

CLASS HasPlasmaWeapon: Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}

// --------------------------------------------------------------------------
//
// Plasma rifle
//
// --------------------------------------------------------------------------

CLASS Plasma_Gun : doomb_weapon_base { 
	Default {
		
		Weapon.SlotNumber 6;
		Weapon.SlotPriority 0;
		
		Weapon.SelectionOrder 100;
		Weapon.AmmoUse1 0;
		Weapon.AmmoGive1 0;
		Weapon.AmmoUse2 0;
		Weapon.AmmoGive2 0;
		Inventory.PickupSound "PLSDRAW";
		Weapon.AmmoType1 "Cell";
		Weapon.AmmoType2 "PlasmaAmmo";
		+WEAPON.NOAUTOAIM;
		+FORCEXYBILLBOARD;
		+WEAPON.NO_AUTO_SWITCH;
		Inventory.PickupMessage "Plasma Gun";
	}
	States
	{
		
		Flash:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("FlashlightAction", 1, "CheckFlashlight");
			TNT1 A 1;
			TNT1 A 0 A_JumpIfInventory("IsFlashlightOn", 1, "FlashOn");
			Goto Flash;
		FlashOn:
			TNT1 A 0 A_FireProjectile("FlashlightProjectile");
			TNT1 A 0 A_FireProjectile("FlashlightSource");
			Goto Flash;
		CheckFlashLight:
			TNT1 A 1;
			TNT1 A 0 A_TakeInventory("FlashlightAction");
			TNT1 A 0 A_JumpIfInventory("IsFlashlightOn", 1, "TurnOffFlashlight");
			TNT1 A 0 A_GiveInventory("IsFlashlightOn", 1);
			Goto Flash;
		TurnOffFlashlight:
			TNT1 A 0 A_TakeInventory("IsFlashlightOn", 1);
			Goto Flash;
			
		Steady:
			TNT1 A 1;
			Goto Ready;
		Ready:
			TNT1 A 0 A_GunFlash;
			TNT1 A 0 A_PlaySound("PLSDRAW");
		ready_loop:
			PLSG A 1 A_WeaponReady(WRF_ALLOWRELOAD);
			loop;
			
		Deselect:
			PLS9 CBA 1;
			TNT1 AAAAAAAAAAAAAAAAAAAAAA 0 A_Lower;
			TNT1 A 1;
			Wait;
			
		Select:
			TNT1 A 0 A_Raise;
			Wait;
			
		Fire:
			TNT1 A 0 A_CheckReload;
			TNT1 A 0 A_JumpIfInventory("PlasmaAmmo",1,2);
			Goto Reload;
			TNT1 AAAA 0;
			TNT1 A 0 A_PlaySound("PLSM9", CHAN_WEAPON);
			TNT1 A 0 A_FireProjectile("PlasmaFlareSpawn", 0, 0, 0, 0);
			RIFF A 0 A_FireProjectile("GunFireSmoke", 0, 0, 0, 0, 0, 0);
			PLSF A 1 BRIGHT A_FireProjectile("PlasmaBall", 0, 1, 0, 0);
			TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
			PLSA BC 1 BRIGHT;
			PLSF B 1 BRIGHT;
			
			
			TNT1 A 0 A_Takeinventory("PlasmaAmmo",1);
			TNT1 A 0 A_ReFire;
			TNT1 A 0 A_PlaySound("PLSCOOL", 0);
			PLSG BCD 1;
			PLSG EEEEEE 3 A_FireProjectile ("ShotSmoke", 0, 0, random (0, 360), 2, random (0, 180));
			
			
			PLSG DCB 1;
			TNT1 A 0 A_PlaySound("BEPBEP");
			Goto ready_loop;
			
			// Charging up secondary ------------------------------------------------------------
			
		AltFire:
			
			TNT1 A 0 A_JumpIfInventory("PlasmaAmmo",10,2);
			Goto Reload;
			TNT1 AAA 0;
			
			TNT1 A 0 A_PlaySound("PLSCHARG");
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Takeinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Takeinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Takeinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Takeinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Takeinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Takeinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Takeinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Takeinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Takeinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Takeinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			
			TNT1 A 0 A_PlaySound("PLSFULL", 6, 0.8, 1);
			TNT1 A 0 A_ReFire;
			
			// Holding Charge ------------------------------------------------------------
			
		AltHold:
			
			TNT1 A 0 A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			TNT1 A 0 A_JumpIfInventory("Reloading",1,"Cancel");
			PLFA A 1 BRIGHT offset (0, 32);
			
			TNT1 A 0 A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			TNT1 A 0 A_JumpIfInventory("Reloading",1,"Cancel");
			PLFA C 1 BRIGHT offset (0, 33);
			
			TNT1 A 0 A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			TNT1 A 0 A_JumpIfInventory("Reloading",1,"Cancel");
			PLFA A 1 BRIGHT offset (1, 32);
			
			TNT1 A 0 A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			TNT1 A 0 A_JumpIfInventory("Reloading",1,"Cancel");
			PLFA C 1 BRIGHT offset (-1, 32);
			
			TNT1 A 0 A_ReFire;
			
			// Let Fly --------------------------------------------------------------------------
			
			TNT1 A 0 A_StopSound(6);
			PLSF A 1 A_PlaySound("PLSALTFR");
			PLSF B 2 BRIGHT A_Recoil(3);
			RIFF A 0 A_FireProjectile("GunFireSmoke", 0, 0, 0, 0, 0, 0);
			TNT1 AAAAAAAAAAAAA 0 A_FireProjectile("GunFireSmoke", random(-6,6), 0, -1, 0, 0, random(-4,4));
			TNT1 AAAAAAAAAAAAA 0 A_FireProjectile("PlasmaBall75", random(-6,6), 0, -1, 0, 0, random(-4,4));
			TNT1 A 0 A_FireProjectile("PlasmaFlareSpawn",-5,0,0,0);
			TNT1 A 0 Radius_Quake (8, 6, 0, 1, 0);
			PLSG J 1;
			PLSG KLKJ 1;
			TNT1 A 0 A_SetPitch(pitch - 8.0);
			PLSG BCD 1;
			PLSG EEEEEEEEEEEE 3 A_fireProjectile ("ShotSmoke",0,0,10,5);
			
			PLSG DCB 1;
			TNT1 A 0 A_JumpIfInventory("PlasmaAmmo",1,2);
			Goto Reload;
			TNT1 AAAA 0;
			TNT1 A 0 A_PlaySound("BEPBEP");
			Goto ready_loop;
			
			// Cancel Charge --------------------------------------------------------------------------------------------
			
		Cancel:
			TNT1 A 0 A_TakeInventory("Reloading",1);
			TNT1 A 0 A_StopSound(6);
			TNT1 A 0 A_PlaySound("decharg", 5);
			
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Giveinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Giveinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Giveinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Giveinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Giveinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Giveinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT A_PlaySound("plscool", 7);
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Giveinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Giveinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Giveinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			PLSA A 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA B 1 BRIGHT A_Giveinventory("PlasmaAmmo",1);
			PLSA C 1 BRIGHT A_FireProjectile("PlasmaFlareSpawn",0,0,0,0);
			PLSA D 1 BRIGHT;
			Goto Ready_loop;
			
			//  ------------------------------------------------------------------------------
			
		Flash:
			TNT1 A 4;
			Goto LightDone;
		Spawn:
			PLAS A -1;
		Stop;
			
		Reload:
			
			TNT1 A 0 A_Takeinventory("Reloading",1);
			TNT1 A 0 A_ClearReFire;
			TNT1 A 0 A_JumpIfInventory("PlasmaAmmo",50,"DontNeedToReload");
			TNT1 A 0 A_JumpIfInventory("Cell",1,7);
			
			TNT1 A 0 A_PlaySound("BEP");
			PLSR A 4 A_WeaponReady(WRF_NOFIRE);
			TNT1 A 0 A_PlaySound("BEP");
			PLSR A 4 A_WeaponReady(WRF_NOFIRE);
			TNT1 A 0 A_CheckReload;
			Goto ready_loop;
			TNT1 AAAA 0;
			TNT1 A 0 A_PlaySound("PLREADY");
			
			PLSR AB 1;
			TNT1 A 0 A_FireProjectile("PlasmaCaseSpawn",-210,0,20,-20);
			PLSR CDEEEEEEEEEEEEEEEF 1;
			PLSR GHHIIIJJJJJJJJIKLBAAAAA 1;
			
		ReloadingSequence:
			TNT1 AAAAAAAAAA 0;
			TNT1 A 0 A_JumpIfInventory("PlasmaAmmo",50,15);
			TNT1 A 0 A_JumpIfInventory("Cell",1,3);
			Goto ready_loop;
			TNT1 AAAAAA 0;
			TNT1 A 0 A_Giveinventory("PlasmaAmmo",1);
			TNT1 A 0 A_Takeinventory("Cell",1);
			Goto ReloadingSequence;
			TNT1 AAAAAAAA 0;
			
			TNT1 A 0 A_Takeinventory("Reloading",1);
			Goto ready_loop;
			
	}
}



CLASS Plasma_Ball: FastProjectile Replaces PlasmaBall { 
	Default {
		
		Radius 10;
		Height 2;
		Speed 60;
		Damage 8;
		DamageType "Plasma";
		Decal "SmallerScorch";
		Projectile;
		+RANDOMIZE;
		
		//+SHOOTABLE
		-NOBLOCKMAP;
		+NOBLOOD;
		+NORADIUSDMG;
		+THRUSPECIES;
		+MTHRUSPECIES;
		Species "Marines";
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Taunt", 0.0;
		damagefactor "KillMe", 0.0;
		Health 5;
		Scale 1.0;
		
		renderstyle "Add";
		alpha 0.90;
		Scale 0.10;
		DeathSound "weapons/plasmax";
		//SeeSound "PLSM9"
		SeeSound "None";
		Obituary "$OB_MPPLASMARIFLE";
	}
	States
	{
		Spawn:
			TNT1 A 0;
		Spawn1:
			PBAL C 1 BRIGHT A_SpawnItem("PlasmaFlare",0,0);
			TNT1 A 0 A_CheckFloor("Death");
			Loop;
			
		Xdeath:
			TNT1 A 0 A_SpawnProjectile ("BluePlasmaFire", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAA 0 A_SpawnProjectile ("BluePlasmaParticle", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 B 1 A_Explode(6,50,0);
			TNT1 B 4;
			TNT2 AA 9 A_SpawnProjectile ("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 160));
			
			Stop;
			
		Death:
			TNT1 B 1 A_Explode(6,50,1);
			TNT1 A 0 A_SpawnItemEx ("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("DetectCeilCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnProjectile ("BluePlasmaFire", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAA 0 A_SpawnProjectile ("BluePlasmaParticle", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 B 4;
			TNT2 AAAAAAAAA 9 A_SpawnProjectile ("PlasmaSmoke", 1, 0, random (0, 360), 2, random (0, 160));
			Stop;
	}
}


CLASS PlasmaBall75: Plasma_Ball { 
	Default {
		
		Damage 9;
		SeeSound "PLSM9";
	}
}
CLASS PlasmaBall99: Plasma_Ball { 
	Default {
		
		Damage 20;
		SeeSound "PLSM9";
	}
}










CLASS PlasmagunOnTheFloor: CustomInventory Replaces PlasmaRifle { 
	Default {
		
		scale 1.0;
		radius 16;
		height 4;
		damage 0;
		Mass 1;
		Inventory.PickupMessage "You got the Plasma Rifle!";
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("InvisiblePlasmaAmmo");
			PLAS A -1;
			Stop;
			
		Pickup:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("Plasma_Gun", 1, "Pickup2");
			TNT1 A 0 A_GiveInventory("Plasma_Gun", 1);
			Stop;
		Pickup2:
			TNT1 A 0 A_GiveInventory("DualPlasmaRifles", 1);
			Stop;
	}
}


CLASS DropedPlasmaGun: PlasmagunOnTheFloor { 
	States
	{
		
		Spawn:
			TNT1 A 0;
			PLAS A -1;
			Stop;
	}
}



CLASS InvisiblePLasmaAmmo: CustomInventory { 
	Default {
		
		scale 1.0;
		radius 16;
		height 4;
		damage 0;
		Mass 1;
		Inventory.PickupMessage "Plasma Cells.";
	}
	States
	{
		
		Spawn:
			CELL D -1;
			Stop;
		Pickup:
			TNT1 A 0;
			TNT1 A 0 A_GiveInventory("Cell", 50);
			Stop;
			
	}
}
