
// --------------------------------------------------------------------------
//
// Grenade launcher
//
// --------------------------------------------------------------------------

CLASS GrenadeLauncher : doomb_weapon_base { 
	Default {
		
		Weapon.AmmoUse1 1;
		Weapon.AmmoUse2 1;
		Weapon.AmmoGive 6;
		Weapon.AmmoType1 "doomb_rockets_ammo";
		Weapon.AmmoType2 "doomb_rockets_ammo";
		Inventory.PickupSound "ROCKPKUP";
		+WEAPON.NOAUTOAIM;
		Weapon.SelectionOrder 8500;
		Inventory.PickupMessage "$GOTLAUNCHER";
		+WEAPON.CHEATNOTWEAPON;
	}
	States
	{
		Ready:
			TNT1 A 0 A_PlaySound("RLANDRAW");
			GLSW ABC 1;
			TNT1 AAAAA 0;
			GLAN A 1 A_WeaponReady(WRF_ALLOWRELOAD);
			Goto Ready+7;
		Deselect:
			GLSW CBA 1;
			TNT1 A 1 A_Lower;
			Wait;
		Select:
			MISG A 0 A_Raise;
		Wait;
			
		Fire:
			TNT1 A 0 A_FireProjectile("RedFlareSpawn",-5,0,0,0);
			GLAF A 1 BRIGHT A_FireProjectile("GrenadeMissile", 0, 1, 0, 0);
			TNT1 A 0 A_SetPitch(-6.0 + pitch);
			TNT1 A 0 A_PlaySound("weapons/firegrenade");
			GLAF C 1;
			GLAF CCBBB 1 A_SetPitch(1.0 + pitch);
			GLAN A 5 A_SetPitch(1.0 + pitch);
			GLR1 ABCDEFGHIJKL 1;
			TNT1 A 0 A_PlaySound("Weapons/GrenadeOpen");
			GLR1 MMMNNNN 1 {invoker.doomb_show_effect("GunFireSmoke", (20, 20, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.6,0) );}
			GLR1 OPQQRRSS 1;
			TNT1 A 0 A_PlaySound("Weapons/GrenadeLoad");
			GLR1 T 1;
			GLR1 UVWX 1;
			TNT1 A 0 A_PlaySound("Weapons/GrenadeClose");
			GLR1 YZ 1;
			GLAN A 1;
			Goto Ready+7;
			
		AltFire:
			TNT1 A 0 A_FireProjectile("RedFlareSpawn",-5,0,0,0);
			GLAF A 1 BRIGHT A_FireProjectile("GrenadeMissile", 0, 1, 0, 0);
			TNT1 A 0 A_SetPitch(-6.0 + pitch);
			TNT1 A 0 A_PlaySound("weapons/firegrenade");
			GLAF C 1;
			GLAF CCBBB 1 A_SetPitch(1.0 + pitch);
			GLAN A 5 A_SetPitch(1.0 + pitch);
			GLR1 ABCDEFGHIJKL 1;
			TNT1 A 0 A_PlaySound("Weapons/GrenadeOpen");
			GLR1 MMMNNNN 1 {invoker.doomb_show_effect("GunFireSmoke", (20, 20, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.6,0) );}
			GLR1 OPQQRRSS 1;
			TNT1 A 0 A_PlaySound("Weapons/GrenadeLoad");
			GLR1 T 1;
			GLR1 UVWX 1;
			TNT1 A 0 A_PlaySound("Weapons/GrenadeClose");
			GLR1 YZ 1;
			GLAN A 1;
			Goto Ready+7;
			
			
		Spawn:
			GLAP A -1;
			Stop;
			
		Steady:
			TNT1 A 1;
			Goto Ready;

	}
}

CLASS RocketerAmmo: Inventory { 
	Default {
		
		inventory.maxamount 6;
	}
}


CLASS GrenadeMissile : doomb_boolet_base { 
Default {
	
	Radius 4;
	Height 4;
	Speed 50;
	Damage 6;
	+MISSILE;
	+BLOODSPLATTER;
	Gravity 0.7;
	
	+SKYEXPLODE;
	+DOOMBOUNCE;
	+EXPLODEONWATER;
	DamageType "Kick";
	BounceFactor 0.5;
	SeeSound "Weapons/GrenadeBounce";
	DeathSound "none";
	Obituary "$OB_MPROCKET";
}

private uint timer; 
States
{
	Spawn:
		tnt1 a 0
		{
			timer++;
			if(timer > 10)
				setstatelabel("explode");
		}
		TNT1 A 0 A_CheckFloor("Death");
		GBPJ ABCDEFGH 3
		{
			if(waterlevel <= 1)
				doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		
			vel.z -= 1;
		}
	Loop;
		
	Death:
		tnt1 a 0
		{
			vel.z -= 5;
			timer+= 5;
			if(timer > 10)
				setstatelabel("explode");
		}
		GBPJ AAAA 3 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
	Loop;
		
	Explode:
		EXPL A 0 Radius_Quake (3, 8, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		TNT1 A 0 {if(waterlevel > 1) spawn("UnderwaterExplosion", pos:self.pos); }
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_Explode(100,150, damagetype:"Explosive_Impact");
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		TNT1 AA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
		TNT1 A 0 A_PlaySound("Explosion", 1);
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		tnt1 a 0
		{
			a_setscale(2.0);
			a_setrenderstyle(0.12, STYLE_add);
		}
		SHWK ACEGIKMOQ 1 A_FadeOut(0.01);
		Stop;
	}
}