CLASS doomb_knight : doomb_monster_base Replaces HellKnight { 
	Default {
		
		doomb_monster_base.headshot_multiplier 2;
		doomb_monster_base.head_starting_position 58;//so that if someone forgot to define this number monster dont get headshot from every attack
		doomb_monster_base.legs_height_max -1;//same for legs
		
		
		Radius 24;
		Height 64;
		Mass 1000;
		Speed 8;
		PainChance 50;
		Monster;
		+FLOORCLIP;
		
		HitObituary "$OB_KNIGHTHIT";
		Obituary "$OB_KNIGHT";
		Tag "$FN_HELL";
		
		Scale 1.0;
		Speed 8;
		Health 500;
		PainChance "Kick", 255;
		PainChance "Head", 150;
		PainChance "Explosive_Impact", 255;
		PainChance 25;
		PainChance "Saw", 100;
		PainChance "Cut", 100;
		damagefactor "Fatality", 2.0;
		DamageFactor "CauseObjectsToSplash", 0.0;
		damagefactor "SSG", 0.5;
		damagefactor "Avoid", 0.0;
		damagefactor "TeleportRemover", 0.0;
		damagefactor "Avoid", 0.0;
		damagefactor "Crush", 10.0;
		damagefactor "GibRemoving", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		PainSound "PSXDPN";
		GibHealth 30;
		-BOSSDEATH;
		MaxStepHeight 24;
		MaxDropOffHeight 32;
		BloodType "Brutal_Blood",  "SawBlood";
		DropItem "DemonStrengthRune", 3;
		Obituary "%o was slain by a Hell Knight.";
		DamageType "HKF";
		MeleeDamage 5;
		
		SeeSound "knight/sight";
		ActiveSound "knight/active";
		PainSound "knight/pain";
		DeathSound "knight/death";
		HitObituary "$OB_KNIGHTHIT";
		
	}
	States
	{
		Melee:
			
			BOS2 E 6 A_FaceTarget;
			TNT1 A 0 A_PlaySound("weapons/gswing");
			
			BOS2 F 6 A_FaceTarget;
			
			BOS2 G 6 A_SpawnProjectile("KnightAttack",10,0,0,0);
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			Goto See2;
			
		Spawn:
			TNT1 A 0;
			TNT1 A 0 ACS_ExecuteAlways(796, 0, 0, 0, 0);//Check if Vanilla Mode is activated
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			
		Stand:
			TNT1 A 0 A_CheckSight("Stand2");
			BOS2 BBBBBBBBBB 10 A_Look;
			Loop;
			
		Stand2:
			BOS2 B 11 A_Look;
			Goto Stand;
			
		See: 
			TNT1 A 0;
			TNT1 A 0 A_CheckSight("SeeNeverSeen");
			Goto Rage;
		See2:
			TNT1 A 0;
			TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsACyberdemon", 1, "CheckRetreat");
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMastermind", 1, "CheckRetreat");
			
		See3:
			
			TNT1 A 0 A_CheckSight("SeeNeverSeen");
			
		SeeContinue:
			
			//TNT1 A 0 A_SpawnItemEx("FootSep", 0, 0, 20, 0, 0)
			TNT1 A 0 A_JumpIfInventory("EnemyMemory", 20, "ForgetTarget");
			TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
			
			BOS2 AA 2 A_Chase;
			
			BOS2 AA 2 A_Chase;
			
			
			
			BOS2 BB 2 A_Chase;
			
			BOS2 BB 2 A_Chase;
			
			
			BOS2 CC 2 A_Chase;
			
			BOS2 CC 2 A_Chase;
			
			
			BOS2 DD 2 A_Chase;
			
			BOS2 DD 2 A_Chase;
			TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
			Loop;
			
			
		SeeNeverSeen:
			BOS2 AAAABBBBCCCCDDDD 2 A_Chase;
			TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
		Loop;
	
		RAGE:
			TNT1 A 0;
			TNT1 A 0 A_CheckSight("See2");
			BTS2 ABC 1;
			BTS2 DEDF 2;
			BTS2 DEDF 2;
			BTS2 CBA 1 A_FaceTarget;
			TNT1 A 0 HealThing(200);
			TNT1 A 0 A_Jump(96, "MissileInRage");
			Goto See2;
			
		Idle:
		LookingForPlayer:
			TNT1 A 0 A_GiveInventory("SKImp", 1);
			
			BOS2 B 10 A_Look;
			
			BOS2 B 10 A_Look;
			
			BOS2 B 10 A_Look;
			TNT1 A 0 A_SetAngle(angle - 40);
			
			BOS2 B 10 A_Look;
			
			BOS2 B 10 A_Look;
			
			BOS2 B 10 A_Look;
			TNT1 A 0 A_SetAngle(angle + 40);
			
			BOS2 B 10 A_Look;
			
			BOS2 B 10 A_Look;
			
			BOS2 B 10 A_Look;
			
			BOS2 A 0 A_Wander;
			BOS2 AA 2 A_Look;
			TNT1 A 0 A_Recoil(-2);
			
			
			BOS2 B 0 A_Wander;
			BOS2 BB 2 A_Look;
			TNT1 A 0 A_Recoil(-2);
			
			
			BOS2 C 0 A_Wander;
			BOS2 CC 2 A_Look;
			TNT1 A 0 A_Recoil(-2);
			
			
			BOS2 D 0 A_Wander;
			BOS2 DD 2 A_Look;
			TNT1 A 0 A_Recoil(-2);
			
			
			
			TNT1 A 0 A_jump(128, "LookingForPlayer");
			
			
			BOS2 A 0 A_Wander;
			BOS2 AA 2 A_Look;
			TNT1 A 0 A_Recoil(-2);
			
			
			BOS2 B 0 A_Wander;
			BOS2 BB 2 A_Look;
			TNT1 A 0 A_Recoil(-2);
			
			
			BOS2 C 0 A_Wander;
			BOS2 CC 2 A_Look;
			TNT1 A 0 A_Recoil(-2);
			
			
			BOS2 D 0 A_Wander;
			BOS2 DD 2 A_Look;
			TNT1 A 0 A_Recoil(-2);
			
			
			
			
			Goto LookingForPlayer;
			
			
			
		ForgetTarget:
			TNT1 A 0 A_ClearTarget;
			TNT1 A 0 A_TakeInventory("EnemyMemory", 25);
			TNT1 A 0 A_GiveInventory("LookingForPlayer", 1);
			Goto LookingForPlayer;
			
		Melee2:
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			BOS2 EF 8 A_FaceTarget;
			BOS2 G 8 A_SpawnProjectile("KnightAttack",10,0,0,0);
			Goto See2;
		Missile:
			TNT1 A 0;
			//TNT1 A 0 A_Jump(64, "MissileInRage")
			
			TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsACyberdemon", 1, "CheckRetreat");
			TNT1 A 0 A_JumpIfInTargetInventory("TargetIsAMastermind", 1, "CheckRetreat");
			TNT1 A 0 A_JumpIfInventory("StopKickingMyBallsMotherFucker", 1, "MissileInRage");
			
			
			//TNT1 A 0 A_JumpIfInTargetInventory("IsPlayer", 0, 5)
			//TNT1 A 0 A_TakeInventory("CantFire", 1)
			//TNT1 A 0 A_SpawnProjectile("MonsterTargetCheck", 34, 0, 0, 0) 
			//TNT1 A 0 A_SpawnProjectile("MonsterTargetCheckFaster", 34, 0, 0, 0) 
			BOS2 E 3 A_FaceTarget;
			//TNT1 A 0 A_JumpIfInventory("CantFire",1, "SeeContinue")
			
			BOS2 EEEEEEE 2
			{
				A_FaceTarget();
				doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 30 , 64), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
				A_SpawnProjectile ("BallGettingReadyGreen", 64, 30, random (0, 140), 2, random (0, 160));
			}
			BOS2 F 8 A_FaceTarget;
			
			BOS2 G 8 A_SpawnProjectile("GreenPlasmaBall", 36, 0, 0, 1);
		Goto See2;
			
		MissileInRage:
			TNT1 A 0 A_TakeInventory("CantFire", 1);
			TNT1 A 0 A_SpawnProjectile("MonsterTargetCheck", 34, 0, 0, 0);
			TNT1 A 0 A_SpawnProjectile("MonsterTargetCheckFaster", 34, 0, 0, 0);
			BOS2 E 3 A_FaceTarget;
			TNT1 A 0 A_JumpIfInventory("CantFire",1, "SeeContinue");
			BOS2 E 3 A_FaceTarget;
			BOS2 F 6 A_FaceTarget;
			BOS2 G 6 A_SpawnProjectile("GreenPlasmaBall", 36, 0, 0, 1);
			
			
			BAS2 EF 6 A_FaceTarget;
			
			BAS2 G 6 A_SpawnProjectile("GreenPlasmaBall", 36, 0, 0, 1);
			
			
			BOS2 EF 6 A_FaceTarget;
			
			BOS2 G 6 A_SpawnProjectile("GreenPlasmaBall", 36, 0, 0, 1);
			Goto See2;
			
		CheckRetreat:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(500, "Retreat");
			Goto Missile+5;
			
		Retreat:
			TNT1 A 0;
			//TNT1 A 0 A_SpawnItemEx("FootSep", 0, 0)
			TNT1 A 0 A_FaceTarget;
			
			BOS2 DD 2 A_Recoil(2);
			
			BOS2 DD 2 A_Recoil(2);
			TNT1 A 0 A_FaceTarget;
			
			
			BOS2 CCCCBBBBAAAA 2 A_Recoil(1);
		Goto Missile+5;
			
		Pain.Explosive_Impact:
			TNT1 A 0 {vel.z += 5;}
		Pain:
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			TNT1 A 0 A_TakeInventory("StopKickingMyBallsMotherFucker", 1);
			BOS2 H 3;
			BOS2 H 3 A_Pain;
		Goto See2;
			
		Pain.HeavyImpact:
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 {bNOPAIN = true;}
			TNT1 A 0 {vel.z += 5;}
			TNT1 A 0 A_Recoil(8);
			BOS2 H 3;
			BOS2 H 3 A_Pain;
			TNT1 A 0 {bNOPAIN = false;}
		Goto See2;
			
			
		Pain.Kick:
		Pain.KickDowned:
			TNT1 A 0 {bMISSILEMORE = true;}
			TNT1 A 0 {bMISSILEEVENMORE = true;}
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			TNT1 A 0 A_JumpIfInventory("StopKickingMyBallsMotherFucker", 1, "MissileInRage");
			TNT1 A 0 A_GiveInventory("StopKickingMyBallsMotherFucker", 1);
			TNT1 A 0 ThrustThingZ(0,5,0,1);
			TNT1 A 0 {bNOPAIN = true;}
			KNRJ ABCD 5;
			TNT1 A 0 A_Pain;
			KNRJ ABCD 5;
			TNT1 A 0 A_Pain;
			KNRJ ABCD 5;
			TNT1 A 0 A_Pain;
			KNRJ ABCD 5;
		Goto Missile;
			
		Death.Shotgun:
			TNT1 A 0;
			TNT1 A 0 A_Jump(96, "Death.Arm");
			TNT1 A 0 A_JumpIfCloser(250, "Death.Blast");
			Goto Death;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Jump(64, "Death.Arm");
			HKDD A  10;
			HKDD B  10 A_Scream;
			HKDD C  10;
			HKDD D  0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("DeadKnight");
			Stop;
		Death.Arm:
			TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightArm", 55, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 55, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("DyingHellKnight1");
			Stop;
			
		Death.Blast:
		Death.SSG:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAAAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2b", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3b", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeathBrain1", 60, 0, random (0, 360), 2, random (0, 160));
			BOS2 PQRSTU 6;
			TNT1 A 0 doomb_spawn_bloodpool();
			BOS2 VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 1 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_SpawnItem ("DeadKnightHalfDown", 1);
			Stop;
			
		XDeath:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("KnightXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
		Death.Crush:
		Death.Cut:
		Death.Saw:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAAAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfHK", 24, 0, random (0, 360), 2, random (0, 160));
			BBO1 AAAAAAAAAABBBBBCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (30, 110));
			BBO1 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 1 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("DeadKnightHalfDown", 1);
			Stop;
			
		Death.CutLess:
			TNT1 A 0;
			TNT1 A 0 A_Jump(192, "Death.Arm");
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAAAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfHK", 24, 0, random (0, 360), 2, random (0, 160));
			BBO1 AAAAAAAAAABBBBBCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (30, 110));
			BBO1 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 1 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("DeadKnightHalfDown", 1);
			Stop;
			
			
		Death.Headshot:
			TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
			TNT1 A 0 A_JumpIfHealthLower(-80, "Death.HeadExplode");
			TNT1 A 0 A_SpawnItem("HellKnightHeadExplodeHalf", 0, 62);
			TNT1 A 0 A_Pain;
			BTN5 AABBAACC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 62, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_Pain;
			BTN5 AAABBBAAACCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 62, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_Pain;
			BTN5 AAABBBAAACCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 62, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_Pain;
			BTN5 AAABBBAAACCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 62, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_Scream;
			BTN5 DDD 2 A_SpawnProjectile ("Brutal_LiquidBlood", 50, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_NoBlocking;
			BTN5 EEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (30, 110));
			BTN5 FFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SPawnItem ("DeadKnightBTN5F");
			Stop;
			
		Death.headExplode:
			TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
			TNT1 A 0 A_SpawnItem("HellKnightHeadExplode", 0, 62);
			BTN2 AAAAAAAAAAA 2 A_SpawnProjectile ("Brutal_LiquidBlood", 62, 0, random (0, 360), 2, random (30, 110));
			BTN2 BBBBB 2 A_SpawnProjectile ("Brutal_LiquidBlood", 50, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_NoBlocking;
			BTN2 CCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (30, 110));
			BTN2 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadKnightNoHead");
			Stop;
		Death.decaptate:
			TNT1 AAAAA 0 A_SpawnProjectile ("Xdeath1", 62, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightHead", 62, 0, random (0, 360), 2, random (50, 130));
			BTN2 AAAAAAAAAAA 2 A_SpawnProjectile ("Brutal_LiquidBlood", 62, 0, random (0, 360), 2, random (30, 110));
			BTN2 BBBBB 2 A_SpawnProjectile ("Brutal_LiquidBlood", 50, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_NoBlocking;
			BTN2 CCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (30, 110));
			BTN2 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadKnightNoHead");
			Stop;
			
		Death.Plasma:
		Death.Plasma2:
			TNT1 A 0;
			TNT1 A 0 A_BossDeath;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
			TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(1.8, 2.2), 0) );
			BOSB ABC 7 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
			TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(1.8, 2.2), 0) );
			BOSB D 7 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			TNT1 A 0 doomb_spawn_bloodpool();
			BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BOSB E -1;
			Stop;
			
		Death.GreenFire:
			TNT1 A 0;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
			
			TNT1 AA 0 doomb_spawn_burned_flesh;
			
			EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("GreenFlameTrails", (0, 0, 50), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
			Stop;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,35,0,1);
			TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightArm", 62, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 62, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 62, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Jump(255, "Death.Explosive_Impact1", "Death.Explosive_Impact2");
			
		Death.Explosive_Impact1:
			BAH3 A  8 A_Scream;
			BAH3 B  8 A_NoBlocking;
			BAH3 CCCCCC  8 A_CheckFloor("Land1");
			Goto Land1;
			
		Land1:
			TNT1 A 0 A_SpawnItem ("DeadKnightExplosive_Impact1", 1);
			Stop;
			
		Death.Explosive_Impact2:
			BAH3 E  8 A_Scream;
			BAH3 F  8 A_NoBlocking;
			BAH3 GGGGGG  8 A_CheckFloor("Land2");
			Goto Land2;
			
			
		Land2:
			TNT1 A 0 A_SpawnItem ("DeadKnightExplosive_Impact2", 1);
			Stop;
			
			
		Raise:
			BOS2 ONMLKJI 8;
		Goto See2;
			
		Death.Fire:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			BOSB AAAABBBBCCCCDDDD 2 doomb_show_effect("FlameTrails", (0, 0, 30), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_Playsound("props/redfire");
			BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 doomb_show_effect("FlameTrails", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 10 doomb_show_effect("AltSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
			BOSB E -1;
			Stop;
			
			
		CurbstompMarine:
			TNT1 A 0 A_SetInvulnerable;
			KTFP AAAA 3;
			KTFP BCDE 3;
			TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 40, 0, 0);
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			KTFP E 8;
			KTFP F 24;
			KTFP MGGGGG 3;
			KTFP H 2;
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			TNT1 AAA 0 A_SpawnProjectile ("Brains1", 11, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("jaw", 11, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("eye", 11, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_piece", 11, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_piece", 11, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 1, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_spawn_bloodpool();
			KTFP IJ 2;
			KTFP KLLLLL 4;
			TNT1 A 0 A_TakeInventory("Curbstomp_Marine",1);
			TNT1 A 0 A_UnSetInvulnerable;
			TNT1 A 0 A_SpawnItem ("CurbstompedMarine", 1);
			Goto See2;
			
		Death.Fatality:
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_GiveToTarget("GoFatality", 1);
			TNT1 A 0 A_Jump(128, "Death.Fatality3");
			TNT1 A 0 A_GiveToTarget("HKFatality", 1);
			TNT1 A 1 A_NoBlocking;
			TNT1 A 0 A_BossDeath;
		Stop;
		
		Death.Fatality3:
			TNT1 A 0 A_GiveToTarget("HKFatality3", 1);
			TNT1 A 1 A_NoBlocking;
			TNT1 A 0 A_BossDeath;
			Stop;
			
		Pain.KillMe:
		Pain.Taunt:
			Goto Missile;
			
		Crush:
		Death.Stomp:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			BOS2 JKL 2;
			TNT1 AA 0 A_SpawnItem("MeatDeathSmall");
			TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AA 0 bright A_SpawnProjectile ("XDeath2b", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 AA 0 bright A_SpawnProjectile ("XDeath3b", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("CrushedRemains");
			TNT1 A 1;
			TNT1 A 1 A_XScream;
			Stop;
			
	}
}  

CLASS GreenPlasmaBall : doomb_boolet_base { 
	Default {
		Radius 10;
		Height 16;
		Speed 16;
		FastSpeed 20;
		DamageType "GreenFire";
		Projectile;
		+FORCEXYBILLBOARD;
		+THRUGHOST;
		DamageFunction (random(25,35));
		RenderStyle "Add";
		Alpha 1;
		Scale 1.2;
		SeeSound "baron/attack";
		DeathSound "baron/shotx";
		Decal "Scorch";
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
		Spawn1:
			FRPG JK 1 BRIGHT
			{
				A_SpawnItem("GreenFlareSmall",0,0);
				doomb_show_effect("GreenFlameTrails");
			}
		Loop;
			
		Death:
			TNT1 AAAA 0 A_SpawnItemEx("green_particle", 0, 0, 14, (0.1)*Random(10, 40), 0, (0.1)*Random(-40, 40), Random(0, 360), 128);
			TNT1 AAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			EXPL AAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("GreenFlameTrails", (0, 0, 50), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			TNT1 AA 0 A_SpawnItem("GreenFlare",0,0);
			FRPG ABCDEFGH 2 BRIGHT;
			TNT1 AAAAA 19 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		Stop;
	}
}

CLASS KnightAttack : doomb_boolet_base { 
	Default {
		
		+RANDOMIZE;
		+ZDOOMTRANS;
		
		Radius 24;
		Height 16;
		DamageType "HKFT";
		Projectile;
		+RANDOMIZE;
		+FORCEXYBILLBOARD;
		+THRUGHOST;
		RenderStyle "Add";
		Alpha 0.6;
		Damage 10;
		Speed 42;
	}
	States
	{
		Spawn:
			TNT1 A 4 BRIGHT;
		Stop;
	}
}




CLASS StopKickingMyBallsMotherFucker : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}
