CLASS doomb_knight : doomb_monster_base
{ 
	Default {
		
		doomb_monster_base.headshot_multiplier 2;
		doomb_monster_base.head_starting_position 50;//so that if someone forgot to define this number monster dont get headshot from every attack
		doomb_monster_base.legs_height_max -1;//same for legs
		
		
		Radius 24;
		Height 64;
		Mass 1000;
		Speed 8;
		PainChance 50;
		Monster;
		+FLOORCLIP;
		
		HitObituary "$OB_KNIGHTHIT";
		Obituary "$OB_KNIGHT";
		Tag "$FN_HELL";
		
		Scale 0.9;
		Speed 8;
		Health 500;
		PainChance "Kick", 255;
		PainChance "Explosive_Impact", 130;
		PainChance 25;
		PainChance "Saw", 100;
		PainChance "Cut", 100;
		damagefactor "Fatality", 2.0;
		damagefactor "SSG", 0.5;
		damagefactor "Crush", 10.0;
		PainSound "PSXDPN";
		GibHealth 30;
		-BOSSDEATH;
		MaxStepHeight 24;
		MaxDropOffHeight 32;
		BloodType "Brutal_Blood",  "SawBlood";
		DropItem "DemonStrengthRune", 3;
		Obituary "%o was slain by a Hell Knight.";
		DamageType "HKF";
		MeleeDamage 5;
		
		SeeSound "knight/sight";
		ActiveSound "knight/active";
		PainSound "knight/pain";
		DeathSound "knight/death";
		HitObituary "$OB_KNIGHTHIT";
		species 'bruiser';
	}
	States
	{
		Spawn:
			BOS2 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		Stand:
			BOS2 B 10 A_Look;
		Loop;

		See: 
			TNT1 A 0 A_CheckSight("See2");
			BTS2 ABC 1;
			BTS2 DEDFDEDF 2;
			BTS2 CBA 1 A_FaceTarget;
			TNT1 A 0 HealThing(200);
			TNT1 A 0 A_Jump(96, "MissileInRage");
		See2:
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
			BOS2 AAAABBBBCCCCDDDD 2 A_Chase;
			TNT1 A 0 doomb_monster_memory("LookingForPlayer");
		Loop;

		Melee:
			BOS2 E 6 A_FaceTarget;
			TNT1 A 0 A_PlaySound("weapons/gswing");
			BOS2 F 6 A_FaceTarget;
			BOS2 G 6 {doomb_cheap_melee_attack(160, random(30, 60), "HKFT");}
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		Goto See2;
			
			
		Idle:
		LookingForPlayer:
			BOS2 BBB 10 A_Look;
			TNT1 A 0 A_SetAngle(angle - 40);
			BOS2 BBB 10 A_Look;
			TNT1 A 0 A_SetAngle(angle + 40);
			BOS2 BBB 10 A_Look;
			BOS2 AABBCCDD 2
			{
				A_Look();
				A_Wander();
			}
		loop;
			
			
			
		Melee:
			TNT1 A 0 doomb_update_memory();
			BOS2 E 6 A_FaceTarget;
			TNT1 A 0 A_PlaySound("weapons/gswing");
			BOS2 F 6 A_FaceTarget;
			BOS2 G 6 {doomb_cheap_melee_attack(160, random(30, 60), "HKFT");}
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		Goto See2;
		
		Missile:
			TNT1 A 0 doomb_update_memory();
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			TNT1 A 0 doomb_if_boss_retreat(target, "CheckRetreat");
			TNT1 A 0 A_JumpIfInventory("StopKickingMyBallsMotherFucker", 1, "MissileInRage");
			BOS2 E 3 A_FaceTarget;
			
			BOS2 EEEEEEE 2
			{
				A_FaceTarget();
				doomb_show_effect("GreenFlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 30 , 64), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			}
			BOS2 F 8 A_FaceTarget;
			
			BOS2 G 8 A_SpawnProjectile("GreenPlasmaBall", 36, 0, 0, 1);
		Goto See2;
			
		MissileInRage:
			BOS2 EE 3 A_FaceTarget;
			BOS2 F 6 A_FaceTarget;
			BOS2 G 6 A_SpawnProjectile("GreenPlasmaBall", 36, 0, 0, 1);
			tnt1 a 0
			{
				if(random(0, 10) > 3)
					setstate(findstate("MissileInRage") +2);//jumps to BOS2 F 6 A_FaceTarget;
			}
		Goto See2;
			
		CheckRetreat:
			TNT1 A 0 A_JumpIfCloser(500, "Retreat");
		goto missile+5;
		
		Retreat:
			BOS2 DDDDCCCCBBBBAAAA 2
			{
				A_Recoil(1);
				A_FaceTarget();
			}
		Goto Missile+5;
			
		Pain.Explosive_Impact:
			TNT1 A 0 {vel.z += 5;}
		Pain:
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			TNT1 A 0 A_TakeInventory("StopKickingMyBallsMotherFucker", 1);
			BOS2 H 3;
			BOS2 H 3 A_Pain;
		Goto See2;
			
		Pain.HeavyImpact:
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 {bNOPAIN = true;}
			TNT1 A 0 {vel.z += 5;}
			TNT1 A 0 A_Recoil(8);
			BOS2 H 3;
			BOS2 H 3 A_Pain;
			TNT1 A 0 {bNOPAIN = false;}
		Goto See2;
			
			
		Pain.Kick:
		Pain.KickDowned:
			TNT1 A 0 {bMISSILEMORE = true;}
			TNT1 A 0 {bMISSILEEVENMORE = true;}
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			TNT1 A 0 A_JumpIfInventory("StopKickingMyBallsMotherFucker", 1, "MissileInRage");
			TNT1 A 0 A_GiveInventory("StopKickingMyBallsMotherFucker", 1);
			TNT1 A 0 ThrustThingZ(0,5,0,1);
			TNT1 A 0 {bNOPAIN = true;}
			KNRJ ABCD 5;
			TNT1 A 0 A_Pain;
			KNRJ ABCD 5;
			TNT1 A 0 A_Pain;
			KNRJ ABCD 5;
			TNT1 A 0 A_Pain;
			KNRJ ABCD 5;
		Goto Missile;
			
		Death.Shotgun:
			TNT1 A 0;
			TNT1 A 0 A_Jump(96, "Death.Arm");
			TNT1 A 0 A_JumpIfCloser(250, "Death.Blast");
		Goto Death;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Jump(64, "Death.Arm");
			HKDD A  10;
			HKDD B  10 A_Scream;
			HKDD C  10;
			HKDD D  0 A_NoBlocking;
			TNT1 A 0 doomb_severed_limb("DeadKnight", limb_ignore_cvar: true);
		Stop;
		
		Death.Arm:
			TNT1 A 0 doomb_severed_limb("XDeathHellKnightArm", "spawn", (0, 0, 55), doomb_random_velocity(7) );
			TNT1 A 0 doomb_much_blood(55);
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_severed_limb("DyingHellKnight1", limb_ignore_cvar: true);
		Stop;
			
		Death.Blast:
		Death.SSG:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN );
			TNT1 AAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
			TNT1 AAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 60), doomb_random_velocity(7) );
			BOS2 PQRSTU 3;
			TNT1 A 0 doomb_spawn_bloodpool();
			BOS2 VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			BOS2 V -1;
		Stop;
			
		XDeath:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_severed_limb("KnightXDeath", "spawn", (0, 0, 20) );
		Stop;
			
		Death.mini_gun:
			TNT1 A 0 A_Jump(192, "Death.Arm");
		Death.Crush:
		Death.Cut:
		Death.Saw:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
			TNT1 AAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
			TNT1 A 0 doomb_severed_limb("XDeathHalfHK", "spawn", (0, 0, 24), doomb_random_velocity(3) );
			BBO1 AAAAAAAAAABBBBBCCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_severed_limb("DeadKnightHalfDown", limb_ignore_cvar: true);
		Stop;
			
			
		Death.Headshot:
			TNT1 A 0 A_Jump(126, "headshot_1");
			TNT1 A 0 A_JumpIfHealthLower(-80, "Death.HeadExplode");
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 doomb_severed_limb("HellKnightHeadExplode", "spawn", (0, 0, 62) );
		dead_headshot_loop:
			TNT1 A 0 A_Pain;
			BTN5 AABBAACC 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			tnt1 a 0 a_jump(200, "dead_headshot_loop");
		
			TNT1 A 0 A_Screamandunblock;
			BTN5 DDDEEEFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_severed_limb("DeadKnightBTN5F", limb_ignore_cvar: true);
		Stop;

		Death.headExplode:
		headshot_1:
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0
			{
				if(random(0, 1) == 1)
					doomb_severed_limb("HellKnightHeadExplode", "spawn", (0, 0, 62) );
				else
					doomb_severed_limb("XDeathHellKnightHead", "spawn", (0, 0, 62), doomb_random_velocity(7) );
			}
			BTN2 AAAAAAAAAAABBBBB 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_NoBlocking;
			BTN2 CCCCCDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_severed_limb("DeadKnightNoHead", limb_ignore_cvar: true);
		Stop;

		Death.Plasma:
		Death.Plasma2:
			TNT1 A 0 A_BossDeath;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
			TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(1.8, 2.2), 0) );
			BOSB ABC 7 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
			TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(1.8, 2.2), 0) );
			BOSB D 7 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			TNT1 A 0 doomb_spawn_bloodpool();
			BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BOSB E -1;
		Stop;
			
		Death.Explosive_Impact:
			TNT1 A 0 ThrustThingZ(0,35,0,1);
			TNT1 A 0 doomb_severed_limb("XDeathHellKnightArm", "spawn", (0, 0, 62), doomb_random_velocity(7) );
			TNT1 A 0 doomb_severed_limb("XDeathHellKnightLeg", "spawn", (0, 0, 32), doomb_random_velocity(7) );
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
			TNT1 A 0 doomb_much_blood(62);
			TNT1 A 0 A_Jump(255, "Death.Explosive_Impact1", "Death.Explosive_Impact2");
		Death.Explosive_Impact1:
			BAH3 A 8 A_Scream;
			BAH3 B 8 A_NoBlocking;
			BAH3 CCCCCC  8 A_CheckFloor("Land1");
		Land1:
			TNT1 A 0 doomb_severed_limb("DeadKnightExplosive_Impact1");
		Stop;
			
		Death.Explosive_Impact2:
			BAH3 E 8 A_Scream;
			BAH3 F 8 A_NoBlocking;
			BAH3 GGGGGG  8 A_CheckFloor("Land2");
		Land2:
			TNT1 A 0 doomb_severed_limb("DeadKnightExplosive_Impact2");
		Stop;
			
			
		Raise:
			BOS2 ONMLKJI 8;
		Goto See2;
			
		Death.Fire:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			BOSB AAAABBBBCCCCDDDD 2 doomb_show_effect("FlameTrails", (0, 0, 30), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_Playsound("props/redfire");
			BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 doomb_show_effect("FlameTrails", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			BOSB EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 10 doomb_show_effect("AltSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
			BOSB E -1;
			Stop;
			
			
		CurbstompMarine:
			TNT1 A 0 A_SetInvulnerable;
			KTFP AAAA 3;
			KTFP BCDE 3;
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			KTFP E 8;
			KTFP F 24;
			KTFP MGGGGG 3;
			KTFP H 2;
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			TNT1 A 0 doomb_severed_limb("jaw", "spawn", (0, 0, 11), doomb_random_velocity(7) );
			TNT1 A 0 doomb_severed_limb("eye", "spawn", (0, 0, 11), doomb_random_velocity(7) );
			TNT1 AAA 0 doomb_severed_limb("head_piece", "spawn", (0, 0, 11), doomb_random_velocity(7) );
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
			TNT1 A 0 doomb_much_blood(0);
			TNT1 A 0 doomb_spawn_bloodpool();
			KTFP IJ 2;
			KTFP KLLLLL 4;
			TNT1 A 0 A_TakeInventory("Curbstomp_Marine",1);
			TNT1 A 0 A_UnSetInvulnerable;
			TNT1 A 0 doomb_severed_limb("CurbstompedMarine", limb_ignore_cvar: true);
		Goto See2;
			
			
		Pain.Taunt:
		Goto Missile;
			
		Crush:
		Death.Stomp:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			BOS2 JKL 2;
			TNT1 AA 0 doomb_Meat_Death_Small();
			TNT1 A 0 doomb_blood_mist('doomb_non_interactive_blood', 'blood_mist', (0, 0, 5), 6);
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_severed_limb("CrushedRemains");
			TNT1 A 1;
			TNT1 A 1 A_XScream;
		Stop;






		Death.Fatality:
			tnt1 A 0
			{
				doomb_monster_fatality_camera(target);
				A_Pain();
				A_NoBlocking();
				A_BossDeath();
			}
			TNT1 A 0 A_Jump(256, "knight_falatily_1", "knight_falatily_2");
		Stop;
		
	knight_falatily_1:
		HKF1 A 1;
		HKF1 AB 6;
		tnt1 A 0 A_PlaySound("misc/xdeath4", CHAN_AUTO, 1);
		HKF1 C 6 A_PlaySound("PSXDPN", CHAN_AUTO, 1);
		tnt1 AAA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 45), doomb_random_velocity(7) );
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		HKF1 C 5 A_PlaySound("imp/melee", CHAN_AUTO, 1);
		HKF1 C 5;
		tnt1 AAA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 45), doomb_random_velocity(7) );
		
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		tnt1 AAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		tnt1 AAAAAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 45), doomb_random_velocity(7) );
		HKF1 CDEFG 6 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 15) );
		HKF1 H 18;
		tnt1 A 0 
		{
			A_Givetotarget("HealthBonus",10);
			doomb_severed_limb("RapedHK", limb_ignore_cvar: true);
			doomb_destroy_monster_fatality_camera();
		}
	stop;	
	
	
	knight_falatily_2:
		HKF3 A 1
		{
			A_PlaySound("weapons/gswing", CHAN_AUTO, 1);
			A_PlaySound("PSXDPN", CHAN_AUTO, 1);
		}
		HKF3 ABC 6;

		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 A_PlaySound("PSXDPN", CHAN_AUTO, 1);
		HKF3 D 15;
		tnt1 A 0 A_PlaySound("knight/death", CHAN_AUTO, 1);
		
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		tnt1 AAA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 45), doomb_random_velocity(7) );
		tnt1 AAAAAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 45), doomb_random_velocity(7) );

		tnt1 A 0 doomb_severed_limb("XDeathHellKnightArm", "spawn", (0, 0, 40), doomb_random_velocity(7) );
		HKF3 EFGG 7 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 45), doomb_random_velocity(7) );
		
		tnt1 A 0 A_PlaySound("PSXDPN", CHAN_AUTO, 1);
		HKF3 H 15;
		
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		
		tnt1 AAA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 45), doomb_random_velocity(7) );
		tnt1 AAAAAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 45), doomb_random_velocity(7) );
		tnt1 A 0 doomb_severed_limb("XDeathHellKnightHead", "spawn", (0, 0, 40), doomb_random_velocity(7) );
		HKF3 I 20;
		tnt1 A 0 
		{
			A_Givetotarget("HealthBonus",10);
			doomb_severed_limb("NoArmNoHeadFatalizedHK", limb_ignore_cvar: true);
			doomb_destroy_monster_fatality_camera();
		}
	stop;	
}

}

CLASS GreenPlasmaBall : doomb_boolet_base { 
	Default {
		Radius 10;
		Height 16;
		Speed 16;
		FastSpeed 20;
		DamageType "GreenFire";
		Projectile;
		+FORCEXYBILLBOARD;
		+THRUGHOST;
		DamageFunction (random(25,35));
		RenderStyle "Add";
		Alpha 1;
		Scale 1.2;
		SeeSound "baron/attack";
		DeathSound "baron/shotx";
		Decal "Scorch";
	}
	States
	{
		Spawn:
			FRPG JK 1 BRIGHT light ("BARONBALL")
			{
				{doomb_flare_base.doomb_attach_flare(self, "lens_flare_green");}
				
				doomb_show_effect("GreenFlameTrails");
			}
		Loop;
			
		Death:
			TNT1 AAAA 0 doomb_show_effect("green_particle", velocity:(frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
			TNT1 AAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			EXPL AAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("GreenFlameTrails", (0, 0, 50), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			TNT1 AA 0 {doomb_flare_base.doomb_attach_flare(self, "GreenFlare");}
			FRPG ABCDEFGH 2 BRIGHT light ("BARONBALL_X2");
			TNT1 AAAAA 19 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		Stop;
	}
}





CLASS StopKickingMyBallsMotherFucker : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}
