
CLASS DyingHellKnight1 : doomb_body_base { 
	Default {
		Radius 16;
		Height 50 + 22;
		doomb_monster_base.head_starting_position 55;
		Health 100;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		
		damagefactor "Cutless", 0.6;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+FLOORCLIP;
		+NOPAIN;
		+DONTSPLASH;
		Scale 1.1;
	}
	States
	{
		Spawn:
			KSA1 ABCB 6;
			TNT1 A 0 doomb_blood_dying();
			TNT1 A 0 A_PlaySound ("PSXDPN");
			tnt1 a 0 a_jump(200, "spawn");
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_PlaySound("knight/death");
			BTN3 ABCD 6;
			TNT1 A 0 doomb_severed_limb("DeadHellKnightNoArm");
		Stop;
			
		Death.Headshot:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 doomb_severed_limb("HellKnightHeadExplode", "spawn", (0, 0, 62) );
			BTN4 ABCD 6;
			TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
			TNT1 A 0 doomb_severed_limb("DeadHellKnightNoArmNoHead");
		Stop;
			
			
		Death.SSG:
		XDeath:
		Death.Explosive_Impact:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_severed_limb("KnightXDeath");
		Stop;
			
		Death.Cutless:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
			TNT1 A 0 doomb_severed_limb("XDeathHellKnightArm", "spawn", (0, 0, 32), doomb_random_velocity(5));
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
			TNT1 A 0 doomb_severed_limb("XDeathHellKnightHead", "spawn", (0, 0, 32), doomb_random_velocity(5));
			BBO1 AABCD 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_severed_limb("DeadKnightHalfDown");
		Stop;
	}
	
}






CLASS HellKnightHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		-NOBLOCKMAP;
		+SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Radius 10;
		Mass 60;
		Health 60;
		Scale 1.0;
	}
	States
	{
		Spawn:
			HKHE G 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;
		
		Death:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 doomb_severed_limb("HellKnightHeadExplode", "spawn", (0, 0, 40) );
		Stop;

		Death.Trample:
		Crush:
			TNT1 AAAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 9009;
		Stop;

		Death.plasma:
			TNT1 A 0 doomb_severed_limb("XDeathBurnedSkull", "spawn", (0, 0, 32), doomb_random_velocity(5));
			EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		Stop;

		Death.punch:
		Death.Kick:
			HKHE DD 1 A_FaceTarget;
			TNT1 A 0 doomb_severed_limb("XDeathHellKnightHead", "spawn", (0, 0, 15), doomb_random_velocity(5) );
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		Stop;
			
		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			HKHE ABCDEFGH 2;
		Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			HKHE ABCDEFGH 3;
			HKHE H 0 doomb_severed_limb("HellKnightHead");
		Stop;
	}
	
}


CLASS Gib_HellKnightArm: LimbBase
{
	States
	{
		Spawn:
			GHKA I 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;
		
		Death.plasma:
		Death.Fire:
			TNT1 A 0 doomb_spawn_burned_flesh;
		Stop;
			
		Death:    
			TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		Stop;
	}
	
}



CLASS Gib_HellKnightLeg: LimbBase { 
	States
	{
		Spawn:
			GHKL A 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;
		
		Death.plasma: 
		Death.Fire:
			TNT1 A 0 doomb_spawn_burned_flesh;
		Stop;
		
		Death:    
			TNT1 AAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		Stop;
	}
	
}




CLASS XDeathHellKnightTorso: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 12;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GHKT ABCDEFGH 3 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		Loop;

		Death:
			GHKT G 1 doomb_spawn_bloodpool(BPS_SMALL);
			HNDC A 0 doomb_severed_limb("Gib_HellKnightTorso");
		Stop;
	}
}

CLASS Gib_HellKnightTorso: LimbBase { 
	States
	{
		Spawn:
			GHKT I 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;
		
		Death.plasma:
		Death.Fire:
			TNT1 A 0 doomb_spawn_burned_flesh;
		Stop;
		
		Death:    
			TNT1 AAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
		Stop;
	}
	
}


CLASS XDeathKnightLeg : doomb_body_base
{ 
	Default {
		
		Radius 8;
		Height 8;
		Speed 8;
		Mass 6;
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal "GreenBloodSuper";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GORA A 8 
			{
				actor a = doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail");
				if(a)
					a.a_settranslation("red_to_green");
			}
		Loop;

		Death:
			GORA A -1;
		Stop;
	}
}

CLASS XDeathKnightArm : doomb_body_base
{ 
	Default {
		
		Radius 8;
		Height 8;
		Speed 8;
		Mass 6;
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal "GreenBloodSuper";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GORA B 8
			{
				actor a = doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail");
				if(a)
					a.a_settranslation("red_to_green");
			}
		Loop;

		Death:
			GORA B -1;
		Stop;
	}
}






CLASS DeadKnight: CurbstompedMarine { 
	Default {
		
		Radius 24;
		Height 12;
		Scale 1.1;
		+SHOOTABLE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		+FLOORCLIP;
		-SOLID;
		+THRUACTORS;
		damagefactor "Crusher", 50.0;
		Mass 1000;
		Health 200;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			HKDD D -1;
		Stop;
		
		Raise:
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 0 A_SpawnItem("TeleportFog");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("doomb_knight");
		Stop;
	}
	
}		
		
CLASS DeadKnightBTN5F: DeadKnight
{
	States
	{
		Spawn:
			BTN5 F -1;
		Stop;
	}
	
}	   
CLASS DeadKnightHalfDown: DeadKnight
{
	States
	{
		Spawn:
			BBO1 D -1;
		Stop;
	}
	
}
CLASS DeadKnightHalfUp: DeadKnight
{
	States
	{
		Spawn:
		BTO1 D -1;
		Stop;
	}
	
}
CLASS DeadKnightNoHead: DeadKnight { 
	States
	{
		Spawn:
		BTN2 D -1;
			Stop;
	}
	
}
CLASS RapedHK: DeadKnight { 
	States
	{
		Spawn:     
		   HKF1 I -1;
			Stop;
	}
	
}

CLASS DeadKnightExplosive_Impact2: DeadKnight { 
	States
	{
		Spawn: 
		       BAH3 H -1;
			Stop;
	}
	
}
CLASS DeadKnightExplosive_Impact1: DeadKnight { 
	States
	{
		Spawn: 
		       BAH3 D -1;
			Stop;
	}
	
}
CLASS OmgSoDeadHK: DeadKnight { 
	States
	{
		Spawn:
			HKF2 O -1;        
			Stop;
	}
	
}
CLASS NoArmNoHeadFatalizedHK: DeadKnight { 
	States
	{
		Spawn:  
			HKF3 JKLM 5 ;
			HKF3 N -1;
			Stop;
	}
	
}
CLASS DeadHellKnightNoArm: DeadKnight { 
	States
	{
		Spawn:  
			BTN3 D -1;
			Stop;
	}
	
}
CLASS DeadHellKnightNoArmNoHead: DeadKnight { 
	States
	{
		Spawn:  
			BTN4 D -1;
			Stop;
	}
	
}



CLASS XDeathHalfHK : doomb_body_base
{ 
	Default {
		
		+FLOORCLIP;
		Radius 0;
		Height 8;
		Speed 10;
		Mass 8;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
	}
	States
	{
		Spawn:
			BTO1 AABBCC 4 doomb_for_khorne("brutal_Blood");
			HPLA A 0 doomb_severed_limb("DeadKnightHalfUp");
		Stop;

		Crawl:
			TNT1 A 0 doomb_severed_limb("DyingHellKnight");
		Stop;
	}
}























CLASS DyingHellKnight : doomb_body_base
{ 
	Default {
		
		Radius 12;
		Height 30;
		Speed 9;
		Health 70;
		PainSound "PSXDPN";
		DeathSound "grunt/death";
		damagefactor "Kick", 0.1;
		damagefactor "Crush", 2.0;
		damagefactor "Fatality", 20.1;
		PainChance "Kick", 255;
		+SHOOTABLE;
		+FLOORCLIP;
		+LOOKALLAROUND;
		+FRIGHTENED;
		+FLOORCLIP;
		-SOLID;
		+THRUACTORS;
	}
	States
	{
		Spawn:
			BTC1 A 1 A_Look;
		Loop;

		See:
			BTC1 ABC 10 A_Chase;
			TNT1 A 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			BTC1 D 10 A_Pain;
			tnt1 a 0 a_jumpif(random(0, 10) < 1, "death");
		Loop;

		Pain.Kick:
			TNT1 A 0 doomb_severed_limb("Teeth", "spawn", (0, 0, 30), doomb_random_velocity(5));
			TNT1 A 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 30), doomb_random_velocity(5));
			TNT1 A 0 A_Givetotarget("CrueltyBonus1health");
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_FaceTarget;
			BTCK ABA 3;
			BTC1 B 20;
		Goto See;
			
		Death.Kick:
		Death.Fatality:
			tnt1 A 0
			{
				doomb_monster_fatality_camera(target);
				A_Pain();
				A_NoBlocking();
				A_BossDeath();
			}
			HKF2 AAB 6;
			tnt1 A 0 A_PlaySound("PSXDPN", CHAN_AUTO, 1);
			HKF2 DEFFGH 8;
			tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
			tnt1 A 0 A_PlaySound("PSXDPN", CHAN_AUTO, 1);
			HKF2 IJIJIJ 4;
			tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
			tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
			tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
			tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
			tnt1 AAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
			tnt1 AA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 30), doomb_random_velocity(5));
			tnt1 AAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", "spawn", (0, 0, 50), doomb_random_velocity(5));
			HKF2 KL 6;
			tnt1 A 0 doomb_severed_limb("XDeathHellKnightHead", "spawn", (0, 0, 64), doomb_random_velocity(5) );
			HKF2 MNNNNN 6;
			tnt1 A 0 
			{
				A_Givetotarget("HealthBonus",10);
				doomb_severed_limb("OmgSoDeadHK");
				doomb_destroy_monster_fatality_camera();
			}
		Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_SpawnItem ("DeadKnightHalfUp");
			Stop;
			
			
		Death.Stomp:
		Death.SSG:
		XDeath:
			TNT1 A 0 doomb_blood_mist('doomb_non_interactive_blood', 'blood_mist', (0, 0, 5), 6);
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ), BCF_GREEN);
			TNT1 a 0 A_Givetotarget("CrueltyBonus5Health");
			TNT1 A 0 doomb_severed_limb("CrushedRemains");
			TNT1 A 1 A_XScream;
			TNT1 A 1 A_NoBlocking;
			TNT1 A -1;
			Stop;
	}
}