
CLASS DyingHellKnight1 : doomb_body_base { 
	Default {
		Radius 16;
		Height 50 + 22;
		doomb_monster_base.head_starting_position 55;
		Health 100;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Avoid", 0.0;
		
		damagefactor "Cutless", 0.6;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		+FLOORCLIP;
		+NOPAIN;
		+DONTSPLASH;
		Scale 1.1;
	}
	States
	{
		Spawn:
			KSA1 ABCB 6;
			TNT1 A 0 doomb_blood_dying();
			TNT1 A 0 A_PlaySound ("PSXDPN");
			tnt1 a 0 a_jump(200, "spawn");
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_PlaySound("knight/death");
			BTN3 ABCD 6;
			TNT1 A 0 A_SpawnItem("DeadHellKnightNoArm");
			Stop;
			
		Death.Headshot:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_SpawnItem("HellKnightHeadExplode", 0, 62);
			BTN4 ABCD 6;
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 A 0 A_SpawnItem("DeadHellKnightNoArmNoHead");
			Stop;
			
			
		Death.SSG:
		XDeath:
		Death.Explosive_Impact:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("KnightXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
		Death.Cutless:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath4", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightHead", 32, 0, random (0, 360), 2, random (0, 160));
			BBO1 AABCD 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("DeadKnightHalfDown", 1);
			Stop;
			
	}
	
}


CLASS FrozenHellKnight : ACTOR { 
	Default {
		
		+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
		
		Radius 24;
		Height 64;
		Health 60;
		Scale 1.1;
	}
	States
	{
		Spawn:
			FZD6 A 200;
			FZD6 A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZD6 A 50;
			FZD6 B 2;
			FZD6 A 50;
			FZD6 B 2;
			FZD6 A 50;
			FZD6 B 2;
			FZD6 A 25;
			FZD6 B 2;
			FZD6 A 25;
			FZD6 B 2;
			FZD6 A 10;
			FZD6 B 2;
			FZD6 A 10;
			FZD6 B 2;
			FZD6 A 10;
			FZD6 BABABA 2;
		Death.Fire:
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_spawnItem("HellKnight");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("MuchBlood", 48, 0, random (0, 360), 2, random (0, 160));
			FZD6 C 300;
			FZD6 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
			Stop;
	}
}


CLASS XDeathHellKnightArm: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 12;
		BounceFactor 0.4;
		BounceCount 3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GHKA ABCDEFGH 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			GHKA I 1;
			GHKA I -1;
			Stop;
	}
}


CLASS HellKnightHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		damagefactor "SuperPunch", 9.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		-NOBLOCKMAP;
		+SOLID;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Radius 10;
		Mass 60;
		Health 60;
		Scale 1.0;
	}
	States
	{
		Spawn:
			HKHE G 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem("HellKnightHeadExplode", 0, 10);
			Stop;
		Death.Trample:
		Crush:
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0;
			Stop;
		Death.SuperPunch:
		Death.Kick:
			HKHE DD 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			HKHE ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			HKHE ABCDEFGH 3;
			HKHE H 0 A_SpawnItem("HellKnightHead");
			Stop;
			
			
	}
	
}

CLASS XDeathHellKnightHeadKicked: XDeathHellKnightHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}


CLASS XDeathHellKnightHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			HKHE ABCDEFGH 3;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			HKHE E 1;
			HKHE E 1 A_SpawnItem("HellKnightHead",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HellKnightArm: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			GHKA I 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma:
		Death.Fire:
			TNT1 A 0 doomb_spawn_burned_flesh;
			Stop;
			
		Death:    
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("Xdeath1", 0, 0, random (0, 360), 2, random (0, 360));
			Stop;
	}
	
}


CLASS XDeathHellKnightLeg: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 12;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GHKL ABCDEFG 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			GHKL A 1;
			GHKL A -1;
			Stop;
	}
}

CLASS Gib_HellKnightLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			GHKL A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma: 
		Death.Fire:
			TNT1 A 0 doomb_spawn_burned_flesh;
			Stop;
		Death:    
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("Xdeath1", 0, 0, random (0, 360), 2, random (0, 360));
			Stop;
	}
	
}




CLASS XDeathHellKnightTorso: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 12;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GHKT ABCDEFGH 3 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_SpawnItem("Blood");
			GHKT G 1;
			HNDC A 0 A_SpawnItem("Gib_HellKnightTorso",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HellKnightTorso: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			GHKT I 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma:
		Death.Fire:
			TNT1 A 0 doomb_spawn_burned_flesh;
			Stop;
		Death:    
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("Xdeath1", 0, 0, random (0, 360), 2, random (0, 360));
			Stop;
	}
	
}


CLASS XDeathKnightLeg : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 8;
		Mass 6;
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal "GreenBloodSuper";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GORA A 8 A_SpawnProjectile("GreenBloodTrail",0,0,180,2);
			Loop;
		Death:
			GORA A -1;
			Stop;
	}
}

CLASS XDeathKnightArm : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 8;
		Mass 6;
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal "GreenBloodSuper";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			GORA B 8 A_SpawnProjectile("GreenBloodTrail",0,0,180,2);
			Loop;
		Death:
			GORA B -1;
			Stop;
	}
}






CLASS DeadKnight: CurbstompedMarine { 
	Default {
		
		Radius 24;
		Height 12;
		Scale 1.1;
		+SHOOTABLE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		+FLOORCLIP;
		-SOLID;
		+THRUACTORS;
		damagefactor "Crusher", 50.0;
		Mass 1000;
		Health 200;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			HKDD D -1;
			Stop;
		Raise:
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 0 A_SpawnItem("TeleportFog");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("doomb_knight");
			Stop;
	}
	
}		
		
CLASS DeadKnightBTN5F: DeadKnight { 

	States
	{
		Spawn:
			BTN5 F -1;
			Stop   ;
	}
	
}	   
CLASS DeadKnightHalfDown: DeadKnight { 

	States
	{
		Spawn:
		BBO1 D -1;
			Stop;
	}
	
}
CLASS DeadKnightHalfUp: DeadKnight { 
	States
	{
		Spawn:
		BTO1 D -1;
			Stop;
	}
	
}
CLASS DeadKnightNoHead: DeadKnight { 
	States
	{
		Spawn:
		BTN2 D -1;
			Stop;
	}
	
}
CLASS RapedHK: DeadKnight { 
	States
	{
		Spawn:     
		   HKF1 I -1;
			Stop;
	}
	
}

CLASS DeadKnightExplosive_Impact2: DeadKnight { 
	States
	{
		Spawn: 
		       BAH3 H -1;
			Stop;
	}
	
}
CLASS DeadKnightExplosive_Impact1: DeadKnight { 
	States
	{
		Spawn: 
		       BAH3 D -1;
			Stop;
	}
	
}
CLASS OmgSoDeadHK: DeadKnight { 
	States
	{
		Spawn:
			HKF2 O -1;        
			Stop;
	}
	
}
CLASS NoArmNoHeadFatalizedHK: DeadKnight { 
	States
	{
		Spawn:  
			HKF3 JKLM 5 ;
			HKF3 N -1;
			Stop;
	}
	
}
CLASS DeadHellKnightNoArm: DeadKnight { 
	States
	{
		Spawn:  
			BTN3 D -1;
			Stop;
	}
	
}
CLASS DeadHellKnightNoArmNoHead: DeadKnight { 
	States
	{
		Spawn:  
			BTN4 D -1;
			Stop;
	}
	
}



CLASS XDeathHalfHK : ACTOR { 
	Default {
		
		+FLOORCLIP;
		Radius 0;
		Height 8;
		Speed 10;
		Mass 8;
		BounceFactor 0.3;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
	}
	States
	{
		Spawn:
			BTO1 AABBCC 4 A_SpawnProjectile("Blood",0,0,180,2);
			//TNT1 A 0 A_Jump(128, "Crawl")
			HPLA A 0 A_SpawnItem("DeadKnightHalfUp",0,0,0,1);
			Stop;
		Crawl:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("DyingHellKnight");
			TNT1 A 0;
			Stop;
	}
}























CLASS DyingHellKnight : ACTOR { 
	Default {
		
		Radius 12;
		Height 30;
		Speed 9;
		Health 70;
		PainSound "PSXDPN";
		DeathSound "grunt/death";
		damagefactor "Kick", 0.1;
		damagefactor "Crush", 2.0;
		damagefactor "Fatality", 20.1;
		PainChance "Kick", 255;
		+SHOOTABLE;
		+FLOORCLIP;
		//+NOBLOCKMAP
		+LOOKALLAROUND;
		+FRIGHTENED;
		+FLOORCLIP;
		-SOLID;
		+THRUACTORS;
	}
	States
	{
		
		
		Pain.Kick:
			TNT1 A 0 A_SpawnProjectile ("Teeth", 30, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("Blood", 30, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("TeethNoBounce", 30, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem("CrueltyBonus1health");
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_FaceTarget;
			BTCK ABA 3;
			BTC1 B 20;
			Goto See;
			
		Death.Kick:
		Death.Fatality:
			TNT1 A 0 A_GiveToTarget("GoFatality", 1);
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("HKFatality2", 1);
			Stop;
			
		Spawn:
			BTC1 A 1 A_Look;
			Loop;
		See:
			BTC1 ABC 10 A_Chase;
			TNT1 A 0 A_SpawnItemEx("Brutal_FlyingBlood", 0, 0, 10, 0, 0);
			BTC1 D 10 A_Pain;
			TNT1 A 0 A_SpawnItemEx("Brutal_FlyingBlood", 0, 0, 10, 0, 0);
			tnt1 a 0 a_jumpif(random(0, 10) < 1, "death");
		Loop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_SpawnItem ("DeadKnightHalfUp");
			Stop;
			
			
		Death.Stomp:
		Death.SSG:
		XDeath:
			TNT1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AAAAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AA 0 bright A_SpawnProjectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 AA 0 bright A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 A 0 A_SpawnItem ("CrushedRemains");
			TNT1 A 1;
			TNT1 A 1 A_XScream;
			TNT1 A 1 A_NoBlocking;
			TNT1 A -1;
			TNT1 AAA 0 A_SpawnItem ("CrueltyBonus5Health");
			Stop;
	}
}


CLASS KnightXDeath : ACTOR { 
	Default {
		
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
	States
	{
		Spawn:
			tnt1 a 0 A_Explode(3,600, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightTorso", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathHellKnightLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath4", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath2", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath3", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece2", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece1", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHellKnightHead", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("doomb_red_blood_pool");
			
			TNT1 A 1;
			TNT1 A 2;
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
		Stop;
	}
}
