//===========================================================================
//
// Cacodemon
//
//===========================================================================
CLASS doomb_cacodemon : doomb_monster_base Replaces Cacodemon { 
Default {
	
	bloodtype "Blue_Blood", "BlueSawBlood";
	+NOBLOODDECALS;
	GibHealth 25;
	damagefactor "Crush", 10.0;
	damagefactor "SSG", 10.0;
	Radius 31;
	Height 56;
	Mass 400;
	Speed 8;
	Health 320;
	PainChance 128;
	PainChance "Kick", 255;
	PainChance "Avoid", 90;
	PainChance "Saw", 255;
	Monster;
	Scale 0.9;
	+FLOAT +NOGRAVITY;
	SeeSound "caco/sight";
	PainSound "caco/pain";
	DeathSound "caco/death";
	ActiveSound "caco/active";
	DamageFactor "CauseObjectsToSplash", 0.0;
	Obituary "$OB_CACO";
	HitObituary "$OB_CACOHIT";
	DropItem "DemonStrengthRune", 5;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
}
States
{
	
	Pain.Avoid: 
		HEAD A 1 A_FaceTarget;
		TNT1 A 0 ThrustThing(angle*256/360+randompick(64, 192), 15, 0, 0);
		HEAD A 5 A_FaceTarget;
		Goto Missile;
		
	Spawn:
		HEAD A 0;
		HEAD A 1 A_Look;
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "FatalityMarine");
	Stand:
		HEAD A 10 A_Look;
	Loop;
		
	SearchPlayer:
		TNT1 A 0 A_ClearTarget;
		TNT1 A 0 A_TakeInventory("EnemyMemory", 40);
		HEAD A 10 A_Look;
		TNT1 A 0 A_SetAngle(angle - 30);
		HEAD A 10 A_Look;
		TNT1 A 0 A_SetAngle(angle + 30);
		HEAD A 10 A_Look;
		TNT1 A 0 A_SetAngle(angle + 30);
		HEAD A 10 A_Look;
		TNT1 A 0 A_SetAngle(angle - 30);
		HEAD AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 2
		{
			A_Look();
			A_Wander();
		}
	loop;
		
	See:
		HEAD AAA 2 A_Chase;
		TNT1 A 0 A_JumpIfCloser(99, "Melee");
		TNT1 A 0 A_TakeInventory("EnemyMemory", 1);
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "SearchPlayer");
	Loop;
		
	Missile:
		TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
		TNT1 A 0 A_JumpIfCloser(140, "Melee");
		TNT1 A 0 A_Jump (198, 3);
	Goto Avoid;
		TNT1 AAA 0;
		HEAD B 4 A_FaceTarget;
		HEAD C 4 A_FaceTarget;
		HEAD D 4 BRIGHT A_SpawnProjectile("CacodemonBall", 34, 0, 0, 0);
		Goto See;
		
	Melee:
		HEAD B 4 A_Facetarget;
		HEAD C 4 A_Recoil(-5);
		tnt1 a 0 doomb_cheap_melee_attack(80, random(20, 80), "HKFT");
		TNT1 A 0 A_PlaySound("imp/melee");
		HEAD D 4;
		TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "FatalityMarine");
	Goto See;
		
	Pain:
		HEAD E 3 A_Pain;
		HEAD E 3;
		TNT1 A 0 A_Jump (128, 1);
	Goto Avoid;
		HEAD F 6;
	Goto See;
		
	Pain.Kick:
	Pain.HeavyImpact:
		TNT1 A 0 A_FaceTarget;
		HEAD E 6 A_Recoil(5);
		HEAD E 6 A_Pain;
		HEAD F 10;
	Goto See;
		
	Avoid:
		HEAD AAAA 6 A_FastChase;
		HEAD BC 5 A_FaceTarget;
		HEAD D 5 BRIGHT A_HeadAttack;
	Goto See;
		
	Death.Shotgun:
		TNT1 A 0 A_JumpIfCloser(500, "Death.Brutal");
	Death:
		HEAD G 3 A_Scream;
		HEAD H 3 A_NoBlocking;
		HEAD IJK 4 A_SpawnProjectile ("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("DeadCacoDemon1", 1);
		HEAD L -1;
	Stop;
		
	Deathlulz:
		H3D2 A 6 A_Scream;
		H3D2 B 6 A_NoBlocking;
		H3D2 CD 6;
		TNT1 AAAA 0 A_SpawnProjectile ("Blue_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
		H3D2 E 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("DeadCacoDemon1", 1);
		H3D2 F -1;
	Stop;
		
	Death.Fatality:
		TNT1 A 0
		{
			A_NoBlocking();
			A_Pain();
			A_GiveToTarget("GoFatality", 1);

			if(random(1, 2) > 1)
				A_GiveToTarget("CacoDemonFatality", 1);
			else
				A_GiveToTarget("CacoDemonFatality2", 1);
		}
	Stop;
		
	Death.saw:
		TNT1 A 0 A_SetFloorClip;
		TNT1 A 0 A_Scream;
		TNT1 O 0 A_NoBlocking;
		TNT1 AAAAA 0 A_SpawnProjectile ("Blue_FlyingBlood", 47, 0, random (0, 360), 2, random (30, 150));
		TNT1 A 0
		{
			A_SpawnProjectile ("CacoXDeath3", 50, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("CacoXDeath4", 50, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("CacoXDeath6", 50, 0, random (0, 360), 2, random (0, 160));
		}
		HEDC AB 9 A_SpawnProjectile ("CacoXDeath7", 50, 0, random (0, 360), 2, - random (0, 160));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("SawedCacodemon", 1);
		HEDC C -1;
	Stop;
		
	Death.cut:
		TNT1 O 0 A_Jump(180, 2);
	Goto Death;
		TNT1 A 0 A_SetFloorClip;
		TNT1 A 0 A_Scream;
		TNT1 O 0 A_NoBlocking;
		CCD3 A 6 A_SpawnProjectile ("RipCaco", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("Dead_lower_caco_Half", 1);
		CCD3 B -1;
	Stop;

	Death.cutless:
		TNT1 O 0 A_Jump(64, 2);
	Goto Death.Brutal;
		TNT1 A 0 A_SetFloorClip;
		TNT1 A 0 A_SetFloorClip;
		TNT1 A 0 A_Scream;
		TNT1 O 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("RipCaco", 0, 0, random (0, 360), 2, random (0, 160));
		CCD3 A 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("Dead_lower_caco_Half", 1);
		CCD3 B -1;
	Stop;
		
	Death.Brutal:
		TNT1 A 0 A_SetFloorClip;
		TNT1 A 0 A_SetFloorClip;
		TNT1 A 0 A_Scream;
		TNT1 O 0 A_NoBlocking;
		TNT1 AAAAA 0 A_SpawnProjectile ("Blue_FlyingBlood", 47, 0, random (0, 360), 2, random (30, 150));
		TNT1 A 0 A_SpawnProjectile ("CacoXDeath3", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("CacoXDeath4", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("CacoXDeath6", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("CacoXDeath7", 50, 0, random (0, 360), 2, random (0, 160));
		CCD1 A 0 A_SpawnItem("caco_with_head_hole");
	Stop;
		
		
	Death.Plasma:
	Death.Plasma2:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		EXPL AAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		CACB A 10 doomb_show_effect("ExplosionSmoke", (0, 0, 24), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		CACB A 0 A_SpawnProjectile ("XDeathBurnedBlueMeat1", 0, 0, random (0, 360), 2, random (0, 160));
		CACB A 0 A_SpawnProjectile ("XDeathBurnedBlueMeat2", 0, 0, random (0, 360), 2, random (0, 160));
		CACB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		CACB B -1;
	Stop;
	
	Death.fire:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Playsound("props/redfire");
		TNT1 A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		tnt1 B 0
		{
			A_Explode(3,30, damagetype:"fire");
			A_SpawnItem("RedFlare", 0, 5);
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			A_SpawnProjectile ("SmallFireTrail324", 0, 0, random (0, 360), 2, -random (0, 130));
		}
		HEAD NNEE 1 Bright A_Wander;
		tnt1 B 0
		{
			A_Explode(3,30, damagetype:"fire");
			A_SpawnItem("RedFlare", 0, 5);
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			A_SpawnProjectile ("SmallFireTrail324", 0, 0, random (0, 360), 2, -random (0, 130));
			A_SpawnProjectile("FireballExplosionFlamesBig", 40, 0, random (0, 360), 2, random (50, 130));
			doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
		}
	mini_fire:
		HEAD EE 1 Bright A_Wander;
		TNT1 A 0 A_Recoil(-1);
		tnt1 B 0
		{
			A_Explode(3,30, damagetype:"fire");
			A_SpawnItem("RedFlare", 0, 5);
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			A_SpawnProjectile ("SmallFireTrail324", 0, 0, random (0, 360), 2, -random (0, 130));
			doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
		}
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 15, "Death_fire");
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
	Loop;
	
	Death_fire:
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_NoBlocking;
		HEAD P 1 A_SpawnItem("o_100SmallFireFocusSpawnerz");
		TNT1 A 0 A_Playsound("props/redfire");
		HEAD PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP 8 A_SpawnProjectile("FireballExplosionFlamesBig", 15, 0, random (0, 360), 2, random (50, 130));
		HEAD P 1 A_SpawnItem("o_100SmallFireFocusSpawnerz");
		HEAD PPPPPPPPPPPPPPPPPPPPPPPP 6 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		HEAD P -1;
	Stop;
	
	Death.Explosive_Impact:
	XDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("CacoXDeath", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;
	
	Death.SSG:
		TNT1 A 0;
		CCD3 A 1 A_Pain;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Scream;
		TNT1 AAAAAAAAAAAAA 0 A_SpawnProjectile ("Blue_FlyingBlood", 50, 0, random (160, 200), 2, random (0, 50));
		TNT1 A 0 A_SpawnProjectile ("CacoXDeath2", 50, 0, random (160, 200), 2, random (20, 40));
		TNT1 A 0 A_SpawnProjectile ("CacoXDeath1", 50, 0, random (160, 200), 2, random (20, 40));
		TNT1 A 0 A_SpawnProjectile ("CacoXDeath3", 50, 0, random (160, 200), 2, random (20, 40));
		TNT1 A 0 A_SpawnProjectile ("CacoXDeath4", 50, 0, random (160, 200), 2, random (20, 40));
		TNT1 AA 0 A_SpawnProjectile ("CacoXDeath5", 50, 0, random (160, 200), 2, random (20, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("CacoXDeath6", 50, 0, random (160, 200), 2, random (20, 40));
		TNT1 AAAAAA 0 A_SpawnProjectile ("CacoXDeath7", 50, 0, random (160, 200), 2, random (20, 40));
		CCD3 A 6 A_NoBlocking;
		TNT1 A 0 doomb_spawn_bloodpool();
		CCD3 B -1;
	Stop;
	
	Crush:
		CRS2 B 5 A_PlaySound("misc/xdeath4");
		CRS2 B -1 doomb_spawn_bloodpool();
	Stop;
	
	Pain.Taunt:
		TNT1 A 0;
	Goto Missile;
	
	
	FatalityMarine:
		CFPF A 1 A_SetInvulnerable;
		TNT1 A 0 A_PlaySound("DSFDTHE");
		CFPF ABCBCBCBC 10
		{
			A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("Brutal_Blood", 25, 0, random (0, 360), 2, random (0, 160));
		}
		TNT1 A 0 A_TakeInventory("Curbstomp_Marine",1);
		TNT1 A 0 A_SpawnItem ("PlayerJustGotCutInHalf", 1);
		TNT1 A 0 A_UnSetInvulnerable;
	Goto See;

	raise:
		TNT1 A 1 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 0), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("doomb_cacodemon");
	Stop;
}
}

//===========================================================================
//
// Cacodemon plasma ball
//
//===========================================================================
CLASS CacodemonBall_ : doomb_boolet_base Replaces CacodemonBall
{ 
Default
{
	Radius 6;
	Height 6;
	Speed 14;
	FastSpeed 18;
	DamageFunction (random(20,25));
	Projectile;
	+RANDOMIZE;
	+THRUGHOST;
	RenderStyle "Add";
	Alpha 1;
	damagetype "Plasma";
	SeeSound "caco/attack";
	DeathSound "caco/shotx";
	Decal "Scorch";
}

States
{
	Spawn:
		BAL2 AA 2 BRIGHT light ("CACOBALL") A_SpawnItem("RedFlareMedium",0,0);
		BAL2 BB 2 BRIGHT light ("CACOBALL") A_SpawnItem("BlueFlareMedium",0,0);
	Loop;

	Death:
		TNT1 AAAA 0
		{
			A_SpawnProjectile ("Shoque", 3, 0, random (0, 360), 2, random (0, 360));
			A_SpawnProjectile ("ShoqueAzul", 3, 0, random (0, 360), 2, random (0, 360));
		}
		BAL2 CDEF 6 BRIGHT light ("CACOBALL_X2");
	Stop;
}
}

CLASS Shoque : visual_sfx
{ 
Default {
	Radius 1;
	Height 1;
	Speed 2;
	Damage 0;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+DONTSPLASH;
	+MISSILE;
	+FORCEXYBILLBOARD;
	+CLIENTSIDEONLY;
	RenderStyle "Add";
	Scale 0.7;
	Gravity 0;
	Alpha 0.5;
}
States
{
	Spawn:
		SHOQ ABCDEFG 1 BRIGHT;
	Stop;
}
}


CLASS ShoqueAzul : visual_sfx { 
Default {
	Radius 1;
	Height 1;
	Speed 3;
	Damage 0;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+DONTSPLASH;
	+MISSILE;
	+FORCEXYBILLBOARD;
	+CLIENTSIDEONLY;
	RenderStyle "Add";
	Scale 1.0;
	Gravity 0;
}

States
{
	Spawn:
		TNT1 A 1;
		SH1K ABCDEFG 2 BRIGHT;
	Stop;
}

}