
CLASS BrutalizedCacodemon1 : ACTOR { 
	Default {
		
		
		Radius 24;
		Height 48;
		Health 50;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Avoid", 0.0;
		damagefactor "KillMe", 0.0;
		damagefactor "Cutless", 0.6;
		bloodtype "Blue_Blood";
		bloodcolor darkblue;
		Mass 999999;
		-SOLID;
		+NOBLOODDECALS;
		+SHOOTABLE;
		+FLOORCLIP;
		+DONTSPLASH;
		+NOPAIN;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(96, "NoSuffer");
			TNT1 A 0 A_Jump(64, "Fall");
			CCD1 AAEEAAEEAAAAEEAAEEAA 5 A_SpawnProjectile ("BlueBloodTrails", 40, 0, random (0, 360), 2, random (0, 160));
		Fall:
			TNT1 AAAAA 0 A_NoBlocking();
			TNT1 A 0 A_Fall();
			TNT1 A 0 A_ChangeFlag("SHOOTABLE", 0);
			TNT1 A 0 A_ChangeFlag("SOLID", 0);
			CCD1 ABC 6;
			CCD1 C -1;
			Stop;
			
		Death:
			TNT1 AAAAA 0 A_SpawnProjectile ("Blue_FlyingBlood", 47, 0, random (0, 360), 2, random (30, 150));
			TNT1 A 0 A_SpawnProjectile ("CacoXDeath3", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("CacoXDeath4", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("CacoXDeath6", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("CacoXDeath7", 40, 0, random (0, 360), 2, random (0, 160));
			CCD2 A 10;
			TNT1 A 0 A_SpawnItem("BrutalizedCacodemon2");
			Stop;
			
		NoSuffer:
			TNT1 AAAAA 0 A_SpawnProjectile ("Blue_FlyingBlood", 47, 0, random (0, 360), 2, random (30, 150));
			TNT1 A 0 A_SpawnProjectile ("CacoXDeath3", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("CacoXDeath4", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("CacoXDeath6", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("CacoXDeath7", 40, 0, random (0, 360), 2, random (0, 160));
			CCD2 B 6;
			TNT1 A 0 A_ChangeFlag("SHOOTABLE", 0);
			TNT1 A 0 A_ChangeFlag("SOLID", 0);
			CCD2 B -1;
			Stop;
			
	}
	
}
CLASS BrutalizedCacodemon2 : ACTOR { 
	Default {
		
		
		Radius 24;
		Height 48;
		Health 50;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Avoid", 0.0;
		damagefactor "KillMe", 0.0;
		damagefactor "Cutless", 0.6;
		bloodtype "Blue_Blood";
		bloodcolor darkblue;
		Mass 999999;
		-SOLID;
		+NOBLOODDECALS;
		+SHOOTABLE;
		+FLOORCLIP;
		+DONTSPLASH;
		+NOPAIN;
		Scale 1.0;
	}
	States
	{
		Spawn:
			CCD2 AEAEAEAEAEAEAEAE 5 A_SpawnProjectile ("BlueBloodTrails", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_Fall();
			CCD2 B 6;
			TNT1 A 0 A_ChangeFlag("SHOOTABLE", 0);
			TNT1 A 0 A_ChangeFlag("SOLID", 0);
			CCD2 B -1;
			Stop;
			
		Death:
			TNT1 AAAAA 0 A_SpawnProjectile ("Blue_FlyingBlood", 47, 0, random (0, 360), 2, random (30, 150));
			TNT1 AAAA 0 A_SpawnProjectile ("Blue_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AA 0 A_SpawnProjectile ("CacoXDeath6", 30, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("CacoXDeath7", 30, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			CCD3 A 10;
			CCD3 B -1;
			Stop;
			
	}
	
}


CLASS FrozenCacodemon : ACTOR { 
	Default {
		
		+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
		
		Radius 31;
		Height 56;
		Health 60;
		Scale 1.0;
	}
	States
	{
		Spawn:
			FZDC A 200;
			FZDC A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZDC A 50;
			FZDC B 2;
			FZDC A 50;
			FZDC B 2;
			FZDC A 50;
			FZDC B 2;
			FZDC A 25;
			FZDC B 2;
			FZDC A 25;
			FZDC B 2;
			FZDC A 10;
			FZDC B 2;
			FZDC A 10;
			FZDC B 2;
			FZDC A 10;
			FZDC BABABA 2;
		Death.Fire:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_spawnItem("Cacodemon");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 AAAAAAAAAAAAA 0 A_SpawnProjectile ("Blue_FlyingBlood", 50, 0, random (160, 200), 2, random (0, 50));
			TNT1 A 0 A_SpawnProjectile ("CacoXDeath2", 50, 0, random (0, 360), 2, random (20, 40));
			TNT1 A 0 A_SpawnProjectile ("CacoXDeath1", 50, 0, random (0, 360), 2, random (20, 40));
			TNT1 A 0 A_SpawnProjectile ("CacoXDeath3", 50, 0, random (0, 360), 2, random (20, 40));
			TNT1 A 0 A_SpawnProjectile ("CacoXDeath4", 50, 0, random (0, 360), 2, random (20, 40));
			TNT1 AA 0 A_SpawnProjectile ("CacoXDeath5", 50, 0, random (0, 360), 2, random (20, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("CacoXDeath6", 50, 0, random (0, 360), 2, random (20, 40));
			TNT1 AAAAAA 0 A_SpawnProjectile ("CacoXDeath7", 50, 0, random (0, 360), 2, random (20, 40));
			Stop;
	}
}

