CLASS BurningZombie : doomb_body_base { 
	Default {
		
		Radius 12;
		Height 56;
		Speed 5;
		Scale 0.85;
		Health 100;
		GibHealth 25;
		damagefactor "Fire", 0.0;
		damagefactor "Explosive_Impact", 10.0;
		MONSTER;
		-COUNTKILL;
		+NOICEDEATH;
		+FRIENDLY;
		+FLOORCLIP;
		+SHOOTABLE;
		+NOBLOCKMONST;
		+DONTSPLASH;
		
		Gravity 0.7;
		bloodtype "DeadBlood";
		Obituary "%o was near someone in flames.";
		MaxDropOffHeight 6000;
		
		Mass 999999;
	}
	States
	{
		Spawn:
			tnt1 B 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 A_PlaySound("BURNZOM");
		Suffer:
			BDT1 AAABBBCCCDDD 1 Bright light("BIGREDTORCH")
			{
				A_Wander();
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
			}

			TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
			TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 12, "Death");
		Loop;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,60,0,1);
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 A 0;
		Looping:
			BDT3 AAAABBBBCCCCDDDD 1 Bright light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				if(vel.z == 0)
					setstatelabel("falldeath");
			}
			Loop;
			
		FallDeath:
			TNT1 AAAAAAAAAA 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 AAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 10), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 AAAA 0 A_SpawnProjectile("XDeath1", 10, 0, random (0, 360), 2, random (20, 150));
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 A 0 A_Explode(100, 128);
		Death:
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_Jump(128, "Death2");
			BDT1 EEFFGGHHiijjkkLLmm 3 Bright light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			NJEX AAAAAAAAAAAAAAAAAA 10 Bright doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			NJEX A -1;
		Stop;
		
		Death2:
			BDT1 EEFFGGHHiijjkkLLmmBBBBBBBBBBBBBBBBBB 3 Bright light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			NJEX BBBBBBBBBBBBBBBBBB 10 Bright doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			NJEX B -1;
		Stop;

		XDEATH:
		DEATH.SSG:
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 AA 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchMeatDeath", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("BurningFlyingMeatPiece", 64, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			Stop;
	}
}


CLASS PoorGuyBurningLife : Inventory { 
	Default {
		
		inventory.maxamount 20;
	}
}





CLASS BurningZombieMan : doomb_body_base { 
	Default {
		
		Radius 12;
		Height 56;
		Speed 3;
		Health 30;
		GibHealth 25;
		damagefactor "Fire", 0.0;
		damagefactor "Ice", 0.0;
		damagefactor "Explosive_Impact", 10.0;
		MONSTER;
		-COUNTKILL;
		+FRIENDLY;
		+FLOORCLIP;
		+SHOOTABLE;
		+NOBLOCKMONST;
		
		Gravity 0.7;
		bloodtype "DeadBlood";
		Obituary "%o was near someone in flames.";
		MaxDropOffHeight 6000;
		
		Mass 999999;
	}
	States
	{
		Spawn:
			tnt1 B 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 A_PlaySound("BURNZOM");
			Goto Suffer;
		Suffer:
			BRZ3 AAABBBCCCBBB 1 BRIGHT light("BIGREDTORCH")
			{
				A_Wander();
				A_Recoil(-1);
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			tnt1 a 0 doomb_random_death;
		Loop;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,60,0,1);
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 A 0;
		Looping:
			BDT3 AAAABBBBCCCCDDDD 1 Bright light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );

				if(vel.z == 0)
					setstatelabel("FallDeath");
			}
		Loop;
			
		FallDeath:
			tnt1 BBBBBBBBBBBBBBBB 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 AAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 10), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 AAAA 0 A_SpawnProjectile("XDeath1", 10, 0, random (0, 360), 2, random (20, 150));
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 A 0 A_Explode(100, 128);
		Death:
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_Jump(256, "Death1", "Death2", "Death3");
		Death1:
			TNT1 A 0 A_PlaySound("BURNZOM");
			BRZ3 DDEEFF 3 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}

			BRZ3 GGFFGGFFGGFFGGFFGGFFGGFFGGFFGGFF 3 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				A_Wander();
			}

			BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BRZ3 H -1;
			Stop;
		Death2:
			TNT1 A 0 A_PlaySound("BURNZOM");
			BRZ3 DDEEFFGGFFGGFFGGFFGGFFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 3 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			BRZ3 IIIIIIIIIIIIIIIII 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BRZ3 I -1;
			Stop;
			
		Death3:
			TNT1 A 0 A_PlaySound("BURNZOM");
			BRZ3 DDEEFF 3 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			BRZ3 GGFFGGFFGGFFGGFF 3 Bright light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
		mini:
			TNT1 A 0 A_Playsound("BurnZom");
			ZMAB AABB 5	light("BIGREDTORCH")
			{
				A_Chase();
				doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
			tnt1 a 0 a_jumpif(random(0, 10) < 1, "death_fire");
		Loop;
			
		Death_fire:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BRZ3 H -1;
			Stop;
			
		XDEATH:
		DEATH.SSG:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 AA 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchMeatDeath", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("BurningFlyingMeatPiece", 64, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 a_spawnitemex ("CrueltyBonus5Health");
			Stop;
	}
}


CLASS XDeathZombieLeg : doomb_body_base
{ 
	Default {
		Radius 8;
		Height 8;
		Scale 1.1;
		Speed 8;
		Mass 1;
		gravity 0.5;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		wallbouncefactor 0.2;
		BounceCount 3;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		+EXPLODEONWATER;
		+SKYEXPLODE;
		-DONTSPLASH;
		seesound "bloood";
		deathsound "bloood";
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG1 ABCDEFGH 5 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			Loop;
		Death:
			LEG1 E 1 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			LEG1 E -1;
			stop;
	}
}

CLASS XDeathZombieLegKicked: XDeathZombieLeg { 
	Default {
		
		+ACTIVATEMCROSS;
		+ACTIVATEIMPACT;
	}
}



CLASS GibZombieBoot: TinyGib { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			LEG1 Y -1;
			stop;
	}
}




CLASS Gib_ZombieLeg2: LimbBase { 
	Default {
		
	}
	States
	{
		Spawn:
			LEG1 A 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
		Death.plasma:
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
			Stop;
		Death:    
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnProjectile ("GibZombieBoot", 0, 0, random (0, 180), 2, random (0, 180));
			LEG1 Z -1;
			stop;
			
		Death.Kick:
		Death.Punch:
			LEG1 AA 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathZombieLegKicked", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LEG1 ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			LEG1 A 5;
			LEG1 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Landz:
			LEG1 E 1 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			LEG1 E -1;
			stop;
			
	}
	
}




CLASS XDeathHalfZombieman : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			POSX F 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			POSX F 1 A_SpawnItem("Gib_HalfZombieman",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS Gib_HalfZombieMan: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			POSX F 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathZombiemanHead", 15, 0, random (0, 360), 2, random (0, 180));
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 6, 0, random (0, 360), 2, random (0, 90));
			Stop;
			
	}
	
}	   

CLASS XDeathHalfZombiemanNoArmNoHead : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			POSX GHIJKLMN 4;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
			TNT1 A 0 A_SpawnItem("Gib_HalfZombiemanNoArmNoHead",0,0,0,1);
			Stop;
	}
}

CLASS Gib_HalfZombieManNoArmNoHead: BigGibBase { 
	Default {
		
		Scale 1.3;
	}
	States
	{
		Spawn:
			POSX O -1;
			Stop ;
			
		Death:
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_Meat_Death_Small();
			Stop;
			
	}
}	 


CLASS XDeathHalfZombiemanDown : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.1;
		Speed 6;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			POSX D 12;
			Loop;
		Death:
			POSX E 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop   ;
	}
}




CLASS XDeathHalfZombieman2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 7;
		Mass 8;
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			PP2X F 12 A_SpawnProjectile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			PP2X G -1;
			Stop;
	}
}


CLASS XDeathZombieManHead: LimbBase { 
	Default {
		
		-CLIENTSIDEONLY;
		Radius 10;
		Scale 1.0;
	}
	States
	{
		Spawn:
		Spawn1:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			XHE2 AB 3;
			XHE2 CDEFGH 3;
			Loop;
		Death:
			XHE2 E 1;
			XHE2 E 1 A_SpawnItem("ZombieManHead",0,0,0,1);
			Stop;
	}
}


CLASS XDeathZombiemanHeadBeheaded : XDeathZombieManHead { 
	Default {
		
		Speed 5;
		Gravity 0.5;
	}
}


CLASS XDeathZombiemanHeadOnXDeath : XDeathZombieManHead { 
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_jump(96, "ExplodeOnAir");
			Goto Spawn1;
		ExplodeOnAir:
			TNT1 A 0;
			
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
			
			Stop;
	}
}

CLASS ZombiemanHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 99.0;
		damagefactor "Melee", 99.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Radius 10;
		
		Mass 60;
		Health 40;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
		Spawn1:
			XHE2 C 1;
			XHE2 C -1;
			Stop;
		Spawn2:
			XHE2 G 1;
			XHE2 G -1;
			Stop;
		Spawn3:
			XHE2 H 1;
			XHE2 H -1;
			Stop;
			
		Death.Trample:
		Death.Stomp:
		Death:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
			
			Stop;
		Crush:
			TNT1 AAAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 5;
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0;
			Stop;
		Death.Punch:
		Death.Kick:
			XHE2 EE 1 A_FaceTarget;
			TNT1 AAAA 0 A_SpawnItemEx("Blood", 0, 0, 10);
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 0 A_SpawnProjectile ("XDeathZombieManHeadKicked", 5, 0, random (170, 190), 2, random (20, 30));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE2 ABCDEFGH 2;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE2 ABCD 6;
			XDT5 I 0 A_SpawnItem("ZombiemanHead");
			Stop;
			
			
	}
	
}

CLASS XDeathZombieManHeadKicked: XDeathZombieManHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
	}
}

CLASS ZombieXDeath : doomb_body_base { 
	Default {
		
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		
		BounceFactor 0.5;
		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_FaceTarget;
			tnt1 a 0 A_Explode(3,600, 0, 0, 0, 0, 0, "none", "blood");
			
			TNT1 AAAAAAAAAAAAAAA 0 A_SpawnProjectile ("WallRedBlood", 40, 0, random (0, 360), 2, random (-15, 15));
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 0, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombiemanNoArmNoHead", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath2", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath3", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece2", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece1", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathZombieLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("GibZombieBoot", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathZombiemanHeadOnXDeath", 32, 0, random (0, 360), 2, random (0, 160));
			tnt1 a 0 doomb_spawn_bloodpool();
			
			TNT1 A 1;
			TNT1 A 2;
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
			Stop;
	}
}



CLASS DyingZombiemanLostTeeth : doomb_body_base
{ 
Default {
	
	Radius 12;
	Height 32+15;
	doomb_monster_base.head_starting_position 32;

	Speed 0;
	Health 40;
	-COUNTKILL;
	+GHOST;
	+THRUGHOST;
	+NOPAIN;
	+FRIENDLY;
}
States
{
	Spawn:
	SEE:
		TNT1 A 0;
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("Teeth", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("TeethNoBounce", 50, 0, random (0, 360), 2, random (0, 160));
		ZZD5 A 6 A_SpawnProjectile ("MuchBlood", 40, 0, random (0, 360), 2, random (0, 160));
	mini:
		ZZD5 CBCB 12 A_PlaySound("grunt/pain", 3);
		tnt1 a 0 doomb_random_death();
	loop;

	Death:
		ZZD5 D 6
		{
			A_NoBlocking();
			A_Scream();
			doomb_spawn_bloodpool();
		}
		TNT1 A 0 A_SpawnItem("DeadZombieManFacingFront");
	Stop;
		
	Death.Headshot:
		TNT1 A 0 A_SpawnItem("CrueltyBonus1Health");
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		ZMAD B 0 A_XScream;
		tnt1 a 0 A_Explode(3,200, damagetype:"blood");
		ZMAD C 0 A_NoBlocking;
		
		TNT1 A 0 A_Jump(32, "Deathchickenhead");
		ZMAD AAAAABBBBBBBBBBCCCCCDDDDEEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoHeadFront");
	stop;

	Death.Shotgun:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 {bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil (6);
		POS4 U 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel == (0, 0, 0) ), "TakeASit");
		POS4 U 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel == (0, 0, 0) ), "TakeASit");
		POS4 V 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel == (0, 0, 0) ), "TakeASit");
		POS4 W 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		POS4 X 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		POS4 Y 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
	stop;

	TakeASit:
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		POS4 U 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItemEx("DeadZombieman_Slumped", 10);
	Stop;
}

}

CLASS DyingZombiemanNoArm : doomb_body_base { 
	Default {
		
		Radius 16;
		Height 28+18;
		doomb_monster_base.head_starting_position 30;

		Health 50;
		PainSound "grunt/pain";
		PainChance 255;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Leg", 0.0;
		damagefactor "Kick", 6.0;
		Mass 500;
		+SHOOTABLE;
		+FLOORCLIP;
		+DONTSPLASH;
		MONSTER;
		+FRIENDLY;//
		-COUNTKILL;
		+GHOST;
		+THRUGHOST;
		-SOLID;
		
		+FLOORCLIP;
		+DONTSPLASH;
	}
	States
	{
		Death.Fatality:
		Death.punch:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("HasZmanShield", 1);
			TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
			Stop;
			
		Death.fire:
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("BurningZombie");
			Stop;
			
		Spawn:
			ZZD1 A 1 A_Chase;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_PlaySound ("BURNZOM");
			ZZD1 IIIIAAAAA 2 A_SpawnProjectile ("Brutal_LiquidBlood", 40, 0, 90, 2, random (0, 45));
			ZZD1 A 1 A_Chase;
			TNT1 A 0 A_FaceTarget;
			ZZD2 AAAAAAAA 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, 90, 2, random (0, 45));
		Suffer:
			ZZD2 EEEEEBBBBB 2 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, 90, 2, random (0, 45));
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Jump(32, "LastStand");
			tnt1 a 0 a_jumpif(random(0, 10) < 1, "death");
		loop;

		Death.Cut:
		Death.Cutless:
		Death:
			TNT1 A 0 A_FaceTarget;
			ZZD2 CCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, 90, 2, random (0, 45));
			TNT1 A 0 A_PlaySound ("grunt/death");
			TNT1 A 0 A_FaceTarget;
			ZZD3 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 A_SpawnProjectile ("Brutal_LiquidBlood", 1, 0, 90, 2, random (10, 45));
			TNT1 A 0 A_SpawnItem ("DeadZombieman_NoArmFront");
			Stop;
			
		Death.Headshot:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
			
			TNT1 A 0 A_XScream;
			TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 37, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
			ZZD3 GGGG 2 A_SpawnProjectile ("Brutal_LiquidBlood", 35, 0, random (0, 360), 2, random (0, 90));
			ZZD3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 1 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (0, 90));
			ZZD3 H -1 doomb_final_absolution(12, 12);
		Stop;
			
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		XBRN AA 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_burned_flesh;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		XBRN BB 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 A 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		XBRN CC 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
		TNT1 AAAAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
		TNT1 AAA 0 doomb_show_effect("PlasmaParticleX", (0, 0, 42), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(1.8, 2.2), 0) );
	Stop;
		
	Death.Kick:
	Death.Punch:
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_PlaySound ("grunt/death");
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_NoBlocking;
		ID11 EF 15;
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoArm");
		Stop;
		
	Death.Fatality:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 A 0 A_GiveToTarget("HasZmanShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		Stop;
		
		
	Xdeath:
	Death.punch:
	Death.Blast:
	Death.SSG:
	Death.Shotgun:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_PlaySound ("misc/xdeath4");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Bloodmist", 30, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 42, 0, random (170, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 42, 0, random (170, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 42, 0, random (170, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("ZombieXDeath", 2, 0, random (0, 360), 2, random (0, 160));
		Stop;
		
	LastStand:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_SpawnItem ("ZombiemanLastStand2");
		Stop;
}
}

CLASS FrozenZombieman : ACTOR { 
	Default {
	
	Health 60;
	Radius 16;
	Height 52;
	+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
	}
	States
	{
	Spawn:
		FZD1 A 200;
		FZD1 A 2;
		TNT1 A 0 A_PlaySound("ICEBRK1");
		FZD1 A 50;
		FZD1 B 2;
		FZD1 A 50;
		FZD1 B 2;
		FZD1 A 50;
		FZD1 B 2;
		FZD1 A 25;
		FZD1 B 2;
		FZD1 A 25;
		FZD1 B 2;
		FZD1 A 10;
		FZD1 B 2;
		FZD1 A 10;
		FZD1 B 2;
		FZD1 A 10;
		FZD1 BABABA 2;
	Death.Fire:
		TNT1 A 0 A_ChangeCountFlags(false, false);
		TNT1 A 0 A_PlaySound ("DSBOTTLE");
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_spawnItem("Zombieman");
		Stop;
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound ("DSBOTTLE");
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("MuchBlood", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem("Rifle");
		FZD1 C 300;
		FZD1 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
		Stop;
}
}


CLASS ZombieManDyingAfterFatality : doomb_body_base { 
	Default {
	
	Radius 16;
	Height 28;
	Health 50;
	PainSound "grunt/pain";
	PainChance 255;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "Leg", 0.0;
	damagefactor "Kick", 6.0;
	Mass 500;
	+SHOOTABLE;
	+FLOORCLIP;
	+DONTSPLASH;
	MONSTER;
	+FRIENDLY;//
	-COUNTKILL;
	+GHOST;
	+THRUGHOST;
	-SOLID;
	
	+FLOORCLIP;
	+DONTSPLASH-CANPASS;
	-SOLID;
	}
	States
	{
	
	Spawn:
		ZZD5 E 1;
		TNT1 A 0 A_PlaySound ("BURNZOM");
		TNT1 A 0 doomb_spawn_bloodpool();
	Suffer:
		ZZD5 EEEEEFFFFF 2 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, random(0, 360), 2, random (0, 45));
		tnt1 a 0 a_jump(220, "suffer");
		tnt1 a 0 a_die();
	stop;
		
	Death.cut:
	Death.saw:
		TNT1 A 0;
		TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 O 0 A_NoBlocking;
		
		TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieMan", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (0, 40));
		POSX AABCDE 9 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 doomb_spawn_bloodpool();
		POSX EEEEEEEEEEEEEEEEEEEEEE 1 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 90));
		POSX E -1;//doomb_final_absolution(12, 12);
		Stop;
		
		
	Death.fire:
		TNT1 AA 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("BurningZombie");
		Stop;
		
	Death.Headshot:
		TNT1 A 0 A_Jump(126, "headshot_1");
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		TNT1 A 0 A_XScream;
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 37, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		ZZD5 HHHHIIII 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (0, 90));
		PP2X H 0 A_SpawnItem ("DeadZombieman_NoHeadFront");
	Stop;
		
		
	headshot_1:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 A 0 A_SpawnProjectile ("XDeathZombiemanHead", 35, 0, random (0, 360), 2, random (30, 110));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		ZZD5 HHH 2 A_SpawnProjectile ("Brutal_LiquidBlood", 35, 0, random (0, 360), 2, random (0, 90));
		PP2X H 0 A_SpawnItem ("DeadZombieman_NoHeadFront");
		Stop;
	
	death:
	Death.Shotgun:
	Death.Kick:
	Death.Punch:
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Scream;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_NoBlocking;
		ID11 EF 15;
		TNT1 A 0 A_SpawnItem ("DeadZombieman1");
		Stop;
		
	Death.Fatality:
		stop;
		
}
}

CLASS ZombiemanLastStand2 : ZombiemanLastStand1 { 
	Default {
	
	Radius 16;
	Height 28;
	Health 50;
	PainSound "grunt/pain";
	PainChance 255;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "Leg", 0.0;
	damagefactor "Kick", 6.0;
	Mass 500;
	+SHOOTABLE;
	+FLOORCLIP;
	+DONTSPLASH;
	MONSTER;
	+FRIENDLY;
	-COUNTKILL;
	+GHOST;
	+THRUGHOST;
	-SOLID;
	
	+FLOORCLIP;
	+DONTSPLASH;
	MONSTER;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+LOOKALLAROUND;
	+GHOST;
	+THRUGHOST;
	-SOLID;
	
	}
States
	{
	Spawn:
		ZBLS C 1 A_Look;
	See:
		ZBLS CCCCC 1 A_Chase;
		Loop;
		
	Missile:
		ZBLS CCCC 10
		{
			A_FaceTarget();
			A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, 90, 2, random (0, 45));
		}
		TNT1 AA 0 A_SpawnProjectile("OrangeLensFlareAlt", 24, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		ZBLS D 6 BRIGHT A_SpawnProjectile("MonsterTracer", 28, 0, random(-12, 12), CMF_OFFSETPITCH, frandom(-5, 5) );
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 20,0);
		TNT1 A 0 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, 90, 2, random (0, 45));
		tnt1 a 0 doomb_random_death();
	loop;		
}
}



CLASS ZombiemanGotHisLegBlowed : doomb_body_base { 
	Default {
	
	Radius 16;
	Height 28 + 18;
	doomb_monster_base.head_starting_position 30;

	Health 50;
	PainSound "grunt/pain";
	PainChance 255;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "Leg", 0.0;
	damagefactor "Kick", 6.0;
	Mass 500;
	+SHOOTABLE;
	+FLOORCLIP;
	+DONTSPLASH;
	MONSTER;
	+FRIENDLY;//
	-COUNTKILL;
	+GHOST;
	+THRUGHOST;
	-SOLID;
	+FLOORCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound ("BURNZOM");
		POS7 AAAAABBCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_Jump(16, "GotoDeath");
	Suffer:
		TNT1 A 0;
		POS7 EEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		POS7 FFFFF 2 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_Jump(12, "LastStand");
		TNT1 A 0 A_Jump(24, "LeaveCrawling");
		tnt1 a 0 a_jumpif(random(0, 10) < 1, "death");
	Loop;
		
	Death.Cut:
	Death.Cutless:
	Death:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_PlaySound ("grunt/death");
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoLeg");
		Stop;
		
	LEaveCrawling:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_PlaySound ("grunt/death");
		TNT1 A 0 A_SpawnItem ("DyingZombieMan");
		Stop;
		
	LastStand:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_SpawnItem ("ZombiemanLastStand1");
		Stop;
		
	Death.Headshot:
			TNT1 A 0 A_Jump(126, "headshot_1");
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		POS7 GHI 6;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoLeg", 1);
	Stop;
		
	headshot_1:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieManHead", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		POS7 GHI 6;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoLeg", 1);
		Stop;
		
	Death.Fatality:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("HasZmanShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		Stop;
		
	Death.Shotgun:
	Death.Kick:
	Death.Punch:
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Scream;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_NoBlocking;
		ID11 KL 15;
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoLeg");
		Stop;
		
		
}
}

CLASS ZombiemanLastStand1: ZombiemanGotHisLegBlowed { 
	Default {
	
	Speed 0;
	MONSTER;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+LOOKALLAROUND;
	+GHOST;
	+THRUGHOST;
	-SOLID;
	BloodType "Brutal_Blood",  "SawBlood";
	}
States
	{
	Spawn:
		ZBLS A 1 A_Look;
	Loop;
		
	Missile:
		ZBLS AAAA 10 A_FaceTarget;
		
		TNT1 AA 0 A_SpawnProjectile("OrangeLensFlareAlt", 24, 10, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		ZBLS B 6 BRIGHT A_SpawnProjectile("MonsterTracer", 28, 0, random(-12, 12), CMF_OFFSETPITCH, frandom(-5, 5) );
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 20,0);
		tnt1 a 0 doomb_random_death();
	loop;
		
		
	Death.headshot:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Scream;
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 37, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_NoBlocking;
		POS7 GHI 6;
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoLeg", 1);
	Stop;
}
}	











CLASS ZombiemanSaciLol: ZombiemanGotHisLegBlowed { 
	Default {
	
	//MONSTER
	+GHOST;
	+THRUGHOST;
	-COUNTKILL;
	Speed 4;
	Height 48;
	}
	States
	{
	
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound ("BURNZOM");
		Goto Suffer;
		
	Suffer:
		ZL1E ABC 3;
		TNT1 A 0 doomb_blood_dying();
		ZL1E DDDD 1 A_Chase(null, null);
		tnt1 a 1 a_jump(200, "suffer");
		
		TNT1 A 0 A_PlaySound ("none");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("ZombiemanGotHisLegBlowed");
	Stop;

	Death.Headshot:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		ZMAD B 0 A_PlaySound("misc/xdeath");
		ZMAD C 0 A_NoBlocking;
		Goto FallHead;
	FallHead:
		ZL1E EFG 6;
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoLeg");
		Stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("grunt/death");
		ZL1E HI 6;
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoLeg");
		Stop;
}
}








CLASS ZombiemanTorso: CurbstompedMarine { 
	Default {
	
	Radius 12;
	Height 12;
	Scale 0.98;
	Mass 6000;
	damagefactor "Crush", 50.0;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	//+NORADIUSDMG
	+NOPAIN;
	+CORPSE;
	}
    States
    {
	Spawn:
		BLUD C 0 A_Recoil (3);
		BLUD C 0 ThrustThing (random(0,255),random(1,5));
		BLUD C 0 ThrustThingZ (0,random(0,50),random(0,1),0);
	Dead:
		GORX A -10;
		stop;
	Crush:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		POSC A 5;
		POSC A -1;
		Stop;
		
	Raise:
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("doomb_zombie_Man");
		Stop;
		
}
}

CLASS DeadZombieman1: CurbstompedMarine Replaces DeadZombieman { 
	Default {
	Radius 12;
	Height 12;
	+SHOOTABLE;
	-SOLID;
	+MOVEWITHSECTOR;
	+CORPSE;
	+FLOORCLIP;
	-DONTGIB;
	-THRUACTORS;
	+SLIDESONWALLS;
	damagefactor "Crusher", 50.0;
	Mass 6000;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.4;
	damagefactor "Crush", 10.0;
	damagefactor "BFGSplash", 100.0;
	DAMAGEFACTOR "Stomp", 10.0;
	damagefactor "Kick", 3.0;
	damagefactor "punch", 2.0;
	Painchance 256;
	Scale 0.98;
	}
States
    {
	Spawn:
		POSS L -1;
		Stop;
	Raise:
		
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("doomb_zombie_Man");
		Stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(256, "Death1", "Death2");
	Death1:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 A_SpawnProjectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnItem ("DeadZombieMan_NoArm");
		Stop;
	Death2:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieLeg", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 A_SpawnProjectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnItem ("DeadZombieMan_NoLeg");
		Stop;
}
}






CLASS DeadZombieMan_NoArm: ZombiemanTorso { 
	Default {
	
	Health 300;
	}
States
{
	Spawn:
		POS3 E -1;
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_Rip_Guts();
		TNT1 A 0 A_SpawnProjectile ("XDeathZombiemanHead", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 AA 0 A_SpawnProjectile ("XDeathZombieLeg", 6, 0, random (0, 360), 2, random (0, 90));
		PXSX O -1;//doomb_final_absolution(12, 12);
		Stop;
		
}

}		


CLASS DeadZombieMan_NoLeg: DeadZombieMan_NoArm { 
	Default {
	
	Health 300;
	}
States
{
	Spawn:
		POS7 D -1;
		Stop;
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("MuchBlood", 0, 10);
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieLeg", 15, 0, random (0, 360), 2, random (0, 180));
		POS8 D -1;//doomb_final_absolution(12, 12);
		Stop;
		
}

}		 
		 
CLASS DeadZombieMan_NoLegBoth: DeadZombieMan_NoArm { 
	Default {
	
	Health 300;
	}
States
{
	Spawn:
		POS8 D -1;//doomb_final_absolution(12, 12);
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieMan", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 doomb_Meat_Death_Small();
		Stop;
		
}

}		 



CLASS DeadZombieMan_NoHeadFront: DeadZombieMan_NoArm { 
	Default {
	
	Health 300;
	}
States
{
	
	Spawn:
		ZMAD E -1;
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 A_SpawnProjectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
		ZZD3 H -1;//doomb_final_absolution(12, 12);
		Stop;
		
}

}



CLASS VeryFuckedUpBrutalizedZombiemanLeg: CurbstompedMarine { 
	Default {
	
	Health 200;
	DamageFactor "Explosive_Impact", 10.0;
	}
States
{
	Spawn:
		tnt1 a 0 nodelay a_jump(128, 1);
		ID15 E -1 doomb_final_absolution(12, 12);

		ID13 G -1 doomb_final_absolution(12, 12);
	Stop;

	Death.Explosive_Impact:
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID13 ABCDEF 5;
		TNT1 A 0 A_SpawnItem ("VeryFuckedUpBrutalizedZombiemanLeg");
	Stop;
}

}

CLASS StompedZombieman: DeadZombieman_NoHeadfront { 
	Default {
	
	Health 300;
	}
States
{
	Pain:
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 180));
		01CB F -1;//doomb_final_absolution(12, 12);
		Stop;
}

}		  



CLASS DeadZombieMan_NoArmFront: DeadZombieMan_NoArm { 
	Default {
	
	}
	States
	{	
	Spawn:
		ZZD3 D -1;//doomb_final_absolution(12, 12);
		Stop ;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		ZZD3 H -1;//doomb_final_absolution(12, 12);
		Stop;
		
		
}
		}	
		
		

CLASS DeadZombieMan_StomachExploded: DeadZombieman_NoHeadFront { 
	Default {
	
	}
	States
	{	
	Spawn:
		ZXZ1 E -1;
		Stop ;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoHeadFront");
		Stop;
		
		
}
		}	
		

CLASS DeadZombieMan_Blasted: DeadZombieMan_NoHeadFront { 
	Default {
	
	}
	States
	{	
	Spawn:
		ZXZ2 E -1;
		Stop ;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 A_SpawnProjectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
		ZZD3 H -1;//doomb_final_absolution(12, 12);
		Stop;
		
		
}
		}			
		
CLASS DeadZombieManFacingFront: DeadZombieMan_NoArmFront { 
	Default {
	
	}
States
{
	Spawn:
		FPZ2 J -1;
		Stop  ;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(256, "Death1", "Death2");
	Death1:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 A_SpawnProjectile ("BloodMist", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 A 0 A_SpawnItem ("DeadZombieMan_NoArmFront");
		Stop;
	Death2:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		TNT1 A 0 A_SpawnItem ("DeadZombieMan_NoHeadFront");
		Stop;
		
}

}		
CLASS DeadZombieManFacingFrontMinorHead: DeadZombieManFacingFront { 
States
{
	Spawn:
		12DG N -1;
		Stop ;
	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		TNT1 A 0 A_SpawnItem ("DeadZombieMan_NoHeadFront");
		Stop;
}
}

CLASS zombie_fatalized_body: ZombiemanTorso { 
	Default {
	
	}
States
{
	Spawn:
		FPZ3 S -1;//doomb_final_absolution(12, 12);
		Stop  ;
}
		}		
		
CLASS DeadZombiemanShotguntotheFace1: DeadZombieman1 { 
	Default {
	
	}
States
{
	Spawn:
		POS4 J -1;
		Stop;
	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieMan", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 doomb_Meat_Death_Small();
		ZZD1 H -1;//doomb_final_absolution(12, 12);
		Stop;
		
}

}

CLASS DeadZombiemanShotguntotheFace2: DeadZombieman1 { 
	Default {
	
	}
States
{
	Spawn:
		POS4 T -1;
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieMan", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 doomb_Meat_Death_Small();
		ZZD1 H -1;//doomb_final_absolution(12, 12);
		Stop;
		
}

}

CLASS DeadZombiemanLikeInActionMovie: DeadZombieman1 { 
	Default {
	
	}
States
{
	Spawn:
		12DG I -1;
		Stop;
	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieMan", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 doomb_Meat_Death_Small();
		ZZD1 H -1;//doomb_final_absolution(12, 12);
		Stop;
}

}		

	
CLASS DyingZombieman : doomb_body_base
{ 
	Default {
	
	Radius 12;
	Height 16;
	Speed 9;
	Health 50;
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	damagefactor "Kick", 6.0;
	PainChance "Kick", 255;
	damagefactor "trample", 2.0;
	damagefactor "Death.KickDowned", 100.0;
	damagefactor "Death.KickDownedAny", 100.0;
	+SHOOTABLE;
	+FLOORCLIP;
	//+NOBLOCKMAP
	+LOOKALLAROUND;
	+FRIGHTENED;
	-SOLID;
	+DONTSPLASH;
	MONSTER;
	+FRIENDLY;//
	-COUNTKILL;
	+GHOST;
	+THRUGHOST;
	Mass 500;
	}
    States
    {
	
	Pain.Kick:
		TNT1 A 0 A_SpawnProjectile ("Teeth", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("Blood", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("TeethNoBounce", 30, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem("CrueltyBonus1health");
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_FaceTarget;
		ZMAK ABA 4;
		ZMAM A 20;
		Goto See;
		
		
	Death.Fatality:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("HasZmanShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		Stop;
		
	Death.Kick:
	Death.KickDowned:
	Death.punch:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_GiveToTarget("IsCurbstompingZombieman", 1);
		Stop;
		
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_GiveInventory("IsCrawling", 1);
		ZMAM A 1 A_Look;
		Loop;
	See:
		ZMAM ABAB 10 A_Chase;
		ZMAM A 9 A_Pain;
		TNT1 A 0 A_Jump(12, "LastStand");
		TNT1 A 0 A_SpawnItemEx("Brutal_FlyingBlood", 0, 0, 10, 0, 0);
		
			tnt1 a 0 a_jumpif(random(0, 10) < 1, "death");
		Loop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Pain;
		POSH Z -1;//doomb_final_absolution(12, 12);
		Stop;
		
	LastStand:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_SpawnItem ("ZombiemanLastStand1");
		Stop;
		
	Death.Fire:
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		
	mini_fire:
		TNT1 A 0 A_Playsound("BurnZom");
		ZMAB AABB 5 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				A_Chase();
				doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
			}
		TNT1 A 0 doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
		TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
			tnt1 a 0 a_jumpif(random(0, 10) < 1, "death_fire");
	Loop;
		
	death_fire:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 light("BIGREDTORCH")
		{
			A_Explode(3,30, damagetype:"fire");
			{Spawn("RedFlare", pos);}
			doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
		}
		TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		BRZ3 H -1;
		Stop;
		
	Death.Trample:
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 10, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 180));
		01CB F -1;//doomb_final_absolution(12, 12);
		Stop;
		Stop;
		
	Death.SSG:
	XDeath:
		TNT1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AAAAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
		TNT1 A 1 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		Stop;
		
	Death.Shotgun:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 20, 0, random (0, 360), 2, random (0, 160));
		
		ZMAD B 0 A_XScream;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		ZMAD C 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("DeadZombieman_Noheadfront");
		Stop;
		
	Crush:
	Death.Stomp:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AAAAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
		TNT1 A 1 A_NoBlocking;
		Stop;
}
}


//////////////////////////////////////////////////////////////////////////////////////////////////////
//zombieman minigun fatality
//////////////////////////////////////////////////////////////////////////////////////////////////////



CLASS BrutalizedZombieMan1 : doomb_body_base
{
Default
{
	Radius 16;
	Height 50;
	Health 300;
	bloodtype "DeadBlood";
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	
	+SHOOTABLE;
	+NORADIUSDMG;
	+FLOORCLIP;
	+DONTSPLASH;
	+FRIENDLY;//
	+GHOST;
	-SOLID;
	+THRUGHOST;
	+nopain
	Scale 1.0;
	Mass 500;
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(2);
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		ZZD1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1
		{
			if(health <= 200)
				setstatelabel("no_head");
		}
		TNT1 A 0 A_SpawnItem ("BrutalizedZombieManStop");
	Stop;

		
	//BrutalizedZombieMan2
	no_head:
		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Recoil(4);
		ZZD1 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1
		{
			if(health <= 100)
				setstatelabel("just_torso");
		}
		TNT1 A 0 A_SpawnItem ("BrutalizedZombieManStop2");
	Stop;

	just_torso:
		ZZD1 C 35;//just die
		ZZD3 H -1 doomb_final_absolution(12, 12);
	Stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(2);
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("Brutal_LiquidBlood", 44, 0, random (0, 360), 2, random (0, 50));
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		ZZD1 EFG 6;
		ZZD1 H -1 doomb_final_absolution(12, 12);
	Stop;



	Death.SSG:
	XDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("ZombieXDeath", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;

	Death.Fatality:
	Death.punch:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("HasZManShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	Stop;
}

}

CLASS BrutalizedZombieManStop: CurbstompedMarine { 
    States
    {
	Spawn:
		ZZD2 ABCD 5 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
		ZZD3 D 0;
		TNT1 A 0 A_SpawnItem("DeadZombieMan_NoArmFront");
		Stop   ;
}

}

CLASS BrutalizedZombieManStop2: CurbstompedMarine { 
    States
    {
	Spawn:
		ZZD4 AB 6 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
		ZZD3 H -1 doomb_final_absolution(12, 12);
		Stop;
}

}


CLASS BrutalizedZombieManLeg: BrutalizedZombieMan1 { 
	States
	{
	Spawn:
		POS7 ABCD 5;
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoLeg");
		Stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(4);
		
		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		//TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160))
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID13 ABCDEF 5;
		TNT1 A 0 A_SpawnItem ("VeryFuckedUpBrutalizedZombiemanLeg");
		Stop;
		
}

}

		

CLASS DeadZombieman_Slumped: ZombiemanTorso { 
	Default {
	
	+NOPAIN;
	Health 200;
	Height 22+15;
	doomb_monster_base.head_starting_position 22;
	Radius 6;
	}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(6);
		BR92 A 6;
		TNT1 A 0 A_JumpIf(vel.x == 0 && vel.y ==0, "LayDown");
		BR92 A 16;
	LayDown:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
	Stop;
	
	XDeath:
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
		Stop;
		
	Death.Headshot:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		TNT1 A 0 A_SpawnItem("DeadZombieman_Slumped_NoHead");
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 40, 0, random (0, 360), 2, random (30, 90));
		
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		POSX E -1;//doomb_final_absolution(12, 12);
		Stop;
		
}

}		
		
CLASS DeadZombieman_Slumped_NoHead: ZombiemanTorso { 
	Default {
	
	+NOPAIN;
	Height 22;
	}
States
{
	Spawn:
		BR92 B -1;
		stop;
	XDeath:
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("ZombieXDeath");
		Stop;
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 40, 0, random (0, 360), 2, random (30, 90));
		POSX E -1 doomb_final_absolution(12, 12);
	Stop;
}

}

