CLASS BurningZombie : doomb_body_base { 
	Default {
		
		Radius 12;
		Height 56;
		Speed 5;
		Scale 0.85;
		Health 100;
		GibHealth 25;
		damagefactor "Fire", 0.0;
		damagefactor "Explosive_Impact", 10.0;
		MONSTER;
		-COUNTKILL;
		+NOICEDEATH;
		+FRIENDLY;
		+FLOORCLIP;
		+SHOOTABLE;
		+NOBLOCKMONST;
		+DONTSPLASH;
		
		Gravity 0.7;
		
		Obituary "%o was near someone in flames.";
		MaxDropOffHeight 6000;
		
		Mass 999999;
	}
	States
	{
		Spawn:
			tnt1 B 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 A_PlaySound("BURNZOM");
		Suffer:
			BDT1 AAABBBCCCDDD 1 Bright light("BIGREDTORCH")
			{
				A_Wander();
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
			}

			TNT1 A 0 doomb_random_death();
		Loop;
			
		Death.Explosive_Impact:
			TNT1 A 0 ThrustThingZ(0,60,0,1);
			TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
			TNT1 A 0;
		Looping:
			BDT3 AAAABBBBCCCCDDDD 1 Bright light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				if(vel.z == 0)
					setstatelabel("falldeath");
			}
			Loop;
			
		FallDeath:
			TNT1 AAAAAAAAAA 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 AAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 10), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 A 0 A_Explode(100, 128);
		Death:
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_Jump(128, "Death2");
			BDT1 EEFFGGHHiijjkkLLmm 3 Bright light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			NJEX AAAAAAAAAAAAAAAAAA 10 Bright doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			NJEX A -1;
		Stop;
		
		Death2:
			BDT1 EEFFGGHHiijjkkLLmmBBBBBBBBBBBBBBBBBB 3 Bright light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			NJEX BBBBBBBBBBBBBBBBBB 10 Bright doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			NJEX B -1;
		Stop;

		XDEATH:
		DEATH.SSG:
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 AA 0 doomb_severed_limb("XDeathBurnedArm", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_severed_limb("XDeathBurnedLeg", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_severed_limb("XDeathBurnedSkull", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_severed_limb("MeatDeath", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_severed_limb("BurningFlyingMeatPiece", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
		Stop;
	}
}




CLASS BurningZombieMan : doomb_body_base { 
	Default {
		
		Radius 12;
		Height 56;
		Speed 3;
		Health 30;
		GibHealth 25;
		damagefactor "Fire", 0.0;
		damagefactor "Ice", 0.0;
		damagefactor "Explosive_Impact", 10.0;
		MONSTER;
		-COUNTKILL;
		+FRIENDLY;
		+FLOORCLIP;
		+SHOOTABLE;
		+NOBLOCKMONST;
		
		Gravity 0.7;
		
		Obituary "%o was near someone in flames.";
		MaxDropOffHeight 6000;
		
		Mass 999999;
	}
	States
	{
		Spawn:
			tnt1 B 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 A_PlaySound("BURNZOM");
			Goto Suffer;
		Suffer:
			BRZ3 AAABBBCCCBBB 1 BRIGHT light("BIGREDTORCH")
			{
				A_Wander();
				A_Recoil(-1);
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			tnt1 a 0 doomb_random_death;
		Loop;
			
		Death.Explosive_Impact:
			TNT1 A 0 ThrustThingZ(0,60,0,1);
			TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
			TNT1 A 0;
		Looping:
			BDT3 AAAABBBBCCCCDDDD 1 Bright light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );

				if(vel.z == 0)
					setstatelabel("FallDeath");
			}
		Loop;
			
		FallDeath:
			tnt1 BBBBBBBBBBBBBBBB 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 AAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 10), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 A 0 A_Explode(100, 128);
		Death:
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_Jump(256, "Death1", "Death2", "Death3");
		Death1:
			TNT1 A 0 A_PlaySound("BURNZOM");
			BRZ3 DDEEFFGGFFGGFFGGFFGGFFGGFFGGFFGGFFGGFFHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}

			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BRZ3 H -1;
		Stop;

		Death2:
			TNT1 A 0 A_PlaySound("BURNZOM");
			BRZ3 DDEEFFGGFFGGFFGGFFGGFFIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 3 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			BRZ3 IIIIIIIIIIIIIIIII 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BRZ3 I -1;
			Stop;
			
		Death3:
			TNT1 A 0 A_PlaySound("BURNZOM");
			BRZ3 DDEEFFGGFFGGFFGGFFGGFF 3 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
		mini:
			TNT1 A 0 A_Playsound("BurnZom");
			ZMAB AABB 5	light("BIGREDTORCH")
			{
				A_Chase();
				doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			tnt1 a 0 a_jumpif(random(0, 10) < 1, "death_fire");
		Loop;

		Death_fire:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			BRZ3 H -1;
			Stop;
			
		XDEATH:
		DEATH.SSG:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_PlaySound("misc/xdeath");
			TNT1 AA 0 doomb_severed_limb("XDeathBurnedArm", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_severed_limb("XDeathBurnedLeg", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_severed_limb("XDeathBurnedSkull", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_severed_limb("MeatDeath", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_severed_limb("BurningFlyingMeatPiece", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
		Stop;
	}
}


CLASS XDeathZombieLeg : doomb_body_base
{ 
	Default
	{
		Radius 8;
		Height 8;
		Scale 1.1;
		Speed 8;
		Mass 1;
		gravity 0.5;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		wallbouncefactor 0.2;
		BounceCount 3;

		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MISSILE;
		+EXPLODEONWATER;
		+SKYEXPLODE;
		-DONTSPLASH;
		seesound "bloood";
		deathsound "bloood";
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			LEG1 ABCDEFGH 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), doomb_random_velocity(5) );
		Loop;
		
		Death:
			LEG1 E 1 doomb_spawn_bloodpool(BPS_SMALL);
			LEG1 E -1;
		stop;
	}
}

CLASS XDeathZombieLegKicked: XDeathZombieLeg { 
	Default {
		
		+ACTIVATEMCROSS;
		+ACTIVATEIMPACT;
	}
}



CLASS GibZombieBoot: TinyGib
{
States
{
	Spawn:
		LEG1 Y -1;
	stop;
}

}




CLASS Gib_ZombieLeg2: LimbBase
{
States
{
		Spawn:
			LEG1 A 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;

		Death.plasma:
			TNT1 A 0 doomb_severed_limb("XDeathBurnedLeg", (0, 0, 32), doomb_random_velocity(5) );
		Stop;

		Death:    
			TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("GibZombieBoot", vel_dir:doomb_random_velocity(5) );
			LEG1 Z -1;
		stop;

		Death.Kick:
		Death.Punch:
			LEG1 AA 1 A_FaceTarget;
			TNT1 A 0 doomb_severed_limb("XDeathZombieLegKicked");
		Stop;

		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LEG1 ABCDEFGH 2;
		Goto Spawn;

		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			LEG1 A 5;
			LEG1 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Landz:
			LEG1 E 1 doomb_spawn_bloodpool(BPS_SMALL);
			LEG1 E -1;
		stop;
	}
	
}




CLASS XDeathHalfZombieman : doomb_body_base { 
	Default
	{
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			POSX F 12;
		Loop;

		Death:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			POSX F 1 doomb_severed_limb("Gib_HalfZombieman", limb_ignore_cvar: true);
		Stop;
	}
}

CLASS Gib_HalfZombieMan: BigGibBase
{
	States
	{
		Spawn:
			POSX F 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;

		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_severed_limb("XDeathZombiemanHead", (0, 0, 15), doomb_random_velocity(5) );
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 AA 0 doomb_severed_limb("XDeathArm1");
		Stop;
	}
	
}	   

CLASS XDeathHalfZombiemanNoArmNoHead : doomb_body_base
{
	Default
	{
		Radius 8;
		Height 8;
		
		Speed 10;
		Gravity 0.7;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.01;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay doomb_spawn_bloodpool(BPS_SMALL);
			POSX GHIJKLMN 4;
		Loop;
		
		Death:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			TNT1 A 0 doomb_severed_limb("Gib_HalfZombiemanNoArmNoHead");
		Stop;
	}
}

CLASS Gib_HalfZombieManNoArmNoHead: BigGibBase
{
	States
	{
		Spawn:
			POSX O -1;
		Stop;
			
		Death:
			TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 A 0 doomb_Meat_Death_Small();
		Stop;
	}
}	 


CLASS XDeathHalfZombiemanDown : doomb_body_base { 
	Default
	{
		Radius 8;
		Height 8;
		Scale 1.1;
		Speed 6;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			POSX D 12;
		Loop;

		Death:
			POSX E 1900 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;
	}
}




CLASS XDeathHalfZombieman2 : doomb_body_base
{
Default
{
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
}

States
{
	Spawn:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		PP2X F 12 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
	Loop;

	Death:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		PP2X G -1;
	Stop;
}

}


CLASS XDeathZombieManHead: LimbBase { 
	Default
	{
		-CLIENTSIDEONLY;
		Radius 10;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			XHE2 ABCDEFGH 3;
		Loop;

		Death:
			XHE2 E 1 doomb_severed_limb("ZombieManHead");
		Stop;
	}
}


CLASS XDeathZombiemanHeadBeheaded : XDeathZombieManHead
{
	Default
	{
		Speed 5;
		Gravity 0.5;
	}
}


CLASS XDeathZombiemanHeadOnXDeath : XDeathZombieManHead { 
	States
	{
		Spawn:
			TNT1 A 0 A_jump(96, "ExplodeOnAir");
		ExplodeOnAir:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
			TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );

			TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );

			TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		Stop;
	}
}

CLASS ZombiemanHead: LimbBase
{
	Default {
		damagefactor "Kick", 99.0;
		damagefactor "Melee", 99.0;
		-CLIENTSIDEONLY;
		+SHOOTABLE;
		+THRUACTORS;
		damagefactor "Crush", 50.0;
		Radius 10;
		
		Mass 60;
		Health 40;
		Scale 1.1;
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
			XHE2 C -1;
		Stop;

		Spawn2:
			XHE2 G -1;
		Stop;

		Spawn3:
			XHE2 H -1;
		Stop;
			
		Death.Trample:
		Death.Stomp:
		Death:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
			TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );

			TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );			
		Stop;

		Crush:
			TNT1 AAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), doomb_random_velocity(5) );
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 9009;
		Stop;

		Death.plasma:
			TNT1 A 0 doomb_severed_limb ("XDeathBurnedSkull", (0, 0, 32), doomb_random_velocity(5) );
			EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		Stop;

		Death.Punch:
		Death.Kick:
			XHE2 EE 1 A_FaceTarget;
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 0 doomb_severed_limb("XDeathZombieManHeadKicked");
		Stop;
			
		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE2 ABCDEFGH 2;
		Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			XHE2 ABCD 6;
			tnt1 a 0 doomb_severed_limb("ZombiemanHead");
		Stop;
	}
	
}

CLASS XDeathZombieManHeadKicked: XDeathZombieManHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
	}
}




CLASS DyingZombiemanLostTeeth : doomb_body_base
{ 
Default {
	
	Radius 12;
	Height 45;
	doomb_monster_base.head_starting_position 32;

	Speed 0;
	Health 40;
	-COUNTKILL;
	+GHOST;
	+THRUGHOST;
	+NOPAIN;
	+FRIENDLY;
}
States
{
	Spawn:
	SEE:
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		ZZD5 A 6 doomb_much_blood(48);
	mini:
		ZZD5 CBCB 12 A_PlaySound("grunt/pain", 3);
		tnt1 a 0 doomb_random_death();
	loop;

	Death:
		ZZD5 D 6
		{
			A_NoBlocking();
			A_Scream();
			doomb_spawn_bloodpool();
		}
		TNT1 A 0 doomb_severed_limb("DeadZombieManFacingFront");
	Stop;
		
	Death.Headshot:
		TNT1 A 0 A_Givetotarget("CrueltyBonus1Health");
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		ZMAD B 0 A_XScream;
		tnt1 a 0 A_Explode(3,200, damagetype:"blood");
		ZMAD C 0 A_NoBlocking;
		
		TNT1 A 0 A_Jump(32, "Deathchickenhead");
		ZMAD AAAAABBBBBBBBBBCCCCCDDDDEEEEEEEEEEEEEEEE 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoHeadFront");
	stop;

	Death.Shotgun:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 {bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil (6);
		POS4 U 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 A_JumpIf((vel == (0, 0, 0) ), "TakeASit");
		POS4 U 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 A_JumpIf((vel == (0, 0, 0) ), "TakeASit");
		POS4 V 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 A_JumpIf((vel == (0, 0, 0) ), "TakeASit");
		POS4 W 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		POS4 X 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		POS4 Y 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadZombieman1");
	stop;

	TakeASit:
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		POS4 U 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadZombieman_Slumped");
	Stop;
}

}

CLASS DyingZombiemanNoArm : doomb_body_base { 
	Default {
		
		Radius 16;
		Height 45;
		doomb_monster_base.head_starting_position 30;

		Health 50;
		PainSound "grunt/pain";
		PainChance 255;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Leg", 0.0;
		damagefactor "Kick", 6.0;
		Mass 500;
		+SHOOTABLE;
		+FLOORCLIP;
		+DONTSPLASH;
		MONSTER;
		+FRIENDLY;//
		-COUNTKILL;
		+GHOST;
		+THRUGHOST;
		-SOLID;
		
		+FLOORCLIP;
		+DONTSPLASH;
	}
	States
	{
		Spawn:
			ZZD1 A 1 A_Chase;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_PlaySound ("BURNZOM");
			ZZD1 IIIIAAAAA 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			ZZD1 A 1 A_Chase;
			TNT1 A 0 A_FaceTarget;
			ZZD2 AAAAAAAA 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		Suffer:
			ZZD2 EEEEEBBBBB 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Jump(32, "LastStand");
			tnt1 a 0 doomb_random_death();
		loop;

		Death.Fatality:
		Death.punch:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("HasZmanShield", 1);
			TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
			Stop;
			
		Death.fire:
			TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_severed_limb("BurningZombie");
		Stop;
			

		Death.Cut:
		Death.Cutless:
		Death:
			TNT1 A 0 A_FaceTarget;
			ZZD2 CCCC 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 A 0 A_PlaySound ("grunt/death");
			TNT1 A 0 A_FaceTarget;
			ZZD3 DDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("DeadZombieman_NoArmFront");
		Stop;
			
		Death.Headshot:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
			TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
			TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 A_XScream;
			TNT1 AAAAAAAAAAA 0 doomb_for_khorne("Brutal_Blood", (0, 0, 37), doomb_random_velocity(5) );
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
			ZZD3 GGGGHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			ZZD3 H -1 doomb_final_absolution(12, 12);
		Stop;
			
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		XBRN AABBCCDDEE 2 BRIGHT
		{
			{doomb_flare_base.doomb_attach_flare(self, "BlueFlare", (0, 0, 43) );}
			doomb_for_khorne("Brutal_Blood", (0, 0, 37), doomb_random_velocity(5) );
			doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
			doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
			doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
			doomb_show_effect("PlasmaParticleX", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ) );
		}
		TNT1 AAAAAAAAAAA 0 doomb_for_khorne("Brutal_Blood", (0, 0, 37), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_severed_limb("XDeathBurnedArm", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_severed_limb("XDeathBurnedLeg", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_severed_limb("XDeathBurnedSkull", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_severed_limb("MeatDeath", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_severed_limb("BurningFlyingMeatPiece", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_burned_flesh;
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Armor");
	Stop;
		
	Death.Kick:
	Death.Punch:
		TNT1 A 0 doomb_much_blood(35);
		TNT1 A 0 A_PlaySound ("grunt/death");
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_NoBlocking;
		ID11 EF 15;
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoArm");
	Stop;
		
	Death.Fatality:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("HasZmanShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	Stop;
		
		
	Xdeath:
	Death.punch:
	Death.Blast:
	Death.SSG:
	Death.Shotgun:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_PlaySound ("misc/xdeath4");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 30) );
		TNT1 A 0 doomb_severed_limb("ZombieXDeath");
		Stop;
		
	LastStand:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Pain;
		TNT1 A 0 doomb_severed_limb("ZombiemanLastStand2");
	Stop;
}
}



CLASS ZombieManDyingAfterFatality : doomb_body_base { 
	Default {
	
	Radius 16;
	Height 28;
	Health 50;
	PainSound "grunt/pain";
	PainChance 255;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "Leg", 0.0;
	damagefactor "Kick", 6.0;
	Mass 500;
	+SHOOTABLE;
	+FLOORCLIP;
	+DONTSPLASH;
	MONSTER;
	+FRIENDLY;//
	-COUNTKILL;
	+GHOST;
	+THRUGHOST;
	-SOLID;
	
	+FLOORCLIP;
	+DONTSPLASH-CANPASS;
	-SOLID;
	}
	States
	{
	
	Spawn:
		ZZD5 E 1;
		TNT1 A 0 A_PlaySound ("BURNZOM");
		TNT1 A 0 doomb_spawn_bloodpool();
	Suffer:
		ZZD5 EEEEEFFFFF 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		tnt1 a 0 a_jump(220, "suffer");
		tnt1 a 0 a_die();
	stop;
		
	Death.cut:
	Death.saw:
		TNT1 A 0 doomb_much_blood(35);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
		TNT1 O 0 A_NoBlocking;
		
		TNT1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieMan", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		POSX AABCDE 9 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		POSX EEEEEEEEEEEEEEEEEEEEEE 1 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		POSX E -1;//doomb_final_absolution(12, 12);
		Stop;
		
		
	Death.fire:
		TNT1 AA 0 A_Givetotarget("CrueltyBonus5Health");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("BurningZombie");
	Stop;
		
	Death.Headshot:
		TNT1 A 0 A_Jump(126, "headshot_1");
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_XScream;
		TNT1 AAAAAAAAAAA 0 doomb_for_khorne("Brutal_Blood", (0, 0, 37), doomb_random_velocity(5) );
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
		ZZD5 HHHHIIII 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		PP2X H 0 doomb_severed_limb("DeadZombieman_NoHeadFront");
	Stop;
		
		
	headshot_1:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 A 0 doomb_severed_limb("XDeathZombiemanHead", (0, 0, 35), doomb_random_velocity(5) );
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
		ZZD5 HHH 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		PP2X H 0 doomb_severed_limb("DeadZombieman_NoHeadFront");
	Stop;
	
	death:
	Death.Shotgun:
	Death.Kick:
	Death.Punch:
		TNT1 A 0 doomb_much_blood(35);
		TNT1 A 0 A_Scream;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_NoBlocking;
		ID11 EF 15;
		TNT1 A 0 doomb_severed_limb("DeadZombieman1");
	Stop;
		
	Death.Fatality:
	stop;
}

}

CLASS ZombiemanLastStand2 : ZombiemanLastStand1 { 
	Default {
	
	Radius 16;
	Height 28;
	Health 50;
	PainSound "grunt/pain";
	PainChance 255;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "Leg", 0.0;
	damagefactor "Kick", 6.0;
	Mass 500;
	+SHOOTABLE;
	+FLOORCLIP;
	+DONTSPLASH;
	MONSTER;
	+FRIENDLY;
	-COUNTKILL;
	+GHOST;
	+THRUGHOST;
	-SOLID;
	
	+FLOORCLIP;
	+DONTSPLASH;
	MONSTER;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+LOOKALLAROUND;
	+GHOST;
	+THRUGHOST;
	-SOLID;
	
	}
States
	{
	Spawn:
		ZBLS C 1 A_Look;
	See:
		ZBLS CCCCC 1 A_Chase;
		Loop;
		
	Missile:
		ZBLS CCCC 10
		{
			A_FaceTarget();
			doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		}
			TNT1 A 0 A_PlaySOund("DISTFRRIFLE");
		TNT1 AA 0 {doomb_flare_base.doomb_attach_flare(self, "lens_flare_orange", (0, 0, 24) );}
		TNT1 A 0 A_PlaySound("weapons/rifle");
		ZBLS D 6 BRIGHT A_SpawnProjectile("MonsterTracer", 28, 0, random(-12, 12), CMF_OFFSETPITCH, frandom(-5, 5) );
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 20,0);
		TNT1 A 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		tnt1 a 0 doomb_random_death();
	loop;		
}

}



CLASS ZombiemanGotHisLegBlowed : doomb_body_base { 
	Default {
	
	Radius 16;
	Height 45;
	doomb_monster_base.head_starting_position 30;

	Health 50;
	PainSound "grunt/pain";
	PainChance 255;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "Leg", 0.0;
	damagefactor "Kick", 6.0;
	Mass 500;
	+SHOOTABLE;
	+FLOORCLIP;
	+DONTSPLASH;
	MONSTER;
	+FRIENDLY;//
	-COUNTKILL;
	+GHOST;
	+THRUGHOST;
	-SOLID;
	+FLOORCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound ("BURNZOM");
		POS7 AAAAABBCC 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_Jump(16, "GotoDeath");
	Suffer:
		TNT1 A 0;
		POS7 EEEEEFFFFF 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 A_Jump(12, "LastStand");
		TNT1 A 0 A_Jump(24, "LeaveCrawling");
		tnt1 a 0 a_jumpif(random(0, 10) < 1, "death");
	Loop;
		
	Death.Cut:
	Death.Cutless:
	Death:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_PlaySound ("grunt/death");
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoLeg");
	Stop;
		
	LEaveCrawling:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_PlaySound ("grunt/death");
		TNT1 A 0 doomb_severed_limb("DyingZombieMan");
	Stop;
		
	LastStand:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Pain;
		TNT1 A 0 doomb_severed_limb("ZombiemanLastStand1");
		Stop;
		
	Death.Headshot:
		TNT1 A 0 A_Jump(126, "headshot_1");
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		POS7 GHI 6;
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoLeg");
	Stop;
		
	headshot_1:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathZombieManHead", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		POS7 GHI 6;
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoLeg");
	Stop;
		
	Death.Fatality:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("HasZmanShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
		Stop;
		
	Death.Shotgun:
	Death.Kick:
	Death.Punch:
		TNT1 A 0 doomb_much_blood(35);
		TNT1 A 0 A_Scream;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_NoBlocking;
		ID11 KL 15;
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoLeg");
	Stop;
}

}

CLASS ZombiemanLastStand1: ZombiemanGotHisLegBlowed
{
Default
{
	Speed 0;
	MONSTER;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+LOOKALLAROUND;
	+GHOST;
	+THRUGHOST;
	-SOLID;
	BloodType "Brutal_Blood",  "SawBlood";
}

States
{
	Spawn:
		ZBLS A 1 A_Look;
	Loop;
		
	Missile:
		ZBLS AAAA 10 A_FaceTarget;
		
		TNT1 A 0 A_PlaySOund("DISTFRRIFLE");
		TNT1 AA 0 {doomb_flare_base.doomb_attach_flare(self, "lens_flare_orange", (0, 0, 24) );}
		TNT1 A 0 A_PlaySound("weapons/rifle");
		ZBLS B 6 BRIGHT A_SpawnProjectile("MonsterTracer", 28, 0, random(-12, 12), CMF_OFFSETPITCH, frandom(-5, 5) );
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 20,0);
		tnt1 a 0 doomb_random_death();
	loop;
		
		
	Death.headshot:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AA 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 A 0 A_Scream;
		TNT1 AAAA 0 doomb_for_khorne("Brutal_Blood", (0, 0, 37), doomb_random_velocity(5) );
		TNT1 A 0 A_NoBlocking;
		POS7 GHI 6;
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoLeg");
	Stop;
}

}	











CLASS ZombiemanSaciLol: ZombiemanGotHisLegBlowed { 
Default
{
	+GHOST;
	+THRUGHOST;
	-COUNTKILL;
	Speed 4;
	Height 48;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound ("BURNZOM");
	Suffer:
		ZL1E ABC 3;
		TNT1 A 0 doomb_blood_dying();
		ZL1E DDDD 1 A_Chase(null, null);
		tnt1 a 1 a_jump(200, "suffer");
		
		TNT1 A 0 A_PlaySound ("none");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_show_effect("ZombiemanGotHisLegBlowed");
	Stop;

	Death.Headshot:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		ZMAD B 0 A_PlaySound("misc/xdeath");
		ZMAD C 0 A_NoBlocking;
	FallHead:
		ZL1E EFG 6;
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoLeg");
	Stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("grunt/death");
		ZL1E HI 6;
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoLeg");
	Stop;
}

}








CLASS ZombiemanTorso: CurbstompedMarine { 
Default
{
	Radius 12;
	Height 12;
	Scale 0.98;
	Mass 6000;
	damagefactor "Crush", 50.0;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	//+NORADIUSDMG
	+NOPAIN;
	+CORPSE;
}

States
{
	Spawn:
		tnt1 a 0 A_Recoil (3);
		tnt1 a 0 ThrustThing (random(0,255),random(1,5));
		tnt1 a 0 ThrustThingZ (0,random(0,50),random(0,1),0);
	Dead:
		GORX A -1;
	stop;

	Crush:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), doomb_random_velocity(5) );
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		POSC A -1;
	Stop;
		
	Raise:
		TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 spawn("doomb_zombie_Man", pos);
	Stop;
}

}

CLASS DeadZombieman1: CurbstompedMarine
{
Default
{
	Radius 12;
	Height 12;
	+SHOOTABLE;
	-SOLID;
	+MOVEWITHSECTOR;
	+CORPSE;
	+FLOORCLIP;
	-DONTGIB;
	-THRUACTORS;
	+SLIDESONWALLS;
	damagefactor "Crusher", 50.0;
	Mass 6000;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.4;
	damagefactor "Crush", 10.0;
	damagefactor "BFGSplash", 100.0;
	DAMAGEFACTOR "Stomp", 10.0;
	damagefactor "Kick", 3.0;
	damagefactor "punch", 2.0;
	Painchance 256;
	Scale 0.98;
}

States
{
	Spawn:
		POSS L -1;
	Stop;

	Raise:
		TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("doomb_zombie_Man");
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 a 0
		{
			doomb_for_khorne("blood_impact_splash", (0, 0, 15) );
			doomb_for_khorne("blood_impact_splash", (0, 0, 15) );
			doomb_for_khorne("blood_impact_splash", (0, 0, 15) );
			doomb_for_khorne("blood_impact_splash", (0, 0, 15) );

			switch(random(0, 1))
			{
				case 0:
				default:
					doomb_severed_limb("XDeathArm1", (0, 0, 15), doomb_random_velocity(5) );
					doomb_severed_limb("DeadZombieMan_NoArm");
				break;

				case 1:
					doomb_severed_limb("XDeathZombieLeg", (0, 0, 15), doomb_random_velocity(5) );
					doomb_severed_limb("DeadZombieMan_NoLeg");
				break;
			}
		}
	Stop;
}
}






CLASS DeadZombieMan_NoArm: ZombiemanTorso
{
States
{
	Spawn:
		POS3 E -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_Rip_Guts();
		TNT1 A 0 doomb_severed_limb("XDeathZombiemanHead", (0, 0, 15), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathZombieLeg", (0, 0, 15), doomb_random_velocity(5) );
		TNT1 A 0 doomb_Meat_Death_Small();
		PXSX O -1;//doomb_final_absolution(12, 12);
	Stop;
}

}		


CLASS DeadZombieMan_NoLeg: DeadZombieMan_NoArm
{
States
{
	Spawn:
		POS7 D -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_much_blood(10);
		TNT1 A 0 doomb_severed_limb("XDeathZombieLeg", (0, 0, 15), doomb_random_velocity(5) );
		POS8 D -1;//doomb_final_absolution(12, 12);
	Stop;
}

}		 
		 
CLASS DeadZombieMan_NoLegBoth: DeadZombieMan_NoArm
{
States
{
	Spawn:
		POS8 D -1;//doomb_final_absolution(12, 12);
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieMan", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 A 0 doomb_Meat_Death_Small();
	Stop;
		
}

}		 



CLASS DeadZombieMan_NoHeadFront: DeadZombieMan_NoArm
{
States
{
	
	Spawn:
		ZMAD E -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 15) );
		ZZD3 H -1;//doomb_final_absolution(12, 12);
	Stop;
		
}

}



CLASS VeryFuckedUpBrutalizedZombiemanLeg: CurbstompedMarine
{
States
{
	Spawn:
		tnt1 a 0 nodelay a_jump(128, 1);
		ID15 E -1 doomb_final_absolution(12, 12);

		ID13 G -1 doomb_final_absolution(12, 12);
	Stop;

	Death.Explosive_Impact:
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID13 ABCDEF 5;
		TNT1 A 0 doomb_severed_limb("VeryFuckedUpBrutalizedZombiemanLeg");
	Stop;
}

}




CLASS DeadZombieMan_NoArmFront: DeadZombieMan_NoArm { 
	States
	{	
	Spawn:
		ZZD3 D -1;//doomb_final_absolution(12, 12);
		Stop ;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		ZZD3 H -1;//doomb_final_absolution(12, 12);
	Stop;
}

}	
		
		

CLASS DeadZombieMan_StomachExploded: DeadZombieman_NoHeadFront { 
	States
	{	
	Spawn:
		ZXZ1 E -1;
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoHeadFront");
	Stop;
}

}	
		

CLASS DeadZombieMan_Blasted: DeadZombieMan_NoHeadFront { 
States
{
	Spawn:
		ZXZ2 E -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 15), doomb_random_velocity(5));
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 15) );
		ZZD3 H -1;//doomb_final_absolution(12, 12);
		Stop;
}

}			
		
CLASS DeadZombieManFacingFront: DeadZombieMan_NoArmFront { 
States
{
	Spawn:
		FPZ2 J -1;
	Stop;
		
	Death:
		TNT1 A 0;
		TNT1 A 0 A_Jump(256, "Death1", "Death2");
	Death1:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 15), doomb_random_velocity(5));
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 15) );
		TNT1 A 0 doomb_severed_limb("DeadZombieMan_NoArmFront");
	Stop;

	Death2:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("DeadZombieMan_NoHeadFront");
	Stop;
}

}		

CLASS DeadZombieManFacingFrontMinorHead: DeadZombieManFacingFront { 
States
{
	Spawn:
		12DG N -1;
		Stop ;
	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("DeadZombieMan_NoHeadFront");
	Stop;
}

}

CLASS zombie_fatalized_body: ZombiemanTorso
{
States
{
	Spawn:
		FPZ3 S -1;//doomb_final_absolution(12, 12);
	Stop;
}

}		
		
CLASS DeadZombiemanShotguntotheFace1: DeadZombieman1 { 
States
{
	Spawn:
		POS4 J -1;
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfZombieMan", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		
		TNT1 A 0 doomb_Meat_Death_Small();
		ZZD1 H -1;//doomb_final_absolution(12, 12);
	Stop;
		
}

}

CLASS DeadZombiemanShotguntotheFace2: DeadZombieman1 { 
States
{
	Spawn:
		POS4 T -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfZombieMan", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		
		TNT1 A 0 doomb_Meat_Death_Small();
		ZZD1 H -1;//doomb_final_absolution(12, 12);
	Stop;
}

}

CLASS DeadZombiemanLikeInActionMovie: DeadZombieman1
{
States
{
	Spawn:
		12DG I -1;
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking;
		
		TNT1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfZombieMan", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		
		TNT1 A 0 doomb_Meat_Death_Small();
		ZZD1 H -1;//doomb_final_absolution(12, 12);
	Stop;
}

}		

	
CLASS DyingZombieman : doomb_body_base
{ 
	Default {
	
	Radius 12;
	Height 16;
	Speed 9;
	Health 50;
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	damagefactor "Kick", 6.0;
	PainChance "Kick", 255;
	damagefactor "trample", 2.0;
	damagefactor "Death.KickDowned", 100.0;
	damagefactor "Death.KickDownedAny", 100.0;
	+SHOOTABLE;
	+FLOORCLIP;
	//+NOBLOCKMAP
	+LOOKALLAROUND;
	+FRIGHTENED;
	-SOLID;
	+DONTSPLASH;
	MONSTER;
	+FRIENDLY;//
	-COUNTKILL;
	+GHOST;
	+THRUGHOST;
	Mass 500;
	}
    States
    {
	
	Pain.Kick:
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_for_khorne("brutal_Blood", (0, 0, 30), doomb_random_velocity(5));
		TNT1 A 0 A_Givetotarget("CrueltyBonus1health");
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_FaceTarget;
		ZMAK ABA 4;
		ZMAM A 20;
		Goto See;
		
		
	Death.Fatality:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("HasZmanShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	Stop;

	Death.Kick:
	Death.KickDowned:
	Death.punch:
		tnt1 A 0
		{
			doomb_monster_fatality_camera(target);
			A_Pain();
			A_NoBlocking();
		}
		01CB A 3;

		tnt1 A 0 A_PlaySound("grunt/death");
		01CB BCCCC 3 SetPlayerProperty(0,1,0);
		tnt1 A 0 A_PlaySound("misc/xdeath1");
		01CB D 3;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		//spawn height +20
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
	
		TNT1 A 0 doomb_spawn_bloodpool();
		01CB E 20;
		tnt1 a 0
		{
			A_Givetotarget("HealthBonus",15);
			doomb_severed_limb("DeadZombieman_NoHeadfront");
			A_Givetotarget("HealthBonus",15);
			doomb_destroy_monster_fatality_camera();
		}
	Stop;
		
	Spawn:
		ZMAM A 1 A_Look;
		Loop;
	See:
		ZMAM ABAB 10 A_Chase;
		ZMAM A 9 A_Pain;
		TNT1 A 0 A_Jump(12, "LastStand");
		TNT1 A 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		
		tnt1 a 0 doomb_random_death();
	Loop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Pain;
		POSH Z -1;//doomb_final_absolution(12, 12);
	Stop;
		
	LastStand:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Pain;
		TNT1 A 0 doomb_severed_limb ("ZombiemanLastStand1");
	Stop;
		
	Death.Fire:
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Armor");
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
		
	mini_fire:
		TNT1 A 0 A_Playsound("BurnZom");
		ZMAB AABB 5 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				A_Chase();
				doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
			}
		TNT1 A 0 doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		tnt1 a 0 a_jumpif(random(0, 10) < 1, "death_fire");
	Loop;
		
	death_fire:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHH 3 light("BIGREDTORCH")
		{
			A_Explode(3,30, damagetype:"fire");
			{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}
			doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
		}
		TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
		BRZ3 HHHHHHHHHHHHHHHHHHHHHHHH 10 doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		BRZ3 H -1;
		Stop;
		
	Death.Trample:
		TNT1 A 0 doomb_much_blood(10);
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Armor");
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		01CB F -1;//doomb_final_absolution(12, 12);
		Stop;
		Stop;
		
	Death.SSG:
	XDeath:
		TNT1 A 0 doomb_gore_spawner(null, (0, 0, 5), 6);
		TNT1 AAAAAA 0 bright doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AA 0 bright doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AA 0 bright doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
		TNT1 A 1 A_NoBlocking;
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
	Stop;
		
	Death.Shotgun:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 doomb_much_blood(20);

		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		
		ZMAD B 0 A_XScream;
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
		ZMAD C 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("DeadZombieman_Noheadfront");
	Stop;
		
	Crush:
	Death.Stomp:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_gore_spawner(null, (0, 0, 5), 6);
		TNT1 AAAAAA 0 bright doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AA 0 bright doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AA 0 bright doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
		TNT1 A 1 A_NoBlocking;
	Stop;
}

}


//////////////////////////////////////////////////////////////////////////////////////////////////////
//zombieman minigun fatality
//////////////////////////////////////////////////////////////////////////////////////////////////////
CLASS BrutalizedZombieMan1 : doomb_body_base
{
Default
{
	Radius 16;
	Height 50;
	Health 300;
	
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	
	+SHOOTABLE;
	+NORADIUSDMG;
	+FLOORCLIP;
	+DONTSPLASH;
	+FRIENDLY;//
	+GHOST;
	-SOLID;
	+THRUGHOST;
	+nopain
	Scale 1.0;
	Mass 500;
}

States
{
	Spawn:
		TNT1 A 0 A_Recoil(2);
		TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 35), doomb_random_velocity(5));
		TNT1 AAAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		ZZD1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1
		{
			if(health <= 200)
				setstatelabel("no_head");
		}
		TNT1 A 0 doomb_severed_limb("BrutalizedZombieManStop");
	Stop;

		
	//BrutalizedZombieMan2
	no_head:
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );

		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAAAAAA 0 doomb_for_khorne("Brutal_Blood", (0, 0, 50), doomb_random_velocity(5));
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_Recoil(4);
		ZZD1 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1
		{
			if(health <= 100)
				setstatelabel("just_torso");
		}
		TNT1 A 0 doomb_severed_limb("BrutalizedZombieManStop2");
	Stop;

	just_torso:
		ZZD1 C 35;//just die
		ZZD3 H -1 doomb_final_absolution(12, 12);
	Stop;
		
	Death:
		TNT1 A 0 A_Recoil(2);
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 A_Givetotarget("CrueltyBonus5Health");
		ZZD1 EFG 6;
		ZZD1 H -1 doomb_final_absolution(12, 12);
	Stop;



	Death.SSG:
	XDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("ZombieXDeath");
	Stop;

	Death.Fatality:
	Death.punch:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("HasZManShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	Stop;
}

}

CLASS BrutalizedZombieManStop: CurbstompedMarine { 
    States
    {
	Spawn:
		ZZD2 ABCD 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("DeadZombieMan_NoArmFront");
	Stop;
}

}

CLASS BrutalizedZombieManStop2: CurbstompedMarine { 
States
{
	Spawn:
		ZZD4 AB 6 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		ZZD3 H -1 doomb_final_absolution(12, 12);
	Stop;
}

}


CLASS BrutalizedZombieManLeg: BrutalizedZombieMan1 { 
	States
	{
	Spawn:
		POS7 ABCD 5;
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoLeg");
	Stop;
		
	Death:
		TNT1 A 0 A_Recoil(4);
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 50), doomb_random_velocity(5) );

		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID13 ABCDEF 5;
		TNT1 A 0 doomb_severed_limb("VeryFuckedUpBrutalizedZombiemanLeg");
	Stop;
}

}

		

CLASS DeadZombieman_Slumped: ZombiemanTorso { 
Default
{
	+NOPAIN;
	Health 200;
	Height 40;
	doomb_monster_base.head_starting_position 22;
	Radius 6;
}
States
{
	Spawn:
		TNT1 A 0 A_Recoil(6);
		BR92 A 6;
		TNT1 A 0 A_JumpIf(vel.x == 0 && vel.y ==0, "LayDown");
		BR92 A 16;
	LayDown:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("DeadZombieman1");
	Stop;
	
	XDeath:
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("ZombieXDeath");
	Stop;
		
	Death.Headshot:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("DeadZombieman_Slumped_NoHead");
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
		TNT1 AA 0 doomb_severed_limb("XDeathArm1", (0, 0, 40), doomb_random_velocity(5));

		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		
		POSX E -1;//doomb_final_absolution(12, 12);
	Stop;
}

}		
		
CLASS DeadZombieman_Slumped_NoHead: ZombiemanTorso { 
	Default {
	
	+NOPAIN;
	Height 22;
	}
States
{
	Spawn:
		BR92 B -1;
	stop;
	
	XDeath:
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("ZombieXDeath");
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
		TNT1 AA 0 doomb_severed_limb("XDeathArm1", (0, 0, 40), doomb_random_velocity(5));
		POSX E -1 doomb_final_absolution(12, 12);
	Stop;
}

}