CLASS ZombiemanAmmo : Inventory { 
Default {
	
	inventory.maxamount 20;
}
}

CLASS TypeZombieman : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS EverSeenThePlayer : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS IsCrawling : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS doomb_zombie_Man : doomb_monster_base Replaces ZombieMan { 
Default {
	
	Health 50;
	Radius 16;
	Height 56;
	
	doomb_monster_base.headshot_multiplier 2;
	doomb_monster_base.head_starting_position 50;
	doomb_monster_base.legs_height_max 10;
	doomb_monster_base.weapon_type "rifle";

	Speed 6;
	Mass 300;
	FastSpeed 12;
	PainChance 200;
	PainChance "Avoid", 50;
	PainChance "Kick", 255;
	PainChance "Melee", 255;
	PainChance "Taunt", 255;
	PainChance "HelperMarineFatality", 255;
	damagefactor "Crush", 5.0;
	damagefactor "HelperMarineFatallity", 3.0;
	damagefactor "Avoid", 1.0;
	damagefactor "SSG", 50.0;
	damagefactor "Explosive_Impact", 2.5;
	damagefactor "Taunt", 1.0;
	damagefactor "cut", 0.7;
	damagefactor "saw", 0.7;
	PainChance "Trample", 255;
	PainChance "Explosive_Impact", 255;
	damagetype "Melee";
	
	Monster;
	+FLOORCLIP;
	+RANDOMIZE;
	+SLIDESONWALLS;
	+DONTHARMCLASS
	+DONTHARMSPECIES
	
	Scale 0.98;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	BloodType "Brutal_Blood",  "SawBlood";
	SeeSound "grunt/sight";
	AttackSound "weapons/rifle";
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	ActiveSound "grunt/active";
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "Explosive_Impact", 0.6;
	Obituary "%o has been gunned down by a Zombie Soldier.";
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_GiveInventory("SKZombieman", 1);
		TNT1 A 0 A_GiveInventory("TypeZombieMan", 1);
		TNT1 A 0 A_TakeInventory("ZombiemanAmmo", 20);
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", random(1,10));
		PSSS B 1;
	Stand:
		PSSS ABABABABAB 10 A_Look;
	Loop;
		
	SearchForPlayer:
	Idle:
		TNT1 A 0 A_ClearTarget;
		TNT1 A 0 A_TakeInventory("EnemyMemory", 30);
		TNT1 A 0 A_GiveInventory("SKZombieMan", 1);
		PSSS ABACADA 10 A_Look;
		POSS ABCD 4
		{
			A_Look();
			A_Wander();
		}
	Loop;
		
		
	FallBack:
		TNT1 A 0 A_CheckSight("Advance");
		TNT1 A 0 {bNODROPOFF = true;}
		TNT1 A 0 A_jump(64, "Missile");
		POSS DDCCBBAA 2
		{
			A_FaceTarget();
			A_Recoil(4);
		}
		TNT1 A 0 {bNODROPOFF = false;}
	GOto Missile;
		
	See:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		TNT1 A 0 A_CheckSight("SeeNeverSeen");
	SeeContinue:
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "SearchForPlayer");
		TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
		POSS AA 2 A_Chase;
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		POSS BBCCDD 2 A_Chase;
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "Idle");
	Loop;
		
	SeeNeverSeen:
	Advance:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		POSS AABBCCDD 2 A_Chase;
	Loop;
		
	Pain.Taunt:
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
		POSS B 0 A_Pain;
		TNT1 A 0 {bMISSILEMORE = true;}
		TNT1 A 0 {bMISSILEEVENMORE = true;}
		TNT1 A 0 A_PlaySound("grunt/sight");
		POSS B 1 A_FaceTarget;
		POSS B 10;
		TNT1 A 0 A_GiveInventory("Enraged", 1);
		TNT1 A 0 A_PlaySound("grunt/sight", 1);
	Goto Missile;
		
	Missile:
		POSS E 1 A_Stop;
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_TakeInventory("EnemyMemory", 10);
		TNT1 A 0 A_Jump(80, "Grenade");
		
		POSS EE 3 A_FaceTarget;
		TNT1 A 0 A_GiveInventory("ZombieManAmmo", 2);

		POSS EFEFEFE 2
		{
			if(frame == 5)
			{
				A_SpawnProjectile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
				A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
				A_PlaySound("weapons/rifle");
			}
			A_FaceTarget();
			A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		}
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		POSS F 2 BRIGHT A_SpawnProjectile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		
		POSS E 2 A_FaceTarget;
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
		TNT1 A 0 A_jump(96, "Missile");
		
		POSS E 6 A_FaceTarget;
		TNT1 A 0 A_JumpIfInventory("ZombieManAmmo", 20, "Reload");
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "SearchForPlayer");
	Goto SeeContinue;
		
		
	Grenade:
		TNT1 A 0 A_Stop;
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_TakeInventory("EnemyMemory", 10);
		TNT1 A 0 A_JumpIfCloser(500, "Missile");
		POSG A 6 A_FaceTarget;
		TNT1 A 0 A_PLaySound ("GRNPIN");
		POSG A 6 A_FaceTarget;
		POSG B 6 A_SpawnProjectile("ZombiemanGrenade", 42);
	Goto SeeContinue;
		
	Reload:
		TNT1 A 0 A_TakeInventory("ZombieManAmmo", 20);
		POSS E 3 A_SpawnProjectile("EmptyClipSpawn", 38, 0, random(-11, 11), 0);
		POSS E 1 A_PlaySound("Reload");
		ID12 A 30;
		ID12 C 10 A_PlaySound("CLIPIN");
		ID12 D 10;
		POSS A 10;
	Goto SeeContinue;
		
		//Currently unused. Used to make the enemy rolls left or right when hit by a rocket alert actor.
	Pain.Avoid:
		POSS A 1 A_FaceTarget;
		TNT1 A 0 ThrustThing((int)(angle*256/360+randompick(64, 192)), 15, 0, 0);
		ZRO2 ABCDEFGH 3 A_FaceTarget;
		Goto Missile;
		
	Pain:
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, 8);
		POSS G 5;
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		POSS G 5 A_Pain;
		TNT1 A 0 A_Jump(196, "Missile");
	Goto SeeContinue;
		TNT1 AAAA 0;
		TNT1 A 0 A_Pain;
		ID11 F 6;
	Goto GetUp;
		
	Pain.punch:
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, 8);
		POSS G 4;
		POSS G 4 A_Pain;
	Goto SeeContinue;
		TNT1 AAAA 0;
		TNT1 A 0 A_Pain;
		ID11 FRRRQ 10;
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_TakeInventory("IsDown", 1);
	Goto SeeContinue;
		
	Pain.Explosive_Impact:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		POS4 UVWXY 5;
	Goto FallingAfterImpact;
		
	Pain.Kick:
	Pain.HeavyImpact:
		TNT1 A 0 {bNODROPOFF = false;}
		POS4 U 0 A_Pain;
		TNT1 A 0 {bFORCEXYBILLBOARD = true;}
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
		TNT1 A 0 A_TakeInventory("SKZombieman", 1);
		POS4 U 1 A_facetarget;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget;
		POS4 U 3 ThrustThing((int)(angle*256/360+128), 10, 0, 0);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		POS4 UVWXY 3;
	Goto FallingAfterImpact;
		
	FallingAfterImpact:
		ID11 F 1 A_GiveInventory ("FallingHeight", 1);
		ID11 F 1 A_CheckFloor ("GetUp");
		tnt1 A 0 A_JumpIf (vel.z == 0, "GetUp");
	Loop;
		
	GetUp:
		TNT1 A 0 {if(waterlevel > 1) A_SpawnItem("LargeMassWaterImpact");}
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDie");
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		TNT1 A 0 A_Stop;
		ID11 RRRRRRRRRR 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		ID11 Q 10;
		TNT1 A 0 {bFORCEXYBILLBOARD = false;}
	Goto SeeContinue;
		
	FallingDie:
		TNT1 A 0 A_ChangeCountFlags(false, false);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 15, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDeath");
		
	FallingDeath:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBLocking;
		TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
		ID11 EF 2;
		TNT1 A 0 doomb_spawn_bloodpool();
		POSS L 0;
		TNT1 A 0 A_SpawnItem ("DeadZombieman1");
	Stop;
		
	FallingSuperDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBLocking;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 AAA 0 A_SpawnItem ("Ploft");
	Goto Death.Explosive_Impact+1;

	Death.punch:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
	Death.Kick:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 {bSLIDESONWALLS = true;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil (10);
		POS4 UUVWXY 5;
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
	Stop;

	death.back_stab:
		TNT1 A 0
		{
			if(target.player && target.player.readyweapon.getclassname() == "Melee_Attacks")
				setstate(curstate+1);
		}
	Goto Death;
		TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_GiveToTarget("SKZombieMan", 1);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 1;
	Stop;

	Death.Trample:
	Death.Down:
		POSS I 0 A_Scream;
		TNT1 A 0 A_Stop;
		POSS J 0 A_NoBlocking;
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 2, 0, random (0, 360), 2, random (0, 40));
		ID11 F 12;
		POSS K 3;
		POSS L 0;
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
	Stop;
		
	Death.MonsterShotgunBullet:
	Death.Shotgun:
		TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
		TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
		TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
	Goto Death;
		
	Death.Shotgunontheface:
	Death.HeavyImpact:
		TNT1 A 0;
		TNT1 A 0 {bSLIDESONWALLS = false;}
		TNT1 A 0 A_Jump(160, "DeathShotgunFly");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Stop;
		TNT1 A 0 A_Pain;
		POSS H 1 A_FaceTarget;
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_JumpIf(vel.y == 0, "DeathShotgunFly");
		TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_NoBlocking;
		POS4 ABCD 4 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		POS4 EFGHIJ 4 A_JumpIf((vel == (0, 0, 0) ), "DSFStop");
	Goto DSFStop+1;
		
	DSFStop:
		TNT1 A 0 A_SpawnItem("Ploft3");
		TNT1 A 0 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnProjectile ("WallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
		POS4 J 0;
		TNT1 A 0 A_SpawnItem("DeadZombiemanShotguntotheFace1");
	Stop;
		
	DeathShotgunontheface2:
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
		POS4 KLMN 4 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		POS4 OPQRST 4 A_JumpIf((vel.y == 0), "DSFStop2");
	Goto DSFStop2+1;
		
	DSFStop2:
		TNT1 A 0 A_SpawnItem("Ploft3");
		TNT1 A 0 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnProjectile ("WallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
		POS4 T 0;
		TNT1 A 0 A_SpawnItem("DeadZombiemanShotguntotheFace2");
		Stop;
		
		
	DeathShotgunFly:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 {bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil (6);
		POS4 U 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel == (0, 0, 0) ), "TakeASit");
		POS4 U 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel == (0, 0, 0) ), "TakeASit");
		POS4 V 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_JumpIf((vel == (0, 0, 0) ), "TakeASit");
		POS4 W 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		POS4 X 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		POS4 Y 5 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
	Stop;
	
	TakeASit:
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		POS4 U 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItemEx("DeadZombieman_Slumped", 10);
		Stop;
		
		
	Death:
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		TNT1 AA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 7, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Jump(32, "Death.Arm");
	Death.MinorLeg:
		TNT1 A 0 A_Jump(128, "DeathMirror");
		POSS Q 8 A_NoBlocking;
		POSS I 5 A_Scream;
		POSS J 5;
		POSS K 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
	Stop;
		
	Death.Rare:
		TNT1 A 0 A_FaceTarget;
		12DG A 5 A_Scream;
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("ZombieManTracer", 24, 5, -20, 2, -20);
		12DG B 5 BRIGHT;
		12DG CD 5;
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0 A_SpawnProjectile ("ZombieManTracer", 24, -5, 20, 2, 30);
		12DG E 5 BRIGHT;
		TNT1 A 0 A_NoBlocking;
		12DG FGHI 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		12DG I 0;
		TNT1 A 0 A_SpawnItem("DeadZombiemanLikeInActionMovie");
	Stop;
		
	DeathMirror:
		POSS R 8 A_NoBlocking;
		POSS M 5;
		POSS N 5 A_Scream;
		POSS OP 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		POSS P -1 doomb_final_absolution(12, 12);
	Stop;
		
	Death.Arm:
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_NoBlocking;
		ZZD1 I 10 A_Scream;
		TNT1 A 0 A_SpawnItemEx ("DyingZombiemanNoArm",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;

	Death.Leg:
		TNT1 A 0 A_JumpIfHealthLower(-300,"DoubleLegRemove");
		TNT1 A 0 A_JumpIfHealthLower(-20, "LegRemove");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		POSL MO 6;
		POSS K 6;
		TNT1 A 0 A_SpawnItem("DeadZombieman1");
		POSS L 0;
		TNT1 A 0 doomb_spawn_bloodpool();
	Stop;
		
	DoubleLegRemove:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 A_SpawnProjectile ("XDeathZombieLeg", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Blood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath2", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		POS8 ABC 3;
		POS8 D 10;
		TNT1 A 0 doomb_spawn_bloodpool();
		POS8 D 0;
		POS8 D -1 doomb_final_absolution(12, 12);
	Stop;
		
	LegRemove:
		TNT1 A 0 A_Jump(64, "LegRemoveRare");
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_SpawnItemEx ("ZombiemanGotHisLegBlowed",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;
		
	LegRemoveRare:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieLeg", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_SpawnItemEx ("ZombiemanSacilol",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
	Stop;
		
		
		
	Death.Saw:
		TNT1 A 0 A_Jump(96, "Death.arm");
	Goto Death.Tear;
		
	Death.cut:
	Death.HKFT:
		TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_XScream;
		TNT1 O 0 A_NoBlocking;
		TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieMan", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (0, 40));
		POSX AABCDE 9 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 doomb_spawn_bloodpool();
		POSX EEEEEEEEEEEEEEEEEEEEEE 1 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 90));
		POSX E 0;
		POSX E -1 doomb_final_absolution(12, 12);
	Stop;
	
	Death.cutless:
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(64, "Death.Rare");
		TNT1 A 0 A_Jump(16, "Death.Saw");
		TNT1 A 0 A_Jump(9, "Death.LegMassacre");
		TNT1 A 0 A_Jump(64, "Death");
	Goto Death.Minigun;
		
	Death.Minigun:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Scream;
		TNT1 O 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem ("BrutalizedZombieMan1", 1);
	Stop;
		
	Death.LegMassacre:
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("BrutalizedZombieManLeg");
		POS7 B 1 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("misc/xdeath2");
		LEG1 IJK 8;
		LEG1 E 1 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		LEG1 E -1 doomb_final_absolution(12, 12);
	Stop;
		
	Death.Tear:
		TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_XScream;
		TNT1 O 0 A_NoBlocking;
		PP2X AA 8 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 40, 0, random (0, 360), 2, random (0, 160));
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieman2", 32, 0, random (0, 360), 2, random (0, 160));
		PP2X BBCD 8 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 doomb_spawn_bloodpool();
		PP2X EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (0, 90));
		PP2X E -1 doomb_final_absolution(12, 12);
	Stop;
		
		
		
	Death.Eat:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_GiveToTarget("ZombieManFatality",1);
	Stop;
		
	Death.Fatality:
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_Jump(256,"Death.Fatality1", "Death.Fatality1", "Death.Fatality2", "Death.Fatality2", "Death.Fatality3", "Death.Fatality3", "Death.Fatality4");
		
	Death.Fatality1:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_GiveToTarget("ZombieManFatality", 1);
		Stop;
	Death.Fatality2:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_GiveToTarget("ZombieManFatality2", 1);
		Stop;
	Death.Fatality3:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_GiveToTarget("ZombieManFatality3", 1);
		Stop;
	Death.Fatality4:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_GiveToTarget("ZombieManFatality4", 1);
		Stop;
		
	Death.HelperMarineFatallity:
		TNT1 A 1 A_Pain;
		TNT1 A 0 A_Chase(null,null);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("ZombieManFatality3", 1);
	Stop;
		
	Death.BHFT:
	Death.RVFT:
		TNT1 A 1 A_Pain;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_GiveToTarget("ZombieManFatality", 1);
	Stop;
		
	Death.Headshot:
		TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
			TNT1 A 0 A_Jump(126, "headshot_1");
		TNT1 A 0 {if(target.player && target.player.readyweapon.getclassname() == "Melee_Attacks") setstatelabel("Death_headshot_1");}
		TNT1 A 0 A_JumpIfHealthLower(-600, "XDeath");
		TNT1 A 0 A_JumpIfHealthLower(-250, "Death.SSGHead");
		TNT1 A 0 A_JumpIfHealthLower(-50, "Death.HeadExplode");
		TNT1 A 0 A_Jump (96, "Death_headshot_1");
		TNT1 A 0 A_Jump (96, "Death_headshot_2");
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_SpawnProjectile ("Brutal_LiquidBlood", 50, 0, random (175, 185), 2, random (30, 40));
		POSH U 5 A_SpawnProjectile ("MuchBlood", 40, 0, random (0, 360), 2, random (0, 160));
		POSH V 5;
		TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 A 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		POSH W 5 A_NoBlocking;
		POSH XY 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		POSH Z -1 doomb_final_absolution(12, 12);
	Stop;

	Death_headshot_1:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("DyingZombiemanLostTeeth");
		Stop;
		
		
	Death_headshot_2:
		TNT1 A 0;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 A 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("Brutal_LiquidBlood", 50, 0, random (175, 185), 2, random (30, 40));
		12DG J 6 A_SpawnProjectile ("MuchBlood", 40, 0, random (0, 360), 2, random (0, 160));
		12DG KL 8;
		TNT1 A 0 A_Scream;
		12DG M 6 A_NoBlocking;
		TNT1 A 0 doomb_spawn_bloodpool();
		12DG N 0;
		TNT1 A 0 A_SpawnItem("DeadZombieManFacingFrontMinorHead");
	Stop;
		
	Death.HeadExplode:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_JumpIfInTargetInventory("HeavyStrikeUpward", 1, "HeavyHead");
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		ZMAD B 0 A_XScream;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		ZMAD C 0 A_NoBlocking;
		
		TNT1 A 0 A_Jump(32, "Deathchickenhead");
		ZMAD AAAAABBBBBBBBBBCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 doomb_spawn_bloodpool();
		ZMAD DDDDEEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoHeadFront");
	Stop;
		
	HeavyHead:
		ZMAD C 0 A_NoBlocking;
		TNT1 A 0 A_ClearTarget;
		POSL G 1 A_Chase(null, null);
		POSL G 1 A_Pain;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(10);
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		ZMAD B 0 A_XScream;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		POSL GHIJK 6;
		POSL LLLLLLLLLLLLLLLLLLL 4 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (10, 40));
		POSL L -1;
		Stop;
		
		
	DeathChickenHead:
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		ZMAD FFGGHH 2 A_SpawnProjectile ("Brutal_LiquidBlood", 46, 0, random (0, 360), 2, random (60, 120));
		tnt1 a 0 a_jump(200, "DeathChickenHead");
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		ZMAD AAAAABBBBBBBBBBCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 doomb_spawn_bloodpool();
		ZMAD DDDDEEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoHeadFront");
		Stop;
		
	headshot_1:
		TNT1 A 0;
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieManHeadBeheaded", 50, 0, random (0, 360), 2, random (50, 90));
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 40, 0, random (0, 360), 2, random (0, 160));
		POSH AAA 15 A_SpawnProjectile ("MuchBlood", 40, 0, random (0, 360), 2, random (0, 160));
		ZMAD AAAAABBBBBBBBBBCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (60, 120));
		TNT1 A 0 doomb_spawn_bloodpool();
		ZMAD DDDDEEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 10, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnItem ("DeadZombieman_NoHeadFront");
		Stop;
		
	Death.fire:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("BurningZombieMan", 0, 7);
		//TNT1 A 0 A_SpawnItem("BurningZombieMan", 0, 10)
		Stop;
		
	Death.Plasma: Death.Plasma2:
		PBR1 A 6 A_Scream;
		TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 doomb_show_effect("BluePlasmaFire", (0, 0, 32), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		PBR1 B 6 A_NoBlocking;
		PBR1 CDEFGH 6 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		PBR1 HHHHHHHHHHHHHHHHHHHHHH 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		PBR1 H -1;
		Stop;
		
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_burned_flesh;
		
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("GreenFlameTrails", (0, 0, 50), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
		Stop;
		
		
		
	HeavyPunchRight:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 ThrustTHing((int)(angle*256/360+64), 10, 0);
		Goto BlownAwayRight;
		
	HeavyPunchLeft:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 ThrustTHing((int)(angle*256/360+192), 10, 0);
		Goto BlownAwayLeft;
		
	Death.Blast:
	Death.Railgun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Jump(128, "Death.Blast2");
		TNT1 A 0 A_Scream;
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
		ZXZ1 A 6 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		ZXZ1 BBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (30, 60));
		ZXZ1 CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (10, 40));
		ZXZ1 DD 3 A_SpawnProjectile ("Brutal_LiquidBlood", 6, 0, random (0, 360), 2, random (30, 60));
		ZXZ1 E -1;
		//TNT1 A 0 A_SpawnItem("DeadZombieMan_StomachExploded")
		Stop;
		
	Death.Blast2:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 42, 0, random (0, 360), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 A_SpawnProjectile ("Xdeath2", 16, 0, random (130, 210), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
		ZXZ2 A 6 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		ZXZ2 BBBBBBBBBBBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (30, 60));
		ZXZ2 CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (10, 40));
		ZXZ2 DD 3 A_SpawnProjectile ("Brutal_LiquidBlood", 6, 0, random (0, 360), 2, random (30, 60));
		ZXZ1 E 0;
		TNT1 A 0 A_SpawnItem("DeadZombieMan_Blasted");
		Stop;
		
	Death.SSG:
		ZZD1 E 1 A_Pain;
		ZZD1 E 1 A_FaceTarget;
		//TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160))
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 35, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieManHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		ZZD1 EEFFGH 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		ZZD1 H 0;
		POSX E -1 doomb_final_absolution(12, 12);
		Stop;
		
	Death.SSGHead:
	Death.Railgun:
		ZZD1 E 1 A_Pain;
		ZZD1 E 1 A_FaceTarget;
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 35, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 A_SpawnProjectile ("Bloodmist", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnProjectile ("jaw", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreenBig", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Teeth", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 10, 0, random (0, 360), 2, random (50, 90));
		
		TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 40));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		ZZD1 EEFFGH 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		ZZD1 H 0;
		POSX E -1 doomb_final_absolution(12, 12);
		Stop;
		
	XDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 42, 0, random (0, 290), 2, random (10, 60));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 42, 0, random (0, 290), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("ZombieXDeath", 2, 0, random (0, 360), 2, random (0, 160));
		Stop;
		TNT1 A 0;
		TNT1 A 0 A_Recoil(4);
		
	Crush:
	Death.Stomp:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		POSS IJK 2;
		TNT1 AA 0 A_SpawnItem("MeatDeathSmall");
		TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
		Stop;
		
	Death.Hammered:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID13 AB 5;
		ID13 CDEF 5 A_CheckFloor ("Dead.Explosive_Impact");
		ID13 FFFFFFFFFF 5 A_CheckFloor ("Dead.Explosive_Impact");
		Goto Dead.Explosive_Impact;
		
	Death.Explosive_Impact:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget;
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(angle < 180, "IsFacingNorth");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayLeft");
		Goto XDeath;
	IsFacingNorth:
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayLeft");
		Goto XDeath;
		
	BlownAwayLeft:
		TNT1 A 0;
		TNT1 A 0 A_Jump(96, "Death.Landmine");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Xscream;
		TNT1 A 0 A_SpawnItemEx("BloodMist", 0, 0, 50, vel.x, vel.y, vel.z, 0, SXF_ABSOLUTEVELOCITY);
		PXSX GHIJKLM 3 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
		TNT1 A 0 A_CheckFloor("Land8473");
		PXSX GHIJKLMGHIJKLM 5 A_CheckFloor("Land8473");
	Land8473:
		PXSX N 0;
		TNT1 A 0 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		PXSX O -1 doomb_final_absolution(12, 12);
		Stop;
		
	BlownAwayRight:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Jump(96, "Death.Hammered");
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_pieceGreen", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnItemEx("BloodMist", 0, 0, 50, vel.x, vel.y, vel.z, 0, SXF_ABSOLUTEVELOCITY);
		PXS2 GHIJKLM 3 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
		TNT1 A 0 A_CheckFloor("Land8472");
		PXS2 GHIJKLMGHIJKLM 5 A_CheckFloor("Land8472");
	Land8472:
		PXS2 N 0;
		TNT1 A 0 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		PXS2 O -1 doomb_final_absolution(12, 12);
		Stop;
		
	Death.LandMine:
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("GibHand", 42, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		ID13 A 1 A_Scream;
		ID15 A 9;
		ID15 BCD 9 A_CheckFloor("Dead.Landmine");
		ID15 DDDDD 9 A_CheckFloor("Dead.Landmine");
		TNT1 A 0 A_SpawnItem("DeadZombieman_NoLeg");
		Stop;
		
	Dead.Explosive_Impact:
		TNT1 AAAA 0 A_SpawnItem ("Blood");
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 A 0 A_SpawnItem("VeryFuckedUpBrutalizedZombiemanLeg");
		Stop;
		
	Dead.Landmine:
		TNT1 AAAA 0 A_SpawnItem ("Blood");
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("Ploft");
		ID15 E -1 doomb_final_absolution(12, 12);
		Stop;
		
		
		
}
}




CLASS ZombiemanGrenade : doomb_boolet_base { 
Default {
	Radius 4;
	Height 4;
	Speed 20;
	Damage 20;
	+MISSILE;
	+BLOODSPLATTER;
	+EXTREMEDEATH;
	+DOOMBOUNCE;
	Gravity 1.0;
	Scale 0.2;
	Decal "Scorch";
	SeeSound "none";
	DeathSound "Explosion";
	Obituary "$OB_MPROCKET";
	
	Damagetype "Explosive_Impact";
	Speed 10;
	Damage 0;
	+GHOST;
	+THRUGHOST;
	BounceFactor 0.7;
	}
	States
	{
	Spawn:
		TNT1 A 0;
		BLUD C 0 ThrustThingZ (0,50,1,0);
	Live:
		GRND ABCDEFGH 2;
		Loop;
		
		
	Death:
		EXPL A 0 Radius_Quake (2, 8, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
		TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -30);
		TNT1 A 0 {if(waterlevel > 1) spawn("UnderwaterExplosion", pos:self.pos); }
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAA 0
					{
				doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
				doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
				doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
				doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
				doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
			}

		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 AAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
		TNT1 A 0 A_Explode(20, 200, 0);
		TNT1 A 0 A_Explode(20, 70, 1);
		TNT1 A 1;
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 AAAAAA 3 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
	Stop;
}
}

