CLASS doomb_zombie_Man : doomb_monster_base
{
private uint ammo_amount;

Default {
	
	Health 50;
	Radius 16;
	Height 56;
	
	doomb_monster_base.headshot_multiplier 2;
	doomb_monster_base.head_starting_position 50;
	doomb_monster_base.legs_height_max 10;
	doomb_monster_base.weapon_type "rifle";

	Speed 6;
	Mass 300;
	FastSpeed 12;
	PainChance 200;
	PainChance "Kick", 255;
	PainChance "Melee", 255;
	PainChance "Taunt", 255;
	PainChance "HelperMarineFatality", 255;
	damagefactor "Crush", 5.0;
	damagefactor "HelperMarineFatallity", 3.0;
	damagefactor "SSG", 50.0;
	damagefactor "Explosive_Impact", 2.5;
	damagefactor "Taunt", 1.0;
	damagefactor "cut", 0.7;
	damagefactor "saw", 0.7;
	PainChance "Trample", 255;
	PainChance "Explosive_Impact", 255;
	damagetype "Melee";
	
	Monster;
	+FLOORCLIP;
	+RANDOMIZE;
	+SLIDESONWALLS;
	+DONTHARMCLASS
	+DONTHARMSPECIES
	
	Scale 0.98;
	MaxStepHeight 24;
	MaxDropOffHeight 32;
	BloodType "Brutal_Blood",  "SawBlood";
	SeeSound "grunt/sight";
	AttackSound "weapons/rifle";
	PainSound "grunt/pain";
	DeathSound "grunt/death";
	ActiveSound "grunt/active";
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	Obituary "%o has been gunned down by a Zombie Soldier.";
}
States
{
	Spawn:
		TNT1 A 0 nodelay {ammo_amount = 20;}
	Stand:
		PSSS ABABABABAB 10 A_Look;
	Loop;
		
	SearchForPlayer:
	Idle:
		TNT1 A 0 A_ClearTarget;
		TNT1 A 0 doomb_update_memory();
		PSSS ABACADA 10 A_Look;
		POSS ABCD 4
		{
			A_Look();
			A_Wander();
		}
	Loop;
		
		
	FallBack:
		TNT1 A 0 A_CheckSight("Advance");
		TNT1 A 0 {bNODROPOFF = true;}
		TNT1 A 0 A_jump(64, "Missile");
		POSS DDCCBBAA 2
		{
			A_FaceTarget();
			A_Recoil(4);
		}
		TNT1 A 0 {bNODROPOFF = false;}
	GOto Missile;
		
	See:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 doomb_update_memory();
		TNT1 A 0 A_CheckSight("SeeNeverSeen");
	SeeContinue:
		TNT1 A 0 A_JumpIfCloser(200, "FallBack");
	Advance:
		TNT1 A 0 {bNODROPOFF = false;}
		POSS AABBCCDD 2 A_Chase;
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "Idle");
		TNT1 A 0 doomb_monster_memory();
	Loop;
		
	SeeNeverSeen:
	Advance:
		TNT1 A 0 {bNODROPOFF = false;}
		POSS AABBCCDD 2 A_Chase;
	Loop;
		
	Pain.Taunt:
		TNT1 A 0 A_JumpIfInventory("Enraged", 1, "Missile");
		POSS B 0 A_Pain;
		TNT1 A 0 {bMISSILEMORE = true;}
		TNT1 A 0 {bMISSILEEVENMORE = true;}
		TNT1 A 0 A_PlaySound("grunt/sight");
		POSS B 1 A_FaceTarget;
		POSS B 10;
		TNT1 A 0 A_GiveInventory("Enraged", 1);
		TNT1 A 0 A_PlaySound("grunt/sight", 1);
	Goto Missile;
		
	Missile:
		TNT1 A 0 doomb_update_memory();
		TNT1 A 0
		{
			if(ammo_amount <= 0)
			{
				setstatelabel("reload");
				return;
			}
		}
		POSS E 1 A_Stop;
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 A_Jump(80, "Grenade");
		
		POSS EE 3 A_FaceTarget;
		POSS EFEFEFE 2
		{
			if(frame == 5)
			{
				A_SpawnProjectile("ZombieManTracer", 32, 0, random(-8, 8), 1, random(-3, 3));
				A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
				A_PlaySound("weapons/rifle");
				ammo_amount --;
			}
			A_FaceTarget();
			A_PlaySOund("DISTFRRIFLE");
			{doomb_flare_base.doomb_attach_flare(self, "lens_flare_orange", (0, 0, 36) );}
		}
		TNT1 A 0 A_jump(96, "Missile");
		
		POSS E 6 A_FaceTarget;
		TNT1 A 0
		{
			if(ammo_amount <= 0)
			{
				setstatelabel("reload");
				return;
			}
		}
		TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "SearchForPlayer");
	Goto SeeContinue;
		
		
	Grenade:
		TNT1 A 0 doomb_update_memory();
		TNT1 A 0 A_Stop;
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 A_JumpIfCloser(500, "Missile");
		POSG A 6 A_FaceTarget;
		TNT1 A 0 A_PLaySound ("GRNPIN");
		POSG A 6 A_FaceTarget;
		POSG B 6 A_SpawnProjectile("ZombiemanGrenade", 42);
	Goto SeeContinue;
		
	Reload:
		POSS E 3 A_SpawnProjectile("EmptyClipSpawn", 38, 0, random(-11, 11), 0);
		POSS E 1 A_PlaySound("Reload");
		ID12 A 30 {ammo_amount = 20;}
		ID12 C 10 A_PlaySound("CLIPIN");
		ID12 D 10;
		POSS A 10;
	Goto SeeContinue;
		
	//MARK V: Currently unused. Used to make the enemy rolls left or right when hit by a rocket alert actor.
	//Apeirogom: But I dont think so :v
	Avoid:
		POSS A 1 A_FaceTarget;
		TNT1 A 0 ThrustThing((int)(angle*256/360+randompick(64, 192)), 15, 0, 0);
		ZRO2 ABCDEFGH 3 A_FaceTarget;
	Goto Missile;
		
	Pain:
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, 4);
		POSS G 5;
		POSS G 5 A_Pain;
		TNT1 A 0 A_Jump(196, "Missile");
	Goto SeeContinue;
		ID11 F 6 A_Pain;
	Goto GetUp;
		
	Pain.punch:
		POSS G 4 A_JumpIfInventory ("IsDown", 1, 2);
		POSS G 4 A_Pain;
	Goto SeeContinue;
		TNT1 A 0 A_Pain;
		ID11 FRRRQ 10;
		TNT1 A 0 A_TakeInventory("IsDown", 1);
	Goto SeeContinue;
		
	Pain.Explosive_Impact:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		POS4 UVWXY 5;
	Goto FallingAfterImpact;
		
	Pain.Kick:
	Pain.HeavyImpact:
		TNT1 A 0 {bNODROPOFF = false;}
		POS4 U 0 A_Pain;
		TNT1 A 0 {bFORCEXYBILLBOARD = true;}
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
		POS4 U 1 A_facetarget;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget;
		POS4 U 3 ThrustThing((int)(angle*256/360+128), 10, 0, 0);
		TNT1 A 0 A_GiveInventory("IsDown", 1);
		POS4 UVWXY 3;
	FallingAfterImpact:
		ID11 F 1 A_GiveInventory ("FallingHeight", 1);
		ID11 F 1 A_CheckFloor ("GetUp");
		tnt1 A 0 A_JumpIf (vel.z == 0, "GetUp");
	Loop;
		
	GetUp:
		TNT1 A 0
		{
			if(waterlevel > 1)
				A_SpawnItem("LargeMassWaterImpact");
		}
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDie");
		TNT1 A 0 A_TakeInventory("FallingHeight", 100);
		TNT1 A 0 A_Stop;
		ID11 RRRRRRRRRR 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
		TNT1 A 0 A_TakeInventory("IsDown", 1);
		ID11 Q 10;
		TNT1 A 0 {bFORCEXYBILLBOARD = false;}
	Goto SeeContinue;
		
	FallingDie:
		TNT1 A 0 A_ChangeCountFlags(false, false);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 15, "Death.Stomp");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 10, "FallingSuperDeath");
		TNT1 A 0 A_JumpIfInventory ("FallingHeight", 5, "FallingDeath");
	FallingDeath:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBLocking;
		TNT1 AAAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		ID11 EF 2;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadZombieman1", limb_ignore_cvar: true);
	Stop;
		
	FallingSuperDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBLocking;
		TNT1 A 0 doomb_spawn_bloodpool();
	Goto Death.Explosive_Impact+1;

	Death.punch:
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
	Death.Kick:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 {bSLIDESONWALLS = true;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Screamandunblock;
		TNT1 A 0 A_Recoil (10);
		POS4 UUVWXY 5;
		TNT1 A 0 doomb_severed_limb("DeadZombieman1", limb_ignore_cvar: true);
	Stop;





	Death.Trample:
	Death.Down:
		TNT1 A 0 A_Screamandunblock;
		TNT1 A 0 A_Stop;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		ID11 F 12;
		POSS K 3;
		TNT1 A 0 doomb_severed_limb("DeadZombieman1", limb_ignore_cvar: true);
	Stop;
		
	Death.Shotgun:
		TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
		TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
		TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
	Goto Death;
		
	Death.Shotgunontheface:
	Death.HeavyImpact:
		TNT1 A 0 {bSLIDESONWALLS = false;}
		TNT1 A 0 A_Jump(160, "DeathShotgunFly");
		POSS H 1 A_Screamandunblock;
		TNT1 A 0 A_Recoil(13);
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		TNT1 A 0 A_JumpIf(vel != (0, 0, 0), "DeathShotgunFly");
		TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
		TNT1 A 0 A_Scream;
		TNT1 A 0 doomb_much_blood(35);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_NoBlocking;
		POS4 ABCD 4 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		POS4 EFGHIJ 4 A_JumpIf((vel == (0, 0, 0) ), "DSFStop");
	Goto DSFStop+1;
		
	DSFStop:
		TNT1 A 0 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 A 0 doomb_severed_limb("DeadZombiemanShotguntotheFace1", limb_ignore_cvar: true);
	Stop;
		
	DeathShotgunontheface2:
		TNT1 A 0 doomb_much_blood(35);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		POS4 KLMN 4 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		POS4 OPQRST 4 A_JumpIf((vel.y == 0), "DSFStop2");
	Goto DSFStop2+1;
		
	DSFStop2:
		TNT1 A 0 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 A 0 doomb_severed_limb("DeadZombiemanShotguntotheFace2", limb_ignore_cvar: true);
	Stop;
		
		
	DeathShotgunFly:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0 {bSLIDESONWALLS = false;}
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil (6);
		POS4 UVWXY 5
		{
			doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			if(vel == (0, 0, 0) )
			{
				setstatelabel("TakeASit");
				return;
			}
		}
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadZombieman1", limb_ignore_cvar: true);
	Stop;
	
	TakeASit:
		POS4 U 5 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadZombieman_Slumped", limb_ignore_cvar: true);
	Stop;
		
		
	Death:
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		TNT1 AA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 A_Jump(32, "Death.Arm");
	Death.MinorLeg:
		TNT1 A 0 A_Jump(128, "DeathMirror");
		POSS Q 8 A_Screamandunblock;
		POSS I 5 ;
		POSS JK 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadZombieman1", limb_ignore_cvar: true);
	Stop;
		
	Death.Rare:
		TNT1 A 0 A_FaceTarget;
		12DG A 5 A_Scream;
		12DG B 5 BRIGHT
		{
			A_PlaySound("weapons/rifle");
			A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
			A_SpawnProjectile ("ZombieManTracer", 24, 5, -20, 2, -20);
		}
		12DG CD 5;
		12DG E 5 BRIGHT
		{
			A_PlaySound("weapons/rifle");
			A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
			A_SpawnProjectile ("ZombieManTracer", 24, -5, 20, 2, 30);
		}
		TNT1 A 0 A_NoBlocking;
		12DG FGHI 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		12DG I 0;
		TNT1 A 0 doomb_severed_limb("DeadZombiemanLikeInActionMovie", limb_ignore_cvar: true);
	Stop;
		
	DeathMirror:
		POSS R 8 A_ScreamandunBlock;
		POSS MNOP 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		POSS P -1 doomb_final_absolution(12, 12);
	Stop;
		
	Death.Arm:
		TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 35), doomb_random_velocity(5) );
		TNT1 A 0 doomb_much_blood(35);
		TNT1 A 0 A_NoBlocking;
		ZZD1 I 10 A_Scream;
		TNT1 A 0 doomb_severed_limb("DyingZombiemanNoArm", limb_ignore_cvar: true);
	Stop;

	Death.Leg:
		TNT1 A 0 A_JumpIfHealthLower(-300,"DoubleLegRemove");
		TNT1 A 0 A_JumpIfHealthLower(-20, "LegRemove");
		TNT1 A 0 ;
		POSL MO 6;
		POSS K 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadZombieman1", limb_ignore_cvar: true);
	Stop;
		
	DoubleLegRemove:
		TNT1 A 0 ;
		TNT1 AA 0 doomb_severed_limb("XDeathZombieLeg", (0, 0, 15), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		POS8 ABC 3;
		POS8 D 10;
		TNT1 A 0 doomb_spawn_bloodpool();
		POS8 D -1 doomb_final_absolution(12, 12);
	Stop;
		
	LegRemove:
		TNT1 A 0 A_Jump(64, "LegRemoveRare");
		TNT1 A 0 doomb_much_blood(15);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AA 0 doomb_severed_limb("XDeathZombieLeg", (0, 0, 35), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_Screamandunblock;
		TNT1 A 0 doomb_severed_limb("ZombiemanGotHisLegBlowed", limb_ignore_cvar: true);
	Stop;
		
	LegRemoveRare:
		TNT1 A 0 doomb_much_blood(15);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AA 0 doomb_severed_limb("XDeathZombieLeg", (0, 0, 35), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_Screamandunblock;
		TNT1 A 0 doomb_severed_limb("ZombiemanSacilol", limb_ignore_cvar: true);
	Stop;
		
		
		
	Death.Saw:
		TNT1 A 0 A_Jump(96, "Death.arm");
	Goto Death.Tear;
		
	Death.cut:
	Death.HKFT:
		TNT1 A 0 doomb_much_blood(35);
		TNT1 A 0 A_Screamandunblock;
		TNT1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb ("XDeathHalfZombieMan", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		POSX AABCDE 9 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		POSX EEEEEEEEEEEEEEEEEEEEEE 1 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		POSX E 0;
		POSX E -1 doomb_final_absolution(12, 12);
	Stop;
	
	Death.cutless:
		TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
		TNT1 A 0 A_Jump(64, "Death.Rare");
		TNT1 A 0 A_Jump(16, "Death.Saw");
		TNT1 A 0 A_Jump(9, "Death.LegMassacre");
		TNT1 A 0 A_Jump(64, "Death");
	Goto Death.Minigun;
		
	Death.Minigun:
		TNT1 A 0 A_Scream;
		TNT1 O 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("BrutalizedZombieMan1", limb_ignore_cvar: true);
	Stop;
		
	Death.LegMassacre:
		TNT1 A 0 doomb_much_blood(15);
		TNT1 A 0 doomb_severed_limb("BrutalizedZombieManLeg");
		POS7 B 1 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound("misc/xdeath2");
		LEG1 IJK 8;
		LEG1 E 1 doomb_spawn_bloodpool(BPS_SMALL);
		LEG1 E -1 doomb_final_absolution(12, 12);
	Stop;
		
	Death.Tear:
		TNT1 A 0 doomb_much_blood(1);
		TNT1 A 0 A_XScream;
		TNT1 O 0 A_NoBlocking;
		PP2X AA 8 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 AAAAAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfZombieman2", (0, 0, 32), doomb_random_velocity(5) );
		PP2X BBCD 8 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		PP2X EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 1 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		PP2X E -1 doomb_final_absolution(12, 12);
	Stop;
		
		
		
		
	Death.Eat:
	Death.BHFT:
	Death.RVFT:
		TNT1 A 1;
	Stop;
		
	Death.Headshot:
		TNT1 A 0 A_Jump(126, "headshot_1");
		TNT1 A 0 A_JumpIfHealthLower(-600, "XDeath");
		TNT1 A 0 A_JumpIfHealthLower(-250, "Death.SSGHead");
		TNT1 A 0 A_JumpIfHealthLower(-50, "Death.HeadExplode");
		TNT1 A 0 A_Jump (96, "Death_headshot_1", "Death_headshot_2");
		TNT1 A 0 A_Scream;
		TNT1 A 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_much_blood(40);
		POSH V 5;
		TNT1 AAAA 0 doomb_severed_limb("SmallBrainPiece", (0, 0, random (45, 55) ), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		POSH W 5 A_NoBlocking;
		POSH XY 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		POSH Z -1 doomb_final_absolution(12, 12);
	Stop;

	Death_headshot_1:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("DyingZombiemanLostTeeth");
		Stop;
		
		
	Death_headshot_2:
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 doomb_severed_limb("head_pieceGreen", (0, 0, random (45, 55) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, random (45, 55) ), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 A 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		12DG J 6 doomb_much_blood(48);
		12DG KL 8;
		TNT1 A 0 A_Scream;
		12DG M 6 A_NoBlocking;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadZombieManFacingFrontMinorHead", limb_ignore_cvar: true);
	Stop;
		
	Death.HeadExplode:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_JumpIfInTargetInventory("HeavyStrikeUpward", 1, "HeavyHead");
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		
		ZMAD B 0 A_XScream;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		ZMAD C 0 A_NoBlocking;
		
		TNT1 A 0 A_Jump(32, "Deathchickenhead");
		ZMAD AAAAABBBBBBBBBBCCCCC 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		ZMAD DDDDEEEEEEEEEEEEEEEE 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoHeadFront", limb_ignore_cvar: true);
	Stop;
		
	HeavyHead:
		ZMAD C 0 A_NoBlocking;
		TNT1 A 0 A_ClearTarget;
		POSL G 1 A_Chase(null, null);
		POSL G 1 A_Pain;
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil(10);
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		
		ZMAD B 0 A_XScream;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		POSL GHIJK 6;
		POSL LLLLLLLLLLLLLLLLLLL 4 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		POSL L -1;
	Stop;
		
		
	DeathChickenHead:
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		ZMAD FFGGHH 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		tnt1 a 0 a_jump(200, "DeathChickenHead");
		TNT1 A 0 A_PlaySound("misc/xdeath2c");
		ZMAD AAAAABBBBBBBBBBCCCCC 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		ZMAD DDDDEEEEEEEEEEEEEEEE 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoHeadFront", limb_ignore_cvar: true);
	Stop;
		
	headshot_1:
		TNT1 A 0 A_SpawnProjectile ("XDeathZombieManHeadBeheaded", 50, 0, random (0, 360), 2, random (50, 90));
		POSH AAA 15 doomb_much_blood(40);
		ZMAD AAAAABBBBBBBBBBCCCCC 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		ZMAD DDDDEEEEEEEEEEEEEEEE 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("DeadZombieman_NoHeadFront", limb_ignore_cvar: true);
	Stop;
		
	Death.fire:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("BurningZombieMan", limb_ignore_cvar: true);
	Stop;
		
	Death.Plasma: Death.Plasma2:
		PBR1 A 6 A_Scream;
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_severed_limb("Ashes1", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_show_effect("BluePlasmaFire", (0, 0, 32), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		PBR1 B 6 A_NoBlocking;
		PBR1 CDEFGH 6 doomb_for_khorne("brutal_Blood", (0, 0, 10), doomb_random_velocity(5) 	);
		PBR1 HHHHHHHHHHHHHHHHHHHHHH 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		PBR1 H -1;
	Stop;

	HeavyPunchRight:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 ThrustTHing((int)(angle*256/360+64), 10, 0);
		Goto BlownAwayRight;
		
	HeavyPunchLeft:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 ThrustTHing((int)(angle*256/360+192), 10, 0);
		Goto BlownAwayLeft;
		
	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Jump(128, "Death.Blast2");
		TNT1 A 0 A_Scream;
		TNT1 AAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
		ZXZ1 A 6 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		ZXZ1 BBBBBBBBBBCCCDD 3 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		ZXZ1 E -1;
	Stop;
		
	Death.Blast2:
		TNT1 A 0 A_XScream;
		TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 42), doomb_random_velocity(5) );
		TNT1 AAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
		ZXZ2 A 6 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		ZXZ2 BBBBBBBBBBBBBBBBBBBCCCDD 3 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("DeadZombieMan_Blasted", limb_ignore_cvar: true);
	Stop;
		
	Death.SSG:
		ZZD1 E 1 A_Pain;
		ZZD1 E 1 A_FaceTarget;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_gore_spawner(null, (0, 0, 35), 6);
		TNT1 AAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 42), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathZombieManHead", (0, 0, 42), doomb_random_velocity(5) );
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		ZZD1 EEFFGH 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		POSX E -1 doomb_final_absolution(12, 12);
	Stop;
		
	Death.SSGHead:
	Death.Railgun:
		ZZD1 E 1 A_Pain;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 A 0 doomb_gore_spawner(null, (0, 0, 35), 6);
		TNT1 AAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), doomb_random_velocity(5) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 42), doomb_random_velocity(5) );

		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 AAAAA 0 doomb_for_khorne("blood_impact_splash");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("Teeth", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		ZZD1 EEFFGH 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		POSX E -1 doomb_final_absolution(12, 12);
	Stop;
		
	XDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("ZombieXDeath", limb_ignore_cvar: true);
	Stop;
	
	Crush:
	Death.Stomp:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		POSS IJK 2;
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_gore_spawner(null, (0, 0, 5), 6);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("CrushedRemains", limb_ignore_cvar: true);
	Stop;
		
	Death.Hammered:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 42), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathZombieLeg", (0, 0, 42), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID13 AB 5;
		ID13 CDEF 5 A_CheckFloor ("Dead.Explosive_Impact");
		ID13 FFFFFFFFFF 5 A_CheckFloor ("Dead.Explosive_Impact");		
	Death.Explosive_Impact:
		TNT1 A 0 {bNODROPOFF = false;}
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_FaceTarget;
		TNT1 A 1;
		TNT1 A 0 A_JumpIf(angle < 180, "IsFacingNorth");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayLeft");
		Goto XDeath;
	IsFacingNorth:
		TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayRight");
		TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayLeft");
		Goto XDeath;
		
	BlownAwayLeft:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 42), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathZombieLeg", (0, 0, 42), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_Xscream;
		PXSX GHIJKLM 3 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 A_CheckFloor("Land8473");
		PXSX GHIJKLMGHIJKLM 5 A_CheckFloor("Land8473");
	Land8473:
		TNT1 A 0 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		PXSX O -1 doomb_final_absolution(12, 12);
	Stop;
		
	BlownAwayRight:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Jump(96, "Death.Hammered");
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathArm1", (0, 0, 42), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathZombieLeg", (0, 0, 42), doomb_random_velocity(5) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 0 A_XScream;
		PXS2 GHIJKLM 3 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		TNT1 A 0 A_CheckFloor("Land8472");
		PXS2 GHIJKLMGHIJKLM 5 A_CheckFloor("Land8472");
	Land8472:
		TNT1 A 0 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		PXS2 O -1 doomb_final_absolution(12, 12);
	Stop;
		
	Dead.Explosive_Impact:
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("VeryFuckedUpBrutalizedZombiemanLeg", limb_ignore_cvar:true);
	Stop;







	////////////////////////////////////////////////////////////
	//			backstab from player
	////////////////////////////////////////////////////////////
	death.back_stab: 
		TNT1 A 0
		{
			if(is_melee_player_kill() )
				setstate(curstate+1);
		}
	Goto Death;
		tnt1 a 0
		{
			doomb_monster_fatality_camera(target);
			vel = (0, 0, 0);
		}
		SFZM AB 8;
		SFZM C 16;
		tnt1 A 0 A_PlaySound("misc/xdeath4");
		SFZM D 16;
		tnt1 A 1
		{
			doomb_severed_limb("DeadZombieMan1", limb_ignore_cvar: true);
			doomb_destroy_monster_fatality_camera();
		}
	Stop;



	Death.Fatality:
		tnt1 A 0
		{
			doomb_monster_fatality_camera(target);
			A_Pain();
			A_NoBlocking();
		}
		TNT1 A 0 A_Jump(256,"zombieman_fatality_1", "zombieman_fatality_2", "zombieman_fatality_3", "zombieman_fatality_4");

	zombieman_fatality_1:
		FTYZ AB 4;
		tnt1 A 0  A_PlaySound("grunt/pain");
		FTYZ BCDEF 3;
		tnt1 A 0 A_PlaySound("BURNZOM", 3);
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		FTYZ FG 2;
		tnt1 A 0 A_PlaySound ("misc/xdeath", 1);
		FTYZ FG 2;
		tnt1 A 0 A_PlaySound ("misc/xdeath", 1);
		FTYZ F 2 Radius_Quake (4, 24, 0, 15, 0);
		FTYZ H 4;
		tnt1 AA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		tnt1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		FTYZ I 4;
		tnt1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		tnt1 AA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		tnt1 A 0 A_PlaySound ("misc/xdeath", 3);
		
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 AAAAAAAAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
		tnt1 A 0 doomb_severed_limb("XDeathHalfZombieMan", (0, 0, 60), doomb_random_velocity(5));
		tnt1 A 0 doomb_severed_limb("XDeathHalfZombieManDown", (0, 0, 60), doomb_random_velocity(5));
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAA 0 doomb_severed_limb("Intestine", (0, 0, 50), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		tnt1 AAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", (0, 0, 60), doomb_random_velocity(5));
		FTYZ K 2;
		FTYZ L 15;
		tnt1 A 0 
		{
			A_Givetotarget("HealthBonus",15);
			doomb_destroy_monster_fatality_camera();
		}
	stop;
	
	
	zombieman_fatality_2:
		FPZ2 AB 4;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 AAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 AAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", (0, 0, 60), doomb_random_velocity(5));
		FPZ2 C 10;
		tnt1 A 0 A_PlaySound("imp/melee");
		FPZ2 D 10;
		tnt1 AAAAA 0 doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 AAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", (0, 0, 60), doomb_random_velocity(5));
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		FPZ2 EF 3;
		tnt1 A 0 A_PlaySound("grunt/death");
		FPZ2 G 6;
		tnt1 A 0 
		{
			A_Givetotarget("HealthBonus",15);
			doomb_severed_limb("ZombieManDyingAfterFatality", limb_ignore_cvar: true);
			doomb_destroy_monster_fatality_camera();
			doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		}
	stop;
	
	zombieman_fatality_3:
		FPZ3 AABCDE 3;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 A_PlaySound("grunt/pain", 1);
		FPZ3 FGGGG 2;
		
		FPZ3 HHHIIIIIIIIHJJJ 1;
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
		tnt1 A 0 A_PlaySound("grunt/pain", 1);
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0
		{
			actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 5 ) );
			if(a)
				a.scale = (0.45, 0.45);
		}
		TNT1 A 0 doomb_spawn_bloodpool();
		
		FPZ3 KKKLLLLLLKJJJ 1;
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
		tnt1 A 0 A_PlaySound("grunt/pain", 1);
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0
		{
			actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 5 ) );
			if(a)
				a.scale = (0.45, 0.45);
		}

		FPZ3 MMMNNNNNNNMOOO 1;
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
		tnt1 A 0 A_PlaySound("grunt/pain", 1);
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0
		{
			actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 5 ) );
			if(a)
				a.scale = (0.45, 0.45);
		}
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		
		
		FPZ3 PPPQQQQQQQPRRR 1;
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0
		{
			actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 5 ) );
			if(a)
				a.scale = (0.45, 0.45);
		}
		
		FPZ3 RP 3;
		tnt1 A 0 
		{
			A_Givetotarget("HealthBonus",15);
			doomb_severed_limb("zombie_fatalized_body", limb_ignore_cvar: true);
			doomb_destroy_monster_fatality_camera();
			doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		}
	stop;
	
	
	zombieman_fatality_4:
		FPZ4 AB 2;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 A_PlaySound("grunt/pain", 1);
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
		FPZ4 CDEEEFGH 3;
	zombie_punch_loop_4:
		FPZ4 HHI 2;
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
		tnt1 A 0 A_PlaySound("grunt/pain", 1);
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 4, 1);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0
		{
			actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 5 ) );
			if(a)
				a.scale = (0.45, 0.45);
		}
		tnt1 A 0 doomb_severed_limb("Teeth", (0, 0, 15), doomb_random_velocity(5));
		TNT1 A 0 doomb_spawn_bloodpool();
		FPZ4 JJJIH 2;
		tnt1 a 0 a_jump(100, 1);
	loop;
		FPZ4 OOOMN 2;
	zombie_punch_loop_4_1:
		FPZ4 NNM 2;
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
		tnt1 A 0 A_PlaySound("grunt/pain", 1);
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0
		{
			actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 5 ) );
			if(a)
				a.scale = (0.45, 0.45);
		}
		tnt1 A 0 doomb_severed_limb("Teeth", (0, 0, 15), doomb_random_velocity(5));
		FPZ4 OOOMN 2;
		tnt1 a 0 a_jump(100, 1);
	loop;
		FPZ4 NNM 2;
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
		tnt1 A 0 A_PlaySound("grunt/pain", 1);
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 5) );
		
		tnt1 A 0 doomb_severed_limb("Teeth", (0, 0, 15), doomb_random_velocity(5));
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 4);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 A 0 doomb_severed_limb("Teeth", (0, 0, 15), doomb_random_velocity(5));
		tnt1 AAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", (0, 0, 15), doomb_random_velocity(5));
		
		TNT1 A 0 doomb_severed_limb("eye", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_spawn_bloodpool();
		FPZ4 PL 6;
		tnt1 A 0 
		{
			A_Givetotarget("HealthBonus",15);
			doomb_severed_limb("zombie_fatalized_body", limb_ignore_cvar: true);
			doomb_destroy_monster_fatality_camera();
			doomb_severed_limb("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		}
	stop;
}

}


CLASS ZombiemanGrenade : doomb_boolet_base { 
Default
{
	Radius 4;
	Height 4;
	Speed 20;
	Damage 20;
	Gravity 1.0;
	Scale 0.2;
	Speed 15;
	Damage 0;
	BounceFactor 0.7;

	+MISSILE;
	+BLOODSPLATTER;
	+EXTREMEDEATH;
	+DOOMBOUNCE;
	+GHOST;
	+THRUGHOST;

	Decal "Scorch";
	SeeSound "none";
	DeathSound "Explosion";
	Obituary "$OB_MPROCKET";
	Damagetype "Explosive_Impact";
}

private uint timer;

States
{
	Spawn:
		TNT1 A 0 nodelay {vel.z += 10;}
	Live:
		GRND ABCDEFGH 2
		{
			vel.z -= 1;
			timer ++;
			if(timer > 20)
				setstatelabel("death");
		}
	Loop;
		
		
	Death:
	explosion:
		TNT1 a 1
		{
			Radius_Quake (2, 8, 0, 15, 0);//(intensity, duration, damrad, tremrad, tid)
			if(waterlevel > 1)
				spawn("UnderwaterExplosion", pos:self.pos);
			
			{doomb_flare_base.doomb_attach_flare(self, "NewfagExplosionFlare");}
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-0.5, 1) ) );
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(0.9, 1.4), 0) );
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(-1, 1) ), (frandom(0.9, 1.4), 0) );
			A_Explode(20, 70, 1);
			A_PlaySound("FAREXPL", 3);
		
			for(uint i = 0; i < 30; i++)
				doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-1, 1), frandom(-1, 1), frandom(0.5, 1) ) );
		}
	Stop;
}

}