//===========================================================================
//
// Imp
//
//===========================================================================
CLASS doomb_Imp : doomb_monster_base Replaces DoomImp { 
	Default {
		
		doomb_monster_base.headshot_multiplier 2;
		doomb_monster_base.head_starting_position 50;
		doomb_monster_base.legs_height_max 10;
		Height 60;
		
		Scale 1.04;
		Health 75;
		Radius 18;
		Mass 100;
		GibHealth 35;
		PainChance 200;
		PainChance "Head", 255;
		PainChance "Taunt", 255;
		PainChance "Kick", 255;
		PainChance "Melee", 255;
		PainChance "Fatality", 255;
		PainChance "HelperMarineFatality", 255;
		
		damagefactor "TeleportRemover", 0.0;
		damagefactor "GibRemoving", 0.0;
		PainChance "Explosive_Impact", 255;
		damagefactor "Avoid", 0.0;
		damagefactor "Trample", 1.5;
		damagefactor "SSG", 50.0;
		damagefactor "Crush", 10.0;
		DamageFactor "CauseObjectsToSplash", 0.0;
		Monster;
		Species "Imps";
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		BloodType "Brutal_Blood",  "SawBlood";
		+FLOORCLIP;
		SeeSound "imp/sight";
		PainSound "imp/pain";
		DeathSound "imp/death";
		ActiveSound "imp/active";
		damagefactor "SSG", 5.0;
		damagefactor "cut", 0.7;
		damagefactor "saw", 0.7;
		DropItem "DemonStrengthRune", 1;
		damagefactor "Explosive_Impact", 2.5;
		MaxStepHeight 24;
		MaxDropOffHeight 32;
		+MISSILEMORE;
		+SLIDESONWALLS;
		+RANDOMIZE;
		+MTHRUSPECIES;
		PainChance "Trample", 255;
		Speed 8;
	}
	States
	{
		
		Spawn:
			TROO A 0;
			TNT1 A 0 ACS_ExecuteAlways(796, 0, 0, 0, 0);//Check if Vanilla Mode is activated
			TNT1 A 0 A_GiveInventory("SKImp", 1);
			TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
			TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			Goto Stand;
			
		Stand:
			TROS ABABABABAB 10 A_Look;
			Loop;
			
		Idle:
		LookingForPlayer:
			TNT1 A 0 A_GiveInventory("SKImp", 1);
			
			TROS A 10 A_Look;
			
			TROS B 10 A_Look;
			
			TROS A 10 A_Look;
			TNT1 A 0 A_SetAngle(angle - 40);
			
			TROS A 10 A_Look;
			
			TROS B 10 A_Look;
			
			TROS A 10 A_Look;
			TNT1 A 0 A_SetAngle(angle + 40);
			
			TROS B 10 A_Look;
			
			TROS A 10 A_Look;
			
			TROS B 10 A_Look;
			
			TROO A 0 A_Wander;
			TROO AA 2 A_Look;
			TNT1 A 0 A_Recoil(-2);
		Goto LookingForPlayer;
			
			
			
		ForgetTarget:
			TNT1 A 0 A_ClearTarget;
			TNT1 A 0 A_TakeInventory("EnemyMemory", 25);
			TNT1 A 0 A_GiveInventory("LookingForPlayer", 1);
			Goto LookingForPlayer;
			
		See:
			TNT1 A 0;
			TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
			TNT1 A 0 A_Jump(128, "SeeContinue");
			
			TROT A 2 A_faceTarget;
			
			TROT BC 2;
		Goto SeeContinue;
			
			
			
		SeeContinue:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
			TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
			
		Advancing:
			TNT1 A 0 A_TAkeInventory("CantFire", 1);
			//TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0)
			
			TNT1 A 0 A_JumpIfInventory("EnemyMemory", 20, "ForgetTarget");
			TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
			
			TROO AAAA 2 A_Chase;
			TNT1 A 0 A_TakeInventory("SKImp", 1);

			TROO BBBBCCCCDDDD 2 A_Chase;
			TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
		Loop;
			
		SeeNeverSeen:
			//TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 10, 0, 0)
			TROO AAAA 2 A_Chase;
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TROO BBBBCCCCDDDD 2 A_Chase;
			TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
			Loop;
			
		Melee:
			TROO E 1 A_FaceTarget;
			TNT1 A 0 A_TakeInventory("EnemyMemory", 100);
			
			TNT1 A 0 A_JumpIfCloser(50, "Melee2");
			
			TROT CD 4;
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TNT1 A 0 ThrustThingZ(0,25,0,1);
			TNT1 A 0 A_FaceTarget;
			
			TNT1 A 0 A_Recoil (-10);
			TROT E 2;
			TROT F 2;
			TNT1 A 0 A_GiveInventory ("IsJumping");
			TNT1 A 0 A_FaceTarget;
			TROT F 6;
			TNT1 A 0 A_SpawnProjectile("ImpAttack2",10,0,0,0);
			TNT1 A 0 A_TakeInventory ("IsJumping");
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			TROT G 1;
			TROT GG 2 A_SpawnProjectile("ImpAttack2",10,0,0,0);
			TROT G 1;
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			TROT HHH 2 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			Goto SeeContinue;
			
		Melee2:
			TROO EF 4 A_FaceTarget;
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TROO G 4 A_SpawnProjectile("ImpAttack",10,0,0,0);
			TROO FE 4;
			Goto SeeContinue;
			
		Missile:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(200, "Melee");
			TNT1 A 0 A_TakeInventory("EnemyMemory", 100);
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			
			TROO E 3 A_FaceTarget;
			
		FireballAttack:
			
			TROO E 2 A_FaceTarget;
			TNT1 A 0 A_JumpIfCloser(170, "Melee");
			TNT1 A 0 A_Playsound ("IMPCHARG");
			TROO EEEEE 2
			{
				A_FaceTarget();
				doomb_show_effect("FlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 30, 35), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );	
				doomb_show_effect("ImBallGettingReady", ( (cos(angle - 90), sin(angle - 90) ) * 30, 35), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			}
			TROO F 2 A_FaceTarget;
			TNT1 A 0 A_Jump(100, "specialattack");
			TROO G 6 A_SpawnProjectile("FireBall_", 34, 0, 0, 0);
			TROO F 4;
		Goto SeeContinue;
			
			
		SpecialAttack:
			TROO G 6 A_SpawnProjectile("FireBall_", 34, 0, 0, 0);
			TROO F 4;
			TROO I 2 A_FaceTarget;
			TROA H 6 A_SpawnProjectile("FireBall_", 34, 0, 0, 0);
			TROO I 4;
		Goto SeeContinue;
			
		Death.Eat:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_GiveToTarget("ImpFatality",1);
			TNT1 A 0;
			Stop;
			
		Death.HelperMarineFatallity:
		Death.RVFT:
			TNT1 A 0;
			TNT1 A 1 A_Pain;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("ImpFatality3", 1);
			TNT1 A 0 A_GiveToTarget("ImpFatality", 1);
			Stop;
			
		Death.Fatality:
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("GoFatality", 1);
			TNT1 A 0 A_Jump(255, "Death.Fatality1", "Death.Fatality1", "Death.Fatality2", "Death.Fatality3");
		Death.Fatality1:
			TNT1 A 0 A_GiveToTarget("ImpFatality", 1);
			Stop;
		Death.Fatality2:
			TNT1 A 0 A_GiveToTarget("ImpFatality2", 1);
			Stop;
		Death.Fatality3:
		Death.BHFT:
			TNT1 A 0 A_GiveToTarget("ImpFatality3", 1);
			Stop;
			
		death.stealth:
			TNT1 A 1;
			TNT1 A 0 A_GiveToTarget("SKImp");
			TNT1 A 0 A_GiveToTarget("GoFatality", 1);
			TNT1 A 1 A_Die("Stealthy");
		Stop;
		
		Death.Stealthy:
			TNT1 A 0 A_NoBlocking;
			Stop;

	StealthKill:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInTargetInventory("FistsSelected", 1, 1);
	Goto Death;
		TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 0 A_GiveToTarget("SKImp", 1);
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 A 1;
		TNT1 A 0 A_Die("Stealthy");
		TNT1 A 1;
		Stop;
	Death.Stealthy:
		TNT1 A 0;
		Stop;

		Pain:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain.IsDown");
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TROO H 3;
			TROO H 3 A_Pain;
		Goto SeeContinue;
			
		Pain.IsDown:
			ID11 B 1;
			ID11 B 5 A_Pain;
		Goto GetUp;
			
			
		Pain.KillMe:
		Pain.Taunt:
			TNT1 A 0;
			Goto Missile;
			
		Pain.head:
		Pain.minorhead:
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TROO H 6;
			TROO H 6 A_Pain;
		Goto SeeContinue;
			
		Pain.Explosive_Impact:
		Pain.punch:
			TNT1 D 0;
			TROO A 4;
			TNT1 A 0 A_JumpIfInventory ("SKImp", 1, "GotoStealthKill");
			TROO A 4 A_Pain;
			
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TNT1 A 0 A_GiveInventory("IsDown", 1);
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			IZD4 KL 8;
			Goto FallingAfterImpact;
			
			
		Pain.Kick:
		Pain.HeavyImpact:
			TNT1 A 0;
			IZD4 K 1 A_Pain;
			TNT1 A 0 A_GiveInventory("IsDown", 1);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			IZD4 K 1 A_facetarget;
			IZD4 K 6 ThrustThing(angle*256/360+128, 5, 0, 0);
			IZD4 L 8;
		FallingAfterImpact:
			IZD4 L 1 A_GiveInventory ("FallingHeight", 1);
			TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
			TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
			IZD4 L 1 A_CheckFloor ("GetUp");
			TNT1 A 0 {bNOPAIN = false;}
			tnt1 A 0 A_JumpIf (vel.z == 0, "GetUp");
		Loop;
			
		GetUp:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("LargeMassWaterImpact");
			TNT1 A 0 A_SpawnItem("SmallUnderwaterExplosion");
			TNT1 A 0 A_JumpIf(waterlevel == 2, "Swim");
			TNT1 A 0 A_JumpIf(waterlevel == 3, "Swim");
			TNT1 A 0 {bNOPAIN = false;}
			TNT1 A 0 {bSOLID = false;}
			TNT1 A 0 {bFORCEXYBILLBOARD = true;}
			TNT1 A 0 A_GiveInventory("ISDOWN", 1);
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 6, "FallingDie");
			IZD4 MMMMMMMM 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
			TNT1 A 0 {bSOLID = true;}
			TNT1 A 0 {bFORCEXYBILLBOARD = false;}
			TNT1 A 0 A_TakeInventory("ISDOWN", 1);
			TNT1 A 0 A_TakeInventory("FallingHeight", 100);
			TNT1 A 0 A_TakeInventory("IsDown", 1);
			IZD4 NO 7;
			Goto SeeContinue;
			
			
		FallingDie:
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 30, "Death.Stomp");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 20, "FallingSuperDeath");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 6, "FallingDeath");
			
		FallingDeath:
			TROO M 1;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBLocking;
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0 doomb_spawn_bloodpool();
			TROO M -1;
			Stop;
			
		FallingSuperDeath:
			TNT1 A 0;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBLocking;
			TNT1 A 0 doomb_spawn_bloodpool();
			Goto Death.Explosive_Impact+1;
			
			
		PainHurt:
			TNT1 A 0 A_TakeInventory("SKImp", 1);
			TROO H 1;
			TROO H 1 A_Pain;
			Goto SeeContinue;
			
		Death.MonsterShotgunBullet:
		Death.Shotgun:
			TNT1 A 0 {bSLIDESONWALLS = false;}
			TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
			TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
			TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
			Goto Death;
			
		Death.Shotgunontheface:
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(128, "DeathJump");
			TNT1 A 0 A_Jump(32, "Death.ARm");
			TNT1 A 0 A_Jump(96, "DeathNoGuts");
			TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_Pain;
			TROO H 1 A_FaceTarget;
			TNT1 A 0 A_Recoil(13);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
			TR06 ABCDE 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			TR06 FGHIJK 4 A_JumpIf((vel.Y == 0), "DSFStop");
			Goto DSFStop+1;
			
		DSFStop:
			TNT1 A 0 A_SpawnItem("Ploft3");
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnProjectile ("WallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
			TNT1 A 0 A_SpawnItem("DeadImpTR06K");
			Stop;
			
		DeathShotgunontheface2:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_Pain;
			TROO H 1 A_FaceTarget;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_Recoil(13);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 35, 0, random (0, 360), 2, random (0, 160));
			TR06 LMNO 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			TR06 QRSTU 4 A_JumpIf((vel.Y == 0), "DSFStop2");
			Goto DSFStop2+1;
			
		DSFStop2:
			TNT1 A 0 A_SpawnItem("Ploft3");
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnProjectile ("WallRedBlood", 2, 0, random (170, 190), 2, random (0, 0));
			TNT1 A 0 A_SpawnItem("DeadImpTR06V");
			Stop;
			
		Death.MinorLeg:
			TNT1 A 0;
			TNT1 A 0 A_Jump(48, "Death.Leg");
			Goto Death+5;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "DeathJump");
			TNT1 A 0 A_Jump(32, "Death.Arm");
			TNT1 A 0 A_Jump(24,"DeathNoGuts");
			TNT1 A 0 A_Jump(24,"Death20alt");
			TNT1 A 0 A_Jump(128, "DeathMirror");
			TR97 A 8;
			TR97 B 8 A_Scream;
			TR97 C 6;
			TR97 D 6 A_NoBlocking;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadImp");
			Stop;
			
		Death.Down:
		Death.Trample:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Stop;
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 2, 0, random (0, 360), 2, random (0, 40));
			ID11 DC 6;
			TNT1 A 0 A_SpawnItem("DeadImp");
			Stop;
			
		Death.Fire:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("BurningImpRunning", 0, 10);
			Stop;
			
			
		Death20alt:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TROD ABCD 6;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItemEx ("ImpDyingOfBloodLoss", 0,0,7,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
			
			
		Death.Arm:
			TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TR08 A 8 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItemEx ("DyingImpNoArm",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		Death.Leg:
			TNT1 A 0;
			TNT1 A 0 A_Jump(64, "DeathLeg2");
			TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "Death.LegInTheAir");
			TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TR09 A 9;
			TR09 A 3 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			TR09 B 3 A_Scream;
			TR09 C 3 A_NoBlocking;
			TNT1 A 0 A_SpawnItemEx ("DyingImpNoLeg",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		DeathLeg2:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnItem("ImpSaciLol");
			Stop;
			
			
			
		DeathJump:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Stop;
			TNT1 A 0 {bNODROPOFF = false;}
			TNT1 A 0 {bSLIDESONWALLS = false;}
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (10);
			ID11 A 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			ID11 A 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			ID11 B 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			ID11 B 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			ID11 C 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			ID11 C 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			ID11 D 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			ID11 D 4 A_SpawnProjectile ("Brutal_LiquidBlood3", 15, 0, random (0, 360), 2, random (0, 40));
			TNT1 A 0 A_JumpIf((vel.Y == 0), "TakeASit");
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadImp");
			Stop;
			
			Stop;
		TakeASit:
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 6, 0, random (170, 190), 2, random (0, 40));
			ID11 B 5;
			TNT1 A 0 A_SpawnItem("doomb_red_blood_pool");
			TNT1 A 0 A_SpawnItemEx("DeadImp_Slumped", 10);
			Stop;
			
			
		Death.Kick:   
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (8);
			ID11 ABCD 8;
			TNT1 A 0 A_SpawnItem("DeadImp");
			Stop;
			
			
			
			
			
		HeadExploder:
			TNT1 A 0;
			TNT1 A 0 A_Jump(72, "Death.HeadExplode");
			Goto Death.HeadMinor;
			
		Death.Headshot:
			TNT1 A 0 A_JumpIfInTargetInventory("HasPlasmaWeapon", 1, "Death.Plasma");
			TNT1 A 0 A_JumpIfInTargetInventory("HasCutingWeapon", 1, "Death.Decaptate");
			TNT1 A 0 A_JumpIfHealthLower(-60, "Death.HeadExplode");
			TNT1 A 0 A_JumpIfInTargetInventory("RandomHeadExploder", 1, "HeadExploder");
			Goto Death.HeadMinor;
			
		Death.HeadMinor:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_piece_dark", 50, 0, random (0, 360), 2, random (0, 160));
			//TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160))
			TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
			
			TROH K 9 A_NoBlocking;
			TROH L 9 A_Scream;
			TROH M 8;
			TROH N 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadImp_MinorHeadDeadFront");
			Stop;
			
			
		Death.headExplode:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 50);
			
			TROH AAAA 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 50, 0, random (0, 360), 2, random (60, 120));
			TNT1 A 0 A_NoBlocking;
			TROH BBBB 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 40, 0, random (0, 360), 2, random (60, 120));
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_Jump(32, "Deathchickenhead");
			TROH CCCCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (60, 120));
			TROH DDD 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 20, 0, random (0, 360), 2, random (60, 120));
			TNT1 A 0 doomb_spawn_bloodpool();
			TROH EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 15, 0, random (0, 360), 2, random (15, 40));
			TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
			Stop;
			
		Deathchickenhead:
			TNT1 A 0 A_PlaySound("misc/xdeath2c");
			TROH FFFGGGHHHIII 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (10, 90));
			tnt1 a 0 a_jump(200, "Deathchickenhead");
			
			TROH CCCCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 30, 0, random (0, 360), 2, random (60, 120));
			TROH DDD 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 20, 0, random (0, 360), 2, random (60, 120));
			TNT1 A 0 doomb_spawn_bloodpool();
			TROH EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood2", 15, 0, random (0, 360), 2, random (15, 40));
			TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
			Stop;
			
			
			
		DeathMirror:
			TROO V 9;
			TROO W 9 A_Scream;
			TROO X 8 A_NoBlocking;
			TROO Y 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadImpMinorHeadShot");
			Stop;
			
		Death.decaptate:
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("Blood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_SpawnProjectile ("XDeathImpHeadBeheaded", 50, 0, random (0, 360), 2, random (40, 90));
			TROH A 9;
			TROH B 9 A_XScream;
			TROH C 8 A_NoBlocking;
			TROH DE 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
			Stop;
			
		Death.cut:
		Death.HKFT:
		Death.Saw:
			TNT1 A 0;
			TNT1 A 0 A_Jump(48, "Death.Arm", "Death");
			TNT1 A 0 A_Jump(32,"DeathNoGuts");
			Goto Death.Tear;
			
			
			
			
			
		Death.cutless:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
			TNT1 A 0 A_Jump(32,"DeathNoGuts");
			TNT1 A 0 A_Jump(8, "Death.LegMassacre");
			TNT1 A 0 A_Jump(96, "Death");
			Goto Death.Minigun;
			
		Death.Minigun:
			TNT1 A 0;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Scream;
			TNT1 O 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("BrutalizedImp1", 1);
			Stop;
			
		Death.LegMassacre:
			TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TR09 A 8 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			TR09 B 8 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("ImpBrutalizedWithNoLeg");
			Stop;
			
		Death.Tear:
			TNT1 A 0 A_XScream;
			TNT1 O 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			TROG A 2 A_SpawnProjectile ("RipImp", 0, 0, random (0, 360), 2, random (0, 160));
			TROG AAA 4 doomb_spawn_big_blood(30);
			TROG BCDEFGH 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("DeadImp_Half", 5);
			Stop;
			
		DeathNoGuts:
			TNT1 AAAAA 0;
			TNT1 AA 0 A_SpawnProjectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 30, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 30, 0, random (0, 360), 2, random (0, 160));
			IMPC A 8 A_Scream;
			IMPC B 8 A_NoBlocking;
			IMPC C 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("DyingImp", 2);
			Stop;
			
	Death.Plasma: Death.Plasma2:
		PBR1 A 6 A_Scream;
		TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes2", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 doomb_show_effect("BluePlasmaFire", (0, 0, 32), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		PBR1 B 6 A_NoBlocking;
		PBR1 CDEFGH 6 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		PBR1 HHHHHHHHHHHHHHHHHHHHHH 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		PBR1 H -1;
	Stop;
		
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		
		
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_spawn_burned_flesh;
		
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("GreenFlameTrails", (0, 0, 50), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
		Stop;
		
	Death.Blast:
	Death.Railgun:
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Jump(128, "Death.Blast2");
		TNT1 A 0 A_XScream;
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TRO3 A 6 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		TRO3 BBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		TRO3 CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		TRO3 DD 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem("DeadImpTRO3E");
		Stop;
		
	Death.Blast2:
		TNT1 A 0 A_XScream;
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("BloodMistBig", 40, 0, random (0, 360), 2, random (30, 90));
		TRO4 A 6 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		TRO4 BBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (30, 60));
		TRO4 CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 26, 0, random (0, 360), 2, random (10, 40));
		TRO4 DD 3 A_SpawnProjectile ("Brutal_LiquidBlood2", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem("DeadImpTRO4E");
		Stop;
		
	Death.SSG:
	Death.SuperPunch:
		IZD1 E 1 A_Pain;
		IZD1 E 1 A_FaceTarget;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 35, 0, random (170, 190), 2, random (0, 40));
		//TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160))
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AA 0 A_SpawnProjectile ("XDeathImpArm", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		IZD1 EEFFG 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem("DeadImpIZD1H");
		Stop;
		
	XDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 42, 0, random (0, 190), 2, random (10, 60));
		TNT1 A 1 A_SpawnProjectile ("ImpXDeath", 0, 0, random (0, 360), 2, random (0, 160));
		Stop;
		
	Death.punch:
		TNT1 A 0 A_JumpIfInventory ("SKImp", 1, "StealthKill");
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Jump(96,"Death.LandMine");
		
		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece_dark", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		ID17 AB 5;
		ID17 CDEF 5 A_CheckFloor ("Dead.Explosive_Impact");
		ID17 EEEEEEEEEE 5 A_CheckFloor ("Dead.Explosive_Impact");
		TNT1 A 0 A_SpawnItem("DeadImpID17G");
		Stop;
		
	Dead.Explosive_Impact:
		TNT1 A 0;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("ThisImpGotFuckedHard");
		TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 A_SpawnItem ("Blood");
		Stop;
		
		
	Death.Landmine:
	Death.LandMine2:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,15,0,1);
	Death.LegInTheAir:
		TNT1 A 0 ThrustThingZ(0,35,0,1);
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAA 0 A_SpawnProjectile ("BloodMistLarge", 40, 0, random (0, 360), 2, random (20, 90));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		
		ID13 A 1 A_Scream;
		ID17 HI 4;
		ID17 JKLMN 4 A_CheckFloor ("Dead.Landmine");
		ID17 NNNNNNNN 4 A_CheckFloor ("Dead.Landmine");
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
		Stop;
		
	Dead.Landmine:
		TR09 E 0;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 A_SpawnItem ("Blood");
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
		Stop;
		
	Crush:
	Death.Stomp:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TROO KL 2;
		TNT1 AA 0 A_SpawnItem("MeatDeathSmall");
		TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath2b", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath3b", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
		Stop;
		
	FatalityMarine:
		TNT1 A 0 A_SetInvulnerable;
		IPFP ABCD 4;
		TNT1 A 0 A_SpawnItemEx("FootStep5", 0, 0, 40, 0, 0);
		IPFP EEF 6;
		
		TNT1 A 0 A_PlaySound("DSFDTHE");
		IPFP GHIJKHIJKLMNOLMNO 8
		{
			A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
			A_SpawnProjectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		}
		TNT1 A 0 A_TakeInventory("Fatality_Marine",1);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_UnSetInvulnerable;
		TNT1 A 0 A_SpawnItem ("MarineGotOwnedByImp", 1);
	Goto See;
		
		
	Swim:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_SpawnItem("ImpFish");
	Stop;
}
}

CLASS ImpAttack : doomb_boolet_base
{ 
Default {
	Radius 10;
	Height 18;
	DamageType "Rip";
	Projectile;
	+RANDOMIZE;
	Damage 2;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	+BLOODSPLATTER;
	RenderStyle "Add";
	Alpha 0.6;
	HitObituary "$OB_IMPHIT";
	Obituary "$OB_IMPHIT";
	
	SeeSound "None";
	DeathSound "none";
	Decal "none";
	Speed 20;
}

States
{
	Spawn:
		TNT1 A 4 BRIGHT;
		Stop;
	Death:
		TNT1 A 0 A_PlaySound("imp/melee");
		TNT1 A 0 BRIGHT;
		Stop;
}

}


CLASS MonsterTargetCheck : ACTOR { 
	Default {
	
	Radius 4;
	Height 4;
	Damage 0;
	PROJECTILE;
	-BLOODSPLATTER;
	+SEEKERMISSILE;
	+THRUSPECIES;
	SeeSound "None";
	DeathSound "none";
	Decal "none";
	Species "NonCombatant";
	Speed 300;
	}
	States
	{
	Spawn:
		TNT1 AAAAAAAAAAA 1 A_SeekerMissile (99,99);
		Stop;
	Death:
	XDeath:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfTargetInLOS("NoSight", 0, JLOSF_PROJECTILE, 50);
		TNT1 A 0 A_GiveToTarget("CantFire");
		PLAY A 0;
		TNT1 A 0 BRIGHT;
		Stop;
	NoSight:
		TNT1 A 0;
		PLAY A 0;
		TROO A 0;
		TNT1 A 1;
		Stop;
}
}


CLASS MonsterTargetCheckFaster: FastProjectile { 
	Default {
	
	Radius 4;
	Height 4;
	Projectile;
	Damage 0;
	-BLOODSPLATTER;
	+SEEKERMISSILE;
	+THRUSPECIES;
	SeeSound "None";
	DeathSound "none";
	Decal "none";
	Species "NotACover";
	Speed 900;
	}
	States
	{
	Spawn:
		TNT1 AAAAAAAAAAA 1 A_SeekerMissile (99,99);
		Stop;
	Death:
	XDeath:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfTargetInLOS("NoSight", 0, JLOSF_PROJECTILE, 50);
		TNT1 A 0 A_GiveToTarget("CantFire");
		PLAY A 0;
		TNT1 A 0 BRIGHT;
		Stop;
	NoSight:
		TNT1 A 0;
		PLAY A 0;
		TROO A 0;
		TNT1 A 1;
		Stop;
}
}



		

CLASS ImpAttack2: ImpAttack { 
	Default {
	
	+THRUGHOST;
	DamageType "ImpFatalityMarine";
	Damage 2;
	}
}

CLASS FireBall_ : doomb_boolet_base Replaces DoomImpBall { 
	Default {
	DamageType "Fire";
	Radius 4;
	Height 10;
	Speed 14;
	FastSpeed 18;
	Damagefunction (random(15,20));
	PROJECTILE;
	+THRUGHOST;
	RenderStyle "Add";
	Alpha 1;
	SeeSound "imp/attack";
	DeathSound "imp/shotx";
	Decal "Scorch";
	Scale 1.6;
}
States
{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "SpawnUnderwater");
	Spawn1:
		TNT1 A 0 A_JumpIfInventory("lowgraphicsmode", 1, "SpawnCheap");
		TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails", 0, random( -2, 2));
		FR7X A 1 BRIGHT;
		TNT1 A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		TNT1 A 0 A_SpawnItem ("CoolAndNewFlameTrails");
		FR7X B 1 BRIGHT;
	Loop;

	SpawnUnderwater:
		FR7X A 1 BRIGHT A_SpawnItem("FireballFlare",0,0);
		TNT1 A 0 A_SpawnProjectile ("BUBULZ", 0, 0, random (0, 360), 2, random (0, 180));
		FR7X B 1 BRIGHT A_SpawnItem("FireballFlare",0,0);
		TNT1 A 0 A_SpawnProjectile ("BUBULZ", 0, 0, random (0, 360), 2, random (0, 180));
		Goto Spawn1;
		
	Death:
		TNT1 A 0 A_SpawnItemEx ("SmallUnderwaterExplosion",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		EXPL AAAAAA 0 A_SpawnProjectile ("FireBallExplosionFlames", 1, 0, random (0, 360), 2, random (0, 360));
		FRFX CDEFGHIJKLMNOP 1 BRIGHT A_SpawnItem("RedFlare",0,0);
		TNT1 A 0 A_SpawnItemEx("TinyBurningPiece2", random (-5, 5), random (-5, 5));
		TNT1 A 0 A_SpawnItemEx ("DetectFloorCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItemEx ("DetectCeilCraterSmall",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 AAAA 19 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
	Stop;
}
}
