//===========================================================================
//
// Imp
//
//===========================================================================
CLASS doomb_Imp : doomb_monster_base
{ 
	Default {
		
		doomb_monster_base.headshot_multiplier 2;
		doomb_monster_base.head_starting_position 50;
		doomb_monster_base.legs_height_max 10;
		Height 60;
		
		Scale 1.04;
		Health 75;
		Radius 18;
		Mass 100;
		GibHealth 35;
		PainChance 200;
		PainChance "Taunt", 255;
		PainChance "Kick", 255;
		PainChance "Melee", 255;
		PainChance "Fatality", 255;
		PainChance "HelperMarineFatality", 255;
		

		PainChance "Explosive_Impact", 255;
		damagefactor "Trample", 1.5;
		damagefactor "SSG", 50.0;
		damagefactor "Crush", 10.0;
		Monster;
		Species "Imps";
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		BloodType "Brutal_Blood",  "SawBlood";
		+FLOORCLIP;
		SeeSound "imp/sight";
		PainSound "imp/pain";
		DeathSound "imp/death";
		ActiveSound "imp/active";
		damagefactor "SSG", 5.0;
		damagefactor "cut", 0.7;
		damagefactor "saw", 0.7;
		DropItem "DemonStrengthRune", 1;
		damagefactor "Explosive_Impact", 2.5;
		MaxStepHeight 24;
		MaxDropOffHeight 32;
		+FLOORCLIP;
		+MISSILEMORE;
		+SLIDESONWALLS;
		+RANDOMIZE;
		+MTHRUSPECIES;
		+dontharmclass
		PainChance "Trample", 255;
		Speed 8;
	}
	States
	{
		
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel >= 2, "Swim");
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
		Stand:
			TROS AB 10 A_Look;
		Loop;
			
		Idle:
		LookingForPlayer:
			TROS AAA 10 A_Look;
			TNT1 A 0 {angle += random(-40, 40);}
			TROS AAAAAA 10 A_Look;
			TROO AABBCCDD 2
			{
				A_Wander();
				A_Look();
				A_Recoil(-2);
			}
		loop;
			
		See:
			TROT A 2 A_faceTarget;
			TROT BC 2;
		SeeContinue:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			TNT1 A 0 A_JumpIf(waterlevel >= 2, "Swim");
		Advancing:
			TROO AAAABBBBCCCCDDDD 2 A_Chase;
			tnt1 a 0 doomb_monster_memory();
			TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "ForgetTarget");
		Loop;
			
		Melee:
			TROO E 1 A_FaceTarget;
			TNT1 A 0 doomb_update_memory();
			TNT1 A 0 A_JumpIfCloser(50, "Melee2");
			TROT CD 4;
			TNT1 A 0 ThrustThingZ(0,25,0,1);
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (-10);
			TROT E 2;
			TROT F 2;
			TNT1 A 0 A_GiveInventory ("IsJumping");
			TNT1 A 0 A_FaceTarget;
			TROT F 6;
			TNT1 A 0 doomb_cheap_melee_attack(100, random(5, 10), "ImpFatalityMarine");
			tnt1 a 0 a_Playsound("imp/melee");
			TNT1 A 0 A_TakeInventory ("IsJumping");
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			TROT G 1;
			TROT GG 2 doomb_cheap_melee_attack(100, random(5, 10), "ImpFatalityMarine");
			TROT G 1;
			TNT1 A 0 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			TROT HHH 2 A_JumpIfInventory("Fatality_Marine", 1, "FatalityMarine");
			Goto SeeContinue;
			
		Melee2:
			TROO EF 4 A_FaceTarget;
			TROO G 4 doomb_cheap_melee_attack(80, random(5, 30), "Rip");
			tnt1 a 0 a_Playsound("imp/melee");
			TROO FE 4;
			Goto SeeContinue;
			
		Missile:
			TNT1 A 0 A_JumpIfCloser(200, "Melee");
			TNT1 A 0 doomb_update_memory();
			TROO E 3 A_FaceTarget;
		FireballAttack:
			TROO E 2 A_FaceTarget;
			TNT1 A 0 A_JumpIfCloser(170, "Melee");
			TNT1 A 0 A_Playsound ("IMPCHARG");
			TROO EEEEE 2
			{
				A_FaceTarget();
				doomb_show_effect("FlameTrails", ( (cos(angle - 90), sin(angle - 90) ) * 30, 35), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );	
			}
			TROO F 2 A_FaceTarget;
			TNT1 A 0 A_Jump(100, "specialattack");
			TROO G 6 A_SpawnProjectile("FireBall_", 34, 0, 0, 0);
			TROO F 4;
		Goto SeeContinue;
			
			
		SpecialAttack:
			TROO G 6 A_SpawnProjectile("FireBall_", 34, 0, 0, 0);
			TROO F 4;
			TROO I 2 A_FaceTarget;
			TROA H 6 A_SpawnProjectile("FireBall_", 34, 0, 0, 0);
			TROO I 4;
		Goto SeeContinue;
			
		Death.Eat:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_GiveToTarget("ImpFatality",1);
			TNT1 A 0;
			Stop;
			
		Death.HelperMarineFatallity:
		Death.RVFT:
			TNT1 A 0;
			TNT1 A 1 A_Pain;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("ImpFatality3", 1);
			TNT1 A 0 A_GiveToTarget("ImpFatality", 1);
			Stop;

		Pain:
			TNT1 A 0 A_JumpIfInventory("IsDown", 1, "Pain.IsDown");
			TROO H 3;
			TROO H 3 A_Pain;
		Goto SeeContinue;
			
		Pain.IsDown:
			ID11 B 1;
			ID11 B 5 A_Pain;
		Goto GetUp;
			
			
		Pain.Taunt:
			TNT1 A 0;
			Goto Missile;
			
		Pain.Explosive_Impact:
		Pain.punch:
			TROO A 4;
			TROO A 4 A_Pain;
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Pain");
			TNT1 A 0 A_GiveInventory("IsDown", 1);
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			IZD4 KL 8;
			Goto FallingAfterImpact;
			
			
		Pain.Kick:
		Pain.HeavyImpact:
			IZD4 K 1 A_Pain;
			TNT1 A 0 A_GiveInventory("IsDown", 1);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			IZD4 K 1 A_facetarget;
			IZD4 K 6;
			IZD4 L 8;
		FallingAfterImpact:
			IZD4 L 1 A_GiveInventory ("FallingHeight", 1);
			TNT1 A 0 A_JumpIf(waterlevel > 2, "Swim");
			IZD4 L 1 A_CheckFloor ("GetUp");
			TNT1 A 0 {bNOPAIN = true;}
			tnt1 A 0 A_JumpIf (vel.z == 0, "GetUp");
		Loop;
			
		GetUp:
			TNT1 A 0;
			TNT1 A 0 {if(waterlevel > 1) A_SpawnItem("LargeMassWaterImpact");}
			TNT1 A 0
			{
				if(waterlevel > 1)
				{
					spawn("UnderwaterExplosion", pos:self.pos);
					setstatelabel("swim");
				}
			}
			TNT1 A 0 {bNOPAIN = false;}
			TNT1 A 0 {bSOLID = false;}
			TNT1 A 0 {bFORCEXYBILLBOARD = true;}
			TNT1 A 0 A_GiveInventory("ISDOWN", 1);
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 6, "FallingDie");
			IZD4 MMMMMMMM 5 A_JumpIf(vel.z < 0, "FallingAfterImpact");
			TNT1 A 0 {bSOLID = true;}
			TNT1 A 0 {bFORCEXYBILLBOARD = false;}
			TNT1 A 0 A_TakeInventory("ISDOWN", 1);
			TNT1 A 0 A_TakeInventory("FallingHeight", 100);
			TNT1 A 0 A_TakeInventory("IsDown", 1);
			IZD4 NO 7;
			Goto SeeContinue;
			
			
		FallingDie:
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 30, "Death.Stomp");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 20, "FallingSuperDeath");
			TNT1 A 0 A_JumpIfInventory ("FallingHeight", 6, "FallingDeath");
			
		FallingDeath:
			TROO M 1;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBLocking;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TROO M -1 doomb_spawn_bloodpool();
			Stop;
			
		FallingSuperDeath:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBLocking;
			TNT1 A 0 doomb_spawn_bloodpool();
		Goto Death.Explosive_Impact+1;
			
			
		PainHurt:
			TROO H 1;
			TROO H 1 A_Pain;
			Goto SeeContinue;
			
		Death.Shotgun:
			TNT1 A 0 {bSLIDESONWALLS = false;}
			TNT1 A 0 A_Jump(42, "Death.Shotgunontheface");
			TNT1 A 0 A_JumpIfCloser(80, "Death.Blast");
			TNT1 A 0 A_JumpIfCloser(320, "Death.Shotgunontheface");
			Goto Death;
			
		Death.Shotgunontheface:
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(128, "DeathJump");
			TNT1 A 0 A_Jump(32, "Death.ARm");
			TNT1 A 0 A_Jump(96, "DeathNoGuts");
			TNT1 A 0 A_Jump(128, "DeathShotgunontheface2");
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_Pain;
			TROO H 1 A_FaceTarget;
			TNT1 A 0 A_Recoil(13);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			TNT1 A 0 A_Scream;
			TNT1 A 0 doomb_much_blood(35);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TR06 ABCDE 4 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TR06 FGHIJK 4 A_JumpIf((vel.Y == 0), "DSFStop");
			Goto DSFStop+1;
			
		DSFStop:
			TNT1 A 0 A_SpawnItem("Ploft3");
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 A 0 A_SpawnItem("DeadImpTR06K");
		Stop;
			
		DeathShotgunontheface2:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Stop;
			TNT1 A 0 A_Pain;
			TROO H 1 A_FaceTarget;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_Recoil(13);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			TNT1 A 0 doomb_much_blood(35);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TR06 LMNO 4 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TR06 QRSTU 4 A_JumpIf((vel.Y == 0), "DSFStop2");
		Goto DSFStop2+1;
			
		DSFStop2:
			TNT1 A 0 A_SpawnItem("Ploft3");
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 A 0 A_SpawnItem("DeadImpTR06V");
		Stop;
			
		Death.MinorLeg:
			TNT1 A 0;
			TNT1 A 0 A_Jump(48, "Death.Leg");
			Goto Death+5;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "DeathJump");
			TNT1 A 0 A_Jump(32, "Death.Arm");
			TNT1 A 0 A_Jump(24,"DeathNoGuts");
			TNT1 A 0 A_Jump(24,"Death20alt");
			TNT1 A 0 A_Jump(128, "DeathMirror");
			TR97 A 8;
			TR97 B 8 A_Scream;
			TR97 C 6;
			TR97 D 6 A_NoBlocking;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadImp");
			Stop;
			
		Death.Down:
		Death.Trample:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Stop;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			ID11 DC 6;
			TNT1 A 0 A_SpawnItem("DeadImp");
		Stop;
			
		Death.Fire:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("BurningImpRunning", 0, 10);
		Stop;
			
			
		Death20alt:
			TNT1 A 0 A_Scream;
			TROD ABCD 6;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItemEx ("ImpDyingOfBloodLoss", 0,0,7,0,0,0,0,SXF_NOCHECKPOSITION,0);
		Stop;
			
			
			
		Death.Arm:
			TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_much_blood();
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TR08 A 8;
			TNT1 A 0 A_SpawnItemEx ("DyingImpNoArm",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		Death.Leg:
			TNT1 A 0;
			TNT1 A 0 A_Jump(64, "DeathLeg2");
			TNT1 A 0 A_JumpIfInventory("IsJumping", 1, "Death.LegInTheAir");
			TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_much_blood();
			TR09 A 9;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TR09 A 3;
			TR09 B 3 A_Scream;
			TR09 C 3 A_NoBlocking;
			TNT1 A 0 A_SpawnItemEx ("DyingImpNoLeg",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		DeathLeg2:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Fall;
			TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_much_blood();
			TNT1 A 0 A_SpawnItem("ImpSaciLol");
			Stop;
			
			
			
		DeathJump:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Stop;
			TNT1 A 0 {bNODROPOFF = false;}
			TNT1 A 0 {bSLIDESONWALLS = false;}
			TNT1 A 0 ThrustThingZ(0,40,0,1);
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (10);
			ID11 ABCD 4
			{
				doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
				if(vel == (0, 0, 0) ) setstatelabel("TakeASit");
			}
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadImp");
		Stop;
			
		TakeASit:
			TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			ID11 B 5;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItemEx("DeadImp_Slumped", 10);
		Stop;
			
			
		Death.Kick:   
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (8);
			ID11 ABCD 8;
			TNT1 A 0 A_SpawnItem("DeadImp");
		Stop;
			
			
			
			
			
		Death.Headshot:
			TNT1 A 0 A_Jump(126, "headshot_1");
			TNT1 A 0 A_JumpIfHealthLower(-60, "Death.HeadExplode");
		Death.HeadMinor:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("head_piece_dark", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
			
			TROH K 9 A_NoBlocking;
			TROH L 9 A_Scream;
			TROH M 8;
			TROH N 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadImp_MinorHeadDeadFront");
			Stop;
			
			
		Death.headExplode:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 50);
			TROH AAAA 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_NoBlocking;
			TROH BBBB 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_Jump(32, "Deathchickenhead");
			TROH CCCCCCCC 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TROH DDD 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			TROH EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
			
		Deathchickenhead:
			TNT1 A 0 A_PlaySound("misc/xdeath2c");
			TROH FFFGGGHHHIII 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			tnt1 a 0 a_jump(200, "Deathchickenhead");
			
			TROH CCCCCCCC 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TROH DDD 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			TROH EEEEEEEEEEEEEEEEEEEEEEEEEEEEE 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
			
			
			
		DeathMirror:
			TROO V 9;
			TROO W 9 A_Scream;
			TROO X 8 A_NoBlocking;
			TROO Y 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadImpMinorHeadShot");
			Stop;
			
		headshot_1:
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("Blood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 50, 0, random (0, 360), 2, random (40, 90));
			TROH A 9;
			TROH B 9 A_XScream;
			TROH C 8 A_NoBlocking;
			TROH DE 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
			Stop;
			
		Death.cut:
		Death.HKFT:
		Death.Saw:
			TNT1 A 0;
			TNT1 A 0 A_Jump(48, "Death.Arm", "Death");
			TNT1 A 0 A_Jump(32,"DeathNoGuts");
			Goto Death.Tear;
			
			
			
			
			
		Death.cutless:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfInventory ("IsDown", 1, "Death.Down");
			TNT1 A 0 A_Jump(32,"DeathNoGuts");
			TNT1 A 0 A_Jump(8, "Death.LegMassacre");
			TNT1 A 0 A_Jump(96, "Death");
			Goto Death.Minigun;
			
		Death.Minigun:
			TNT1 A 1
			{
				A_FaceTarget();
				A_Scream();
				A_NoBlocking();
				A_SpawnItem ("BrutalizedImp1", 1);
			}
		Stop;
			
		Death.LegMassacre:
			TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_much_blood();
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TR09 A 8;
			TR09 B 8 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("ImpBrutalizedWithNoLeg");
			Stop;
			
		Death.Tear:
			TNT1 A 0 A_XScream;
			TNT1 O 0 A_NoBlocking;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TROG A 2;
			TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAA 0 doomb_for_khorne("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfImp", 40, 0, random (0, 360), 2, random (0, 160));

			TROG AAA 4 doomb_spawn_big_blood(30);
			TROG BCDEFGH 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("DeadImp_Half", 5);
			Stop;
			
		DeathNoGuts:
			TNT1 AAAAA 0;
			TNT1 AAA 0 doomb_for_khorne("Intestine", (0, 0, 24), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
			TNT1 A 0 doomb_much_blood(30);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			IMPC A 8 A_Scream;
			IMPC B 8 A_NoBlocking;
			IMPC C 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("DyingImp", 2);
		Stop;
			
	Death.Plasma: Death.Plasma2:
		PBR1 A 6 A_Scream;
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
		TNT1 AAAA 0 doomb_show_effect("BluePlasmaFire", (0, 0, 32), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		PBR1 B 6 A_NoBlocking;
		PBR1 CDEFGH 6 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (0, 160));
		PBR1 HHHHHHHHHHHHHHHHHHHHHH 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		PBR1 H -1;
	Stop;

	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Jump(12, "Death.Arm");
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Jump(128, "Death.Blast2");
		TNT1 A 0 A_XScream;
		TNT1 AAA 0 doomb_for_khorne("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
		TRO3 A 6 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		TRO3 BBBBBBBBBBCCCDD 3 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_SpawnItem("DeadImpTRO3E");
	Stop;
		
	Death.Blast2:
		TNT1 A 0 A_XScream;
		TNT1 AAA 0 doomb_for_khorne("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
		TRO4 A 6 A_Stop;
		TNT1 A 0 doomb_spawn_bloodpool();
		TRO4 BBBBBBBBBBCCCDD 3 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_SpawnItem("DeadImpTRO4E");
	Stop;
		
	Death.SSG:
	Death.punch:
		IZD1 E 1 A_Pain;
		IZD1 E 1 A_FaceTarget;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 35), 6);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAA 0 doomb_for_khorne("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AA 0 A_SpawnProjectile ("XDeathImpArm", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		IZD1 EEFFG 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem("DeadImpIZD1H");
		Stop;
		
	XDeath:
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_FaceTarget;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 1 A_SpawnProjectile ("ImpXDeath", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;
		
	Death.punch:
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_XScream;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece_dark", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 ThrustThingZ(0,40,0,1);
		ID17 AB 5;
		ID17 CDEFEEEEEEEEEE 5 A_CheckFloor ("Dead.Explosive_Impact");
		TNT1 A 0 A_SpawnItem("DeadImpID17G");
	Stop;
		
	Dead.Explosive_Impact:
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("ThisImpGotFuckedHard");
		TNT1 A 0 A_SpawnItem ("Ploft");
		TNT1 AAAA 0 A_SpawnItem ("Blood");
		Stop;
		
		
	Death.LegInTheAir:
		TNT1 A 0 ThrustThingZ(0,35,0,1);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));		
		ID13 A 1 A_Scream;
		ID17 HI 4;
		ID17 JKLMNNNNNNNNN 4;
		TNT1 A 0 A_SpawnItem("DeadImp_NoLeg");
	Stop;
		
	Crush:
	Death.Stomp:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TROO KL 2;
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 5), 6);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
		Stop;
		
	FatalityMarine:
		TNT1 A 0 A_SetInvulnerable;
		IPFP ABCD 4;
		TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 40, 0, 0);
		IPFP EEF 6;
		
		TNT1 A 0 A_PlaySound("DSFDTHE");
		IPFP GHIJKHIJKLMNOLMNO 8
		{
			doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			A_SpawnProjectile ("PlayerFlyingBlood", 25, 0, random (0, 360), 2, random (0, 160));
		}
		TNT1 A 0 A_TakeInventory("Fatality_Marine",1);
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_UnSetInvulnerable;
		TNT1 A 0 A_SpawnItem ("MarineGotOwnedByImp", 1);
	Goto See;
		
		
	Swim:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Fall;
		TNT1 A 0 A_SpawnItem("ImpFish");
	Stop;







	////////////////////////////////////////////////////////////
	//			backstab from player
	////////////////////////////////////////////////////////////
	death.back_stab: 
		TNT1 A 0
		{
			if(is_melee_player_kill() )
				setstate(curstate+1);
		}
	Goto Death;
		tnt1 a 0
		{
			doomb_monster_fatality_camera(target);
			vel = (0, 0, 0);
		}
		SFIM AB 8;
		tnt1 A 0 A_PlaySound("misc/xdeath4");
		SFIM CD 16;
		tnt1 A 1
		{
			A_SpawnItemEx("DeadImp");
			doomb_destroy_monster_fatality_camera();
		}
	Stop;

		Death.BHFT:
			TNT1 A 0 A_GiveToTarget("ImpFatality3", 1);
		Stop;



		Death.Fatality:
			tnt1 A 0
			{
				doomb_monster_fatality_camera(target);
				A_Pain();
				A_NoBlocking();
			}
			TNT1 A 0 A_Jump(255, "imp_fatality_1", "imp_fatality_2", "imp_fatality_3");

	
	imp_fatality_1:
		FTYI ABB 4;
		FTYI CDEFG 2;
		tnt1 A 0  A_PlaySound("imp/pain", CHAN_AUTO, 1);
		tnt1 A 0 A_SpawnItemEx("FootStep", 0, 0, 40, 0, 0);
		tnt1 A 0 A_PlaySound("CLAP", CHAN_AUTO, 1);
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		FTYI GGGGHHHHHHHHIIJJJJJJJJJJJ 1;
		FTYI K 3;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 A 0 A_SpawnItemEx("FootStep", 0, 25, 30, 0, 0);
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 doomb_spawn_bloodpool();
		FTYI LLLL 1;
		FTYI LMNNN 3;
		FTYI N 9
		{
			A_Givetotarget("HealthBonus",10);
			A_SpawnProjectile ("StompedImp", 1, 0, random (0, 360), 2, random (0, 160));
			doomb_destroy_monster_fatality_camera();
		}
	stop;
	
	
	imp_fatality_2:
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 50, 0, random (0, 360), 2, random (50, 130));
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 60, 0, random (0, 360), 2, random (0, 160));
		FTBI BC 2;
		tnt1 A 0 A_PlaySound("imp/die", CHAN_AUTO, 1);
		FTBI D 25;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 50, 0, random (0, 360), 2, random (50, 130));
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 60, 0, random (0, 360), 2, random (0, 160));
		FTBI EF 3;
		FTBI G 25
		{
			A_Givetotarget("HealthBonus",10);
			A_SpawnItem("ImpMessyCorpse");
			doomb_destroy_monster_fatality_camera();
		}
	stop;	
	
	imp_fatality_3:
		FTCI AB 2;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 A_PlaySound("grunt/pain", CHAN_AUTO, 1);
		tnt1 A 0 A_PlaySound("player/cyborg/fist", CHAN_AUTO, 1);
		FTCI CDE 2;
		FTCI E 6;
		
		FTCI FGG 4;
	imp_punch_loop:
		FTCI H 2;
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		TNT1 A 0 Radius_Quake (1, 4, 0, 1, 0);
		tnt1 A 0 A_PlaySound("grunt/pain", CHAN_AUTO, 1);
		tnt1 A 0 A_PlaySound("player/cyborg/fist", CHAN_AUTO, 1);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0
		{
			actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 5 ) );
			if(a)
				a.scale = (0.45, 0.45);
		}
		tnt1 A 0 A_SpawnProjectile ("Teeth", 15, 0, random (0, 360), 2, random (0, 160));
		FTCI I 5;
		FTCI H 2;
		FTCI G 3;
		tnt1 a 0 a_jump(40, 1);
	loop;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		FTCI LJ 10;
		tnt1 A 0
		{
			A_Givetotarget("HealthBonus",10);
			A_SpawnItem("impfacesorapedomgthisiscruel");
			doomb_destroy_monster_fatality_camera();
		}
	stop;
	
}

}





CLASS ImpFatality : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS ImpFatality2 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}

CLASS ImpFatality3 : Inventory { 
Default {
	
	inventory.maxamount 1;
}
}





		


CLASS FireBall_ : doomb_boolet_base
{ 
	Default {
	DamageType "Fire";
	Radius 4;
	Height 10;
	Speed 14;
	FastSpeed 18;
	Damagefunction (random(15,20));
	PROJECTILE;
	+THRUGHOST;
	RenderStyle "Add";
	Alpha 1;
	SeeSound "imp/attack";
	DeathSound "imp/shotx";
	Decal "Scorch";
	Scale 1.6;
}
States
{
	Spawn:
		FR7X AB 1 BRIGHT
		{
			if(waterlevel > 1)
			{
				A_SpawnItem("FireballFlare",0,0);
				A_SpawnProjectile ("BUBULZ", 0, 0, random (0, 360), 2, random (0, 180));
			}

			else if(frame == 1)
			{
				actor a = doomb_show_effect("FlameTrails", (prev-pos), (0, 0, frandom(0, 1) ), (0.35, 0) );
				if(a)
				{
					a.setstate(a.curstate+2);
					//a.sprite = self.sprite;
					//a.frame = self.frame;
				}
				doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
			}
		}
	Loop;

	Death:
		TNT1 A 0 {if(waterlevel > 1) spawn("UnderwaterExplosion", pos:self.pos); }
		EXPL AAAAAA 0 doomb_show_effect("SmallFireTrail", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
		TNT1 A 0 doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
		TNT1 AAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		FRFX CDEFGHIJKLMNOP 1 BRIGHT {spawn("RedFlare", pos);}
		TNT1 AAAA 19 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
	Stop;
}
}
