CLASS ImpFish: doomb_Imp { 
Default {
	
	+FLOAT;
	+NOGRAVITY;
	Height 56;
	Speed 4;
}
States
{
	Spawn:
		IUSA B 1 A_Look();
		Goto Spawn;
	See:
		
		TNT1 A 0 ThrustThingZ(0,-2,0,1);
		IUSA AAAABBBBCCCCDDDD 2
		{
			if(waterlevel < 1)
				setstatelabel("JumpOutOfWater");
			A_Chase();
			A_Recoil(-1);
		}
	Loop;
	
	JumpOutOfWater:
		TROO A 1 A_Facetarget();
		TNT1 A 0 A_Recoil(-6);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		TROO A 4;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("doomb_Imp");
		Stop;
		
	Melee:
		IUSA A 4 A_FaceTarget();
		TNT1 A 0 A_JumpIf(waterlevel < 1, "JumpOutOfWater");
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (-6);
		IUSA B 6;
		TNT1 A 0 A_JumpIf(waterlevel < 1, "JumpOutOfWater");
		TNT1 A 0 A_FaceTarget();
		IUSA E 6;
		TNT1 AA 0 doomb_cheap_melee_attack(80, random(5, 10), "ImpFatalityMarine");
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(waterlevel < 1, "JumpOutOfWater");
		IUSA B 6;
		Goto See;
		
	Missile:
		TNT1 A 0 A_JumpIfCloser(150, "Melee");
		
		IUSA A 4 A_FaceTarget();
		TNT1 A 0 A_JumpIfCloser(170, "Melee");
		TNT1 A 0 A_Playsound ("IMPCHARG");
		TNT1 A 0 A_SpawnProjectile ("BUBULZ", 35, 30, random (0, 40), 2, random (0, 160));
		IUSA AAAAA 2
		{
			A_FaceTarget();
			A_SpawnProjectile ("BUBULZ", 25, 30, random (0, 40), 2, random (0, 160));
		}
		
		IUSA B 2 A_FaceTarget();
		IUSA E 6 A_SpawnProjectile("FireBall_", 34, 0, 0, 0);
		TNT1 A 0 A_JumpIf(waterlevel < 1, "JumpOutOfWater");
		IUSA B 4;
		Goto See;
		
		
		
	Death.Explosive_Impact:
	XDeath:
		TNT1 A 0 a_fall;
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece_dark", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (0, 360));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		Goto FloatXDEath;
		
	FloatXDeath:
		ID17 C 5 A_CheckFloor ("Dead.Explosive_Impact");
		TNT1 A 0 A_SpawnProjectile ("Underblood1", 32, 0, random (0, 360), 2, random (0, 160));
		BLUD C 0 ThrustThingZ (0,7,1,0);
		ID17 DEF 5 A_CheckFloor ("Dead.Explosive_Impact");
		TNT1 A 0 A_SpawnProjectile ("Underblood1", 32, 0, random (0, 360), 2, random (0, 160));
		BLUD C 0 ThrustThingZ (0,7,1,0);
		Loop;
		
	Dead.Explosive_Impact:
		TNT1 A 0 A_SpawnItem ("ThisImpGotFuckedHard");
		Stop;
		
	Pain:
		TROO C 2;
		TROO C 2 A_Pain();
		Goto See;

	Death:
	Death.Cut:
	Death.Cutless:
	Death.Shotgun:
		TNT1 A 0 A_NOBlocking();
		TNT1 A 0 A_Scream();
		TROO VW 4;
	Sink:
		TROO X 4 A_CheckFloor ("Deadz");
	Loop;
		
	Deadz:
		TROO YYYYYYY 8 A_SpawnProjectile ("Underblood1", 32, 0, random (0, 360), 2, random (0, 160));
		TROO Y -1;
	Loop;
		
}
}


CLASS XDeathImpArm: XDeathArm1 { 
Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		HND4 ABCDEFGH 4 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	Loop;
	
	Death.plasma:
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160));
	Stop;
	
	Death:
		HND4 X 1 A_SpawnItem("Gib_ImpArm",0,0,0,1);
	Stop;
}
}

CLASS Gib_ImpArm: LimbBase { 
Default {
	
	Scale 1.1;
}
States
{
	Spawn:
		HND4 X 1900;
		Loop;
	Death.plasma:
	Death.Fire:
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160));
	Stop;
	
	Death:    
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_SpawnProjectile ("GibImpHand", 0, 0, random (0, 180), 2, random (0, 180));
		TNT1 A 0 A_SpawnProjectile ("GibImpArmPart", 0, 0, random (0, 180), 2, random (0, 180));
		Stop;
		
	Death.Kick:
	Death.Punch:
		HND4 AA 1 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 5, 0, random (170, 190), 2, random (20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		HND4 ABCDEFGH 3;
		Goto Spawn;
		
	Death.Explosive_Impact:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		HND4 X 5;
		HND4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Goto Landz;
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_ImpArm");
		Stop;
		
}

}
CLASS GibImpArmPart: TinyGib { 
Default {
	
	Scale 1.1;
}
States
{
	Spawn:
		HND4 Z 1;
		Loop;
	Death:
		HND4 Z 1;
		Loop;
		
}

}
CLASS GibImpHand: TinyGib { 
Default {
	
	Scale 0.8;
}
States
{
	Spawn:
		HND4 Y 1;
		Loop;
	Death:
		HND4 Y 1;
		Loop;
		
}

}

CLASS XDeathHalfImpUpperPart32 : ACTOR { 
Default {
	
	Radius 2;
	Height 2;
	Scale 1.1;
	Speed 6;
	Gravity 0.3;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	wallbouncefactor 0.2;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
}
States
{
	Spawn:
		//TNT1 A 0 A_SpawnItem("Brutal_LiquidBlood",0,0,0,1)
		HND4 IJKLMNOPQ 3 A_SpawnProjectile("Brutal_LiquidBlood",0,0,0,1);
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		TNT1 AAA 0 A_spawnItem("Blood", 0, 10);
		HND4 Q 1;
		HND4 Q -1;
		Stop;
}
}



CLASS XDeathImpLeg: XDeathArm1 { 
Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEG4 ABCDEFGH 5 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		Loop;
	Death:
		LEG4 I 1;
		LEG4 I 0 A_SpawnItem("Gib_ImpLeg");
		Stop;
		
}
}

CLASS Gib_ImpLeg: LimbBase { 
Default {
	
	Scale 1.1;
}
States
{
	Spawn:
		LEG4 I 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		Loop;
	Death.plasma:
	Death.Fire:
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		Stop;
	Death:    
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_SpawnProjectile ("GibImpPaw", 0, 0, random (0, 180), 2, random (0, 180));
		TNT1 A 0 A_SpawnProjectile ("GibImpLegPart", 0, 0, random (0, 180), 2, random (0, 180));
		Stop;
	Death.Kick:
	Death.Punch:
		LEG4 A 1 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 5, 0, random (170, 190), 2, random (20, 40));
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		LEG4 ABCDEFGH 2;
		Goto Spawn;
		
	Death.Explosive_Impact:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		LEG4 A 5;
		LEG4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Goto Landz;
	Landz:
		XDT5 I 0 A_SpawnItem("Gib_ImpLeg");
		Stop;
		
}

}
CLASS GibImpLegPart: TinyGib { 
Default {
	
	Scale 1.1;
}
States
{
	Spawn:
		LEG4 Z 1;
		Loop;
	Death:
		LEG4 Z 1;
		Loop;
		
}

}
CLASS GibImpPaw: TinyGib { 
Default {
	
	Scale 1.1;
}
States
{
	Spawn:
		LEG4 Y 1;
		Loop;
	Death:
		LEG4 Y 1;
		Loop;
		
}

}


CLASS XDeathHalfImp : doomb_body_base
{ 
Default {
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TROG K 12 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		TROG K 0 A_SpawnItem("HalfImpGib",0,0,0,1);
		Stop;
}
}


CLASS HalfImpGib: BigGibBase { 
Default {
	
}
States
{
	Spawn:
		TROG K 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		Loop   ;
		
	Death:  
		TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 12, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 12, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfImpUpperPart32", 12, 0, random (0, 360), 2, random (10, 60));
		TNT1 A 0 doomb_Meat_Death_Small();
		Stop;
		
}

}


CLASS XDeathBurnedImpLeg : doomb_body_base { 
Default {
	
	Radius 8;
	Height 8;
	Speed 5;
	Mass 6;
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
}
States
{
	Spawn:
		CARB F 10 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		Loop;
	Death:
		CARB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 14 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		CARB F -1;
		Stop;
}
}

CLASS ImpTorso : doomb_body_base { 
Default {
	
	Radius 0;
	Height 16;
	Scale 1.1;
	Mass 20;
	Health 50;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+FLOORCLIP;
	+MOVEWITHSECTOR;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
}
States
{
	Spawn:
		BLUD C 0 A_Recoil (3);
		BLUD C 0 ThrustThing (random(0,255),random(1,5));
		BLUD C 0 ThrustThingZ (0,random(0,50),random(0,1),0);
		TNT1 A 0 A_SetInvulnerable();
		GORX B 10;
		TNT1 A 0 A_UnSetInvulnerable();
		Goto Dead;
		
	Dead:
		GORX B 10;
		Loop;
	Death:
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 0, 0, random (0, 180), 2, random (0, 180));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 0, 0, random (0, 180), 2, random (0, 180));
		TNT1 A 0;
		Stop;
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 doomb_spawn_burned_flesh();
	EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
	TNT1 A 0;
	Stop;
Raise:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("TeleportFog");
	TNT1 A 0 A_SpawnItem("doomb_Imp");
	stop;
	
}
}










CLASS DeadImp : CurbstompedMarine Replaces DeadDoomImp { 
Default {

Radius 12;
Height 12;
+SHOOTABLE;
+NOTELEPORT;
+MOVEWITHSECTOR;
+CORPSE;
-SOLID;
+FLOORCLIP;
+THRUACTORS;
+SHOOTABLE;
damagefactor "Crush", 50.0;
Mass 1000;
Health 100;
damagefactor "Blood", 0.0;
damagefactor "Trample", 0.0;
damagefactor "Melee", 10.0;
damagefactor "Fatality", 10.0;
damagefactor "Kick", 10.0;
damagefactor "Explosive_Impact", 10.0;
}
States
{
Spawn:
	TROO M -1;
	Stop;
Raise:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem("TeleportFog");
	TNT1 A 0 A_SpawnItem("doomb_Imp");
	stop;
	
Death:
	TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg", 5);
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 doomb_Meat_Death_Small();
Stop;
	
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 doomb_spawn_burned_flesh();
	EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
	TNT1 A 0;
Stop;
XDeath:
	TNT1 A 0 A_SpawnItem("GibsZ");
	TNT1 AA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
Stop;

}

}
CLASS DeadImp_NoArm: DeadImp { 
Default {

Health 200;
}
States
{
Spawn:
	TR08 E -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImp_NoArmNoHead");
		Stop;
		
}

}


CLASS DeadImp_NoArmNoHead: DeadImp_NoArm { 
Default {

Health 200;
}
States
{
Spawn:
	TR08 G -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_Rip_Guts();
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem("DeadImp_Half");
		Stop;
}

}
CLASS DeadImp_NoLeg: DeadImp { 
Default {

Health 200;
}
States
{
	Spawn:
		TR09 E -1;
	Stop;
	Death:
		TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_NoBlocking;
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfImp", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_Meat_Death_Small();
	Stop;
	
}

}

CLASS DeadImp_NoHead: DeadImp { 
Default {

Health 200;
}
States
{
Spawn:
	TROH E -1;
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem("DeadImp_NoArmNoHead");
		Stop;
}

}
CLASS DeadImp_MinorHeadDeadFront: DeadImp { 
Default {

Health 200;
}
States
{
Spawn:
	TROH O -1;
	Stop;
	
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
	
}

}		 
CLASS DeadImpMinorHeadShot: DeadImp { 
Default {

Health 200;
}
States
{
Spawn:
	TROO Y -1;
	Stop;
	
}

}
CLASS DeadImp_Half: DeadImp { 
Default {

Health 200;
}
States
{
Spawn:
	TROG H -1;
	Stop;
	Death:
	TNT1 AA 0 A_SpawnProjectile ("XDeathImpLeg", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 doomb_Meat_Death_Small();
	TNT1 A 0 A_NoBlocking;
	Stop;
	
}

}		  
CLASS impfacesorapedomgthisiscruel: DeadImp_Half { 
Default {

Health 200;
}
States
{
Spawn:
	FTCI K -1;
	Stop;
	
	Death:
	TNT1 A 0 A_NoBlocking;
	TNT1 A 0 doomb_Rip_Guts();
	TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathHalfImpUpperPart32", 32, 0, random (0, 360), 2, random (10, 60));
	TNT1 A 0 doomb_Meat_Death_Small();
	TNT1 A 0 A_SpawnItem("DeadImp_Half");
	Stop;

	}
	}		  


CLASS StompedImp: impfacesorapedomgthisiscruel { 
Default {
-solid
Health 200;
}
States
{
Spawn:
	FTYI Z -1;
	Stop;
}

}


CLASS DeadImp_NoStomach: DeadImp { 
Default {

Health 200;
}
States
{
Spawn:
	IMPC I -1;
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
}

}


CLASS DeadImp_NoStomachNoHead: DeadImp { 
Default {

Health 200;
}
States
{
Spawn:
	IMPC L -1;
	Stop;
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 10);
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
		Stop;
}

}		
	
CLASS DeadImp_BaronFatality: DeadImp { 
Default {

-SHOOTABLE
Health 200;
}
States
{
Spawn:
	3HF2 K -1;
	Stop ;
	}
	}		


CLASS ImpMessyCorpse: CurbstompedMarine { 
Default {

Health 200;
}
States
{
Spawn:
	FTBI H -1;
	Stop;
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 A_SpawnProjectile ("XDeathImpArm", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeathImpLeg", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 A_SpawnItem("DeadImp_NoHead");
	Stop;
}

}		
	


CLASS DeadImp_Slumped: ImpTorso { 
Default {
	+NOPAIN
	Health 200;
	Height 22+15;
	doomb_monster_base.head_starting_position 22;
	Radius 8;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(6);
		BR94 A 6;
		TNT1 A 0 A_JumpIf(vel.x == 0 && vel.y == 0, "LayDown");
		BR94 A 16;
	LayDown:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("DeadImp");
	Stop;
	
	XDeath:
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ImpXDeath");
		Stop;
		
	Death.Headshot:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItemEx("ImpHeadExplode", 0, 0, 22);
		TNT1 A 0 A_SpawnItem("DeadImp_Slumped_NoHead");
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AA 0 A_SpawnProjectile ("XDeathImpArm", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnItemEx("ImpHeadExplode", 0, 0, 22);
	Stop;
		
}

}		
	
CLASS DeadImp_Slumped_NoHead: ImpTorso { 
Default {
	
	+NOPAIN;
	Height 22;
}
States
{
	Spawn:
		TNT1 A 0;
		BR94 B 100;
		Loop ;
	XDeath:
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("ImpXDeath");
		Stop;
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
		TNT1 AA 0 A_SpawnProjectile ("XDeathImpArm", 40, 0, random (0, 360), 2, random (30, 90));
		//TNT1 A 0 A_SpawnItem("DeadImpJustLegsAreLeft")
		Stop;
		
}

}		


CLASS DeadImpTR06K: DeadImp { 
Default {
	
}
States
{
	Spawn:
		TR06 K -1;
		Stop;
		
	Death:
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 A_SpawnItem("DeadImp_Half");
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfImp", 40, 0, random (0, 360), 2, random (0, 160));
		Stop;
		
}

}		
	

CLASS DeadImpTR06V: DeadImp { 
Default {
	
}
States
{
	Spawn:
		TR06 V -1;
		Stop;
		
	Death:
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 A_SpawnItem("DeadImp_Half");
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfImp", 40, 0, random (0, 360), 2, random (0, 160));
		Stop;
}
}	


CLASS DeadImpTRO3E: DeadImp { 
Default {
	
}
States
{
	Spawn:
		TRO3 E -1;
		Stop;
		
	Death:
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfImpUpperPart32", 32, 0, random (0, 360), 2, random (10, 60));
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 A_SpawnItem("DeadImp_Half");
		TNT1 A 0 A_NoBlocking();
		Stop;
		
}
}	


CLASS DeadImpTRO4E: DeadImp { 
Default {
	
}
States
{
	Spawn:
		TRO4 E -1;
		Stop;
		
	Death:
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfImpUpperPart32", 32, 0, random (0, 360), 2, random (10, 60));
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 A_SpawnItem("DeadImp_Half");
		TNT1 A 0 A_NoBlocking();
		Stop;
}
}	


CLASS DeadImpIZD1H: DeadImp_Half { 
Default {
	
}
States
{
	Spawn:
		IZD1 H -1;
		Stop;
}
}	


CLASS DeadImpID17G: DeadImp { 
Default {
	
}
States
{
	Spawn:
		ID17 G -1;
		Stop;
		
	Death:
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfImpUpperPart32", 32, 0, random (0, 360), 2, random (10, 60));
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_Rip_Guts();
		TNT1 A 0 A_NoBlocking();
		Stop;
}
}	
	
	

CLASS DeadImpIZD3D: DeadImp { 
States
{
	Spawn:
		IZD3 D -1;
		Stop;
		
	Death:
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfImpUpperPart32", 32, 0, random (0, 360), 2, random (10, 60));
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 AA 0 A_SpawnProjectile ("XDeathImpLeg", 5, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_Rip_Guts();
		TNT1 A 0 A_NoBlocking();
		Stop;
}
}			


CLASS FrozenImp : ACTOR { 
Default {
	
	Health 60;
	Radius 16;
	Height 52;
	+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
	
}
States
{
	Spawn:
		FZD4 A 200;
		FZD4 A 2;
		TNT1 A 0 A_PlaySound("ICEBRK1");
		FZD4 A 50;
		FZD4 B 2;
		FZD4 A 50;
		FZD4 B 2;
		FZD4 A 50;
		FZD4 B 2;
		FZD4 A 25;
		FZD4 B 2;
		FZD4 A 25;
		FZD4 B 2;
		FZD4 A 10;
		FZD4 B 2;
		FZD4 A 10;
		FZD4 B 2;
		FZD4 A 10;
		FZD4 BABABA 2;
	Death.Fire:
	TNT1 A 0 A_ChangeCountFlags(false, false);
		TNT1 A 0 A_PlaySound ("DSBOTTLE");
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_spawnItem("doomb_Imp");
		Stop;
	Death:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_PlaySound ("DSBOTTLE");
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("MuchBlood", 48, 0, random (0, 360), 2, random (0, 160));
		FZD4 C 300;
		FZD4 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
		Stop;
}
}



CLASS DyingImp : doomb_body_base { 
Default {
	Radius 16;
	Height 28;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	+SHOOTABLE;
	-SOLID;
	+THRUACTORS;
	
	+FLOORCLIP;
	damagefactor "Crush", 50.0;
	Scale 1.0;
}
States
{
	Spawn:
	Suffer:
		
		TRO2 DDDDDDEEEEE 2 A_SpawnProjectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		TRO2 E 2 A_Pain();
		tnt1 a 0 a_jump(180, "spawn");
	Death:
		TRO2 FG 8;
		TNT1 A 1 A_SpawnItem ("DeadImp_NoStomach", 5);
		Stop;
		
	Death.Headshot:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		IMPC JJJJJJJJJJJJJJJJJJJ 2 A_SpawnProjectile ("Brutal_LiquidBlood", 32, 0, random (0, 360), 2, random (0, 45));
		IMPC KKKK 2 A_SpawnProjectile ("Brutal_LiquidBlood", 16, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		IMPC LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_SpawnItem("DeadImp_NoStomachNoHead");
		Stop;
		
Death.Plasma: Death.Plasma2:
	TNT1 A 0;
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	XBRN AA 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
	TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
	
	TNT1 A 0 A_SpawnProjectile ("XDeathBurnedImpArm", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathBurnedImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 doomb_spawn_burned_flesh();
	
	XBRN BB 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
	TNT1 A 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
	XBRN CC 2 BRIGHT A_SpawnItem("BlueFlare",0,43);
	XBRN DEF 4 BRIGHT;
	TNT1 A 0;
	Stop;
	
Death.Fire:
	TNT1 A 0;
	TNT1 A 0 A_Scream();
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	TROO JJJJKKKKLLLL 2 doomb_show_effect("FlameTrails", (0, 0, 30), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
	TNT1 A 0 A_Playsound("props/redfire");
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 doomb_show_effect("FlameTrails", (0, 0, 15), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
	BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 doomb_show_effect("AltSmoke", (0, 0, 15), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
	BOSB E -1;
	Stop;
	
Death.cut:
Death.cutless:
	TNT1 O 0 A_Jump(230, 2);
	Goto Death;
	TNT1 A 0 A_XScream();
	TNT1 O 0 A_NoBlocking();
	TNT1 A 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
	TROG A 2;

	TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathHalfImp", 40, 0, random (0, 360), 2, random (0, 160));

	TROG AAA 4 doomb_spawn_big_blood(30);
	TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	TROG BCDEFGH 8;
	TNT1 A 1 A_SpawnItem ("DeadImp_Half", 5);
	//TROG H -1
	Stop;
	
	
Death.SSG:
	//TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160))
	TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 A 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
	TNT1 AA 0 A_SpawnProjectile ("XDeathImpArm", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 A_SpawnProjectile ("SuperGoreSpawner", 22, 0, random (170, 190), 2, random (0, 15));
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	IZD1 EFGH 6;
	IZD1 H -1;
	TNT1 A 0 doomb_spawn_bloodpool();
	Stop;
	
Death.Fatality:
Death.punch:
	TNT1 A 0 A_NoBlocking();
	TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
	TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	Stop;
	
Death.Shotgun:
Death.Blast:
Death.Railgun:
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
	TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
	TRO3 A 6 A_Stop();
	TNT1 A 0 doomb_spawn_bloodpool();
	TRO3 BBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (30, 60));
	TRO3 CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (10, 40));
	TRO3 DD 3 A_SpawnProjectile ("Brutal_LiquidBlood", 6, 0, random (0, 360), 2, random (30, 60));
	TRO3 E -1;
	Stop;
}
}


CLASS BurningImpRunning : doomb_body_base
{ 
Default {
	Radius 12;
	Height 56;
	Speed 5;
	Scale 0.85;
	Health 100;
	GibHealth 25;
	damagefactor "Fire", 0.0;
	damagefactor "Explosive_Impact", 10.0;
	MONSTER;
	-COUNTKILL;
	+NOICEDEATH;
	+FRIENDLY;
	+FLOORCLIP;
	+SHOOTABLE;
	+NOBLOCKMONST;
	+DONTSPLASH;
	
	Gravity 0.7;
	bloodtype "DeadBlood";
	Obituary "%o was near someone in flames.";
	MaxDropOffHeight 6000;
	
	Mass 999999;
	
}
States
{
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
	Suffer:
		TRBR AAA 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_PlaySound("imp/pain");
		tnt1 B 0 doomb_show_effect("BurnParticles", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		tnt1 B 0 doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );

		TRBR BBB 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		tnt1 B 0 doomb_show_effect("BurnParticles", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		tnt1 B 0 doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
		TRBR CCC 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		tnt1 B 0 doomb_show_effect("BurnParticles", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		tnt1 B 0 doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
		TRBR DDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		tnt1 B 0 doomb_show_effect("BurnParticles", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		tnt1 B 0 doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
		TNT1 A 0 A_GiveInventory("PoorGuyBurningLife", 1);
		TNT1 A 0 doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
		TNT1 A 0 A_JumpIfInventory("PoorGuyBurningLife", 8, "Death");
		Loop;
	Death:
	Death.Explosive_Impact:
		TNT1 A 0 A_Fall;
		TNT1 A 0 {bSHOOTABLE = false;}
		TNT1 A 0 {bSOLID = false;}
		TNT1 A 0 {bNOTARGET = true;}
		IZD4 CCCDDD 2 doomb_show_effect("BurnParticles", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		tnt1 a 0 a_jump(200, "death");
		TROO LLLL 2 doomb_show_effect("FlameTrails", velocity: (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 doomb_show_effect("FlameTrails", velocity: (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 20 doomb_show_effect("AltSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		BOSB F -1;
Stop;
}
}















////////////////////////////////////////////////////////////////////////////////////////////////
//minigun death fatality
////////////////////////////////////////////////////////////////////////////////////////////////


CLASS BrutalizedImp1 : doomb_body_base { 
Default {
	Radius 16;
	Height 50;
	Health 300;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+NORADIUSDMG;
	+nopain
	Scale 1.0;
}

States
{
	Spawn:
		TNT1 A 0 A_Recoil(2);
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		IZD1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1
		{
			if(health <= 200)
				setstatelabel("no_head");
		}
		//one hand death
		TNT1 A 0 A_SpawnItem ("BrutalizedImpStop");
	Stop;
		
	//BrutalizedImp2
	no_head:
		TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("head_piece_dark", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_Recoil(2);
		IZD1 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1
		{
			if(health <= 100)
				setstatelabel("just_torso");
		}
		//no hand and head
		TNT1 A 0 A_SpawnItem ("BrutalizedImpStop2");
	Stop;

	//BrutalizedImp3
	just_torso:
		IZD1 C 35;//just die here
		TNT1 A 0 A_SpawnItem ("BrutalizedImpStop3");
	Stop;
		
	Death:
		TNT1 A 0 A_Recoil(2);
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 40, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("Brutal_LiquidBlood", 44, 0, random (0, 360), 2, random (0, 50));
		TNT1 A 0 doomb_spawn_bloodpool();
		IZD1 EFGH 6;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 A 0 A_SpawnItem("DeadImpIZD1H");
	Stop;





	Death.Fatality:
	Death.punch:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	Stop;

	Death.SSG:
	XDeath:
		TNT1 A 0 A_SpawnProjectile ("ImpXDeath", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;
}

}


CLASS BrutalizedImpStop: CurbstompedMarine { 
Default {

damagefactor "Blood", 0.0;
damagefactor "Trample", 0.0;
damagefactor "Melee", 10.0;
damagefactor "Fatality", 10.0;
damagefactor "Kick", 10.0;
}
States
{
	Spawn:
		IZD2 ABC 5 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
		TNT1 A 0 A_SpawnItem("DeadImpIZD3D");
	Stop;
	
	Death.Kick:
	Death.punch:
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 1 A_SpawnItem ("BrutalizedImpStop", 5);
	Stop;
	
	
}

}

CLASS BrutalizedImpStop2: BrutalizedImpStop { 
States
{
	Spawn:
		IZD4 AB 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem("DeadImpIZD3D");
	Stop;
		
	Death.Kick:
	Death.punch:
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		IZD4 A 7;
		TNT1 A 1 A_SpawnItem ("BrutalizedImpStop2", 5);
	Stop;
	
}

}

CLASS BrutalizedImpStop3: BrutalizedImpStop { 
States
{
	Spawn:
		IZD3 AB 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem("DeadImpIZD1H");
	Stop;
		
	Death.Kick:
	Death.punch:
		TNT1 A 0;
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 A_FaceTarget();
		IZD3 B 7;
		TNT1 A 1 A_SpawnItem ("BrutalizedImpStop3", 5);
	Stop;
}

}	   

////////////////////////////////////////////////////////////////////////////////////////////////
//minigun death fatality end
////////////////////////////////////////////////////////////////////////////////////////////////

























CLASS ThisImpGotFuckedHard: DeadImpID17G { 
Default {

Health 200;
}
}
	


CLASS ImpBrutalizedWithNoLeg : ACTOR { 
Default {


Radius 16;
Height 50;
Health 20;
PainSound "grunt/pain";
PainChance 255;
Mass 999999;
-SOLID;
+SHOOTABLE;
Scale 1.0;
}
States
{

Spawn:
	TR09 A 30;
	Goto DieNow;
	
DieNow:
	TR09 BC 8;
	TR09 DE 8;
	TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg");
	Stop;
	
	
	
Death:
	TNT1 A 0;
	TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("head_piece_dark", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
	TNT1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
	TNT1 AAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 35, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 AA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 ThrustThingZ(0,30,0,1);
	ID17 ABCDEF 5;
	TNT1 A 0 A_SpawnItem ("CrueltyBonus5Armor");
	TNT1 A 0 A_SpawnItem ("ThisImpGotFuckedHard");
	Stop;
	
}

}








CLASS DyingImpNoArm : doomb_body_base { 
Default {
	Radius 16;
	Height 32+18;
	doomb_monster_base.head_starting_position 32;

	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+GHOST;
	+THRUGHOST;
	Scale 1.0;
}
States
{
	Spawn:
		TR08 B 1;
	Suffer:
		TR08 BBBCC 4 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, - random (0, 45));
		TR08 C 5 A_Pain();
		tnt1 a 0 a_jump(222, "suffer");
		tnt1 a 0 a_die();
	Death:
		TR08 D 8;
		TNT1 A 0 A_SpawnItem ("DeadImp_NoArm", 5);
	Stop;
		
	Death.Headshot:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TR08 F 8;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 A 0 A_SpawnItem ("DeadImp_NoArmNoHead", 1);
	Stop;
		
	XDeath:
	Death.Explosive_impact:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 42, 0, random (170, 190), 2, random (10, 60));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 42, 0, random (170, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 42, 0, random (170, 190), 2, random (10, 60));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 42, 0, random (170, 190), 2, random (10, 60));
		TNT1 A 1 A_SpawnProjectile ("ImpXDeath", 0, 0, random (0, 360), 2, random (0, 160));
	Stop;
		
	Death.SSG:
	Death.Shotgun:
	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 32, 0, random (150, 210), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Xdeath3", 16, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (30, 90));
		TROG A 6 A_Stop();
		TNT1 A 0 doomb_spawn_bloodpool();
		TROG BBBBBBBBBB 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (30, 60));
		TROG CCC 3 A_SpawnProjectile ("Brutal_LiquidBlood", 26, 0, random (0, 360), 2, random (10, 40));
		TROG DD 3 A_SpawnProjectile ("Brutal_LiquidBlood", 6, 0, random (0, 360), 2, random (30, 60));
		TNT1 A 0 A_SpawnItem("DeadImp_Half");
	Stop;
}
}


CLASS XDeathImpHead: XDeathChaingunguyHead { 
States
{
	Spawn:
	Spawn1:
		TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XHE4 AB 3;
		XHE4 CDEFGH 3;
		Loop;
	Death:
		TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
		XHE4 E 1;
		XHE4 E 1 A_SpawnItem("ImpHead",0,0,0,1);
		Stop;
}
}


CLASS XDeathImpHeadBeheaded: XDeathImpHead { 
Default {
	
	Speed 5;
	Gravity 0.5;
}
}

CLASS XDeathImpHeadOnXDeath: XDeathImpHead { 
Default {
	
}
States
{
	Spawn:
		TNT1 A 1;
		TNT1 A 0 A_jump(96, "ExplodeOnAir");
		Goto Spawn1;
	ExplodeOnAir:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode");
		Stop;
		
}

}
CLASS ImpHead : LimbBase { 
Default {
	
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("Brutal_BloodSpot");
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
	Spawn1:
		XHE4 C 1;
		XHE4 C -1;
		Stop;
	Spawn2:
		XHE4 G 1;
		XHE4 G -1;
		Stop;
	Spawn3:
		XHE4 H 1;
		XHE4 H -1;
		Stop;
	Death:
		TNT1 A 0;
		TNT1 A 0 A_SpawnItem("ImpHeadExplode");
		Stop;
	Death.punch:
	Death.Kick:
		XHE4 EE 1 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile ("XDeathImpHead", 5, 0, random (170, 190), 2, random (20, 40));
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
		TNT1 A 20;
		Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE4 ABCDEFGH 2;
		Goto Spawn;
		
	Death.Explosive_Impact:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XHE4 ABCDEFGH 3;
		XDT5 I 0 A_SpawnItem("ImpHead");
		Stop;
}

}

CLASS DyingImpNoLeg : doomb_body_base { 
Default {


Radius 16;
Height 32;
Health 50;
PainSound "imp/pain";
PainChance 255;
Mass 999999;
-SOLID;
+SHOOTABLE;
Scale 1.0;
}
States
{
Spawn:
	IMPC E 1;
	TNT1 A 0;
	TNT1 A 0 A_Jump(32, "Colapse");
	Goto Suffer;
Suffer:
	
	
	TR09 DD 4 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 D 5 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 FF 4 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 F 5 A_Pain();
	
	
	TR09 DD 4 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 D 5 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 FF 4 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 F 5 A_Pain();
	
	
	TR09 DD 4 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 D 5 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 FF 4 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 F 5 A_Pain();
	
	
	
	TR09 DD 4 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 D 5 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 FF 4 A_SpawnProjectile ("Brutal_LiquidBlood", 12, 0, random (0, 360), 2, random (0, 45));
	
	TR09 F 5 A_Pain();
	
	Goto Colapse;
Death:
	TNT1 A 0 A_PlaySound("imp/death");
	TR09 G 8;
	TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg", 5);
	Stop;
	
Colapse:
	TR09 H 8;
	TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg", 5);
	Stop;
	
Death.Headshot:
	TNT1 A 0 A_PlaySound("misc/xdeath4");
	TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 30);
	TNT1 A 0 A_XScream();
	TNT1 A 0 A_NoBlocking();
	TR09 I 8;
	TNT1 A 0 A_SpawnItem ("DeadImp_Noleg", 1);
	TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
	Stop;
}
}




CLASS ImpSaciLol: DyingImpNoLeg { 
Default {

+GHOST;
+THRUGHOST;
-COUNTKILL;
Speed 4;
Height 48;
}
States
{

	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound ("imp/pain");
		ZL3E ABC 3;
		TNT1 A 0 doomb_blood_dying();
		ZL3E DDDD 1 a_wander();
	Suffer:
		TNT1 A 0 A_PlaySound ("imp/pain");
		TR09 AB 6;
		tnt1 a 0 a_jump(200, "suffer");
		TR09 C 3 A_NoBlocking();
		TNT1 A 0 A_SpawnItem ("DyingImpNoLeg");
	Stop;

	Death.Headshot:
		TNT1 A 0 A_PlaySound("misc/xdeath");
		TNT1 A 0 A_SpawnItem("ImpHeadExplode", 0, 50);
		ZL3E EFG 7;
		TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg");
	Stop;

	Death:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("imp/death");
		ZL3E HIJ 7;
		TNT1 A 0 A_SpawnItem ("DeadImp_NoLeg");
	Stop;
}
}

CLASS ImpDyingOfBloodLoss: doomb_Imp { 
Default {

Radius 16;
Height 28;
Health 10;
+NOPAIN;
-COUNTKILL;
+SHOOTABLE;
}
States
{
Spawn:
	TROD E 1;
	TROD EFEFEFEFEFEFEFEFEFEFEFEF 10;
Colapse:
	TNT1 A 0;
	TNT1 A 0 A_NoBlocking();
	TROD GHIJ 5;
	TNT1 A 0 A_SpawnItem ("DeadImpBloodLoss", 5);
	Stop;
	
Death:
	TNT1 A 0;
	Goto DeathNoGuts;
	
Death.Shotgun:
	TNT1 A 0;
	TNT1 A 0 A_JumpIfCloser(150, "Death.Shotgunontheface");
	Goto DeathNoGuts;
	
}
}

CLASS DeadImpBloodLoss: CurbstompedMarine { 
Default {

Health 200;
}
States
{
Spawn:
	TROD J -1;
	Stop;
Death:
	TNT1 A 0 doomb_Meat_Death_Small();
	TNT1 A 0 A_SpawnItem("DeadImp_Half");
	TNT1 A 0 A_NoBlocking();
	TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 15, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
	TNT1 A 0 A_SpawnProjectile ("XDeathHalfImp", 40, 0, random (0, 360), 2, random (0, 160));
	Stop;
}
}		

CLASS ImpXDeath : doomb_body_base { 
Default {
	
	Radius 1;
	Height 1;
	Scale 0.8;
	Speed 0;
	Mass 1;
	
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+MISSILE;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+NOGRAVITY;
	+NOCLIP;
	+DONTSPLASH;
}
States
{
	Spawn:
		tnt1 a 0 A_Explode(3,600, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AAAAAAAAAAAAAAA 0 A_SpawnProjectile ("WallRedBlood", 40, 0, random (0, 360), 2, random (-15, 15));
		TNT1 AAAAAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 0, 0, random (0, 360), 2, random (50, 130));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfImpUpperPart32", 32, 0, random (0, 360), 2, random (10, 60));
		TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan1", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathOrgan2", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath2", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath3", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece2", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece1", 15, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAA 0 A_SpawnProjectile ("Instestin", 24, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathImpHeadOnXDeath", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_bloodpool();
		
		TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
		Stop;
		
	LowBlood:
		TNT1 A 2;
		Stop;
	LotsOfBlood:
		TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
		TNT1 AAAAAA 0 A_SpawnProjectile ("SuperGoreSpawner", 64, 0, random (0, 360), 2, random (20, 40));
		Stop;
	AbsurdBlood:
		TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
		TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("SuperGoreMist", 24, 0, random (0, 360), 2, random (30, 90));
		TNT1 AAAAAAAA 0 A_SpawnProjectile ("SuperGoreSpawner", 64, 0, random (0, 360), 2, random (20, 40));
		Stop;
}
}

