CLASS ImpFish: doomb_Imp { 
Default {
	
	+FLOAT;
	+NOGRAVITY;
	Height 56;
	Speed 4;
}
States
{
	Spawn:
		IUSA B 1 A_Look();
	loop;

	See:
		TNT1 A 0 ThrustThingZ(0,-2,0,1);
		IUSA AAAABBBBCCCCDDDD 2
		{
			if(waterlevel < 1)
				setstatelabel("JumpOutOfWater");
			A_Chase();
			A_Recoil(-1);
		}
	Loop;
	
	JumpOutOfWater:
		TROO A 1 A_Facetarget();
		TNT1 A 0 A_Recoil(-6);
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		TROO A 4;
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("doomb_Imp");
	Stop;
		
	Melee:
		IUSA A 4 A_FaceTarget();
		TNT1 A 0 A_JumpIf(waterlevel < 1, "JumpOutOfWater");
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 A_Recoil (-6);
		IUSA B 6;
		TNT1 A 0 A_JumpIf(waterlevel < 1, "JumpOutOfWater");
		TNT1 A 0 A_FaceTarget();
		IUSA E 6;
		TNT1 AA 0 doomb_cheap_melee_attack(80, random(5, 10), "ImpFatalityMarine");
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(waterlevel < 1, "JumpOutOfWater");
		IUSA B 6;
	Goto See;
		
	Missile:
		TNT1 A 0 A_JumpIfCloser(150, "Melee");
		IUSA A 4 A_FaceTarget();
		TNT1 A 0 A_JumpIfCloser(170, "Melee");
		TNT1 A 0 A_Playsound ("IMPCHARG");
		TNT1 A 0 A_SpawnProjectile ("BUBULZ", 35, 30, random (0, 40), 2, random (0, 160));
		IUSA AAAAA 2
		{
			A_FaceTarget();
			A_SpawnProjectile ("BUBULZ", 25, 30, random (0, 40), 2, random (0, 160));
		}
		
		IUSA B 2 A_FaceTarget();
		IUSA E 6 A_SpawnProjectile("doomb_imp_fireball", 34, 0, 0, 0);
		TNT1 A 0 A_JumpIf(waterlevel < 1, "JumpOutOfWater");
		IUSA B 4;
	Goto See;
		
		
		
	Death.Explosive_Impact:
	XDeath:
		TNT1 A 0 a_fall;
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("eye", "spawn", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece_dark", "spawn", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", "spawn", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 AAAAAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 50), doomb_random_velocity(5) );

		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAAAAA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_blood_mist('doomb_non_interactive_blood', 'blood_mist', times:6);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathImpLeg", "spawn", (0, 0, 32), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
	FloatXDeath:
		ID17 C 5 A_CheckFloor ("Dead.Explosive_Impact");
		TNT1 A 0 doomb_for_khorne("Underblood1", "spawn", (0, 0, 32), doomb_random_velocity(5));
		tnt1 a 0 ThrustThingZ (0,7,1,0);
		ID17 DEF 5 A_CheckFloor ("Dead.Explosive_Impact");
		TNT1 A 0 doomb_for_khorne("Underblood1", "spawn", (0, 0, 32), doomb_random_velocity(5));
		tnt1 a 0 ThrustThingZ (0,7,1,0);
	Loop;
		
	Dead.Explosive_Impact:
		TNT1 A 0 doomb_severed_limb("DeadImpID17G", limb_ignore_cvar: true);
	Stop;
		
	Pain:
		TROO C 2;
		TROO C 2 A_Pain();
	Goto See;

	Death:
	Death.Cut:
	Death.Cutless:
	Death.Shotgun:
		TNT1 A 0 A_NOBlocking();
		TNT1 A 0 A_Scream();
		TROO VW 4;
	Sink:
		TROO X 4 A_CheckFloor ("Deadz");
	Loop;
		
	Deadz:
		TROO YYYYYYY 8 doomb_for_khorne("Underblood1", "spawn", (0, 0, 32), doomb_random_velocity(5));
		TROO Y -1;
	Loop;
}

}


CLASS XDeathImpArm: XDeathArm1 { 
Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		HND4 ABCDEFGH 4 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	Loop;
	
	Death.plasma:
		TNT1 A 0 doomb_severed_limb("XDeathBurnedImpArm", "spawn", (0, 0, 32), doomb_random_velocity(3) );
	Stop;
	
	Death:
		HND4 X 1 doomb_severed_limb("Gib_ImpArm");
	Stop;
}
}

CLASS Gib_ImpArm: LimbBase
{
States
{
	Spawn:
		HND4 X 1900;
	Loop;
	
	Death.plasma:
	Death.Fire:
		TNT1 A 0 doomb_severed_limb("XDeathBurnedImpArm", "spawn", (0, 0, 32), doomb_random_velocity(3) );
	Stop;
	
	Death:    
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_severed_limb("GibImpHand", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("GibImpArmPart", "spawn", (0, 0, 2), doomb_random_velocity(3) );
	Stop;
		
	Pain:
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		HND4 ABCDEFGH 3;
	Goto Spawn;
		
	Death.Explosive_Impact:
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		HND4 X 5;
		HND4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Landz:
		tnt1 a 0 doomb_severed_limb("Gib_ImpArm");
	Stop;
		
}

}
CLASS GibImpArmPart: TinyGib
{

States
{
	Spawn:
		HND4 Z 1;
	Loop;

	Death:
		HND4 Z 1;
	Loop;
		
}

}

CLASS GibImpHand: TinyGib
{

States
{
	Spawn:
		HND4 Y 1;
	Loop;

	Death:
		HND4 Y 1;
	Loop;
		
}

}

CLASS XDeathHalfImpUpperPart32 : doomb_body_base
{ 
Default
{
	Radius 2;
	Height 2;
	Scale 1.1;
	Speed 6;
	Gravity 0.3;
	Mass 4;
	Decal "BrutalBloodSplat";
	BounceFactor 0.2;
	wallbouncefactor 0.2;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
}

States
{
	Spawn:
		HND4 IJKLMNOPQ 3 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	Loop;
	
	Death:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		TNT1 AAA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 10) );
		HND4 Q -1;
	Stop;
}

}



CLASS XDeathImpLeg: XDeathArm1 { 
Default {
	
	Scale 1.1;
	Speed 8;
	Gravity 0.4;
	BounceFactor 0.4;
}
States
{
	Spawn:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		LEG4 ABCDEFGH 5 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		Loop;
	Death:
		LEG4 I 1;
		LEG4 I 0 doomb_severed_limb("Gib_ImpLeg");
	Stop;
}

}

CLASS Gib_ImpLeg: LimbBase
{
States
{
	Spawn:
		LEG4 I 1900 doomb_spawn_bloodpool(BPS_SMALL);
	Loop;

	Death.plasma:
	Death.Fire:
		TNT1 A 0 doomb_severed_limb("XDeathBurnedImpLeg", "spawn", (0, 0, 2), doomb_random_velocity(3) );
	Stop;
	
	Death:    
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_severed_limb("GibImpPaw", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("GibImpLegPart", "spawn", (0, 0, 2), doomb_random_velocity(3) );
	Stop;

	Death.Kick:
	Death.Punch:
		LEG4 A 1 A_FaceTarget;
		TNT1 A 0 doomb_severed_limb("XDeathImpLeg", "spawn", (0, 0, 2), doomb_random_velocity(3) );
	Stop;
		
	Pain:
		TNT1 A 0;
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		LEG4 ABCDEFGH 2;
	Goto Spawn;
		
	Death.Explosive_Impact:
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		LEG4 A 5;
		LEG4 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
	Landz:
		tnt1 a 0 doomb_severed_limb("Gib_ImpLeg");
	Stop;
}

}

CLASS GibImpLegPart: TinyGib
{

States
{
	Spawn:
		LEG4 Z 1;
	Loop;
	
	Death:
		LEG4 Z 1;
	Loop;
}

}

CLASS GibImpPaw: TinyGib
{

States
{
	Spawn:
		LEG4 Y 1;
	Loop;
	
	Death:
		LEG4 Y 1;
	Loop;
}

}


CLASS XDeathHalfImp : doomb_body_base
{ 
Default
{
	Radius 8;
	Height 8;
	Speed 7;
	Mass 8;
	BounceFactor 0.2;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
	DeathSound "misc/xdeath1";
	Decal "BrutalBloodSplat";
}

States
{
	Spawn:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TROG K 12 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	Loop;
	
	Death:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		TROG K 0 doomb_severed_limb("HalfImpGib", limb_ignore_cvar: true);
	Stop;
}

}


CLASS HalfImpGib: BigGibBase
{
States
{
	Spawn:
		TROG K 1900 doomb_spawn_bloodpool(BPS_SMALL);
	Loop;
		
	Death:  
		TNT1 A 0 doomb_severed_limb("XDeathImpHead", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfImpUpperPart32", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 A 0 doomb_Meat_Death_Small();
	Stop;
}

}


CLASS XDeathBurnedImpLeg : doomb_body_base { 
Default {
	
	Radius 8;
	Height 8;
	Speed 5;
	Mass 6;
	BounceFactor 0.5;
	+DOOMBOUNCE;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+DONTSPLASH;
	+MOVEWITHSECTOR;
}
States
{
	Spawn:
		CARB F 10 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		Loop;
	Death:
		CARB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 14 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
		CARB F -1;
		Stop;
}

}

CLASS ImpTorso : doomb_body_base { 
Default {
	Radius 0;
	Height 16;
	Scale 1.1;
	Mass 20;
	Health 50;
	+SHOOTABLE;
	-SOLID;
	+NOTELEPORT;
	+FLOORCLIP;
	+MOVEWITHSECTOR;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
}

States
{
	Spawn:
		tnt1 a 0 A_Recoil (3);
		tnt1 a 0 ThrustThing (random(0,255),random(1,5));
		tnt1 a 0 ThrustThingZ (0,random(0,50),random(0,1),0);
		GORX B -1;
	stop;

	Death:
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
	Stop;

	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_spawn_burned_flesh();
		EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
	Stop;

	Raise:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_SpawnItem("doomb_Imp");
	stop;
}

}










CLASS DeadImp : CurbstompedMarine
{
Default {

	Radius 12;
	Height 12;
	+SHOOTABLE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	-SOLID;
	+FLOORCLIP;
	+THRUACTORS;
	+SHOOTABLE;
	damagefactor "Crush", 50.0;
	Mass 1000;
	Health 200;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	damagefactor "Melee", 10.0;
	damagefactor "Fatality", 10.0;
	damagefactor "Kick", 10.0;
	damagefactor "Explosive_Impact", 10.0;
}
States
{
	Spawn:
		TROO M -1;
	Stop;

	Raise:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_SpawnItem("TeleportFog");
		TNT1 A 0 A_SpawnItem("doomb_Imp");
	stop;
	
	Death:
		TNT1 A 0 doomb_severed_limb("XDeathImpLeg", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("DeadImp_NoLeg", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 doomb_Meat_Death_Small();
	Stop;
	
	Death.Plasma: Death.Plasma2:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_spawn_burned_flesh();
		EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
	Stop;

	XDeath:
		TNT1 A 0 doomb_severed_limb("GibsZ");
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
	Stop;
}

}

CLASS DeadImp_NoArm: DeadImp
{
States
{
	Spawn:
		TR08 E -1;
	Stop;
	
	Death:
		TNT1 A 0 doomb_severed_limb("ImpHeadExplode", "spawn", (0, 0, 10) );
		TNT1 A 0 doomb_severed_limb("DeadImp_NoArmNoHead", "spawn", limb_ignore_cvar: true);
	Stop;
}

}


CLASS DeadImp_NoArmNoHead: DeadImp_NoArm { 
States
{
	Spawn:
		TR08 G -1;
	Stop;
	
	Death:
		TNT1 A 0 doomb_Rip_Guts();
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("DeadImp_Half");
	Stop;
}

}

CLASS DeadImp_NoLeg: DeadImp
{
States
{
	Spawn:
		TR09 E -1;
	Stop;

	Death:
		TNT1 A 0 doomb_severed_limb("XDeathImpLeg", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 AAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfImp", "spawn", (0, 0, 40), doomb_random_velocity(3) );
		TNT1 A 0 doomb_Meat_Death_Small();
	Stop;
}

}

CLASS DeadImp_NoHead: DeadImp
{
States
{
	Spawn:
		TROH E -1;
	Stop;

	Death:
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("DeadImp_NoArmNoHead");
	Stop;
}

}

CLASS DeadImp_MinorHeadDeadFront: DeadImp
{
States
{
	Spawn:
		TROH O -1;
	Stop;
	
	Death:
		TNT1 A 0 doomb_severed_limb("ImpHeadExplode", "spawn", (0, 0, 10) );
		TNT1 A 0 doomb_severed_limb("DeadImp_NoHead");
	Stop;
}

}

CLASS DeadImpMinorHeadShot: DeadImp
{
States
{
	Spawn:
		TROO Y -1;
	Stop;
}

}


CLASS DeadImp_Half: DeadImp { 
States
{
	Spawn:
		TROG H -1;
	Stop;

	Death:
		TNT1 AA 0 doomb_severed_limb("XDeathImpLeg", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 AA 0 doomb_Meat_Death_Small();
	Stop;
}

}

CLASS impfacesorapedomgthisiscruel: DeadImp_Half
{

States
{
	Spawn:
		FTCI K -1;
	Stop;
	
	Death:
		TNT1 A 0 doomb_Rip_Guts();
		TNT1 A 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfImpUpperPart32", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("DeadImp_Half");
	Stop;
}

}		  


CLASS StompedImp: impfacesorapedomgthisiscruel
{
States
{
	Spawn:
		FTYI Z -1;
	Stop;
}

}


CLASS DeadImp_NoStomach: DeadImp
{
States
{
	Spawn:
		IMPC I -1;
	Stop;

	Death:
		TNT1 A 0 doomb_severed_limb("ImpHeadExplode", "spawn", (0, 0, 10) );
		TNT1 A 0 doomb_severed_limb("DeadImp_NoHead");
	Stop;
}

}


CLASS DeadImp_NoStomachNoHead: DeadImp
{
States
{
	Spawn:
		IMPC L -1;
	Stop;

	Death:
		TNT1 A 0 doomb_severed_limb("ImpHeadExplode", "spawn", (0, 0, 10) );
		TNT1 A 0 doomb_severed_limb("DeadImp_NoHead");
	Stop;
}

}		
	
CLASS DeadImp_BaronFatality: DeadImp
{
States
{
	Spawn:
		3HF2 K -1;
	Stop;
}

}		


CLASS ImpMessyCorpse: CurbstompedMarine
{

States
{
	Spawn:
		FTBI H -1;
	Stop;

	Death:
		TNT1 AA 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 AA 0 doomb_severed_limb("XDeathImpLeg", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("DeadImp_NoHead");
	Stop;
}

}		
	


CLASS DeadImp_Slumped: ImpTorso { 
Default {
	+NOPAIN
	Health 200;
	Height 40;
	doomb_monster_base.head_starting_position 22;
	Radius 8;
}
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Recoil(6);
		BR94 A 6;
		TNT1 A 0 A_JumpIf(vel == (0, 0, 0), "LayDown");
		BR94 A 16;
	LayDown:
		TNT1 A 0 doomb_severed_limb("DeadImp");
	Stop;
	
	XDeath:
	Death.Explosive_Impact:
		TNT1 A 0 doomb_severed_limb("ImpXDeath");
	Stop;
		
	Death.Headshot:
		TNT1 A 0 doomb_severed_limb("ImpHeadExplode", "spawn", (0, 0, 22) );
		TNT1 A 0 doomb_severed_limb("DeadImp_Slumped_NoHead");
	Stop;
		
	Death:
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, 40) );
		TNT1 AA 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 40), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("ImpHeadExplode", "spawn", (0, 0, 22) );
	Stop;
		
}

}		
	
CLASS DeadImp_Slumped_NoHead: ImpTorso
{
Default {
	
	+NOPAIN;
	Height 22;
}

States
{
	Spawn:
		BR94 B 100;
	Loop ;

	XDeath:
	Death.Explosive_Impact:
		TNT1 A 0 doomb_severed_limb("ImpXDeath");
	stop;
	
	Death:
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, 40) );
		TNT1 AA 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 44), doomb_random_velocity(3) );
	Stop;
}

}		


CLASS DeadImpTR06K: DeadImp
{
States
{
	Spawn:
		TR06 K -1;
	Stop;
		
	Death:
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("DeadImp_Half");
		TNT1 AAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfImp", "spawn", (0, 0, 40), doomb_random_velocity(3) );
	Stop;
		
}

}		
	

CLASS DeadImpTRO3E: DeadImp { 
States
{
	Spawn:
		TRO3 E -1;
	Stop;
		
	Death:
		TNT1 A 0 doomb_severed_limb("XDeathHalfImpUpperPart32", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("DeadImp_Half");
	Stop;
}

}	


CLASS DeadImpTRO4E: DeadImp { 
States
{
	Spawn:
		TRO4 E -1;
		Stop;
		
	Death:
		TNT1 A 0 doomb_severed_limb("XDeathHalfImpUpperPart32", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("DeadImp_Half");
	Stop;
}

}	


CLASS DeadImpIZD1H: DeadImp_Half { 
States
{
	Spawn:
		IZD1 H -1;
		Stop;
}

}	


CLASS DeadImpID17G: DeadImp { 
States
{
	Spawn:
		ID17 G -1;
		Stop;
		
	Death:
		TNT1 A 0 doomb_severed_limb("XDeathHalfImpUpperPart32", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("DeadImp_Half");
		TNT1 A 0 doomb_Rip_Guts();
	Stop;
}

}	
	
	

CLASS DeadImpIZD3D: DeadImp { 
States
{
	Spawn:
		IZD3 D -1;
		Stop;
		
	Death:
		TNT1 A 0 doomb_severed_limb("XDeathHalfImpUpperPart32", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("DeadImp_Half");
		TNT1 A 0 doomb_Rip_Guts();
		TNT1 AA 0 doomb_severed_limb("XDeathImpLeg", "spawn", (0, 0, 2), doomb_random_velocity(3) );
	Stop;
}

}			



CLASS DyingImp : doomb_body_base
{
Default
{
	Radius 16;
	Height 28;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	damagefactor "Crush", 50.0;
	Scale 1.0;

	+SHOOTABLE;
	-SOLID;
	+THRUACTORS;
	+FLOORCLIP;
}

States
{
	Spawn:
	Suffer:
		TRO2 DDDDDDEEEEE 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TRO2 E 2 A_Pain();
		tnt1 a 0 a_jump(180, "spawn");
	Death:
		TRO2 FG 8;
		TNT1 A 1 doomb_severed_limb("DeadImp_NoStomach");
		Stop;
		
	Death.Headshot:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 doomb_severed_limb("ImpHeadExplode", "spawn", (0, 0, 30) );
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		IMPC JJJJJJJJJJJJJJJJJJJ 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		IMPC KKKK 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		IMPC LLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLLL 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_severed_limb("DeadImp_NoStomachNoHead");
	Stop;
		
	Death.Plasma:
	Death.Plasma2:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 doomb_severed_limb("XDeathBurnedImpArm", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("XDeathBurnedImpLeg", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		XBRN AABBCC 2 BRIGHT
		{
			doomb_flare_base.doomb_attach_flare(self, "BlueFlare", (0, 0, 43) );
			doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 30), doomb_random_velocity(5) );
		}
		TNT1 A 0 doomb_spawn_burned_flesh();
		TNT1 A 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 30), doomb_random_velocity(5) );
		XBRN DEF 4 BRIGHT;
	Stop;

	Death.Fire:
		TNT1 A 0;
		TNT1 A 0 A_Scream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		TROO JJJJKKKKLLLL 2 doomb_show_effect("FlameTrails", (0, 0, 30), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 doomb_show_effect("FlameTrails", (0, 0, 15), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 10 doomb_show_effect("AltSmoke", (0, 0, 15), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		BOSB E -1;
	Stop;
	
	Death.cut:
	Death.cutless:
		TNT1 O 0 A_Jump(230, 2);
	Goto Death;
		TNT1 A 0 A_XScream();
		TNT1 O 0 A_NoBlocking();
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TROG A 2;
		TNT1 AAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfImp", "spawn", (0, 0, 42), doomb_random_velocity(3) );

		TROG AAA 4 doomb_spawn_big_blood(30);
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		TROG BCDEFGH 8;
		TNT1 A 1 doomb_severed_limb("DeadImp_Half");
	Stop;
	
	
	Death.SSG:
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AA 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("XDeathImpHead", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 A 0 doomb_blood_mist('doomb_non_interactive_blood', 'blood_mist', times:6);
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		IZD1 EFGH 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		IZD1 H -1;
	Stop;
	
	Death.Fatality:
	Death.punch:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	Stop;
	
	Death.Shotgun:
	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_XScream();
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AA 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("XDeathImpHead", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, 40) );
		TRO3 A 6 A_Stop();
		TNT1 A 0 doomb_spawn_bloodpool();
		TRO3 BBBBBBBBBB 3 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TRO3 CCC 3 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TRO3 DD 3 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TRO3 E -1;
	Stop;
}

}


CLASS BurningImpRunning : doomb_body_base
{ 
Default
{
	Radius 12;
	Height 56;
	Speed 5;
	Scale 0.85;
	Health 100;
	GibHealth 25;
	damagefactor "Fire", 0.0;
	damagefactor "Explosive_Impact", 10.0;
	MONSTER;
	-COUNTKILL;
	+NOICEDEATH;
	+FRIENDLY;
	+FLOORCLIP;
	+SHOOTABLE;
	+NOBLOCKMONST;
	+DONTSPLASH;
	
	Gravity 0.7;
	
	Obituary "%o was near someone in flames.";
	MaxDropOffHeight 6000;
	
	Mass 999999;
}

States
{
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");
	Suffer:
		TRBR ABCD 3 BRIGHT
		{
			A_Wander();
			A_Recoil(-1);
			A_PlaySound("imp/pain");
			doomb_show_effect("BurnParticles", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
		}
		tnt1 a 0 A_PlaySound("imp/pain");

		TNT1 A 0 A_Jump(random(0, 10) <= 1, "Death");
	Loop;
	
	Death:
	Death.Explosive_Impact:
		TNT1 A 0 A_Fall;
		TNT1 A 0 {bSHOOTABLE = false;}
		TNT1 A 0 {bSOLID = false;}
		TNT1 A 0 {bNOTARGET = true;}
		IZD4 CCCDDD 2 doomb_show_effect("BurnParticles", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		tnt1 a 0 a_jump(200, "death");
		TROO LLLL 2 doomb_show_effect("FlameTrails", velocity: (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_Playsound("props/redfire");
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 2 doomb_show_effect("FlameTrails", velocity: (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		BOSB FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF 20 doomb_show_effect("AltSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		BOSB F -1;
	Stop;
}

}















////////////////////////////////////////////////////////////////////////////////////////////////
//minigun death fatality
////////////////////////////////////////////////////////////////////////////////////////////////
CLASS BrutalizedImp1 : doomb_body_base { 
Default {
	Radius 16;
	Height 50;
	Health 300;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+NORADIUSDMG;
	+nopain
	Scale 1.0;
}

States
{
	Spawn:
		TNT1 A 0 A_Recoil(2);
		TNT1 A 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		IZD1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 1
		{
			if(health <= 200)
				setstatelabel("no_head");
		}
		//one hand death
		TNT1 A 0 doomb_severed_limb("BrutalizedImpStop");
	Stop;
		
	//BrutalizedImp2
	no_head:
		TNT1 A 0 doomb_severed_limb("jaw", "spawn", (0, 0, 50), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("eye", "spawn", (0, 0, 50), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("head_piece_dark", "spawn", (0, 0, 50), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 50), doomb_random_velocity(3) );
		
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAAAAAAAAA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 A_Recoil(2);
		IZD1 BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 1
		{
			if(health <= 100)
				setstatelabel("just_torso");
		}
		//no hand and head
		TNT1 A 0 doomb_severed_limb("BrutalizedImpStop2");
	Stop;

	//BrutalizedImp3
	just_torso:
		IZD1 C 35;//just die here
		TNT1 A 0 doomb_severed_limb("BrutalizedImpStop3");
	Stop;
		
	Death:
		TNT1 A 0 A_Recoil(2);
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_spawn_bloodpool();
		IZD1 EFGH 6;
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		TNT1 A 0 doomb_severed_limb("DeadImpIZD1H");
	Stop;





	Death.Fatality:
	Death.punch:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_GiveToTarget("HasImpShield", 1);
		TNT1 A 0 A_GiveToTarget("GotMeatShield", 1);
	Stop;

	death.Explosive_Impact:
	Death.SSG:
	XDeath:
		TNT1 A 0 doomb_severed_limb("ImpXDeath", "spawn", (0, 0, 2), doomb_random_velocity(3) );
	Stop;
}

}


CLASS BrutalizedImpStop: CurbstompedMarine { 
Default
{
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
	damagefactor "Melee", 10.0;
	damagefactor "Fatality", 10.0;
	damagefactor "Kick", 10.0;
}

States
{
	Spawn:
		IZD2 ABC 5 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_severed_limb("DeadImpIZD3D");
	Stop;
	
	Death.Kick:
	Death.punch:
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		TNT1 A 1 doomb_severed_limb("BrutalizedImpStop");
	Stop;
	
	
}

}

CLASS BrutalizedImpStop2: BrutalizedImpStop { 
States
{
	Spawn:
		IZD4 AB 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadImpIZD3D");
	Stop;
		
	Death.Kick:
	Death.punch:
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		IZD4 A 7;
		TNT1 A 1 doomb_severed_limb("BrutalizedImpStop2");
	Stop;
	
}

}

CLASS BrutalizedImpStop3: BrutalizedImpStop { 
States
{
	Spawn:
		IZD3 AB 6;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadImpIZD1H");
	Stop;
		
	Death.Kick:
	Death.punch:
		TNT1 A 0 ThrustThingZ(0,15,0,1);
		TNT1 A 0 A_FaceTarget();
		IZD3 B 7;
		TNT1 A 1 doomb_severed_limb("BrutalizedImpStop3");
	Stop;
}

}	   

////////////////////////////////////////////////////////////////////////////////////////////////
//minigun death fatality end
////////////////////////////////////////////////////////////////////////////////////////////////

























	


CLASS ImpBrutalizedWithNoLeg : doomb_body_base
{ 
Default
{
	Radius 16;
	Height 50;
	Health 20;
	PainSound "grunt/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	Scale 1.0;
}

States
{

	Spawn:
		TR09 A 30;
		TR09 BDEC 8;
		TNT1 A 0 doomb_severed_limb("DeadImp_NoLeg");
	Stop;
	
	


	Death:
		TNT1 A 0 doomb_severed_limb("jaw", "spawn", (0, 0, 50), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("eye", "spawn", (0, 0, 50), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("head_piece_dark", "spawn", (0, 0, 50), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 50), doomb_random_velocity(3) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAAAAA 0 doomb_for_khorne("brutal_Blood", "spawn", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 35), doomb_random_velocity(3) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("XDeathImpLeg", "spawn", (0, 0, 35), doomb_random_velocity(3) );
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		ID17 ABCDEF 5;
		TNT1 A 0 A_givetotarget("CrueltyBonus5Armor");
		TNT1 A 0 doomb_severed_limb("DeadImpID17G");
	Stop;
}

}








CLASS DyingImpNoArm : doomb_body_base
{
Default
{
	Radius 16;
	Height 50;
	doomb_monster_base.head_starting_position 32;

	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	+GHOST;
	+THRUGHOST;
	Scale 1.0;
}

States
{
	Spawn:
		TR08 B 1;
	Suffer:
		TR08 BBBCC 4 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TR08 C 5 A_Pain();
		tnt1 a 0 a_jump(222, "suffer");
		tnt1 a 0 a_die();
	Death:
		TR08 D 8;
		TNT1 A 0 doomb_severed_limb("DeadImp_NoArm");
	Stop;
		
	Death.Headshot:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 doomb_severed_limb("ImpHeadExplode", "spawn", (0, 0, 30) );
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TR08 F 8;
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		TNT1 A 0 doomb_severed_limb("DeadImp_NoArmNoHead");
	Stop;
		
	XDeath:
	Death.Explosive_impact:
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_FaceTarget();
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 1 doomb_severed_limb("ImpXDeath", "spawn", (0, 0, 2), doomb_random_velocity(3) );
	Stop;
		
	Death.SSG:
	Death.Shotgun:
	Death.Blast:
	Death.Railgun:
		TNT1 A 0 A_XScream();
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("XDeathImpHead", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 A 0 doomb_severed_limb("XDeathImpArm", "spawn", (0, 0, 32), doomb_random_velocity(3) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, 40) );
		TROG A 6 A_Stop();
		TNT1 A 0 doomb_spawn_bloodpool();
		TROG BBBBBBBBBB 3 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TROG CCC 3 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TROG DD 3 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_severed_limb("DeadImp_Half");
	Stop;
}

}


CLASS XDeathImpHead: XDeathArm1
{
Default {
	Speed 5;
	Gravity 0.5;
}
States
{
	Spawn:
		tnt1 a 0 nodelay
		{
			if(random(0, 10) == 3)
			{
				doomb_severed_limb("ImpHeadExplode");
				destroy();
			}
		}
	Spawn1:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
		TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
		XHE4 AB 3;
		XHE4 CDEFGH 3;
	Loop;
	
	Death:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		XHE4 E 1;
		XHE4 E 1 doomb_severed_limb("ImpHead");
	Stop;
}

}


CLASS ImpHead : LimbBase { 
States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		TNT1 A 0 A_Jump(256, "Spawn1", "Spawn2", "Spawn3");
	Spawn1:
		XHE4 C -1;
	Stop;

	Spawn2:
		XHE4 G -1;
	Stop;

	Spawn3:
		XHE4 H -1;
	Stop;

	Death:
		TNT1 A 0 doomb_severed_limb("ImpHeadExplode");
	Stop;

	Death.punch:
	Death.Kick:
		XHE4 EE 1 A_FaceTarget;
		TNT1 A 0 doomb_severed_limb("XDeathImpHead", "spawn", (0, 0, 2), doomb_random_velocity(3) );
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
	Stop;
		
	Pain:
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		XHE4 ABCDEFGH 2;
	Goto Spawn;
		
	Death.Explosive_Impact:
		TNT1 A 0 ThrustThingZ(0,50,0,1);
		XHE4 ABCDEFGH 3;
		tnt1 a 0 doomb_severed_limb("ImpHead");
	Stop;
}

}

CLASS DyingImpNoLeg : doomb_body_base
{
Default
{
	Radius 16;
	Height 32;
	Health 50;
	PainSound "imp/pain";
	PainChance 255;
	Mass 999999;
	-SOLID;
	+SHOOTABLE;
	Scale 1.0;
}

States
{
	Spawn:
		IMPC E 1;
		TNT1 A 0 A_Jump(32, "Colapse");
	Suffer:
		TR09 DDDFFF 4 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		tnt1 a 0 A_Pain();
		tnt1 a 0 a_jump(50, "death");
	loop;

	
	Death:
		TNT1 A 0 A_PlaySound("imp/death");
		TR09 GH 8;
		TNT1 A 0 doomb_severed_limb("DeadImp_NoLeg");
	Stop;
	
	
	Death.Headshot:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 doomb_severed_limb("ImpHeadExplode", "spawn", (0, 0, 30) );
		TNT1 A 0 A_XScream();
		TNT1 A 0 A_NoBlocking();
		TR09 I 8;
		TNT1 A 0 doomb_severed_limb("DeadImp_Noleg");
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
	Stop;
}
}




CLASS ImpSaciLol: DyingImpNoLeg
{
Default {
	+GHOST;
	+THRUGHOST;
	-COUNTKILL;
	Speed 4;
	Height 48;
}

States
{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound ("imp/pain");
		ZL3E ABC 3;
		TNT1 A 0 doomb_blood_dying();
		ZL3E DDDD 1 a_wander();
	Suffer:
		TNT1 A 0 A_PlaySound ("imp/pain");
		TR09 AB 6;
		tnt1 a 0 a_jump(200, "suffer");
		TNT1 A 0 doomb_severed_limb("DyingImpNoLeg");
	Stop;

	Death.Headshot:
		TNT1 A 0 A_PlaySound("misc/xdeath");
		TNT1 A 0 doomb_severed_limb("ImpHeadExplode", "spawn", (0, 0, 50) );
		ZL3E EFG 7;
		TNT1 A 0 doomb_severed_limb("DeadImp_NoLeg");
	Stop;

	Death:
		TNT1 A 0 A_PlaySound("imp/death");
		ZL3E HIJ 7;
		TNT1 A 0 doomb_severed_limb("DeadImp_NoLeg");
	Stop;
}

}

CLASS ImpDyingOfBloodLoss: doomb_body_base
{
Default
{
	Radius 16;
	Height 28;
	Health 10;
	+NOPAIN;
	-COUNTKILL;
	+SHOOTABLE;
}
States
{
	Spawn:
		TROD E 1;
		TROD EFEFEFEFEFEFEFEFEFEFEFEF 10;
	Colapse:
		TNT1 A 0;
		TNT1 A 0 A_NoBlocking();
		TROD GHIJ 5;
		TNT1 A 0 doomb_severed_limb("DeadImpBloodLoss");
	Stop;
	
	Death:
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 24), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 A 0 doomb_much_blood(30);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		IMPC A 8 A_Scream;
		IMPC B 8 A_NoBlocking;
		IMPC C 8;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DyingImp");
	Stop;
}

}

CLASS DeadImpBloodLoss: CurbstompedMarine
{
Default
{
	Health 200;
}

States
{
	Spawn:
		TROD J -1;
	Stop;

	Death:
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("DeadImp_Half");
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAA 0 doomb_severed_limb("Intestine", "spawn", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_severed_limb("XDeathHalfImp", "spawn", (0, 0, 42), doomb_random_velocity(3) );
	Stop;
}

}