
CLASS PEPart1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Scale 1.5;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		+DOOMBOUNCE;
		+SKYEXPLODE;
		BounceFactor 0.5;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			ID22 A 2 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			ID22 B 2 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			ID22 C 2 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			ID22 D 2 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			Loop;
		Death:
			ID22 F 1;
			ID22 F -1;
			Stop;
			TNT1 A 1;
		Splash:
			TNT1 A 0;
			Stop;
	}
}


CLASS PEPart2 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 16;
		Scale 1.5;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		+DOOMBOUNCE;
		+SKYEXPLODE;
		BounceFactor 0.5;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			ID22 A 2 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 bright A_SpawnItem("YellowFlare",0,2);
			TNT1 A 0 A_SPawnItem("PlasmaSmoke");
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			
			ID22 B 2 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 bright A_SpawnItem("YellowFlare",0,2);
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			
			ID22 C 2 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 bright A_SpawnItem("YellowFlare",0,2);
			TNT1 A 0 A_SPawnItem("PlasmaSmoke");
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			
			ID22 D 2 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 bright A_SpawnItem("YellowFlare",0,2);
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			Loop;
		Death:
			ID22 F 1 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			TNT1 A 0 A_SpawnItem("o_100SmallFireFocusSpawnerz");
			ID22 F -1;
			Stop;
			TNT1 A 1;
		Splash:
			TNT1 A 0;
			Stop;
	}
}

CLASS PEPart2SuperFast: PEPart2 { 
	Default {
		
		Speed 22;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			ID22 A 1 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 bright A_SpawnItem("YellowFlare",0,2);
			
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			
			ID22 B 1 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 bright A_SpawnItem("YellowFlare",0,2);
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			
			ID22 C 1 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 bright A_SpawnItem("YellowFlare",0,2);
			
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			
			ID22 D 1 A_SpawnProjectile("BloodTrails",0,0,180,2);
			TNT1 A 0 bright A_SpawnItem("YellowFlare",0,2);
			TNT1 A 0 A_SpawnProjectile ("SmallFlameTrails", 2, 0, random (0, 360), 2, random (70, 110));
			Loop;
	}
}






CLASS FatalizedPE : ACTOR { 
	Default {
		
		Radius 12;
		Height 18;
		Scale 1.2;
		+SHOOTABLE;
		-SOLID;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		Mass 1000;
		Health 200;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			PA1F U -1;
			Stop;
		Death:
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
	}
	
}		
		


CLASS FrozenPainElemental : ACTOR { 
	Default {
		
		+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
		
		Radius 31;
		Height 56;
		Health 60;
		Scale 1.0;
	}
	States
	{
		Spawn:
			FZDP A 200;
			FZDP A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZDP A 50;
			FZDP B 2;
			FZDP A 50;
			FZDP B 2;
			FZDP A 50;
			FZDP B 2;
			FZDP A 25;
			FZDP B 2;
			FZDP A 25;
			FZDP B 2;
			FZDP A 10;
			FZDP B 2;
			FZDP A 10;
			FZDP B 2;
			FZDP A 10;
			FZDP BABABA 2;
		Death.Fire:
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_spawnItem("PainElemental");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_Explode (220,220);
			TNT1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 0, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0 A_SpawnProjectile ("XDeathBrain1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBrain2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("PEPart1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("PEPart2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("ExplosionParticle2", 0, 0, random (0, 360), 2, random (0, 180));
			EXPL AAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("FireBallExplosion", 6, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 BRIGHT A_PainDie();
			Stop;
	}
}
