
CLASS PEPart1 : doomb_body_base { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Scale 1.5;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		+DOOMBOUNCE;
		+SKYEXPLODE;
		BounceFactor 0.5;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			ID22 ABCD 2
			{
				doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
				doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
				doomb_show_effect("FlameTrails", ( 0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );	
			}
			Loop;
		Death:
			ID22 F 1;
			ID22 F -1;
			Stop;
			TNT1 A 1;
		Splash:
			TNT1 A 0;
			Stop;
	}
}


CLASS PEPart2 : doomb_body_base { 
	Default {
		
		Radius 8;
		Height 8;
		Speed 16;
		Scale 1.5;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		+DOOMBOUNCE;
		+SKYEXPLODE;
		BounceFactor 0.5;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			ID22 ABCD 2
			{
				doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
				A_SpawnItem("YellowFlare",0,2);
				doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("FlameTrails", ( 0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );	
			}
		Loop;

		Death:
			ID22 F 1 A_SpawnItem("Brutal_FlyingBlood",0,5,0,1);
			TNT1 A 0 doomb_show_effect("SmallFireFocus24", (frandom(-0.5, 0.5), frandom(-0.5, 0.5), 0 ) );
			ID22 F -1;
		Stop;

		Splash:
			TNT1 A 0;
			Stop;
	}
}


CLASS XDeathPainElementalNew1 : doomb_body_base { 
	Default {
		
		Radius 8;
		Height 8;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		+dontsplash
		damagetype "Blood";
		Mass 1;
		
		
		Speed 12;
		Gravity 0.4;
		Decal "BrutalBloodSplat";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath4";
	Translation "64:72=133:142", "73:75=13:15", "76:79=236:239";
	Scale 1.1;
	}
    States
    {
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
		CAGI ABCDEFGH 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	Loop;

	Death:
		
		TNT1 A 0;
		TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
		TNT1 A 0 A_CheckFloor("SpawnFloor");
		TNT1 A 0 A_SpawnItemEx ("CeilBloodLauncher",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 doomb_meat_on_ceiling();
		CAGI Q 9009;
		TNT1 A 2;
	Stop;

	SpawnFloor:
		CAGI Q 9009;
		TNT1 A 2;
	Stop;
}
}



CLASS XDeathPainElementalNew2: XDeathPainElementalNew1 { 
	Default {
 
    Speed 12;
	Gravity 0.6;
    Decal "BrutalBloodSplat";
    Scale 1.1;
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
        CAGI IJKLMNOP 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	Loop;

    Death:
		TNT1 A 0;
        TNT1 AAA 0 A_SpawnItem("Blood", 0, 5);
	    TNT1 A 0 A_CheckFloor("SpawnFloor");
		TNT1 A 0 A_SpawnItemEx ("CeilBloodLauncher",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 doomb_meat_on_ceiling();
        CAGI R 9009;
		TNT1 A 2;
	Stop;

	SpawnFloor:
	    CAGI R 9009;
		TNT1 A 2;
	Stop;
}

}

CLASS PEPart2SuperFast: PEPart2 { 
	Default
	{
		Speed 22;
	}
}






CLASS FatalizedPE : ACTOR { 
	Default {
		
		Radius 12;
		Height 18;
		Scale 1.2;
		+SHOOTABLE;
		-SOLID;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		Mass 1000;
		Health 200;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			PA1F U -1;
			Stop;
		Death:
			TNT1 AAA 0 A_SpawnProjectile ("doomb_internal_organs", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("doomb_internal_organs", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("doomb_internal_organs", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("doomb_internal_organs", 5, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
	}
	
}		
		


CLASS FrozenPainElemental : doomb_body_base { 
	Default {
		
		+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
		
		Radius 31;
		Height 56;
		Health 60;
		Scale 1.0;
	}
	States
	{
		Spawn:
			FZDP A 200;
			FZDP A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZDP A 50;
			FZDP B 2;
			FZDP A 50;
			FZDP B 2;
			FZDP A 50;
			FZDP B 2;
			FZDP A 25;
			FZDP B 2;
			FZDP A 25;
			FZDP B 2;
			FZDP A 10;
			FZDP B 2;
			FZDP A 10;
			FZDP B 2;
			FZDP A 10;
			FZDP BABABA 2;
		Death.Fire:
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_spawnItem("PainElemental");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_Explode (220,220);
			TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 5), 6);
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 0, 0, random (0, 360), 2, random (50, 130));
			TNT1 A 0 A_SpawnProjectile ("XDeathBrain1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBrain1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("PEPart1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("PEPart2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			EXPL AAAAAAAAAAAAAAAAA 0 doomb_show_effect("FireBallExplosion", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			TNT1 A 0 BRIGHT A_PainDie();
			Stop;
	}
}
