//All the liquid gore stuff goes here.









































































 






























































//SLOWDOWN
CLASS BloodmistSmall : Bloodmist { 
	Default {
		
		scale    0.45;
		Gravity 0.8;
	}
}


CLASS BloodmistExtraBig : Bloodmist { 
	Default {
		
		scale    1.4;
	}
}


CLASS BloodmistXXBig : Bloodmist { 
	Default {
		
		scale    2.2;
		GRAVITY 0.2;
	}
}







