
CLASS SpiderLeg : doomb_body_base
{ 
	Default {
		
		Radius 8;
		Height 8;
		Speed 12;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+DOOMBOUNCE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath3";
		BounceFactor 0.3;
		BounceCount 3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			XDSL ABCDEFGH 2;
		Loop;
		
		Death:
			XDSL I 9009;
		Stop;
	}
}


CLASS XDeathArachnotronHead : doomb_body_base
{ 
	Default
	{
		Radius 8;
		Height 8;
		Speed 10;
		Scale 1.2;
		Mass 1;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+RIPPER;
		+BLOODLESSIMPACT;
		-DONTSPLASH;
		+THRUGHOST;
		+THRUACTORS;
		+FLOORCLIP;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSuper";
		Mass 1;
		
		Speed 12;
		Gravity 0.9;
		+DONTSPLASH;
		DeathSound "";
		SeeSound "";
		+SKYEXPLODE;
		Decal "";
		Scale 1.0;
	}
	States
	{
		Spawn:
			NAHA ABCDEFGH 4;
		Loop;

		Death:
			tnt1 a 0 a_jump(100, "cleandeath");
			TNT1 A 0 doomb_severed_limb("CrawlingDyingSpider");
		Stop;

		CleanDeath:
			TNT1 AAAAAAAAAAAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 10), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			NAHC IJKLMN 5;
			NAHC N -5;
		Stop;
	}
}






CLASS DeadSpider: CurbstompedMarine { 
	Default {
		
		Radius 0;
		Height 0;
		Scale 1.3;
		+SHOOTABLE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		-SOLID;
		+THRUACTORS;
		damagefactor "Crusher", 50.0;
		Mass 1000;
		Health 100;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			BSPI P -1;
			Stop;
		Raise:
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("TeleportFog");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("doomb_arachnotron");
		Stop;

		Death.Cut:
		Death.Cutless:
		Death:
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		Stop;
	}
	
}
CLASS XDeadSpider: DeadSpider { 
	States
	{
		Spawn:
			XBSP D -1;
		Stop;

		Death:
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		Stop;
}

}

CLASS RapedArachnotron: DeadSpider { 
States
{
	Spawn:
        ARF1 O -1;
	Stop;
	
	Death:
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
	Stop;
}

}		
		
CLASS NoLegsSpider: DeadSpider
{
States
{
	Spawn:
        ARF2 H -1;
	Stop;
}

}		


CLASS SpiderPart1 : doomb_body_base
{
Default
{
    Radius 1;
    Height 8;
    Speed 12;
    Scale 1.3;
	Mass 1;
    +NOBLOCKMAP
	+MISSILE
    +NOTELEPORT
    +MOVEWITHSECTOR
    +CLIENTSIDEONLY
    +RIPPER
    +BLOODLESSIMPACT 
	damagetype "Blood";
    SeeSound "misc/xdeath4";
    DeathSound "misc/xdeath1";
}

States
{
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "null");
        ID22 ABCD 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	Loop;
    
	Death:
        ID22 E 1 doomb_spawn_bloodpool(BPS_SMALL);
        ID22 E -1;
	Stop;
}

}


CLASS SpiderPart2 : doomb_body_base
{
Default {
 
    Radius 1;
    Height 8;
    Speed 12;
    Scale 2.0;
	Mass 1;
    +NOBLOCKMAP
	+MISSILE
    +NOTELEPORT
    +MOVEWITHSECTOR
    +CLIENTSIDEONLY
    +RIPPER
    +BLOODLESSIMPACT 
    +DOOMBOUNCE
	bounceFactor 0.5;
	damagetype "Blood";
	SeeSound "misc/xdeath4";
	DeathSound "misc/xdeath1";
}

States
{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "null");
			ID22 ABCD 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		Loop;

		Death:
			ID22 F 1 doomb_spawn_bloodpool(BPS_SMALL);
			ID22 F -1;
		Stop;
	}
}













CLASS CrawlingDyingSpider : doomb_body_base { 
	Default {
		
		Radius 12;
		Height 24;
		Speed 9;
		Health 100;
		PainSound "grunt/pain";
		damagefactor "Kick", 0.1;
		damagefactor "Melee", 0.1;
		damagefactor "punch", 0.1;
		PainChance "Kick", 255;
		PainChance "punch", 255;
		PainChance 255;
		damagefactor "trample", 2.0;
		+SHOOTABLE;
		+FLOORCLIP;
		//+NOBLOCKMAP
		+LOOKALLAROUND;
		+FRIGHTENED;
		+SOLID;
	}
	States
	{
		
		Spawn:
		See:
			NAHC ABCD 10 A_Chase;
			NAHC A 0 A_Pain;
			TNT1 A 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_random_death("one_death");
		Loop;
			
		death.one_death:
			TNT1 A 0 a_noblocking;
			NAHC EFGH 5;
			NAHC H -1;
		Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 AAAAAAAAAAAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 10), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			NAHC IJKLMN 5;
			NAHC N -5;
		Stop;
			
		Pain.Explosive_Impact:
			TNT1 A 0 ThrustThingZ(0,50,0,1);
		Pain.Kick:
		Pain.punch:
			TNT1 A 0 A_FaceTarget;
			NAHA A 1 A_Pain;
		Fly:
			NAHA ABCDEFGH 3 A_CheckFloor("See");
			tnt1 A 0 A_JumpIf (vel.z == 0, "See");
		Loop;
	}
}
