
CLASS FrozenArachnotron : ACTOR { 
	Default {
		
		+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
		
		Radius 48;
		Height 64;
		Health 60;
		Scale 1.3;
	}
	States
	{
		Spawn:
			FZD8 A 200;
			FZD8 A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZD8 A 50;
			FZD8 B 2;
			FZD8 A 50;
			FZD8 B 2;
			FZD8 A 50;
			FZD8 B 2;
			FZD8 A 25;
			FZD8 B 2;
			FZD8 A 25;
			FZD8 B 2;
			FZD8 A 10;
			FZD8 B 2;
			FZD8 A 10;
			FZD8 B 2;
			FZD8 A 10;
			FZD8 BABABA 2;
		Death.Fire:
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_spawnItem("Arachnotron");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("MuchBlood", 48, 0, random (0, 360), 2, random (0, 160));
			FZD8 C 300;
			FZD8 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
			Stop;
		Death.Freeze:
		Death.Ice:
		Death.Frost:
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_SpawnItem("FrozenArachnotron");
			Stop;
	}
}
