
CLASS FrozenArachnotron : ACTOR { 
	Default {
		
		+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
		
		Radius 48;
		Height 64;
		Health 60;
		Scale 1.3;
	}
	States
	{
		Spawn:
			FZD8 A 200;
			FZD8 A 2;
			TNT1 A 0 A_PlaySound("ICEBRK1");
			FZD8 A 50;
			FZD8 B 2;
			FZD8 A 50;
			FZD8 B 2;
			FZD8 A 50;
			FZD8 B 2;
			FZD8 A 25;
			FZD8 B 2;
			FZD8 A 25;
			FZD8 B 2;
			FZD8 A 10;
			FZD8 B 2;
			FZD8 A 10;
			FZD8 B 2;
			FZD8 A 10;
			FZD8 BABABA 2;
		Death.Fire:
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_spawnItem("Arachnotron");
			Stop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_PlaySound ("DSBOTTLE");
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("Instestin", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("MuchBlood", 48, 0, random (0, 360), 2, random (0, 160));
			FZD8 C 300;
			FZD8 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
			Stop;
		Death.Freeze:
		Death.Ice:
		Death.Frost:
		TNT1 A 0 A_ChangeCountFlags(false, false);
			TNT1 A 0 A_SpawnItem("FrozenArachnotron");
			Stop;
	}
}


CLASS DeadSpider: CurbstompedMarine { 
	Default {
		
		Radius 0;
		Height 0;
		Scale 1.3;
		+SHOOTABLE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		-SOLID;
		+THRUACTORS;
		damagefactor "Crusher", 50.0;
		Mass 1000;
		Health 100;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			BSPI P -1;
			Stop;
		Raise:
			TNT1 A 2 A_SpawnProjectile ("RealFlameTrailsSmall", 6, 0, random (0, 360), 2, random (70, 110));
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 A_SpawnProjectile ("RealFlameTrailsSmall", 6, 0, random (0, 360), 2, random (70, 110));
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 0 A_SpawnItem("TeleportFog");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("Arachnotron1");
			Stop;
		Death.Cut:
		Death.Cutless:
		Death:
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
			Stop;
	}
	
}
CLASS XDeadSpider: DeadSpider { 
	Default {
		Scale 1.0;
		Health 200;
	}
	States
	{
		Spawn:
			XBSP D -1;
			Stop   ;
Death.Cut:        Death.Cutless:        Death:
	TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
	TNT1 AAA 0 A_SpawnProjectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
	Stop;
}

}

CLASS RapedArachnotron: DeadSpider { 
	Default {

 Scale 1.0;
Health 200;
	}
States
{
Spawn:
        ARF1 O -1;
        Stop    ;
       Death.Cut:        Death.Cutless:	        Death:
  	    		 TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AAA 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AAA 0 A_SpawnProjectile ("XDeath3", 5, 0, random (0, 360), 2, random (0, 160));
		 TNT1 AAA 0 A_SpawnProjectile ("XDeath4", 5, 0, random (0, 360), 2, random (0, 160));
		Stop;
}

}		
		
CLASS NoLegsSpider: DeadSpider { 
	Default {

 Scale 1.0;
+NOBLOOD;
Health 999999999999;
	}
States
{
Spawn:
        ARF2 H -1;
        Stop  ;  
     
		}
		}		


CLASS SpiderPart1 : ACTOR { 
	Default {
 
    Radius 1;
    Height 8;
    Speed 12;
    Scale 1.3;
	Mass 1;
    +NOBLOCKMAP
	+MISSILE
    +NOTELEPORT
    +MOVEWITHSECTOR
    +CLIENTSIDEONLY
    +RIPPER
    +BLOODLESSIMPACT 
damagetype "Blood";
    SeeSound "misc/xdeath4";
    DeathSound "misc/xdeath1";
	
	}
    States
    {
    Spawn:
	    TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
        ID22 ABCD 2 A_SpawnProjectile("BloodTrails",0,0,180,2);
        Loop;
    Death:
        ID22 E 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
        ID22 E -1;
        Stop;

     Splash:
        TNT1 A 0;
        Stop;
    }
}


CLASS SpiderPart2 : ACTOR { 
	Default {
 
    Radius 1;
    Height 8;
    Speed 12;
    Scale 2.0;
	Mass 1;
    +NOBLOCKMAP
	+MISSILE
    +NOTELEPORT
    +MOVEWITHSECTOR
    +CLIENTSIDEONLY
    +RIPPER
    +BLOODLESSIMPACT 
    +DOOMBOUNCE
	bounceFactor 0.5;
		damagetype "Blood";
		SeeSound "misc/xdeath4";
		DeathSound "misc/xdeath1";
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			ID22 ABCD 2 A_SpawnProjectile("BloodTrails",0,0,180,2);
			Loop;
		Death:
			ID22 F 1 A_SpawnItem("Brutal_BloodSpot",0,0,0,1);
			ID22 F -1;
			Stop;
			TNT1 A 1;
		Splash:
			TNT1 A 0;
			Stop;
	}
}













CLASS CrawlingDyingSpider : doomb_body_base { 
	Default {
		
		Radius 12;
		Height 24;
		Speed 9;
		Health 100;
		PainSound "grunt/pain";
		damagefactor "Kick", 0.1;
		damagefactor "Melee", 0.1;
		damagefactor "SuperPunch", 0.1;
		damagefactor "SuperKick", 0.1;
		damagefactor "punch", 0.1;
		PainChance "Kick", 255;
		PainChance "SuperKick", 255;
		PainChance "SuperPunch", 255;
		PainChance "punch", 255;
		PainChance 255;
		damagefactor "trample", 2.0;
		+SHOOTABLE;
		+FLOORCLIP;
		//+NOBLOCKMAP
		+LOOKALLAROUND;
		+FRIGHTENED;
		+SOLID;
	}
	States
	{
		
		Spawn:
			NAHC B 1 A_Look;
			Goto See;
		See:
			NAHC ABCD 10 A_Chase;
			NAHC A 0 A_Pain;
			TNT1 A 0 A_SpawnItemEx("Brutal_FlyingBlood", 0, 0, 10, 0, 0);
			
			TNT1 A 0 doomb_random_death("one_death");
			Loop;
			
		death.one_death:
			TNT1 A 0 a_noblocking;
			NAHC EFGH 5;
			NAHC H -1;
			Stop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 AAAAAAAAAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 10, 0, random (0, 360), 2, random (0, 160));
			NAHC IJKLMN 5;
			NAHC N -5;
			Stop;
			
		Pain.SuperPunch:
		Pain.SuperKick:
		Pain.Kick:
		Pain.punch:
			TNT1 A 0 A_FaceTarget;
			NAHA A 1 A_Pain;
			TNT1 A 0 ThrustThing(angle*256/360+128, 5, 0, 0);
		Pain.Explosive_Impact:
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			
			NAHA A 2 A_FaceTarget;
			Goto Fly;
			
		Fly:
			NAHA ABCDEFGH 3 A_CheckFloor("See");
			tnt1 A 0 A_JumpIf (vel.z == 0, "See");
			TNT1 A 0;
			Loop;
			
	}
}
