




CLASS MetalShard1 : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 0.6;
		Speed 7;
		Mass 1;
		gravity 0.5;
		BounceFactor 0.6;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
		
		Scale 0.2;
		Speed 7;
		Gravity 0.5;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			JNK1 ABCDEFGH 3;
			Loop;
			
		Death:
			JNK1 H 200;
			Stop;
	}
}


CLASS MetalShard2: MetalShard1 { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			JNK2 ABCDEFGH 3;
			Loop;
			
		Death:
			JNK2 H 200;
			Stop;
	}
}


CLASS MetalShard3: MetalShard1 { 
	Default {
		
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			JNK3 ABCDEFGH 3;
			Loop;
			
		Death:
			JNK3 H 200;
			Stop;
	}
}


CLASS DyingRevenant : doomb_body_base
{ 
	Default {
		Radius 16;
		Height 60;
		Health 40;
		Mass 999999;
		-SOLID;
		+SHOOTABLE;
		Scale 1.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
	}
	States
	{
		Spawn:
			FRVX A 1;
			Goto Suffer;
		Suffer:
			FRVX AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 4 doomb_spawn_big_blood(40);
			Goto Death;
		Death:
			FRVX B 8;
			FRVX C -1;
			Stop;
		XDeath:
			TNT1 A 0 A_SpawnProjectile ("SkeletonXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			Stop;
	}
}











CLASS RevenantPiece : ACTOR { 
	Default {
		
		Radius 2;
		Height 2;
		Speed 7;
		Mass 3;
		BounceFactor 0.4;
		BounceCount 4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+THRUACTORS;
		Scale 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 Thing_ChangeTID(0,394);
			TNT1 A 0 A_Jump(128,9);
			SPIC ABCDEFGH 2;
			wait;
			SPIC HGFEDCBA 2;
			wait;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Jump(128,2);
			SPIC A 401;
			Stop;
			SPIC E 1;
			SPIC E 401;
			Stop;
	}
}


CLASS RevenantDust: RevenantPiece { 
	Default {
		
		Speed 10;
		BounceFactor 0.3;
		Scale 0.6;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			SPIC I 5;
			Loop;
		Death:
			TNT1 A 0;
			SPIC I 401;
			Stop;
	}
}


CLASS RevenantDust2: RevenantDust { 
	Default {
		
		Speed 8;
		BounceFactor 0.2;
		Scale 0.3;
	}
}

CLASS RevenantBlood : doomb_body_base
{ 
	Default {
		Decal "BrutalBloodSplat";
		+FORCEXYBILLBOARD;
		+GHOST;
		+NOBLOCKMAP;
		+NOGRAVITY;
		+NOCLIP;
		-DONTSPLASH;
		-ALLOWPARTICLES;
		Speed 0;
	}
	states
	{
		Spawn:
			TNT1 A 0;
			TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAA 0 A_SpawnProjectile ("RevenantDust", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAA 0 A_SpawnProjectile ("RevenantDust2", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Splash");
			TNT1 A 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnProjectile ("RevenantPiece", 7, 0, random (0, 360), 2, random (30, 150));
			TNT1 A 0 A_SpawnItem ("BloodHit");
			stop;
			
		Splash:
			TNT1 AAA 0 A_SpawnProjectile ("Underblood1", 7, 0, random (0, 360), 2, random (30, 150));
			stop;
	}
}




CLASS RevenantBones: RevenantPiece { 
	Default {
		
		Speed 9;
		BounceFactor 0.3;
		Scale 1.0;
	}
	States
	{
		Spawn:
			BNP1 ABCDEFGH 4;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			Loop;
		Death:
			TNT1 A 0;
			BNP1 A 4000;
			Stop;
	}
}


CLASS RevenantBonesFast: RevenantPiece { 
	Default {
		
		Speed 14;
		BounceFactor 0.3;
		Scale 1.0;
	}
	States
	{
		Spawn:
			BNP1 ABCDEFGH 4;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			Loop;
		Death:
			TNT1 A 0;
			BNP1 A 4000;
			Stop;
	}
}





CLASS RevenantArm: RevenantPiece { 
	Default {
		
		Speed 10;
		BounceFactor 0.1;
		Scale 1.0;
	}
	States
	{
		Spawn:
			BNP2 ABCDEFGH 4;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			Loop;
		Death:
			TNT1 A 0;
			BNP2 A 4000;
			Stop;
	}
}


CLASS RevenantTorso5: RevenantPiece { 
	Default {
		
		Speed 5;
		BounceFactor 0.2;
		Scale 1.0;
	}
	States
	{
		Spawn:
			BNP3 ABCD 8;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			Loop;
		Death:
			TNT1 A 0;
			BNP3 A 4000;
			Stop;
	}
}





CLASS RevenantU : doomb_monster_base { 
	Default {
		GibHealth 45;
		Health 150;
		Monster;
		MeleeThreshold 196;
		+FLOORCLIP;
		+MISSILEMORE;
		Speed 6;
		damagefactor "Crush", 10.0;
		damagefactor "Plasma", 0.5;
		PainChance "Kick", 255;
		BloodType "RevenantBlood";
		SeeSound "skeleton/sight";
		PainSound "skeleton/pain";
		DeathSound "skeleton/death";
		ActiveSound "skeleton/active";
		MeleeSound "skeleton/melee";
		HitObituary "$OB_UNDEADHIT";
		Obituary "$OB_UNDEAD";
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		MaxStepHeight 24;
		+DONTHARMCLASS;
		+NOPAIN;
		+LOOKALLAROUND;
		+NOTARGET;
		MaxDropOffHeight 32;
		Radius 20;
		Height 40;
	}
	States
	{
		Spawn:
			UKEL A 6 A_Look;
			Loop;
			
		See:
			UKEL AAABBBCCC 2 A_chase(null,null);
			UKEL CDDD 2 A_Chase;
			Loop;
			
		Missile:
			UKEL E 10 A_FaceTarget;
			UKEL F 10 A_SpawnProjectile("RevenantBalls",20,15,0,0);
			TNT1 A 0 A_Jump(128, "Missile2");
		Goto See;
			
		Missile2:
			UKEL E 1 A_FaceTarget;
			UKEL F 10 A_SpawnProjectile("RevenantBalls",20,-15,0,0);
		Goto See;
			
			
		Death:
			TNT1 AAA 0 A_SpawnProjectile ("RevenantDust", 5, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAA 0 A_SpawnProjectile ("RevenantDust2", 5, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnProjectile ("XDeathRevenantHead", 5, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AA 0 A_SpawnProjectile ("RevenantBones", 5, 0, random (0, 360), 2, random (30, 150));
			TNT1 AA 0 A_SpawnProjectile ("RevenantArm", 5, 0, random (0, 360), 2, random (30, 150));
			TNT1 AA 0 A_SpawnProjectile ("MetalShard1", 5, 0, random (0, 360), 2, random (30, 160));
			TNT1 AA 0 A_SpawnProjectile ("MetalShard2", 5, 0, random (0, 360), 2, random (30, 160));
			TNT1 AA 0 A_SpawnProjectile ("MetalShard3", 5, 0, random (0, 360), 2, random (30, 160));
			TNT1 AAA 0 A_SpawnProjectile ("RevenantBonesFast", 5, 0, random (0, 360), 2, random (30, 150));
			TNT1 AAA 0 A_SpawnProjectile ("RevenantPiece", 5, 0, random (0, 360), 2, random (30, 150));
			TNT1 A 0 A_SpawnItem("HellishMissileLauncher");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 10;
			Stop;

		Pain.Taunt:
			TNT1 A 0;
			Goto Missile;
	}
}




CLASS DeadSkeleton: CurbstompedMarine { 
	Default {
		
		Radius 4;
		Height 18;
		Scale 1.0;
		+SHOOTABLE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		+FLOORCLIP;
		-SOLID;
		+NORADIUSDMG;
		damagefactor "Crusher", 50.0;
		Mass 1000;
		Health 200;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
		damagefactor "Saw", 0.3;
		bloodtype "RevenantBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			SKEL Q -1;
			Stop;
			
		Raise:
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 2 doomb_show_effect("RealFlameTrailsSmall", (0, 0, 5), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("PentagramSpawner", 0, 60);
			TNT1 A 0 A_SpawnItem("TeleportFog");
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("doomb_Revenant");
			Stop;
			
		Death.Fire:
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		TNT1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		EXPL AAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		CARB NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN 10 doomb_show_effect("AltSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		CARB N -1;
		Stop;
		
	Death.Cut:
	Death.Saw:
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAA 0 A_SpawnProjectile ("RevenantBones", 7, 0, random (0, 360), 2, random (30, 150));
		TNT1 AA 0 A_SpawnProjectile ("RevenantArm", 7, 0, random (0, 360), 2, random (30, 150));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfSkeleton", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("XDeadSkeleton", 1);
		Stop;
		
}

}


CLASS XDeathRevenantHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Scale 1.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			XHE6 ABCD 6;
			Loop;
		Death:
			XHE6 A 1;
			XHE6 A 1 A_SpawnItem("RevenantHead",0,0,0,1);
			Stop;
	}
}




CLASS RevenantHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		BloodType "RevenantBlood";
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 60;
		Health 60;
		Scale 1.0;
	}
	States
	{
		Spawn:
			XHE6 B 1900;
			Loop;
			
		Death.Trample:
		Crush:
			TNT1 AAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS1 B 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
			EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0;
			Stop;
		Death:
		Death.punch:
		Death.Kick:
			XHE6 A 1 A_Pain;
			XHE6 A 1 A_FaceTarget;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathRevenantHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			XHE6 ABCD 3;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,50,0,1);
			Goto Fly293;
		Fly293:
			XHE6 ABCD 6;
			TNT1 A 0 A_JumpIf(vel.z == 0, "Land293");
			
		Land293:
			XHE6 I 0 A_SpawnItem("XDeathRevenantHead");
			Stop;
			
			
	}
	
}

CLASS XDeathRevenantHeadKicked: XDeathRevenantHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		BounceFactor 0.4;
	}
}

CLASS XDeathRevenantHeadKicked2: XDeathRevenantHead { 
	Default {
		
		+BOUNCEONACTORS;
		+NOEXTREMEDEATH;
		Damage 15;
		Speed 24;
		BounceFactor 0.2;
	}
}


CLASS XDeathHalfSkeleton : doomb_body_base
{ 
	Default {
		
		Radius 8;
		Height 8;
		Speed 9;
		Mass 8;
		BounceFactor 0.4;
		+DOOMBOUNCE;
		+NOBLOCKMAP;
		+MISSILE;
		+NOTELEPORT;
		+DONTSPLASH;
		+MOVEWITHSECTOR;
		DeathSound "misc/xdeath1";
		Decal "BrutalBloodSplat";
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			SKEX F 12 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			Loop;
		Death:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			SKEX F 0 A_SpawnItem("GibHalfSkeleton",0,0,0,1);
			Stop;
	}
}

CLASS GibHalfSkeleton: BigGibBase { 
	Default {
		
		Radius 8;
		damagefactor "Kick", 12.0;
		damagefactor "punch", 12.0;
		damagefactor "Melee", 12.0;
		damagefactor "Fatality", 12.0;
	}
	States
	{
		Spawn:
			SKEX F 1900 doomb_spawn_bloodpool(BPS_SMALL);
			Loop   ;
		Death.Trample:
		Death:
			TNT1 A 0 A_SpawnItem("HellishMissileLauncher");
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		Stop;
	}
	
}


CLASS NotDeadSkeleton: DeadSkeleton { 
	Default {
	
	Health 50;
	damagefactor "Kick", 50.0;
	-THRUACTORS;
	-CORPSE;
	Radius 1;
	}
States
{
	Spawn:
		SKEL Q 500;
		SKEL PONML 5;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_fall;
		TNT1 A 0 A_SpawnItem ("doomb_Revenant", 3);
		Stop;
		
}

}

CLASS DeadSkeletonNoHead: DeadSkeleton
{

Default
{
	Health 200;
	+SHOOTABLE;
	Radius 4;
	Height 18;
}

States
{
	Spawn:
		REVH D -1;
	Stop;
}

}

CLASS XDeadSkeleton: DeadSkeleton { 
	Default {
	Health 200;
	}
States
{
	Spawn:
		DKEL I -1;
	Stop;

	Death.Cutless:
	Death.Cut:
	Death: Death.Saw:
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
	Stop;
}

}		
		


CLASS RoamingLegs : doomb_body_base { 
	Default {
    Radius 8;
    Height 32;
    Speed 5;
	Health 80;
	BloodType "RevenantBlood";
	+SHOOTABLE
    +FLOORCLIP
    +LOOKALLAROUND
	}
    States
    {
    Spawn:
        DKEL AABBCCDD 2 A_Wander;
		tnt1 a 0 doomb_random_death();
	loop;

		Death:
		TNT1 A 0 A_NoBlocking;
		DKEL EFGHI 4;
		TNT1 A 0 A_SpawnItem ("XDeadSkeleton", 1);
		Stop;
	Death.Shotgun:
	Death.Cutless:
	XDeath:
	TNT1 AAAA 0 A_SpawnProjectile ("RevenantBones", 37, 0, random (0, 360), 2, random (30, 150));
		TNT1 AAAAAAA 0 A_SpawnProjectile ("RevenantPiece", 37, 0, random (0, 360), 2, random (30, 150));
		Stop;
    Crush:
        TNT1 A 0 A_PlaySound("misc/xdeath4");
        CRS2 A -1;
        Stop;
	}
}


CLASS VeryFuckedUpRevenant: CurbstompedMarine { 
    States
    {
    Spawn:
	REVH L 1900 ;
       Loop    ;
}

}	   
CLASS MarineFatalizedByRevenant: CurbstompedMarine { 
    States
    {
    Spawn:
REFP K 1900;
       Loop;
}

}	   
