//===========================================================================
//
// Demon
//
//===========================================================================

CLASS EatMe : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}

CLASS DemonBleedingOut : Inventory { 
	Default {
		
		inventory.maxamount 50;
	}
}

CLASS BullDemon : doomb_monster_base Replaces Demon { 
	Default {
		
		GibHealth 35;
		//Radius 30
		Health 200;
		Scale 1.1;
		Height 56;
		Radius 22;
		Mass 400;
		Speed 11;
		FastSpeed 9;//yes, his fast speed is slower because it would make him sanic fast if it was default.
		PainChance "Saw", 200;
		PainChance "Cut", 200;
		PainChance "Kick", 255;
		damagefactor "Crush", 10.0;
		damagefactor "SSG", 5.0;
		damagefactor "Avoid", 0.0;
		damagefactor "SSG", 5.0;

		+CANPASS;
		Monster;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		+FLOORCLIP;
		
		SeeSound "demon/sight";
		AttackSound "demon/melee";
		PainSound "demon/pain";
		DeathSound "demon/death";
		ActiveSound "PINKIDL";
		BloodType "Brutal_Blood",  "SawBlood";
		DamageType "Eat";
		MaxStepHeight 32;
		MaxDropOffHeight 32;
		DropItem "DemonStrengthRune", 2;
		damagefactor "cut", 0.7;
		damagefactor "saw", 0.7;
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
		Spawned:
			TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
			SARG YZYZYZYZYZ 10 A_Look;
			Loop;
			
		Forget:
			TNT1 A 0 A_ClearTarget;
			TNT1 A 0 A_TakeInventory("EnemyMemory", 15);
		SearchPlayer:
		Idle:
			
			SARG YZ 10 A_Look;
			TNT1 A 0 A_SetAngle(angle - 40);
			SARG YZ 10 A_Look;
			TNT1 A 0 A_SetAngle(angle + 40);
			SARG YZ 10 A_Look;
			
			
			SARG A 0 A_Wander;
			SARG A 2 A_Look;
			SARG A 0 A_Wander;
			SARG A 2 A_Look;
			SARG B 0 A_Wander;
			SARG B 2 A_Look;
			SARG B 0 A_Wander;
			SARG B 2 A_Look;
			SARG C 0 A_Wander;
			SARG C 2 A_Look;
			SARG C 0 A_Wander;
			SARG C 2 A_Look;
			SARG D 0 A_Wander;
			SARG D 2 A_Look;
			SARG D 0 A_Wander;
			SARG D 2 A_Look;
			
			TNT1 A 0 A_Jump(128, "SearchPlayer");
			
			SARG A 0 A_Wander;
			SARG A 2 A_Look;
			SARG A 0 A_Wander;
			SARG A 2 A_Look;
			SARG B 0 A_Wander;
			SARG B 2 A_Look;
			SARG B 0 A_Wander;
			SARG B 2 A_Look;
			SARG C 0 A_Wander;
			SARG C 2 A_Look;
			SARG C 0 A_Wander;
			SARG C 2 A_Look;
			SARG D 0 A_Wander;
			SARG D 2 A_Look;
			SARG D 0 A_Wander;
			SARG D 2 A_Look;
			
			Goto SearchPlayer;
			
		See:
			TNT1 A 0 A_CheckSight("SeeNeverSeen");
			
		SeeContinue:
			TNT1 A 0;
			
			TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman");
			TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
			TNT1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
			TNT1 A 0 A_CheckSight("SeeNoSee");
			TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
			//TNT1 A 0 A_SpawnItemEx("FootSep6", 0, 0, 30, 0, 0)
			TNT1 A 0 A_TakeInventory("EnemyMemory", 17);
			SARG AA 2 A_Chase;
			SARG BB 2 A_Chase;
			//TNT1 A 0 A_SpawnItemEx("FootSep6", 0, 0, 30, 0, 0)
			SARG CC 2 A_Chase;
			SARG DD 2 A_Chase;
			TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "Idle");
			Loop;
			
		SeeNoSee:
			//TNT1 A 0 A_SpawnItemEx("FootSep6", 0, 0, 30, 0, 0)
			SARG AA 2 A_Chase;
			SARG BB 2 A_Chase;
			SARG CC 2 A_Chase;
			SARG DD 2 A_Chase;
			TNT1 A 0 A_GiveInventory("EnemyMemory", 1);
			TNT1 A 0 A_JumpIfInventory("EnemyMemory", 15, "Forget");
			Goto See;
			
		SeeNeverSeen:
			//TNT1 A 0 A_SpawnItemEx("FootSep6", 0, 0, 30, 0, 0)
			SARG AA 2 A_Chase;
			SARG BB 2 A_Chase;
			SARG CC 2 A_Chase;
			SARG DD 2 A_Chase;
			Loop;
			
			
		Melee:
			TNT1 A 0;
			TNT1 A 0 A_TakeInventory("EnemyMemory", 100);
			TNT1 A 0 A_JumpIfInTargetInventory("ComeEatMeDemon", 1, "MeleeDown");
			SARG E 6 A_FaceTarget;
			SARG F 6 A_FaceTarget;
			SARG G 12 doomb_cheap_melee_attack(60, random(16, 40), "eat");
			
			TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman");
			TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
			TNT1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
			
			TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
			Goto SeeContinue;
			
		MeleeDown:
			PDEV AB 6 A_FaceTarget;
			PDEV C 12 doomb_cheap_melee_attack(60, random(16, 40), "eat");
			TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman");
			TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
			TNT1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando");
		Goto SeeContinue;
			
		Pain:
			SARG H 2;
			SARG H 2 A_Pain;
			Goto SeeContinue;
			
		Pain.punch:
			SARG H 3;
			SARG H 3 A_Pain;
			Goto SeeContinue;
			
			
			
		Pain.Shotgun:
			TNT1 A 0 A_Pain;
			TNT1 A 0;
			//TNT1 A 0 ThrustThingZ(0,30,0,1)
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (2);
			SARG H 2;
			//DEMP A 4
			SARG H 2;
			Goto SeeContinue;
			
		Pain.Kick:
		Pain.HeavyImpact:
			SARG A 1 A_Pain;
			SARG A 1 A_FaceTarget;
			//TNT1 A 0 ThrustThingZ(0,30,0,1)
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (15);
			SARG H 4;
			//DEMP B 6
			SARG H 4;
			Goto SeeContinue;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Jump(96, "LeftDeath");
			TNT1 A 0 A_Jump(96, 13);
			TNT1 AAA 0;
			SARG I 8;
			SARG J 8 A_Scream;
			SARG K 4;
			SARG L 4 A_NoBlocking;
			SARG M 4;
			TNT1 A 0 A_SpawnItem ("DeadDemon1", 1);
			TNT1 A 0 doomb_spawn_bloodpool();
			Stop;
			TNT1 AAAAAAAAA 0;
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathDemonArm", 35, 0, random (0, 360), 2, random (0, 160));
			SAAR A 8 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
			SAAR B 8 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItemEx ("PoorPinkyLostHisArm",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		LeftDeath:
			S2RG I 8;
			S2RG J 8 A_Scream;
			S2RG K 4;
			S2RG L 4 A_NoBlocking;
			S2RG M 4;
			TNT1 A 0 A_SpawnItem ("DeadDemon1Left", 1);
			TNT1 A 0 doomb_spawn_bloodpool();
			Stop;
			
		CleanDeath:
			TNT1 A 0;
			TNT1 A 0 A_Jump(96, "LeftDeath");
			SARG I 8;
			SARG J 8 A_Scream;
			SARG K 4;
			SARG L 4 A_NoBlocking;
			SARG M 4;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("DeadDemon1", 1);
			Stop;
			
		Death.Kick:
			TNT1 A 0;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil(5);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			Goto CleanDeath;
			
		Death.Shotgun:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(200, "Death.Strong");
			Goto Death+4;
			
		Death.Strong:
			TNT1 A 0;
			TNT1 A 0 A_Jump(128, "DeathRemoveArm");
			TNT1 A 0 A_FaceTarget;
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AA 0 A_SpawnProjectile ("XDeathBrain1", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathBrain2", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", random (45, 55), random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", random (45, 55), random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 A 0 A_SpawnProjectile ("MuchBlood", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Bloodmist", 50, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_SpawnProjectile ("BaronHeadPiece", 52, 0, random (0, 360), 2, random (0, 160));
			//TNT1 A 0 A_SpawnProjectile ("PinkyJaw", 52, 0, random (0, 360), 2, random (0, 160))
			TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			SARH AAAAAAA 2 A_SpawnProjectile ("Brutal_LiquidBlood", 40, 0, random (0, 360), 2, random (30, 110));
			SARH BBBBBB 2 A_SpawnProjectile ("Brutal_LiquidBlood", 40, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			SARH CCCCCC 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 doomb_spawn_bloodpool();
			SARH DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_SpawnItem("DeadDemonNoHead");
			Stop;
			
		Death.Saw:
			TNT1 A 0 A_Jump(32, "Death");
			TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath4", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 60, 0, random (0, 360), 2, random (0, 160));
			SARG O 8;
			SARG P 8 A_Scream;
			SARG Q 4 A_NoBlocking;
			SARG RRSSTT 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 doomb_spawn_bloodpool();
			SARG TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT 2 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, random (0, 360), 2, random (30, 110));
			SARG T -1;
			Stop;
			
		Death.Cut:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(32, "Death");
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfDemon", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 60, 0, random (0, 360), 2, random (0, 160));
			SARC AAABBBCCCDDD 3 A_SpawnProjectile ("Brutal_LiquidBlood", 35, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 doomb_spawn_bloodpool();
			SARC DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (30, 110));
			SARC D 0 A_SpawnItem("DeadDemonHalf23");
			Stop;
			
			
		Death.Blast:
		Death.SSG:
			SARC A 1 A_Pain;
			SARC A 1 A_FaceTarget;
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 35, 0, random (170, 190), 2, random (0, 40));
			//TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, random (0, 160))
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
			TNT1 AAAA 0 A_SpawnProjectile ("BloodMist", 42, 0, random (0, 360), 2, random (40, 90));
			TNT1 AA 0 A_SpawnProjectile ("BaronHeadPiece", 42, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PinkyJaw", 42, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathDemonArm", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			SARC AAABBBCCCDDD 3 A_SpawnProjectile ("Brutal_LiquidBlood", 35, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 doomb_spawn_bloodpool();
			SARC DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 A_SpawnProjectile ("Brutal_LiquidBlood", 15, 0, random (0, 360), 2, random (30, 110));
			SARC D 0 A_SpawnItem("DeadDemonHalf23");
			Stop;
			
		Death.punch:
			TNT1 A 0 ThrustThingZ(0,45,0,1);
			Goto Death.SSG;
			
			TNT1 A 0;
			TNT1 A 0 A_ClearTarget;
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 42, 0, random (0, 360), 2, random (0, 160));
			POSL A 1 A_Chase(null, null);
			POSL A 1 A_Pain;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil(8);
			TNT1 A 0 ThrustThingZ(0,45,0,1);
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			POSL ABCDE 6;
			POSL F -1;
		Stop;
			
		Death.CutLEss:
			TNT1 A 0;
			TNT1 A 0 A_Jump(32, "Death.Cut");
			TNT1 A 0 A_Jump(132, "DeathRemoveArm");
			Goto Death;
			
			
		Crush:
		Death.Stomp:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			SARG IJKL 2;
			TNT1 AA 0 A_SpawnItem("MeatDeathSmall");
			TNT1 AAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
			TNT1 AA 0 bright A_SpawnProjectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 AA 0 bright A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("CrushedRemains");
			TNT1 A 1 A_XScream;
		Stop;
			
		DeathRemoveArm:
			Goto Death+14;
			
		Death.GreenFire:
			TNT1 A 0;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
			
			
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedDemonArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedDemonLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_spawn_burned_flesh;
			
			EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("GreenFlameTrails", (0, 0, 50), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
			XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
			Stop;
			
		Death.Plasma:
		Death.Plasma2:
			TNT1 A 0;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedDemonArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedDemonLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_spawn_burned_flesh;
			SPRG ABCDEF 6;
			CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 10 doomb_show_effect("AltSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
			CARB J -1;
			Stop;
			
		Death.Fire:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("BurningDemon", 0, 10);
			Stop;
			
		Death.Fatality:
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("GoFatality", 1);
			TNT1 A 0 A_Jump(256, "DemonFatality1", "DemonFatality2", "DemonFatality3");
			
		DemonFatality1:
			TNT1 A 0 A_GiveToTarget("DemonFatality", 1);
			Stop;
		DemonFatality2:
			TNT1 A 0 A_GiveToTarget("DemonFatality2", 1);
			TNT1 A 0;
			Stop;
		DemonFatality3:
			TNT1 A 0 A_GiveToTarget("DemonFatality3", 1);
			TNT1 A 0;
			Stop;
			
			
		Death.BHFT:
		Death.BHFT:
		Death.RVFT:
			TNT1 A 1 A_Pain;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("DemonFatality", 1);
			TNT1 A 0;
			Stop;
			
		XDeath:
		DEath.Explosive_Impact:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_FaceTarget;
			TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 42, 0, random (0, 190), 2, random (10, 60));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath3", 42, 0, random (0, 190), 2, random (10, 60));
			TNT1 AAA 0 A_SpawnProjectile ("XDeath2", 42, 0, random (0, 190), 2, random (10, 60));
			TNT1 A 0 A_SpawnProjectile ("XDeath4", 42, 0, random (0, 190), 2, random (10, 60));
			TNT1 A 0 A_SpawnProjectile ("BullXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_noblocking;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,25,0,1);
			TNT1 A 0 A_FaceTarget;
			TNT1 A 1;
			TNT1 A 0 A_JumpIf(angle < 180, "IsFacingNorth");
			TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayRight");
			TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayLeft");
			Goto XDeath;
		IsFacingNorth:
			TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayRight");
			TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayLeft");
			Goto XDeath;
			
		BlownAwayLeft:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBullLeg12", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathDemonArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathPinkyDemonHead", 42, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (20, 90));
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 A_Xscream;
			SRRD ABCD 5 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
			SRRD DDDDDDDDDD 3 A_CheckFloor("LandBlownAwayLeft");
		LandBlownAwayLeft:
			TNT1 A 0 A_Stop;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadDemonSRRDE");
			Stop;
			
		BlownAwayRight:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBullLeg12", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathDemonArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathPinkyDemonHead", 42, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("Bloodmist", 40, 0, random (0, 360), 2, random (20, 90));
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 A_Xscream;
			SRRD FGHI 5 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, 0, 2, 90);
			SRRD GGGGGGGGGG 3 A_CheckFloor("LandBlownAwayRight");
		LandBlownAwayRight:
			TNT1 A 0 A_Stop;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadDemonSRRDJ");
			Stop;
			
			
		Raise:
			SARG NMLKJI 5;
		Goto See;
			
		Pain.Taunt:
			TNT1 A 0;
			Goto See;
			
			
		FatalityZombieman:
			TNT1 A 0 A_SetInvulnerable;
			SARK DEDEDEDEDE 10 A_SpawnProjectile ("MuchBlood", 45, 0, random (0, 360), 2, random (0, 160));
			
			
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieManDown", 20, 0, random(0, 360), 2, random (0, 160));
			
			
			TNT1 A 0 A_TakeInventory("ZombiemanFatality",1);
			TNT1 A 0 A_UnSetInvulnerable;
			Goto See;
			
			
		FatalitySergeant:
			TNT1 A 0 A_SetInvulnerable;
			SARK FGFGFGFGFG 10 A_SpawnProjectile ("MuchBlood", 45, 0, random (0, 360), 2, random (0, 160));
			
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieManDown", 20, 0, random(0, 360), 2, random (0, 160));
			
			TNT1 A 0 A_TakeInventory("SergeantFatality",1);
			TNT1 A 0 A_UnSetInvulnerable;
			Goto See;
			
		FatalityComando:
			TNT1 A 0 A_SetInvulnerable;
			SARK JKJKJKJKJK 10 A_SpawnProjectile ("MuchBlood", 45, 0, random (0, 360), 2, random (0, 160));
			
			
			TNT1 A 0 A_TakeInventory("ComandoFatality",1);
			TNT1 A 0 A_UnSetInvulnerable;
			Goto See;
			
		FatalityImp:
			TNT1 A 0 A_SetInvulnerable;
			SARK HIHIHIHIHI 10 A_SpawnProjectile ("MuchBlood", 45, 0, random (0, 360), 2, random (0, 160));
			
			
			TNT1 A 0 A_TakeInventory("ImpFatality",1);
			TNT1 A 0 A_UnSetInvulnerable;
			Goto See;
			
			
		Eat:
			TNT1 A 0 A_TakeInventory ("EatMe", 1);
			SARK A 20 A_Look;
			TNT1 AAAAAAAAAAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 0, 0, random (0, 360), 2, random (0, 160));
			SARK BA 10 A_Look;
			tnt1 a 0 a_jump(240, "eat");
		Goto Spawn;

		Death.Eat:
			TNT1 A 0 A_GiveToTarget("EatMe",1);
			Goto Death+3;
		Stop;
}
}