CLASS ArmlessDemon : doomb_pinky
{ 
	Default {
		
		Health 100;
		+LOOKALLAROUND;
		+NOPAIN;
	}

	private void doomb_blood_loss()
	{
		if(random(0, 10) <= 2)
			damagemobj(self, self, 1, 'none');
	}

	States
	{
		
		Idle:
		Spawn:
			SG1A A 2
			{
				A_Look();
				doomb_blood_loss();
				doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			}
		Loop;
		
		See:
			SG1A AABBCCDD 2
			{
				A_Chase();
				doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			}
			TNT1 A 0 doomb_blood_loss();
		Loop;

		Melee:
			TNT1 A 0 doomb_blood_loss();
			SG1A E 3 A_FaceTarget;
			TNT1 A 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SG1A E 3 A_FaceTarget;
			TNT1 A 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SG1A F 3 A_FaceTarget;
			TNT1 A 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SG1A F 3 A_FaceTarget;
			TNT1 A 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SG1A G 3 doomb_cheap_melee_attack(60, random(16, 40), "eat");
			SG1A GGG 3 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		Goto See;
			
		Pain.Taunt:
		Goto See;
			
		Death.Shotgun:
		Death.mini_gun:
			TNT1 A 0 A_FaceTarget;
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AAAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 60), doomb_random_velocity(7) );
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_much_blood(60);
			TNT1 A 0 doomb_severed_limb("BaronHeadPiece", "spawn", (0, 0, 52), doomb_random_velocity(7) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, height/2) );
			TNT1 AAAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 60), doomb_random_velocity(7) );
			SAAR GGGGGGG 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			SAAR HHHHHHHHH 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			SAAR IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			tnt1 a 0 doomb_severed_limb("DeadDemonSAARI", limb_ignore_cvar: true);
		Stop;
			
		Death:
		Death.Kick:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			SAAR BCDEF 5;
			TNT1 A 0 doomb_severed_limb("DeadDemonNoArm", limb_ignore_cvar: true);
			TNT1 A 0 doomb_spawn_bloodpool();
		Stop;
	}
}



CLASS DeadDemon1: CurbstompedMarine
{
Default
{
	Radius 18;
	Height 12;
	Scale 1.1;
	+SHOOTABLE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CORPSE;
	+FLOORCLIP;
	-SOLID;
	-THRUACTORS;
	+SHOOTABLE;
	-GHOST;
	-THRUGHOST;
	Species "Marines";
	damagefactor "Crush", 50.0;
	Mass 9000;
	Health 300;
	damagefactor "Blood", 0.0;
	damagefactor "Trample", 0.0;
}

States
{
	Spawn:
		SARG N -1;
	Stop;
	
	Raise:
		SARG N 5;
		SARG MLKJI 5;
		TNT1 A 0 A_SpawnItem ("doomb_pinky", 3);
	Stop;
	
	Death:
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 AAAAAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 20), doomb_random_velocity(7) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_much_blood(20);
		TNT1 A 0 doomb_severed_limb("BaronHeadPiece", "spawn", (0, 0, 22), doomb_random_velocity(7) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, 20) );
		TNT1 A 0 doomb_severed_limb("DeadDemonNoHead", limb_ignore_cvar: true);
	Stop;
			
	Death.Plasma:
	Death.Plasma2:
		TNT1 AAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 10 doomb_show_effect("AltSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		CARB J -1;
	Stop;
}

}

CLASS DeadDemonHalf: DeadDemon1
{
Default
{
	Health 300;
}

States
{
	Spawn:
		SARG T -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 doomb_severed_limb("XDeathBullLeg12", "spawn", (0, 0, 35), doomb_random_velocity(7) );
		TNT1 AA 0 doomb_severed_limb("XDeathDemonArm", "spawn", (0, 0, 35), doomb_random_velocity(7) );
		TNT1 AA 0 doomb_Meat_Death_Small();
	Stop;
}

}		

CLASS DeadDemonHalf23 : DeadDemon1
{ 
Default
{
	Health 300;
	Height 16;
}

States
{
	Spawn:
		SARC D -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 doomb_severed_limb("XDeathBullLeg12", "spawn", (0, 0, 35), doomb_random_velocity(7) );
		TNT1 AA 0 doomb_Meat_Death_Small();
		Stop;
}

}

CLASS DeadDemonNoArm : DeadDemon1
{ 
	Default {
	Health 300;
}

States
{
	Spawn:
		SAAR F -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 doomb_severed_limb("XDeathDemonArm", "spawn", (0, 0, 35), doomb_random_velocity(7) );
		TNT1 AA 0 doomb_Meat_Death_Small();
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 AAAAAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 20), doomb_random_velocity(7) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_much_blood(20);
		TNT1 A 0 doomb_severed_limb("BaronHeadPiece", "spawn", (0, 0, 22), doomb_random_velocity(7) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, 20) );
		TNT1 A 0 doomb_severed_limb("DeadDemonSAARK", limb_ignore_cvar:true);
	Stop;
		
}

}	  
	  
CLASS DeadDemonSAARK: DeadDemon1
{
Default
{
	Health 300;
}

States
{
	Spawn:
		SAAR K -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 doomb_severed_limb("XDeathBullLeg12", "spawn", (0, 0, 35), doomb_random_velocity(7) );
		TNT1 AA 0 doomb_Meat_Death_Small();
	Stop;
		
}

}	  

CLASS DeadDemonNoHead: DeadDemon1 { 
Default
{
	Health 300;
}

States
{
	Spawn:
		SARH D -1;
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0
		{
			doomb_generic_internal_organ a = doomb_generic_internal_organ( doomb_severed_limb("doomb_generic_internal_organ", "spawn", (0, 0, 30), doomb_random_velocity(7) ) );

			if(a)
				a.set_gib_appearance(0, DIT_GUT_PILE_FLYING);
		}
		TNT1 AA 0 doomb_severed_limb("XDeathDemonArm", "spawn", (0, 0, 35), doomb_random_velocity(7) );
		TNT1 A 0 doomb_severed_limb("PinkyJaw", "spawn", (0, 0, 35), doomb_random_velocity(7) );
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("DeadDemonHalf23", limb_ignore_cvar: true);
	Stop;
		
}

}		
		
CLASS DeadDemon1Left: DeadDemon1
{

States
{
	Spawn:
		S2RG N -1;
	Stop;
}

}

CLASS DeadDemonStomped: DeadDemonNoARm
{

States
{
	Spawn:
		FD2M K -1;
	Stop;
		
}

}	




CLASS doomb_demon_right_half : DeadDemon1
{

States
{
	Spawn:
		SRRD J -1;
	Stop;

	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0
		{
			doomb_generic_internal_organ a = doomb_generic_internal_organ( doomb_severed_limb("doomb_generic_internal_organ", "spawn", (0, 0, 30), doomb_random_velocity(7) ) );

			if(a)
				a.set_gib_appearance(0, DIT_GUT_PILE_FLYING);
		}
		TNT1 A 0 doomb_severed_limb("XDeathDemonArm", "spawn", (0, 0, 35), doomb_random_velocity(7) );
		TNT1 A 0 doomb_severed_limb("XDeathBullLeg12", "spawn", (0, 0, 35), doomb_random_velocity(7) );
		TNT1 AA 0 doomb_Meat_Death_Small();
	Stop;
}

}

CLASS doomb_demon_left_half: doomb_demon_right_half
{

States
{
	Spawn:
		SRRD E -1;
	Stop;
}

}	



CLASS DeadDemonSAARI: DeadDemon1
{

States
{
	Spawn:
		SAAR I -1;
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0
		{
			doomb_generic_internal_organ a = doomb_generic_internal_organ( doomb_severed_limb("doomb_generic_internal_organ", "spawn", (0, 0, 30), doomb_random_velocity(7) ) );

			if(a)
				a.set_gib_appearance(0, DIT_GUT_PILE_FLYING);
		}
		TNT1 A 0 doomb_severed_limb("XDeathDemonArm", "spawn", (0, 0, 35), doomb_random_velocity(7) );
		TNT1 A 0 doomb_severed_limb("PinkyJaw", "spawn", (0, 0, 35), doomb_random_velocity(7) );
		TNT1 A 0 A_SpawnProjectile ("", 22, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 doomb_severed_limb("DeadDemonHalf23", limb_ignore_cvar: true);
	Stop;
}
}


CLASS PoorPinkyLostHisArm: doomb_body_base
{

Default
{
	Height 56;
	Radius 22;
	Health 50;
	+NOPAIN;
	-COUNTKILL;
	+SHOOTABLE;
	Scale 1.1;
}

States
{
	Spawn:
		SAAR J 1 A_Pain;
		SAAR JJJJJJJJJJJJ 4 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		tnt1 a 0 a_jump(32, "PutAFight");
		tnt1 a 0 a_jump(196, "Colapse");
	loop;

	PutAFight:
		TNT1 A 0 spawn("ArmlessDemon", pos);
	Stop;

	Death.Shotgun:
	Death.mini_gun:
	Death:
	Death.Fatality:
		TNT1 A 0 A_FaceTarget;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AAAAAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 20), doomb_random_velocity(7) );
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_much_blood(60);
		TNT1 A 0 doomb_severed_limb("BaronHeadPiece", "spawn", (0, 0, 52), doomb_random_velocity(7) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, 50) );
		SAAR GGGGGGG 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
		SAAR HHHHHHHHH 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_spawn_bloodpool();
		SAAR IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 2 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_severed_limb("DeadDemonSAARI", limb_ignore_cvar: true);
	Stop;
		
		
	Colapse:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		SAAR BCDEF 5;
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 doomb_severed_limb("DeadDemonNoArm", limb_ignore_cvar: true);
	Stop;
}

}




CLASS DyingDemon : doomb_body_base
{ 
Default
{
	Radius 8;
	Height 8;
	Speed 0;
	Mass 6;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+DONTSPLASH;
	+CLIENTSIDEONLY;
	+FORCEXYBILLBOARD;
}

States
{
	Spawn:
		SARH AAA 4 doomb_spawn_big_blood(50);
		SARH BBB 4 doomb_spawn_big_blood(40);
		SARH CCC 4 doomb_spawn_big_blood( 30);
		SARH DDDDDDDDDDDDDDD 4 doomb_spawn_big_blood(20);
		TNT1 A 0 doomb_severed_limb("DeadDemonNoHead", limb_ignore_cvar: true);
	Stop;
}

}



CLASS Gib_DemonLeg: LimbBase { 
	States
	{
		Spawn:
			LEG8 GH 2;
		Spawn1:
			LEG8 I 4000 doomb_spawn_bloodpool(BPS_SMALL);
		Loop;
			
			
		Death.plasma:
			TNT1 A 0 doomb_severed_limb("XDeathBurnedDemonLeg", "spawn", (0, 0,32), doomb_random_velocity(7) );
		Stop;

		Death:    
			TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_severed_limb("GibDemonLegPart", "spawn", (0, 0,32), doomb_random_velocity(7) );
			TNT1 A 0 doomb_severed_limb("GibDemonPaw", "spawn", (0, 0,32), doomb_random_velocity(7) );
		Stop;
		
		Death.Kick:
		Death.Punch:
			LEG8 A 1 A_FaceTarget;
			TNT1 A 0 doomb_severed_limb("XDeathBullLeg12", "spawn", (0, 0, 5), doomb_random_velocity(7) );
		Stop;
			
		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LEG8 ABCDEFGH 2;
		Goto Spawn1;
			
		Death.Explosive_Impact:
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			LEG8 A 5;
			LEG8 ABCDEFGH 5;
			TNT1 A 0 doomb_severed_limb("Gib_DemonLeg", limb_ignore_cvar: true);
		Stop;
}
	
}
CLASS GibDemonLegPart: TinyGib
{
States
{
	Spawn:
		LEG8 Z 1;
	Loop;
}
	
}


CLASS GibDemonPaw: TinyGib
{
States
{
	Spawn:
		LEG8 Y 1;
	Loop;
	
	Death:
		LEG8 Y 1;
	Loop;
}
	
}


CLASS XDeathDemonHead : doomb_body_base
{ 
Default
{
	Radius 8;
	Height 8;
	Scale 0.9;
	Speed 10;
	Mass 1;
	gravity 0.5;
	Decal "BrutalBloodSplat";
	BounceFactor 0.4;
	BounceCount 5;
	+DOOMBOUNCE;
	+MISSILE;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+NOBLOCKMAP;
	+NOTELEPORT;
}

States
{
	Spawn:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		DEMH ABCDEF 7 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
	Loop;
	
	Death:
		TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
		TNT1 A 0 doomb_severed_limb("Gib_DemonHead", limb_ignore_cvar: true);
	Stop;
}

}


CLASS Gib_DemonArm: LimbBase
{
	States
	{
		Spawn:
			HND8 GH 2;
		Spawn1:
			HND8 I 40000;
		Loop;

		Death:    
			TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_severed_limb("GibDemonHand");
			TNT1 A 0 doomb_severed_limb("GibDemonArmPart");
		Stop;

		Pain:
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			HND8 ABCDEFGH 2;
		Goto Spawn1;
			
		Death.Explosive_Impact:
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			HND8 A 5;
			HND8 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Landz:
			TNT1 A 0 doomb_severed_limb("Gib_DemonArm");
		Stop;
}
	
}

CLASS GibDemonArmPart: TinyGib
{
States
{
	Spawn:
		HND8 Z 1;
	Loop;
		
}
	
}





CLASS PinkyDemonHead: LimbBase
{
Default {
	
	damagefactor "Kick", 9.0;
	damagefactor "Melee", 9.0;
	-CLIENTSIDEONLY;
	Radius 10;
	
	Mass 60;
	Health 60;
	Scale 1.5;
}

States
{
	Spawn:
		DEMH I 4000 doomb_spawn_bloodpool(BPS_SMALL);
	Loop;
		
	Death:
		TNT1 AAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		TNT1 A 0 doomb_severed_limb("PinkyJaw", "spawn", (0, 0, 5), doomb_random_velocity(7) );
		TNT1 A 0 doomb_severed_limb("eye", "spawn", (0, 0, 5), doomb_random_velocity(7) );
		TNT1 A 0 doomb_severed_limb("head_piece", "spawn", (0, 0, 5), doomb_random_velocity(7) );
		TNT1 AAAAAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 20), doomb_random_velocity(7) );
	Stop;

	Death.Trample:
	Crush:
		TNT1 AAAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		DEMH I 5;
		DEMH I 9009;
	Stop;
	
	Death.plasma:
		TNT1 A 0 doomb_spawn_burned_flesh();
		EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
	Stop;
	
	Death.punch:
	Death.Kick:
		DEMH A 1 A_Pain;
		DEMH A 1 A_FaceTarget;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 doomb_severed_limb("XDeathPinkyDemonHead", "spawn", (0, 0, 5), doomb_random_velocity(7) );
		TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
		TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
	Stop;
		
	Pain:
		TNT1 A 0 ThrustThingZ(0,20,0,1);
		DEMH ACEGI 3;
	Goto Spawn;
		
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ThrustThingZ(0,30,0,1);
		DEMH ABCDEFGH 3;
		DEMH I 0 doomb_severed_limb("PinkyDemonHead");
	Stop;
}
	
}


CLASS XDeathHalfDemon : doomb_body_base
{
	Default {
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			SARC E 12;
		Loop;

		Death:
			TNT1 A 0 doomb_spawn_bloodpool(BPS_SMALL);
			SARC F 1 doomb_severed_limb("Gib_HalfDemon", limb_ignore_cvar: true);
		Stop;
	}
}

CLASS Gib_HalfDemon: doomb_body_base
{
States
{
	Spawn:
		SARC F 1900 doomb_spawn_bloodpool(BPS_SMALL);
	Loop;
}
	
}	   


CLASS GibDemonHand: TinyGib
{
	States
	{
		Spawn:
			HND8 Y 1;
			Loop;
		Death:
			HND8 Y 1;
			Loop;
			
	}
	
}

CLASS Gib_DemonHead: LimbBase
{
	States
	{
		Spawn:
			DEMH I -1 nodelay
			{
				frame += random(0, 1);
			}
		stop;

		Death.plasma:
			TNT1 A 0 doomb_spawn_burned_flesh();
		Stop;
		
		Death:    
			TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 AAAAAA 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 20), doomb_random_velocity(7) );
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "blood_impact_splash", (0, 0, 10) );
			TNT1 A 0 doomb_severed_limb("BaronHeadPiece", "spawn", (0, 0, 52), doomb_random_velocity(7) );
			TNT1 A 0 doomb_severed_limb("PinkyJaw", "spawn", (0, 0, 5), doomb_random_velocity(7) );
		Stop;
	}
	
}

CLASS BurningDemon : doomb_body_base
{
	Default {
	
	Radius 12;
	Height 56;
	Speed 5;
	Scale 0.85;
	Health 100;
	GibHealth 25;
	damagefactor "Fire", 0.0;
	damagefactor "Explosive_Impact", 10.0;
	MONSTER;
	-COUNTKILL;
	+NOICEDEATH;
	+FRIENDLY;
	+FLOORCLIP;
	+SHOOTABLE;
	+NOBLOCKMONST;
	+DONTSPLASH;
	
	Gravity 0.7;
	
	Obituary "%o was near someone in flames.";
	MaxDropOffHeight 6000;
	
	Mass 999999;
}

States
{
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");

	Suffer:
		SBRG AAABBBCCCDDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_playsound ("demon/pain");
			tnt1 B 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{{doomb_flare_base.doomb_attach_flare(self, "RedFlare");}}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
			}
		TNT1 A 0 doomb_random_death;
	Loop;
	
	Death:
		CRB7 Q 2
		{
			A_NoBlocking();
			A_Scream();
			A_playsound ("demon/death");
		}
		CRB7 QQQQRRRR 2 doomb_show_effect("FlameTrails", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_Playsound("props/redfire");
		CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 2 doomb_show_effect("FlameTrails", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 20 doomb_show_effect("AltSmoke", (0, 0, 35), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		CARB J -1;
	Stop;
		
	XDeath:
	Death.SSG:
	Death.Explosive_Impact:
		TNT1 A 0 A_NOBlocking;
		TNT1 A 0 doomb_blood_mist('doomb_non_interactive_blood', 'blood_mist', (0, 0, 110), 6);
		TNT1 A 0 doomb_severed_limb("XDeathBurnedDemonArm", "spawn", (0, 0, 32), doomb_random_velocity(7) );
		TNT1 A 0 doomb_severed_limb("XDeathBurnedDemonLeg", "spawn", (0, 0,32), doomb_random_velocity(7) );
		TNT1 AA 0 doomb_spawn_burned_flesh;
		TNT1 A 0 doomb_severed_limb("MeatDeath", "spawn", (0, 0, 35) );
		TNT1 AAAAAA 0 doomb_severed_limb("BurningFlyingMeatPiece", "spawn", (0, 0, 64), doomb_random_velocity(7) );
		TNT1 A 0 a_givetotarget("CrueltyBonus5Health");
	Stop;
}
}


