//===========================================================================
//
// Demon
//
//===========================================================================

CLASS EatMe : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}

CLASS doomb_pinky : doomb_monster_base
{ 
	Default {
		
		GibHealth 35;
		//Radius 30
		Health 200;
		Scale 1.1;
		Height 56;
		Radius 22;
		Mass 400;
		Speed 11;
		FastSpeed 11;//yes, his fast speed is slower because it would make him sanic fast if it was default.
		PainChance "Saw", 200;
		PainChance "Cut", 200;
		PainChance "Kick", 255;
		damagefactor "Crush", 10.0;
		damagefactor "SSG", 5.0;
		damagefactor "SSG", 5.0;

		+CANPASS;
		Monster;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		+FLOORCLIP;
		
		SeeSound "demon/sight";
		AttackSound "demon/melee";
		PainSound "demon/pain";
		DeathSound "demon/death";
		ActiveSound "PINKIDL";
		BloodType "Brutal_Blood",  "SawBlood";
		DamageType "Eat";
		MaxStepHeight 32;
		MaxDropOffHeight 32;
		DropItem "DemonStrengthRune", 2;
		damagefactor "cut", 0.7;
		damagefactor "saw", 0.7;
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
		Spawned:
			TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
			SARG YZYZYZYZYZ 10 A_Look;
		Loop;
			
		Forget:
			TNT1 A 0 A_ClearTarget;
		SearchPlayer:
		Idle:
			SARG YZ 10 A_Look;
			TNT1 A 0 A_SetAngle(angle - 40);
			SARG YZ 10 A_Look;
			TNT1 A 0 A_SetAngle(angle + 40);
			SARG YZ 10 A_Look;
			
			
			SARG AABBCCDD 2
			{
				A_Wander();
				A_Look();
			}
		Goto SearchPlayer;
			
		See:
			TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
			TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
			SARG AABBCCDD 2 A_Chase;
			TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "Idle");
			tnt1 a 0 doomb_monster_memory();
		Loop;
			
		Melee:
			TNT1 A 0 doomb_update_memory();
			TNT1 A 0 A_JumpIfInTargetInventory("ComeEatMeDemon", 1, "MeleeDown");
			SARG E 6 A_FaceTarget;
			SARG F 6 A_FaceTarget;
			SARG G 12
			{
				actor a = doomb_cheap_melee_attack(60, random(16, 40), "eat");
			
				if(a && a.health <= 0)
				{
					name type = a.getclassname();

					switch(type)
					{
						case 'doomb_zombie_Man':
							a.destroy();
							setstatelabel("FatalityZombieman");
						break;

						default: break;
					}
				}
			}

			TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
			TNT1 A 0
			{
				if(target && target.health <= 0)
				{
					name tn = target.getclassname();
					switch(tn)
					{
						case 'doomb_commando': setstatelabel("FatalityComando"); break;

						default: break;
					}
				}
			}
			TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
		Goto see;
			
		MeleeDown:
			PDEV AB 6 A_FaceTarget;
			PDEV C 12 
			{
				actor a = doomb_cheap_melee_attack(60, random(16, 40), "eat");
			
				if(a && a.health <= 0)
				{
					name type = a.getclassname();

					switch(type)
					{
						case 'doomb_zombie_Man':
							a.destroy();
							setstatelabel("FatalityZombieman");
						break;

						default: break;
					}
				}
			}

			TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
		Goto see;
			
		Pain.punch:
		Pain:
			SARG H 2;
			SARG H 2 A_Pain;
		Goto see;
			
			
		Pain.Shotgun:
			TNT1 A 0 A_Pain;
			TNT1 A 0;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (2);
			SARG H 2;
			SARG H 2;
			Goto see;
			
		Pain.Kick:
		Pain.HeavyImpact:
			SARG A 1 A_Pain;
			SARG A 1 A_FaceTarget;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (15);
			SARG H 4;
			SARG H 4;
		Goto see;
	
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Jump(96, "LeftDeath", "death_1");
			SARG I 8;
			SARG J 8 A_Scream;
			SARG K 4;
			SARG L 4 A_NoBlocking;
			SARG M 4;
			TNT1 A 0 doomb_severed_limb("DeadDemon1", limb_ignore_cvar: true);
			TNT1 A 0 doomb_spawn_bloodpool();
		Stop;

		death_1:
			TNT1 A 0 doomb_much_blood();
			TNT1 A 0 doomb_severed_limb("XDeathDemonArm", (0, 0, 35), doomb_random_velocity(5) );
			SAAR A 8 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			SAAR B 8 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_severed_limb("PoorPinkyLostHisArm", limb_ignore_cvar: true);
		Stop;
			
		LeftDeath:
			S2RG I 8;
			S2RG J 8 A_Scream;
			S2RG K 4;
			S2RG L 4 A_NoBlocking;
			S2RG M 4;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_severed_limb("DeadDemon1Left", limb_ignore_cvar: true);
		Stop;
			
		Death.Kick:
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil(5);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			TNT1 A 0 A_Jump(96, "LeftDeath");
			SARG I 8;
			SARG J 8 A_Scream;
			SARG K 4;
			SARG L 4 A_NoBlocking;
			SARG M 4;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_severed_limb("DeadDemon1", limb_ignore_cvar: true);
		Stop;
			
		
		Death.Shotgun:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(200, "Death.Strong");
		Goto Death+4;
			
		Death.Strong:
			TNT1 A 0 A_Jump(128, "DeathRemoveArm");
			TNT1 A 0 A_FaceTarget;
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AAAAAAAAA 0 doomb_severed_limb("SmallBrainPiece", (0, 0, 60), doomb_random_velocity(5)) ;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_much_blood(60);
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 50) );
			TNT1 A 0 doomb_severed_limb("BaronHeadPiece", (0, 0, 52), doomb_random_velocity(5)) ;
			SARH AAAAAAA 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SARH BBBBBB 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			SARH CCCCCC 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			SARH DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_severed_limb("DeadDemonNoHead", limb_ignore_cvar: true);
		Stop;
			
		Death.Saw:
			TNT1 A 0 A_Jump(32, "Death");
			TNT1 A 0 doomb_severed_limb("XDeathStomach", (0, 0, 60), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			SARG O 8;
			SARG P 8 A_Scream;
			SARG Q 4 A_NoBlocking;
			SARG RRSSTT 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			SARG TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SARG T -1;
		Stop;
			
		Death.Cut:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(32, "Death");
			TNT1 A 0 doomb_severed_limb("XDeathHalfDemon", (0, 0, 60), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("XDeathStomach", (0, 0, 60), doomb_random_velocity(5) );
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			SARC AAABBBCCCDDD 3 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			SARC DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SARC D 0 doomb_severed_limb("DeadDemonHalf23", limb_ignore_cvar: true);
		Stop;
			
			
		Death.Blast:
		Death.SSG:
			SARC A 1 A_Pain;
			SARC A 1 A_FaceTarget;
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 A 0 doomb_gore_spawner(null, (0, 0, 35), 6);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 42) );
			TNT1 A 0 doomb_severed_limb("BaronHeadPiece", (0, 0, 52), doomb_random_velocity(5)) ;
			TNT1 A 0 doomb_severed_limb("PinkyJaw", (0, 0, 5), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("XDeathDemonArm", (0, 0, 35), doomb_random_velocity(5) );
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			SARC AAABBBCCCDDD 3 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			SARC DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SARC D 0 doomb_severed_limb("DeadDemonHalf23", limb_ignore_cvar: true);
		Stop;

		Death.punch:
			TNT1 A 0 ThrustThingZ(0,45,0,1);
		Goto Death.SSG;
			TNT1 A 0 A_ClearTarget;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			POSL A 1 A_Chase(null, null);
			POSL A 1 A_Pain;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil(8);
			TNT1 A 0 ThrustThingZ(0,45,0,1);
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			POSL ABCDE 6;
			POSL F -1;
		Stop;
			
		Death.CutLEss:
			TNT1 A 0;
			TNT1 A 0 A_Jump(32, "Death.Cut");
			TNT1 A 0 A_Jump(132, "DeathRemoveArm");
		Goto Death;


		Crush:
		Death.Stomp:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			SARG IJKL 2;
			TNT1 AA 0 doomb_Meat_Death_Small();
			TNT1 A 0 doomb_gore_spawner('blood_mist', times:6);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_severed_limb("CrushedRemains", limb_ignore_cvar: true);
			TNT1 A 1 A_XScream;
		Stop;
			
		DeathRemoveArm:
		Goto Death+14;
			
		Death.Plasma:
		Death.Plasma2:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_severed_limb("Ashes1", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_severed_limb("XDeathBurnedDemonArm", (0, 0, 32), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("XDeathBurnedDemonLeg", (0, 0,32), doomb_random_velocity(5) );
			TNT1 A 0 doomb_spawn_burned_flesh;
			SPRG ABCDEF 6;
			CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 10 doomb_show_effect("AltSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
			CARB J -1;
		Stop;
			
		Death.Fire:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0doomb_severed_limb ("BurningDemon", limb_ignore_cvar:true );
		Stop;
			
			
			
		Death.BHFT:
		Death.BHFT:
		Death.RVFT:
			TNT1 A 1 A_Pain;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("DemonFatality", 1);
		Stop;
			
		XDeath:
		DEath.Explosive_Impact:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_FaceTarget;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_severed_limb("BullXDeath");
		Stop;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_noblocking;
			TNT1 A 0 ThrustThingZ(0,25,0,1);
			TNT1 A 0 A_FaceTarget;
			TNT1 A 1;
			TNT1 A 0 A_JumpIf(vel != (0, 0, 0), "Blown_Away");
		Goto XDeath;

		Blown_Away:
			TNT1 A 0 A_NoBlocking;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_severed_limb("XDeathStomach", (0, 0, 52), doomb_random_velocity(5)) ;
			TNT1 A 0 doomb_severed_limb("PinkyJaw", (0, 0, 5), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("XDeathDemonArm", (0, 0, 35), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("XDeathBullLeg12", (0, 0, 35), doomb_random_velocity(5) );
			TNT1 A 0 doomb_severed_limb("XDeathPinkyDemonHead", (0, 0, 35), doomb_random_velocity(5) );
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
			TNT1 A 0 ThrustThingZ(0,randompick(-30, 30),0,1);
			TNT1 A 0
			{
				A_Xscream();
				if(vel.x < 0)
					setstatelabel("blown_right");
			}
			SRRD ABCD 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SRRD DDDDDDDDDD 3 A_CheckFloor("LandBlownAwayLeft");
		LandBlownAwayLeft:
			TNT1 A 0 A_Stop;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_severed_limb("doomb_demon_left_half", limb_ignore_cvar: true);
		Stop;
			
		blown_right:
			SRRD FGHI 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SRRD GGGGGGGGGG 3 A_CheckFloor("LandBlownAwayRight");
		LandBlownAwayRight:
			TNT1 A 0 A_Stop;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_severed_limb("doomb_demon_right_half", limb_ignore_cvar: true);
		Stop;
			
			
		Raise:
			SARG NMLKJI 5;
		Goto See;
			
		Pain.Taunt:
			TNT1 A 0;
			Goto See;
			
			
		FatalityZombieman:
			TNT1 A 0 A_SetInvulnerable;
			SARK DEDEDEDEDE 10 doomb_much_blood(45);
			TNT1 A 0 doomb_severed_limb("XDeathHalfZombieManDown", (0, 0, 20) );
			TNT1 A 0 A_UnSetInvulnerable;
		Goto See;
			
			
		FatalitySergeant:
			TNT1 A 0 A_SetInvulnerable;
			SARK FGFGFGFGFG 10 doomb_much_blood(45);
			TNT1 A 0 doomb_severed_limb("XDeathHalfZombieManDown", (0, 0, 20) );
			TNT1 A 0 A_TakeInventory("SergeantFatality",1);
			TNT1 A 0 A_UnSetInvulnerable;
		Goto See;
			
		FatalityComando:
			TNT1 A 0 A_SetInvulnerable;
			SARK JKJKJKJKJK 10 doomb_much_blood(45);
			TNT1 A 0 A_UnSetInvulnerable;
		Goto See;
			
		FatalityImp:
			TNT1 A 0 A_SetInvulnerable;
			SARK HIHIHIHIHI 10 doomb_much_blood(45);
			TNT1 A 0 A_TakeInventory("ImpFatality",1);
			TNT1 A 0 A_UnSetInvulnerable;
		Goto See;
			
			
		Eat:
			TNT1 A 0 A_TakeInventory("EatMe", 1);
			SARK A 20 A_Look;
			TNT1 AAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SARK BA 10 A_Look;
			tnt1 a 0 a_jump(200, "eat");
		Goto Spawn;

		Death.Eat:
			TNT1 A 0 A_GiveToTarget("EatMe",1);
			Goto Death+3;
		Stop;









		Death.Fatality:
			tnt1 A 0 doomb_monster_fatality_camera(target);
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(256, "Demon_fatality_1", "Demon_fatality_2", "Demon_fatality_3");
				
		Demon_fatality_1:
			FDEM A 4;
			FDEM B 4 A_PlaySound("demon/melee");
			FDEM C 8;
			FDEM C 1 A_PlaySound("demon/pain");
			FDEM CDCDCD 3;
			tnt1 A 0 Radius_Quake (4, 24, 0, 15, 0);
			tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
			tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
			tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
			tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
			tnt1 AAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			tnt1 AAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", (0, 0, 50), doomb_random_velocity(5) );
			FDEM EFGHI 3 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			tnt1 A 0 doomb_severed_limb("XDeathDemonHead", (0, 0, 32), doomb_random_velocity(5) );
			tnt1 A 0
			{
				A_Givetotarget("HealthBonus",10);
				doomb_severed_limb("DyingDemon", limb_ignore_cvar: true);
				doomb_destroy_monster_fatality_camera();
			}
		stop;
	
	Demon_fatality_2:
		FDEM J 2;
		FDEM J 5 A_PlaySound("demon/pain");
		FDEM J 9;
		FDEM K 7;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 AAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 AAAAAAAAAA 0 doomb_for_khorne("PlayerFlyingBlood", (0, 0, 50), doomb_random_velocity(5) );
		tnt1 A 0 doomb_severed_limb("XDeathStomach", (0, 0, 32), doomb_random_velocity(5) );
		FDEM LMNO 6;
		tnt1 A 0
		{
			A_Givetotarget("HealthBonus",10);
			doomb_severed_limb("DeadDemonHalf", limb_ignore_cvar: true);
			doomb_destroy_monster_fatality_camera();
		}
	Stop;
	
	Demon_fatality_3:
		FD2M A 2;
		FDEM J 0 A_PlaySound("demon/pain");
		FD2M A 10;
	punch_loop:
		FD2M B 4;
		FD2M C 3;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 A_PlaySound("demon/pain");
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 1);
		FD7M B 4;
		FD2M A 6;
		tnt1 a 0 a_jump(100, 1);
	loop;
		
		FD2M AD 3;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 A_PlaySound("demon/pain");
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 1);
		FD2M E 4;
		FD2M F 15;
		FD2M GHHH 4;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 AAA 0 doomb_for_khorne("brutal_blood", vel_dir: doomb_random_velocity(5) );
		tnt1 A 0 doomb_severed_limb("MeatDeath");
		FD2M IJJJJ 5;
	
		tnt1 A 0
		{
			A_Givetotarget("HealthBonus",10);
			doomb_severed_limb("DeadDemonStomped", limb_ignore_cvar: true);
			doomb_destroy_monster_fatality_camera();
		}
	Stop;
}

}

//FIXME dummy inventory item
class DemonFatality : inventory{}