//===========================================================================
//
// Demon
//
//===========================================================================

CLASS EatMe : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}

CLASS doomb_pinky : doomb_monster_base
{ 
	Default {
		
		GibHealth 35;
		//Radius 30
		Health 200;
		Scale 1.1;
		Height 56;
		Radius 22;
		Mass 400;
		Speed 11;
		FastSpeed 11;//yes, his fast speed is slower because it would make him sanic fast if it was default.
		PainChance "Saw", 200;
		PainChance "Cut", 200;
		PainChance "Kick", 255;
		damagefactor "Crush", 10.0;
		damagefactor "SSG", 5.0;
		damagefactor "SSG", 5.0;

		+CANPASS;
		Monster;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		+FLOORCLIP;
		
		SeeSound "demon/sight";
		AttackSound "demon/melee";
		PainSound "demon/pain";
		DeathSound "demon/death";
		ActiveSound "PINKIDL";
		BloodType "Brutal_Blood",  "SawBlood";
		DamageType "Eat";
		MaxStepHeight 32;
		MaxDropOffHeight 32;
		DropItem "DemonStrengthRune", 2;
		damagefactor "cut", 0.7;
		damagefactor "saw", 0.7;
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
		Spawned:
			TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
			SARG YZYZYZYZYZ 10 A_Look;
		Loop;
			
		Forget:
			TNT1 A 0 A_ClearTarget;
		SearchPlayer:
		Idle:
			SARG YZ 10 A_Look;
			TNT1 A 0 A_SetAngle(angle - 40);
			SARG YZ 10 A_Look;
			TNT1 A 0 A_SetAngle(angle + 40);
			SARG YZ 10 A_Look;
			
			
			SARG AABBCCDD 2
			{
				A_Wander();
				A_Look();
			}
		Goto SearchPlayer;
			
		See:
		SeeContinue:
			TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
			TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
			SARG AABBCCDD 2 A_Chase;
			TNT1 A 0 A_JumpIfInTargetInventory("IsInvisible", 1, "Idle");
			tnt1 a 0 doomb_monster_memory();
		Loop;
			
		Melee:
			TNT1 A 0 doomb_update_memory();
			TNT1 A 0 A_JumpIfInTargetInventory("ComeEatMeDemon", 1, "MeleeDown");
			SARG E 6 A_FaceTarget;
			SARG F 6 A_FaceTarget;
			SARG G 12
			{
				actor a = doomb_cheap_melee_attack(60, random(16, 40), "eat");
			
				if(a && a.health <= 0)
				{
					name type = a.getclassname();

					switch(type)
					{
						case 'doomb_zombie_Man':
							a.destroy();
							setstatelabel("FatalityZombieman");
						break;

						default: break;
					}
				}
			}

			TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
			TNT1 A 0
			{
				if(target && target.health <= 0)
				{
					name tn = target.getclassname();
					switch(tn)
					{
						case 'doomb_commando': setstatelabel("FatalityComando"); break;

						default: break;
					}
				}
			}
			TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
		Goto SeeContinue;
			
		MeleeDown:
			PDEV AB 6 A_FaceTarget;
			PDEV C 12 
			{
				actor a = doomb_cheap_melee_attack(60, random(16, 40), "eat");
			
				if(a && a.health <= 0)
				{
					name type = a.getclassname();

					switch(type)
					{
						case 'doomb_zombie_Man':
							a.destroy();
							setstatelabel("FatalityZombieman");
						break;

						default: break;
					}
				}
			}

			TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
			TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
		Goto SeeContinue;
			
		Pain:
			SARG H 2;
			SARG H 2 A_Pain;
			Goto SeeContinue;
			
		Pain.punch:
			SARG H 3;
			SARG H 3 A_Pain;
			Goto SeeContinue;
			
			
			
		Pain.Shotgun:
			TNT1 A 0 A_Pain;
			TNT1 A 0;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (2);
			SARG H 2;
			SARG H 2;
			Goto SeeContinue;
			
		Pain.Kick:
		Pain.HeavyImpact:
			SARG A 1 A_Pain;
			SARG A 1 A_FaceTarget;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil (15);
			SARG H 4;
			SARG H 4;
			Goto SeeContinue;
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Jump(96, "LeftDeath");
			TNT1 A 0 A_Jump(96, 13);
			TNT1 AAA 0;
			SARG I 8;
			SARG J 8 A_Scream;
			SARG K 4;
			SARG L 4 A_NoBlocking;
			SARG M 4;
			TNT1 A 0 A_SpawnItem ("DeadDemon1", 1);
			TNT1 A 0 doomb_spawn_bloodpool();
			Stop;
			TNT1 AAAAAAAAA 0;
			TNT1 A 0 doomb_much_blood();
			TNT1 A 0 A_SpawnProjectile ("XDeathDemonArm", 35, 0, random (0, 360), 2, random (0, 160));
			SAAR A 8 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			SAAR B 8 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItemEx ("PoorPinkyLostHisArm",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Stop;
			
		LeftDeath:
			S2RG I 8;
			S2RG J 8 A_Scream;
			S2RG K 4;
			S2RG L 4 A_NoBlocking;
			S2RG M 4;
			TNT1 A 0 A_SpawnItem ("DeadDemon1Left", 1);
			TNT1 A 0 doomb_spawn_bloodpool();
			Stop;
			
		CleanDeath:
			TNT1 A 0;
			TNT1 A 0 A_Jump(96, "LeftDeath");
			SARG I 8;
			SARG J 8 A_Scream;
			SARG K 4;
			SARG L 4 A_NoBlocking;
			SARG M 4;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("DeadDemon1", 1);
			Stop;
			
		Death.Kick:
			TNT1 A 0;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil(5);
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			Goto CleanDeath;
			
		Death.Shotgun:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(200, "Death.Strong");
			Goto Death+4;
			
		Death.Strong:
			TNT1 A 0;
			TNT1 A 0 A_Jump(128, "DeathRemoveArm");
			TNT1 A 0 A_FaceTarget;
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("SmallBrainPiece", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_much_blood(60);
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 50) );
			TNT1 A 0 A_SpawnProjectile ("BaronHeadPiece", 52, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			SARH AAAAAAA 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SARH BBBBBB 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			SARH CCCCCC 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			SARH DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnItem("DeadDemonNoHead");
			Stop;
			
		Death.Saw:
			TNT1 A 0 A_Jump(32, "Death");
			TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			SARG O 8;
			SARG P 8 A_Scream;
			SARG Q 4 A_NoBlocking;
			SARG RRSSTT 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			SARG TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SARG T -1;
			Stop;
			
		Death.Cut:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(32, "Death");
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfDemon", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			SARC AAABBBCCCDDD 3 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			SARC DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SARC D 0 A_SpawnItem("DeadDemonHalf23");
			Stop;
			
			
		Death.Blast:
		Death.SSG:
			SARC A 1 A_Pain;
			SARC A 1 A_FaceTarget;
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 A 0 doomb_gore_spawner('SuperGore', (0, 0, 35), 6);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 42) );
			TNT1 AA 0 A_SpawnProjectile ("BaronHeadPiece", 42, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PinkyJaw", 42, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathDemonArm", 32, 0, random (170, 190), 2, random (0, 40));
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			SARC AAABBBCCCDDD 3 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			SARC DDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDDD 2 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SARC D 0 A_SpawnItem("DeadDemonHalf23");
			Stop;
			
		Death.punch:
			TNT1 A 0 ThrustThingZ(0,45,0,1);
		Goto Death.SSG;
			TNT1 A 0 A_ClearTarget;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			POSL A 1 A_Chase(null, null);
			POSL A 1 A_Pain;
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_Recoil(8);
			TNT1 A 0 ThrustThingZ(0,45,0,1);
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			POSL ABCDE 6;
			POSL F -1;
		Stop;
			
		Death.CutLEss:
			TNT1 A 0;
			TNT1 A 0 A_Jump(32, "Death.Cut");
			TNT1 A 0 A_Jump(132, "DeathRemoveArm");
			Goto Death;
			
			
		Crush:
		Death.Stomp:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			SARG IJKL 2;
			TNT1 AA 0 doomb_Meat_Death_Small();
			TNT1 A 0 doomb_gore_spawner('SuperGore', times:6);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem ("CrushedRemains");
			TNT1 A 1 A_XScream;
		Stop;
			
		DeathRemoveArm:
			Goto Death+14;
			
		Death.Plasma:
		Death.Plasma2:
			TNT1 A 0;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Ashes1", 32, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedDemonArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedDemonLeg", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_spawn_burned_flesh;
			SPRG ABCDEF 6;
			CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 10 doomb_show_effect("AltSmoke", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
			CARB J -1;
			Stop;
			
		Death.Fire:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem ("BurningDemon", 0, 10);
			Stop;
			
			
			
		Death.BHFT:
		Death.BHFT:
		Death.RVFT:
			TNT1 A 1 A_Pain;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_GiveToTarget("DemonFatality", 1);
			TNT1 A 0;
			Stop;
			
		XDeath:
		DEath.Explosive_Impact:
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_FaceTarget;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 A_SpawnProjectile ("BullXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			Stop;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_noblocking;
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,25,0,1);
			TNT1 A 0 A_FaceTarget;
			TNT1 A 1;
			TNT1 A 0 A_JumpIf(angle < 180, "IsFacingNorth");
			TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayRight");
			TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayLeft");
			Goto XDeath;
		IsFacingNorth:
			TNT1 A 0 A_JumpIf(vel.x > 0, "BlownAwayRight");
			TNT1 A 0 A_JumpIf(vel.x < 0, "BlownAwayLeft");
			Goto XDeath;
			
		BlownAwayLeft:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBullLeg12", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathDemonArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathPinkyDemonHead", 42, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 A_Xscream;
			SRRD ABCD 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SRRD DDDDDDDDDD 3 A_CheckFloor("LandBlownAwayLeft");
		LandBlownAwayLeft:
			TNT1 A 0 A_Stop;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadDemonSRRDE");
			Stop;
			
		BlownAwayRight:
			TNT1 A 0 A_NoBlocking;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathBullLeg12", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathDemonArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathPinkyDemonHead", 42, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 40) );
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			TNT1 A 0 A_Xscream;
			SRRD FGHI 5 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SRRD GGGGGGGGGG 3 A_CheckFloor("LandBlownAwayRight");
		LandBlownAwayRight:
			TNT1 A 0 A_Stop;
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 0 A_SpawnItem("DeadDemonSRRDJ");
			Stop;
			
			
		Raise:
			SARG NMLKJI 5;
		Goto See;
			
		Pain.Taunt:
			TNT1 A 0;
			Goto See;
			
			
		FatalityZombieman:
			TNT1 A 0 A_SetInvulnerable;
			SARK DEDEDEDEDE 10 doomb_much_blood(45);
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieManDown", 20, 0, random(0, 360), 2, random (0, 160));
			TNT1 A 0 A_UnSetInvulnerable;
		Goto See;
			
			
		FatalitySergeant:
			TNT1 A 0 A_SetInvulnerable;
			SARK FGFGFGFGFG 10 doomb_much_blood(45);
			TNT1 A 0 A_SpawnProjectile ("XDeathHalfZombieManDown", 20, 0, random(0, 360), 2, random (0, 160));
			TNT1 A 0 A_TakeInventory("SergeantFatality",1);
			TNT1 A 0 A_UnSetInvulnerable;
		Goto See;
			
		FatalityComando:
			TNT1 A 0 A_SetInvulnerable;
			SARK JKJKJKJKJK 10 doomb_much_blood(45);
			TNT1 A 0 A_UnSetInvulnerable;
		Goto See;
			
		FatalityImp:
			TNT1 A 0 A_SetInvulnerable;
			SARK HIHIHIHIHI 10 doomb_much_blood(45);
			TNT1 A 0 A_TakeInventory("ImpFatality",1);
			TNT1 A 0 A_UnSetInvulnerable;
		Goto See;
			
			
		Eat:
			TNT1 A 0 A_TakeInventory ("EatMe", 1);
			SARK A 20 A_Look;
			TNT1 AAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 AA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			SARK BA 10 A_Look;
			tnt1 a 0 a_jump(240, "eat");
		Goto Spawn;

		Death.Eat:
			TNT1 A 0 A_GiveToTarget("EatMe",1);
			Goto Death+3;
		Stop;









		Death.Fatality:
			tnt1 A 0 doomb_monster_fatality_camera(target);
			TNT1 A 0 A_Pain;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Jump(256, "Demon_fatality_1", "Demon_fatality_2", "Demon_fatality_3");
			
	Demon_fatality_1:
		FDEM A 4;
		FDEM B 4 A_PlaySound("demon/melee");
		FDEM C 8;
		FDEM C 1 A_PlaySound("demon/pain");
		FDEM CDCDCD 3;
		tnt1 A 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
		FDEM EFGHI 3 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 A 0 A_SpawnProjectile ("XDeathDemonHead", 32, 0, 90, 2, random (0, 90));
		tnt1 A 0
		{
			A_Givetotarget("HealthBonus",10);
			A_SpawnItem ("DyingDemon", 1);
			doomb_destroy_monster_fatality_camera();
		}
	stop;
	
	Demon_fatality_2:
		FDEM J 2;
		FDEM J 5 A_PlaySound("demon/pain");
		FDEM J 9;
		FDEM K 7;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 ACS_Execute(580, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(581, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(582, 0, 0, 0, 0);
		tnt1 A 0 ACS_Execute(583, 0, 0, 0, 0);
		tnt1 AAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 40, 0, random (0, 360), 2, random (50, 130));
		TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		tnt1 AAAAAAAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeathStomach", 32, 0, random (0, 360), 2, random (0, 160));
		FDEM LMN 6;
		FDEM OO 3;
		tnt1 A 0
		{
			A_Givetotarget("HealthBonus",10);
			A_SpawnItem ("DeadDemonHalf", 1);
			doomb_destroy_monster_fatality_camera();
		}
	Stop;
	
	Demon_fatality_3:
		FD2M A 2;
		FDEM J 0 A_PlaySound("demon/pain");
		FD2M A 10;
	punch_loop:
		FD2M B 3;
		FD7M B 1;
		FD2M C 3;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 A_PlaySound("demon/pain");
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 1);
		tnt1 A 0 A_SpawnItem("Blood", 0, 20);
		FD7M B 1;
		FD2M B 3;
		FD2M A 6;
		tnt1 a 0 a_jump(100, 1);
	loop;
		
		FD2M AD 3;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 A 0 A_PlaySound("demon/pain");
		tnt1 A 0 A_PlaySound("player/cyborg/fist", 1);
		tnt1 A 0 A_SpawnItem("Blood", 0, 5);
		FD2M E 4;
		FD2M F 15;
		FD2M GHHH 4;
		tnt1 a 0 Radius_Quake (4, 24, 0, 15, 0);
		tnt1 AAA 0 A_SpawnItem("Blood", 0, 5);
		tnt1 A 0 A_SpawnItem("MeatDeath", 0, 1);
		FD2M IJJJJ 5;
	
		tnt1 A 0
		{
			A_Givetotarget("HealthBonus",10);
			A_SpawnItem ("DeadDemonStomped", 1);
			doomb_destroy_monster_fatality_camera();
		}
	Stop;
}
}


class DemonFatality : inventory{}