CLASS ArmlessDemon : doomb_pinky
{ 
	Default {
		
		Health 100;
		+LOOKALLAROUND;
		+NOPAIN;
	}

	private void doomb_blood_loss()
	{
		if(random(0, 10) <= 2)
			damagemobj(self, self, 1, 'none');
	}

	States
	{
		
		Pain.Taunt:
			TNT1 A 0;
			Goto See;
			
		Idle:
		Spawn:
			SG1A A 2
			{
				A_Look();
				doomb_blood_loss();
				A_SpawnProjectile ("Brutal_LiquidBlood", 42, 0, random (0, 360), 2, random (0, 45));
			}
		Loop;
		
		See:
			SG1A AABBCCDD 2
			{
				A_Chase();
				A_Recoil(-2);
				A_SpawnProjectile ("Brutal_LiquidBlood", 42, 0, random (0, 360), 2, random (0, 45));
			}
			TNT1 A 0 doomb_blood_loss();
		Loop;

		Melee:
			TNT1 A 0 doomb_blood_loss();
			SG1A E 3 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("Brutal_LiquidBlood", 42, 0, random (0, 360), 2, random (0, 45));
			SG1A E 3 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("Brutal_LiquidBlood", 42, 0, random (0, 360), 2, random (0, 45));
			SG1A F 3 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("Brutal_LiquidBlood", 42, 0, random (0, 360), 2, random (0, 45));
			SG1A F 3 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("Brutal_LiquidBlood", 42, 0, random (0, 360), 2, random (0, 45));
			SG1A G 3 doomb_cheap_melee_attack(60, random(16, 40), "eat");
			SG1A GGG 3 A_SpawnProjectile ("Brutal_LiquidBlood", 42, 0, random (0, 360), 2, random (0, 45));
			Goto See;
			
		Death.Shotgun:
		Death.Cutless:
			TNT1 A 0;
			TNT1 A 0 A_FaceTarget;
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 AA 0 A_SpawnProjectile ("XDeathBrain1", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathBrain1", 60, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", random (45, 55), random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", random (45, 55), random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 A 0 doomb_much_blood(60);
			TNT1 A 0 A_SpawnProjectile ("BaronHeadPiece", 52, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Bloodmist", 50, 0, random (0, 360), 2, random (30, 90));
			TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
			SAAR GGGGGGG 2 A_SpawnProjectile ("Brutal_LiquidBlood", 40, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			SAAR HHHHHHHHH 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (30, 110));
			TNT1 A 0 doomb_spawn_bloodpool();
			SAAR IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 2 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, random (0, 360), 2, random (30, 110));
			SAAR I 0 A_SpawnItem("DeadDemonSAARI");
			Stop;
			
		Death:
		Death.Kick:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			SAAR BCDEF 5;
			TNT1 A 0 A_SpawnItem ("DeadDemonNoArm", 5);
			TNT1 A 0 doomb_spawn_bloodpool();
			Stop;
	}
}



CLASS DeadDemon1: CurbstompedMarine Replaces DeadDemon { 
	Default {
		
		Radius 18;
		Height 12;
		Scale 1.1;
		+SHOOTABLE;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		+FLOORCLIP;
		-SOLID;
		-THRUACTORS;
		+SHOOTABLE;
		-GHOST;
		-THRUGHOST;
		Species "Marines";
		damagefactor "Crush", 50.0;
		Mass 9000;
		Health 300;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			SARG N -1;
			Stop;
		Raise:
			SARG N 5;
			SARG MLKJI 5;
			TNT1 A 0 A_SpawnItem ("doomb_pinky", 3);
			Stop;
		Death:
			TNT1 A 0 A_FaceTarget;
			TNT1 A 0 A_NoBlocking;
			tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 AAA 0 A_SpawnProjectile ("XDeathBrain1", 20, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("XDeathBrain1", 20, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", random (25, 35), random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", random (25, 35), random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 A 0 doomb_much_blood(20);
			TNT1 A 0 A_SpawnProjectile ("BaronHeadPiece", 22, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Bloodmist", 20, 0, random (0, 360), 2, random (30, 90));
			TNT1 A 0 A_SpawnItem("DeadDemonNoHead");
			Stop;
			
	Death.Plasma: Death.Plasma2:
		TNT1 A 0;
		TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
		EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 10 doomb_show_effect("AltSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		CARB J -1;
		Stop;
}

}

CLASS DeadDemonHalf: DeadDemon1 { 
	Default {
	
	Health 300;
	}
States
{
	Spawn:
		SARG T -1;
		Stop  ;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 A_SpawnProjectile ("XDeathBullLeg12", 35, 0, random (0, 360), 2, random (10, 40));
		TNT1 AA 0 A_SpawnProjectile ("XDeathDemonArm", 35, 0, random (0, 360), 2, random (10, 40));
		TNT1 AA 0 doomb_Meat_Death_Small();
		Stop;
	}
}		
CLASS DeadDemonHalf23 : DeadDemon1
{ 
	Default
	{
	
	Health 300;
	Height 16;
	}
States
{
	Spawn:
		SARC D -1;
		Stop  ;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 A_SpawnProjectile ("XDeathBullLeg12", 35, 0, random (0, 360), 2, random (10, 40));
		TNT1 AA 0 doomb_Meat_Death_Small();
		Stop;
}

}

CLASS DeadDemonNoArm : DeadDemon1
{ 
	Default {
	Health 300;
	}
States
{
	Spawn:
		SAAR F -1;
	Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("XDeathDemonArm", 35, 0, random (0, 360), 2, random (10, 40));
		TNT1 AA 0 doomb_Meat_Death_Small();
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 A 0 doomb_Meat_Death_Small();
		TNT1 AAA 0 A_SpawnProjectile ("XDeathBrain1", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 A_SpawnProjectile ("XDeathBrain1", 20, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath3", random (25, 35), random (5, -5), random (160, 200), 2, random (-10, 10));
		TNT1 AA 0 A_SpawnProjectile ("XDeath2", random (25, 35), random (5, -5), random (160, 200), 2, random (-10, 10));
		TNT1 A 0 doomb_much_blood(20);
		TNT1 A 0 A_SpawnProjectile ("BaronHeadPiece", 22, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("Bloodmist", 20, 0, random (0, 360), 2, random (30, 90));
		TNT1 A 0 A_SpawnItem("DeadDemonSAARK");
		Stop;
		
}

}	  
	  
CLASS DeadDemonSAARK: DeadDemon1 { 
	Default {
	
	Health 300;
	}
States
{
	Spawn:
		SAAR K -1;
		Stop   ;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 AA 0 A_SpawnProjectile ("XDeathBullLeg12", 35, 0, random (0, 360), 2, random (10, 40));
		TNT1 AA 0 doomb_Meat_Death_Small();
		Stop;
		
}
		}	  

CLASS DeadDemonNoHead: DeadDemon1 { 
	Default {
	
	Health 300;
	}
States
{
	Spawn:
		SARH D -1;
		Stop   ;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeathDemonArm", 35, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnProjectile ("PinkyJaw", 22, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 A_SpawnItem("DeadDemonHalf23");
		Stop;
		
}

}		
		
CLASS DeadDemon1Left: DeadDemon1 { 
	Default {
	
	}
States
{
	Spawn:
		S2RG N -1;
		Stop;
}
}

CLASS DeadDemonStomped: DeadDemonNoARm { 
	Default {
	
	}
States
{
	Spawn:
		FD2M K -1;
		Stop;
		
}
		}	




CLASS DeadDemonSRRDJ: DeadDemon1 { 
	Default {
	
	}
States
{
	Spawn:
		SRRD J -1;
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 60, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathDemonArm", 35, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathBullLeg12", 35, 0, random (0, 360), 2, random (10, 40));
		TNT1 AA 0 doomb_Meat_Death_Small();
		Stop;
}
}	

CLASS DeadDemonSRRDE: DeadDemon1 { 
	Default {
	
	}
States
{
	Spawn:
		SRRD E -1;
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 60, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathDemonArm", 35, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathBullLeg12", 35, 0, random (0, 360), 2, random (10, 40));
		TNT1 AA 0 doomb_Meat_Death_Small();
		Stop;
}
}	



CLASS DeadDemonSAARI: DeadDemon1 { 
	Default {
	
	}
States
{
	Spawn:
		SAAR I -1;
		Stop;
		
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 60, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathDemonArm", 35, 0, random (0, 360), 2, random (10, 40));
		TNT1 A 0 A_SpawnProjectile ("PinkyJaw", 22, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_Meat_Death_Small();
		TNT1 A 0 A_SpawnItem("DeadDemonHalf23");
		Stop;
}
}


CLASS PoorPinkyLostHisArm: doomb_body_base { 
Default {
	Height 56;
	Radius 22;
	Health 50;
	+NOPAIN;
	-COUNTKILL;
	+SHOOTABLE;
	Scale 1.1;
}

States
{
	Spawn:
		SAAR J 1;
		TNT1 A 0 A_Pain;
		TNT1 A 0 A_Jump(32, "Colapse");
		SAAR JJJJ 4 A_SpawnProjectile ("Brutal_LiquidBlood", 42, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_Jump(90, "PutAFight");
		SAAR JJJJ 4 A_SpawnProjectile ("Brutal_LiquidBlood", 42, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_Pain;
		SAAR JJJJJJJJ 4 A_SpawnProjectile ("Brutal_LiquidBlood", 42, 0, random (0, 360), 2, random (0, 45));
		TNT1 A 0 A_Pain;
		SAAR JJJ 4 A_SpawnProjectile ("Brutal_LiquidBlood", 42, 0, random (0, 360), 2, random (0, 45));
		Goto Colapse;
		
	PutAFight:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItemEx ("ArmlessDemon",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0;
	Stop;

	Death.Shotgun:
	Death.Cutless:
	Death:
	Death.Fatality:
		TNT1 A 0 A_FaceTarget;
		tnt1 a 0 A_Explode(3,200, 0, 0, 0, 0, 0, "none", "blood");
		TNT1 AA 0 A_SpawnProjectile ("XDeathBrain1", 60, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeathBrain1", 60, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath3", random (45, 55), random (5, -5), random (160, 200), 2, random (-10, 10));
		TNT1 AA 0 A_SpawnProjectile ("XDeath2", random (45, 55), random (5, -5), random (160, 200), 2, random (-10, 10));
		TNT1 A 0 doomb_much_blood(60);
		TNT1 A 0 A_SpawnProjectile ("BaronHeadPiece", 52, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (-10, 10));
		TNT1 AAAA 0 A_SpawnProjectile ("Bloodmist", 50, 0, random (0, 360), 2, random (30, 90));
		SAAR GGGGGGG 2 A_SpawnProjectile ("Brutal_LiquidBlood", 40, 0, random (0, 360), 2, random (30, 110));
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_SpawnItem ("CrueltyBonus5Health");
		SAAR HHHHHHHHH 2 A_SpawnProjectile ("Brutal_LiquidBlood", 30, 0, random (0, 360), 2, random (30, 110));
		TNT1 A 0 doomb_spawn_bloodpool();
		SAAR IIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIII 2 A_SpawnProjectile ("Brutal_LiquidBlood", 20, 0, random (0, 360), 2, random (30, 110));
		TNT1 A 0 A_SpawnItem("DeadDemonSAARI");
		Stop;
		
		
	Colapse:
		TNT1 A 0 A_Scream;
		TNT1 A 0 A_NoBlocking;
		SAAR BCDEF 5;
		TNT1 A 0 A_SpawnItem ("DeadDemonNoArm", 5);
		TNT1 A 0 doomb_spawn_bloodpool();
		Stop;
}
}


CLASS FrozenDemon : doomb_body_base
{ 
	Default {
	
	Health 60;
	Radius 16;
	Height 52;
	+SOLID+SHOOTABLE+NOBLOOD +PUSHABLE;
	
	Radius 22;
	Height 52;
	Health 60;
	}
States
	{
	Spawn:
		FZD5 A 200;
		FZD5 A 2;
		TNT1 A 0 A_PlaySound("ICEBRK1");
		FZD5 A 50;
		FZD5 B 2;
		FZD5 A 50;
		FZD5 B 2;
		FZD5 A 50;
		FZD5 B 2;
		FZD5 A 25;
		FZD5 B 2;
		FZD5 A 25;
		FZD5 B 2;
		FZD5 A 10;
		FZD5 B 2;
		FZD5 A 10;
		FZD5 B 2;
		FZD5 A 10;
		FZD5 BABABA 2;
	Death.Fire:
		TNT1 A 0 A_ChangeCountFlags(false, false);
		TNT1 A 0 A_PlaySound ("DSBOTTLE");
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_spawnItem("Demon");
		Stop;
	Death:
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_PlaySound ("DSBOTTLE");
		TNT1 AAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk2", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("XIceChunk3", 48, 0, random (0, 360), 2, random (40, 120));
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath2", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeath3", 48, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAA 0 doomb_for_khorne("Intestine", (0, 0, 32), (frandom(-10, 10), frandom(-10, 10), frandom(0, 10) ) );
		TNT1 AAA 0 doomb_much_blood(48);
		FZD5 C 300;
		FZD5 CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC 1 A_FadeOut(0.01);
		Stop;
	Death.Freeze:
	Death.Ice:
	Death.Frost:
		TNT1 A 0 A_ChangeCountFlags(false, false);
		TNT1 A 0 A_SpawnItem("FrozenDemon");
		Stop;
}
}


CLASS DyingDemon : doomb_body_base
{ 
	Default {
	
	Radius 8;
	Height 8;
	Speed 0;
	Mass 6;
	+NOBLOCKMAP;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+DONTSPLASH;
	+CLIENTSIDEONLY;
	+FORCEXYBILLBOARD;
	}
    States
    {
	Spawn:
		SARH AAA 4 doomb_spawn_big_blood(50);
		SARH BBB 4 doomb_spawn_big_blood(40);
		SARH CCC 4 doomb_spawn_big_blood( 30);
		SARH DDDDDDDDDDDDDDD 4 doomb_spawn_big_blood(20);
		TNT1 A 0 A_SpawnItem ("DeadDemonNoHead", 1);
		Stop;
}
}


CLASS XDeathBullLeg12: XDeathArm1 { 
	Default {
		
		Scale 1.1;
		Speed 8;
		Gravity 0.4;
		BounceFactor 0.4;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			LEG8 ABCDEFGH 4 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			Loop;
		Death:
			LEG8 I 1;
			LEG8 I 0 A_SpawnItem("Gib_DemonLeg");
			Stop;
	}
}

CLASS Gib_DemonLeg: LimbBase { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			LEG8 GH 2;
		Spawn1:
			LEG8 I 4000 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
			
			
		Death.plasma:
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedDemonLeg", 32, 0, random (0, 360), 2, random (0, 160));
		Stop;
		Death:    
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnProjectile ("GibDemonLegPart", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("GibDemonPaw", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Punch:
			LEG8 A 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathBullLeg12", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			LEG8 ABCDEFGH 2;
			Goto Spawn1;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			LEG8 A 5;
			LEG8 ABCDEFGH 5;
			XDT5 I 0 A_SpawnItem("Gib_DemonLeg");
			Stop;
	}
	
}
CLASS GibDemonLegPart: TinyGib { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			LEG8 Z 1;
			Loop;
		Death:
			LEG8 Z 1;
			Loop;
			
	}
	
}
CLASS GibDemonPaw: TinyGib { 
	Default {
		
		Scale 1.1;
	}
	States
	{
		Spawn:
			LEG8 Y 1;
			Loop;
		Death:
			LEG8 Y 1;
			Loop;
			
	}
	
}


CLASS XDeathDemonHead : doomb_body_base
{ 
	Default {
		Radius 8;
		Height 8;
		Scale 0.9;
		Speed 10;
		Mass 1;
		gravity 0.5;
		Decal "BrutalBloodSplat";
		BounceFactor 0.4;
		BounceCount 5;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			DEMH ABCDEF 7 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			TNT1 A 0 A_SpawnItem("Gib_DemonHead");
			Stop;
	}
}


CLASS XDeathBullArm1: XDeathArm1 { 
	Default {
		
		Scale 1.0;
		Speed 10;
		Gravity 0.4;
		BounceFactor 0.4;
		wallbouncefactor 0.2;
		+SKYEXPLODE;
		Species "Marines";
		+THRUSPECIES;
		BounceCount 5;
		Radius 10;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			HND8 ABCDEFGH 3 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			Loop;
			
		Death.plasma:
		death.Fire:
			TNT1 A 0 A_SpawnProjectile ("XDeathBurnedDemonArm", 32, 0, random (0, 360), 2, random (0, 160));
			Stop;
		Death:
			HND8 I 1;
			HND8 A 0 A_SpawnItem("Gib_DemonArm",0,0,0,1);
			Stop;
	}
}


CLASS XDeathDemonArm: XDeathBullArm1 { 
	Default {
		
		Scale 1.0;
	}
}

CLASS Gib_DemonArm: LimbBase { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			HND8 GH 2;
			Goto Spawn1;
			
		Spawn1:
			HND8 I 40000;
			Loop;
		Death:    
			TNT1 AAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_SpawnProjectile ("GibDemonHand", 0, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("GibDemonArmPart", 0, 0, random (0, 180), 2, random (0, 180));
			Stop;
		Death.Kick:
		Death.Punch:
			HND8 AA 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathBullArm1Kicked", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			HND8 ABCDEFGH 2;
			Goto Spawn1;
			
		Death.Explosive_Impact:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			HND8 A 5;
			HND8 ABCDEFGHABCDEFGHABCDEFGH 5 A_CheckFloor("Landz");
		Landz:
			XDT5 I 0 A_SpawnItem("Gib_DemonArm");
			Stop;
			
	}
	
}

CLASS XDeathBullArm1Kicked: XDeathBullArm1 { 
	Default {
		
		+ACTIVATEMCROSS;
		+ACTIVATEIMPACT;
		+CANUSEWALLS;
	}
}

CLASS GibDemonArmPart: TinyGib { 
	Default {
		
		Scale 1.0;
	}
	States
	{
		Spawn:
			HND8 Z 1;
			Loop;
		Death:
			HND8 Z 1;
			Loop;
			
	}
	
}


CLASS XDeathPinkyDemonHead: XDeathBullArm1 { 
	Default {
		
		-CLIENTSIDEONLY;
		Speed 10;
		Scale 1.3;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIf(waterlevel > 1, "Death");
			TNT1 A 0 A_JumpIf(vel.z == 0, "Death");
			DEMH AB 3;
			DEMH CDEFGH 3;
			Loop;
		Death:
			DEMH I 1;
			DEMH I 1 A_SpawnItem("PinkyDemonHead",0,0,0,1);
			Stop;
	}
}



CLASS PinkyDemonHead: LimbBase { 
	Default {
		
		damagefactor "Kick", 9.0;
		damagefactor "Melee", 9.0;
		-CLIENTSIDEONLY;
		Radius 10;
		
		Mass 60;
		Health 60;
		Scale 1.5;
	}
	States
	{
		Spawn:
			DEMH I 4000 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop;
			
		Death:
			TNT1 AAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			TNT1 AAAA 0 A_SpawnProjectile ("Brains1", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_SpawnProjectile ("jaw", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_SpawnProjectile ("eye", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_SpawnProjectile ("head_piece", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 A 0 A_SpawnProjectile ("head_piece", 5, 0, random (0, 360), 2, random (60, 140));
			TNT1 AAAAAA 0 A_SpawnProjectile ("SmallBrainPiece", 5, 0, random (0, 360), 2, random (60, 140));
			Stop;
		Death.Trample:
		Crush:
			TNT1 AAAAAAAA 0 doomb_for_khorne("Brutal_FlyingBloodTrail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			DEMH I 5;
			DEMH I 9009;
			Stop;
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 doomb_spawn_burned_flesh();
			EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0;
			Stop;
		Death.punch:
		Death.Kick:
			DEMH A 1 A_Pain;
			DEMH A 1 A_FaceTarget;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathPinkyDemonHeadKicked", 5, 0, random (170, 190), 2, random (20, 40));
			TNT1 A 0 A_PlaySound("misc/xdeath4", 1);
			TNT1 A 0 A_PlaySound("player/cyborg/fist", 3);
			TNT1 A 20;
			Stop;
			
		Pain:
			TNT1 A 0;
			TNT1 A 0 ThrustThingZ(0,20,0,1);
			DEMH ACEGI 3;
			Goto Spawn;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 ThrustThingZ(0,30,0,1);
			DEMH ABCDEFGH 3;
			DEMH I 0 A_SpawnItem("PinkyDemonHead");
			Stop;
			
			
	}
	
}


CLASS XDeathHalfDemon : ACTOR { 
	Default {
		
		Radius 8;
		Height 8;
		Scale 1.0;
		Speed 6;
		Mass 4;
		Decal "BrutalBloodSplat";
		BounceFactor 0.2;
		+DOOMBOUNCE;
		+MISSILE;
		+MOVEWITHSECTOR;
		+CLIENTSIDEONLY;
		+NOBLOCKMAP;
		+NOTELEPORT;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			SARC E 12;
			Loop;
		Death:
			TNT1 A 0 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			SARC F 1 A_SpawnItem("Gib_HalfDemon",0,0,0,1);
			TNT1 A 0;
			Stop;
	}
}

CLASS Gib_HalfDemon: BigGibBase { 
	Default {
		
	}
	States
	{
		Spawn:
			SARC F 1900 A_SpawnItem ("Brutal_BloodSpot", 0, 1);
			Loop   ;
	}
	
}	   


CLASS XDeathPinkyDemonHeadKicked: XDeathPinkyDemonHead { 
	Default {
		
		-BOUNCEONACTORS;
		Damage 4;
		Speed 13;
		Scale 1.3;
		BounceFactor 0.4;
	}
}


CLASS GibDemonHand: TinyGib { 
	Default {
		
		Scale 0.9;
	}
	States
	{
		Spawn:
			HND8 Y 1;
			Loop;
		Death:
			HND8 Y 1;
			Loop;
			
	}
	
}

CLASS Gib_DemonHead: LimbBase { 
	Default {
		
		Scale 0.9;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump (128, "Spawn2");
			DEMH I 9;
			DEMH I -1;
			Loop;
		Spawn2:
			DEMH J 9;
			DEMH J -1;
			Loop;
		Death.plasma:
			TNT1 A 0 doomb_spawn_burned_flesh();
			Stop;
		Death:    
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 AA 0 A_SpawnProjectile ("XDeathBrain1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathBrain1", 10, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 10, random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 10, random (5, -5), random (160, 200), 2, random (-10, 10));
			TNT1 AAAA 0 A_SpawnProjectile ("Bloodmist", 10, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 A_SpawnProjectile ("BaronHeadPiece", 12, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("PinkyJaw", 12, 0, random (0, 360), 2, random (0, 160));
		Stop;
			
		Death.Kick:
		Death.punch:
			HND3 A 1 A_FaceTarget;
			TNT1 A 0 A_SpawnProjectile ("XDeathChainArm", 5, 0, random (170, 190), 2, random (20, 40));
			Stop;
	}
	
}

CLASS BurningDemon : doomb_body_base { 
	Default {
	
	Radius 12;
	Height 56;
	Speed 5;
	Scale 0.85;
	Health 100;
	GibHealth 25;
	damagefactor "Fire", 0.0;
	damagefactor "Explosive_Impact", 10.0;
	MONSTER;
	-COUNTKILL;
	+NOICEDEATH;
	+FRIENDLY;
	+FLOORCLIP;
	+SHOOTABLE;
	+NOBLOCKMONST;
	+DONTSPLASH;
	
	Gravity 0.7;
	
	Obituary "%o was near someone in flames.";
	MaxDropOffHeight 6000;
	
	Mass 999999;
	
	}
    States
    {
	Spawn:
		TNT1 A 0 A_PlaySound("BURNZOM");

	Suffer:
		SBRG AAABBBCCCDDD 1 BRIGHT A_Wander;
		TNT1 A 0 A_Recoil(-1);
		TNT1 A 0 A_playsound ("demon/pain");
			tnt1 B 0 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				{Spawn("RedFlare", pos);}
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
				doomb_show_effect("ExplosionParticle2", (0, 0, 40), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (frandom(0.01, 0.04), 0) );
			}
		TNT1 A 0 doomb_random_death;
	Loop;
	
	Death:
		CRB7 Q 2
		{
			A_NoBlocking();
			A_Scream();
			A_playsound ("demon/death");
		}
		CRB7 QQQQRRRR 2 doomb_show_effect("FlameTrails", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 A 0 A_Playsound("props/redfire");
		CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 2 doomb_show_effect("FlameTrails", (0, 0, 25), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		CARB JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJ 20 doomb_show_effect("AltSmoke", (0, 0, 35), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.5, 0) );
		CARB J -1;
	Stop;
		
	XDeath:
	Death.SSG:
	Death.Explosive_Impact:
		TNT1 A 0 A_NOBlocking;
		TNT1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 A_SpawnProjectile ("XDeathBurnedDemonArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("XDeathBurnedDemonLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 doomb_spawn_burned_flesh;
		TNT1 A 0 A_SpawnProjectile ("MuchMeatDeath", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAAAA 0 A_SpawnProjectile ("BurningFlyingMeatPiece", 64, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 a_spawnitemex ("CrueltyBonus5Health");
	Stop;
}
}


CLASS BullXDeath : doomb_body_base { 
	Default {
		Radius 1;
		Height 1;
		Scale 0.8;
		Speed 0;
		Mass 1;
		BounceFactor 0.5;

		+DOOMBOUNCE;
		+MISSILE;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+NOGRAVITY;
		+NOCLIP;
		+DONTSPLASH;
	}
	States
	{
		Spawn:
			tnt1 a 0 A_Explode(3,600, damagetype:"blood");
			TNT1 AAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
			TNT1 AAAAAAAAA 0 A_SpawnProjectile ("CeilBloodLauncher", 0, 0, random (0, 360), 2, random (50, 130));
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath2", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeath3", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece1", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathSkinPiece1", 15, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathStomach", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathBullLeg12", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeathDemonArm", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_SpawnProjectile ("XDeathPinkyDemonHead", 42, 0, random (0, 360), 2, random (0, 160));
			
			TNT1 A 1;
			TNT1 A 2;
			TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("BloodMistExtraBig", 30, 0, random (0, 360), 2, random (20, 90));
			Stop;
	}
}