
CLASS Belphegor : doomb_monster_base {
	Default {
		
		Scale 1.5;
		
		GibHealth 25;
		+NOICEDEATH;
		PainChance "Kick", 255;

		Health 2000;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		BloodType "Brutal_Blood";
		damagefactor "Explosive_Impact", 1.7;
		Obituary "%o was no match for the great Belphegor.";
		MaxStepHeight 24;
		MaxDropOffHeight 32;
		+MISSILEMORE;
		Speed 14;
		
		Height 88;
		Radius 32;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			BOS3 BD 10 A_Look;
			Loop;
		See:
			BOS3 AAAABBBBCCCCBBBB 2 A_Chase;
		Loop;

		Melee:
			BOS3 F 8;
			TNT1 A 0 A_PlaySound("weapons/gswing");
			BOS3 G 8 A_FaceTarget;
			TNT1 AAAA 0 {doomb_cheap_melee_attack(160, 10, "HKFT");}
			BOS3 H 8 A_FaceTarget;
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		Goto See;
			
		Missile:
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			BOS3 FG 8 A_FaceTarget;
			TNT1 A 0 A_JumpIfCloser(150, "Melee2");
			BOS3 H 8 A_SpawnProjectile("BelphegorGreenPlasmaBall", 50, 0, 0, 1);
		Goto See;
			
		Melee2:
			TNT1 AAAA 0 {doomb_cheap_melee_attack(160, 10, "HKFT");}
			TNT1 A 0 A_PlaySound("weapons/gswing");
			BOS3 H 8 A_FaceTarget;
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
		Goto See;
			
		Pain:
			TNT1 A 0 A_JumpIfInventory("Curbstomp_Marine", 1, "CurbstompMarine");
			BOS3 E  3;
			BOS3 E  3 A_Pain;
		Goto See;

		Death.SSG:
		XDeath:
			tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
			TNT1 A 0 doomb_gore_spawner(times:16);
			TNT1 AAAAAAAAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
			TNT1 AA 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, random (0, 160));
			BXDE B 0 A_Scream;
			BXDE C 0 A_bossdeath;
			BXDE D 0 A_NoBlocking;
		Stop;
			
		Death:
			BOS3 I 8 A_Scream;
			BOS3 J 8 A_bossdeath;
			BOS3 K 8 A_NoBlocking;
			BOS3 L -1;
		Stop;
			
			
		Death.Headshot:
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AA 0 A_SpawnProjectile ("jaw", 82, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("eye", 82, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("head_piece_dark", 82, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0 A_bossdeath;
			TNT1 A 0 A_NoBlocking;
			BOS3 MNOPQR 8;
			BOS3 R -1;
			Stop;
			
		Raise:
			BOS3 O 8;
			BOS3 NMLKJI  8;
		Goto See;
		
		Crush:
			TNT1 A 0 A_PlaySound("misc/xdeath4");
			CRS2 C -1;
		Stop;
			
		CurbstompMarine:
			TNT1 A 0 A_SetInvulnerable;
			BS3F AB 10;
			BS3F CDEF 2;
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			BS3F GF 4;
			BS3F HHIII 2;
			BS3F J 15;
			BS3F K 6;
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			TNT1 A 0 doomb_gore_spawner(times:6);
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 A 0 doomb_much_blood();
			TNT1 AAAAA 0 A_SpawnProjectile ("PlayerFlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
			BS3F L 15;
			
			
			BS3F NM 4;
			BS3F N 1 doomb_gore_spawner(times:6);
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 10) );
			TNT1 AAA 0 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			BS3F NOPPP 3;
			
			BS3F NM 4;
			BS3F N 1;
			TNT1 A 0 doomb_gore_spawner(times:6);
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 10) );
			TNT1 AAA 0 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			BS3F NOPPP 3;
			
			BS3F NM 4;
			BS3F N 1;
			TNT1 A 0 doomb_gore_spawner(times:6);
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 10) );
			TNT1 AAA 0 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			BS3F NOPPP 3;
			
			BS3F NM 4;
			BS3F N 1;
			TNT1 A 0 doomb_gore_spawner(times:6);
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 10) );
			TNT1 AAA 0 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			BS3F NOPPP 3;
			
			BS3F NM 4;
			BS3F N 1;
			TNT1 A 0 doomb_gore_spawner(times:6);
			EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 10) );
			TNT1 AAA 0 A_SpawnProjectile ("Blood", 10, 0, random (0, 360), 2, random (30, 90));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			BS3F NOPPP 3;
			
			TNT1 A 0 A_TakeInventory("Curbstomp_Marine");
			TNT1 A 0 A_UnSetInvulnerable;
		Goto See;
			
		Pain.Taunt:
			TNT1 A 0;
			Goto Missile;
		Death.Taunt:
			TNT1 A 0 A_noblocking();
			TNT1 A 0 A_SpawnItem("Belphegor");
			Stop;
		Death.Eat:
			TNT1 A 0 A_GiveToTarget("EatMe",1);
			Goto Death+3;
			Stop;
	}
} 



CLASS DeadBelphegor : doomb_body_base { 
	Default {
		
		Radius 12;
		Height 18;
		Scale 1.2;
		+SHOOTABLE;
		-SOLID;
		+NOTELEPORT;
		+MOVEWITHSECTOR;
		+CORPSE;
		Mass 1000;
		Health 200;
		damagefactor "Blood", 0.0;
		damagefactor "Trample", 0.0;
	}
	States
	{
		Spawn:
			BADD D -1;
			Stop;
		Raise:
			BOS3 O 8;
			BOS3 NMLKJI  8;
			TNT1 A 0 A_SpawnItem ("doomb_knight", 3);
			Stop;
		Death:
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		Stop;

		Death.Plasma: Death.Plasma2:
		Death.Fire:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			EXPL AAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
			BOSB ABCDE 9 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		mini:
			BOSB E 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
			tnt1 a 0 a_jumpif(random(0, 100) < 3, 1);
		loop;
			BOSB E -1;
		Stop;
}

}
CLASS BelphegorGreenPlasmaBall : doomb_boolet_base { 
	Default {
	
	Radius 10;
	Height 16;
	Speed 30;
	FastSpeed 30;
	Projectile;
	+RANDOMIZE;
	+FORCEXYBILLBOARD;
	+THRUGHOST;
	Damage 7;
	RenderStyle "Add";
	Alpha 0.9;
	Scale 1.6;
	SeeSound "baron/attack";
	DeathSound "FAREXPL";
	Decal "Scorch";
	DamageType "Explosive_Impact";
	
	}
States
{
	Spawn:
		TNT1 A 0 A_SpawnItem("GreenFlare22",0,0);
		FRPG K 1 BRIGHT A_SpawnItemEx("GreenExplosionFlameTrail", 0, 0, 0, 0, 0, 0, 0, 128);
	Loop;
	
	Death:
		BFE1 A 0 Bright;
		EXPL A 0 Radius_Quake (2, 54, 0, 15, 0);
		BFE1 A 0 Bright A_Explode(30, 170, 1);
		TNT1 AAAAAAAAA 0 A_SpawnProjectile ("GreenExplosionFire", 2, 0, random (0, 360), 2, random (0, 360));
		EXPL AA 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 BCDEF 2 Bright;
		TNT1 AAAAAAA 2 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
	Stop;
}
}


CLASS GreenExplosionFlameTrail: visual_sfx { 
	Default {
		Radius 1;
		Height 1;
		Speed 3;
		Damage 0;
		+NOBLOCKMAP;
		+NOTELEPORT;
		+DONTSPLASH;
		+MISSILE;
		+FORCEXYBILLBOARD;
		+CLIENTSIDEONLY;
		+NOINTERACTION;
		+NOCLIP;
		RenderStyle "Add";
		DamageType "fire";
		Scale 0.5;
		Alpha 1;
		Gravity 0;

		Scale 2.2;
		Speed 2;

		Scale 0.5;
	}
	States
	{
		Spawn:
			EXPG ABCDEFG 1 BRIGHT;
			Stop;
	}
}