CLASS IsAnEvilMarine : Inventory { 
	Default {
		
		inventory.maxamount 5;
	}
}

CLASS NaziVerification1 : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}

CLASS NaziVerification2 : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}

CLASS TVRRainVerification : Inventory { 
	Default {
		
		inventory.maxamount 30;
	}
}



CLASS Epic2AlienVerification : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}

CLASS AltEasyMarineVerification : Inventory { 
	Default {
		
		inventory.maxamount 1;
	}
}




CLASS EvilMarine : doomb_monster_base Replaces WolfensteinSS { 
	Default {
		
		Health 200;
		Radius 14;
		Height 56;
		Speed 6;
		FastSpeed 6;
		PainChance 200;
		Monster;
		+FLOORCLIP;
		+QUICKTORETALIATE;
		Species "EvilMarines";
		damagefactor "shotgun", 0.6;
		damagefactor "cutless", 0.6;
		damagefactor "saw", 0.8;
		damagefactor "cut", 0.8;
		damagefactor "Explosive_Impact", 0.4;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Avoid", 0.0;
		

		SeeSound "none";
		AttackSound "grunt/attack";
		PainSound "evilmarinepain";
		DeathSound "evilmarinedeath";
		ActiveSound "evilmarineactive";
		Obituary "%o was eliminated by an evil marine.";
		DropItem "PLasmaRifle";
	Translation "112:127=[64,64,64]:[0,0,0]";
	}
	States
	{
	Spawn:
		TNT1 A 0;
		TNT1 A 0 Thing_ChangeTID(0,748);
		MARN A 0 ACS_ExecuteAlways(177, 0, 0, 0, 0);//Check if you are playing on an Wolfenstein level
		TNT1 A 0 A_GiveInventory("IsAnEvilMarine", 1);
		PLAY A 5;
		TNT1 A 0 A_JumpIfInventory("Epic2AlienVerification", 1, "ISEpic2Alien");
		TNT1 A 0 A_JumpIfInventory("NaziVerification1", 1, "VerificateNazi");
		TNT1 A 0 A_JumpIfInventory("AltEasyMarineVerification", 1, "ISEasyMarine");
		
		Goto Steady;
		
	VerificateNazi:
		PLAY A 1;
		TNT1 A 0 A_JumpIfInventory("NaziVerification2", 1, "IsANazi");
		Goto Steady;
		
		
	ISANazi:
		TNT1 A 0;
		TNT1 A 0 A_ChangeCountFlags(true);


		TNT1 A 0 a_noblocking();
		TNT1 A 0 A_SpawnItemEx("Nazi", 0, 0, 28, 0, 0, 0, 0, SXF_TRANSFERPOINTERS | SXF_TRANSFERAMBUSHFLAG);
		Stop;
		
	ISEpic2Alien:
		TNT1 A 0;
		TNT1 A 0 A_ChangeCountFlags(true);


		TNT1 A 0 a_noblocking();
		TNT1 A 0 A_SpawnItemEx("Epic2Alien", 0, 0, 28, 0, 0, 0, 0, SXF_TRANSFERPOINTERS | SXF_TRANSFERAMBUSHFLAG);
		Stop;
		
	ISEasyMarine:
		TNT1 A 0;
		TNT1 A 0 A_ChangeCountFlags(true);


		TNT1 A 0 a_noblocking();
		TNT1 A 0 A_SpawnItemEx("EasyMarine", 0, 0, 28, 0, 0, 0, 0, SXF_TRANSFERPOINTERS | SXF_TRANSFERAMBUSHFLAG);
		Stop;
		
	Idle:
		PLAY AAAAAAA 5 A_Look;
		TNT1 A 0 A_Jump(32, 3);
		TNT1 A 0 A_SetAngle(angle - 40);
		PLAY AA 5 A_Look;
		TNT1 A 0 A_SetAngle(angle + 40);
		PLAY A 5 A_Look;
		TNT1 A 0 A_Jump(32, 3);
		TNT1 A 0 A_SetAngle(angle + 40);
		PLAY AAAABBBBCCCCDDDD 5
		{
			A_Look();
			A_Wander();
		}
	Loop;
		
	Steady:
		PLAY A 5 A_Look;
		Loop;
	See:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("evilmarinesight", 2);
		Goto ChasePlayer;
	ChasePlayer:
		PLAY AAAABBBBCCCCDDDD 2
		{
			if(random(0, 5) > 3)
				a_recoil(-1);
			A_Chase();//()
		}
	Loop;

	WrongTarget:
		TNT1 A 0 A_ClearTarget;
		TNT1 A 0 {bFRIENDLY = false;}
		PLAY AAAABBBBCCCCDDDDAAABBBBCCCCDDDDAAABBBBCCCCDDDDAAABBBBCCCCDDDDAAABBBBCCCCDDDDAAABBBBCCCCDDDD 1 A_Chase;
		Goto ChasePlayer;
	Missile:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInTargetInventory("IsAnEvilMarine", 1, "WrongTarget");
		TNT1 A 0 A_Recoil(-4);
		TNT1 A 0 A_Jump(192, "Missile_evasion");
		PLAY E 6 A_FaceTarget;
		PLAY F 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		PLAY E 3 A_Facetarget;
		PLAY F 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		PLAY E 3 A_Facetarget;
		PLAY F 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		PLAY E 6 A_Facetarget;
		TNT1 A 0 {if(target && target.health <= 0) A_PlaySound("EVMRLAUG");}
		Goto ChasePlayer;
		
	Missile_evasion:
		TNT1 A 0;
		MARN A 3 A_FaceTarget;
		TNT1 A 0
		{
			A_FaceTarget();
			int i = randompick(90. -90);
			vel.xy += (10 * sin(angle + i), 10 * cos(angle + i) );
		}
		MARN C 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN B 2 A_Facetarget;
		MARN A 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN A 2 A_Facetarget;
		MARN B 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN A 3 A_FaceTarget;
		TNT1 A 0
		{
			A_FaceTarget();
			int i = randompick(90. -90);
			vel.xy += (10 * sin(angle + i), 10 * cos(angle + i) );
		}
		MARN C 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN B 2 A_Facetarget;
		MARN A 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN A 2 A_Facetarget;
		MARN B 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN C 4 A_Facetarget;
		TNT1 A 0 {if(target && target.health <= 0) A_PlaySound("EVMRLAUG");}
	Goto ChasePlayer;
	
	Pain:
		PLAY G 3 A_Pain;
		TNT1 A 0 A_Jump(160, "RollLeft", "RollRight");
		PLAY G 3;
		Goto ChasePlayer;
		
	RollLeft:
		TNT1 A 0
		{
			A_FaceTarget();
			vel.xy += (10 * sin(angle - 90), 10 * cos(angle - 90) );
		}
		PROL EDCBA 3;
		TNT1 A 0 A_CheckSight("See");
		Goto Missile;
		
	RollRight:
		TNT1 A 0
		{
			A_FaceTarget();
			vel.xy += (10 * sin(angle + 90), 10 * cos(angle + 90) );
		}
		PROL ABCDE 3;
		TNT1 A 0 A_CheckSight("See");
		Goto Missile;
		
	Death:
	Death.Bullet:
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		PLAY H 10 A_PlayerScream;
		
		PLAY I 10 A_NoBlocking;
		PLAY J 10;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		PLAY KLM 10;
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		PLAY N -1;
		Stop;
		
	Death.Shotgun:
	Death.SSG:
	Death.Eat:
		TNT1 A 0 A_GiveToTarget("EatMe",1);
		TNT1 AAA 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("muchblood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL1 A 10 A_XScream;
		XPL1 B 20 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		XPL1 CDE 10;
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		XPL1 E -1;
		Stop;
		
	Death.Cut:
	Death.Saw:
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("RipGuts", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("muchblood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 A 10 A_XScream;
		TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 B 20 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 C 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 DE 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		XPL2 E -1;
		Stop;
		
	Death.Slime:
		TNT1 A 0 A_PlaySound("BIGSCREA");
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		PMET AABBCCDDEEFFGGHHIIIII 10 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		PMET IIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLLLLLLLLL 3 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		TNT1 A 0 A_NoBlocking;
		TNT1 A -1;
		Stop;
		
	Death.CutLess:
		TNT1 A 0 A_Jump (128, 3);
		Goto Death;
		TNT1 AAA 0;
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("RipGuts", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 A 10 A_XScream;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 B 20 A_NoBlocking;
		TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 C 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 AA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL2 DE 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		XPL2 E -1;
		Stop;
		
	Death.Rip:
		TNT1 AAAAAAAAAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 A 10 A_XScream;
		TNT1 AAAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 B 20 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 C 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 D 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 E 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 F 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL3 F 10 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		XPL3 F -1;
		Stop;
	XDeath:
		TNT1 A 0 A_SpawnProjectile ("MarineXDeath", 0, 0, random (0, 360), 2, random (0, 160));
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		MHEA A 7 A_XScream;
		MHEA B 7 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		MHEA CD 7;
		MHEA E -1;
		Stop;
		
	Crush:
	Death.Stomp:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 0, 0, random (0, 360), 2, random (0, 360));
		TNT1 AAAAAA 0 bright A_SpawnProjectile ("SuperGoreSpawner", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AAAAAA 0 bright A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath2", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 AA 0 bright A_SpawnProjectile ("XDeath3", 55, 0, random (0, 360), 2, random (30, 180));
		TNT1 A 0 A_SpawnItem ("doomb_red_blood_pool");
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
		TNT1 A 1 A_NoBlocking;
		Stop;
		
	Death.Blast:
	Death.punch:
	Death.SSG:
		PLAY O 2 A_FaceTarget;
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath2", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("XDeath3", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodTrail", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 AAAA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		PLAY OPQRSTU 8;
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		PLAY U -1;
		Stop;
		
	Death.Rape:
		TNT1 AAAAAAAAAAAAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 A 20 A_XScream;
		TNT1 A 0 A_SpawnProjectile ("XDeath1", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath2", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath3", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeath4", 1, 0, random (0, 360), 2, random (0, 160));
		TNT1 AAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 B 20 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 C 20;
		TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 D 20;
		TNT1 AAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 E 20;
		TNT1 AAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		XPL4 F 20;
		TNT1 AAAA 0 A_SpawnProjectile ("MuchBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnItem ("MediumBloodSpot");
		XPL4 F -1;
		Stop;
		
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_burned_flesh;
		EXPL AAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 32), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		TNT1 A 1;
		TNT1 A -1;
		Stop;
		
		
	Death.GreenFire:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		TNT1 AAAA 0 A_SpawnProjectile ("Brutal_Blood", 30, 0, random (0, 360), 2, random (0, 160));
		
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_burned_flesh;
		
		EXPL AAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("GreenFlameTrails", 50, 0, random (0, 360), 2, random (0, 360));
		XBRN AAAA 2 BRIGHT A_SpawnItem("GreenFlare",0,43);
		Stop;
		
	Death.Fire:
		tnt1 a 0 a_jump(128, "fire_death_2");
		PBUR A 1;
		PBUR A 1 A_Scream;
		PBUR A 1 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		PBUR AAAABBBBCCCC 2 A_SpawnProjectile ("SmallFlameTrails", 32, 0, random (0, 180), 2, random (0, 180));
		PBUR DDDDEEEE 2 A_SpawnProjectile ("SmallFlameTrails", 16, 0, random (0, 180), 2, random (0, 180));
		PBUR EEEEE 4 A_SpawnProjectile ("SmallFlameTrails", 8, 0, random (0, 180), 2, random (0, 180));
		PBUR EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 6 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		PBUR E -1;
		Stop;
		
	fire_death_2:
		TNT1 A 0 A_PlaySound("BIGSCREA");
		BURN W 6 A_Scream;
		BURN X 6 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		BUR2 ABCD 6 BRIGHT doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		BURN FGHIJKLMNOPQRSTUV 6 BRIGHT doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 6 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		BURN V -1;
		Stop;
		
		
	Death.Explosive_Impact:
		tnt1 AAAA 0 A_SpawnProjectile ("Brains1", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("jaw", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("eye", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("head_piece", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", random (45, 55), random (5, -5), random (170, 190), 2, random (0, 40));
		tnt1 AAAA 0 A_SpawnProjectile ("SmallBrainPiece", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 AA 0 A_SpawnProjectile ("WallRedBlood", 46, 0, random (170, 190), 2, random (0, 40));
		tnt1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeath3", 40, 0, random (0, 360), 2, random (0, 160));
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		tnt1 AAAA 0 A_SpawnProjectile ("XDeath1", 40, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_XScream;
		XPL6 A 5;
		tnt1 A 0 A_NoBlocking;
		XPL6 BCDE 5;
		XPL6 F -1;
		Stop;
		
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 A 5;
		CRS1 A -1;
		Stop;
		
	Death.HKFT:
	Death.BHFT:
	Death.RVFT:
		TNT1 A 1 A_PlayerScream;
		TNT1 A 1 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		TNT1 A 0 A_GiveToTarget("Curbstomp_Marine",1);
		TNT1 A -1;
		Stop;
		
	Death.FatalityMarine:
		TNT1 A 1 A_PlayerScream;
		TNT1 A 0 A_GiveToTarget("GoFatality", 1);
		TNT1 A 1 A_NoBlocking;
		TNT1 A 0 A_SpawnItem("RemoveMarine");
		TNT1 A 0 A_GiveToTarget("Fatality_Marine",1);
		TNT1 A -1;
		Stop;
}
}



CLASS EasyMarine: EvilMarine { 
	Default {
	
	Health 80;
	Speed 5;
	FastSpeed 5;
	DropItem "Rifle";
	MaxStepHeight 42;
	MaxDropOffHeight 42;
	-CANUSEWALLS;
	}
States
{
	Spawn:
		PLAY A 3 A_Look;
		TNT1 A 0 A_GiveInventory("IsAnEvilMarine", 1);
		Loop;
		
	Missile:
		TNT1 A 0;
		TNT1 A 0 A_JumpIfInTargetInventory("IsAnEvilMarine", 1, "WrongTarget");
		TNT1 A 0 A_Recoil(-4);
		TNT1 A 0 A_Jump(192, "MissileLeft", "MissileRight");
		PLAY E 6 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		PLAY F 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		PLAY E 3 A_Facetarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		PLAY F 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		PLAY E 3 A_Facetarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		PLAY F 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		PLAY E 6 A_Facetarget;
		TNT1 A 0 A_Jump(160, "RollLeft", "RollRight");
		TNT1 A 0 {if(target && target.health <= 0) A_PlaySound("EVMRLAUG");}
		Goto ChasePlayer;
		
	MissileLeft:
		TNT1 A 0;
		MARN A 3 A_FaceTarget;
		TNT1 A 0
		{
			A_FaceTarget();
			vel.xy += (10 * sin(angle - 90), 10 * cos(angle - 90) );
		}
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MARN C 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN B 2 A_Facetarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MARN A 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN A 2 A_Facetarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MARN B 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN A 3 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0
		{
			A_FaceTarget();
			vel.xy += (10 * sin(angle - 90), 10 * cos(angle - 90) );
		}
		MARN C 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN B 2 A_Facetarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MARN A 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN A 2 A_Facetarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MARN B 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN C 4 A_Facetarget;
		TNT1 A 0 {if(target && target.health <= 0) A_PlaySound("EVMRLAUG");}
		Goto ChasePlayer;
		
	MissileRight:
		TNT1 A 0;
		MARN A 3 A_FaceTarget;
		TNT1 A 0
		{
			A_FaceTarget();
			vel.xy += (10 * sin(angle + 90), 10 * cos(angle + 90) );
		}
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MARN C 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN B 2 A_Facetarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MARN A 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN A 2 A_Facetarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MARN B 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN A 3 A_FaceTarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		TNT1 A 0
		{
			A_FaceTarget();
			vel.xy += (10 * sin(angle + 90), 10 * cos(angle + 90) );
		}
		MARN C 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN B 2 A_Facetarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MARN A 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN A 2 A_Facetarget;
		TNT1 A 0 A_SpawnProjectile("MarineMuzzle1", 36, 20, 15, 0);
		TNT1 A 0 A_SpawnProjectile("OrangeLensFlareAlt", 36, 20, 15, 0);
		TNT1 A 0 A_PlaySound("weapons/rifle");
		TNT1 A 0 A_SpawnItem ("RifleCaseSpawn", 0, 30,0);
		MARN B 3 BRIGHT A_SpawnProjectile("ZombiemanTracer",35,0,0,0);
		MARN C 4 A_Facetarget;
		TNT1 A 0 {if(target && target.health <= 0) A_PlaySound("EVMRLAUG");}
		Goto ChasePlayer;
		
	Pain:
		PLAY G 3 A_Pain;
		TNT1 A 0 A_Jump(160, "RollLeft", "RollRight");
		PLAY G 3;
		Goto ChasePlayer;
		
	RollLeft:
		TNT1 A 0
		{
			A_FaceTarget();
			vel.xy += (10 * sin(angle - 90), 10 * cos(angle - 90) );
		}
		PROL EDCBA 3;
		TNT1 A 0 A_CheckSight("See");
		Goto Missile;
		
	RollRight:
		TNT1 A 0
		{
			A_FaceTarget();
			vel.xy += (10 * sin(angle + 90), 10 * cos(angle + 90) );
		}

		PROL ABCDE 3;
		TNT1 A 0 A_CheckSight("See");
		Goto Missile;
}
}
