CLASS doomb_evil_marine : doomb_monster_base
{
	Default {
		
		Health 200;
		Radius 14;
		Height 56;
		Speed 6;
		FastSpeed 6;
		PainChance 200;
		Monster;
		+FLOORCLIP;
		+QUICKTORETALIATE;
		Species "doomb_evil_marines";
		damagefactor "shotgun", 0.6;
		damagefactor "cutless", 0.6;
		damagefactor "saw", 0.8;
		damagefactor "cut", 0.8;
		damagefactor "Explosive_Impact", 0.4;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		

		SeeSound "none";
		AttackSound "grunt/attack";
		PainSound "doomb_evil_marinepain";
		DeathSound "doomb_evil_marinedeath";
		ActiveSound "doomb_evil_marineactive";
		Obituary "%o was eliminated by an evil marine.";
		DropItem "PLasmaRifle";
	Translation "112:127=[64,64,64]:[0,0,0]";
	}
	States
	{
	Spawn:
		PLAY A 5;
	Goto Steady;
		
	Idle:
		PLAY AAAAAAA 5 A_Look;
		TNT1 A 0 A_Jump(32, 3);
		TNT1 A 0 A_SetAngle(angle - 40);
		PLAY AA 5 A_Look;
		TNT1 A 0 A_SetAngle(angle + 40);
		PLAY A 5 A_Look;
		TNT1 A 0 A_Jump(32, 3);
		TNT1 A 0 A_SetAngle(angle + 40);
		PLAY AAAABBBBCCCCDDDD 5
		{
			A_Look();
			A_Wander();
		}
	Loop;
		
	Steady:
		PLAY A 5 A_Look;
		Loop;
	See:
		TNT1 A 0;
		TNT1 A 0 A_PlaySound("doomb_evil_marinesight", 2);
		Goto ChasePlayer;
	ChasePlayer:
		PLAY AAAABBBBCCCCDDDD 2
		{
			if(random(0, 5) > 3)
				a_recoil(-1);
			A_Chase();//()
		}
	Loop;

	WrongTarget:
		TNT1 A 0 A_ClearTarget;
		TNT1 A 0 {bFRIENDLY = false;}
		PLAY AAAABBBBCCCCDDDDAAABBBBCCCCDDDDAAABBBBCCCCDDDDAAABBBBCCCCDDDDAAABBBBCCCCDDDDAAABBBBCCCCDDDD 1 A_Chase;
		Goto ChasePlayer;
	Missile:
		TNT1 A 0 A_Recoil(-4);
		TNT1 A 0 A_Jump(192, "Missile_evasion");
		PLAY E 6 A_FaceTarget;
		PLAY F 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		PLAY E 3 A_Facetarget;
		PLAY F 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		PLAY E 3 A_Facetarget;
		PLAY F 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		PLAY E 6 A_Facetarget;
		TNT1 A 0 {if(target && target.health <= 0) A_PlaySound("EVMRLAUG");}
		Goto ChasePlayer;
		
	Missile_evasion:
		TNT1 A 0;
		MARN A 3 A_FaceTarget;
		TNT1 A 0
		{
			A_FaceTarget();
			int i = randompick(90. -90);
			vel.xy += (10 * sin(angle + i), 10 * cos(angle + i) );
		}
		MARN C 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN B 2 A_Facetarget;
		MARN A 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN A 2 A_Facetarget;
		MARN B 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN A 3 A_FaceTarget;
		TNT1 A 0
		{
			A_FaceTarget();
			int i = randompick(90. -90);
			vel.xy += (10 * sin(angle + i), 10 * cos(angle + i) );
		}
		MARN C 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN B 2 A_Facetarget;
		MARN A 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN A 2 A_Facetarget;
		MARN B 3 BRIGHT A_SpawnProjectile("EnemyPlasmaBall",35,0,0,0);
		MARN C 4 A_Facetarget;
		TNT1 A 0 {if(target && target.health <= 0) A_PlaySound("EVMRLAUG");}
	Goto ChasePlayer;
	
	Pain:
		PLAY G 3 A_Pain;
		TNT1 A 0 A_Jump(160, "RollLeft", "RollRight");
		PLAY G 3;
		Goto ChasePlayer;
		
	RollLeft:
		TNT1 A 0
		{
			A_FaceTarget();
			vel.xy += (10 * sin(angle - 90), 10 * cos(angle - 90) );
		}
		PROL EDCBA 3;
		TNT1 A 0 A_CheckSight("See");
		Goto Missile;
		
	RollRight:
		TNT1 A 0
		{
			A_FaceTarget();
			vel.xy += (10 * sin(angle + 90), 10 * cos(angle + 90) );
		}
		PROL ABCDE 3;
		TNT1 A 0 A_CheckSight("See");
		Goto Missile;
		
	Death:
	Death.Bullet:
		TNT1 A 0 doomb_much_blood();
		PLAY H 10 A_PlayerScream;
		
		PLAY I 10 A_NoBlocking;
		PLAY J 10;
		TNT1 A 0 ;
		PLAY KLM 10;
			TNT1 A 0 doomb_spawn_bloodpool();
		PLAY N -1;
		Stop;
		
	Death.Shotgun:
	Death.SSG:
	Death.Eat:
		TNT1 A 0 A_GiveToTarget("EatMe",1);
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_much_blood();
		XPL1 A 10 A_XScream;
		XPL1 B 20 A_NoBlocking;
		TNT1 A 0 ;
		XPL1 CDE 10;
			TNT1 A 0 doomb_spawn_bloodpool();
		XPL1 E -1;
		Stop;
		
	Death.Cut:
	Death.Saw:
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_Rip_Guts();
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_much_blood();
		XPL2 A 10 A_XScream;
		TNT1 A 0 doomb_much_blood();
		XPL2 B 20 A_NoBlocking;
		TNT1 A 0 doomb_much_blood();
		XPL2 CDE 10 doomb_much_blood();
		TNT1 A 0 doomb_spawn_bloodpool();
		XPL2 E -1;
	Stop;
		
	Death.Slime:
		TNT1 A 0 A_PlaySound("BIGSCREA");
		TNT1 A 0 ;
		PMET AABBCCDDEEFFGGHHIIIII 10 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		PMET IIIIIIIIIIJJJJJJJJJJJJJJJJJJJJJJKKKKKKKKKKKKKKKKKKKKKKKKKKLLLLLLLLLLLLLLL 3 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		TNT1 A 0 A_NoBlocking;
		TNT1 A -1;
		Stop;
		
	Death.CutLess:
		TNT1 A 0 A_Jump (128, 3);
	Goto Death;
		TNT1 AAA 0;
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_Rip_Guts();
		TNT1 A 0 A_SpawnProjectile ("XDeathHalfMarine", 50, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_much_blood();
		XPL2 A 10 A_XScream;
		TNT1 A 0 ;
		TNT1 A 0 doomb_much_blood();
		XPL2 B 20 A_NoBlocking;
		TNT1 A 0 doomb_much_blood();
		XPL2 CDE 10 doomb_much_blood();
		TNT1 A 0 doomb_spawn_bloodpool();
		XPL2 E -1;
	Stop;
		
	Death.Rip:
		XPL3 A 10 A_XScream;
		TNT1 AAAAA 0 doomb_much_blood();
		XPL3 B 20 A_NoBlocking;
		TNT1 A 0 doomb_much_blood();
		XPL3 CDEFF 10 doomb_much_blood();
		TNT1 A 0 doomb_spawn_bloodpool();
		XPL3 F -1;
	Stop;

	XDeath:
		TNT1 A 0 A_SpawnProjectile ("MarineXDeath", 0, 0, random (0, 360), 2, random (0, 160));
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		MHEA A 7 A_XScream;
		MHEA B 7 A_NoBlocking;
		TNT1 A 0 ;
		MHEA CD 7;
		MHEA E -1;
	Stop;
		
	Crush:
	Death.Stomp:
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 0 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 doomb_blood_mist('doomb_non_interactive_blood', 'blood_mist', times:6);
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 A 0 doomb_spawn_bloodpool();
		TNT1 A 0 A_SpawnItem ("CrushedRemains");
		TNT1 A 1;
		TNT1 A 1 A_XScream;
		TNT1 A 1 A_NoBlocking;
		Stop;
		
	Death.Blast:
	Death.punch:
	Death.SSG:
		PLAY O 2 A_FaceTarget;
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, 32 ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 AAAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (170, 190), 2, random (0, 40));
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;
		PLAY OPQRSTU 8;
			TNT1 A 0 doomb_spawn_bloodpool();
		PLAY U -1;
		Stop;
		
	Death.Rape:
		TNT1 AAAAAAAAAAAAAA 0 doomb_much_blood();
		XPL4 A 20 A_XScream;
			TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		TNT1 AAAA 0 doomb_much_blood();
		XPL4 B 20 A_NoBlocking;
		TNT1 A 0 doomb_much_blood();
		XPL4 CDEFF 20 doomb_much_blood();
		TNT1 A 0 doomb_spawn_bloodpool();
		XPL4 F -1;
	Stop;
		
	Death.plasma:
		TNT1 A 0;
		TNT1 A 0 A_XScream;
		TNT1 A 0 A_NoBlocking;
		TNT1 A 0 ;
		TNT1 AAA 0 doomb_for_khorne("doomb_non_interactive_blood", "red_blood_trail", (0, 0, random(20, 30) ), (frandom(-5, 5), frandom(-5, 5), frandom(0, 5) ) );
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedArm", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedLeg", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("XDeathBurnedSkull", 32, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_burned_flesh;
		EXPL AAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 32), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		TNT1 A 1;
		TNT1 A -1;
		Stop;
		
		
	Death.Fire:
		tnt1 a 0 a_jump(128, "fire_death_2");
		PBUR A 1;
		PBUR A 1 A_Scream;
		PBUR A 1 A_NoBlocking;
		TNT1 A 0 ;
		PBUR AAAABBBBCCCC 2 doomb_show_effect("FlameTrails", (0, 0, 32), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (0.3, 0) );
		PBUR DDDDEEEE 2 doomb_show_effect("FlameTrails", (0, 0, 16), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (0.3, 0) );
		PBUR EEEEE 4 doomb_show_effect("FlameTrails", (0, 0, 8), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (0.3, 0) );
		PBUR EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE 6 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		PBUR E -1;
		Stop;
		
	fire_death_2:
		TNT1 A 0 A_PlaySound("BIGSCREA");
		BURN W 6 A_Scream;
		BURN X 6 A_NoBlocking;
		TNT1 A 0 ;
		BUR2 ABCD 6 BRIGHT doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		BURN FGHIJKLMNOPQRSTUV 6 BRIGHT doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		BURN VVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVVV 6 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		BURN V -1;
		Stop;
		
		
	Death.Explosive_Impact:
		TNT1 A 0 doomb_severed_limb("eye", "spawn", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("head_piece", "spawn", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("jaw", "spawn", (0, 0, 50), doomb_random_velocity(5) );
		TNT1 A 0 doomb_severed_limb("SmallBrainPiece", "spawn", (0, 0, 50), doomb_random_velocity(5) );
		tnt1 a 0 doomb_spray_decal("BrutalBloodSuper", times: 5);
		tnt1 AAAAAAAAAAA 0 A_SpawnProjectile ("Brutal_Blood", 50, 0, random (0, 360), 2, random (0, 160));
		tnt1 A 0 A_SpawnProjectile ("XDeathArm1", 35, 0, random (0, 360), 2, random (0, 160));
		TNT1 A 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
		PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
		tnt1 A 0 A_XScream;
		XPL6 A 5;
		tnt1 A 0 A_NoBlocking;
		XPL6 BCDE 5;
		XPL6 F -1;
	Stop;
		
	Crush:
		TNT1 A 0 A_PlaySound("misc/xdeath4");
		CRS1 A -1;
		Stop;
		
	Death.HKFT:
	Death.BHFT:
	Death.RVFT:
		TNT1 A 1 A_PlayerScream;
		TNT1 A 1 A_NoBlocking;
		TNT1 A 0 ;
		TNT1 A 0 A_GiveToTarget("Curbstomp_Marine",1);
		TNT1 A -1;
		Stop;
		
	Death.FatalityMarine:
		TNT1 A 1 A_PlayerScream;
		TNT1 A 1 A_NoBlocking;
		TNT1 A 0 ;
		TNT1 A 0 A_GiveToTarget("Fatality_Marine",1);
		TNT1 A -1;
	Stop;
}

}