CLASS Hectebus : doomb_fatso { //Replaces Hectebus
	Default {
		
		Scale 1.5;
		
		GibHealth 25;
		damagefactor "Avoid", 0.0;
		PainChance "Kick", 255;
		damagefactor "Stomp", 0.0;

		DamageFactor "CauseObjectsToSplash", 0.0;
		Health 8000;
		+NOICEDEATH;
		PainSound "juggernaut/pain";
		DeathSound "juggernaut/death";
		ActiveSound "juggernaut/roam";
		SeeSound "juggernaut/see";
		
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		BloodType "Brutal_Blood";
		damagefactor "Explosive_Impact", 1.3;
		Obituary "%o was destroyed by the Juggernaut";
		MaxStepHeight 24;
		MaxDropOffHeight 32;
		Speed 1;
		Height 88;
		Radius 48;
		Mass 99999;
		Painchance 10;
		Painchance "Explosive_Impact", 50;
		+MISSILEMORE;
		+MISSILEEVENMORE;
		MinMissileChance 150;
	}
	States
	{
		/////////////////////
		Spawn:
			BS1W A 1;
			TNT1 A 0 A_SpawnItemEx ("KillTreads",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			Goto Standby;
		Standby:
			BS1W A 1;
			BS1W AC 10 A_Look;
			Loop;
			//////////////////
		See:
			BS1W A 1;
			//TNT1 A 0 A_SpawnItem("KillTreads")
			Goto Rolling;
		Rolling:
			
			TNT1 A 0 A_PlaySound("juggernaut/engine");
			
			BS1W A 2 A_Chase();
			BS1W B 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			BS1W A 2 A_Recoil(-2);
			BS1W B 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			
			BS1W C 2 A_Recoil(-2);
			BS1W D 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			BS1W C 2 A_Recoil(-2);
			BS1W D 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			
			BS1W A 2 A_Chase();
			BS1W B 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			BS1W A 2 A_Recoil(-2);
			BS1W B 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			
			BS1W C 2 A_Recoil(-2);
			BS1W D 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			BS1W C 2 A_Recoil(-2);
			BS1W D 2 A_Recoil(-2);
			TNT1 A 0 A_Jump (128, "Rolling2");
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			Loop;
			
		Rolling2:
			
			TNT1 A 0 A_PlaySound("juggernaut/engine");
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Chase();
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Chase();
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			TNT1 A 0 A_CheckSight("See");
			Goto Missile;
			
			///////////////////	
			
		Missile:
			TNT1 A 0;
			TNT1 A 0 A_JumpIfCloser(150, "Rolling");
			TNT1 A 0 A_Jump (128, "FireRockets");
			Goto FireMachinegun;
		FireMachinegun:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("juggernaut/engine");
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Chase();
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody2", 0);
			TNT1 A 0 A_SpawnProjectile("MonsterMinigunTracer", 72, 42, random(-8, 8), 0);
			TNT1 A 0 A_SpawnProjectile("MonsterMinigunTracer", 72, -42, random(-8, 8), 0);
			TNT1 A 0 A_SpawnProjectile("YellowFlareSmall", 72, 42, 0, 0);
			TNT1 A 0 A_SpawnProjectile("YellowFlareSmall", 72, -42, 0, 0);
			TNT1 A 0 A_SpawnProjectile("RifleCaseSpawn", 72, 42, 0, 0);
			TNT1 A 0 A_SpawnProjectile("RifleCaseSpawn", 72, -42, 180, 0);
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			BS1B A 2 A_Recoil(-2);
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody2", 0);
			TNT1 A 0 A_SpawnProjectile("MonsterMinigunTracer", 72, 42, random(-8, 8), 0);
			TNT1 A 0 A_SpawnProjectile("MonsterMinigunTracer", 72, -42, random(-8, 8), 0);
			TNT1 A 0 A_SpawnProjectile("YellowFlareSmall", 72, 42, 0, 0);
			TNT1 A 0 A_SpawnProjectile("YellowFlareSmall", 72, -42, 0, 0);
			TNT1 A 0 A_SpawnProjectile("RifleCaseSpawn", 72, 42, 0, 0);
			TNT1 A 0 A_SpawnProjectile("RifleCaseSpawn", 72, -42, 180, 0);
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			TNT1 A 0 A_GiveInventory("JuggernautMachinegunAmmo", 1);
			TNT1 A 0 A_JumpIfInventory("JuggernautMachinegunAmmo", 30, "stopfiring");
			TNT1 A 0 A_CheckSight("StopFiring");
			Loop;
			
		FireRockets:
			TNT1 A 0;
			TNT1 A 0 A_PlaySound("juggernaut/engine");
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Chase();
			
			TNT1 A 0 A_SpawnProjectile("Rocket", 110, -42, random(-3, 3), 0);
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			BS1B A 2 A_Recoil(-2);
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Chase();
			TNT1 A 0 A_SpawnProjectile("Rocket", 110, 42, random(-3, 3), 0);
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			BS1B A 2 A_Recoil(-2);
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			BS1B A 2 A_Recoil(-2);
			
			TNT1 A 0 A_SpawnProjectile ("JuggernautBody1", 0);
			
			
			TNT1 A 0 A_SpawnItem("TreadsDamage",65);
			TNT1 A 0 A_GiveInventory("JuggernautRocketAmmo", 2);
			TNT1 A 0 A_JumpIfInventory("JuggernautRocketAmmo", 6, "stopfiring");
			TNT1 A 0 A_CheckSight("StopFiring");
			Loop;
			
		StopFiring:
			TNT1 A 0;
			TNT1 A 0 A_TakeInventory("JuggernautMachinegunAmmo", 30);
			TNT1 A 0 A_TakeInventory("JuggernautRocketAmmo", 6);
			Goto See;
			
			
			
			
			////////////////////
		Pain:
			TNT1 A 0;
			BS1W A 2;
			BS1W A 2 A_Pain;
			Goto Rolling;
			
			
			///////////////////////
		Death:
			TNT1 A 0;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("KillTreads");
			EXPL A 0 Radius_Quake (6, 100, 0, 22, 0);
		TNT1 AAAA 0
		{
			A_PlaySound("FAREXPL");
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		}
			TNT1 AAAA 0 A_SpawnProjectile ("UltraGoreSPawner", 90, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_SpawnProjectile ("UltraGoreSpawner", 90, 0, random (0, 180), 2, random (0, 180));
			TNT1 A 0 A_SpawnProjectile ("CyberXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			TNT1 A 0;
			BS1B BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB 5
			{
				doomb_show_effect("ExplosionSmoke", (0, 0, 60), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
				A_SpawnProjectile ("RealFlameTrailsMedium", 60, 0, random (0, 360), 2, random (0, 160));
			}
		Decay:
			BS1B B 38 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.3,0), 0.3 );
		Loop;
			
	}
} 


CLASS JuggernautBase : CurbstompedMarine { 
	Default {
		
		Health 10000;
		Radius 64;
		Height 2;
		Scale 1.5;
		Monster;
		+NOBLOOD;
		+SOLID;
		-NOBLOCKMAP;
		-COUNTKILL;
		Mass 99999;
	}
	States
	{
		Spawn:
			BS1B A 5;
			Loop;
			
		Death:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			Stop;
	}
}


CLASS KillTreads : ACTOR { 
	Default {
		
		+NOTARGET;
		Radius 1;
		Height 1;
		+NOGRAVITY;
		+NOTELEPORT;
		+NODAMAGETHRUST;
		+THRUGHOST;
		+NORADIUSDMG;
		+NOEXTREMEDEATH;
		+FORCERADIUSDMG;
		PROJECTILE;
		+DEHEXPLOSION;
		+ACTIVATEMCROSS;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Explode(20,80,0);
			Stop;
	}
}


CLASS TreadsDamage : ACTOR { 
	Default {
		
		+NOTARGET;
		Radius 1;
		Height 1;
		DamageType "Stomp";
		+NOGRAVITY;
		+NOTELEPORT;
		+NODAMAGETHRUST;
		+THRUGHOST;
		+NORADIUSDMG;
		+NOEXTREMEDEATH;
		+FORCERADIUSDMG;
		PROJECTILE;
		+DEHEXPLOSION;
		+ACTIVATEMCROSS;
		+EXPLODEONWATER;
	}
	States
	{
		Spawn:
			TNT1 A 0 A_Explode(500,50,0);
			TNT1 A 1 A_Noblocking;
			Stop;
	}
}













CLASS JuggernautBody1 : ACTOR { 
	Default {
		
		+RANDOMIZE;
		+FORCEXYBILLBOARD;
		+DONTSPLASH;
		+NOEXTREMEDEATH;
		+THRUACTORS;
		+NOGRAVITY;
		+NOCLIP;
		Projectile;
		damage 0;
		radius 2;
		height 0;
		speed 1;
		Scale 1.5;
	}
	states
	{
		Spawn:
			BS1T AAAA 1;//A_FaceTarget
			Stop;
			Goto Death;
		Death:
			TNT1 A 0;
			Stop;
		XDeath:
			TNT1 A 0;
			Stop;
	}
}

CLASS JuggernautBody2: JuggernautBody1 { 
	Default {
		
	}
	states
	{
		Spawn:
			BS1T BBBB 1 BRIGHT;//A_FaceTarget
			Stop;
			Goto Death;
	}
}



CLASS JuggernautMachinegunAmmo : Inventory { 
	Default {
		
		inventory.maxamount 30;
	}
}

CLASS JuggernautRocketAmmo : Inventory { 
	Default {
		
		inventory.maxamount 6;
	}
}
