class Spectro : BullDemon Replaces Spectre
{
default
{
	GibHealth 35;
    Scale 1.1;
	Height 52;
	Radius 22;
	Mass 400;
    damagefactor "Crush", 10.0;
    damagefactor "SSG", 5.0;
	PainChance "Kick", 255;
	Monster;
	damagefactor "Blood", 0.0 ;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0;
	damagefactor "SSG", 5.0;
	+FLOORCLIP ;
	SeeSound "demon/sight";
	AttackSound "demon/melee";
	PainSound "demon/pain";
	DeathSound "demon/death";
	ActiveSound "demon/active";
    BloodType "Brutal_Blood",  "SawBlood";
	DamageType "Eat";
	MaxStepHeight 48;
	MaxDropOffHeight 48;
	DropItem "DemonStrengthRune", 2;
	DropItem "SuperBlurSphere", 12;
	RenderStyle "Add";
    Alpha 0.45;
	speed 8;
	fastspeed 6;
	Obituary "%o has been sodomized by a Spectre.";

}

States
{
    Spawn:
		TNT1 A 0;
	Spawned:
		SPEC AAAAAAAAAAAAAAAAAA 10 BRIGHT A_Look;
		Loop;
	SpawnVisible:
		
		SARG A 10;
		Goto Spawned;
		
	See:
        TNT1 A 0 A_SpawnItemEx("FootStep", 0, 0, 30, 0, 0);
		TNT1 A 0 A_JumpIfInTargetInventory("powerLightAmp", 1, "SeeVisible");
		SPEC AAABBBAAABBB 1 BRIGHT A_Chase;
		TNT1 A 0 doomb_monster_memory();
	Loop;
	
	SeeVisible:
		SARG AAABBBCCCDDD 1 A_Chase;
		Goto See;
	
	Pain:
		SARG H 2;
		SARG H 2 A_Pain;
		Goto See;
	Pain:
		SARG H 2;
		SARG H 2 A_Pain;
		Goto See;
		
    Pain.Kick:
	Pain.HeavyImpact:
	Pain.Shotgun:
		TNT1 A 0 A_Pain;
		TNT1 A 0;
		TNT1 A 0 A_FaceTarget;
		TNT1 A 0 A_Recoil (2);
		SARG H 2;
		SARG H 2;
	Goto See;
		 
	Melee:
		TNT1 A 0 doomb_update_memory();
		TNT1 A 0 A_JumpIfInTargetInventory("ComeEatMeDemon", 1, "MeleeDown");
		SARG EF 6 A_FaceTarget;
		SARG G 12 doomb_cheap_melee_attack(60, random(16, 40), "eat");
		TNT1 A 0 A_JumpIfInventory("ZombieManFatality", 1, "FatalityZombieman");
		TNT1 A 0 A_JumpIfInventory("SergeantFatality", 1, "FatalitySergeant");
		TNT1 A 0 A_JumpIfInventory("ImpFatality", 1, "FatalityImp");
		TNT1 A 0 A_JumpIfInventory("ComandoFatality", 1, "FatalityComando")	;

     TNT1 A 0 A_JumpIfInventory("EatMe", 1, "Eat");
		Goto See;
	}
}