CLASS VeryDeadMarine: DeadMarine Replaces DeadMarine { 
	Default {
		
		damagefactor "Avoid", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0 ;
		damagefactor "Taunt", 0.0;
		
		+CLIENTSIDEONLY;
		+FLOORCLIP;
		Radius 0;
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 AAAAA 0 A_SpawnProjectile ("WallRedBlood", 10, 0, random (0, 360), 2, - random (5, 40));
			TNT1 AAAAAA 0 A_SpawnItemEx("Brutal_BloodSpot",random(64, -64),- random(64, -64));
			TNT1 A 0 A_SpawnItem("MediumBloodSpot");
			TNT1 A 0 A_CheckSight("Spawn2");
			TNT1 A 0;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("CurbstompedMarine");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("AteMarine");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("DeadRippedOffMarine");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("FuckedMarine");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("ADoomedSpaceMarine2");
			Goto Death;
			TNT1 A 1 A_SpawnItem("ADoomedSpaceMarine");
			Stop;
			
		Spawn2:
			TNT1 A 0;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("CurbstompedMarine");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("AteMarine");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("DeadRippedOffMarine");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("FuckedMarine");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("ADoomedSpaceMarine2");
			Goto Death;
			TNT1 A 1 A_SpawnItem("ADoomedSpaceMarine");
			Stop;
		Death:
			TNT1 A 0;
			Stop;
	}
}

CLASS VeryVeryDeadMarine: GibbedMarine Replaces GibbedMarine { 
	Default {
		
		+CLIENTSIDEONLY;
		damagefactor "Avoid", 0.0;
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 AAAAA 0 A_SpawnProjectile ("WallRedBlood", 10, 0, random (0, 360), 2, - random (5, 40));
			TNT1 AAAAAAA 0 A_SpawnItemEx("Brutal_BloodSpot",random(64, -64),random(64, -64));
			TNT1 A 0 A_SpawnItem("MediumBloodSpot");
			TNT1 A 0 A_CheckSight("Spawn2");
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("GibsZ");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("GibsZ");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("VeryDeadCivilian");
			Goto Death;
			TNT1 A 1 A_SpawnItem("GutsPile");
			Stop;
			
		Spawn2:
			TNT1 A 0;
			
			TNT1 A 0;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("GibsZ");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("GibsZ");
			Goto Death;
			TNT1 A 0 A_Jump(160,2);
			TNT1 A 1 A_SpawnItem("VeryDeadCivilian");
			Goto Death;
			TNT1 A 1 A_SpawnItem("GutsPile");
			Stop;
		Death:
			TNT1 A 0;
			Stop;
	}
}

CLASS VeryVeryDeadMarine2 : VeryVeryDeadMarine Replaces GibbedMarineExtra { 
	Default {
		
	}
}



CLASS CurbstompedMarine : doomb_body_base { 
	Default {
		
		Radius 10;
		Height 6;
		+NOTELEPORT;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		+MOVEWITHSECTOR;
		+FLOORCLIP;
		+NOBLOCKMONST;
		+CANPASS;
		+THRUACTORS;
		+FORCEXYBILLBOARD;
		+SHOOTABLE;
		+CLIENTSIDEONLY;
		+CORPSE;
		damagefactor "Crusher", 50.0;
		Mass 5000;
		Health 300;
		PainChance 255;
		Mass 6000;
		
		damagefactor "Normal", 2.0;
		damagefactor "Desintegrate", 990.0;
		damagefactor "BFG", 990.0;
		damagefactor "Kick", 3.0;
		damagefactor "SuperKick", 3.0;
		
		damagefactor "punch", 2.0;
		bloodtype "DeadBlood";
	}
	States
	{
		Spawn:
			PLDH A 3000;
			Loop;
			
		Death.Fire:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("GoryAshes");
			Stop;
			
		Death:
		Death.Stomp:
		Death.Explosive_Impact:
			TNT1 A 0 A_SpawnItem("GibsZ");
			TNT1 A 0 A_NoBlocking;
			TNT1 AA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, - random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, - random (0, 160));
			TNT1 AA 0 A_SpawnProjectile ("XDeath3", 5, 0, random (0, 360), 2, - random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 10, 0, random (0, 360), 2, - random (40, 90));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("XDeathSkinPiece2", 5, 0, random (0, 360), 2, - random (0, 160));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeathSkinPiece1", 5, 0, random (0, 360), 2, - random (0, 160));
			TNT1 AAAAAAAA 0 A_SpawnProjectile ("SmallSuperGore", 10, 0, random (0, 360), 2, - random (10, 170));
			TNT1 AAAA 0 A_SpawnProjectile ("BloodMistSmall", 35, 0, random (0, 360), 2, - random (40, 90));
			Stop;
			
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 A_SpawnProjectile ("Brutal_FlyingBlood", 50, 0, random (0, 360), 2, - random (0, 160));
			TNT1 A 0 doomb_spawn_burned_flesh;
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0;
			Stop;
			
		Death.Trample: 
		Death.Crush:
		Death.Stomp:
			TNT1 AAAAA 0 A_SpawnProjectile ("XDeath1", 5, 0, random (0, 360), 2, - random (0, 30));
			TNT1 AA 0 A_SpawnProjectile ("XDeath2", 5, 0, random (0, 360), 2, - random (0, 30));
			TNT1 AAAA 0 A_SpawnProjectile ("BloodMist", 5, 0, random (0, 360), 2, - random (0, 30));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("XDeathSkinPiece2", 5, 0, random (0, 360), 2, - random (10, 30));
			TNT1 AAAA 0 A_SpawnProjectile ("XDeathSkinPiece1", 5, 0, random (0, 360), 2, - random (10, 130));
			TNT1 AAAA 0 A_SpawnProjectile ("SmallSuperGore", 10, 0, random (0, 360), 2, - random (10, 30));
			TNT1 A 0 doomb_spawn_bloodpool();
			XME2 L -1;
			Stop;
			
		Death.Desintegrate:
			TNT1 A 0;
			TNT1 AAAA 0 A_SpawnProjectile ("Brutal_FlyingBloodFake", 0, 0, random (0, 360), 2, - random (0, 90));
			TNT1 A 0 A_SpawnProjectile ("Brutal_FlyingBlood", 7, 0, random (0, 360), 2, - random (30, 60));
			TNT1 AA 0 A_SpawnProjectile ("BloodMistSmall", 7, 0, random (0, 360), 2, - random (30, 60));
			TNT1 A 0 A_SpawnItem("GibsZ");
			TNT1 A 0 A_SpawnItem("MeatDeathSmall");
			Stop;
			
	}
	
}
CLASS RappedMarine: CurbstompedMarine { 

	States
	{
		Spawn:
			XPL4 F 1;
			Loop;
	}
	
}
CLASS AteMarine: CurbstompedMarine { 
	Default {
		
	}
	States
	
	{
		Spawn:
			XPL1 E -1;
			stop;
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("MeatDeathSmall");
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, - random (0, 180));
			TNT1 A 0 A_SpawnItem("RipGuts");
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			TNT1 A 0 A_SpawnItem("DeadRippedOffMarine");
			Stop;
	}
	
}

CLASS FuckedMarine: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			XPL3 F -1;
			stop;
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("MeatDeathSmall");
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, - random (0, 180));
			TNT1 A 0 A_SpawnItem("RipGuts");
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			TNT1 A 0 A_SpawnItem("DeadRippedOffMarineRight");
			Stop;
			
	}
	
}	   
	   
	   


CLASS DeadRippedOffMarine: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			XPL2 F -1;
			stop;
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("MeatDeathSmall");
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			TNT1 A 0 A_SpawnItem("GibsZ");
			Stop;
	}
	
}

CLASS DeadRippedOffMarineRight: DeadRippedOffMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			XPL2 L -1;
			stop;
			
			
	}
	
}
CLASS VeryDeadCivilian: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			DCIV A -1;
			stop;
	}
	
}

CLASS MarineGotOwnedByImp: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			IPFP P -1;
			stop;
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, - random (0, 180));
			TNT1 A 0 A_SpawnItem("MeatDeathSmall");
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			TNT1 A 0 A_SpawnItem("DeadRippedOffMarine");
			Stop;
	}
	
}	   
CLASS ADoomedSpaceMarine: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			PLAY N -1;
			Loop;
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, - random (0, 180));
			TNT1 A 0 A_SpawnItem("MeatDeathSmall");
			TNT1 A 0 A_SpawnItem("AteMarine");
			Stop;
	}
	
}	   
CLASS ADoomedSpaceMarine2: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			PLA9 N -1;
			Loop;
			
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("MeatDeathSmall");
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, - random (0, 180));
			TNT1 A 0 A_SpawnItem("AteMarine");
			Stop;
			
			
	}
	
}
CLASS DeadHalfMarine: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			HPLA A -1;
			Loop;
	}
	
}
CLASS GutsPile : ACTOR { 
	Default {
		
		Radius 1;
		Height 1;
	}
	States
	{
		Spawn:
			GUTS P -1;
			Stop;
	}
	
}

CLASS GoryAshes : doomb_body_base { 
	Default {
		
		Radius 1;
		Height 1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			GIBD SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 6 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				Spawn("RedFlare", pos);
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				A_SpawnProjectile ("SmallFireTrail324", 0, 0, random (0, 360), 2, -random (0, 130));
			}
			GIBD SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			GIBD S -1;
			stop;
	}
	
}

CLASS GibsZ : ACTOR { 
	Default {
		
		Radius 1;
		Height 1;
	}
	States
	{
		Spawn:
			TNT1 A 1;
			TNT1 A 0 A_Jump(255, "Death1", "Death2", "Death3", "Death4");
			
		Death1:
			GIBS Z -1;
			Stop;
			
		Death2:
			GIBD A -1;
			Stop;
			
		Death3:
			GIBD B -1;
			Stop;
			
		Death4:
			GIBD C -1;
			Stop;
	}
	
}// Dead on a stick ---------------

CLASS DeadDeadStick: DeadStick Replaces DeadStick { 
	Default {
		
		Health 200;
		Mass 99999999;
		Radius 16;
		Height 64;
		+SOLID;
		+SHOOTABLE;
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "ArmorShard", 128;
		DropItem "ArmorShard", 128;
		DropItem "Stimpack", 128;
		DropItem "Clip2", 128;
		DropItem "Shell", 128;
		bloodtype "DeadBlood";
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0 ;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		GibHealth 10;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("MediumBloodSpot",0,0);
			Goto Stand;
		Stand:
			POL1 A 60 A_SpawnItemEx ("TinyBlood", random (-5, 5), random (-5, 5), 15);
			Loop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnProjectile ("ZombieXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			CAPT N -1;
			Stop;
	}
}

// Still alive on a stick --------------------------------------------------

CLASS DeadLiveStick: LiveStick Replaces LiveStick { 
	Default {
		
		Health 200;
		Mass 99999999;
		Radius 16;
		Height 64;
		GibHealth 10;
		+SOLID;
		+SHOOTABLE;
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "ArmorShard", 128;
		DropItem "ArmorShard", 128;
		DropItem "Stimpack", 128;
		DropItem "Clip2", 128;
		DropItem "Shell", 128;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		bloodtype "DeadBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("MediumBloodSpot",0,0);
		Stand:
			POL6 A 6;
			POL6 B 8;
			POL6 A 6;
			POL6 B 8;
			POL6 A 6;
			POL6 B 8;
			POL6 A 6;
			POL6 B 8;
			Loop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnProjectile ("ZombieXDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			CAPT N -1;
			Stop;
	}
}

CLASS DeadBloodyTwitch : BloodyTwitch Replaces BloodyTwitch { 
	Default {
		
		Radius 16;
		Height 68;
		Health 100;
		Mass 99999999;
		-SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 10;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		bloodtype "DeadBlood";
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "ArmorShard", 128;
		DropItem "ArmorShard", 128;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			GOR1 A 1;
			TNT1 A 0 Thing_ChangeTID(0,728);
			MARN A 0 ACS_ExecuteAlways(177, 0, 0, 0, 0);//Check if you are playing on an TVR!
		Stand:
			GOR1 A 10;
			TNT1 A 0 A_JumpIfInventory("TVRRainVerification", 10, "Replacerain");
			TNT1 A 0 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
		Stand2:
			GOR1 B 15;
			GOR1 C 8;
			GOR1 B 6;
			GOR1 A 10;
			GOR1 B 15;
			GOR1 C 8;
			GOR1 B 6;
			loop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("DeadBloodyTwitchB");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
		ReplaceRain:
			TNT1 A 0 {bSHOOTABLE = false;}
			TNT1 A 0 A_SpawnItem("TVRRainSpawner");
			Stop;
			
	}
}

CLASS DeadBloodyTwitchB: DeadBloodyTwitch { 
	Default {
		
		DropItem "HealthPlus", 0;
		DropItem "HealthPlus", 0;
		DropItem "ArmorShard", 0;
		DropItem "ArmorShard", 0;
		damagefactor "Fire", 0.0;
		Health 100;
	}
	States
	{
		Spawn:
			GOR1 D 1;
			GOR1 D 15 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
			Goto Stand;
		Stand:
			GOR1 D 100;
		loop;

		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("DeadBloodyTwitchC");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

CLASS DeadBloodyTwitchC: DeadBloodyTwitchB { 
	Default {
		
		-SHOOTABLE;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			GOR1 E 10;
			loop;
	}
}

// Meat 2 ------------------------------------------------------------------

CLASS HangingBody: Meat2 Replaces Meat2 { 
	Default {
		
		Radius 16;
		Height 84;
		Health 100;
		Mass 99999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 10;
		damagefactor "Fire", 0.0;
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "ArmorShard", 128;
		DropItem "ArmorShard", 128;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		bloodtype "DeadBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
			GOR2 A 50;
		Stand:
			GOR2 A 100;
		loop;

		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("HangingPairOfLegs");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

CLASS HangingPairOfLegs: DeadBloodyTwitchB Replaces Meat4 { 
	Default {
		
		Health 100;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
			GOR2 B 25;
			Goto Stand;
		Stand:
			GOR2 B 83;
			loop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("Meat2C");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

CLASS NSHangingBody : HangingBody Replaces NonsolidMeat2 { 
	Default {
		
		
		
	}
}

CLASS NSHangingPairOfLegs : HangingPairOfLegs Replaces NonsolidMeat4 { 
	Default {
		
		
		
	}
}

CLASS Meat2C: DeadBloodyTwitchB { 
	Default {
		
		-SHOOTABLE;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			GOR2 C 10;
			loop;
	}
}

// Meat 3 ------------------------------------------------------------------

CLASS HangingDeadGuyNoLeg: Meat3 Replaces Meat3 { 
	Default {
		
		Radius 16;
		Height 84;
		Health 100;
		Mass 99999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 10;
		damagefactor "Fire", 0.0;
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "ArmorShard", 128;
		DropItem "ArmorShard", 128;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		bloodtype "DeadBlood";
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
			GOR3 A 36;
			Goto Stand;
		Stand:
			GOR3 A 100;
			loop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("HangingLeg");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}
CLASS HangingLeg: DeadBloodyTwitchB Replaces Meat5 { 
	Default {
		
		Radius 16;
		Height 84;
		Health 100;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
			GOR3 B 15;
			Goto Stand;
		Stand:
			GOR3 B 100;
			loop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("Meat3C");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

CLASS Meat3C: DeadBloodyTwitchB { 
	Default {
		
		Radius 16;
		Height 84;
		-SHOOTABLE;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			GOR3 C 10;
			loop;
	}
}

CLASS NSHangingDeadGuyNoLeg : HangingDeadGuyNoLeg Replaces NonsolidMeat3 { 
	Default {
		
		
		
	}
}

CLASS NSHangingLeg : HangingLeg Replaces NonsolidMeat5 { 
	Default {
		
		
		
	}
}

// Nonsolid bloody twitch --------------------------------------------------

CLASS DeadNonsolidTwitch : DeadBloodyTwitch Replaces NonsolidTwitch { 
	Default {
		
		
		
	}
}

// Hanging with no guts ----------------------------------------------------

CLASS DeadHangNoGuts: HangNoGuts Replaces HangNoGuts { 
	Default {
		
		Radius 20;
		Height 90;
		Health 100;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		bloodtype "DeadBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
			HDB1 A 15;
			Goto Stand;
		Stand:
			HDB1 A 90;
			loop;
		Death:
			TNT1 A 0 A_SpawnItem ("DeadHangNoGuts");
			Stop;
		XDeath:
			TNT1 A 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

// Hanging from bottom with no brain ---------------------------------------

CLASS DeadHangBNoBrain: HangBNoBrain Replaces HangBNoBrain { 
	Default {
		
		Radius 16;
		Height 88;
		Health 100;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		bloodtype "DeadBlood";
	}
	States
	{
		
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
			HDB2 A 30;
			Goto Stand;
		Stand:
			HDB2 A 90;
			loop;
			
		Death:
			TNT1 A 0 A_SpawnItem ("DeadHangBNoBrain");
			Stop;
		XDeath:
			TNT1 A 0 A_SpawnProjectile ("HalfManDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

// Hanging from top, looking down ------------------------------------------

CLASS DeadHangTLookingDown: HangTLookingDown Replaces HangTLookingDown { 
	Default {
		
		Radius 16;
		Height 64;
		Health 50;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		bloodtype "DeadBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
			HDB3 A 20;
			Goto Stand;
		Stand:
			HDB3 A 90;
			loop;
		Death:
			TNT1 A 0 A_SpawnItem ("DeadHangTLookingDown");
			Stop;
		XDeath:
			TNT1 A 0 A_SpawnProjectile ("HalfManDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

// Hanging from top, looking up --------------------------------------------

CLASS DeadHangTLookingUp: HangTLookingUp Replaces HangTLookingUp { 
	Default {
		
		Radius 16;
		Height 64;
		Health 50;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		bloodtype "DeadBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
			HDB5 A 20;
			Goto Stand;
		Stand:
			HDB5 A 90;
			loop;
		Death:
			TNT1 A 0 A_SpawnItem ("DeadHangTLookingUp");
			Stop;
		XDeath:
			TNT1 A 0 A_SpawnProjectile ("HalfManDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

// Hanging from top, skully ------------------------------------------------

CLASS DeadHangTSkull: HangTSkull replaces HangTSkull { 
	Default {
		
		Radius 16;
		Height 64;
		Health 30;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		bloodtype "DeadBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
			HDB4 A 20;
			Goto Stand;
		Stand:
			HDB4 A 90;
			loop;
		Death:
			TNT1 A 0 A_SpawnItem ("DeadHangTSkull");
			Stop;
		XDeath:
			TNT1 A 0 A_SpawnProjectile ("HalfManDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

// Hanging from top without a brain ----------------------------------------

CLASS DeadHangTNoBrain: HangTNoBrain Replaces HangTNoBrain { 
	Default {
		
		Radius 16;
		Height 64;
		Health 50;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Avoid", 0.0;
		damagefactor "Taunt", 0.0;
		bloodtype "DeadBlood";
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItemEx("TinyBlood", 0, 0, 15, 0, 0);
			HDB6 A 50;
			Goto Stand;
		Stand:
			HDB6 A 90;
			loop;
		Death:
			TNT1 A 0 A_SpawnItem ("DeadHangTNoBrain");
			Stop;
		XDeath:
			TNT1 A 0 A_SpawnProjectile ("HalfManDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}














CLASS ColonGibs2 : ACTOR Replaces ColonGibs { 
	Default {
		
		Radius 20;
		Height 4;
		+NOBLOCKMAP;
		+MOVEWITHSECTOR;
	}
	States
	{
		Spawn:
		Stay:
			POB1 A 8;
			TNT1 A 0 A_SpawnItem("MediumBloodSpot",0,0);
			POB1 A -1;
			Stop;
	}
}





// brain stem lying on the ground ------------------------------------------

CLASS BrainStem2 : ACTOR Replaces BrainStem { 
	Default {
		
		Radius 20;
		Height 4;
		+NOBLOCKMAP;
		+MOVEWITHSECTOR;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("MediumBloodSpot",0,0);
			BRS1 A -1;
			Stop;
	}
}


CLASS RealGibs2 : ACTOR Replaces RealGibs { 
	Default {
		
		+DROPOFF;
		+CORPSE;
		+NOTELEPORT;
		+DONTGIB;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_SpawnItem("MediumBloodSpot",0,0);
			POL5 A -1;
			Stop;
	}
}

CLASS Gibs2 : RealGibs2 Replaces Gibs { 
	Default {
		
		ClearFlags;
	}
}











	   
CLASS CrushedRemains: CurbstompedMarine { 
	Default {
		
		-SHOOTABLE;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			CRS1 A 1;
			TNT1 A 0 doomb_spawn_bloodpool();
			CRS1 A -1;
			Stop;
	}
	
}	   
	   
CLASS PlayerJustGotCutInHalf: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			XPL2 GHIJKL 5;
			XPL2 L -1 A_SpawnItem("MediumBloodSpot");
			Stop;
	}
	
}	   
	   
CLASS DeadNazi: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			NAZI L -1;
			Stop;
	}
}
