CLASS doomb_dead_marine : doomb_body_base
{ 
	Default {
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0 ;
		damagefactor "Taunt", 0.0;
		
		+CLIENTSIDEONLY;
		+FLOORCLIP;
		Radius 0;
	}
	States
	{
		Spawn:
			TNT1 AAAAA 0 doomb_spray_decal("BrutalBloodSuper");
			TNT1 a 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 1
			{
				uint choise = random(0, 5);

				switch (choise)
				{
					case 0:
						spawn("CurbstompedMarine", pos);
					break;

					case 1:
						Spawn("AteMarine", pos);
					break;

					case 2:
						Spawn("DeadRippedOffMarine", pos);
					break;
		
					case 3:
						Spawn("FuckedMarine", pos);
					break;

					case 4:
						Spawn("ADoomedSpaceMarine2", pos);
					break;

					case 5:
						Spawn("ADoomedSpaceMarine", pos);
					break;

					default:
					break;
				}
			}
		Stop;
	}
}

CLASS doomb_gibbed_marine : doomb_body_base
{ 
	Default {
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 AAAAA 0 doomb_spray_decal("BrutalBloodSuper");
			TNT1 a 0 doomb_spawn_bloodpool();
			TNT1 A 0 doomb_spawn_bloodpool();
			TNT1 A 1
			{
				uint choise = random(0, 2);

				switch (choise)
				{
					case 0:
						spawn("GibsZ", pos);
					break;

					case 1:
						Spawn("VeryDeadCivilian", pos);
					break;

					case 2:
						Spawn("GutsPile", pos);
					break;
		
					default:
					break;
				}
			}
		Stop;
	}
}




CLASS CurbstompedMarine : doomb_body_base { 
	Default {
		
		Radius 10;
		Height 6;
		+NOTELEPORT;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		+MOVEWITHSECTOR;
		+FLOORCLIP;
		+NOBLOCKMONST;
		+CANPASS;
		+THRUACTORS;
		+FORCEXYBILLBOARD;
		+SHOOTABLE;
		+CLIENTSIDEONLY;
		+CORPSE;
		damagefactor "Crusher", 50.0;
		Mass 5000;
		Health 300;
		PainChance 255;
		Mass 6000;
		
		damagefactor "Normal", 2.0;
		damagefactor "Desintegrate", 990.0;
		damagefactor "BFG", 990.0;
		damagefactor "Kick", 3.0;
		damagefactor "punch", 2.0;
	}
	States
	{
		Spawn:
			PLDH A 3000;
			Loop;
			
		Death.Fire:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnItem("doomb_half_burned_body");
			Stop;
			
		Death:
		Death.Stomp:
		Death.Explosive_Impact:
			TNT1 A 0 A_SpawnItem("GibsZ");
			TNT1 A 0 A_NoBlocking;
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(5, 15) ) );
			TNT1 AAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 AAAA 0
			{
				actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 35 ) );
				if(a)
					a.scale = (0.45, 0.45);
			}
		Stop;
			
		Death.plasma:
			TNT1 A 0;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_XScream;
			TNT1 A 0 A_NoBlocking;
			TNT1 AAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 A 0 doomb_spawn_burned_flesh;
			EXPL AAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0;
			Stop;
			
		Death.Trample: 
		Death.Crush:
		Death.Stomp:
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(5, 15) ) );
			TNT1 AAAA 0 doomb_for_khorne("blood_impact_splash", (0, 0, 5) );
			TNT1 A 0 doomb_spawn_bloodpool();
			XME2 L -1;
			Stop;
			
		Death.Desintegrate:
			TNT1 A 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 AAAA 0
			{
				actor a = doomb_for_khorne("blood_impact_splash", (0, 0, 5 ) );
				if(a)
					a.scale = (0.45, 0.45);
			}
			TNT1 A 0 A_SpawnItem("GibsZ");
			TNT1 A 0 doomb_Meat_Death_Small();
		Stop;
	}
	
}
CLASS RappedMarine: CurbstompedMarine { 

	States
	{
		Spawn:
			XPL4 F 1;
			Loop;
	}
	
}
CLASS AteMarine: CurbstompedMarine { 
	States
	
	{
		Spawn:
			XPL1 E -1;
			stop;
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, - random (0, 180));
			TNT1 A 0 doomb_Rip_Guts();
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			TNT1 A 0 A_SpawnItem("DeadRippedOffMarine");
			Stop;
	}
	
}

CLASS FuckedMarine: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			XPL3 F -1;
			stop;
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, - random (0, 180));
			TNT1 A 0 doomb_Rip_Guts();
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			TNT1 A 0 A_SpawnItem("DeadRippedOffMarineRight");
			Stop;
			
	}
	
}	   
	   
	   


CLASS DeadRippedOffMarine: CurbstompedMarine { 
	Default {
		
	}
	States
	{
		Spawn:
			XPL2 F -1;
			stop;
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_Meat_Death_Small();
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			TNT1 A 0 A_SpawnItem("GibsZ");
			Stop;
	}
	
}

CLASS DeadRippedOffMarineRight: DeadRippedOffMarine { 
	States
	{
		Spawn:
			XPL2 L -1;
			stop;
			
			
	}
	
}
CLASS VeryDeadCivilian: CurbstompedMarine { 
	States
	{
		Spawn:
			DCIV A -1;
			stop;
	}
	
}

CLASS MarineGotOwnedByImp: CurbstompedMarine { 
	States
	{
		Spawn:
			IPFP P -1;
		stop;
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, - random (0, 180));
			TNT1 A 0 doomb_Meat_Death_Small();
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			PPOD A 0 A_SpawnItemEx("BasicMarineGib1", 0, 0, 0, 0, 0, 0, 0, SXF_TRANSFERTRANSLATION);
			TNT1 A 0 A_SpawnItem("DeadRippedOffMarine");
			Stop;
	}
	
}	   
CLASS ADoomedSpaceMarine: CurbstompedMarine { 
	States
	{
		Spawn:
			PLAY N -1;
			Loop;
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, - random (0, 180));
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 A 0 A_SpawnItem("AteMarine");
			Stop;
	}
	
}	   
CLASS ADoomedSpaceMarine2: CurbstompedMarine { 
	States
	{
		Spawn:
			PLA9 N -1;
			Loop;
			
			
		Death:
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 doomb_Meat_Death_Small();
			TNT1 A 0 A_SpawnProjectile ("XDeathArm1", 15, 0, random (0, 360), 2, - random (0, 180));
			TNT1 A 0 A_SpawnItem("AteMarine");
			Stop;
			
			
	}
	
}
CLASS DeadHalfMarine: CurbstompedMarine { 
	States
	{
		Spawn:
			HPLA A -1;
			Loop;
	}
	
}
CLASS GutsPile : ACTOR { 
	Default {
		Radius 1;
		Height 1;
	}
	States
	{
		Spawn:
			GUTS P -1;
			Stop;
	}
	
}

CLASS doomb_half_burned_body : doomb_body_base { 
	Default {
		Radius 1;
		Height 1;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			GIBD SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 6 light("BIGREDTORCH")
			{
				A_Explode(3,30, damagetype:"fire");
				Spawn("RedFlare", pos);
				doomb_show_effect("ExplosionSmoke", (0, 0, 20), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
				doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
			}
			GIBD SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (0.5, 0), 0.1 );
			GIBD S -1;
			stop;
	}
	
}

CLASS GibsZ : doomb_body_base
{ 
	Default {
		Radius 1;
		Height 1;
	}
	States
	{
		Spawn:
			GIBS Z -1
			{
				frame = randompick(0, 1, 2, 27);
			}
		Stop;
	}
	
}
// Dead on a stick ---------------
CLASS DeadDeadStick: doomb_body_base
{ 
	Default {
		
		Health 200;
		Mass 99999999;
		Radius 16;
		Height 64;
		+SOLID;
		+SHOOTABLE;
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "ArmorShard", 128;
		DropItem "ArmorShard", 128;
		DropItem "Stimpack", 128;
		DropItem "Clip", 128;
		DropItem "Shell", 128;
		
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0 ;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
		GibHealth 10;
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_spawn_bloodpool();
		Stand:
			POL1 A 60 doomb_for_khorne("TinyBlood", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
		Loop;

		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnProjectile ("ZombieXDeath", 0, 0, random (0, 360), 2, random (0, 160));
			CAPT N -1;
			Stop;
	}
}

// Still alive on a stick --------------------------------------------------

CLASS doomb_living_stick : doomb_body_base
{ 
	Default {
		
		Health 200;
		Mass 99999999;
		Radius 16;
		Height 64;
		GibHealth 10;
		+SOLID;
		+SHOOTABLE;
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "ArmorShard", 128;
		DropItem "ArmorShard", 128;
		DropItem "Stimpack", 128;
		DropItem "Clip", 128;
		DropItem "Shell", 128;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
		
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 doomb_spawn_bloodpool();
		Stand:
			POL6 A 6;
			POL6 B 8;
			POL6 A 6;
			POL6 B 8;
			POL6 A 6;
			POL6 B 8;
			POL6 A 6;
			POL6 B 8;
			Loop;
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnProjectile ("ZombieXDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			CAPT N -1;
			Stop;
	}
}

CLASS DeadBloodyTwitch : doomb_body_base
{ 
	Default {
		
		Radius 16;
		Height 68;
		Health 100;
		Mass 99999999;
		-SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 10;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
		
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "ArmorShard", 128;
		DropItem "ArmorShard", 128;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			GOR1 A 1;
		Stand:
			GOR1 A 10;
			TNT1 A 0 doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
		Stand2:
			GOR1 B 15;
			GOR1 C 8;
			GOR1 B 6;
			GOR1 A 10;
			GOR1 B 15;
			GOR1 C 8;
			GOR1 B 6;
		loop;

		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("DeadBloodyTwitchB");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
		Stop;
	}
}

CLASS DeadBloodyTwitchB: DeadBloodyTwitch { 
	Default {
		
		DropItem "HealthPlus", 0;
		DropItem "HealthPlus", 0;
		DropItem "ArmorShard", 0;
		DropItem "ArmorShard", 0;
		damagefactor "Fire", 0.0;
		Health 100;
	}
	States
	{
		Spawn:
			GOR1 D 15 doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
			GOR1 D 100;
		loop;

		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("DeadBloodyTwitchC");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

CLASS DeadBloodyTwitchC: DeadBloodyTwitchB { 
	Default {
		
		-SHOOTABLE;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			GOR1 E 10;
			loop;
	}
}

// Meat 2 ------------------------------------------------------------------

CLASS HangingBody: doomb_body_base
{ 
	Default {
		Radius 16;
		Height 84;
		Health 100;
		Mass 99999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 10;
		damagefactor "Fire", 0.0;
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "ArmorShard", 128;
		DropItem "ArmorShard", 128;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
		
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
			GOR2 A 11100;
		loop;

		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("HangingPairOfLegs");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

CLASS HangingPairOfLegs: DeadBloodyTwitchB
{ 
	Default {
		
		Health 100;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
			GOR2 B 1283;
		loop;
		
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("Meat2C");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
		Stop;
	}
}


CLASS Meat2C: DeadBloodyTwitchB
{ 
	Default {
		
		-SHOOTABLE;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			GOR2 C 10;
			loop;
	}
}

// Meat 3 ------------------------------------------------------------------

CLASS HangingDeadGuyNoLeg: doomb_body_base
{ 
	Default {
		
		Radius 16;
		Height 84;
		Health 100;
		Mass 99999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 10;
		damagefactor "Fire", 0.0;
		DropItem "HealthPlus", 128;
		DropItem "HealthPlus", 128;
		DropItem "ArmorShard", 128;
		DropItem "ArmorShard", 128;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
		
	}
	States
	{
		
		Spawn:
			TNT1 A 0 doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
			GOR3 A 1100;
		loop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("HangingLeg");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}
CLASS HangingLeg: DeadBloodyTwitchB
{
	Default {
		
		Radius 16;
		Height 84;
		Health 100;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
			GOR3 B 1100;
		loop;
			
		Death:
			TNT1 A 0 A_NoBlocking;
			TNT1 A 0 A_Scream;
			TNT1 A 0 A_SpawnItem ("Meat3C");
			TNT1 A 0 A_SpawnProjectile ("MeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

CLASS Meat3C: DeadBloodyTwitchB { 
	Default {
		
		Radius 16;
		Height 84;
		-SHOOTABLE;
		damagefactor "Fire", 0.0;
	}
	States
	{
		Spawn:
			GOR3 C 10;
			loop;
	}
}


// Hanging with no guts ----------------------------------------------------

CLASS DeadHangNoGuts: doomb_body_base
{ 
	Default {
		Radius 20;
		Height 90;
		Health 100;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
		
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
			HDB1 A 1190;
		loop;
		
		Death:
			TNT1 A 0 A_SpawnItem ("DeadHangNoGuts");
			Stop;
		XDeath:
			TNT1 A 0 A_SpawnProjectile ("MuchMeatDeath", 0, 0, random (0, 360), 2, - random (0, 160));
			Stop;
	}
}

// Hanging from bottom with no brain ---------------------------------------

CLASS DeadHangBNoBrain: doomb_body_base
{
	Default {
		Radius 16;
		Height 88;
		Health 300;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
		
	}
	States
	{
		Spawn:
			HDB2 A 1
			{
				if(random(0, 20) >= 20 )
					doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
			}
		loop;
			
		Death:
		XDeath:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 AAAAAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
			TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AAAAAAAAAAAAAA 0
			{
				actor a = doomb_for_khorne("blood_impact_splash", (random(-20, 20), random(-20, 20), random(20, 30) ) );
				if(a)
					a.scale = (1.4, 1.4);
			}
		Stop;
	}
}



// Hanging from top, looking down ------------------------------------------

CLASS DeadHangTLookingDown: doomb_body_base
{
	Default {
		Radius 16;
		Height 64;
		Health 50;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
		
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
			HDB3 A 1190;
		loop;

		Death:
		XDeath:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );

			TNT1 AAAAAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
			TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AAAAAAAAAAAAAA 0
			{
				actor a = doomb_for_khorne("blood_impact_splash", (random(-20, 20), random(-20, 20), random(20, 30) ) );
				if(a)
					a.scale = (1.4, 1.4);
			}
		Stop;
	}
}

// Hanging from top, looking up --------------------------------------------

CLASS DeadHangTLookingUp: doomb_body_base
{
	Default {
		
		Radius 16;
		Height 64;
		Health 50;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
		
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
			HDB5 A 1190;
		loop;
		
		Death:
		XDeath:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 AAAAAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
			TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AAAAAAAAAAAAAA 0
			{
				actor a = doomb_for_khorne("blood_impact_splash", (random(-20, 20), random(-20, 20), random(20, 30) ) );
				if(a)
					a.scale = (1.4, 1.4);
			}
		Stop;
	}
}

// Hanging from top, skully ------------------------------------------------
CLASS DeadHangTSkull: doomb_body_base
{
	Default {
		
		Radius 16;
		Height 64;
		Health 30;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
		
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
			HDB4 A 1190;
		loop;
		
		Death:
		XDeath:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 AAAAAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
			TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AAAAAAAAAAAAAA 0
			{
				actor a = doomb_for_khorne("blood_impact_splash", (random(-20, 20), random(-20, 20), random(20, 30) ) );
				if(a)
					a.scale = (1.4, 1.4);
			}
		Stop;
	}
}

// Hanging from top without a brain ----------------------------------------

CLASS DeadHangTNoBrain: doomb_body_base
{
	Default {
		
		Radius 16;
		Height 64;
		Health 50;
		Mass 999999;
		+SOLID;
		+NOGRAVITY;
		+SPAWNCEILING;
		+SHOOTABLE;
		GibHealth 30;
		damagefactor "Fire", 0.0;
		damagefactor "Blood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "Taunt", 0.0;
		
		damagefactor "Taunt", 0.0;
		
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_for_khorne("TinyBlood", (0, 0, 15 ), doomb_random_velocity(5) );
			HDB6 A 1190;
		loop;
		
		Death:
		XDeath:
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 AAAAAAAAA 0 doomb_sticky_guro(SGT_BLOOD);
			TNT1 AA 0 A_SpawnProjectile ("XDeathArm1", 32, 0, random (0, 360), 2, random (0, 160));
			TNT1 AA 0 doomb_spawn_entrails( (0, 0, random(30, 35) ) );
			TNT1 AAAAAAAA 0 doomb_for_khorne("doomb_red_blood_trail", (0, 0, random(20, 30) ), doomb_random_velocity(5) );
			TNT1 AAAAAAAAAAAAAA 0
			{
				actor a = doomb_for_khorne("blood_impact_splash", (random(-20, 20), random(-20, 20), random(20, 30) ) );
				if(a)
					a.scale = (1.4, 1.4);
			}
		Stop;
	}
}














CLASS ColonGibs2 : doomb_body_base
{
	Default {
		
		Radius 20;
		Height 4;
		+NOBLOCKMAP;
		+MOVEWITHSECTOR;
	}
	States
	{
		Spawn:
		Stay:
			POB1 A 8;
			TNT1 A 0 doomb_spawn_bloodpool();
			POB1 A -1;
			Stop;
	}
}





// brain stem lying on the ground ------------------------------------------

CLASS BrainStem2 : doomb_body_base
{
	Default {
		
		Radius 20;
		Height 4;
		+NOBLOCKMAP;
		+MOVEWITHSECTOR;
	}
	States
	{
		Spawn:
			TNT1 A 0 doomb_spawn_bloodpool();
			BRS1 A -1;
			Stop;
	}
}


CLASS RealGibs2 : doomb_body_base
{
	Default {
		
		+DROPOFF;
		+CORPSE;
		+NOTELEPORT;
		+DONTGIB;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 A 0 doomb_spawn_bloodpool();
			POL5 A -1;
			Stop;
	}
}











	   
CLASS CrushedRemains: CurbstompedMarine { 
	Default {
		
		-SHOOTABLE;
		+CLIENTSIDEONLY;
	}
	States
	{
		Spawn:
			TNT1 A 0 nodelay doomb_spawn_bloodpool();
			CRS1 A -1;
			Stop;
	}
	
}	   
	   
CLASS PlayerJustGotCutInHalf: CurbstompedMarine { 
	States
	{
		Spawn:
			XPL2 GHIJKL 5;
			TNT1 A 0 doomb_spawn_bloodpool();
			XPL2 L -1;
			Stop;
	}
	
}	   
	   
CLASS DeadNazi: CurbstompedMarine { 
	States
	{
		Spawn:
			NAZI L -1;
			Stop;
	}
}
