class doomb_decoration_base : actor
{
protected eventhandler sfx;
void set_effects(eventhandler e)
{
    if(e.getclassname() == "doomb_sfx_main")
        sfx = e;
}

protected actor doomb_show_effect(statelabel effect_name, vector3 offset = (0, 0, 0), vector3 velocity = (0, 0, 0), vector2 visual_size = (double.nan, double.nan), double translucency = double.nan)
{
	return doomb_sfx_main(sfx).show_some_effect(self, effect_name, offset, velocity, visual_size, translucency);
}

}