CLASS ExplosiveBarrel1 : doomb_decoration_base Replaces ExplosiveBarrel  { 
Default {
	damagefactor "Trample", 0.0;
	damagefactor "Kick", 0.1;
	damagefactor "Melee", 0.1;
	damagefactor "punch", 0.1;
	damagefactor "Fatality", 10.1;
	damagefactor "Explosive_Impact", 0.4;
	damagefactor "Fire", 3.5;
	damagefactor "BHFTOnBarrel", 500.0;
	damagefactor "Blood", 0.0;
	damagefactor "BlueBlood", 0.0;
	damagefactor "GreenBlood", 0.0  ;
	
	Health 20;
	Radius 10;
	Height 34;
	Mass 200;
	DamageType "Explosive_Impact";
	
	+SOLID;
	+SHOOTABLE;
	+NOBLOOD;
	+ACTIVATEMCROSS;
	+NOICEDEATH;
	+PUSHABLE;
	+SLIDESONWALLS;
	+WINDTHRUST;
	+TELESTOMP;
	+FLOORCLIP;
	+FRIENDLY;
	+MISSILEMORE;
	+MISSILEEVENMORE;
	+EXTREMEDEATH;
	MONSTER;
	-COUNTKILL;

	Speed 0;
	MaxTargetRange 200;
	DamageFactor "BHFT", 10.0;
	Painchance "Blood", 255;
	PainChance "Kick", 255;
	DeathSound "Explosion";
	Obituary "$OB_BARREL";
	Painchance 255;
}
States
{
	Spawn:
		tnt1 A 0 nodelay {flare_general.doomb_attach_flare(self, "greenlensflarealtsmall", (0, 0, 32));}
	Stay:
		BAR1 ABCDEEFGHIIJKLM 4 light("GREENGOOZ");
	Loop;
		
	Pain:
	Goto Stay;
		
	Pain.Blood:
		TNT1 A 0;
	bloody_barrel:
		BARB AB 4;
	Loop;
		
	Pain.Kick:
	Pain.punch:
		TNT1 A 0 {bFRIENDLY = false;}
		BAR1 A 1 A_Pain();
		BAR1 A 0 A_Chase(null,null);
		BAR1 A 1 A_FaceTarget();
		TNT1 A 0 HealThing(100);
		TNT1 A 0 ThrustThingZ(0,10,0,1);
		TNT1 A 0 {bFRIENDLY = true;}
	Goto Stay;
		
	Death:
		BEXP AB 2;
		TNT1 A 0 A_SpawnItem("WhiteShockwaveBig");
		TNT1 A 0 A_Explode(160,200);
		BEXP CD 2 BRIGHT light ("ROCKET_X1");
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_Fall();
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_SpawnItem("WhiteShockwaveBig");
		TNT1 A 0 A_Explode(160,200, damagetype: "explosive_impact");
		TNT1 AAAAAA 0
		{
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
		}

		TNT1 AAAAAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		EXPL A 0 Radius_Quake (2, 24, 0, 15, 0);
		BEXP B 0 BRIGHT A_Scream();
		
		TNT1 AA 0 A_SpawnProjectile ("BarrelShrapnel1", 25, 0, random (0, 360), 2, - random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("BarrelShrapnel2", 15, 0, random (0, 360), 2, - random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("BarrelShrapnel3", 5, 0, random (0, 360), 2, - random (0, 160));
		TNT1 A 0 A_SpawnProjectile ("BarrelShrapnel4", 5, 0, random (0, 360), 2, - random (0, 160));
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ShrapnelParticle", (0, 0, 0), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), 0.5 ) );
		TNT1 A 0 A_PlaySound("FAREXPL", 3);
		TNT1 A 0 A_SpawnItem("WhiteShockwaveBig");
		TNT1 A 0 A_Explode(160,200);
		TNT1 AAAAAA 0 doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
		
		TNT1 AAAAA 8 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		
		BEXP Z 300 BRIGHT A_BarrelDestroy();
		BEXP Z 5 A_Respawn();
		Wait;
		
	Death.BHFT:
	Death.BHFTOnBarrel:
	Death.Fatality:
		TNT1 A 0 A_NoBlocking();
	Stop;
		
	Death.Kick:
	Death.punch:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 {bTHRUACTORS = true;}
		TNT1 A 1;
		TNT1 A 0 A_SPawnItem("ExplosiveBarrel1");
		Stop;
		
}
}



CLASS BarrelShrapnel1 : ACTOR { 
Default {
	
	Radius 2;
	Height 2;
	Speed 20;
	Mass 1;
	+NOBLOCKMAP;
	+MISSILE;
	+NOTELEPORT;
	+MOVEWITHSECTOR;
	+CLIENTSIDEONLY;
	+THRUACTORS;
	+FLOORCLIP;
	+DOOMBOUNCE;
	-NOGRAVITY;
	BounceFactor 0.5;
	Gravity 0.9;
	Mass 1;
}
States
{
	Spawn:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "death");
		BRPT ABCDEFGH 1;
		TNT1 A 0 {bNOGRAVITY = false;}
	Spawn2:
		TNT1 A 0 A_JumpIf(waterlevel > 1, "death");
		BRPT ABCDEFGH 2;
		Loop;
		
	Death:
		TNT1 A 0;
		BRPT I 300;
		BRPT IIIIIIIII 2 A_FadeOut(0.1);
		Stop;
}
}


CLASS BarrelShrapnel2: BarrelShrapnel1 { 
Default {
	
	Scale 1.7;
}
}

CLASS BarrelShrapnel3: BarrelShrapnel1 { 
Default {
	
	Scale 1.4;
}
}

CLASS BarrelShrapnel4: BarrelShrapnel1 { 
Default {
	
	Scale 1.2;
}
}

















CLASS ExplosionSpawner : visual_sfx { 
Default {
	
	+MISSILE;
	+FORCEXYBILLBOARD;
	damage 0;
	radius 6;
	height 6;
	speed 40;
	renderstyle "Add";
	alpha 0.9;
	scale .01;
	BounceFactor 0.5;
	Decal "FireworxScorch";
}
states
{
	Spawn:
		TNT1 AAAA 0
		{
			A_PlaySound("FAREXPL");
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		}
	Stop;
}
}






CLASS SpawnedExplosion : visual_sfx { 
Default {
	
	+NOCLIP;
	+NOGRAVITY;
}
states
{
	Spawn:
		TNT1 A 2;
		TNT1 A 0 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		Stop;
}
}

CLASS SpawnedExplosionRepeat : visual_sfx { 
Default {
	
	+NOCLIP;
	+NOGRAVITY;
}
states
{
	Spawn:
		TNT1 A 2;
		TNT1 A 2 A_PlaySound("FAREXPL");
		EXPL A 0 doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		EXPL A 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		TNT1 A 3;
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		TNT1 A 3;
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		TNT1 A 3;
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		TNT1 A 3;
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(3, 3.4), 0) );
		TNT1 A 3;
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(3, 3.4), 0) );
		TNT1 A 3;
		TNT1 AAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(3, 3.4), 0) );
		Stop;
}
}
























CLASS FireworkSFXType1 : visual_sfx { 
Default {
	
	Radius 4;
	Height 4;
	Speed 18;
	PROJECTILE;
	+THRUGHOST;
	RenderStyle "Add";
	+MISSILE;
	-NOGRAVITY;
	Gravity 1;
	Alpha 1.0;
}
States
{
	Spawn:
		TNT1 A 0 doomb_show_effect("FlameTrails", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		TNT1 AA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		TNT1 A 1 A_SpawnItem("RedFlareSmall");
		TNT1 A 1 A_SpawnItem("RedFlareSmall");
		Loop;
		
	Death:
		TNT1 A 0 doomb_show_effect("TinyBurningPiece", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ) );
		Stop;
}
}
