
CLASS TreeBlood : ACTOR { 
	Default {
		
		renderstyle "Add";
		alpha 1.0;
		-COUNTKILL;
		-SHOOTABLE;
		+CLIENTSIDEONLY;
		+BLOODLESSIMPACT;
		+FORCEXYBILLBOARD;
		+THRUACTORS;
		+NOGRAVITY;
		Scale 0.09;
		Speed 0;
		Radius 1;
		Height 1;
	}
	states
	{
		Spawn:
			TNT1 AA 0 A_SpawnProjectile ("WoodParticleTIny", 2, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItem("RicoChet");
			Stop;
			
	}
}


// Trees ----------------------------------------------------------------

CLASS half_burned_tree: doomb_decoration_base Replaces TorchTree { 
	Default {
		Radius 16;
		Height 56;
		Health 200;

		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Explosive_Impact" , 10.0;
		damagefactor "Plasma", 10.0;
		damagefactor "Fire", 5.0;
		BloodType "TreeBlood";

		+SOLID;
		+SHOOTABLE;
		+FORCEYBILLBOARD;
		+NOBLOODDECALS;
		+DONTTHRUST
	}
	States
	{
		Spawn:
			TRE1 A -1;
		Stop;

		Death:
			TRE1 B 1
			{
				bsolid = true;
				a_setsize(16, 35);
			}
			TNT1 AAA 0
			{
				A_SpawnProjectile ("WoodParticle", 35, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("WoodParticleSmall", 25, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("WoodParticleTiny", 55, 0, random (0, 360), 2, random (0, 160));
				A_SpawnProjectile ("WoodParticleBig", 65, 0, random (0, 360), 2, random (0, 160));
			}
			TRE1 B -1;
		Stop;

		XDeath:
		death.Explosive_Impact:
		deatrh.Plasma:
		death.Fire:
			TRE1 B 1
			{
				bsolid = true;
				a_setsize(16, 35);
				doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			}
		xdeath_loop:
			TNT1 A 0 A_Playsound("props/redfire");
			TRE1 CCC 3 bright light ("FIREBARREL")
			{
				doomb_show_effect("GunFireSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.2, 0) );
				Spawn("RedFlare", pos + (0, 0, 32));
				doomb_show_effect("RealFlameTrailsSmall", (0, 0, 0), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ), (frandom(1, 1.2), 0) );
			}
		Loop;
	}
}




CLASS Big_Tree: doomb_decoration_base Replaces BigTree
{
	Default {
		Radius 32;
		Height 84;
		ProjectilePassHeight -16;
		deathheight 42;
		Mass 999999999999999;
		Health 500;

		BloodType "TreeBlood";
		PainChance "Blood", 255;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Plasma", 10.0;
		damagefactor "Explosive_Impact", 10.0;
		damagefactor "Fire", 5.0;
		damagefactor "Blood", 10.0;

		+DONTTHRUST
		+SOLID;
		+SHOOTABLE;
		+NOBLOODDECALS;
		+FORCEYBILLBOARD;
		-NOPAIN;
	}
	States
	{
		Spawn:
			TRE2 O -1 nodelay
			{
				scale.x = randompick(-1, 1);
				scale.y = frandom(0.8, 1.2);
			}
		Stop;
			
		Pain.Blood:
			TRE2 M -1;
		Stop;
			
		Death:
			TRE2 B 1;
			TNT1 AAAAA 0 A_SpawnProjectile ("WoodParticle", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("WoodParticleSmall", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAA 0 A_SpawnProjectile ("WoodParticleTiny", 65, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("WoodParticleBig", 85, 0, random (0, 360), 2, random (0, 160));
			TRE2 B -1;
		Stop;
			
		XDeath:
		death.Explosive_Impact:
		deatrh.Plasma:
		death.Fire:
			TRE2 NNNNNNNNNN 1 bright light ("FIREBARREL")
			{
				doomb_show_effect("RealFlameTrailsSmall", (0, 0, 40), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ), (frandom(1, 1.2), 0) );
				Spawn("RedFlare", pos + (0, 0, random(60, 90)) );
			}

			TNT1 A 0
			{
				A_Playsound("props/redfire");
				A_Explode(10,5, damagetype:"fire");
				doomb_show_effect("BigBlackSmoke", velocity:(frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0, 2) ), visual_size: (frandom(0.2, 0.4), 0) );
			}
		Loop;
	}
}






CLASS Wolfenstein3DFlowerPot : ACTOR { 
	Default {
		+DONTTHRUST
		Radius 8;
		Height 60;
		sCALE 1.2;
		+SOLID;
	}
	States
	{
		Spawn:
			WLZ7 B -1;
		stop;
	}
}