
CLASS TreeBlood : ACTOR { 
	Default {
		
		renderstyle "Add";
		alpha 1.0;
		-COUNTKILL;
		-SHOOTABLE;
		+CLIENTSIDEONLY;
		+BLOODLESSIMPACT;
		+FORCEXYBILLBOARD;
		+THRUACTORS;
		+NOGRAVITY;
		Scale 0.09;
		Speed 0;
		Radius 1;
		Height 1;
	}
	states
	{
		Spawn:
			TNT1 AA 0 A_SpawnProjectile ("WoodParticleTIny", 2, 0, random (0, 360), 2, random (0, 360));
			TNT1 A 0 A_SpawnItem("RicoChet");
			Stop;
			
	}
}


// Trees ----------------------------------------------------------------

CLASS TorchTree2: doomb_decoration_base Replaces TorchTree { 
	Default {
		Radius 16;
		Height 56;
		deathheight 32;
		damagefactor "Blood", 0.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Plasma", 10.0;
		damagefactor "Flames", 5.0;
		damagefactor "Fire", 5.0;
		+SOLID;
		+SHOOTABLE;
		BloodType "TreeBlood";
		+FORCEYBILLBOARD;
		+NOBLOODDECALS;
		Mass 999999999999999;
		damagefactor "Explosive_Impact" , 10.0;
		Health 200;
	}
	States
	{
		Vanilla:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("VanillaSmallTree");
			Stop;
			
		Spawn:
			TRE2 O 0;
			TRE2 O 0 Thing_ChangeTID(0,748);
			TRE2 O 3;
		Spawn2:
			TRE1 A -1;
			Stop;
		Death:
			TRE1 B 1;
			TNT1 AAA 0 A_SpawnProjectile ("WoodParticle", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("WoodParticleSmall", 25, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("WoodParticleTiny", 55, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAA 0 A_SpawnProjectile ("WoodParticleBig", 65, 0, random (0, 360), 2, random (0, 160));
			TRE1 B -1;
			Stop;
			
		Death.Plasma:
		Death.Fire:
			TRE1 B 1;
			TNT1 AAAAAAA 0 doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			TNT1 A 0 A_SpawnItem("TorchTreeInFlames",0,1);
			Stop;
	}
}


CLASS TorchTreeInFlames : doomb_decoration_base { 
	Default {
		
		+LOOKALLAROUND;
		+SHOOTABLE;
		+INVULNERABLE;
		+NOBLOOD;
		Mass 999999999999999999999;
		height 35;
		scale 1.0;
	}
	states
	{
		Spawn:
			TNT1 A 0 A_Playsound("props/redfire");
			TRE1 C 0 doomb_show_effect("GunFireSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ), (1.2, 0) );
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", 38, 0, random (0, 360), 2, random (50, 130));
			TRE1 C 3 bright A_SpawnItem("RedFlare3",0,32);
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", 38, 0, random (0, 360), 2, random (50, 130));
			TRE1 C 3 bright A_SpawnItem("RedFlare3",0,32);
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", 38, 0, random (0, 360), 2, random (50, 130));
			TRE1 C 3 bright A_SpawnItem("RedFlare3",0,32);
			Loop;
			
	}
}


CLASS BigTreeReplacer : RandomSpawner Replaces BigTree { 
	Default {
		
		DropItem "Big_Tree";
		DropItem "Big_Tree2";
		DropItem "Big_Tree3";
		DropItem "Big_Tree4";
	}
}

CLASS Big_Tree: BigTree { 
	Default {
		
		
		Radius 32;
		Height 84;
		+NOBLOODDECALS;
		ProjectilePassHeight -16;
		deathheight 42;
		PainChance "Blood", 255;
		damagefactor "Explosive_Impact", 10.0;
		damagefactor "BlueBlood", 0.0;
		damagefactor "GreenBlood", 0.0;
		damagefactor "Plasma", 10.0;
		damagefactor "Flames", 5.0;
		damagefactor "Fire", 5.0;
		damagefactor "Blood", 10.0;
		+SOLID;
		+SHOOTABLE;
		+FORCEYBILLBOARD;
		-NOPAIN;
		Mass 999999999999999;
		Health 500;
		BloodType "TreeBlood";
	}
	States
	{
		
		Vanilla:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("VanillaBigTree");
			Stop;
		Spawn:
			TRE2 O 0;
			TRE2 O 0 Thing_ChangeTID(0,748);
			TRE2 O 3;
		Spawn2:
			TRE2 O -1;
			Stop;
			
		Pain.Blood:
			TRE2 M 1;
			TRE2 M -1;
			Stop;
			
		Death:
			TRE2 B 1;
			TNT1 AAAAA 0 A_SpawnProjectile ("WoodParticle", 35, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAA 0 A_SpawnProjectile ("WoodParticleSmall", 45, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAA 0 A_SpawnProjectile ("WoodParticleTiny", 65, 0, random (0, 360), 2, random (0, 160));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("WoodParticleBig", 85, 0, random (0, 360), 2, random (0, 160));
			TRE2 B -1;
			Stop;
			
		Death.Fire:
		Death.Plasma:
		Death.Plasma2:
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			TRE2 N 1;
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", random (40, 59), random (-10, 10), random (0, 360), 2, random (10, 55));
			BURB A 0 bright A_SpawnItem("RedFlare3",0,random (60, 90));
			
			TNT1 A 0 A_Playsound("props/redfire");
			BURB A 0 A_SpawnItem("BurningBarrelDamage",0,50);
			TNT1 A 0 bright A_SpawnProjectile ("MediumBlackSmoke", 88, 0, random (40, 180), 2, random (40, 120));
			Loop;
	}
}


CLASS Big_Tree2: Big_Tree { 
	Default {
		
		XScale -1.0;
	}
}

CLASS Big_Tree3: Big_Tree { 
	Default {
		
		XScale -1.1;
		YScale 0.8;
	}
}

CLASS Big_Tree4: Big_Tree { 
	Default {
		
		YScale 1.2;
	}
}






CLASS Wolfenstein3DFlowerPot : ACTOR { 
	Default {
		
		
		Radius 8;
		Height 60;
		sCALE 1.2;
		+SOLID;
	}
	States
	{
		Spawn:
			WLZ7 B 1;
			WLZ7 B -1;
			Loop;
	}
}






CLASS VanillaBigTree : ACTOR { 
	Default {
		
		
		Radius 24;
		Height 108;
		ProjectilePassHeight -16;
		+SOLID;
		+SHOOTABLE;
		BloodType "TreeBlood";
		+NOBLOODDECALS;
		Mass 999999999999999;
		Health 99999;
	}
	States
	{
		Spawn:
			TRE2 A -1;
			Stop;
	}
}


CLASS VanillaSmallTree : ACTOR { 
	Default {
		
		
		Radius 16;
		Height 56;
		ProjectilePassHeight -16;
		+SHOOTABLE;
		BloodType "TreeBlood";
		+NOBLOODDECALS;
		Mass 999999999999999;
		Health 99999;
		+SOLID;
	}
	States
	{
		Spawn:
			TRE1 A -1;
			Stop;
	}
}
