CLASS TallTorch_Red : RedTorch replaces RedTorch { 
	Default {
		
		height 85;
		radius 10;
		+LOOKALLAROUND;
		-SHOOTABLE;
		+INVULNERABLE;
		+NOBLOOD;
		+GHOST;
		+RANDOMIZE;
		Mass 900000;
		scale .5;
	}
	states
	{
		Vanilla:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("RedTorchVanilla");
			Stop;
			
		Spawn:
			TTRB A 0;
			TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
			MARN A 0 ACS_ExecuteAlways(795, 0, 0, 0, 0);//Check if advanced decorations are disabled.
			TNT1 A 1;
			
		Stay:
			TNT1 A 0 A_CheckSight("Spawn2");
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmall", 58, 0, random (0, 360), 2, - random (70, 110));
			TNT1 A 0 A_SpawnProjectile ("ImBallGettingReady3", 59, 0, random (0, 140), 2, - random (0, 160));
			TTRB AC 2 A_SpawnItem("RedFlare22",0,59);
			Loop;
			
		Spawn2:
			TTRB A 6;
			Goto Stay;
			
	}
}

CLASS TallTorch_Blue : TallTorch_Red replaces BlueTorch { 
	Default {
		
	}
	states
	{
		Vanilla:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("BlueTorchVanilla");
			Stop;
			
		Spawn:
			TTRB A 0;
			TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
			MARN A 0 ACS_ExecuteAlways(795, 0, 0, 0, 0);//Check if advanced decorations are disabled.
			TNT1 A 1;
			
		Stay:
			TNT1 A 0 A_CheckSight("Spawn2");
			
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsBlue", 58, 0, random (0, 360), 2, - random (70, 110));
			TNT1 A 0 A_SpawnProjectile ("BallGettingReadyBlue", 59, 0, random (0, 140), 2, - random (0, 160));
			TTRB AC 2 A_SpawnItem("BlueFlare22",0,59);
			Loop;
			
		Spawn2:
			TTRB A 6;
			Goto Stay;
			
	}
}

CLASS TallTorch_Green : TallTorch_Red replaces GreenTorch { 
	Default {
		
	}
	states
	{
		Vanilla:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("GreenTorchVanilla");
			Stop;
			
		Spawn:
			TTRB A 0;
			TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
			MARN A 0 ACS_ExecuteAlways(795, 0, 0, 0, 0);//Check if advanced decorations are disabled.
			TNT1 A 1;
			
		Stay:
			TNT1 A 0 A_CheckSight("Spawn2");
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsGreen", 58, 0, random (0, 360), 2, - random (70, 110));
			TNT1 A 0 A_SpawnProjectile ("BallGettingReadyGreen", 59, 0, random (0, 140), 2, - random (0, 160));
			TTRB AC 2 A_SpawnItem("GreenFlare22",0,59);
			Loop;
			
		Spawn2:
			TTRB A 6;
			Goto Stay;
			
	}
}

CLASS ShortTorch_Blue : ShortBlueTorch replaces ShortBlueTorch { 
	Default {
		
		+LOOKALLAROUND;
		-SHOOTABLE;
		+INVULNERABLE;
		+NOBLOOD;
		+GHOST;
		+RANDOMIZE;
		Mass 900000;
		height 80;
		radius 8;
		scale .4;
	}
	states
	{
		Vanilla:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("ShortBlueTorchVanilla");
			Stop;
			
		Spawn:
			TTRB A 0;
			TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
			MARN A 0 ACS_ExecuteAlways(795, 0, 0, 0, 0);//Check if advanced decorations are disabled.
			TNT1 A 1;
			
		Stay:
			TNT1 A 0 A_CheckSight("Spawn2");
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsBlue", 30, 0, random (0, 360), 2, - random (70, 110));
			TNT1 A 0 A_SpawnProjectile ("BallGettingReadyBlue", 30, 0, random (0, 140), 2, - random (0, 160));
			STRB AA 2 A_SpawnItem("BlueFlare22",0,30);
			Loop;
			
		Spawn2:
			STRB A 6;
			Goto Stay;
	}
}

CLASS ShortTorch_Red : ShortTorch_Blue replaces ShortRedTorch { 
	Default {
		
	}
	states
	{
		Vanilla:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("ShortRedTorchVanilla");
			Stop;
			
		Spawn:
			TTRB A 0;
			TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
			TNT1 A 1;
		Stay:
			TNT1 A 0 A_CheckSight("Spawn2");
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmall", 30, 0, random (0, 360), 2, - random (70, 110));
			TNT1 A 0 A_SpawnProjectile ("ImBallGettingReady3", 30, 0, random (0, 140), 2, - random (0, 160));
			STRB AA 2 A_SpawnItem("RedFlare22",0,30);
		Loop;
			
		Spawn2:
			STRB A 6;
			Goto Stay;
	}
}

CLASS ShortTorch_Green : ShortTorch_Blue replaces ShortGreenTorch { 
	Default {
		
	}
	states
	{
		Vanilla:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("ShortGreenTorchVanilla");
			Stop;
			
		Spawn:
			TTRB A 0;
			TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
			MARN A 0 ACS_ExecuteAlways(795, 0, 0, 0, 0);//Check if advanced decorations are disabled.
			TNT1 A 1;
			
		Stay:
			TNT1 A 0 A_CheckSight("Spawn2");
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsGreen", 30, 0, random (0, 360), 2, - random (70, 110));
			TNT1 A 0 A_SpawnProjectile ("BallGettingReadyGreen", 30, 0, random (0, 140), 2, - random (0, 160));
			STRB AA 2 A_SpawnItem("GreenFlare22",0,30);
			Loop;
			
		Spawn2:
			STRB A 5;
			Goto Spawn;
	}
}


CLASS Candelabra1 : Candelabra replaces Candelabra { 
	Default {
		
		+LOOKALLAROUND;
		+INVULNERABLE;
		+NOBLOOD;
		+FORCEYBILLBOARD;
		+GHOST;
		+RANDOMIZE;
		Mass 900000;
		scale 0.7;
	}
	states
	{
		Vanilla:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("CandelabraVanilla");
			Stop;
			
		Spawn:
			TTRB A 0;
			MARN A 0 ACS_ExecuteAlways(795, 0, 0, 0, 0);//Check if advanced decorations are disabled.
			TNT1 A 1;
			
		Stay:
			TNT1 A 0 A_CheckSight("Spawn2");
			TNT1 A 0 bright A_SpawnItem("YellowFlare22",0,61);
			CBRA CC 1 bright;
			TNT1 A 0 bright A_SpawnItem("YellowFlare22",0,61);
			CBRA BC 1 bright;
			TNT1 A 0 bright A_SpawnItem("YellowFlare22",0,61);
			CBRA BC 1 bright;
			TNT1 A 0 bright A_SpawnItem("YellowFlare22",0,61);
			CBRA BB 1 bright;
			Loop;
		Spawn2:
			CBRA C 7 bright;
			Goto Stay;
	}
}

CLASS Candlestick1 : Candlestick replaces Candlestick { 
	Default {
		
		+LOOKALLAROUND;
		+RANDOMIZE;
		scale .7;
	}
	states
	{
		Vanilla:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("CandleVanilla");
			Stop;
			
		Spawn:
			TTRB A 0;
			MARN A 0 ACS_ExecuteAlways(795, 0, 0, 0, 0);//Check if advanced decorations are disabled.
			TNT1 A 1;
			
		Stay:
			TNT1 A 0 A_CheckSight("Spawn2");
			TNT1 A 0 bright A_SpawnItem("YellowFlareSmall22Long",0,16);
			CAND CCCB 1 bright;
			TNT1 A 0 bright A_SpawnItem("YellowFlareSmall22Long",0,16);
			CAND BCBB 1 bright;
			Loop;
		Spawn2:
			CAND C 5;
			Goto Stay;
	}
}

CLASS BurningBarrel1 : ACTOR replaces BurningBarrel { 
	Default {
		
		+LOOKALLAROUND;
		+SHOOTABLE;
		+NOBLOOD;
		+GHOST;
		+NOTARGET;
		+FRIENDLY;
		-BOSS;
		+RANDOMIZE;
		Radius 16;
		+SOLID;
		height 40;
		Health 30;
		DamageFactor "kick", 5.0;
		DamageFactor "SuperPunches", 5.0;
		Damagefactor "SuperKick", 5.0;
		Damagefactor "punch", 5.0;
	}
	states
	{
		Vanilla:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_SpawnItem("BurningBarrelVanilla");
			Stop;
			
		Spawn:
			TTRB A 0;
			TNT1 A 0 A_Playsound("BDFireplace", 1, 1, 1);
			MARN A 0 ACS_ExecuteAlways(795, 0, 0, 0, 0);//Check if advanced decorations are disabled.
			TNT1 A 1;
			
		Stay:
			TNT1 A 0 A_CheckSight("Spawn2");
			TNT1 A 0 bright A_SpawnProjectile ("MediumBlackSmoke", 38, 0, random (40, 180), 2, - random (60, 120));
			TNT1 A 0 bright A_SpawnProjectile ("RealFlameTrailsSmallLong", 38, 0, random (40, 180), 2, - random (50, 130));
			TNT1 A 0 A_SpawnProjectile ("ImBallGettingReady2", 35, 0, random (0, 140), 2, - random (0, 160));
			BURB AAA 1 bright A_SpawnItem("RedFlare3",0,42);
			
			Loop;
			
		Spawn2:
			BURB A 10;
			Goto Stay;
			
		Pain.Kick:
		Death.punch:
		Death.Kick:
		Death.SuperKick:
		Death.SuperPunches:
			TNT1 A 0 A_Pain();
			TNT1 A 0 A_StopSound(1);
			TNT1 A 1 A_FaceTarget();
			TNT1 A 0 A_NoBlocking();
			TNT1 AAA 0 A_SpawnProjectile ("FlyingBurningFuel", 24, 0, random (150, 210), 2, - random (0, 40));
			TNT1 AA 0 A_SpawnProjectile ("FlyingBurningFuel2", 24, 0, random (150, 210), 2, - random (0, 40));
			TNT1 AA 0 A_SpawnProjectile ("FlyingBurningFuel3", 24, 0, random (150, 210), 2, - random (0, 40));
			BARK DE 3;
			BARK F -1;
			Stop;
			
		Death.Explosive_Impact:
			TNT1 A 0 A_NoBlocking();
			TNT1 A 0 A_StopSound(1);
			TNT1 AAA 0 A_SpawnProjectile ("FlyingBurningFuel", 24, 0, random (0, 360), 2, - random (30, 80));
			TNT1 AA 0 A_SpawnProjectile ("FlyingBurningFuel2", 24, 0, random (0, 360), 2, - random (30, 80));
			TNT1 AA 0 A_SpawnProjectile ("FlyingBurningFuel3", 24, 0, random (0, 360), 2,  - random (30, 80));
			TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -15);
			TNT1 A 0 A_SpawnItemEx ("DetectFloorCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("DetectCeilCrater",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_SpawnItemEx ("ExplosionFlareSpawner",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
			TNT1 A 0 A_Explode(160,200);
			TNT1 AAAAAA 0 A_SpawnProjectile ("SmallExplosionSpawner", 20, 0, random (0, 360), 2, - random (0, 180));
			TNT1 AAAAAAA 0 A_SpawnProjectile ("ExplosionFlames", 0, 0, random (0, 360), 2, random (0, 360));
			TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAA 0 A_SpawnProjectile ("ExplosionParticle2", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAAAAA 0 A_SpawnProjectile ("ExplosionParticle2", 0, 0, random (0, 360), 2, random (0, 180));
			TNT1 AAA 0 A_SpawnProjectile ("BarrelShrapnel1", 25, 0, random (0, 360), 2, - random (30, 160));
			TNT1 AAA 0 A_SpawnProjectile ("BarrelShrapnel2", 15, 0, random (0, 360), 2, - random (30, 160));
			TNT1 AAA 0 A_SpawnProjectile ("BarrelShrapnel3", 5, 0, random (0, 360), 2, - random (30, 160));
			TNT1 AAA 0 A_SpawnProjectile ("BarrelShrapnel4", 5, 0, random (0, 360), 2, - random (30, 160));
			tnt1 a 0
			{
				a_setscale(3.0);
				a_setrenderstyle(0.12, STYLE_add);
				
			}
			SHWK ACEGIKMOQ 1 A_FadeOut(0.01);
		Stop;
		
		
	}
}


CLASS BurningBarrelDamage : ACTOR { 
	Default {
		
		+NOTARGET;
		Radius 0;
		Height 0;
		DamageType "Fire";
		+NOGRAVITY;
		+NOTELEPORT;
		+NODAMAGETHRUST;
		+THRUGHOST;
		+NORADIUSDMG;
		+NOEXTREMEDEATH;
		+FORCERADIUSDMG;
		-BLOODSPLATTER;
		+BLOODLESSIMPACT;
		PROJECTILE;
		+DEHEXPLOSION;
		+ACTIVATEMCROSS;
		+NOTARGET;
	}
	States
	{
		Spawn:
			TNT1 A 0;
			TNT1 AA 5 A_Explode(10,5);
			Stop;
	}
}








CLASS TorchFlare : ACTOR { 
	Default {
		
		+NOINTERACTION;
		+NOGRAVITY;
		+CLIENTSIDEONLY;
		+FORCEXYBILLBOARD;
		renderstyle "Add";
		radius 1;
		height 1;
		alpha 0.4;
	}
}

CLASS RedTF : TorchFlare { 
	Default {
		
	}
	states
	{
		Spawn:
		Spawn:
			TNT1 A 0;
			TNT1 A 0 A_Jump(128,2);
			FLAR A 2 bright;
			stop;
			TNT1 A 0;
			FLAR B 2 bright;
			stop;
			Stop;
	}
}









CLASS RedTorchVanilla : ACTOR { 
	Default {
		
		
		Radius 16;
		Height 68;
		ProjectilePassHeight -16;
		+SOLID;
	}
	States
	{
		Spawn:
			TRED ABCD 2 BRIGHT;
			Loop;
	}
}


CLASS BlueTorchVanilla : ACTOR { 
	Default {
		
		
		Radius 16;
		Height 68;
		ProjectilePassHeight -16;
		+SOLID;
	}
	States
	{
		Spawn:
			TBLU ABCD 2 BRIGHT;
			Loop;
	}
}


CLASS GreenTorchVanilla : ACTOR { 
	Default {
		
		
		Radius 16;
		Height 68;
		ProjectilePassHeight -16;
		+SOLID;
	}
	States
	{
		Spawn:
			TGRN ABCD 2 BRIGHT;
			Loop;
	}
}



CLASS ShortBlueTorchVanilla : ACTOR { 
	Default {
		
		
		Radius 16;
		Height 37;
		ProjectilePassHeight -16;
		+SOLID;
	}
	States
	{
		Spawn:
			SMBT ABCD 2 BRIGHT;
			Loop;
	}
}

CLASS ShortRedTorchVanilla : ACTOR { 
	Default {
		
		
		Radius 16;
		Height 37;
		ProjectilePassHeight -16;
		+SOLID;
	}
	States
	{
		Spawn:
			SMRT ABCD 2 BRIGHT;
			Loop;
	}
}


CLASS ShortGreenTorchVanilla : ACTOR { 
	Default {
		
		
		Radius 16;
		Height 37;
		ProjectilePassHeight -16;
		+SOLID;
	}
	States
	{
		Spawn:
			SMGT ABCD 2 BRIGHT;
			Loop;
	}
}

CLASS CandelabraVanilla : ACTOR { 
	Default {
		
		
		Radius 16;
		Height 60;
		ProjectilePassHeight -16;
		+SOLID;
	}
	States
	{
		Spawn:
			CBRA A -1 BRIGHT;
			Stop;
	}
}

CLASS CandleVanilla : ACTOR { 
	Default {
		
		
		Radius 20;
		Height 14;
		ProjectilePassHeight -16;
	}
	States
	{
		Spawn:
			CAND A -1 BRIGHT;
			Stop;
	}
}


CLASS BurningBarrelVanilla : ACTOR { 
	Default {
		
		Radius 16;
		Height 32;
		ProjectilePassHeight -16;
		+SOLID;
	}
	States
	{
		Spawn:
			FCAN ABC 2 BRIGHT;
			Loop;
	}
}
