class doomb_proto_torch_tall : doomb_decoration_base  abstract
{
Default
{
	ProjectilePassHeight -16;
	height 85;
	radius 10;
	+LOOKALLAROUND;
	-SHOOTABLE;
	+INVULNERABLE;
	+NOBLOOD;
	+GHOST;
	+RANDOMIZE;
	+DONTTHRUST
	Mass 900000;
	scale .5;
}

}

CLASS TallTorch_Red : doomb_proto_torch_tall replaces RedTorch
{ 
states
{
	Spawn:
		TTRB A 0;
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
	Stay:
		TNT1 A 0 bright doomb_show_effect("RealFlameTrailsSmall", (0, 0, 58), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		TTRB AC 2 A_SpawnItem("RedFlare22",0,59);
	Loop;
}

}

CLASS TallTorch_Blue : doomb_proto_torch_tall replaces BlueTorch
{ 
states
{
	Spawn:
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
	Stay:
		TNT1 A 0 bright doomb_show_effect("RealFlameTrailsBlue", (0, 0, 58), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		TTRB AC 2 A_SpawnItem("BlueFlare22",0,59);
	Loop;
}
}

CLASS TallTorch_Green : doomb_proto_torch_tall replaces GreenTorch
{ 
states
{
	Spawn:
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
	Stay:
		TNT1 A 0 bright doomb_show_effect("RealFlameTrailsGreen", (0, 0, 58), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		TTRB AC 2 A_SpawnItem("GreenFlare22",0,59);
	Loop;
}
}


class doomb_proto_torch_short : doomb_proto_torch_tall  abstract
{
Default
{
	height 80;
	radius 10;
	scale .4;
}

}

CLASS ShortTorch_Blue : doomb_proto_torch_short replaces ShortBlueTorch { 
states
{
	Spawn:
		TTRB A 0;
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
	Stay:
		TNT1 A 0 bright doomb_show_effect("RealFlameTrailsBlue", (0, 0, 30), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		STRB AA 2 A_SpawnItem("BlueFlare22",0,30);
	Loop;
}
}

CLASS ShortTorch_Red : doomb_proto_torch_short replaces ShortRedTorch { 
states
{
	Spawn:
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
	Stay:
		TNT1 A 0 bright doomb_show_effect("RealFlameTrailsSmall", (0, 0, 30), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		STRB AA 2 A_SpawnItem("RedFlare22",0,30);
	Loop;
}
}

CLASS ShortTorch_Green : doomb_proto_torch_short replaces ShortGreenTorch { 
states
{
	Spawn:
		TNT1 A 0 A_Playsound("BDFireplace2", 1, 1, 1);
	Stay:
		TNT1 A 0 bright doomb_show_effect("RealFlameTrailsGreen", (0, 0, 30), (frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0.5, 1) ) );
		STRB AA 2 A_SpawnItem("GreenFlare22",0,30);
	Loop;
}
}








CLASS Candelabra1 : Candelabra replaces Candelabra { 
Default {
	+LOOKALLAROUND;
	+INVULNERABLE;
	+NOBLOOD;
	+FORCEYBILLBOARD;
	+GHOST;
	+RANDOMIZE;
	Mass 900000;
	scale 0.7;
}
states
{
	Spawn:
	Stay:
		TNT1 A 0 bright A_SpawnItem("YellowFlare22",0,61);
		CBRA CC 1 bright light("BIGREDTORCH");
		TNT1 A 0 bright A_SpawnItem("YellowFlare22",0,61);
		CBRA BC 1 bright light("BIGREDTORCH");
		TNT1 A 0 bright A_SpawnItem("YellowFlare22",0,61);
		CBRA BC 1 bright light("BIGREDTORCH");
		TNT1 A 0 bright A_SpawnItem("YellowFlare22",0,61);
		CBRA BB 1 bright light("BIGREDTORCH");
	Loop;
}
}

CLASS Candlestick1 : Candlestick replaces Candlestick { 
Default {
	+LOOKALLAROUND;
	+RANDOMIZE;
	scale .7;
}
states
{
	Spawn:
		TNT1 A 1;
		
	Stay:
		TNT1 A 0 bright A_SpawnItem("YellowFlareSmall22Long",0,16);
		CAND CCCB 1 bright light("SMALLREDTORCH");
		TNT1 A 0 bright A_SpawnItem("YellowFlareSmall22Long",0,16);
		CAND BCBB 1 bright light("SMALLREDTORCH");
	Loop;
}
}

CLASS BurningBarrel1 : doomb_decoration_base replaces BurningBarrel { 
Default {
	+LOOKALLAROUND;
	+SHOOTABLE;
	+NOBLOOD;
	+NOTARGET;
	+FRIENDLY;
	+SOLID;
	+RANDOMIZE;
	Radius 16;
	height 40;
	Health 30;
	DamageFactor "kick", 5.0;
	Damagefactor "punch", 5.0;
}
states
{
	Spawn:
		TNT1 A 0 A_Playsound("BDFireplace", 1, 0.4, true);
		TNT1 A 0 bright doomb_show_effect("BigBlackSmoke", (0, 0, 50),velocity:(frandom(-0.3, 0.3), frandom(-0.3, 0.3), frandom(0, 2) ), visual_size: (frandom(0.2, 0.4), 0) );
		TNT1 A 0 bright doomb_show_effect("RealFlameTrailsSmall", (frandom(-2,2), frandom(-2,2), 35), (frandom(-1, 1), frandom(-1, 1), frandom(0.5, 2) ) );
		BURB AAA 1 bright {Spawn("RedFlare", pos + (0, 0, 42));}
	Loop;

	Pain.Kick:
	Death.punch:
	Death.Kick:
		TNT1 A 0 A_Pain();
		TNT1 A 0 A_StopSound(1);
		TNT1 A 1 A_FaceTarget();
		TNT1 A 0 A_NoBlocking();
		TNT1 AAAAAAA 0 A_SpawnProjectile ("FlyingBurningFuel", 24, 0, random (150, 210), 2, - random (0, 40));
		BARK DE 3;
		BARK F -1;
		Stop;
		
	Death.Explosive_Impact:
		TNT1 A 0 A_NoBlocking();
		TNT1 A 0 A_StopSound(1);
		TNT1 AAAAAAAAAA 0 A_SpawnProjectile ("FlyingBurningFuel", 24, 0, random (0, 360), 2, - random (30, 80));
		TNT1 A 0 A_SpawnItem ("BigRicoChet", 0, -15);
		TNT1 A 0 A_SpawnItemEx ("NewfagExplosionFlare",0,0,0,0,0,0,0,SXF_NOCHECKPOSITION,0);
		TNT1 A 0 A_Explode(160,200);
		TNT1 AAAAAA 0
		{
			doomb_show_effect("HeavyExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
			doomb_show_effect("ExplosionSmoke", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 1) ) );
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
			doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ), (frandom(0.9, 1.4), 0) );
		}

		TNT1 AAAAAAA 0 doomb_show_effect("ExplosionFlames", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(-0.5, 0.5) ) );
		TNT1 AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA 0 doomb_show_effect("ExplosionParticle2", (0, 0, 0), (frandom(-0.5, 0.5), frandom(-0.5, 0.5), frandom(0.5, 1) ) );
		TNT1 AAA 0 A_SpawnProjectile ("BarrelShrapnel1", 25, 0, random (0, 360), 2, - random (30, 160));
		TNT1 AAA 0 A_SpawnProjectile ("BarrelShrapnel2", 15, 0, random (0, 360), 2, - random (30, 160));
		TNT1 AAA 0 A_SpawnProjectile ("BarrelShrapnel3", 5, 0, random (0, 360), 2, - random (30, 160));
		TNT1 AAA 0 A_SpawnProjectile ("BarrelShrapnel4", 5, 0, random (0, 360), 2, - random (30, 160));
		tnt1 a 0
		{
			a_setscale(3.0);
			a_setrenderstyle(0.12, STYLE_add);
			
		}
		SHWK ACEGIKMOQ 1 A_FadeOut(0.01);
	Stop;
	
	
}
}











CLASS TorchFlare : ACTOR { 
Default {
	
	+NOINTERACTION;
	+NOGRAVITY;
	+CLIENTSIDEONLY;
	+FORCEXYBILLBOARD;
	renderstyle "Add";
	radius 1;
	height 1;
	alpha 0.4;
}
}

CLASS RedTF : TorchFlare { 
states
{
	Spawn:
	Spawn:
		TNT1 A 0;
		TNT1 A 0 A_Jump(128,2);
		FLAR A 2 bright;
		stop;
		TNT1 A 0;
		FLAR B 2 bright;
		stop;
}
}